### ISSUE TITLE
Async Commands not fully blocked?

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#1005]
See: https://github.com/PaperMC/Paper/issues/1004

This shouldn't of been possible, as I had added code to block this and force it sync. So this path must be circumventing my check. need to close this one too.

Relevant stack triggered on async:
[04:18:55] [Async Chat Thread - #0/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[04:18:55] [Async Chat Thread - #0/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677)
[04:18:55] [Async Chat Thread - #0/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:363)
[04:18:55] [Async Chat Thread - #0/WARN]: 	at net.aufdemrand.denizen.scripts.commands.server.ExecuteCommand.execute(ExecuteCommand.java:122)
[04:18:55] [Async Chat Thread - #0/WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:252)

**Comment by aikar** [comment]
Hmm this path is protected, some how that persons async catcher was disabled. hacky plugin must of turned it off.
