### ISSUE TITLE
Problem With PaperSpigot 1.8.8

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1033]
Hi i'm getting this error with spam in my console:

[18:42:43 ERROR]: stopTiming called async for anti-xray - obfuscate
[18:42:43 WARN]: java.lang.Throwable
[18:42:43 WARN]:        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[18:42:43 WARN]:        at org.spigotmc.AntiXray.obfuscateSync(AntiXray.java:103)
[18:42:43 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:22)
[18:42:43 WARN]:        at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.sendChunk(BukkitQueue18R3.java:508)
[18:42:43 WARN]:        at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.sendChunk(BukkitQueue18R3.java:461)
[18:42:43 WARN]:        at com.boydti.fawe.example.NMSRelighter$1.run(NMSRelighter.java:325)
[18:42:43 WARN]:        at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[18:42:43 WARN]:        at com.boydti.fawe.example.NMSRelighter.sendChunks(NMSRelighter.java:331)
[18:42:43 WARN]:        at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:297)
[18:42:43 WARN]:        at com.boydti.fawe.example.NMSMappedFaweQueue$1.run(NMSMappedFaweQueue.java:47)
[18:42:43 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[18:42:43 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:42:43 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[18:42:43 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:42:43 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:42:43 WARN]:        at java.lang.Thread.run(Thread.java:748)

i already seen in paper.yml if use-async-lighting is set to false, and by default it's already set, what i can do to fix this problem?

Thanks, i wish to get an answer to resolve my problem asap, it's really important for me! Gratz

**Comment by electronicboy** [comment]
1. We don't support outdated versions in any capacity
2. You have a plugin (FAWE) which is doing stuff async which isn't designed to be called async

**Comment by ghost** [comment]
How i can resolve this problem?

**Comment by mikroskeem** [comment]
Report to https://github.com/boy0001/FastAsyncWorldedit/issues ?
