### ISSUE TITLE
git-Paper-509 "Silently" catching entity tracking error.

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#104]
```
[13:54:20] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_9_R1.ReportedException: Adding entity to track
    at net.minecraft.server.v1_9_R1.EntityTracker.addEntity(EntityTracker.java:142) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.EntityTracker.track(EntityTracker.java:81) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.WorldManager.a(WorldManager.java:18) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.World.b(World.java:1032) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.WorldServer.b(WorldServer.java:1154) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.World.addEntity(World.java:1025) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:483) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:479) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:490) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.MobSpawnerAbstract.c(MobSpawnerAbstract.java:111) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.TileEntityMobSpawner.c(SourceFile:61) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1509) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:630) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:847) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-509]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-509]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
    at net.minecraft.server.v1_9_R1.EntityTracker.addEntity(EntityTracker.java:109) ~[patched_1.9.jar:git-Paper-509]
    ... 17 more
```

**Comment by zachbr** [comment]
Going to assume you're running dynmap. Don't. 
https://github.com/webbukkit/dynmap/issues/1916

**Comment by andris155** [comment]
I don't use Dynmap plugin.

**Comment by zachbr** [comment]
Does this still occur on latest?

**Comment by andris155** [comment]
Today not writed this error.

**Comment by zachbr** [comment]
Let us know if it comes back please
