### ISSUE TITLE
NPE when calling Inventory#getLocation for an enderchest

### ISSUE THREAD

**Issue by RoboMWM** [PaperMC/Paper#1041]
My understanding is that it should return null if it doesn't support the getLocation call, but not throw an NPE itself...

```
[17:19:32] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to PrettySimpleShop v1.0
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.12.2.jar:git-Paper-1343]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:786) ~[patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.EntityPlayer.openContainer(EntityPlayer.java:829) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:195) ~[patched_1.12.2.jar:git-Paper-1343]
	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$8.onRightClick(SlimefunSetup.java:572) ~[?:?]
	at me.mrCookieSlime.Slimefun.listeners.ItemListener.onRightClick(ItemListener.java:180) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor469.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1343]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1343]
	at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.ItemUseListener.onRightClick(ItemUseListener.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor303.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1343]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:460) ~[patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991) ~[patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1343]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1343]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1343]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_12_R1.InventoryEnderChest.getLocation(InventoryEnderChest.java:18) ~[patched_1.12.2.jar:git-Paper-1343]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.getLocation(CraftInventory.java:504) ~[patched_1.12.2.jar:git-Paper-1343]
	at com.robomwm.prettysimpleshop.shop.ShopListener.onOpenInventory(ShopListener.java:173) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.2.jar:git-Paper-1343]
	... 36 more
```
### Actions to reproduce (if known):
```java
private void onOpenInventory(InventoryOpenEvent event)
    {
        if (event.getInventory().getLocation() == null)
            return;
```

### Paper build number: 
This server is running Paper version git-Paper-1343 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by RoboMWM** [comment]
Hmm, looking at that stacktrace though, could be a slimefun issue... maybe? Since it's strangely not happening for me as I open an ender chest. Reported too soon, whoops.

**Comment by RoboMWM** [comment]
Hmm, seems to be because of `player#openInventory(player#getEnderChest)` https://github.com/TheBusyBiscuit/Slimefun4/blob/5dc57af7732f4131565166f0e1ebd6c917db7849/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L573

But... then shouldn't `getLocation()` still be something that merely returns null?

**Comment by electronicboy** [comment]
Not fond of returning null through an API that generally returns an object where possible, so followed PlayerInventory of returning the players location in such cases

**Comment by RoboMWM** [comment]
Hmm... then I'm not sure how to distinguish someone opening a chest/enderchest in the world vs. via a plugin/item then... at least not in InventoryOpenEvent... and especially not on close.

**Comment by RoboMWM** [comment]
Behavior modified to return null as per https://github.com/PaperMC/Paper/commit/ddc8a0ae88add57bd0b5fa32ba9c0a3450db92f8

Relevant discussion:
https://korobi.io/network/spigot/channel/paper/logs/2018/03/10/#L662
and decision
https://korobi.io/network/spigot/channel/paper/logs/2018/03/10/#L731
