### ISSUE TITLE
More stale cereal

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#10475]
### Expected behavior

Item serialization to yaml should work

### Observed/Actual behavior

java.lang.IllegalStateException: List must have contents; List must have contents
        at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:275) ~[datafixerupper-7.0.14.jar:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1719) ~[paper-1.20.5.jar:git-Paper-"37b3891"]
        at org.bukkit.craftbukkit.inventory.CraftMetaPotion.serialize(CraftMetaPotion.java:332) ~[paper-1.20.5.jar:git-Paper-"37b3891"]
        at org.bukkit.craftbukkit.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1609) ~[paper-1.20.5.jar:git-Paper-"37b3891"]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:50) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:111) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:174) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:331) ~[snakeyaml-2.2.jar:?]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:52) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]

### Steps/models to reproduce

Try to save plugin created potion item with no effects i guess?

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"37b3891" (MC: 1.20.5) (Implementing API version 1.20.5-R0.1-SNAPSHOT) (Git: 37b3891)
You are running the latest version
Previous version: git-Paper-"6e31f38" (MC: 1.20.5)

**Comment by lynxplay** [comment]
Please provide example code on how to generate this item stack.
This is a issue-rich time for paper, creating replication code would be great to get such issues sorted out quickly.

**Comment by lynxplay** [comment]
Then provide the yaml file failing (I presume this is another victim of "storing Itemstacks in Yamlconfiguration is dumb")

**Comment by lynxplay** [comment]
And how are you getting this item stack into memory???
You must have *some* clue where this is coming from...

**Comment by lynxplay** [comment]
Okay perfect, great news for you then, this is already fixed in https://github.com/PaperMC/Paper/issues/10473.

Update and try again, lemme know if I can close this on latest.
