### ISSUE TITLE
git-Paper-521 java.lang.NullPointerException (Server start)

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#105]
```
[17:56:16] [Server thread/WARN]: java.lang.NullPointerException
[17:56:16] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.Village.a(Village.java:394)
[17:56:16] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PersistentVillage.a(SourceFile:215)
[17:56:16] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PersistentCollection.get(PersistentCollection.java:51)
[17:56:16] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.WorldServer.b(WorldServer.java:72)
[17:56:16] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:262)
[17:56:16] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273)
[17:56:16] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:564)
[17:56:16] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
```

**Comment by mibby** [comment]
https://github.com/PaperMC/Paper/issues/95

**Comment by aikar** [comment]
fixed in latest paper

**Comment by andris155** [comment]
Not fixed in build 533

**Comment by andris155** [comment]
New error:

```
[11:26:30] [Server thread/WARN]: java.lang.NullPointerException
[11:26:30] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.Village.a(Village.java:394)
[11:26:30] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PersistentVillage.a(PersistentVillage.java:241)
[11:26:30] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PersistentCollection.get(PersistentCollection.java:51)
[11:26:30] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.WorldServer.b(WorldServer.java:72)
[11:26:30] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.createWorld(CraftServer.java:883)
[11:26:30] [Server thread/WARN]:    at org.bukkit.Bukkit.createWorld(Bukkit.java:485)
[11:26:30] [Server thread/WARN]:    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[11:26:30] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[11:26:30] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)
[11:26:30] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)
[11:26:30] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725)
[11:26:30] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310)
[11:26:30] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[11:26:30] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
[11:26:30] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[11:26:30] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:318)
[11:26:30] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:278)
[11:26:30] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:405)
[11:26:30] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:370)
[11:26:30] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:325)
[11:26:30] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273)
[11:26:30] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:564)
[11:26:30] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
```

**Comment by zachbr** [comment]
@andris155 Please update to Build-541 or newer when you get a chance, then let us know if this issue continues.

**Comment by andris155** [comment]
Fixed, thanks!
