### ISSUE TITLE
NPE when a plugin throws a null event the logger tries to get the event name which causes an uncaught exception

### ISSUE THREAD

**Issue by Narimm** [PaperMC/Paper#1087]
# Incompatibility (Bug)

### What behaviour is expected:
Catch the NPE
### What behaviour is observed:
Plugin failed to load 

### Plugin list:
...extensive....Can provide if really needed.

### Paper build number:
1387

# Crash, Stacktrace
```
Could not pass event ShowCaseItemSpawnEvent to ShowCaseStandalone v789
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1387]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1387]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1387]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1387]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1387]
        at com.kellerkindt.scs.ShowCaseStandalone.callShowCaseEvent(ShowCaseStandalone.java:522) [ShowCaseStandalone.jar:?]
        at com.kellerkindt.scs.internals.SimpleShopHandler.show(SimpleShopHandler.java:724) [ShowCaseStandalone.jar:?]
        at com.kellerkindt.scs.internals.SimpleShopHandler.showShopsFor(SimpleShopHandler.java:420) [ShowCaseStandalone.jar:?]
        at com.kellerkindt.scs.listeners.WorldListener.<init>(WorldListener.java:40) [ShowCaseStandalone.jar:?]
        at com.kellerkindt.scs.ShowCaseStandalone.onEnable(ShowCaseStandalone.java:233) [ShowCaseStandalone.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1387]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1387]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1387]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1387]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1387]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1387]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1387]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1387]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1387]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1387]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: Cannot drop AIR.
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1387]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItem(CraftWorld.java:337) ~[patched_1.12.2.jar:git-Paper-1387]
        at com.kellerkindt.scs.internals.SimpleShopHandler.onShowCaseItemSpawnEvent(SimpleShopHandler.java:757) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor680.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1387]
        ... 20 more
```

### Actions to reproduce (if known):
Simply try and load the plugin.   
### Paper build number:
1387

# Suggestion
Just catch the NPE the plugin loader should proceed as the NPE is just in a logging statement I think...but then I only have decompile jars to check against.

**Comment by electronicboy** [comment]
This stack report has nothing to do with an NPE, and is 100% down to a plugin attempting to do something stupid, i.e. drop AIR. the "null" in the report is because there is no message attached to the EventExecutor, ever.

**Comment by Narimm** [comment]
I am aware the plugin was doing something dumb I have dealt with that separately.   I just figured if a message was null ...there isnt much point returning it ... It may be far better off returning the name of the plugin causing the issue if possible and suppress the stacktrace

**Comment by Narimm** [comment]
Or state no message was attached rather than null

**Comment by electronicboy** [comment]
Yes, there is a point in returning it; Just because bukkit doesn't shove any message in there doesn't make it any less valid for it to be thrown up the stack, EventException is an exception which is used to indicate a plugins event executor threw an exception, this allows for it to be handled properly further up, and for plugins listening on the ServerExceptionEvent to know what the exception is.

The name of the plugin who's event executor was called is printed when bukkit catches and handles the exception further up the stack. suppressing the exception would be stupid and remove a lot of information which can lead to debugging issues.

**Comment by Narimm** [comment]
No problem
