### ISSUE TITLE
TerminalConsoleAppender exception seems to block chat messages for a period of time

### ISSUE THREAD

**Issue by sudofox** [PaperMC/Paper#1093]
###  Timings or Profile link:

https://timings.aikar.co/?id=7f60d61e4d4c4783b08a45ce003fac88

### Description of issue:

We were all briefly unable to send chat messages. After a moment, around the time I went to switch back to the screen session I was running PaperSpigot inside to see what was going on, messages went through all at once, and I was greeted with a stacktrace in the middle of our missing messages.

I do not believe any chat messages were duplicated, just resent by the players when they did not seem to show up.

### bukkit.yml, spigot.yml, paper.yml, server.properties

https://gist.github.com/sudofox/03e33b6e980278efba8198039f228997

### Paper build number:

git-Paper-1381 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

# Crash, Stacktrace

### Link/paste of stack trace

```
[18:41:25 INFO]: <User1> User2 is settling at Rocky Point - a new community on the JUBILEE LINE.
[18:41:33 INFO]: <User2> Yessiree
[18:41:56 INFO]: <Sudofox> I will be returning to my adventures in writing a Minecraft region file parser
[18:42:12 INFO]: <User1> I have NO idea what that is but good luck with it!
[18:42:16 INFO]: <User2> Same
[18:42:20 INFO]: <User2> Have fun
> 
[18:42:43 INFO]: <User1> Something to give him even greater powers!
[18:42:33 INFO]: <User2> I can't speak?
[18:42:29 INFO]: <Sudofox> ty
[18:42:25 INFO]: <Sudofox> ty
[18:42:24 INFO]: <User2> Have fun
> [18:42:32 INFO]: <User1> Something to give him even greater powers!
> 2018-04-20 18:42:47,857 Async Chat Thread - #25 ERROR An exception occurred processing Appender TerminalConsole java.lang.IllegalStateException
        at org.jline.reader.impl.LineReaderImpl.callWidget(LineReaderImpl.java:651)
        at net.minecrell.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:267)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
        at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1297)
        at com.destroystokyo.paper.console.TerminalConsoleCommandSender.sendRawMessage(TerminalConsoleCommandSender.java:14)
        at org.bukkit.craftbukkit.v1_12_R1.command.CraftConsoleCommandSender.sendMessage(CraftConsoleCommandSender.java:22)
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1440)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1302)
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


[18:42:51 INFO]: <User1> hmm
[18:42:52 INFO]: <Sudofox> np
[18:42:57 INFO]: <User2> Omg same
[18:43:11 INFO]: <User2> Oh there we go
[18:43:16 INFO]: <User2> lol
```

In my game, the messages were not in the same order. The `>` and newlines oddly placed may have had something to do with me hitting enter a few times to cancel out the scrolling up I had done in my screen session.

### Plugin list:
ClearLag, CoreProtect, dynmap, WorldEdit

### Actions to reproduce (if known):

Unknown, but I wonder if it has to do with the fact that I had scrolled up in the screen session and left it that way? Chat messages were working fine for a while, however.

I have not experienced this issue before.

**Comment by aikar** [comment]
scrolling inside of screen does cause some kind of pause operation in some circumstances. I'm not really sure the details on that though. I'm thinking it's relating to that, and when you reattached to find out what was wrong, you unscrolled it.
