### ISSUE TITLE
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer cannot be cast to com.massivecraft.factions.entity.Faction 

### ISSUE THREAD

**Issue by GAME4PLAY** [PaperMC/Paper#1113]
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer cannot be cast to com.massivecraft.factions.entity.Faction
[20:22:21 WARN]:        at com.ngxdev.faction.scoreboard.adapters.FactionsV2.getRelation(FactionsV2.java:20)
[20:22:21 WARN]:        at com.ngxdev.faction.nametags.FactionNameManager.run(FactionNameManager.java:28)
[20:22:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[20:22:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[20:22:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[20:22:21 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[20:22:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[20:22:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[20:22:21 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by GAME4PLAY** [comment]
Guys im using the same fac and massivecore version btw 
How can i fix it plz :=) 
and tnx

**Comment by electronicboy** [comment]
Speak to the plugin author, that's a bug on their side.

**Comment by GAME4PLAY** [comment]
Oh okay tnx anyway
