### ISSUE TITLE
/dynmap reload fails to access its own jar file

### ISSUE THREAD

**Issue by RoboMWM** [PaperMC/Paper#1120]
Suspected that https://github.com/PaperMC/Paper/commit/19dea1a6f7a10ea249488264e264076179f20780#commitcomment-28910391 is the cause.

```
[16:46:20] [Server thread/INFO]: RoboMWM issued server command: /dynmap reload
[16:46:20] [Server thread/INFO]: [dynmap] Disabling dynmap v2.6-SNAPSHOT-Dev201801130005
[16:46:20] [Server thread/INFO]: [dynmap] Unloaded 11 components.
[16:46:20] [Server thread/INFO]: [dynmap] Stopping map renderer...
[16:46:21] [Server thread/INFO]: [dynmap] Disabled
[16:46:21] [Server thread/INFO]: [dynmap] Enabling dynmap v2.6-SNAPSHOT-Dev201801130005
[16:46:21] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader dynmap v2.6-SNAPSHOT-Dev201801130005
[16:46:21] [Server thread/INFO]: [dynmap] Using Bukkit Permissions (superperms) for access control
[16:46:21] [Server thread/INFO]: [dynmap] Web interface permissions only available for online users
[16:46:21] [Server thread/INFO]: [dynmap] Mod Support processing completed
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/normal.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/nether.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/normal-lowres.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/nether-lowres.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/normal-hires.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/nether-hires.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/normal-vlowres.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/nether-vlowres.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/the_end.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/the_end-vlowres.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/the_end-lowres.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/the_end-hires.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/normal-low_boost_hi.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/normal-hi_boost_vhi.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/normal-hi_boost_xhi.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/nether-low_boost_hi.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/nether-hi_boost_vhi.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/nether-hi_boost_xhi.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/the_end-low_boost_hi.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/the_end-hi_boost_vhi.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /templates/the_end-hi_boost_xhi.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /shaders.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /perspectives.txt
[16:46:21] [Server thread/ERROR]: [dynmap] Unable to find resource - /lightings.txt
[16:46:21] [Server thread/INFO]: [dynmap] Web server started on address REDACTED:8123
[16:46:21] [Server thread/INFO]: [dynmap] version 2.6-SNAPSHOT-Dev201801130005 is enabled - core version 2.6-SNAPSHOT-Dev201706101301
[16:46:21] [Server thread/INFO]: [dynmap] World 'firstjoin' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'CreativeParkourMaps' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'flatroom' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'maxiworld' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'mall' disabled
[16:46:21] [Server thread/ERROR]: [dynmap] HDMap 'flat' loaded invalid perspective 'iso_S_90_vlowres' - map disabled
[16:46:21] [Server thread/ERROR]: [dynmap] HDMap 'surface' loaded invalid perspective 'iso_SE_30_vlowres' - map disabled
[16:46:21] [Server thread/ERROR]: [dynmap] HDMap 'cave' loaded invalid perspective 'iso_SE_30_vlowres' - map disabled
[16:46:21] [Server thread/INFO]: [dynmap] Loaded 0 maps of world 'cityworld'.
[16:46:21] [Server thread/ERROR]: [dynmap] HDMap 'flat' loaded invalid perspective 'iso_S_90_vlowres' - map disabled
[16:46:21] [Server thread/ERROR]: [dynmap] HDMap 'surface' loaded invalid perspective 'iso_SE_30_vlowres' - map disabled
[16:46:21] [Server thread/ERROR]: [dynmap] HDMap 'cave' loaded invalid perspective 'iso_SE_30_vlowres' - map disabled
[16:46:21] [Server thread/INFO]: [dynmap] Loaded 0 maps of world 'cyberworld'.
[16:46:21] [Server thread/INFO]: [dynmap] World 'sandbox' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'bam' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'plots' disabled
[16:46:21] [Server thread/ERROR]: [dynmap] HDMap 'flat' loaded invalid perspective 'iso_S_90_vlowres' - map disabled
[16:46:21] [Server thread/ERROR]: [dynmap] HDMap 'surface' loaded invalid perspective 'iso_SE_30_vlowres' - map disabled
[16:46:21] [Server thread/ERROR]: [dynmap] HDMap 'cave' loaded invalid perspective 'iso_SE_30_vlowres' - map disabled
[16:46:21] [Server thread/INFO]: [dynmap] Loaded 0 maps of world 'world'.
[16:46:21] [Server thread/INFO]: [dynmap] World 'world_the_end' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'spawn' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'cityworld_nether' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'dogepvp' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'world_nether' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'wellworld' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'minigames' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'mcware' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'alexproject' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'prison' disabled
[16:46:21] [Server thread/INFO]: [dynmap] World 'SkyWarsArenaWorld' disabled
[16:46:21] [Server thread/INFO]: [dynmap] Enabled
```

After this, reloading any other plugin with plugman also fails (though disable/enable does seem to work okay - though I'm guessing this is caused by dynmap having issues when performing /dynmap reload; i.e. not necessarily due to Paper's commit.)

```
[16:46:29] [Server thread/INFO]: RoboMWM issued server command: /plugman reload MountainDewritoes
[16:46:29] [Server thread/INFO]: [MountainDewritoes] Disabling MountainDewritoes v31.1
[16:46:29] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: zip file closed
[16:46:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[16:46:29] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[16:46:29] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
[16:46:29] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
[16:46:29] [Server thread/WARN]: 	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[16:46:29] [Server thread/WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[16:46:29] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:46:29] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[16:46:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[16:46:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:46:29] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[16:46:29] [Server thread/WARN]: 	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669)
[16:46:29] [Server thread/WARN]: 	at java.util.zip.ZipFile.getEntry(ZipFile.java:309)
[16:46:29] [Server thread/WARN]: 	at java.util.jar.JarFile.getEntry(JarFile.java:240)
[16:46:29] [Server thread/WARN]: 	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[16:46:29] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:46:29] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:46:29] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[16:46:29] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:348)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82)
[16:46:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127)
[16:46:29] [Server thread/WARN]: 	... 22 more
```

### Plugin list:
Will provide if needed.
### Actions to reproduce (if known):
1. Start server with dynmap
2. Perform /dynmap reload

### Paper build number:
This server is running Paper version git-Paper-1416 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
That will be the cause due to the classloader being called, it's a bit of a sticky mess where plugins are calling the plugin manager to disable and then re-enable their plugins; as horrific as that is, plugins still do it.

@aikar is there any specific reason why this is done inside of onDisable as opposed to later on?

**Comment by aikar** [comment]
@electronicboy because that's where the class loader clean up code already existed.

This bug confuses the hell out of me, as reload calls loadPlugin, which creates an entirely new class loader. It shouldn't even be using the old class loader.

I think plugman may be in a weird spot in that they are also manually closing the class loader with reflection. I think we should see if plugman can be improved to not close if its already closed by Paper.

**Comment by electronicboy** [comment]
The issue here is that dynmaps reload command calls disablePlugin, and then enablePlugin upon itself, disable plugin now also closes the classloader, which when it comes to call enablePlugin, is going to have a fun time due to the classloader being closed

One trace does have pluginman in there, that looks like another fun ballgame on the side

**Comment by aikar** [comment]
maybe can solve with some form of boolean closeClassloaders so its only closed on actual /reload.

that should fix it.

**Comment by Drc-DEV** [comment]
I have the same problem, is there any way to fix this yet?
