### ISSUE TITLE
Option to delay Head Conversion Thread TileEntitySkull look-up post start-up.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#1126]
Paper dev 1421 (Spigot 1.12.2)

Would it be possible to implement an option to delay the TileEntitySkull look-up at start-up? I have a handful of plugins that do skin look-up requests post startup. Since they happen to run right after another, I get an AuthenticationException every single time I restart my server due to too many look-up requests. I'm under the belief this may be due to a skull head being loaded inside the spawn chunks since TileEntitySkull being called.

Having an option to delay skull tile profile look-up 30-60 seconds post start-up may help spread out the look-up requests over a longer period of time so the error doesn't occur.
```
[09:00:36] [Craft Scheduler Thread - 9/INFO]: [HeadDatabase] Succesfully loaded 14092 heads!
[09:00:36] [Craft Scheduler Thread - 9/INFO]: [HeadDatabase] Succesfully loaded 12 featured tags!
[09:00:36] [Server thread/INFO]: [Citizens] Loaded 62 NPCs.
[09:00:37] [Head Conversion Thread - 2/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@1eff5096[id=0d6e7f2b-b16e-4e2e-9f47-censoreduuid,name=player,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.12.2.jar:git-Paper-1421]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [patched_1.12.2.jar:git-Paper-1421]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:35) [patched_1.12.2.jar:git-Paper-1421]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [patched_1.12.2.jar:git-Paper-1421]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:28) [patched_1.12.2.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:79) [patched_1.12.2.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:46) [patched_1.12.2.jar:git-Paper-1421]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [patched_1.12.2.jar:git-Paper-1421]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [patched_1.12.2.jar:git-Paper-1421]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [patched_1.12.2.jar:git-Paper-1421]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [patched_1.12.2.jar:git-Paper-1421]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [patched_1.12.2.jar:git-Paper-1421]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [patched_1.12.2.jar:git-Paper-1421]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [patched_1.12.2.jar:git-Paper-1421]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [patched_1.12.2.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:206) [patched_1.12.2.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:203) [patched_1.12.2.jar:git-Paper-1421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by electronicboy** [comment]
That is only one avenue out of many that a profile lookup would occur, the real fix here is that your plugins handle their own task sanely instead of flooding mojangs servers with requests.

**Comment by 0-x-2-2** [comment]
Skulls placed on the ground should cause the same issue.

**Comment by mibby** [comment]
@electronicboy Isn't this a skull placed on the ground in a spawn chunk causing the issue? As per;

> 	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:46) [patched_1.12.2.jar:git-Paper-1421]

If it isn't, is there a way to find out what plugin is causing the head conversion thread update? Error doesn't include anything from a plugin.

**Comment by electronicboy** [comment]
lookups on skulls should only ever occur on skulls which aren't storing a game profile properly, i.e. these should not be an issue other than for skulls improperly generated using a command or from skulls actively being updated by a plugin.

There is no way for us to say in which aspect that skull lookup occurred because that skull lookup stuff is used for everything related to skulls, the only thing I can guarantee that it's not is a skull item, and that's only because spigot recently enforced that Skull TE lookup code to perform the lookup sync instead of using the head conversion thread. 

While you may see the exception, the skull lookups should still occur as expected, they'll just be delayed for a while on the lookup thread. delaying that thread from starting to process skulls would only delay when you're going to see that exception.
