### ISSUE TITLE
server crash still occurring

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#113]
```
[13:22:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_9_R1.ReportedException: Exception ticking world
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:842) ~[patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) ~[patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-531]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_74]
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.PlayerChunkMap.flush(PlayerChunkMap.java:119) ~[patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.WorldServer.doTick(WorldServer.java:253) ~[patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:831) ~[patched_1.9.jar:git-Paper-531]
    ... 4 more

```

https://github.com/PaperMC/Paper/issues/86

**Comment by Gabscap** [comment]
Happened to me twice today with e864916.

**Comment by aikar** [comment]
this appears to be caused by bad plugins messing with the world async (likely even modifying the world!)

I added more async catchers to this code now, so it will block the plugin instead of crashing your server (hopefully)

Identify whats triggering the async catcher and get them to fix it.

**Comment by Techcable** [comment]
I'd recomend [this patch](https://github.com/TacoSpigot/TacoSpigot/blob/version/1.9/Paper-Server-Patches/0009-Better-AsyncCatcher.patch), as it will catch any async access to the chunk-map (even reflection).

**Comment by aikar** [comment]
@Techcable checking if main thread isn't a cheap operation. It involves a system call.

Better to only put them where we know things are happening on a case by case basis.
