### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by AaronHzy** [PaperMC/Paper#1139]
### Link/paste of stack trace

`[13:01:24] [Paper Watchdog Thread/ERROR]: The server has stopped responding!
[13:02:20] [Paper Watchdog Thread/ERROR]: Please report this to https://aquifermc.org/
[13:02:34] [ForkJoinPool.commonPool-worker-0/WARN]: Exception in thread "ForkJoinPool.commonPool-worker-0" java.lang.OutOfMemoryError: Java heap space
[13:02:49] [advanced_abilities_pool housekeeper/WARN]: [com.zaxxer.hikari.pool.HikariPool] advanced_abilities_pool - Thread starvation or clock leap detected (housekeeper delta=45s110ms257µs478ns).
[13:02:54] [ForkJoinPool.commonPool-worker-0/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.growArray(ForkJoinPool.java:886)
[13:02:54] [ForkJoinPool.commonPool-worker-0/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1687)
[13:02:54] [ForkJoinPool.commonPool-worker-0/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[13:02:43] [Paper Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[13:02:54] [Paper Watchdog Thread/ERROR]: Paper version: git-Paper-1409 (MC: 1.12.2)
[13:02:54] [Paper Watchdog Thread/ERROR]: ------------------------------
[13:02:54] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[13:02:59] [Paper Watchdog Thread/ERROR]: ------------------------------
[13:02:59] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[13:02:59] [Paper Watchdog Thread/ERROR]: 	PID: 14 | Suspended: false | Native: false | State: RUNNABLE
[13:03:01] [Paper Watchdog Thread/ERROR]: 	Stack:
[13:03:01] [Paper Watchdog Thread/ERROR]: 		java.util.HashMap$KeySet.iterator(HashMap.java:917)
[13:03:01] [Paper Watchdog Thread/ERROR]: 		java.util.HashSet.iterator(HashSet.java:173)
[13:03:01] [Paper Watchdog Thread/ERROR]: 		minelazz.Iiiiiiiiii.L(ol:220)
[13:03:01] [Paper Watchdog Thread/ERROR]: 		minelazz.iIIiiiIIiI.L(bc:532)
[13:03:01] [Paper Watchdog Thread/ERROR]: 		minelazz.iIIiiiIIiI.L(bc:171)
[13:03:01] [Paper Watchdog Thread/ERROR]: 		minelazz.iIIiiiIIiI.L(bc:335)
[13:03:01] [Paper Watchdog Thread/ERROR]: 		minelazz.iIIiiiIIiI.L(bc:126)
[13:03:01] [Paper Watchdog Thread/ERROR]: 		minelazz.iIiIIiIIII.L(gc:90)
[13:03:05] [Thread-8/WARN]: java.sql.SQLException: java.lang.OutOfMemoryError: Java heap space
[13:03:05] [Thread-8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[13:03:05] [Thread-8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[13:03:05] [Thread-8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[13:03:05] [Thread-8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[13:03:06] [Thread-8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:878)
[13:03:06] [Thread-8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:874)
[13:03:06] [Thread-8/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:443)
[13:03:06] [Thread-8/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[13:03:06] [Thread-8/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[13:03:06] [Thread-8/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
[13:03:06] [Thread-8/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:247)
[13:03:06] [luckperms housekeeper/WARN]: [me.lucko.luckperms.lib.hikari.pool.HikariPool] luckperms - Thread starvation or clock leap detected (housekeeper delta=50s930ms346µs884ns).
[13:03:06] [Thread-8/WARN]: 	at net.coreprotect.database.Database.getConnection(Database.java:90)
[13:03:12] [Coins MySQL Connection Pool housekeeper/WARN]: [com.zaxxer.hikari.pool.HikariPool] Coins MySQL Connection Pool - Thread starvation or clock leap detected (housekeeper delta=1m6s203ms903µs639ns).
[13:03:12] [Paper Watchdog Thread/ERROR]: 		minelazz.iIiIIiIIII.getOrCreateChunk(gc:289)
[13:03:15] [Thread-8/WARN]: 	at net.coreprotect.consumer.Process.processConsumer(Process.java:28)
[13:03:15] [Thread-8/WARN]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:105)
[13:03:15] [Thread-8/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:03:16] [Thread-8/WARN]: Caused by: java.lang.OutOfMemoryError: Java heap space
[13:03:16] [Thread-8/WARN]: 	at java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:76)
[13:03:16] [Thread-8/WARN]: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:321)
[13:03:17] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:194)
[13:03:17] [Thread-8/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
[13:03:18] [Thread-8/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
[13:03:18] [Thread-8/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
[13:03:18] [Thread-8/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
[13:03:18] [Thread-8/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[13:03:18] [Thread-8/WARN]: 	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
[13:03:20] [Thread-8/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:03:20] [Thread-8/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[13:03:20] [Thread-8/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:03:17] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:174)
[13:03:21] [Thread-8/WARN]: 	... 8 more
[13:03:21] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:123)
[13:03:21] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:185)
[13:03:21] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:328)
[13:03:21] [bm-local housekeeper/WARN]: 136428141 [bm-local housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.HikariPool - 1m14s605ms154μs212ns - Thread starvation or clock leap detected (housekeeper delta=bm-local).
[13:03:23] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:898)
[13:03:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[13:03:28] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[13:03:28] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[13:03:36] [advanced_abilities_pool housekeeper/WARN]: [com.zaxxer.hikari.pool.HikariPool] advanced_abilities_pool - Thread starvation or clock leap detected (housekeeper delta=1m45s508ms388µs292ns).
[13:04:07] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[13:04:50] [luckperms housekeeper/WARN]: [me.lucko.luckperms.lib.hikari.pool.HikariPool] luckperms - Thread starvation or clock leap detected (housekeeper delta=45s327ms950µs960ns).
[13:04:50] [bm-local housekeeper/WARN]: 136531439 [bm-local housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.HikariPool - 46s796ms454μs113ns - Thread starvation or clock leap detected (housekeeper delta=bm-local).
[13:04:53] [Paper Watchdog Thread/ERROR]: ------------------------------
[13:04:53] [Paper Watchdog Thread/ERROR]: Entire Thread Dump:
[13:04:59] [Coins MySQL Connection Pool housekeeper/WARN]: [com.zaxxer.hikari.pool.HikariPool] Coins MySQL Connection Pool - Thread starvation or clock leap detected (housekeeper delta=1m15s953ms197µs61ns).
[13:05:10] [Thread-2/INFO]: Stopping server
[13:05:28] [advanced_abilities_pool housekeeper/WARN]: [com.zaxxer.hikari.pool.HikariPool] advanced_abilities_pool - Thread starvation or clock leap detected (housekeeper delta=1m53s979ms191µs521ns).
[13:04:54] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: 输入/输出错误
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_172]
	at java.io.FileInputStream.read(FileInputStream.java:255) ~[?:1.8.0_172]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:1.8.0_172]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_172]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_172]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_172]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_172]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_172]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_172]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_172]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_172]
	at net.minecraft.server.v1_12_R1.DedicatedServer$2.run(DedicatedServer.java:95) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
[13:06:29] [bm-local housekeeper/WARN]: 136549485 [bm-global housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.HikariPool - 1m5s956ms673μs402ns - Thread starvation or clock leap detected (housekeeper delta=bm-global).java.sql.SQLException: java.lang.OutOfMemoryError: Java heap space136628980 [bm-local housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.HikariPool - 1m57s752ms532μs751ns - Thread starvation or clock leap detected (housekeeper delta=bm-local).
[13:06:34] [Thread-4/INFO]: [TabooLib - MySQL] 数据库命令执行出错
[13:05:32] [luckperms housekeeper/WARN]: [me.lucko.luckperms.lib.hikari.pool.HikariPool] luckperms - Thread starvation or clock leap detected (housekeeper delta=1m1s461ms308µs906ns).`

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___PaperSpigot-1.12.2-b1409___

**Comment by MiniDigger** [comment]
> java.lang.OutOfMemoryError: Java heap space 

your server ran out of memory. you either have a mem leak in one of your plugins or you are not allocating enough ram to your server.

**Comment by AaronHzy** [comment]
OK Thank you
