### ISSUE TITLE
ConcurrentModificationException: null server crash when someone disconnected after a server restart.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#1188]
Paper dev 1472 (Spigot 1.12.2)

```
[09:00:52] [Server thread/INFO]: player lost connection: Disconnected
[09:00:52] [Server thread/INFO]: [ChatControl] [-] ~player has left the server.
[09:00:52] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_172]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_172]
	at net.minecraft.server.v1_12_R1.World.kill(World.java:1243) ~[patched_1.12.2.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:465) ~[patched_1.12.2.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1147) ~[patched_1.12.2.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:343) ~[patched_1.12.2.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) ~[patched_1.12.2.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) ~[patched_1.12.2.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[patched_1.12.2.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[patched_1.12.2.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1472]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[09:00:53] [Server thread/ERROR]: This crash report has been saved to: /servers/server2/./crash-reports/crash-2018-07-02_09.00.53-server.txt
```

Full crash log.
https://pastebin.com/raw/avgJfk4u

**Comment by electronicboy** [comment]
Something is modifying the collection which stores information like world maps async
