### ISSUE TITLE
"Career id must be greater than 0" error

### ISSUE THREAD

**Issue by LogGits** [PaperMC/Paper#1206]
Although the error suggests that there is an issue with StackMob, the developer has said this is an issue with spigot/paper (https://github.com/Nathat23/StackMob-2/issues/73). Just wanted to get some info from you guys about what could be causing this and if it could be caused by spigot/paper updates. 
```
WARN 15/07/2018 12:04:00
12:04:00[StackMob] Task #5826 for StackMob v2.2.12 generated an exception
Console 15/07/2018 12:04:00
12:04:00java.lang.IllegalArgumentException: Career id must be greater than 0
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1499]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftVillager.getCareer(CraftVillager.java:133) ~[patched_1.12.2.jar:git-Paper-1499]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftVillager.getCareer(CraftVillager.java:54) ~[patched_1.12.2.jar:git-Paper-1499]
at uk.antiperson.stackmob.tools.EntityTools.notMatching(EntityTools.java:72) ~[StackMob-2.2.12-SNAPSHOT.jar:?]
at uk.antiperson.stackmob.tools.EntityTools.notEnoughNearby(EntityTools.java:336) ~[StackMob-2.2.12-SNAPSHOT.jar:?]
at uk.antiperson.stackmob.listeners.entity.SpawnEvent$1.run(SpawnEvent.java:92) ~[StackMob-2.2.12-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1499]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [patched_1.12.2.jar:git-Paper-1499]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) [patched_1.12.2.jar:git-Paper-1499]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1499]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [patched_1.12.2.jar:git-Paper-1499]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1499]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```
### Plugin list:
StackMob, Citizens, Shopkeepers.

### Paper build number:
Paper build 1499.

**Comment by zachbr** [comment]
Plugin is failing upstream CraftBukkit validation.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/entity/CraftVillager.java#133

The plugin is either directly or indirectly passing an invalid career id. There's nothing here for us to fix.
