### ISSUE TITLE
Chunk.getEntities.length is not properly updated/counted?

### ISSUE THREAD

**Issue by JamieSinn** [PaperMC/Paper#1219]
https://pastebin.com/kzFmrB71

The code above produces what should be the entity total per chunk for the top 10 chunks in all worlds.

Fresh after server start: https://i.imgur.com/3eIXzG1.png

Long uptime:
https://i.imgur.com/GqDrHOc.png
https://i.imgur.com/Z2q8ENw.png

Something is very not right; what's the deal?

**Comment by zachbr** [comment]
Make sure you're on latest. There were recent bugs with entity counts and other entity data not being updated properly.

Also please provide the basic information we ask for in the tickets.

**Comment by aikar** [comment]
Hmm, the recent bugs shouldnt of impacted getEntities though, unless entities were literally left in the chunk that shouldn't of been.

**Comment by JamieSinn** [comment]
@andrewkm can fill in some more info if you need it @aikar 

@zachbr - Paper 1499.
Ironically, running the /paper version command throws an NPE.
```
[16:21:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'paper version' in com.destroystokyo.paper.PaperCommand(paper)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[PaperSpigot-latest.jar:git-Paper-1499]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[PaperSpigot-latest.jar:git-Paper-1499]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1473) ~[PaperSpigot-latest.jar:git-Paper-1499]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1278) ~[PaperSpigot-latest.jar:git-Paper-1499]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-latest.jar:git-Paper-1499]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-latest.jar:git-Paper-1499]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1499]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_172]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1499]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) [PaperSpigot-latest.jar:git-Paper-1499]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [PaperSpigot-latest.jar:git-Paper-1499]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [PaperSpigot-latest.jar:git-Paper-1499]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1499]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
	at com.destroystokyo.paper.PaperCommand.execute(PaperCommand.java:70) ~[PaperSpigot-latest.jar:git-Paper-1499]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-latest.jar:git-Paper-1499]
	... 14 more
```

**Comment by zachbr** [comment]
@JamieSinn the reason we ask you fill out the template is so that we can better diagnose the issue.

For example, neither the `version` command nor the `paper version` command NPE on build 1499 on any of my test servers. So I have to assume you have a plugin doing something horrible, but I can't tell because you didn't provide us any information.

**Comment by aikar** [comment]
@JamieSinn 
```java
org.bukkit.Bukkit.getServer().getCommandMap().getCommand("version").execute(sender, commandLabel, new String[0]);
```
Some plugin must be messing with commands. did a plugin unregister /version?

try /bukkit:version

**Comment by aikar** [comment]
but note 1500 did fix a major bug that could be the source of this issue

**Comment by JamieSinn** [comment]
Will try out 1500 - anything we should be aware of beforehand (unintended side effects, etc)

**Comment by aikar** [comment]
no, it's an urgent upgrade from any 1480'ish onwards.

**Comment by theminecoder** [comment]
The version issue may be related to the github outages that have been occurring today, as it is definitely reaching the command (as seen in stacktrace)

**Comment by JamieSinn** [comment]
@theminecoder - it's not that, we explicitly disable the /version command via commands.yml - Didn't realize the /paper version was just a proxy.

**Comment by LogGits** [comment]
@JamieSinn careful with build 1500. I am still having issues with it that causes mobs to vanish randomly for players. The solution for me was to just go back down to 1468.

Ok I would just like to clarify, I only wrote this based on my experience. I am not discrediting anyones work. I am just giving a word of caution, if it can happen to me then it is possible for another user to experience it.

**Comment by andrewkm** [comment]
@LogGits not me buddy, I'm on 1499, shits good with mobs.

**Comment by aikar** [comment]
@LogGits Please do not spread FUD in such a manner.

Build 1500 is absolutely better than Build 1499. There is a confirmed bug fixed in 1500.

We have no other reports of issues beyond your one report, which has not been reproduced.

@andrewkm I strongly suggest updating to 1500 as 1499 does have a bug that can cause entities to be lost.

**Comment by aikar** [comment]
Ok I'm fairly confident this is caused by the issue described in #1223 - please subscribe to that issue.

**Comment by JamieSinn** [comment]
Seems like this one is much more on par - https://i.imgur.com/nRIriI8.png
1500 fixed it it appears.

**Comment by aikar** [comment]
ok figured that build was potentially your specific issue, closing
