### ISSUE TITLE
Warning when some players visit the server

### ISSUE THREAD

**Issue by Qwinsel** [PaperMC/Paper#1237]
Previously, this message appeared rarely, but now it has become very frequent, the game itself does not affect, but how to fix it?

>  Couldn't look up profile properties for com.mojang.authlib.GameProfile@63f4107f[id=6b25701a-5937-3ce1-8af9-4f87abfeaaa5,name=_nata_like_,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[Spigot.jar:git-Paper-1463]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [Spigot.jar:git-Paper-1463]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:35) [Spigot.jar:git-Paper-1463]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [Spigot.jar:git-Paper-1463]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:28) [Spigot.jar:git-Paper-1463]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:178) [Spigot.jar:git-Paper-1463]
        at net.minecraft.server.v1_12_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:301) [Spigot.jar:git-Paper-1463]
        at net.minecraft.server.v1_12_R1.LoginListener$2.run(LoginListener.java:206) [Spigot.jar:git-Paper-1463]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by electronicboy** [comment]
disable bungee online mode in paper.yml.

**Comment by Qwinsel** [comment]
Thank you

**Comment by aikar** [comment]
Are you running an offline mode Bungee Server? @Qwinsel

**Comment by aikar** [comment]
I confirmed that logging into an online mode server with online mode bungee did not trigger a profile request.
So the only way you should be seeing this is if your bungee is in offline mode, but your paper config had online bungee set as @electronicboy told you to turn off.
