### ISSUE TITLE
Skull error

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#128]
```
[14:51:53] [Head Conversion Thread - 0/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@105605a1[id=bd482739-767c-45dc-a1f8-c33c40530952,name=MHF_Villager,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[patched_1.9.jar:git-Paper-554]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [patched_1.9.jar:git-Paper-554]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.TileEntitySkull$1.load(TileEntitySkull.java:75) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.TileEntitySkull$1.load(TileEntitySkull.java:42) [patched_1.9.jar:git-Paper-554]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [patched_1.9.jar:git-Paper-554]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [patched_1.9.jar:git-Paper-554]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [patched_1.9.jar:git-Paper-554]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [patched_1.9.jar:git-Paper-554]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [patched_1.9.jar:git-Paper-554]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [patched_1.9.jar:git-Paper-554]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [patched_1.9.jar:git-Paper-554]
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.TileEntitySkull$3.run(TileEntitySkull.java:196) [patched_1.9.jar:git-Paper-554]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_51]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
```

**Comment by Black-Hole** [comment]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time

So don't use more than 600 different player heads. :D

**Comment by andris155** [comment]
ok thanks!

**Comment by TheIntelloBox** [comment]
Fix soon ?

**Comment by sgdc3** [comment]
@TheIntelloBox Impossible to fix, Mojang has set a limit to the max number of UUID/Skin requests.

**Comment by TheIntelloBox** [comment]
Oh. ;( Thanks so.
