### ISSUE TITLE
[ERROR] - "Silently" catching entity tracking error (1.13)

### ISSUE THREAD

**Issue by Baktus79** [PaperMC/Paper#1288]
```
[20:49:56 ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_13_R1.ReportedException: Adding entity to track
        at net.minecraft.server.v1_13_R1.EntityTracker.addEntity(EntityTracker.java:138) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.EntityTracker.addEntity(EntityTracker.java:104) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.EntityTracker.track(EntityTracker.java:30) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.WorldManager.a(WorldManager.java:21) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.World.b(World.java:1075) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.WorldServer.b(WorldServer.java:1024) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.WorldServer.a(WorldServer.java:978) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.Chunk.addEntities(Chunk.java:942) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.loadChunkAt(ChunkProviderServer.java:99) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.getOrLoadChunkAt(ChunkProviderServer.java:116) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.PlayerChunk.<init>(PlayerChunk.java:52) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.PlayerChunkMap.c(PlayerChunkMap.java:227) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.PlayerChunkMap.addPlayer(PlayerChunkMap.java:285) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.PlayerList.a(PlayerList.java:311) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.PlayerList.onPlayerJoin(PlayerList.java:409) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.PlayerList.a(PlayerList.java:180) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.LoginListener.b(LoginListener.java:169) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.LoginListener.Y_(LoginListener.java:65) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.NetworkManager.a(NetworkManager.java:236) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.ServerConnection.c(ServerConnection.java:130) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:1086) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-55]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-55]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
        at net.minecraft.server.v1_13_R1.EntityTracker.addEntity(EntityTracker.java:112) ~[patched_1.13.jar:git-Paper-55]
        ... 24 more
```

### Paper build number:
Paper version git-Paper-55

### Anything else:
Hard to say what I did to get this error in the console. But I did check the TAB list for a few times before I noticed this error in the console.

**Comment by aikar** [comment]
I'm seeing this too, investigating

**Comment by sgdc3** [comment]
Oh god thanks! This issue was driving me crazy! Thank you @aikar
