### ISSUE TITLE
BlockState caching issue

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#129]
```
[14:56:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Deadbolt v2.2
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.jar:git-Paper-554]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.jar:git-Paper-554]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-554]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-554]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-554]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:889) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-554]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_51]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-554]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-554]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
    at com.daemitus.deadbolt.events.PlayerListener.placeQuickSign(PlayerListener.java:132) ~[?:?]
    at com.daemitus.deadbolt.events.PlayerListener.handleRightClick(PlayerListener.java:41) ~[?:?]
    at com.daemitus.deadbolt.events.PlayerListener.onPlayerInteract(PlayerListener.java:32) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor83.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-554]
    ... 18 more
```

**Comment by Black-Hole** [comment]
I'm sure the author of the Plugin "Deadbolt" have an issue tracker somewhere, but he won't read here...

**Comment by zachbr** [comment]
I think this is just an issue with the plugin itself, not anything we've touched.

**Comment by andris155** [comment]
Spigot 1.9 latest = works Deadbolt
old Paper 1.9 builds = works Deadbolt
latest Paper 1.9 builds = not work Deadbolt.

**Comment by andris155** [comment]
This is a Paper bug, please fix.

**Comment by Ichbinjoe** [comment]
Which paper build does it last work on? And I agree, this isn't anything that looks like a fault on Papers end, just looks like a cast issue.

**Comment by andris155** [comment]
Paper build 549 = works Deadbolt
Paper build 550 = not work Deadbolt

**Comment by Black-Hole** [comment]
There is a caching issue with this patch:
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0102-Cache-BlockState-for-Blocks.patch

I'm sure @aikar will fix this soon.

**Comment by zachbr** [comment]
This patch has been removed. Affected users should update to Build 558 or newer.
If it comes back we'll do some more sanity checks on the cached data.

**Comment by aikar** [comment]
I'm just going to leave the patch out, so no worries.
