### ISSUE TITLE
Error and crash on generate new chunks

### ISSUE THREAD

**Issue by FabioZumbi12** [PaperMC/Paper#1296]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it.___

I have the crash report: https://gist.github.com/FabioZumbi12/92eb789f0e92d3d2e968c6a22deceeac

And a stack trace:
```
[23:36:02 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R1.ReportedException: Exception generating new chunk
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:1054) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-78]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 19
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:134) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.PlayerChunk.a(PlayerChunk.java:96) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.PlayerChunkMap.flush(PlayerChunkMap.java:159) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.WorldServer.doTick(WorldServer.java:322) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:1043) ~[patched_1.13.jar:git-Paper-78]
        ... 4 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 19
        at net.minecraft.server.v1_13_R1.RegionLimitedWorldAccess.c(RegionLimitedWorldAccess.java:70) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkGeneratorAbstract.addFeatures(ChunkGeneratorAbstract.java:36) ~[patched_1.13.jar:git-Paper-78]
        at org.bukkit.craftbukkit.v1_13_R1.generator.NormalChunkGenerator.addFeatures(NormalChunkGenerator.java:54) ~[patched_1.13.jar:git-Paper-78]
        at co.aikar.timings.TimedChunkGenerator.addFeatures(TimedChunkGenerator.java:101) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkTaskLiquidCarve.a(SourceFile:14) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkTask.a(SourceFile:35) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:95) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.a(ChunkTaskScheduler.java:64) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.a(ChunkTaskScheduler.java:17) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:130) ~[patched_1.13.jar:git-Paper-78]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_181]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.jar:git-Paper-78]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:130) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus$1.a(SourceFile:53) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus$1.a(SourceFile:27) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:98) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler.a(SourceFile:60) ~[patched_1.13.jar:git-Paper-78]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.jar:git-Paper-78]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler.b(SourceFile:61) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.SchedulerBatch.a(SourceFile:39) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:182) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:172) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:134) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.PlayerChunk.a(PlayerChunk.java:96) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.PlayerChunkMap.flush(PlayerChunkMap.java:159) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.WorldServer.doTick(WorldServer.java:322) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:1043) ~[patched_1.13.jar:git-Paper-78]
        ... 4 more
[23:36:02 ERROR]:       Cause of unexpected exception was
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 19
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:134) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.PlayerChunk.a(PlayerChunk.java:96) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.PlayerChunkMap.flush(PlayerChunkMap.java:159) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.WorldServer.doTick(WorldServer.java:322) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:1043) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-78]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 19
        at net.minecraft.server.v1_13_R1.RegionLimitedWorldAccess.c(RegionLimitedWorldAccess.java:70) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkGeneratorAbstract.addFeatures(ChunkGeneratorAbstract.java:36) ~[patched_1.13.jar:git-Paper-78]
        at org.bukkit.craftbukkit.v1_13_R1.generator.NormalChunkGenerator.addFeatures(NormalChunkGenerator.java:54) ~[patched_1.13.jar:git-Paper-78]
        at co.aikar.timings.TimedChunkGenerator.addFeatures(TimedChunkGenerator.java:101) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkTaskLiquidCarve.a(SourceFile:14) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkTask.a(SourceFile:35) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:95) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.a(ChunkTaskScheduler.java:64) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.a(ChunkTaskScheduler.java:17) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:130) ~[patched_1.13.jar:git-Paper-78]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_181]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.jar:git-Paper-78]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:130) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus$1.a(SourceFile:53) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus$1.a(SourceFile:27) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-78]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:98) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.Scheduler.a(SourceFile:60) ~[patched_1.13.jar:git-Paper-78]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.jar:git-Paper-78]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.Scheduler.b(SourceFile:61) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.SchedulerBatch.a(SourceFile:39) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:182) ~[patched_1.13.jar:git-Paper-78]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:172) ~[patched_1.13.jar:git-Paper-78]
        ... 9 more
[23:36:02 ERROR]: This crash report has been saved to: /home/Origins/./crash-reports/crash-2018-07-31_23.36.02-server.txt
[23:36:02 INFO]: Stopping server
```

### Plugin list:
___A list of your plugins___
 Plugins (61): AdvancedPortals, afkTerminator*, Arconix*, AutoSa
veWorld*, BetterAlias*, BungeeTabListPlus*, ButtonWarp, ButtonWarpRandom*, Chest
Shop*, Citizens, CoreProtect, DailyRewards*, DeathMessagesPrime, Essentials*, Es
sentialsGeoIP*, ExpBank*, GAListener*, JDALibLoaderBukkit*, JM*, LangUtils*, Lea
derHeads*, LetItRain, LotteryZero*, MagicCarpet*, MarriageMaster*, MaxBans*, mcM
MO, MinEmojis*, MobHunting, Multiverse-Core*, MysqlEconomyBank, neoPaintingSwitc
h*, NyaaCore*, OpenInv*, PermissionsEx*, PerWorldInventory, PixelVip*, Placehold
erAPI*, ProtocolLib*, PvPDiffTimer*, PvPManager*, QuickBoard*, RankUpper, React*
, RedProtect, RFChairs, Shopkeepers, ShopTeleport*, SignEdit*, SimpleClans*, Sim
pleClansAddon*, StackMob*, Televator*, TheEndRegen*, TreeAssist, UltimateChat*, UltimateTrash*, Vault*, Votifier*, WorldBorder*, WorldEdit

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Simply on walk on world to generate some new chunks, no other way to reproduce.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
[23:39:19 INFO]: This server is running Paper version git-Paper-78 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[23:39:19 INFO]: Previous version: git-Paper-67 (MC: 1.13)
[23:39:19 INFO]: Checking version, please wait...
[23:39:20 INFO]: You are running the latest version

**Comment by zachbr** [comment]
If you're still seeing this in 1.13.1, we'd appreciate an updated stacktrace.

**Comment by FabioZumbi12** [comment]
Yeah, this is no more happening on latest versions ;)
