### ISSUE TITLE
Chunk error on player joined world

### ISSUE THREAD

**Issue by matthewmarion** [PaperMC/Paper#1327]
### What behaviour is expected:
Island to delete and player be teleported to new island.

### What behaviour is observed:
Everything works fine--as far as I know--but paper is reporting that I am still in another chunk. 

### Steps/models to reproduce:
Reset your island with latest version of askyblock using paper 1.12.2.

### Paper build number:
git-Paper-1516 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Stacktrace
`[02:01:58 WARN]: EntityPlayer['HM04'/734, uuid='73c8e0f0-8617-49d3-a7ae-fa124787d4e0', l='ASkyBlock', x=-198.00, y=4.00, z=-108.00, cx=-13, cd=-7, tl=3512956, v=true, d=false](HM04 at -198.0,4.0,-108.0) is still
in another ChunkSection! Report this to https://github.com/PaperMC/Paper/issues/1223
[02:01:58 WARN]: java.lang.Throwable
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:705)
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1826)
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1758)
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:706)
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1531)
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:683)
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:920)
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[02:01:58 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[02:01:58 WARN]:        at java.lang.Thread.run(Thread.java:748)`

**Comment by aikar** [comment]
You are using an out of date version of Paper. Newer version has a fix for this.
