### ISSUE TITLE
1.13: Eventually destroy an anvil in use caused server error.

### ISSUE THREAD

**Issue by CBM1014** [PaperMC/Paper#1331]
### Link/paste of stack trace

```
[00:38:18 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:199) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:987) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:915) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:813) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.fromData(CraftBlockData.java:497) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.ContainerAnvil$2.a(ContainerAnvil.java:77) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.Container.a(Container.java:286) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2274) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[patched_1.13.jar:git-Paper-"d285e05d"]
        ... 5 more
```

### Plugin list:
`Plugins (10): CBMUtils, CoreProtect, MelonHomes, MelonTPA, MelonWhitelist, MiaoBoard*, PermissionsEx*, PlaceholderAPI*, Poster, WhiteNoise*`
You can get more information about the plugins [here](https://github.com/Akarin-project/Akarin/issues/50
).

### Actions to reproduce (if known):

You can reproduce this error by eventually destroy an anvil in use.
You can also get more information about this issue [here](https://github.com/Akarin-project/Akarin/issues/50
).

### Paper build number:

`[00:58:26 INFO]: This server is running Paper version git-Paper-"d285e05d" (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
`

**Comment by SomeBottle** [comment]
This is what he wants to express:
Using an anvil which is going to be broken naturally may lead to a server crashing.

**Comment by aikar** [comment]
I can see the issue, as the IDE clearly states "this can be null". Will try to fix soon. It's paper specific.

**Comment by aikar** [comment]
fixed in latest build 130+
