### ISSUE TITLE
Server Crash 1.12.2/paper-1536

### ISSUE THREAD

**Issue by 0XE4** [PaperMC/Paper#1340]
### Link/paste of stack trace

```
[04:03:54 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:915) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1539]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(Unknown Source) ~[?:1.8.0_172]
        at java.util.LinkedList$ListItr.next(Unknown Source) ~[?:1.8.0_172]
        at net.minecraft.server.v1_12_R1.StructureStart.a(StructureStart.java:36) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.StructureGenerator.a(StructureGenerator.java:90) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.ChunkProviderGenerate.recreateStructures(ChunkProviderGenerate.java:333) ~[patched_1.12.2.jar:git-Paper-1539]
        at org.bukkit.craftbukkit.v1_12_R1.generator.NormalChunkGenerator.recreateStructures(NormalChunkGenerator.java:41) ~[patched_1.12.2.jar:git-Paper-1539]
        at co.aikar.timings.TimedChunkGenerator.recreateStructures(TimedChunkGenerator.java:100) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:1174) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:1160) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:207) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:174) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:123) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:185) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:333) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:904) ~[patched_1.12.2.jar:git-Paper-1539]
        ... 4 more
[04:03:54 ERROR]:       Cause of unexpected exception was
java.util.ConcurrentModificationException: null
        at java.util.LinkedList$ListItr.checkForComodification(Unknown Source) ~[?:1.8.0_172]
        at java.util.LinkedList$ListItr.next(Unknown Source) ~[?:1.8.0_172]
        at net.minecraft.server.v1_12_R1.StructureStart.a(StructureStart.java:36) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.StructureGenerator.a(StructureGenerator.java:90) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.ChunkProviderGenerate.recreateStructures(ChunkProviderGenerate.java:333) ~[patched_1.12.2.jar:git-Paper-1539]
        at org.bukkit.craftbukkit.v1_12_R1.generator.NormalChunkGenerator.recreateStructures(NormalChunkGenerator.java:41) ~[patched_1.12.2.jar:git-Paper-1539]
        at co.aikar.timings.TimedChunkGenerator.recreateStructures(TimedChunkGenerator.java:100) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:1174) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:1160) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:207) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:174) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:123) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:185) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:333) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:904) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1539]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
[08:33:54 ERROR]: This crash report has been saved to: /home/xxxxx/xxxxx/./crash-reports/crash-2018-08-16_04.03.54-server.txt
```

### Actions to reproduce (if known):
No action, observe the console after the crash and see the thread dump. The server also prints a dump saying the server has not responded for 5 seconds. This has only started happening since version 1530 or so. The crashes are every 18 hours or so.

### Paper build number:
```
[04:05:53 INFO]: This server is running Paper version git-Paper-1539 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[04:05:53 INFO]: Previous version: git-Paper-1536 (MC: 1.12.2)
```

**Comment by prplz** [comment]
The "not responded for 5 seconds" thing is not actually an error, its more of a warning that there was a lag spike longer than five seconds. Can you paste the actual part where the server crashes?

**Comment by VADemon** [comment]
Is there any player who joins prior to the crash?

Also prplz is right, the crash occured at least 5 seconds before this message.

**Comment by aikar** [comment]
Not a crash as said

**Comment by 0XE4** [comment]
Just to expand, the server stopped just after this message @aikar . @prplz The crash message was:
 -- moved to op --

**Comment by hafarooki** [comment]
Actually is a crash, exception ticking world.

**Comment by aikar** [comment]
Oh I I guess I never pressed button, moved crash to original post, but not reopening as this error would be caused by plugin doing unsafe operations async

**Comment by 0XE4** [comment]
I have no world-modifying or interaction plugins. It seems the issue is linked to loading chunks?
All my plugins are chat based or extra commands & NCP.

**Comment by baba43** [comment]
We have the same problems and no idea, why they have started some weeks ago.

**Comment by hafarooki** [comment]
this one is closed, open a new issue
