### ISSUE TITLE
"Silently" catching entity tracking error again.

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#136]
```
[11:49:19] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_9_R1.ReportedException: Adding entity to track
    at net.minecraft.server.v1_9_R1.EntityTracker.addEntity(EntityTracker.java:142) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.EntityTracker.track(EntityTracker.java:81) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.WorldManager.a(WorldManager.java:18) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.World.b(World.java:1100) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.WorldServer.b(WorldServer.java:1154) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.World.addEntity(World.java:1093) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:483) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:479) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:490) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.MobSpawnerAbstract.c(MobSpawnerAbstract.java:111) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.TileEntityMobSpawner.c(SourceFile:61) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1577) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:630) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:847) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-549]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-549]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
    at net.minecraft.server.v1_9_R1.EntityTracker.addEntity(EntityTracker.java:109) ~[patched_1.9.jar:git-Paper-549]
    ... 17 more
```

**Comment by SmallSansSerif** [comment]
[18:01:08] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_9_R1.ReportedException: Adding entity to track

Error in console in Paper build 606. See the pastebin below:
http://pastebin.com/cvQFA1qP

**Comment by zachbr** [comment]
If anyone remembers those "xxx entity has a duplicate UUID" warning messages, this is likely related to that. If an entity has a duplicate UUID and we give it to the tracker, the tracker is going to throw a fit, similar to what you're seeing here. Sometimes this happens after an entity dies and it wasn't cleared yet, and it'll eventually re-track properly on its own. Sometimes you may end up with a frozen mob or two. Seeing this once or twice over the course of twenty-four hours isn't unrealistic, if it's flooding your console you have a problem.

**Comment by zachbr** [comment]
See response from three months ago.
