### ISSUE TITLE
Async worldcreation

### ISSUE THREAD

**Issue by xXSchrandXx** [PaperMC/Paper#1361]
### Link/paste of stack trace
Log:
```txt
[20:10:10] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_181]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:946) ~[patched_1.13.jar:git-Paper-159]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:813) ~[patched_1.13.jar:git-Paper-159]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[20:10:10] [Craft Scheduler Thread - 6/ERROR]: stopTiming called async for test - syncChunkLoad - Data
[20:10:10] [Craft Scheduler Thread - 6/WARN]: java.lang.Throwable
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:113)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at net.minecraft.server.v1_13_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:202)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at net.minecraft.server.v1_13_R1.ChunkProviderServer.loadChunkAt(ChunkProviderServer.java:93)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at net.minecraft.server.v1_13_R1.ChunkProviderServer.getOrLoadChunkAt(ChunkProviderServer.java:116)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at net.minecraft.server.v1_13_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:127)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createWorld(CraftServer.java:1025)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:491)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at de.xXSchrandXx.API.paperworld$1.run(paperworld.java:39)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:63)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:10:10] [Craft Scheduler Thread - 6/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
Crash:
```txt
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/21/18 8:10 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:946)
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:813)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.13
	Operating System: Linux (amd64) version 4.9.0-6-amd64
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 739932736 bytes (705 MB) / 960495616 bytes (916 MB) up to 960495616 bytes (916 MB)
	JVM Flags: 4 total; -Xms512M -Xmx1G -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1
	CraftBukkit Information: 
   Running: Paper version git-Paper-159 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT) true
   Plugins: { LuckPerms v4.2.58* me.lucko.luckperms.bukkit.LPBukkitBootstrap [Luck], FastAsyncWorldEdit v1.0* com.boydti.fawe.Blank [], ProtocolSupport v4.29-dev protocolsupport.ProtocolSupport [_Shevchik_, 7kasper, MrPowerGamerBR, gdude2002], PlaceholderAPI v2.9.1* me.clip.placeholderapi.PlaceholderAPIPlugin [[extended_clip]], ProtocolLib v4.3.0* com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], ProtocolSupportStuff v2.0.0 net.perfectdreams.protocolsupportstuff.ProtocolSupportStuff [MrPowerGamerBR], iForce v5.0* de.xforcehd.main [Serverteam, xForceHD, xXSchrandXx], FastAsyncWorldEdit vunspecified* com.sk89q.worldedit.bukkit.WorldEditPlugin 
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_13_R1.CraftCrashReport.call(CraftCrashReport.java:27)
	at net.minecraft.server.v1_13_R1.CrashReportSystemDetails.a(SourceFile:79)
	at net.minecraft.server.v1_13_R1.CrashReport.h(CrashReport.java:66)
	at net.minecraft.server.v1_13_R1.CrashReport.<init>(CrashReport.java:34)
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:834)
	at java.lang.Thread.run(Thread.java:748)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 100; []
	Data Packs: vanilla, file/bukkit (incompatible)
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

### Plugin list:
Listet in crash.

### Actions to reproduce (if known):
Can't run Worldcreation async. How can I use [AsyncChunkLoad](https://github.com/PaperMC/Paper/blob/9daa9cec930f16d52330656f42ab992eb4612683/Spigot-API-Patches/0006-Add-async-chunk-load-API.patch).
Very likely a mistake of mine.

### Paper build number:
Listet in crash.

**Comment by aikar** [comment]
creating worlds async is not allowed
Async chunk load is a different thing, to do Disk IO separately, but must still be called on the main thread.

That API is not safe to call async. 

Additionally, Async Chunk Loading is currently removed from 1.13
