### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by randalz-z** [PaperMC/Paper#1373]
[User Authenticator #8/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@154e6725[id=233f4cac-5261-3675-8b3a-bba5032dd6da,name=mskfrioe,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:35) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:28) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:177) ~[patched_1.12.2.jar:git-Paper-1550]
	at net.minecraft.server.v1_12_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:301) ~[patched_1.12.2.jar:git-Paper-1550]
	at net.minecraft.server.v1_12_R1.LoginListener$2.run(LoginListener.java:206) ~[patched_1.12.2.jar:git-Paper-1550]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by hugmanrique** [comment]
Your dedicated server has made too many player lookup requests to Mojang's servers and it has been temporarily denylisted.

There's no way to fix this other than wait for Mojang to remove the ban.

**Comment by randalz-z** [comment]
The problem started immediately after installing the Via Version

**Comment by hugmanrique** [comment]
Then ViaVersion might be causing additional UUID/skin lookups. Anyways, this isn't the place to report it, check https://github.com/MylesIsCool/ViaVersion/issues instead.
