### ISSUE TITLE
Nether World Problem

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#141]
```
[14:51:59] [Paper - Lighting Thread/ERROR]: stopTiming called async for world_nether - chunkLoad - Post
[14:51:59] [Paper - Lighting Thread/WARN]: java.lang.Throwable
[14:51:59] [Paper - Lighting Thread/WARN]:  at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.Chunk.loadNearby(Chunk.java:981)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:212)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:146)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getOrCreateChunkFast(ChunkProviderServer.java:83)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAt(World.java:341)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAtWorldCoords(World.java:337)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getType(World.java:760)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.a(World.java:2276)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.c(World.java:2419)
[14:51:59] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World$6.run(World.java:2502)
[14:51:59] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:51:59] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.FutureTask.run(Unknown Source)
[14:51:59] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:51:59] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:51:59] [Paper - Lighting Thread/WARN]:  at java.lang.Thread.run(Unknown Source)
```

When a player move very fast in nether world, console show this.
**I use lastest Paper, this problem has no fix.** Like #93

**Comment by zachbr** [comment]
This feature is not even present in the latest version of Paper. We forcefully disabled it. Please _ACTUALLY_ run latest. And don't bother submitting build reports with outdated builds. Give us actual version strings only. "latest" is not a version. Nor is it latest in this case.
