### ISSUE TITLE
Players being kicked 

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1417]
### What behaviour is expected:
People not being kicked

### What behaviour is observed:
After updating from paperclip build 187 (the 1.13 one), players get kicked when private messaging other players for:

`[22:23:49 INFO]: username lost connection: Internal Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: -15`

### Steps/models to reproduce:
The user either types /msg (name) (message) or /r (message)

### Plugin list:
`AntiWitherDestruction*, BuycraftX*, ChatColor*, ChatControl, ChatReaction*, ChestShop, ClearLag*, ColoredAnvils*, CombatLogX, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CrateReloaded, CrazyEnchantments, DeluxeCommands, DeluxeMenus*, DiscordBridge*, Emotes, Essentials*, EssentialsSpawn*, FactionsFly*, FarmLimiter*, FastAsyncWorldEdit*, FBasics*, FeatherBoard*, GuiRedeemMCMMO*, HideStream*, HolographicDisplays*, Jobs, KitsPreview*, LiteBans*, LuckPerms*, mcMMO, MergedMob, MergedSpawner, MessageAnnouncer*, MineableSpawners, MomentoAds*, MomentoChat*, MomentoSetWarp*, MomentoTownBan*, Multiverse-Core*, MVdWPlaceholderAPI*, MyCommand*, NametagEdit*, NightVision*, NoCheatPlus, OldCombatMechanics*, PlaceholderAPI*, PlayerVaults, PluginLibrary*, PlugMan*, ProtocolLib*, ProtocolSupport, Questioner*, SuperbVote, TitleManager*, TopTowny*, TopvoterClient*, Towny*, TownyChat*, TownyNameUpdater*, TradePlus, TrailGUI*, UltimateCasino*, Vault*, ViaVersion*, VoteParty*, Votifier*, WorldBorder*, WorldEdit, WorldGuard
`

### Paper build number:
Versions past build 187 for 1.13

### Anything else:
I'm not sure if this is the fault of our chat system or paper, I just thought I should throw this here since we've only started having this issue in the recent updates.

**Comment by andris155** [comment]
/r kick two plugin commands conflict
Remove FastAsyncWorldEdit /r alias commands.yml

**Comment by zachbr** [comment]
If you can whittle this issue down to a plugin interaction or some easily reproducible cause we may be able to help, but short of someone else swooping in with the info, we're not going through all those plugins.

**Comment by ghost** [comment]
@zachbr it happens when users private message or reply using our custom chat plugin. Tho as mentioned it only started happening after a certain update, if you or another developer wants to see how its handled in our plugin I can show you the source but I will not be linking it on here for obvious reasons.

**Comment by zachbr** [comment]
We only need some reproducible test case, what you're calling, when that happens, and what the arguments are that are causing this issue.

Feel free to send me an email or message me on Discord or w/e your preference is.

**Comment by ghost** [comment]
Add me on discord and I'll show you how we handle it, my discord is fergydanny#0001

**Comment by zachbr** [comment]
As we've now discovered and mentioned in GH-1424, this is the result of a packet transaction ID being wrongly instead of the proper range.

```java
[22:33:07 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -279
[22:33:07 WARN]:       at java.lang.String.substring(String.java:1931)
[22:33:07 WARN]:       at com.mojang.brigadier.suggestion.SuggestionsBuilder.<init>(SuggestionsBuilder.java:19)
[22:33:07 WARN]:       at net.minecraft.server.v1_13_R2.PlayerConnection.lambda$sendSuggestions$4(PlayerConnection.java:576)
[22:33:07 WARN]:       at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
[22:33:07 WARN]:       at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669)
[22:33:07 WARN]:       at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997)
[22:33:07 WARN]:       at net.minecraft.server.v1_13_R2.PlayerConnection.sendSuggestions(PlayerConnection.java:566)
[22:33:07 WARN]:       at net.minecraft.server.v1_13_R2.PlayerConnection.lambda$a$2(PlayerConnection.java:556)
[22:33:07 WARN]:       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:33:07 WARN]:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:33:07 WARN]:       at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[22:33:07 WARN]:       at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1012)
[22:33:07 WARN]:       at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428)
[22:33:07 WARN]:       at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[22:33:07 WARN]:       at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838)
[22:33:07 WARN]:       at java.lang.Thread.run(Thread.java:748)
```

**Comment by zachbr** [comment]
Confirmed resolved.
