### ISSUE TITLE
/127.0.0.1:37817 lost connection: Internal Exception: java.lang.IllegalArgumentException: hostname can't be null

### ISSUE THREAD

**Issue by mcpanglei** [PaperMC/Paper#1443]
when the player connected to the paper server，it print this：
/127.0.0.1:37817 lost connection: Internal Exception: java.lang.IllegalArgumentException: hostname can't be null

The bungeecord print this：

14:44:25 [严重] [mcbbfhfg] <-> ServerConnector [ser1] - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
1b87017b227472616e736c617465223a22646973636f6e6e6563742e67656e65726963526561736f6e222c2277697468223a5b22496e7465726e616c20457863
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:130)
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.lang.Thread.run(Thread.java:748)

### Plugin list:
[PlugMan] Plugins (40): AnimatedScoreboard, AntiSpam, AutoMessage, AutoShutdown, BossShop, BungeeTabListPlus, ChestSort, CoreProtect, DeluxeChat, dsTitle, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, GroupManager, HolographicDisplays, iConomy, MoneyTree, Multiverse-Core, MVdWPlaceholderAPI, MySkin, MysqlPlayerDataBridge, NoPlugins, OpenInv, Operator, PixelVip, PlaceholderAPI, PlayerPoints, PlotSquared, PlugMan, ProtocolLib, QuickShop, RandomPlacer, Residence, SQLibrary, Vault, warpk, warpk_antixray, WorldBorder, XRayShield

### Paper build number:
This server is running Paper version git-Paper-253 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
The error on bungeecord is due to the server sending an invalid packet, the message on the server is somewhat indicative to the same, your proxy sent an invalid message to us; Enable debug mode in server.properties and check your logs

**Comment by mcpanglei** [comment]
Whenever this error occurs，I have to restart the bungeecord  to solve this problem.
When I use spigot server and use the same bungeecord proxy, this problem has not happened before.

Here is the error on paperspigot when i  enable debug mode:

[23:41:41 INFO]: /127.0.0.1:47313 lost connection: Internal Exception: java.lang.IllegalArgumentException: hostname can't be null
[23:41:47 WARN]: java.lang.IllegalArgumentException: hostname can't be null
[23:41:47 WARN]:        at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
[23:41:47 WARN]:        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.HandshakeListener.a(HandshakeListener.java:92)
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:29)
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:5)
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:147)
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:136)
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:358)
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:31)
[23:41:47 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:250)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.LegacyPingHandler.channelRead(LegacyPingHandler.java:112)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[23:41:47 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[23:41:47 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[23:41:47 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[23:41:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[23:41:47 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:41:47 WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:250)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.LegacyPingHandler.channelRead(LegacyPingHandler.java:112)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:41:47 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:41:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[23:41:47 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[23:41:47 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[23:41:47 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[23:41:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[23:41:47 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:41:47 WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[23:41:47 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[23:41:47 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:488)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[23:41:47 WARN]:        ... 30 more
[23:41:47 WARN]: Caused by: java.io.IOException: Packet 0/0 (PacketPlayInTeleportAccept) was larger than I expected, found 4 bytes extra whilst reading packet 0
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.PacketDecoder.decode(SourceFile:42)
[23:41:47 WARN]:        at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
[23:41:47 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:41:47 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[23:41:47 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[23:41:47 WARN]:        ... 33 more
[23:41:47 WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[23:41:47 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[23:41:47 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[23:41:47 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[23:41:47 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[23:41:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
[23:41:47 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
[23:41:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[23:41:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[23:41:47 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[23:41:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[23:41:47 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:41:47 WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[23:41:47 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[23:41:47 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:488)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[23:41:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[23:41:47 WARN]:        ... 30 more
[23:41:47 WARN]: Caused by: java.io.IOException: Bad packet id 74
[23:41:47 WARN]:        at net.minecraft.server.v1_13_R2.PacketDecoder.decode(SourceFile:37)
[23:41:47 WARN]:        at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
[23:41:47 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:41:47 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[23:41:47 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[23:41:47 WARN]:        ... 33 more

**Comment by mcpanglei** [comment]
I just tested that by unloading AnimatedScoreboard, after unloaded it, I can enter the server.

**Comment by electronicboy** [comment]
This appears to be a bit of an issue with a plugin on your side, the first error is because something set the hostname that the person is connecting to null in the event, the second of error is going to be due to the first one

**Comment by mcpanglei** [comment]
When I use spigot server and use the same bungeecord proxy, this problem has not happened before，It's strange

**Comment by electronicboy** [comment]
You have a plugin that is listening on papers `PlayerHandshakeEvent`, which is designed to allow a plugin to take over the process, as this event does not exist on Spigot, it would make sense that the plugin messing with that event won't fail, you need to find what is using that event

**Comment by mcpanglei** [comment]
Since I unloaded the AnimatedScoreboard last night, there was no more ERRORS.
Let me check it again. Thank you.
