### ISSUE TITLE
Ticking player

### ISSUE THREAD

**Issue by Feerko** [PaperMC/Paper#1562]
### What behaviour is observed:
the server has shut down

### Paper build number:
1574

### Anything else:
```
[19:18:30] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:932) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1574]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_181]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_181]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:386) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:83) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.EntityPlayer.B_(EntityPlayer.java:281) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1794) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1764) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:706) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1537) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:683) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921) ~[patched_1.12.2.jar:git-Paper-1574]
	... 4 more
[19:18:30] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_181]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_181]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:386) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:83) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.EntityPlayer.B_(EntityPlayer.java:281) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1794) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1764) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:706) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1537) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:683) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1574]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1574]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by electronicboy** [comment]
You have a plugin that is modifying the state of the world async, apparently something causing items to the dropped in the world

**Comment by Feerko** [comment]
@electronicboy it's true. what is it caused and how can I prevent it?
I'm using https://github.com/HexoCraft/WorldRestorer

**Comment by electronicboy** [comment]
I can't say what plugin caused it, if you know the plugin which is causing it, you need to speak to the plugin author so that they can fix it
