### ISSUE TITLE
Crash - Exception ticking world

### ISSUE THREAD

**Issue by Intelli** [PaperMC/Paper#159]
My server has been crashing with the more recent Paper builds.

Listed below is the information from the most recent crash, which occurred while using Paper-581.
## server.log

[17:07:57] [User Authenticator #17/INFO]: UUID of player pastamax1 is bad6a5a6-f25a-4e89-88ec-ef9f3e89ad74
[17:07:57] [Server thread/INFO]: pastamax1[/154.20.232.216:51800] logged in with entity id 173429 at ([world]4077.9236563986483, 67.0, 1684.0340933004668)
[17:07:57] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_9_R1.ReportedException: Exception ticking world
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:877) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.jar:git-Paper-581]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_71]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_71]
        at net.minecraft.server.v1_9_R1.World.a(World.java:2660) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.SpawnerCreature.a(SpawnerCreature.java:121) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.WorldServer.doTick(WorldServer.java:224) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:866) ~[patched_1.9.jar:git-Paper-581]
        ... 4 more
[17:07:57] [Server thread/ERROR]:       Cause of unexpected exception was
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_71]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_71]
        at net.minecraft.server.v1_9_R1.World.a(World.java:2660) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.SpawnerCreature.a(SpawnerCreature.java:121) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.WorldServer.doTick(WorldServer.java:224) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:866) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) ~[patched_1.9.jar:git-Paper-581]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.jar:git-Paper-581]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
[17:07:57] [Server thread/ERROR]: This crash report has been saved to: ./crash-reports/crash-2016-03-27_17.07.57-server.txt
## crash-2016-03-27_17.07.57-server.txt

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 27/03/16 5:07 PM
Description: Exception ticking world

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at net.minecraft.server.v1_9_R1.World.a(World.java:2660)
    at net.minecraft.server.v1_9_R1.SpawnerCreature.a(SpawnerCreature.java:121)
    at net.minecraft.server.v1_9_R1.WorldServer.doTick(WorldServer.java:224)
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:866)
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720)
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows: http://pastebin.com/rrf56X5W

**Comment by Puremin0rez** [comment]
I can confirm that I've also received this running on Build 581.
