### ISSUE TITLE
Spectating does not work any more

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#1603]
### What behaviour is expected:
Spectating an entity should start when left clicking the entity in spectator mode

### What behaviour is observed:
Not spectating the entity but an exception in the server log

### Steps/models to reproduce:
- /gamemode spectator
- click an entity

### Plugin list:
No plugin needed

### Paper build number:
 git-Paper-382 (MC: 1.13.1)

### Anything else:
`[15:56:03 FATAL]: Error executing task
java.lang.NullPointerException: null
        at net.minecraft.server.v1_13_R2.PacketPlayOutCamera.<init>(SourceFile:19) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.EntityPlayer.setSpectatorTarget(EntityPlayer.java:1398) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1414) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1979) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-382]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-382]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-382]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
`

**Comment by CalebBassham** [comment]
If `366` is really the version you are using there should not be a problem as far as I know, but if you are using `376+` then it is because of #1595 and fixed in #1596 but has not been merged to master. When it is, you will just need to download an updated jar from https://papermc.io/downloads to fix the problem.

**Comment by Brokkonaut** [comment]
Oh, i copied the version from the wrong server, thanks
