### ISSUE TITLE
GetOnlinePlayers Methods Breaking?

### ISSUE THREAD

**Issue by zachduda** [PaperMC/Paper#1682]
###Console Error:
`[23:03:35] [Craft Scheduler Thread - 10/INFO]: [GAListener] Connection established!
[23:03:36] [Server thread/WARN]: [GAListener] Task #29 for GAListener v1.3.2 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server._INVALID_getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.swifteh.GAL.GAL$6.run(GAL.java:409) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-447]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-447]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-447]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-447]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-447]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-447]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`
(This issue is only with Paper for some odd reason)

### Steps/models to reproduce:
Download GAListener with defaults and use the latest version of Paper.

### Paper build number:
Build #442

### Anything else:
This does not break on normal 1.13.2 spigot.

**Comment by electronicboy** [comment]
GAListener is trying to use a method which hasn't existed in the server in quite a while now, you'll need to find a plugin which is maintained and updated for recent versions of the server

**Comment by zachbr** [comment]
The method the plugin is attempting to access hasn't existed since May of 2017.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/c185dd58fea5f4ce4b2dc3c135c7ff550f4936b0

So I've a hard time believing this works in Spigot.
