### ISSUE TITLE
Typing Certain Commands Results in Kick

### ISSUE THREAD

**Issue by CinnamonLambda** [PaperMC/Paper#1691]
# Server Info # 
System Info: Java 1.8 (Java HotSpot(TM) Client VM 25.191-b12) Host:  Windows 10 10.0 (x86)
We're running build 451.

# Plugin List # 
Plugins (30): BackOnDeath*, BasicColors*, BlocksHub, ConsoleSay*, CoreProtect, Craftconomy3*, dynmap*, iDisguise, iDisguiseAdditions*, LWC, LWC-Economy*, mcMMO, mcMMOAction*, MuteManager*, Namechanger*, OpenInv*, PremiumVanish, ProtocolLib*, RewardMe*, SignShop*, SimpleHomes*, SimpleJail*, SimpleRename, Sudo*, Suicide*, tpa*, Ultimate-Powertool*, Vault*, WorldEdit, WorldGuard

# Steps to Reproduce # 
Try to run, as a known example: `/co a:container r:#we` in these circumstances, it should kick you around "a:".

# Notes # 
I have a feeling it's a plugin compatability issue, as it is not affecting the lobby, which is also running Paper in the same conditions, but not with all those plugins. When we had the Vampire plugin installed, commands from it also tended to trigger the bug.

**Comment by electronicboy** [comment]
Kick message? anything messages in the server console? are you running bungee or any form of protocol hack on your server?

**Comment by CinnamonLambda** [comment]
I run Waterfall, and in the server the disconnect message is just "Disconnected".
There's also no protocol hack.
In Waterfall, this message appears:
```
[16:41:25 ERROR]: [/192.168.53.1:53166|TheAgentRAINBOW] <-> DownstreamBridge <-> [UnifiedHorn] - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet unknown with contents:

        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 64))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1433) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:726) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:39) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
        ... 29 more
```

**Comment by CinnamonLambda** [comment]
Updated to build 452.

**Comment by electronicboy** [comment]
Could you try without PremiumVanish, I've had a few reports of this with that plugin

**Comment by CinnamonLambda** [comment]
I tried without PremiumVanish and it was fixed, are there any plans to fix this bug?

**Comment by electronicboy** [comment]
This isn't a bug with paper, the plugin is more than likely modifying tab packets in order to remove vanished people from it, but as the packet changed in 1.13+, it no longer works properly and ends up causing an invalid packet to by sent by the server

**Comment by CinnamonLambda** [comment]
Okay then, thanks.
