### ISSUE TITLE
NPE during AsyncPlayerPreLoginEvent to CraftOfflinePlayer

### ISSUE THREAD

**Issue by bundabrg** [PaperMC/Paper#1701]
### Link/paste of stack trace
```
[10:56:08 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to BetonQuest v2.0-preview.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-456]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.13.2.jar:git-Paper-456]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-456]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-456]
        at net.minecraft.server.v1_13_R2.LoginListener$LoginHandler.fireEvents(LoginListener.java:304) ~[patched_1.13.2.jar:git-Paper-456]
        at net.minecraft.server.v1_13_R2.LoginListener$2.run(LoginListener.java:244) ~[patched_1.13.2.jar:git-Paper-456]        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_192]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_13_R2.CraftOfflinePlayer.<init>(CraftOfflinePlayer.java:35) ~[patched_1.13.2.jar:git-Paper-456]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.getOfflinePlayer(CraftServer.java:1481) ~[patched_1.13.2.jar:git-Paper-456]
        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:809) ~[patched_1.13.2.jar:git-Paper-456]
        at pl.betoncraft.betonquest.utils.PlayerConverter.getName(PlayerConverter.java:66) ~[?:?]
        at pl.betoncraft.betonquest.BetonQuest.putPlayerData(BetonQuest.java:1017) ~[?:?]
        at pl.betoncraft.betonquest.JoinQuitListener.playerPreLogin(JoinQuitListener.java:64) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-456]
        ... 8 more
```

### Plugin list:
Unknown but at least one is BetonQuest.

### Actions to reproduce (if known):
On login

### Paper build number:
Unknown but I'll get it from the owner if needed

### Notes

I'm a dev for the plugin BetonQuest. One of the users of the plugin reported this stack trace which occurs in CraftOfflinePlayer on this line I believe:

```
this.storage = (WorldNBTStorage) (server.console.worlds.get(0).getDataManager());
```

It is called inside an AsyncPlayerPreLoginEvent.

I can't reproduce it but thought it would be of interest since it occurs in server code. I've recommended they update to the latest PaperMC and retest with minimal plugins.

I'm pretty sure its safe to call Bukkit#getOfflinePlayer from this event.

**Comment by BillyGalbreath** [comment]
Did this happen on server startup? The only way you'd get an NPE there is if no worlds are loaded. So either a player joined during startup before worlds were loaded, or the server unloaded all the worlds sometime during runtime.

**Comment by bundabrg** [comment]
That was my thoughts as well since the world list must be empty.

**Comment by zachbr** [comment]
As Billy mentioned this can only occur when no worlds are loaded. This doesn't appear to be specific to Paper its just a general issue with how that code is written. I'm not sure there's any good way to fix this but the last time I looked at this was probably 3 or 4 weeks ago.

We'll keep this open for now but this may just end up being something you need to check before hand. It just depends what our options are here.

**Comment by bundabrg** [comment]
For my issue (and probably anyone else) I think just waiting for the first tick should be sufficient. However in my case I'm uninterested in getting the world in the first place, just wanted the player. I wonder if its worth moving world lookup to a lazy lookup on invocation of getWorld. It would just move the NPE to if someone queries the world before it loads but solves it if someone is just looking up the player (to get its UUID, id or name or whatever).

**Comment by zachbr** [comment]
That looks like the most reasonable solution to the problem. I've added it so hopefully you should see this (hopefully) very rare occurrence less. I've also made it throw a clearer exception should someone try to access anything relying on it. Hopefully that'll make things clearer for everyone.

Thanks, builds 477+
