### ISSUE TITLE
Compatibility issue between Hikari lib and Paper

### ISSUE THREAD

**Issue by tianji1993** [PaperMC/Paper#1715]
### What behaviour is expected:
___What you expected to see___
MyPet and LuckPerms works under PaperSpigot.
### What behaviour is observed:
___What you actually saw___
MyPet and LuckPerms both cannot load mysql data, error message contains same error: Hikari cannot init and get timeout error.
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
###LuckPerms log under paperspigot:
[03:07:27] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v4.3.2*
[03:07:27] [Server thread/INFO]:         __    
[03:07:27] [Server thread/INFO]:   |    |__)   LuckPerms v4.3.2
[03:07:27] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[03:07:27] [Server thread/INFO]: 
[03:07:27] [Server thread/INFO]: [LuckPerms] Loading configuration...
[03:07:27] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[03:07:27] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[03:07:27] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[03:07:32] [Server thread/ERROR]: [LuckPerms] Failed to init storage dao
[03:07:32] [Server thread/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.tableExists(SqlDao.java:145)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:162)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:122)
[03:07:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:07:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03:07:32] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:07:32] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:64)
[03:07:32] [Server thread/WARN]: 	at com.sun.proxy.$Proxy59.init(Unknown Source)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:117)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:130)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[03:07:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
[03:07:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[03:07:32] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
###LuckPerms log under Spigot:
[03:11:10] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v4.3.2
[03:11:10] [Server thread/INFO]: [0;36;1m       [0;36;22m __    [m
[03:11:10] [Server thread/INFO]: [0;36;1m  |    [0;36;22m|__)   [0;32;22mLuckPerms [0;36;1mv4.3.2[m
[03:11:10] [Server thread/INFO]: [0;36;1m  |___ [0;36;22m|      [0;30;1mRunning on Bukkit - CraftBukkit[m
[03:11:10] [Server thread/INFO]: [m
[03:11:10] [Server thread/INFO]: [LuckPerms] Loading configuration...
[03:11:10] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[03:11:10] [Server thread/INFO]: luckperms-hikari - Starting...
[03:11:10] [Server thread/INFO]: luckperms-hikari - Start completed.
[03:11:10] [Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[03:11:11] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[03:11:11] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[03:11:11] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 728ms)

**MyPet log under paperspigot:**
[03:08:08] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Connect to MySQL database...
[03:08:38] [Server thread/WARN]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.util.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.util.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.util.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.util.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.repository.types.MySqlRepository.updateInfo(MySqlRepository.java:337)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.repository.types.MySqlRepository.init(MySqlRepository.java:86)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:313)
[03:08:38] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[03:08:38] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[03:08:38] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:08:38] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[03:08:38] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[03:08:38] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
**MyPet log under spigot:**
[03:11:34] [Server thread/INFO]: [[0;32;22mMyPet[m] [mEnabling MyPet v3.0[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [m################################################[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [m# A new build is available: 3.0-SNAPSHOT #641 #[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [m# https://mypet-plugin.de/download #[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [m################################################[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [mCompat mode for v1_13_R2 loaded.[m
[03:11:41] [Server thread/INFO]: [[0;32;22mMyPet[m] [mExp calculation mode: MyPet[m
[03:11:41] [Server thread/INFO]: [[0;32;22mMyPet[m] [mConnect to MySQL database...[m
[03:11:41] [Server thread/INFO]: [[0;32;22mMyPet[m] [mMySQL connection successful.[m

### Plugin list:
___A list of your plugins___
OreBroadcast (1.0)             
KeepItems (1.3.2)              
NoMine (1.0)                   
PlaceholderAPI (2.9.2-DEV-57)  
ConsoleScheduler (1.4.6.0)     
NametagEdit (4.3.0)            
PandaWire (1.0.8-SNAPSHOT)     
GuiCreationTool (4.4)          
OneTimeUse (2.2)               
PvPToggle (1.0.0)              
ConsoleSpamFix (1.6.1)         
Core (0.1.7)                   
AsyncKeepAlive (1.1)           
SkinsRestorer (13.5.1-SNAPSHOT) 
NoPlugins (7.0)                
Multikills (1.9-git-2f36501)   
Yum (2.7.10-git-42ed)          
AT (0.3)                       
ViaVersion (1.6.0)             
ViaBackwards (2.3.1)           
CoreProtect (2.15.1)           
Itemizer (3.5)                 
dynmap (3.0-beta-2-138)        
LuckPerms (4.3.2)              
WorldEdit (7.0.0-SNAPSHOT;)    
DragonEggDrop (1.6.0)          
OpenInv (3.3.6)                
FleshToLeather (1.01)          
AutoMessage (2.5.5)            
NoSpawnerChange (2.0)          
AdvancedBan (2.1.5-RELEASE)    
WorldBorder (1.8.7)            
PAPI-ChestCommands (1.0.1)     
IronElevators (1.1)            
Fireworks (1.5.0)              
ProtocolLib (4.4.0)            
Multiverse-Core (2.6.0-b738)   
Limitedheight (0.0.1)          
RedPacket (1.0)                
AdminEssentials (2.1)          
DeluxeMenus (1.10.5)           
BlocksHub (3.0.0)              
MiaoBoard (2.4.1-git-1565c)    
LangUtils (1.9)                
LoreLimit (1.2)                
mcMMO (1.6.0-SNAPSHOT)         
TownBank (1.0)                 
Vault (1.7.1-b91)              
Lores (1.4.1)                  
TimeGivesYouMoney (1.2.2)      
NeverLag (1.3.0)               
HolographicDisplays (2.3.1)    
WorldGuard (7.0.0-SNAPSHOT;)   
SignColors (1.0.1)             
ChestCommands (3.1.4)          
ChatItem (1.3.6.4)             
GeneralMarket (5.2)            
TradePlus (3.12)               
Multiverse-NetherPortals (maven-version-n) 
Orebfuscator4 (4.4.2)          
AntiXRay (1.8.6)               
Essentials (2.15.0.52)         
ChatInjector (1.0.0)           
Stickers (1.4.13)              
mcMMOAction (2.3.2)            
NyaaCore (6.2.258-mc1.13.)     
DeluxeChat (1.13.2)            
Citizens (2.0.24-SNAPSHOT)     
Shopkeepers (2.4.1)            
Residence (4.8.3.1)            
EssentialsChat (2.15.0.52)     
RFChairs (4.3)                 
ScriptBlockPlus (1.6.5)        
RPGItems (3.6.459-mc1.13.)     
PixelVip (2.0.4)               
QuickShop (Reremake 1.3.0.)    
CitizensCMD (2.1)              
LockettePro (2.8.5-1.13.2)     
MoreFish (2.2.3)               
EssentialsProtect (2.15.0.52)  
EssentialsAntiBuild (2.15.0.52) 
ServerSigns (4.5.1)            
EssentialsSpawn (2.15.0.52)    
TitleManager (2.1.3)           
Bank (3.0.6)                   
MyPet (3.0)                    
Jobs (4.9.3)                   

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
PaperSpigot 1.13.2 build#469
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by mikroskeem** [comment]
*sighs* It's Paper not PaperSpigot.

Can you provide Spigot version as well where things work for you?  
This does not make any sense, this smells definitely a problem with MySQL server connection and/or you were just lucky to start your server while it was down/slow/not responding whatever.

**Comment by electronicboy** [comment]
Closing due to inactivity, Worth noting, while the library is shaded into our jars, we do not modify or touch these libraries in any capacity, making it very unlikely that this is actually an issue with Paper
