### ISSUE TITLE
Server Crash: Ticking player

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1743]
### Link/paste of stack trace
[https://pastebin.com/ca9j21kc](https://pastebin.com/ca9j21kc)

### Plugin list:
Wild v2.3
WorldEdit v7.0.0-beta-01;8975469
Essentials v2.15.0.55
EssentialsSpawn v2.15.0.55
EssentialsChat v2.15.0.55
WorldGuard v7.0.0-beta01;01dfebe

### Actions to reproduce (if known):
Unsure how to reproduce, happened overnight.

### Paper build number:
Paper 476

**Comment by EbonJaeger** [comment]
I am also experiencing this on Paper 488.

The console is spammed with a lot of these errors. The chunk coords are different, but in the same area; they don't vary by much. We have a world border in place (using the vanilla commands), but I don't think these coords are quite near it. There was a player flying quickly, and may have been in the area, however.
```java
[18:01:22] [PaperChunkGen-Neptune/ERROR]: Couldn't generate chunk (Neptune:381,2306)
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_191]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) ~[?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_191]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) ~[?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SchedulerBatch.java:38) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.SchedulerBatch.add(SchedulerBatch.java:33) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.generateChunk(PaperAsyncChunkProvider.java:405) ~[patched_1.13.2.jar:git-Paper-488]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor$PendingTask.run(PriorityQueuedExecutor.java:273) ~[patched_1.13.2.jar:git-Paper-488]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:196) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.requestChunk(PaperAsyncChunkProvider.java:197) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.loadOrGenerateChunk(PaperAsyncChunkProvider.java:154) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.getChunkAt(PaperAsyncChunkProvider.java:150) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:112) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.getChunkAt(PaperAsyncChunkProvider.java:136) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:216) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.StructureGenerator.generate(StructureGenerator.java:49) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.WorldGenDecoratorEmpty.a(SourceFile:16) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.WorldGenDecoratorEmpty.a(SourceFile:13) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.WorldGenFeatureComposite.a(SourceFile:27) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.BiomeBase.a(BiomeBase.java:302) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.addDecorations(ChunkGeneratorAbstract.java:98) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.addDecorations(NormalChunkGenerator.java:59) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkTaskDecorate.a(SourceFile:12) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:109) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:16) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_191]
	... 42 more
```

The last stacktrace before the server quits is different:
```java
[18:01:22] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Ticking player
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:484) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:432) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1470) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:357) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:154) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalStateException: Should always be able to create a chunk!
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:392) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:385) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.World.getFluid(World.java:825) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Entity.a(Entity.java:1293) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityHuman.dg(EntityHuman.java:214) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:161) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:403) ~[patched_1.13.2.jar:git-Paper-488]
	... 9 more
[18:01:22] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.IllegalStateException: Should always be able to create a chunk!
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:392) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:385) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.World.getFluid(World.java:825) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.Entity.a(Entity.java:1293) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityHuman.dg(EntityHuman.java:214) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:161) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:403) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:432) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1470) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:357) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:154) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by aikar** [comment]
Paper 520+ should fix this now
