### ISSUE TITLE
Tab completion in console does not work from IJ 2018.3.1

### ISSUE THREAD

**Issue by zachbr** [PaperMC/Paper#1744]
Not sure when this broke but I feel like its been this way for a while. Have to go through and see if this is all platforms or just mine or what.

```
[22:20:30 INFO]: Timings Reset
> help 				     <--- tab threw some chars in this line
[22:20:40 ERROR]: Caught previously unhandled exception :
[22:20:40 ERROR]: java.lang.ArithmeticException: / by zero
help
```

console becomes unresponsive at this point, no output, seemingly no input.

**Comment by Spottedleaf** [comment]
Did not happen on ubuntu 18.10, happened on windows 10.

EDIT#1:
nevermind the steps to reproduce are:

help->insert space->tab->enter
works on ubuntu and windows

EDIT#2:
`<DiscordBot> <S​po​tt​ed​le​af​> new developement has been made`
`<DiscordBot> <S​po​tt​ed​le​af​> help->tab->ezpz handles correctly`
`<DiscordBot> <S​po​tt​ed​le​af​> help->space->tab->how about git fucked`
`<DiscordBot> <S​po​tt​ed​le​af​> aaand it works on ubuntu now`
`<DiscordBot> <S​po​tt​ed​le​af​> mfw`
`<DiscordBot> <S​po​tt​ed​le​af​> appears to be something with how tabs get aligned`
`<DiscordBot> <S​po​tt​ed​le​af​> using spigot->tab gives an exception`
`<DiscordBot> <S​po​tt​ed​le​af​> using spigot->space->tab gives no exception and it works fine`
`<DiscordBot> <S​po​tt​ed​le​af​> except for the fact that tab doesn't work`

**Comment by stephan-gh** [comment]
I'm pretty sure tab completion does not really work at all in IntelliJ IDEA. However, when you press tab it seems to insert an actual tab character into the command line. As soon as you press enter, JLine reads the tab character, and will try to do completion.

It fails with an `ArithmeticException` in JLine, when it attempts to order the command suggestions in columns based on the terminal width. Since IntelliJ IDEA only provides a "dumb" terminal, the width is unknown (`0`), causing this exception.

```
java.lang.ArithmeticException: / by zero
	at org.jline.reader.impl.LineReaderImpl.toColumns(LineReaderImpl.java:4749) ~[jline-reader-3.9.0.jar:?]
	at org.jline.reader.impl.LineReaderImpl.toColumns(LineReaderImpl.java:4724) ~[jline-reader-3.9.0.jar:?]
	at org.jline.reader.impl.LineReaderImpl.computePost(LineReaderImpl.java:4689) ~[jline-reader-3.9.0.jar:?]
	at org.jline.reader.impl.LineReaderImpl.computePost(LineReaderImpl.java:4642) ~[jline-reader-3.9.0.jar:?]
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:4531) ~[jline-reader-3.9.0.jar:?]
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4149) ~[jline-reader-3.9.0.jar:?]
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:3875) ~[jline-reader-3.9.0.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:585) ~[jline-reader-3.9.0.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404) ~[jline-reader-3.9.0.jar:?]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:157) ~[terminalconsoleappender-1.1.1.jar:?]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140) ~[terminalconsoleappender-1.1.1.jar:?]
	at com.destroystokyo.paper.console.PaperConsole.start(PaperConsole.java:29) ~[classes/:?]
	at net.minecraft.server.DedicatedServer$2.run(DedicatedServer.java:83) ~[classes/:?]
```

We don't really want to run completion after "enter" (there can be more behind the tab), but I'm not sure what's the best way to avoid it. It's definitely an issue in JLine.

**Comment by zachbr** [comment]
I think all of our collective limited time is going to be better spent on useful things rather than working around weird issues in a 'dumb' terminal that only we will be using.
