### ISSUE TITLE
 Exception in thread "Server console handler" com.sun.jna.LastErrorException: [5] Inp ut/output error

### ISSUE THREAD

**Issue by 9hrack** [PaperMC/Paper#1745]
### Link/paste of stack trace

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___
```
[12:00:52] [Thread-38/INFO]: [Notice] The server is going to restart!
[12:00:52] [Server thread/INFO]: Stopping server
[12:00:52] [Server thread/INFO]: [RandomCoords] Disabling RandomCoords v0.6.2-RELEASE
[12:00:53] [User Authenticator #74/INFO]: UUID of player KAQK is afb5541f-7ab3-473d-ad47-402b44d60784
[12:00:54] [User Authenticator #74/INFO]: UUID of player PANIC1111 is 49d66ab1-637d-4d64-a96a-beb435ab0e0a
[12:00:55] [User Authenticator #74/INFO]: UUID of player _Daehyun_Devil_ is 4ae87fdb-63a1-4fcc-b9ed-c5bf0bd4f70e
[12:00:55] [User Authenticator #75/INFO]: UUID of player victor0524 is 735550cc-a120-4ba4-9335-9f15d08fa59f
[12:00:55] [User Authenticator #74/INFO]: UUID of player alsgk1 is 56a15341-5d2c-443c-b19d-32b5c603fd70
[12:00:56] [User Authenticator #74/INFO]: UUID of player neulbonb is 4f113887-fa3c-4c57-b7ac-0992636455c0
[12:00:56] [User Authenticator #75/INFO]: UUID of player rkddPcks is 530f0dfa-263b-4267-a5ba-62c8fe2a0778
[12:00:57] [User Authenticator #75/INFO]: UUID of player DONGSDEN is f7e57173-85e7-47b8-8749-482fecaef125
[12:00:58] [User Authenticator #75/INFO]: UUID of player Hiter123 is 3e95f384-3dbf-46f2-b7d2-57729222aaf9
[12:00:59] [User Authenticator #75/INFO]: UUID of player KAF_Chino is 6391d4d8-0907-4ef8-a68d-1990393fd26c
[12:01:02] [User Authenticator #75/INFO]: UUID of player neulbonb is 4f113887-fa3c-4c57-b7ac-0992636455c0
[12:01:05] [User Authenticator #75/INFO]: UUID of player victor0524 is 735550cc-a120-4ba4-9335-9f15d08fa59f
[12:01:15] [User Authenticator #75/INFO]: UUID of player KAF_Chino is 6391d4d8-0907-4ef8-a68d-1990393fd26c
[12:01:16] [User Authenticator #75/INFO]: UUID of player DONGSDEN is f7e57173-85e7-47b8-8749-482fecaef125
[12:01:25] [User Authenticator #75/INFO]: UUID of player Hae_an is 4fc98dcb-0354-49d6-bedf-328051a92b1d
[12:01:26] [User Authenticator #75/INFO]: UUID of player victor0524 is 735550cc-a120-4ba4-9335-9f15d08fa59f
[12:01:27] [User Authenticator #75/INFO]: UUID of player Hiter123 is 3e95f384-3dbf-46f2-b7d2-57729222aaf9
[12:01:29] [User Authenticator #75/INFO]: UUID of player rinkis6 is bea50287-c101-4e7f-a88f-9531b99af8e3
[12:01:29] [User Authenticator #75/INFO]: UUID of player cannon_penguin is d39f5b6d-7f8d-4433-bd21-a536e38a8638
[12:01:31] [User Authenticator #75/INFO]: UUID of player dinosur1020 is 9ee492ed-1f39-465e-b380-ff607f31783e
[12:01:31] [User Authenticator #75/INFO]: UUID of player OandB is ea8814b7-013f-417c-ad82-3b143744e3db
[12:01:31] [User Authenticator #74/INFO]: UUID of player DONGSDEN is f7e57173-85e7-47b8-8749-482fecaef125
[12:01:35] [User Authenticator #74/INFO]: UUID of player Hae_an is 4fc98dcb-0354-49d6-bedf-328051a92b1d
[12:01:36] [User Authenticator #74/INFO]: UUID of player Hwalee is c440f6e8-59f6-4e13-a585-4e3ab3befca3
[12:01:36] [User Authenticator #74/INFO]: UUID of player PANIC1111 is 49d66ab1-637d-4d64-a96a-beb435ab0e0a
[12:01:38] [User Authenticator #74/INFO]: UUID of player neulbonb is 4f113887-fa3c-4c57-b7ac-0992636455c0
[12:01:38] [User Authenticator #74/INFO]: UUID of player Kelly_green is 3c7c2f84-04c3-4571-9258-ee5aaa57d498
[12:01:42] [User Authenticator #74/INFO]: UUID of player weliade357 is 6559e70f-2d35-49de-b8d4-d30f05a25f39
[12:01:45] [User Authenticator #74/INFO]: UUID of player DONGSDEN is f7e57173-85e7-47b8-8749-482fecaef125
[12:01:50] [User Authenticator #74/INFO]: UUID of player Hwalee is c440f6e8-59f6-4e13-a585-4e3ab3befca3
[12:01:55] [User Authenticator #74/INFO]: UUID of player C96_C4Terrorist is 02eb9eee-2d10-4fef-a011-5fb6e4f033d7
[12:01:56] [Server console handler/WARN]: Exception in thread "Server console handler" com.sun.jna.LastErrorException: [5] Input/output error
[12:01:56] [Server console handler/WARN]:       at com.sun.jna.Native.invokeVoid(Native Method)
[12:01:56] [Server console handler/WARN]:       at com.sun.jna.Function.invoke(Function.java:408)
[12:01:56] [Server console handler/WARN]:       at com.sun.jna.Function.invoke(Function.java:354)
[12:01:56] [Server console handler/WARN]:       at com.sun.jna.Library$Handler.invoke(Library.java:244)
[12:01:56] [Server console handler/WARN]:       at com.sun.proxy.$Proxy18.tcgetattr(Unknown Source)
[12:01:56] [Server console handler/WARN]:       at org.jline.terminal.impl.jna.linux.LinuxNativePty.doSetAttr(LinuxNativePty.java:84)
[12:01:56] [Server console handler/WARN]:       at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:21)
[12:01:56] [Server console handler/WARN]:       at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52)
[12:01:56] [Server console handler/WARN]:       at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:628)
[12:01:56] [Server console handler/WARN]:       at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404)
[12:01:56] [Server console handler/WARN]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:157)
[12:01:56] [Server console handler/WARN]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140)
[12:01:56] [Server console handler/WARN]:       at net.minecraft.server.v1_12_R1.DedicatedServer$2.run(DedicatedServer.java:77)
[12:01:56] [SIGCONT handler/WARN]: Exception in thread "SIGCONT handler" com.sun.jna.LastErrorException: [5] Input/output error
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Native.invokeVoid(Native Method)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Function.invoke(Function.java:408)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Function.invoke(Function.java:354)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Library$Handler.invoke(Library.java:244)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.proxy.$Proxy18.tcgetattr(Unknown Source)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.jna.linux.LinuxNativePty.getAttr(LinuxNativePty.java:76)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:44)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:117)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.reader.impl.LineReaderImpl.handleSignal(LineReaderImpl.java:956)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:81)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.utils.Signals.lambda$register$1(Signals.java:51)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.proxy.$Proxy22.handle(Unknown Source)
[12:01:56] [SIGCONT handler/WARN]:      at sun.misc.Signal$1.run(Signal.java:212)
[12:01:56] [SIGCONT handler/WARN]:      at java.lang.Thread.run(Thread.java:748)
[12:01:56] [SIGCONT handler/WARN]: Exception in thread "SIGCONT handler" com.sun.jna.LastErrorException: [5] Input/output error
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Native.invokeVoid(Native Method)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Function.invoke(Function.java:408)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Function.invoke(Function.java:354)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Library$Handler.invoke(Library.java:244)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.proxy.$Proxy18.tcgetattr(Unknown Source)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.jna.linux.LinuxNativePty.getAttr(LinuxNativePty.java:76)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:44)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:117)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.reader.impl.LineReaderImpl.handleSignal(LineReaderImpl.java:956)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:81)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.utils.Signals.lambda$register$1(Signals.java:51)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.proxy.$Proxy22.handle(Unknown Source)
[12:01:56] [SIGCONT handler/WARN]:      at sun.misc.Signal$1.run(Signal.java:212)
[12:01:56] [SIGCONT handler/WARN]:      at java.lang.Thread.run(Thread.java:748)
[centos@ip-172-26-0-223 analysis]$ cat 2018-12-12-2.log  | less
[12:01:56] [Server console handler/WARN]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140)
[12:01:56] [Server console handler/WARN]:       at net.minecraft.server.v1_12_R1.DedicatedServer$2.run(DedicatedServer.java:77)
[12:01:56] [SIGCONT handler/WARN]: Exception in thread "SIGCONT handler" com.sun.jna.LastErrorException: [5] Input/output error
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Native.invokeVoid(Native Method)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Function.invoke(Function.java:408)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Function.invoke(Function.java:354)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Library$Handler.invoke(Library.java:244)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.proxy.$Proxy18.tcgetattr(Unknown Source)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.jna.linux.LinuxNativePty.getAttr(LinuxNativePty.java:76)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:44)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:117)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.reader.impl.LineReaderImpl.handleSignal(LineReaderImpl.java:956)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:81)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.utils.Signals.lambda$register$1(Signals.java:51)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.proxy.$Proxy22.handle(Unknown Source)
[12:01:56] [SIGCONT handler/WARN]:      at sun.misc.Signal$1.run(Signal.java:212)
[12:01:56] [SIGCONT handler/WARN]:      at java.lang.Thread.run(Thread.java:748)
[12:01:56] [SIGCONT handler/WARN]: Exception in thread "SIGCONT handler" com.sun.jna.LastErrorException: [5] Input/output error
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Native.invokeVoid(Native Method)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Function.invoke(Function.java:408)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Function.invoke(Function.java:354)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.jna.Library$Handler.invoke(Library.java:244)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.proxy.$Proxy18.tcgetattr(Unknown Source)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.jna.linux.LinuxNativePty.getAttr(LinuxNativePty.java:76)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:44)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:117)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.reader.impl.LineReaderImpl.handleSignal(LineReaderImpl.java:956)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:81)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
[12:01:56] [SIGCONT handler/WARN]:      at org.jline.utils.Signals.lambda$register$1(Signals.java:51)
[12:01:56] [SIGCONT handler/WARN]:      at com.sun.proxy.$Proxy22.handle(Unknown Source)
[12:01:56] [SIGCONT handler/WARN]:      at sun.misc.Signal$1.run(Signal.java:212)
[12:01:56] [SIGCONT handler/WARN]:      at java.lang.Thread.run(Thread.java:748)
```

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

I cannot list my plugins here because others can see

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

It's not obvious. but I can say there were lots of lag and I executed the restart command
and it crashed.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

Git-paper-1592

**Comment by electronicboy** [comment]
```
[12:01:56] [Server console handler/WARN]: Exception in thread "Server console handler" com.sun.jna.LastErrorException: [5] Input/output error
[12:01:56] [Server console handler/WARN]: at com.sun.jna.Native.invokeVoid(Native Method)
```

How are you running your server, e.g. what terminal emulator? Are you using anything like screen?

**Comment by 9hrack** [comment]
I'm using screen on CentOS 7!

**Comment by LucidusMC** [comment]
I also got this, I'm using screen on Ubuntu 16.04
Paper 1.13.2 605

https://pastebin.com/WhwRL3Ky

**Comment by Leohige** [comment]
I got this, I'm using screen on Debian 9
