### ISSUE TITLE
Description: Exception in server tick loop

### ISSUE THREAD

**Issue by 9hrack** [PaperMC/Paper#1746]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

BELOW IS THE CRASH-REPORT

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 12/11/18 2:13 AM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
        at net.minecraft.server.v1_12_R1.EntityTracker.untrackEntity(EntityTracker.java:160)
        at net.minecraft.server.v1_12_R1.WorldManager.b(WorldManager.java:29)
        at net.minecraft.server.v1_12_R1.World.c(World.java:1229)
        at net.minecraft.server.v1_12_R1.WorldServer.c(WorldServer.java:1244)
        at net.minecraft.server.v1_12_R1.World.kill(World.java:1268)
        at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:465)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1153)
        at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:352)
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
        at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 3.10.0-957.1.3.el7.x86_64
        Java Version: 1.8.0_191, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 3708939360 bytes (3537 MB) / 9663676416 bytes (9216 MB) up to 9663676416 bytes (9216 MB)
        JVM Flags: 12 total; -Xms9G -Xmx9G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled
        IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
        CraftBukkit Information:
   Running: Paper version git-Paper-1592 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) true

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

not known..

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-1592

**Comment by Duartteno** [comment]
same issue here

**Comment by electronicboy** [comment]
`java.util.ConcurrentModificationException`
Something modified the entity tracker in an unsafe manner, this is generally down to plugins modifying this state improperly (nor can I see any indication that the server is at fault here)

**Comment by userdev265scratchandpython** [comment]
i have no plugins but same type of error
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2025-01-02 09:24:39
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to bind to port
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:271)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.BindException: Cannot assign requested address: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:561)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:922)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:380)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 408653480 bytes (389 MiB) / 1073741824 bytes (1024 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6614
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MiB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.00
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.00
	Memory slot #3 type: DDR4
	Virtual memory max (MiB): 61322.29
	Virtual memory used (MiB): 9791.49
	Swap memory total (MiB): 28672.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 153453.88, total: 802001.00
	Space in storage for workdir (MiB): available: 153453.88, total: 802001.00
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	CraftBukkit Information: 
   BrandInfo: Paper (papermc:paper) version 1.21.4-71-main@83995d7e (2025-01-01T21:03:20Z)
   Running: Paper version 1.21.4-71-83995d7e (MC: 1.21.4) (Implementing API version 1.21.4-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Notification Thread: [], WAITING Paper I/O Worker #0: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.doRun(PrioritisedQueueExecutorThread.java:107), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:49)], RUNNABLE Netty Server IO #0: [java.base@21.0.5/sun.nio.ch.WEPoll.wait(Native Method), java.base@21.0.5/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:114), java.base@21.0.5/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130), java.base@21.0.5/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:147), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:879), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Timer hack thread: [java.base@21.0.5/java.lang.Thread.sleep0(Native Method), java.base@21.0.5/java.lang.Thread.sleep(Thread.java:509), net.minecraft.Util$8.run(Util.java:905)], RUNNABLE Attach Listener: [], WAITING Paper Common Worker #3: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.doRun(PrioritisedQueueExecutorThread.java:107), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:49)], TIMED_WAITING Common-Cleaner: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1852), java.base@21.0.5/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71), java.base@21.0.5/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143), java.base@21.0.5/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218), java.base@21.0.5/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583), java.base@21.0.5/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)], WAITING Worker-Main-3: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371), java.base@21.0.5/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893), java.base@21.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809), java.base@21.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Keep-Alive-Timer: [java.base@21.0.5/java.lang.Thread.sleep0(Native Method), java.base@21.0.5/java.lang.Thread.sleep(Thread.java:509), java.base@21.0.5/sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:238), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583), java.base@21.0.5/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)], WAITING Paper Common Worker #0: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.doRun(PrioritisedQueueExecutorThread.java:107), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:49)], TIMED_WAITING Paper Watchdog Thread: [java.base@21.0.5/java.lang.Thread.sleep0(Native Method), java.base@21.0.5/java.lang.Thread.sleep(Thread.java:509), org.spigotmc.WatchdogThread.run(WatchdogThread.java:155)], RUNNABLE Reference Handler: [java.base@21.0.5/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@21.0.5/java.lang.ref.Reference.processPendingReferences(Reference.java:246), java.base@21.0.5/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)], TIMED_WAITING Yggdrasil Key Fetcher: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1763), java.base@21.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@21.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.5/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.5/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.5/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:235), java.base@21.0.5/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:338), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Server console handler: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1852), org.jline.utils.NonBlockingPumpReader.read(NonBlockingPumpReader.java:78), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:56), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:109)], WAITING Finalizer: [java.base@21.0.5/java.lang.Object.wait0(Native Method), java.base@21.0.5/java.lang.Object.wait(Object.java:366), java.base@21.0.5/java.lang.Object.wait(Object.java:339), java.base@21.0.5/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48), java.base@21.0.5/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158), java.base@21.0.5/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89), java.base@21.0.5/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)], TIMED_WAITING pool-9-thread-1: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1763), java.base@21.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@21.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)], WAITING Paper Common Worker #1: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.doRun(PrioritisedQueueExecutorThread.java:107), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:49)], TIMED_WAITING JNA Cleaner: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1852), java.base@21.0.5/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71), java.base@21.0.5/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143), java.base@21.0.5/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218), com.sun.jna.internal.Cleaner$CleanerThread.run(Cleaner.java:154)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371), java.base@21.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519), java.base@21.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780), java.base@21.0.5/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725), java.base@21.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712), java.base@21.0.5/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:81), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:73)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.5/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.5/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.5/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:235), java.base@21.0.5/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:338), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Worker-Main-2: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:449), java.base@21.0.5/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1891), java.base@21.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809), java.base@21.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)], WAITING Paper Common Worker #2: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.doRun(PrioritisedQueueExecutorThread.java:107), ca.spottedleaf.concurrentutil.executor.thread.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:49)], RUNNABLE WindowsStreamPump: [org.jline.nativ.Kernel32.WaitForSingleObject(Native Method), org.jline.terminal.impl.jni.win.NativeWinSysTerminal.processConsoleInput(NativeWinSysTerminal.java:210), org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:469), org.jline.terminal.impl.AbstractWindowsTerminal$$Lambda/0x0000020083206908.run(Unknown Source), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)], WAITING Worker-Main-1: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371), java.base@21.0.5/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893), java.base@21.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809), java.base@21.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)], TIMED_WAITING ForkJoinPool.commonPool-worker-1: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:449), java.base@21.0.5/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1891), java.base@21.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809), java.base@21.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.5/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.5/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.5/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:235), java.base@21.0.5/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:338), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.5/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.5/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.5/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:235), java.base@21.0.5/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:338), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)], RUNNABLE Server thread: [java.base@21.0.5/java.lang.Thread.dumpThreads(Native Method), java.base@21.0.5/java.lang.Thread.getAllStackTraces(Thread.java:2521), org.bukkit.craftbukkit.CraftCrashReport.get(CraftCrashReport.java:35), org.bukkit.craftbukkit.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.setDetail(SystemReport.java:71), net.minecraft.CrashReport.<init>(CrashReport.java:38), net.minecraft.server.MinecraftServer.constructOrExtractCrashReport(MinecraftServer.java:1347), net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281), net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310), net.minecraft.server.MinecraftServer$$Lambda/0x0000020083dc72a8.run(Unknown Source), java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)],}
   
   Force Loaded Chunks: {}
	Server Running: true
	Player Count: 0 / 20; []
	Active Data Packs: vanilla, file/bukkit, paper (incompatible)
	Available Data Packs: file/bukkit, minecart_improvements, paper (incompatible), redstone_experiments, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -3866223592147705362
	Suppressed Exceptions: ~~NONE~~
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

**Comment by electronicboy** [comment]
> Cannot assign requested address: bind

invalid IP address (also, please don't bump 6 year old issues)

**Comment by userdev265scratchandpython** [comment]
sorry, bing shown me this one, and no IP is set in server.properties
