### ISSUE TITLE
Bug on world creation

### ISSUE THREAD

**Issue by ZenZonEcht** [PaperMC/Paper#1760]
[16:48:52] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_191]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_191]
	at com.destroystokyo.paper.PaperWorldMap$1$1.next(PaperWorldMap.java:32) ~[patched_1.13.2.jar:git-Paper-474]
	at com.destroystokyo.paper.PaperWorldMap$1$1.next(PaperWorldMap.java:22) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1066) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-474]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by TheFlagCourier** [comment]
Update your Paper build, see if that "magically fixes" it. Current one for 1.13 is 486, you look to be on build 474.

Notable:
- 475 and 483 are upstream and include Mappings Updates (a2ad49b22fed8c6e3fb078de52a404460b7ea776 & 3496f2d7e494b44d152c02e1779881f4e55813c1)
- 484 (1f59f78c6f1227be5d013f6b253a1f3913cee8cd) implements `SPIGOT-4534: Only call event for new chunks`

**Comment by electronicboy** [comment]
How are you creating the world? Looks like maybe you're doing it async (which, would give a good potential for it to blow up like it has done here)?
