### ISSUE TITLE
Exception in thread "SIGCONT handler" -> server crash

### ISSUE THREAD

**Issue by 28Pollux28** [PaperMC/Paper#1768]
### Link/paste of stack trace

[02:07:47] [main/INFO]: Loaded 0 recipes
[02:07:47] [Server thread/INFO]: Starting minecraft server version 1.13.2
[02:07:47] [Server thread/INFO]: Loading properties
[02:07:47] [Server thread/INFO]: Default game type: SURVIVAL
[02:07:47] [Server thread/INFO]: This server is running Paper version git-Paper-480 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[02:07:47] [Server thread/INFO]: Debug logging is disabled
[02:07:47] [Server thread/INFO]: Server Ping Player Sample Count: 12
[02:07:47] [Server thread/INFO]: Using 4 threads for Netty based IO
[02:07:47] [Server thread/INFO]: Generating keypair
[02:07:48] [Server thread/INFO]: Starting Minecraft server on 149.202.2XX.XX:25XXX
[02:07:48] [Server thread/INFO]: Using epoll channel type
[02:07:48] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[02:07:48] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[02:07:48] [Server thread/INFO]: Preparing level "world"
[02:07:48] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[02:07:49] [Server thread/INFO]: Loaded 524 recipes
[02:07:50] [Server thread/INFO]: -------- World Settings For [world] --------
[02:07:50] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[02:07:50] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[02:07:50] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[02:07:50] [Server thread/INFO]: Random Lighting Updates: false
[02:07:50] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[02:07:50] [Server thread/INFO]: Cactus Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Cane Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Melon Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Sapling Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Wheat Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Vine Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Max TNT Explosions: 100
[02:07:50] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[02:07:50] [Server thread/INFO]: Mob Spawn Range: 8
[02:07:50] [Server thread/INFO]: Experience Merge Radius: 3.0
[02:07:50] [Server thread/INFO]: Item Despawn Rate: 6000
[02:07:50] [Server thread/INFO]: Item Merge Radius: 2.5
[02:07:50] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[02:07:50] [Server thread/INFO]: View Distance: 10
[02:07:50] [Server thread/INFO]: Arrow Despawn Rate: 1200
[02:07:50] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[02:07:50] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[02:07:50] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[02:07:50] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[02:07:50] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[02:07:50] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[02:07:50] [Server thread/INFO]: Random Lighting Updates: false
[02:07:50] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[02:07:50] [Server thread/INFO]: Cactus Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Cane Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Melon Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Sapling Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Wheat Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Vine Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[02:07:50] [Server thread/INFO]: Max TNT Explosions: 100
[02:07:50] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[02:07:50] [Server thread/INFO]: Mob Spawn Range: 8
[02:07:50] [Server thread/INFO]: Experience Merge Radius: 3.0
[02:07:50] [Server thread/INFO]: Item Despawn Rate: 6000
[02:07:50] [Server thread/INFO]: Item Merge Radius: 2.5
[02:07:50] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[02:07:50] [Server thread/INFO]: View Distance: 10
[02:07:50] [Server thread/INFO]: Arrow Despawn Rate: 1200
[02:07:50] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[02:07:50] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[02:07:51] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[02:07:51] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[02:07:51] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[02:07:51] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[02:07:51] [Server thread/INFO]: Random Lighting Updates: false
[02:07:51] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[02:07:51] [Server thread/INFO]: Cactus Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: Cane Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: Melon Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: Sapling Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: Wheat Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: Vine Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[02:07:51] [Server thread/INFO]: Max TNT Explosions: 100
[02:07:51] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[02:07:51] [Server thread/INFO]: Mob Spawn Range: 8
[02:07:51] [Server thread/INFO]: Experience Merge Radius: 3.0
[02:07:51] [Server thread/INFO]: Item Despawn Rate: 6000
[02:07:51] [Server thread/INFO]: Item Merge Radius: 2.5
[02:07:51] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[02:07:51] [Server thread/INFO]: View Distance: 10
[02:07:51] [Server thread/INFO]: Arrow Despawn Rate: 1200
[02:07:51] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[02:07:51] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[02:07:51] [Server thread/INFO]: Preparing start region for level minecraft:overworld (Seed: 5405110612059805484)
[02:07:51] [Server thread/INFO]: Preparing start region for level minecraft:the_nether (Seed: 5405110612059805484)
[02:07:51] [Server thread/INFO]: Preparing start region for level minecraft:the_end (Seed: 5405110612059805484)
[02:07:51] [Server thread/INFO]: Time elapsed: 126 ms
[02:07:51] [Server thread/INFO]: Done (2.887s)! For help, type "help"
[02:07:51] [Server thread/INFO]: Starting GS4 status listener
[02:07:51] [Server thread/INFO]: Starting remote control listener
[02:07:51] [Query Listener #1/INFO]: Query running on 149.202.2XX.XX:25XXX
[02:07:51] [RCON Listener #2/INFO]: RCON running on `149.202.2XX.XX:27XXX`
[02:07:51] [Server thread/INFO]: Timings Reset
[02:20:13] [Server console handler/ERROR]: Caught previously unhandled exception :
[02:20:13] [Server console handler/ERROR]: com.sun.jna.LastErrorException: [5] Erreur d'entrée/sortie
[02:20:13] [Thread-1/INFO]: Stopping server
[02:20:13] [SIGCONT handler/WARN]: Exception in thread "SIGCONT handler" com.sun.jna.LastErrorException: [5] Erreur d'entrée/sortie
[02:20:13] [SIGCONT handler/WARN]: 	at com.sun.jna.Native.invokeVoid(Native Method)
[02:20:13] [SIGCONT handler/WARN]: 	at com.sun.jna.Function.invoke(Function.java:408)
[02:20:13] [SIGCONT handler/WARN]: 	at com.sun.jna.Function.invoke(Function.java:354)
[02:20:13] [SIGCONT handler/WARN]: 	at com.sun.jna.Library$Handler.invoke(Library.java:244)
[02:20:13] [SIGCONT handler/WARN]: 	at com.sun.proxy.$Proxy18.tcgetattr(Unknown Source)
[02:20:13] [SIGCONT handler/WARN]: 	at org.jline.terminal.impl.jna.linux.LinuxNativePty.getAttr(LinuxNativePty.java:76)
[02:20:13] [SIGCONT handler/WARN]: 	at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:44)
[02:20:13] [SIGCONT handler/WARN]: 	at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:117)
[02:20:13] [SIGCONT handler/WARN]: 	at org.jline.reader.impl.LineReaderImpl.handleSignal(LineReaderImpl.java:956)
[02:20:13] [SIGCONT handler/WARN]: 	at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:81)
[02:20:13] [SIGCONT handler/WARN]: 	at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
[02:20:13] [SIGCONT handler/WARN]: 	at org.jline.utils.Signals.lambda$register$1(Signals.java:51)
[02:20:13] [SIGCONT handler/WARN]: 	at com.sun.proxy.$Proxy21.handle(Unknown Source)
[02:20:13] [SIGCONT handler/WARN]: 	at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
[02:20:13] [SIGCONT handler/WARN]: 	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:220)
[02:20:13] [SIGCONT handler/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

// END
I've got 5 similars logs if you want.
### Plugin list:
None

### Actions to reproduce (if known):
Appears on average 10-13 minutes after restart with and without players in world.

### Paper build number:
Paper version git-Paper-480 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by stephan-gh** [comment]
Duplicate of https://github.com/PaperMC/Paper/issues/911 and https://github.com/PaperMC/Paper/issues/1745.

Can you reproduce this every time you start the server?

**Comment by 28Pollux28** [comment]
It happend 5 times in a row and we just move on to the latest version of Paper. It was the same error both times and crashed the server. I cannot test anymore because i'm not the server administrator so I can't restart it but another error arrived
[20:15:33] [Server console handler/ERROR]: Caught previously unhandled exception :
[20:15:33] [Server console handler/ERROR]: com.sun.jna.LastErrorException: [5] Erreur d'entrée/sortie
EDIT: There were nobody on the server because of the time and no commands were executed so idk

**Comment by electronicboy** [comment]
The error suggests that you've got something on your server which is breaking the process, are you running the server under some form of resource limiter, maybe?

the sigcont handler shouldn't be getting invoked unless something on the system actually stopped the process in the first place

**Comment by 28Pollux28** [comment]
OK we are investigating on our side toward this. I keep you up if i've got any information more. 
Thanks a lot,
28Pollux28

**Comment by zachbr** [comment]
Closing as duplicate of #1745
