### ISSUE TITLE
1.12 Server crashes when loading chunk saved in 1.13

### ISSUE THREAD

**Issue by 9hrack** [PaperMC/Paper#1769]
### Link/paste of stack trace

the server crashes when loading newer version of chunk.
but the version of world is 1.12.2, and all other chunks are fine.
just some chunks have this error. I have no idea how to solve this problem

[06:20:45] [Chunk I/O Executor Thread-2/WARN]: java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 1631 > 1343
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at net.minecraft.server.v1_12_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:104)
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:83)
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:23)
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:16)
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:150)
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:95)
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:85)
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[06:20:45] [Chunk I/O Executor Thread-2/WARN]: at java.lang.Thread.run(Thread.java:748)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 1631 > 1343
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at net.minecraft.server.v1_12_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:104)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:83)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:23)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:16)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:150)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:95)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:85)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[06:20:45] [Chunk I/O Executor Thread-1/WARN]: at java.lang.Thread.run(Thread.java:748)
[06:20:45] [Thread-2/INFO]: Stopping server

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

I have this error when a player tries to load certain chunk.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-1592

**Comment by astei** [comment]
It appears you tried to load your world with 1.13 at some point. 1.13 made substantial changes to how chunks are stored on disk, and 1.12 can't read 1.13 worlds.

Your best bet is to restore from backups if you've got them.
