### ISSUE TITLE
Compatibility issue with VTV1 1594

### ISSUE THREAD

**Issue by DahunDev** [PaperMC/Paper#1777]
The issue is not occurred in original spigot, but in. Paperspigot occures.

SOMETIMES the command made by  variabletriggers (VTV1) is not working.

[13:34:25] [Server thread/INFO]: KitePro issued server command: /경고주기 KitePro_ 0
[13:34:25] [Thread-14595/WARN]: Exception in thread "Thread-14595" java.lang.IllegalStateException: Asynchronous Async Player Chunk Add!
[13:34:25] [Thread-14595/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[13:34:25] [Thread-14595/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerChunkMap.a(PlayerChunkMap.java:478)
[13:34:25] [Thread-14595/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:180)
[13:34:25] [Thread-14595/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerChunkMap.flagDirty(PlayerChunkMap.java:284)
[13:34:25] [Thread-14595/WARN]: 	at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:45)
[13:34:25] [Thread-14595/WARN]: 	at net.minecraft.server.v1_12_R1.World.notify(World.java:489)
[13:34:25] [Thread-14595/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntityCommand$1.i(TileEntityCommand.java:35)
[13:34:25] [Thread-14595/WARN]: 	at net.minecraft.server.v1_12_R1.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:340)
[13:34:25] [Thread-14595/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27)
[13:34:25] [Thread-14595/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcast(CraftServer.java:1343)
[13:34:25] [Thread-14595/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcastMessage(CraftServer.java:469)
[13:34:25] [Thread-14595/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:1928)
[13:34:25] [Thread-14595/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:478)
[13:34:25] [Thread-14595/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:478)
[13:34:25] [Thread-14595/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:478)
[13:34:25] [Thread-14595/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:478)
[13:34:25] [Thread-14595/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.run(ScriptInterpreter.java:328)
[13:34:25] [Thread-14595/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:34:25] [Server thread/INFO]: KitePro issued server command: /경고주기 KitePro_ 0
[13:34:25] [Thread-14596/WARN]: Exception in thread "Thread-14596" java.lang.IllegalStateException: Asynchronous Async Player Chunk Add!
[13:34:25] [Thread-14596/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[13:34:25] [Thread-14596/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerChunkMap.a(PlayerChunkMap.java:478)
[13:34:25] [Thread-14596/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:180)
[13:34:25] [Thread-14596/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerChunkMap.flagDirty(PlayerChunkMap.java:284)
[13:34:25] [Thread-14596/WARN]: 	at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:45)
[13:34:25] [Thread-14596/WARN]: 	at net.minecraft.server.v1_12_R1.World.notify(World.java:489)
[13:34:25] [Thread-14596/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntityCommand$1.i(TileEntityCommand.java:35)
[13:34:25] [Thread-14596/WARN]: 	at net.minecraft.server.v1_12_R1.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:340)
[13:34:25] [Thread-14596/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27)
[13:34:25] [Thread-14596/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcast(CraftServer.java:1343)
[13:34:25] [Thread-14596/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcastMessage(CraftServer.java:469)
[13:34:25] [Thread-14596/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:1928)
[13:34:25] [Thread-14596/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:478)
[13:34:25] [Thread-14596/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:478)
[13:34:25] [Thread-14596/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:478)
[13:34:25] [Thread-14596/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.Interpret(ScriptInterpreter.java:478)
[13:34:25] [Thread-14596/WARN]: 	at com.wizardscraft.scripting.ScriptInterpreter.run(ScriptInterpreter.java:328)
[13:34:25] [Thread-14596/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by zachbr** [comment]
Variable Triggers is adding players to a chunk map asynchronously. This ugly alert is letting you know what they're doing is bad, you should alert them to this issue so they can resolve it in a way that's most useful to them.

There is nothing here for us to fix.

**Comment by DahunDev** [comment]
> Variable Triggers is adding players to a chunk map asynchronously. This ugly alert is letting you know what they're doing is bad, you should alert them to this issue so they can resolve it in a way that's most useful to them.
> 
> There is nothing here for us to fix.

But, Why that errore not occures in original spigot 1.12.2

**Comment by zachbr** [comment]
We’ve added additional checks in Paper to warn of these cases.

It’s still just as bad to be doing this in Spigot, they just don’t warn you about it.

**Comment by DahunDev** [comment]
> We’ve added additional checks in Paper to warn of these cases.
> 
> It’s still just as bad to be doing this in Spigot, they just don’t warn you about it.

 BUT, in spigot the command made by Variable Triggers are always working,
But, in paper, the command made by Variable Triggers are sometimes not working. with that logs

**Comment by zachbr** [comment]
Yes, the async catcher catches the action.
Even if it didn’t, the nature of the action is that it could cause issues, hence why we warn you.

This is not our problem.
