### ISSUE TITLE
Paper 516 and Citizens error Entity#remove

### ISSUE THREAD

**Issue by digital-r** [PaperMC/Paper#1836]
### What behaviour is expected:
Citizens plugin loading without exception

### What behaviour is observed:
Exception are thrown and Citizens not loading:
[10:15:22] [Server thread/WARN]: [Citizens] Task #79 for Citizens v2.0.24-SNAPSHOT (build 1613) generated an exception
java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.remove(CraftPlayer.java:1943) ~[patched_1.13.2.jar:git-Paper-516]
	at net.citizensnpcs.npc.AbstractEntityController.remove(AbstractEntityController.java:35) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.entity.HumanController.remove(HumanController.java:120) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:228) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:143) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$2.run(Citizens.java:306) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-516]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-516]
	at java.lang.Thread.run(Thread.java:844) [?:?]

### Steps/models to reproduce:
Just try start server with Paper #516 and Citizens v2.0.24 build 1613 (lesser builds also affected)

### Paper build number:
git-Paper-516 (MC: 1.13.2)

### Anything else:
Link to issue report on Citizens Git:
https://github.com/CitizensDev/Citizens2/issues/1692

**Comment by zachbr** [comment]
517+
