### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by klister803** [PaperMC/Paper#1849]
### Plugin list:
See crash log

### Actions to reproduce (if known):
Server crashes after a while,  i can't find any reason

### Paper build number:
PAPER 522

**Comment by electronicboy** [comment]
```
 java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
    at net.minecraft.server.v1_13_R2.EntityTracker.updatePlayers(EntityTracker.java:192)
```

Something, more than likely a plugin, modified the entity tracker improperly
