### ISSUE TITLE
Data has changed and inventory lost

### ISSUE THREAD

**Issue by FunkyNico** [PaperMC/Paper#1863]
### Link/paste of stack trace

`[22:29:19 WARN]: Exception in thread "pool-7-thread-12" javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update ls_players set optlock=?, inventory_id=? where id=? and optlock=?] bind[null]
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:122)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:107)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:85)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:110)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:504)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:436)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:343)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:315)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629)
[22:29:19 WARN]:        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619)
[22:29:19 WARN]:        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$1.run(PlayerSession.java:48)
[22:29:19 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:29:19 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:29:19 WARN]:        at java.lang.Thread.run(Unknown Source)`

### Plugin list:
Plugins (16): ActionHealth*, CoreProtect, Essentials, EssentialsSpawn, eZProtector, FastLogin*, LoginSecurity*, LuckPerms, OreReplacerPlugin, PlaceholderAPI, ProtocolLib*, React*, SkinsRestorer, Vault*, VentureChat*, WorldEdit

### Actions to reproduce (if known):
Log in on the server.

### Paper build number:
git-Paper-522 (MC: 1.13.2)

**Comment by aikar** [comment]
Issue with the LoginSecurity plugin, need to take it up with them.

Can't believe someone actually used EBeans
