### ISSUE TITLE
command line help is broken.

### ISSUE THREAD

**Issue by cybertiger** [PaperMC/Paper#189]
### Description of issue:

java -jar paper.jar --help yields an exception.

Apparently present in spigot upstream for a long time, seems to be an issue with relocation of joptsimple.
### Paper build number:

Build 641 (taken from ci server because I don't currently have a real build to run /version on).
### Link/paste of stack trace

```
Exception in thread "main" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key org.bukkit.craftbukkit.libs.joptsimple.BuiltinHelpFormatter.option.header
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at org.bukkit.craftbukkit.libs.joptsimple.internal.Messages.message(Messages.java:42)
        at org.bukkit.craftbukkit.libs.joptsimple.BuiltinHelpFormatter.message(BuiltinHelpFormatter.java:553)
        at org.bukkit.craftbukkit.libs.joptsimple.BuiltinHelpFormatter.addHeaders(BuiltinHelpFormatter.java:315)
        at org.bukkit.craftbukkit.libs.joptsimple.BuiltinHelpFormatter.addRows(BuiltinHelpFormatter.java:202)
        at org.bukkit.craftbukkit.libs.joptsimple.BuiltinHelpFormatter.format(BuiltinHelpFormatter.java:98)
        at org.bukkit.craftbukkit.libs.joptsimple.OptionParser.printHelpOn(OptionParser.java:327)
        at org.bukkit.craftbukkit.libs.joptsimple.OptionParser.printHelpOn(OptionParser.java:313)
        at org.bukkit.craftbukkit.Main.main(Main.java:146)
```

**Comment by zachbr** [comment]
Worked around, seems to be fine. I assume it will be fine.
