### ISSUE TITLE
When Starting up the server, without plugins, it shows a error message

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1894]
### What behaviour is expected:
Just not this message!

### What behaviour is observed:
`2019-03-08 17:24:14,560 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile. java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:224)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:130)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.async.AsyncLoggerContext.start(AsyncLoggerContext.java:76)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
        at net.minecraft.server.v1_13_R2.MinecraftServer.<clinit>(MinecraftServer.java:72)
        at org.bukkit.craftbukkit.Main.main(Main.java:243)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.destroystokyo.paperclip.Utils.invoke(Utils.java:59)
        at com.destroystokyo.paperclip.Paperclip.run(Paperclip.java:155)
        at com.destroystokyo.paperclip.Main.main(Main.java:14)

2019-03-08 17:24:14,562 main ERROR Null object returned for RollingRandomAccessFile in Appenders.
2019-03-08 17:24:14,567 main ERROR Unable to locate appender "File" for logger config "root"`

### Steps/models to reproduce:
Start the server up with PaperMC build 563 using OpenJDK 11
### Plugin list:
None

### Paper build number:
563
### Anything else:
It did not send this error message in build Paper 551

**Comment by zachbr** [comment]
Looks like something added a log4j config somewhere. Cannot reproduce this with just the jar. Please provide additional information about your environment (panel, console, screen/tmux, etc) as well as a listing of files in the server root directory to ensure there's no log4j configs floating around.
