### ISSUE TITLE
Failed to handle packet for /75.102.176.13:49123 (NoSuchElementException)

### ISSUE THREAD

**Issue by TrentTheDude** [PaperMC/Paper#1905]
### Link/paste of stack trace

` [13:15:50 WARN]: Failed to handle packet for /75.102.176.13:49123
net.minecraft.server.v1_13_R2.ReportedException: Ticking player
at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:482) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:262) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1124) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-522]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.util.NoSuchElementException
at org.bukkit.craftbukkit.v1_13_R2.util.UnsafeList$Itr.next(UnsafeList.java:248) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:1105) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.World.getEntities(World.java:2400) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.EntityLiving.cN(EntityLiving.java:2404) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2372) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.EntityHuman.movementTick(EntityHuman.java:422) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2134) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:159) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:401) ~[patched_1.13.2.jar:git-Paper-522]
... 8 more
[13:15:50 INFO]: FroggyKnight lost connection: Internal server error`

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
Plugins (9): AugustineIntegration, AugustineQuests, AugustineRPG, AugustineShops, Citizens, Essentials*, PacketListenerApi*, ProtocolLib*, WorldEdit

### Actions to reproduce (if known):
No idea, logged in for abit and out of the blue it happened.

### Paper build number:
git-Paper-522, it's outdated I know haha, will update.

**Comment by TrentTheDude** [comment]
Edit: I updated the newest spigot release, no more problems.
