### ISSUE TITLE
TIMING_STACK_CORRUPT

### ISSUE THREAD

**Issue by Aster0** [PaperMC/Paper#1918]
Hello,

I restarted my server but it's still outputting these errors. I believe it was fine 30 minutes ago.

```
[22:40:30 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! ( TimingIdentifier{id=Minecraft:## Packet - PacketPlayInWindowClick}:co.aikar.timings.TimingHandler@1df)
java.lang.Throwable: null
at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:111) ~[patched_1.13.2.jar:git-Paper-584]
at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:95) ~[patched_1.13.2.jar:git-Paper-584]
at co.aikar.timings.TimingHandler.close(TimingHandler.java:178) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:16) ~[patched_1.13.2.jar:git-Paper-584]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-584]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[22:40:30 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! ( TimingIdentifier{id=Minecraft:Minecraft Scheduler}:co.aikar.timings.TimingHandler@1df)
java.lang.Throwable: null
at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:111) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1014) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-584]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

My timing report
https://timings.aikar.co/?id=092bdbe8fb8f4c108fe985f969af5286

**Comment by Aster0** [comment]
https://pastebin.com/YqMzDmCu

It might be because of the plugin that I just added, ChatColor.

Best to confirm though.

**Comment by cdmvirt** [comment]
same issue for me but no plugin added

`[19:15:19 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! ( TimingIdentifier{id=Minecraft:Full Server Tick}:co.aikar.timings.TimingHandler@148)
java.lang.Throwable: null
at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:111) ~[patched_1.13.2.jar:git-Paper-584]
at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:32) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:998) ~[patched_1.13.2.jar:git-Paper-584]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-584]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Comment by mibby** [comment]
Broke in this commit? @aikar https://github.com/PaperMC/Paper/commit/4c807f929ec62d47302c85f87cac64ba4c7a3e4c

**Comment by electronicboy** [comment]
Validation of the stack was added, the commit adding that checks to ensure that consistency isn't broken, which something is tripping; I think I've found one cause, need to test

**Comment by aikar** [comment]
Unless there's a bug in one of Paper's timings, it's not that Paper is broke, but some plugin is causing a break.

going to work on improving the corrupt stack data output to be more informative and self healing.
