### ISSUE TITLE
Server crash very frequently and I am unable to explains why

### ISSUE THREAD

**Issue by jdkeke142** [PaperMC/Paper#1980]
### Link/paste of stack trace
`[23:13:55] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Exception ticking world entities
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1118) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-621]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]
Caused by: java.util.NoSuchElementException
	at org.bukkit.craftbukkit.v1_13_R2.util.UnsafeList$Itr.next(UnsafeList.java:248) ~[patched_1.13.2.jar:git-Paper-621]
	at org.spigotmc.ActivationRange.activateChunkEntities(ActivationRange.java:162) ~[patched_1.13.2.jar:git-Paper-621]
	at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:145) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1313) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-621]
	... 4 more
[23:13:55] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.NoSuchElementException: null
	at org.bukkit.craftbukkit.v1_13_R2.util.UnsafeList$Itr.next(UnsafeList.java:248) ~[patched_1.13.2.jar:git-Paper-621]
	at org.spigotmc.ActivationRange.activateChunkEntities(ActivationRange.java:162) ~[patched_1.13.2.jar:git-Paper-621]
	at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:145) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1313) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-621]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]`

### Plugin list:
___AsyncWorldEdit, FairNaturalSpawns, Gloss, GlossChatBubbles, GlossDamageIndicators, HypercraftAuth, HypercraftBukkitSuite, LogBlock, Mortar, OreReplacerPlugin, PacketWrapper, PlaceholderAPI, PlugMan, ProtocolLib, React, Vault, WorldEdit, WorldGuard, zPermissions___

### Actions to reproduce (if known):
___Unable to reproduce as I want, the server crash very frequently, I'm not sure that this is related to PaperSpigot.___

### Paper build number:
___git-Paper-621___

**Comment by joecabezas** [comment]
mine crashes too, no plugins, too often, it was every 60 min, now is every 15 min
I noticed it triggers often when I travel from/to nether

**Comment by Chew** [comment]
Hello! This issue is over a year old and, due to how vague it is, must be closed. The issue has likely been fixed over the course of the last year, but if you still happen to run into this issue, without plugins, feel free to open a new issue. Have a good day!
