### ISSUE TITLE
Forceload chunks

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#1989]
### What behaviour is expected:
I wanted to see message "marked x chunks in minecraft:overworld from x z to x z to be force loaded

### What behaviour is observed:
This message are sended but I'm getting into console spam
Error loading saved data: map_5536
java.io.EOFException: null
at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:1.8.0_212]
at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:1.8.0_212]
at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:1.8.0_212]
at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_212]
at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:18) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.WorldPersistentData.a(WorldPersistentData.java:139) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.WorldPersistentData.a(WorldPersistentData.java:51) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.PersistentCollection.get(SourceFile:31) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.IPersistentAccess.a(SourceFile:20) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ItemWorldMap.a(ItemWorldMap.java:63) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ItemWorldMap.getSavedMap(ItemWorldMap.java:29) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.EntityTrackerEntry.track(EntityTrackerEntry.java:106) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.EntityTracker.updatePlayers(EntityTracker.java:175) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1123) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-621]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
### Steps/models to reproduce:
log: https://mclo.gs/35nD4Zy

### Plugin list:
Plugins (41): AdvancedArmorStands, AdvancedPortals, Citizens, ClearLag*, CommandNPC*, CommandSigns, EasyCarts, EpicHeads, Essentials, HolographicDisplays, InvRestore2*, KInvBackup*, MorkazSk*, Multiverse-Core, Multiverse-Inventories*, Multiverse-NetherPortals, MultiWorldMoney*, OtherDrops, PermissionsEx*, PixelPrinter, PlaceholderAPI, PlayMoreSounds*, PluginConstructorAPI, PlugMan*, RFChairs, ServerRestorer, Shopkeepers, SkQuery*, Skript, skript-mirror*, Spawners, TopLite*, TuSKe*, Vault*, WG-GUI, WolvSK*, WorldBorder, WorldChangeScreenRemover, WorldEdit, WorldGuard, WorldGuardExtraFlags
### Paper build number:
This server is running Paper version git-Paper-621 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[22:11:13 INFO]: Previous version: git-Paper-617 (MC: 1.13.2)
[22:11:13 INFO]: Checking version, please wait...
[22:11:13 INFO]: You are 1 version(s) behind

### Anything else:
Minecraft version: 1.13.2. The world has been filled by worldborder. Can't stop server, I need to force kill server to let it stop spam and restart.

**Comment by electronicboy** [comment]
You have corrupted files, best advice is to delete them or restore a backup

**Comment by Misio12320** [comment]
Corrupted files? not file? It says only 1 chunk or something. Whats the .mca file? How to fix it?

**Comment by electronicboy** [comment]
Theres only one that we can see now, it's more a potential, it's a map data file, in the `world/data/` folder

**Comment by Misio12320** [comment]
Founded. file with 0 bytes. Worked all chunks in this world are force loaded and 0 issues.. Thanks

**Comment by Misio12320** [comment]
and @electronicboy what is this Sebastian_Z_GTA issued server command: /forceload add ~ ~
[19:10:39 ERROR]: java.lang.NullPointerException
[19:10:39 WARN]: java.lang.NullPointerException
[19:10:39 WARN]: at net.minecraft.server.v1_13_R2.DimensionManager.toString(SourceFile:64)
[19:10:39 WARN]: at java.lang.String.valueOf(String.java:2994)
[19:10:39 WARN]: at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.serialize(IChatBaseComponent.java:362)
[19:10:39 WARN]: at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.serialize(IChatBaseComponent.java:184)
[19:10:39 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
[19:10:39 WARN]: at com.google.gson.Gson.toJson(Gson.java:669)
[19:10:39 WARN]: at com.google.gson.Gson.toJson(Gson.java:648)
[19:10:39 WARN]: at com.google.gson.Gson.toJson(Gson.java:603)
[19:10:39 WARN]: at com.google.gson.Gson.toJson(Gson.java:583)
[19:10:39 WARN]: at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:394)
[19:10:39 WARN]: at net.minecraft.server.v1_13_R2.PacketDataSerializer.a(PacketDataSerializer.java:132)
[19:10:39 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayOutChat.b(PacketPlayOutChat.java:39)
[19:10:39 WARN]: at net.minecraft.server.v1_13_R2.PacketEncoder.encode(PacketEncoder.java:42)
[19:10:39 WARN]: at net.minecraft.server.v1_13_R2.PacketEncoder.encode(PacketEncoder.java:12)
[19:10:39 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[19:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[19:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[19:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[19:10:39 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[19:10:39 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[19:10:39 WARN]: at net.minecraft.server.v1_13_R2.NetworkManager.lambda$b$4(NetworkManager.java:214)
[19:10:39 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[19:10:39 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[19:10:39 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[19:10:39 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:10:39 WARN]: at java.lang.Thread.run(Thread.java:748)
[19:10:39 WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by net.minecraft.server.v1_13_R2.EntityPlayer$$Lambda$2349/1149217215.operationComplete()
java.lang.NullPointerException: null
at net.minecraft.server.v1_13_R2.DimensionManager.toString(SourceFile:64) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ChatMessage.b(SourceFile:131) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ChatMessage.b(SourceFile:100) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ChatMessage.i(SourceFile:59) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ChatMessage.c(SourceFile:159) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.IChatBaseComponent.a(IChatBaseComponent.java:52) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.EntityPlayer.lambda$a$4(EntityPlayer.java:1355) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.NetworkManager.lambda$b$4(NetworkManager.java:217) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.13.2.jar:git-Paper-621]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by electronicboy** [comment]
Did you try that in a custom world?

**Comment by Misio12320** [comment]
yep. in another. but executed by player this command. I was thinking if it will work only in my 1 world 'corrupted' now fixed but in everyone 19:17:18 ERROR]: java.lang.NullPointerException
[19:17:18 WARN]: java.lang.NullPointerException
[19:17:18 WARN]: at net.minecraft.server.v1_13_R2.DimensionManager.toString(SourceFile:64)
[19:17:18 WARN]: at java.lang.String.valueOf(String.java:2994)
[19:17:18 WARN]: at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.serialize(IChatBaseComponent.java:362)
[19:17:18 WARN]: at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.serialize(IChatBaseComponent.java:184)
[19:17:18 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
[19:17:18 WARN]: at com.google.gson.Gson.toJson(Gson.java:669)
[19:17:18 WARN]: at com.google.gson.Gson.toJson(Gson.java:648)
[19:17:18 WARN]: at com.google.gson.Gson.toJson(Gson.java:603)
[19:17:18 WARN]: at com.google.gson.Gson.toJson(Gson.java:583)
[19:17:18 WARN]: at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:394)
[19:17:18 WARN]: at net.minecraft.server.v1_13_R2.PacketDataSerializer.a(PacketDataSerializer.java:132)
[19:17:18 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayOutChat.b(PacketPlayOutChat.java:39)
[19:17:18 WARN]: at net.minecraft.server.v1_13_R2.PacketEncoder.encode(PacketEncoder.java:42)
[19:17:18 WARN]: at net.minecraft.server.v1_13_R2.PacketEncoder.encode(PacketEncoder.java:12)
[19:17:18 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:17:18 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:17:18 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[19:17:18 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[19:17:18 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[19:17:18 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[19:17:18 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[19:17:18 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[19:17:18 WARN]: at net.minecraft.server.v1_13_R2.NetworkManager.lambda$b$4(NetworkManager.java:214)
[19:17:18 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[19:17:18 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[19:17:18 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[19:17:18 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:17:18 WARN]: at java.lang.Thread.run(Thread.java:748)
[19:17:18 WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by net.minecraft.server.v1_13_R2.EntityPlayer$$Lambda$2349/1149217215.operationComplete()
java.lang.NullPointerException: null
at net.minecraft.server.v1_13_R2.DimensionManager.toString(SourceFile:64) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ChatMessage.b(SourceFile:131) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ChatMessage.b(SourceFile:100) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ChatMessage.i(SourceFile:59) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.ChatMessage.c(SourceFile:159) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.IChatBaseComponent.a(IChatBaseComponent.java:52) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.EntityPlayer.lambda$a$4(EntityPlayer.java:1355) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.NetworkManager.lambda$b$4(NetworkManager.java:217) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) ~[patched_1.13.2.jar:git-Paper-621]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.13.2.jar:git-Paper-621]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[19:17:23 INFO]: <[Prezydent] Sebastian_Z_GTA> t
[19:17:26 INFO]: Sebastian_Z_GTA issued server command: /forceload add ~ ~

**Comment by Misio12320** [comment]
suggestion? solution?

**Comment by Misio12320** [comment]
???????????????????? and what is [21:06:19 ERROR]: Failed to load data for block entity minecraft:structure_block
java.lang.StackOverflowError: null
at java.lang.StringBuilder.setLength(StringBuilder.java:76) ~[?:1.8.0_212]
at org.apache.logging.log4j.core.async.RingBufferLogEvent.getMessageTextForWriting(RingBufferLogEvent.java:150) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.core.async.RingBufferLogEvent.setMessage(RingBufferLogEvent.java:125) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.core.async.RingBufferLogEvent.setValues(RingBufferLogEvent.java:106) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.core.async.RingBufferLogEventTranslator.translateTo(RingBufferLogEventTranslator.java:58) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.core.async.RingBufferLogEventTranslator.translateTo(RingBufferLogEventTranslator.java:35) ~[patched_1.13.2.jar:git-Paper-621]
at com.lmax.disruptor.RingBuffer.translateAndPublish(RingBuffer.java:962) ~[patched_1.13.2.jar:git-Paper-621]
at com.lmax.disruptor.RingBuffer.tryPublishEvent(RingBuffer.java:478) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.core.async.AsyncLoggerDisruptor.tryPublish(AsyncLoggerDisruptor.java:205) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.core.async.AsyncLogger.publish(AsyncLogger.java:166) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.core.async.AsyncLogger.logWithThreadLocalTranslator(AsyncLogger.java:162) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.core.async.AsyncLogger.logMessage(AsyncLogger.java:132) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2011) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884) ~[patched_1.13.2.jar:git-Paper-621]
at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:854) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.TileEntity.create(TileEntity.java:116) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:68) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:31) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftStructureBlock.<init>(CraftStructureBlock.java:25) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState0(CraftBlock.java:370) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState(CraftBlock.java:285) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState(CraftBlock.java:279) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.World.setTypeAndData(World.java:426) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.TileEntityStructure.J(SourceFile:131) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.TileEntityStructure.load(SourceFile:121) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.TileEntity.create(TileEntity.java:114) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:68) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:31) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftStructureBlock.<init>(CraftStructureBlock.java:25) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState0(CraftBlock.java:370) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState(CraftBlock.java:285) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState(CraftBlock.java:279) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.World.setTypeAndData(World.java:426) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.TileEntityStructure.J(SourceFile:131) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.TileEntityStructure.load(SourceFile:121) ~[patched_1.13.2.jar:git-Paper-621]
at net.minecraft.server.v1_13_R2.TileEntity.create(TileEntity.java:114) ~[patched_1.13.2.jar:git-Paper-621]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:68) ~[patched_1.13.2.jar:git-Paper-621]

**Comment by electronicboy** [comment]
forceload command has been fixed in the latest build of 1.13.2. For issues irrelevant to the original ticket, please use IRC/discord or create a new issue making sure to fill out the template properly, we don't want to spam people with needless emails for issues irrelevant to the report.

Looks like a known bug with structure blocks, not too sure what the source of it was
