### ISSUE TITLE
Server crash [Thread-2/WARN]: Exception in thread "Thread-2" 

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1997]
Server went offline around 9:30 and it's unclear what happened. I don't know but just in case this helps here is the log info.

Everything that day and before the shutdown looks ordinary, because it's just the kind of log activity we create every day.

Remained offline until manual restart a few hours after. No issues since then.

### Link/paste of stack trace

First time server went down:
```
[21:19:22] [Thread-2/INFO]: Stopping server
[21:19:22] [Thread-2/INFO]: [PluginLibrary] PluginLibrary v1.2.1 is now disabled!
[21:19:23] [Thread-2/INFO]: GroupManager version 2.0 (Phoenix) is disabled!
[21:19:23] [Thread-2/INFO]: Saving players
[21:19:24] [Thread-2/INFO]: Afk_Robot lost connection: Liberty Minecraft is restarting. Come back soon!
[21:19:24] [Thread-2/INFO]: Afk_Robot left the game
[21:19:24] [Thread-2/INFO]: Remix_D_Miner lost connection: Liberty Minecraft is restarting. Come back soon!
[21:19:24] [Thread-2/INFO]: Remix_D_Miner left the game
[21:19:24] [Thread-2/INFO]: Cardano_ff lost connection: Liberty Minecraft is restarting. Come back soon!
[21:19:24] [Thread-2/INFO]: Cardano_ff left the game
[21:19:24] [Thread-2/INFO]: Aewheros lost connection: Liberty Minecraft is restarting. Come back soon!
[21:19:24] [Thread-2/INFO]: Aewheros left the game
[21:19:24] [Thread-2/INFO]: coconewell92 lost connection: Liberty Minecraft is restarting. Come back soon!
[21:19:24] [Thread-2/INFO]: coconewell92 left the game
[21:19:24] [Thread-2/INFO]: sharonclaws lost connection: Liberty Minecraft is restarting. Come back soon!
[21:19:24] [Server thread/WARN]: handleDisconnection() called twice
[21:19:24] [Server thread/WARN]: handleDisconnection() called twice
[21:19:24] [Server thread/WARN]: handleDisconnection() called twice
[21:19:24] [Server thread/WARN]: handleDisconnection() called twice
[21:19:24] [Server thread/WARN]: handleDisconnection() called twice
[21:19:24] [Thread-2/INFO]: sharonclaws left the game
[21:19:24] [Thread-2/INFO]: __Wildfire_ lost connection: Liberty Minecraft is restarting. Come back soon!
[21:19:24] [Thread-2/WARN]: Exception in thread "Thread-2" java.util.ConcurrentModificationException
[21:19:24] [Thread-2/WARN]:     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
[21:19:24] [Thread-2/WARN]:     at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.EntityTracker.untrackEntity(EntityTracker.java:153)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.WorldManager.b(WorldManager.java:29)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.World.c(World.java:1146)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.WorldServer.c(WorldServer.java:1036)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.World.kill(World.java:1189)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:465)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1466)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.PlayerConnection.disconnect(PlayerConnection.java:275)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.PlayerList.u(PlayerList.java:1394)
[21:19:24] [Thread-2/WARN]:     at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:662)
[21:19:24] [Thread-2/WARN]:     at org.bukkit.craftbukkit.v1_13_R2.util.ServerShutdownThread.run(ServerShutdownThread.java:18)
```

Server message ~7 minutes later.

```
[02:26:51] [main/INFO]: Loaded 0 recipes
```

### Plugin list:

Autorank, Bot*, CheaperPhysicsEvent, ChestShop, ChestShopNotifier*, ClaimslistClassifier, CoreProtect, dynmap*, Dynmap-GriefPrevention*, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, GPAuctions, GPRealEstate*, GriefPrevention, GroupManager*, InGameMotd, PlaceholderAPI, PlayerVaults*, PluginLibrary*, ProtocolLib*, PVPToggle*, ReferralSystemCustom*, SuperTrailsPro*, Vault, WorldBorder*, WorldEdit, WorldGuard

### Actions to reproduce (if known):
unknown

### Paper build number:
git-Paper-624 (MC: 1.13.2)

**Comment by NullCase** [comment]
Maybe useful info: world data did not save on crash but player data did save.

**Comment by MiniDigger** [comment]
test

**Comment by MiniDigger** [comment]
@electronicboy wants you to know that `Something, more than likely a plugin, modified the entity tracker improperly`
