### ISSUE TITLE
Server starts spitting IllegalStateExceptions at some point

### ISSUE THREAD

**Issue by burdoto** [PaperMC/Paper#2022]
### Paste of stack trace
Server started spitting this out all over the place, without a good reason:
```
[20:21:21] [PaperChunkGen-creative-plots/ERROR]: Couldn't generate chunk (creative-plots:-14,24)
java.util.concurrent.CompletionException: java.lang.IllegalStateException: zip file closed
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_181]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:53) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:27) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SchedulerBatch.java:39) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.generateChunk(ChunkProviderServer.java:204) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.regenerateChunk(CraftWorld.java:291) ~[patched_1.13.2.jar:git-Paper-624]
	at com.github.intellectualsites.plotsquared.bukkit.util.block.BukkitLocalQueue.regenChunk(BukkitLocalQueue.java:71) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:179) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:175) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.ChunkManager$3.run(ChunkManager.java:181) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_181]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_181]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_181]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.generateChunkData(BukkitPlotGenerator.java:135) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.generator.CustomChunkGenerator.createChunk(CustomChunkGenerator.java:71) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkTaskBase.a(SourceFile:13) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:106) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:13) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_181]
	... 69 more
```

Eventually the server crashed with this message:
```
[20:24:21] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Ticking player
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:482) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:432) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1466) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:365) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:153) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: Should always be able to create a chunk!
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:388) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:381) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.getFluid(World.java:840) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Entity.a(Entity.java:1311) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityHuman.dg(EntityHuman.java:212) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:159) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:401) ~[patched_1.13.2.jar:git-Paper-624]
	... 9 more
[20:24:21] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.IllegalStateException: Should always be able to create a chunk!
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:388) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:381) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.getFluid(World.java:840) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Entity.a(Entity.java:1311) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityHuman.dg(EntityHuman.java:212) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:159) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:401) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:432) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1466) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:365) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:153) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

### Plugin list:
- CoreProtect
- dynmap
- e2uClaim
- Essentials
- EssentialsChat
- EssentialsSpawn
- JumpCube
- Multiverse-Core
- Multiverse-Inventories
- PermissionsEx
- PhantomSpawnControl
- PlotSquared
- PluginConstructorAPI
- Vivecraft-Spigot-Extensions
- WorldEdit + WESV
- WorldGuard

### Actions to reproduce (if known):
unknown

### Paper build number:
`git-Paper-624`

**Comment by hugmanrique** [comment]
Were you modifying any world files (creative-plots) with MCEdit/any external tool or moving files?

**Comment by hugmanrique** [comment]
It looks like one of your plugin JAR files is corrupt. You can go one by one trying to open them with WinRAR/7zip and see which one is bad.

This can also happen if you replaced any plugin JAR file while the server was running. Please always replace files while your server is stopped and avoid using /reload.

Another solution (albeit a slower one) would be to setup a breakpoint at PluginClassLoader.loadClass and see which class is giving problems.

**Comment by Spottedleaf** [comment]
Did you perform a reload before this happened?

**Comment by burdoto** [comment]
@Spottedleaf Yes, I performed a reload that added a smaller plugin of my own.

**Comment by BillyGalbreath** [comment]
You're not supposed to use `/reload` or bad things happen. :S

**Comment by burdoto** [comment]
Why not remove it, then?

**Comment by BillyGalbreath** [comment]
Because the community is divided about it. Has been since at least 2011 https://bukkit.org/threads/petition-to-remove-the-reload-command.43212/ In the end, it's just not safe to use.

**Comment by burdoto** [comment]
I'm having _very_ shared opinions about the whole Bukkit thematic, some API decisions are just straight up stupid, in my opinion. This is another thing that makes no sense to me; why keep something that will eventually break your server? It is just not thought through.
Thanks for the help, though.

**Comment by VADemon** [comment]
/reload is an instrument like any other and you ought to know its weak sides. I think there're enough warnings surrounding it (to not use it)
