### ISSUE TITLE
Server crash 1.14.1

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#2032]
### What behaviour is expected:
After execute command save-all or auto save the server crash

### What behaviour is observed:
Server crash 

### Steps/models to reproduce:
Log: https://pastebin.com/1BRNZtq3 the crash code

### Plugin list:
Plugins (25): ClearLag*, CommandSigns, EpicHeads, HolographicDisplays, InvRestore2*, Multiverse-Core, Multiverse-Inventories*, Multiverse-NetherPortals, PermissionsEx*, PixelPrinter, PlaceholderAPI*, PluginConstructorAPI, PlugMan*, RFChairs, ServerRestorer, Shopkeepers, SkQuery*, Skript, TopLite*, TuSKe*, Vault, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
This server is running Paper version git-Paper-20 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

### Anything else:
I does not played the 1.14.1 yet. I will say everything what happen whenever I join and look at the server.

**Comment by Misio12320** [comment]
its this same like #2026 how to fix this?

Edit: also my worlds aren't loading correcty [19:27:13 WARN]: net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:SwiatDrop
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:38)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:43)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.IRegistry.a(SourceFile:188)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.DimensionManager.register(DimensionManager.java:23)
[19:27:13 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:1000)
[19:27:13 WARN]: at org.bukkit.Bukkit.createWorld(Bukkit.java:492)
[19:27:13 WARN]: at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310)
[19:27:13 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:27:13 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[19:27:13 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[19:27:13 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[19:27:13 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843)
[19:27:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[19:27:13 ERROR]: [Multiverse-Core] The world 'SwiatDrop' could NOT be loaded because it contains errors and is probably corrupt!
[19:27:13 ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'SwiatDrop'
[19:27:13 ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[19:27:13 WARN]: net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:Creative
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:38)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:43)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.IRegistry.a(SourceFile:188)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.DimensionManager.register(DimensionManager.java:23)
[19:27:13 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:1000)
[19:27:13 WARN]: at org.bukkit.Bukkit.createWorld(Bukkit.java:492)
[19:27:13 WARN]: at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728)
[19:27:13 WARN]: at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310)
[19:27:13 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:27:13 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[19:27:13 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[19:27:13 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[19:27:13 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[19:27:13 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843)
[19:27:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[19:27:13 ERROR]: [Multiverse-Core] The world 'Creative' could NOT be loaded because it contains errors and is probably corrupt!
[19:27:13 ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'Creative'
[19:27:13 ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer . 1 world is loading correct and works but others doesn't. 
++ cannot even do backup to get sure if im save ** fix

**Comment by andris155** [comment]
SwiatDrop rename to swiatdrop to fix world load.

**Comment by zachbr** [comment]
Closing outdated version, your log indicates writing the world files took too long but it's also from a version with a known memory leak.

The world file resource key issues are because Minecraft now expects worlds to conform to their naming conventions which do not allow uppercase characters.
