### ISSUE TITLE
Structure Generation causes CME on world gen

### ISSUE THREAD

**Issue by northerncarrots** [PaperMC/Paper#2037]
### Link/paste of stack trace
[paper-21](https://hastebin.com/usuceqadux.md)
[spigot-8043ebc-dd99c5b](https://hastebin.com/resiqiviqa.md)

### Plugin list:
[Worldborder 1.9.0](https://www.spigotmc.org/resources/worldborder.60905/update?update=244392)

### Actions to reproduce (if known):
1. Run Paper-21 (1.14.1)
2. Use Worldborder 1.9.0
3. `wb world set 25000 25000 0 0`
4. `wb shape square`
5. `wb fill` + `wb fill confirm`
6. wait for **x** amount of hours
7. crash

### Paper build number:
paper-21

_I tried submitting a ticket for Spigot as well and I was told to narrow this down to the seed and coordinates that reproducibly cause an issue. I know what the seed is, but I cannot figure out how to see which coordinate/chunk causes this crash._

**Comment by andris155** [comment]
Worldborder not supported 1.14.1

**Comment by northerncarrots** [comment]
Words from the current author of WorldBorder

> The stack traces indicate the problem being in Spigot/Bukkit/NMS, no code from any plugins at fault. There is at least one known NMS bug along these lines which may or may not be fixed yet. Whatever the case, look to Spigot/Paper for a fix.

I backed up my files and I am currently trying to pregen on another seed right now.

**Comment by zachbr** [comment]
This is a vanilla issue as far as we know, some of the structure generators are doing things they shouldn't be. I've seen this just randomly happen with no plugins.
We may get to this or it may sit until Mojang's 1.14.2 there's no way to know for sure.

**Comment by andris155** [comment]
Same problem. :(
```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/16/19, 10:23 PM
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at net.minecraft.server.v1_14_R1.WorldGenStronghold.a(SourceFile:46)
	at net.minecraft.server.v1_14_R1.ChunkGenerator.createStructures(ChunkGenerator.java:144)
	at net.minecraft.server.v1_14_R1.ChunkStatus.d(SourceFile:44)
	at net.minecraft.server.v1_14_R1.ChunkStatus.a(SourceFile:199)
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$13(PlayerChunkMap.java:430)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$15(PlayerChunkMap.java:428)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:57)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
