### ISSUE TITLE
About MarvelousCarft

### ISSUE THREAD

**Issue by Pau1am** [PaperMC/Paper#2039]
[19:09:41 ERROR]: Could not pass event InventoryCloseEvent to MarvelousCraft v0.0.1
java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
        at com.willzcode.MenuInventory.onInventoryClose(MenuInventory.java:72) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor157.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.1.jar:git-Paper-22]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-22]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-22]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-22]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1316) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2115) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:995) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:971) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906) ~[patched_1.14.1.jar:git-Paper-22]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by astei** [comment]
The plugin is not compatible with Minecraft 1.14. The author needs to update the plugin.
