### ISSUE TITLE
1.14.1 NPE Generating Chunks

### ISSUE THREAD

**Issue by Blazzike** [PaperMC/Paper#2052]
### Link/paste of stack trace
https://hastebin.com/ovolehulic.rb

### Plugin list:
CoreProtect, HolographicDisplays, LuckPerms, MCTQuests, MCTraveler-Core, PlugMan, ProtocolLib*

### Actions to reproduce (if known):
None known, appears to occur randomly while generating new chunks.

### Paper build number:
`git-Paper-26 (MC: 1.14.1)`

**Comment by Taskeren** [comment]
Omg, I have same problem.

**Comment by zachbr** [comment]
Can someone (OP or next person who runs into this) please paste the stack to GitHub Gist or embed it directly in a fenced code block here?
Hastebin is giving me a blank page on the linked stacktrace.
Thanks.

Edit: from a duplicate https://paste.ubuntu.com/p/Whwf2hDQwN/
Would still appreciate an updated stacktrace

**Comment by andris155** [comment]
```
---- Minecraft Crash Report ----
// Sorry :(

Time: 5/17/19, 11:38 AM
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at net.minecraft.server.v1_14_R1.WorldGenStronghold.a(SourceFile:46)
	at net.minecraft.server.v1_14_R1.ChunkGenerator.createStructures(ChunkGenerator.java:144)
	at net.minecraft.server.v1_14_R1.ChunkStatus.d(SourceFile:44)
	at net.minecraft.server.v1_14_R1.ChunkStatus.a(SourceFile:199)
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$13(PlayerChunkMap.java:430)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$15(PlayerChunkMap.java:428)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:57)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by Blazzike** [comment]
https://gist.github.com/Blazzike/9170c912d5e91e30f12f47dcd3899086
