### ISSUE TITLE
Can not create a new world

### ISSUE THREAD

**Issue by Arasple** [PaperMC/Paper#2056]
### **Expected:**
The world will be created

### **Observed:**
Got errors and failed to create a new world
`[11:54:19 ERROR]: Error occurred while enabling Debug v1.0-SNAPSHOT (Is it up to date?)
net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:Demo        at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:38) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:43) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.IRegistry.a(SourceFile:188) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.DimensionManager.register(DimensionManager.java:23) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:1000) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:492) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279) ~[patched_1.14.1.jar:git-Paper-26]
        at me.arasple.mc.debug.Debug.onEnable(Debug.java:10) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.14.1.jar:git-Paper-26]        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]`

### **Reproducing:**
    @Override
    public void onEnable() {
        new WorldCreator("Demo").createWorld();
    }

### **Paper build number:**
Paper 26 (MC: 1.14.1)

### **Anything else:** 
Paper 17 (MC: 1.14), same situation, no error, and the world created successfully

**Comment by electronicboy** [comment]
Bukkit now requires world names to be lowercased: https://hub.spigotmc.org/jira/browse/SPIGOT-4925
