### ISSUE TITLE
Image rendering on a map 

### ISSUE THREAD

**Issue by MrIvanPlays** [PaperMC/Paper#2065]
### What behaviour is expected:
Image rendered properly at the map

### What behaviour is observed:
Disconnects with this error:
```
[11:24:13 WARN]: Failed to handle packet for /MyIPWhichIWontShow
net.minecraft.server.v1_14_R1.ReportedException: Ticking player
at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:500) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:259) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1189) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1048) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:892) ~[patched_1.14.1.jar:git-Paper-37]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_212]
at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_212]
at org.bukkit.craftbukkit.v1_14_R1.map.CraftMapView.render(CraftMapView.java:150) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:459) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.WorldMap.a(WorldMap.java:336) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.ItemWorldMap.a(ItemWorldMap.java:330) ~[patched_1.14.1.jar:git-Paper-37]
at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:425) ~[patched_1.14.1.jar:git-Paper-37]
... 8 more
```

### Steps/models to reproduce:
Get a empty map ingame and try rendering it with plugin, which has this code inside and functions:

Util for removing map renderers:
```java
public class MapUtils {

    public static void removeRenderers(MapView view) {
        view.getRenderers().forEach(view::removeRenderer);
    }
}
```

sum event handling boiii
```java
    @EventHandler
    public void onMapInitialize(MapInitializeEvent event) {
        MapView mapView = event.getMap();
        mapView.setScale(MapView.Scale.FARTHEST);
        mapView.setUnlimitedTracking(false);
        MapUtils.removeRenderers(mapView);
        mapView.addRenderer(new ImageRenderer(plugin.getDataFolder()));
    }
```

Image renderer:
```java
public class ImageRenderer extends MapRenderer {

    private BufferedImage image;

    public ImageRenderer(File dataFolder) {
        File[] files = dataFolder.listFiles((file, name) -> endsWithImageExtension(name));
        if (files == null) {
            image = null;
            return;
        }
        if (files.length > 1) {
            throw new UnsupportedOperationException("There are 2 or more image files inside data " +
                    "folder. Cannot render 2 or more images!");
        }
        try {
            image = ImageIO.read(files[0]);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void render(@NotNull MapView map, @NotNull MapCanvas canvas, @NotNull Player player) {
        MapUtils.removeRenderers(map);
        if (image == null) {
            return;
        }
        MapCursorCollection cursors = canvas.getCursors();
        for (int cursor = 0; cursor < cursors.size(); cursor++) {
            cursors.removeCursor(cursors.getCursor(cursor));
        }
        canvas.drawImage(0, 0, image);
    }

    private boolean endsWithImageExtension(String name) {
        return name.endsWith(".jpg") || name.endsWith(".png") || name.endsWith(".jpeg");
    }
}
```

### Plugin list:
Only the plugin with the code I showed up

### Paper build number:
[11:22:23 INFO]: This server is running Paper version git-Paper-37 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

### Anything else:
The same was seen at build 33.

**Comment by electronicboy** [comment]
You're modifying the list of renderers as the server is trying to iterate it; don't.

**Comment by MrIvanPlays** [comment]
> You're modifying the list of renderers as the server is trying to iterate it; don't.

Very good fix of the issue. I tested it on spigot - it worked without any problems.

**Comment by MiniDigger** [comment]
its an issue with your code, not paper. Looking at spigot code, it should throw the same exception on spigot, see https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/map/CraftMapView.java#112,150,159

you just cant remove renderer in the render loop. it makes zero sense anyways since you remove all renderers on init....
