### ISSUE TITLE
Unknown target reason

### ISSUE THREAD

**Issue by FrostyWolf** [PaperMC/Paper#2069]
### Link/paste of stack trace
```
11:05:42 Unknown target reason, please report on the issue tracker
Console 05/23/2019 11:05:42
11:05:42 java.lang.Exception: null
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.1.jar:git-Paper-39]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2520) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2309) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.World.a(World.java:880) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1165) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1048) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:892) ~[patched_1.14.1.jar:git-Paper-39]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
11:05:43 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
WARN 05/23/2019 11:05:43
11:05:43 Unknown target reason, please report on the issue tracker
Console 05/23/2019 11:05:43
11:05:43 java.lang.Exception: null
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.1.jar:git-Paper-39]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2520) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2309) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.World.a(World.java:880) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1165) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1048) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:892) ~[patched_1.14.1.jar:git-Paper-39]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
11:05:44 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
WARN 05/23/2019 11:05:44
11:05:44 Unknown target reason, please report on the issue tracker
Console 05/23/2019 11:05:44
11:05:44 java.lang.Exception: null
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.1.jar:git-Paper-39]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2520) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2309) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.World.a(World.java:880) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1165) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1048) ~[patched_1.14.1.jar:git-Paper-39]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:892) ~[patched_1.14.1.jar:git-Paper-39]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

### Plugin list:
DiscordSRV

### Actions to reproduce (if known):
I see the error refers to EntityFox. As I do not have any foxes on the server except in the one area, I assume it is related to them.  They are in a 2 deep, 9x9 hole with berry bushes along the bottom for a Sweet Berry farm, like so: https://i.imgur.com/3sBR5EO.png

### Paper build number:
git-Paper-39

**Comment by Redlnn** [comment]
I also have a similar issue in Paper 1.14.2 (git-55).

### Link/paste of stack trace

```[09:34:53] [Server thread/INFO]: TPS from last 1m, 5m, 15m: *20.0, 20.0, *20.0
[09:41:01] [Server thread/WARN]: <playername1> moved too quickly! 23.761508374058394,0.4647292647846015,-2.778706703741136
[09:41:01] [Server thread/WARN]: <playername1> moved too quickly! 23.642253527820458,0.4891663161451376,-2.8126261297911697
[09:43:10] [Server thread/WARN]: <playername2> moved wrongly!
[09:53:58] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-55]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-55]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[09:56:24] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-55]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-55]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[09:56:48] [Server thread/INFO]: There are 6 of a max 15 players online: madokaqua, SaltedFish_awa, iryNeko, YuLiZSO, 24K_SaltedFish, Pomelo_tea
[10:03:36] [Server thread/WARN]: Pomelo_tea moved too quickly! 0.42365286042604566,7.990803188600971,-8.282837345751432
```

### Plugin list:
CoreProtect 2.17.4, JoinMessagePlus*, WorldEdit(http://builds.enginehub.org/job/worldedit/11815)

### Paper build number:
git-Paper-55 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Fixed in build 68+
