### ISSUE TITLE
Error executing task on Server 1.14.1

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#2074]
### What behaviour is expected:
___What you expected to see___
No write this error

### What behaviour is observed:
___What you actually saw___
```
[10:28:51] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Cannot get property BlockStateEnum{name=type, clazz=class net.minecraft.server.v1_14_R1.BlockPropertyChestType, values=[SINGLE, LEFT, RIGHT]} as it does not exist in Block{minecraft:air}
	at net.minecraft.server.v1_14_R1.BlockDataAbstract.get(SourceFile:95) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.TileEntityChest.a(TileEntityChest.java:187) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.TileEntityChest.lambda$doCloseLogic$0(TileEntityChest.java:146) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MCUtil$DelayedRunnable.run(MCUtil.java:67) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.1.jar:git-Paper-42]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[10:28:51] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Cannot get property BlockStateEnum{name=type, clazz=class net.minecraft.server.v1_14_R1.BlockPropertyChestType, values=[SINGLE, LEFT, RIGHT]} as it does not exist in Block{minecraft:air}
	at net.minecraft.server.v1_14_R1.BlockDataAbstract.get(SourceFile:95) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.TileEntityChest.a(TileEntityChest.java:187) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.TileEntityChest.lambda$doCloseLogic$0(TileEntityChest.java:146) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MCUtil$DelayedRunnable.run(MCUtil.java:67) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.1.jar:git-Paper-42]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
I don't know. I find this error in console.

### Plugin list:
___A list of your plugins___
Plugins (92): AdditionsAPI, AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, AsyncWorldEdit, BuntetesLogolo, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, Citizens, CitizensCMD, CombatLogX, CommandHook, CommandSigns, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus*, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, EnderContainers, EntityDetection, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HonapStaffja, HungerGames, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, MobHeads, Multiverse-Core, MyCommand, MyPet, NametagEdit*, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PlaceholderAPI*, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaAdditions, RandomTeleport, RedstoneClockDetector*, RestrictedCreative, SignEdit*, StaffChat, StaffTime, Stats, SuperLuckyBlock, SzulinapiTuzijatek, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, Votifier, VotingPlugin, VoxelSniper*, WDLCompanion*, WDLCompanionGriefPreventionSupport*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-42 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by zachbr** [comment]
Thanks - Builds 45+
