### ISSUE TITLE
Ticking player crash

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#2082]
### Link/paste of stack trace

```
    [14:48:21] [Server thread/WARN]: Failed to handle packet for xx.xxx.xxx.xxx/xx.xxx.xxx.xxx:43807
net.minecraft.server.v1_14_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:500) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:259) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:132) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:207) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:147) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:94) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:323) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:95) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:318) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.World.getType(World.java:675) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.Entity.inBlock(Entity.java:1924) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityLiving.inBlock(EntityLiving.java:3132) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:241) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:369) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2273) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:150) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
	... 8 more
[14:48:21] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:world - syncChunkLoad} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.1.jar:git-Paper-43]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1202) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[14:48:21] [Server thread/INFO]: UltraLila lost connection: Internal server error
[14:48:21] [Server thread/INFO]: [ChatControl] [-] UltraLila
[14:48:21] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_14_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:500) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.PlayerList.disconnect(PlayerList.java:412) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1507) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.NetworkManager.handleDisconnection(NetworkManager.java:353) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:153) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:132) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:207) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:147) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:94) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:323) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:95) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:318) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.World.getType(World.java:675) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.Entity.inBlock(Entity.java:1924) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityLiving.inBlock(EntityLiving.java:3132) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:241) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:369) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2273) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:150) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
	... 9 more
[14:48:21] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:132) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:207) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:147) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:94) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:323) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:95) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:318) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.World.getType(World.java:675) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.Entity.inBlock(Entity.java:1924) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityLiving.inBlock(EntityLiving.java:3132) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:241) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:369) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2273) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:150) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.PlayerList.disconnect(PlayerList.java:412) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1507) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.NetworkManager.handleDisconnection(NetworkManager.java:353) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:153) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[14:48:21] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/multicraft/servers/server5/./crash-reports/crash-2019-05-26_14.48.21-server.txt
```

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
Plugins (92): AdditionsAPI, AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, AsyncWorldEdit, BuntetesLogolo, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, Citizens, CitizensCMD, CombatLogX, CommandHook, CommandSigns, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus*, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, EnderContainers, EntityDetection, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HonapStaffja, HungerGames, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, MobHeads, Multiverse-Core, MyCommand, MyPet, NametagEdit*, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PlaceholderAPI*, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaAdditions, RandomTeleport, RedstoneClockDetector*, RestrictedCreative, SignEdit*, StaffChat, StaffTime, Stats, SuperLuckyBlock, SzulinapiTuzijatek, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, Votifier, VotingPlugin, VoxelSniper*, WDLCompanion*, WDLCompanionGriefPreventionSupport*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
26.05 15:49:53 [Server] INFO This server is running Paper version git-Paper-43 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
26.05 15:49:53 [Server] INFO Previous version: git-Paper-42 (MC: 1.14.1)

**Comment by kakd** [comment]
This happened to me using Spigot earlier today

**Comment by electronicboy** [comment]
Can you replicate this without 92 plugins?

**Comment by kaanakduman** [comment]
I have fewer plugins and more data so I'm hoping it can help. Here are some crash reports using Paper-45.
https://hasteb.in/jabiwesi.swift
https://hasteb.in/rukekoki.rb
https://hasteb.in/wotiboho.swift
https://hasteb.in/iqipohow.rb

And here are two pairs of console logs and crash reports. I'm using Paper-48 here.
Console log: https://hasteb.in/amewuvam.shell
Crash report: https://hasteb.in/ojikeliy.rb

Console log: https://hasteb.in/atudemog.md
Crash report: https://hasteb.in/ericutuz.php

I have not yet found a way to replicate the error, but when it happens, it seems to follow a teleport command. In the last two examples above, you can see one crash happening after a /home command and another one happening after a /wild (rtp) command. 

Sometimes, the bug is a little different. In this case ( https://hasteb.in/oyaradax.shell ), Askeau used the /home command, and was disconnected. The player was then unable to reconnect. The server remained up, and other players could connect and reconnect just fine, but Askeau remained unable to reconnect until the next restart.

Plugins (34): ArmorStandTools, BanFromShops, BuycraftX, ChestShop, CoreProtect, CrazyCrates, DiscordSRV, DragonEggDrop, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, HeadDatabase*, HorseTpWithMe, LuckPerms, LWC, MinePacks*, ModReq*, Multiverse-Core, MyWarps*, NoSpawnerChange, OpenInv*, Parties, PhantomSMP, PlugMan, RFChairs, ServerSigns*, Vault, Votifier, VotingPlugin, Wild, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by electronicboy** [comment]
Deferring to #2084
