### ISSUE TITLE
Per-Player View Distance API not work 1.14.1

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#2098]
### What behaviour is expected:
___What you expected to see___
Per-Player View Distance API work similar with 1.13.2

### What behaviour is observed:
___What you actually saw___
Per-Player View Distance API not work

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. Install Paper 1.14.1
2. Install BestViewDistance plugin
3. Join to server.

### Plugin list:
___A list of your plugins___
BestViewDistance

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-43 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___
```
[09:38:45] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to BestViewDistance v11.9
org.apache.commons.lang.NotImplementedException: Per-Player View Distance APIs need further understanding to properly implement
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.setViewDistance(CraftPlayer.java:1973) ~[patched_1.14.1.jar:git-Paper-43]
	at me.lxct.bestviewdistance.event.OnJoin.onPlayerJoin(OnJoin.java:21) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.14.1.jar:git-Paper-43]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-43]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-43]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:169) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.1.jar:git-Paper-43]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by BillyGalbreath** [comment]
Patch was intentionally left out of 1.14

Still no plans of bringing it back.

**Comment by zachbr** [comment]
There are plans but there is no ETA. The exception message is still relevant. Reimplementing it properly requires further study and understanding.

**Comment by Menzani** [comment]
If it were not possible/desirable to reimplement the method, I suggest at least per-world view-distance should be implemented to allow limiting the view-distance in the Nether which is useful to counter fog-removing mods.
