### ISSUE TITLE
ERROR: Failed to save chunk 1,-7

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#2104]
### What behaviour is expected:
Chunks saving on unload.

### What behaviour is observed:
```
[10:48:10] [Server thread/INFO]: NullCase lost connection: Disconnected
--
[10:48:11] [Server thread/ERROR]: Failed to save chunk 1,-7
java.lang.ArrayIndexOutOfBoundsException: 248
at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:348) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.LightEngineStorage.h(SourceFile:77) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.LightEngineLayer.a(SourceFile:209) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:270) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:715) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$10(PlayerChunkMap.java:372) ~[patched_1.14.2.jar:git-Paper-55]
at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_211]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_211]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.b(PlayerChunkMap.java:354) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:320) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:285) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-55]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

### Steps/models to reproduce:
booted up the server. logged in. logged out.

did not reoccur when repeating the above.

### Plugin list:

Autorank, Bot*, CheaperPhysicsEvent, ChestShop, ClaimslistClassifier, CoreProtect, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, GPAuctions, GPRealEstate*, GriefPrevention, GroupManager*, InGameMotd, PlaceholderAPI, PlayerVaults*, PluginLibrary*, ProtocolLib*, PVPToggle*, SuperTrailsPro*, Vault, WorldBorder*, WorldEdit, WorldGuard

### Paper build number:
```
[10:52:51] [Server thread/INFO]: This server is running Paper version git-Paper-55 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
--
[10:52:51] [Server thread/INFO]: Previous version: git-Paper-624 (MC: 1.13.2)
[10:52:51] [Server thread/INFO]: You are running the latest version
```

### Anything else:
Spawn unloads in our world.

**Comment by wardpieters** [comment]
Same issue but with other chunck. Running build 55, previous version is 45. Never happened before and did not recur.

```
[19:07:08 ERROR]: Failed to save chunk -17,86
java.lang.ArrayIndexOutOfBoundsException: 41
at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:348) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.LightEngineStorage.h(SourceFile:77) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.LightEngineLayer.a(SourceFile:209) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:270) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:715) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$10(PlayerChunkMap.java:372) ~[patched_1.14.2.jar:git-Paper-55]
at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_212]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_212]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.b(PlayerChunkMap.java:354) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:320) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:285) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-55]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by rumickon** [comment]
Build 58.
```06.06 12:53:50 [Server] ERROR Failed to save chunk -6,-137
06.06 12:53:50 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 102 out of bounds for length 65
06.06 12:53:50 [Server] INFO at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:348) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.LightEngineStorage.h(SourceFile:77) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.LightEngineLayer.a(SourceFile:209) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:270) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:716) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$10(PlayerChunkMap.java:374) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
06.06 12:53:50 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.b(PlayerChunkMap.java:356) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:320) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:285) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-58]
06.06 12:53:50 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by rumickon** [comment]
Build 95
```[12:10:07] [Server thread/ERROR]: Failed to save chunk -55,57
java.lang.ArrayIndexOutOfBoundsException: Index 67 out of bounds for length 65
        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:348) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.LightEngineStorage.h(SourceFile:77) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.LightEngineLayer.a(SourceFile:209) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:269) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:733) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$9(PlayerChunkMap.java:391) ~[patched_1.14.2.jar:git-Paper-95]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.b(PlayerChunkMap.java:373) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:337) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:367) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-95]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by selfslaughter** [comment]
Just saw that pop up on our server as well. Build #96

`[23:02:30 ERROR]: Failed to save chunk -25,-113
java.lang.ArrayIndexOutOfBoundsException: 294
        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:348) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.LightEngineStorage.h(SourceFile:77) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.LightEngineLayer.a(SourceFile:209) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:269) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:733) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$9(PlayerChunkMap.java:391) ~[patched_1.14.2.jar:git-Paper-96]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.b(PlayerChunkMap.java:373) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:337) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:367) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-96]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
`

**Comment by Spottedleaf** [comment]
common CME indicator for fastutil maps

**Comment by NullCase** [comment]
idk if this helps, but here's another one from Paper build 152.

```
30.07 09:30:32 [Disconnect] User Marcus265 has disconnected, reason: Disconnected
30.07 09:30:33 [Server] ERROR Failed to save chunk 1,-81
30.07 09:30:33 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 151
30.07 09:30:33 [Server] INFO at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:348) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.LightEngineStorage.h(SourceFile:77) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.LightEngineLayer.a(SourceFile:215) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:270) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:783) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$10(PlayerChunkMap.java:434) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_212]
30.07 09:30:33 [Server] INFO at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_212]
30.07 09:30:33 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.b(PlayerChunkMap.java:416) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:380) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:393) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:267) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-152]
30.07 09:30:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by aescraftbr** [comment]
Yep, when I logged out:

```
12.09 18:36:09 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 432
12.09 18:36:09 [Server] INFO at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:348) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.LightEngineStorage.h(SourceFile:77) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.LightEngineLayer.a(SourceFile:215) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:385) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:348) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:922) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveIncrementally(PlayerChunkMap.java:336) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.saveIncrementally(ChunkProviderServer.java:489) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.saveIncrementally(WorldServer.java:856) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1101) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-187]
12.09 18:36:09 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

**Comment by Spottedleaf** [comment]
It's likely due to the main thread reading lighting data from the light thread in a non-thread safe manner (especially given we only see CME from the main reading reading this data)

Further inspection shows the race condition is actually a disagreement of the `mask` and `keys` field (although general mapping changes can cause other issues, such as light disappearing entirely on save)

If it is what I think it is this will be a quick fix
