### ISSUE TITLE
It said to report here

### ISSUE THREAD

**Issue by AsVaidas** [PaperMC/Paper#2108]
`[23:34:45 WARN]: Entity threw exception at world:3803.9210344153094,67.35624559217332,-5198.546980400206

[23:34:45 WARN]: net.minecraft.server.v1_14_R1.ReportedException: Colliding entity with block

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.Entity.move(Entity.java:664)

[23:34:45 WARN]: 	at fr.recreative.mounts.v1_14_R1.MountEntity.e_move_master(MountEntity.java:199)

[23:34:45 WARN]: 	at fr.recreative.mounts.v1_14_R1.MountMule.e(MountMule.java:131)

[23:34:45 WARN]: 	at fr.recreative.mounts.v1_14_R1.MountEntity.movementTick_master(MountEntity.java:699)

[23:34:45 WARN]: 	at fr.recreative.mounts.v1_14_R1.MountMule.movementTick(MountMule.java:208)

[23:34:45 WARN]: 	at fr.recreative.mounts.v1_14_R1.MountEntity.tick_master(MountEntity.java:327)

[23:34:45 WARN]: 	at fr.recreative.mounts.v1_14_R1.MountMule.tick(MountMule.java:181)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.World.a(World.java:895)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904)

[23:34:45 WARN]: 	at java.lang.Thread.run(Thread.java:748)

[23:34:45 WARN]: Caused by: java.lang.NullPointerException

[23:34:45 WARN]: 	at fr.recreative.mounts.v1_14_R1.MountMule.damageEntity(MountMule.java:116)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.BlockSweetBerryBush.a(BlockSweetBerryBush.java:46)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:209)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.Entity.checkBlockCollisions(Entity.java:912)

[23:34:45 WARN]: 	at net.minecraft.server.v1_14_R1.Entity.move(Entity.java:658)

[23:34:45 WARN]: 	... 14 more

[23:34:45 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - fr.recreative.mounts.v1_14_R1.MountMule} did not stopTiming)
java.lang.Throwable: null
at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[server.jar:git-Paper-55]
at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[server.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.World.a(World.java:907) ~[server.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[server.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[server.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[server.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[server.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[server.jar:git-Paper-55]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

Version: git-Paper-55 (MC: 1.14.2)

**Comment by electronicboy** [comment]
A plugin entity `fr.recreative.mounts.v1_14_R1.MountMule.damageEntity(MountMule.java:116)` is throwing an exception, that's leading to the timings one, which isn't really the issue here
