### ISSUE TITLE
Unknown target reason with EntityFox

### ISSUE THREAD

**Issue by tomkimberlin** [PaperMC/Paper#2139]
### Link/paste of stack trace

`[20:38:45] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-66]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-66]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[20:38:47] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-66]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-66]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[20:38:49] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-66]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-66]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

### Plugin list:
AquaticsPlus, BettingGames, CMI, Confiscate, CoreProtect, CraftingStore, CropChecker, DeathChestPro, DiscordSRV, GadgetsMenu, GCore, GriefPrevention, GriefPreventionFlags, HorseTpWithMe, IllegalStack, InsaneShops, LagAssist, LiteBans, LiteBansGUI*, LotteryPool, mcMMO, Minions*, MyPet, ProtocolLib*, PvPToggle, RPGMoney, SafariNet, ServerRestart, SmoothSleep, Spartan, SuperVanish, TradePlus, TreeAssist, UltraPermissions, Vault*, Votifier, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, YourAuction

### Actions to reproduce (if known):

Unknown.

### Paper build number:

Paper-66

**Comment by RealFloorIsJava** [comment]
Seems to be a message from upstream, so might be worth bringing this to upstream's attention

@TakoidGit this seems to indicate missing/partial support for foxes' AI at the current point in time. It *should* work, but plugins that modify/rely on the target of foxes might be wonky.

EDIT: Upstream is already aware, it should be fixed soon.

**Comment by fort-bean** [comment]
FYI - Just had this happen on git-Paper-67 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT) as well.

**Comment by RealFloorIsJava** [comment]
A fix seems to have been published upstream 5 hours ago, it will probably be incorporated into paper soon :)

**Comment by electronicboy** [comment]
Lovingly fixed this light night locally, I'll try and get an upstream merge in soon

**Comment by electronicboy** [comment]
Fixed in build 68+
