### ISSUE TITLE
TIMING_STACK_CORRUPTION

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#2182]
### Link/paste of stack trace

```
[21:01:14] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:world_nether - syncChunkLoad} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.2.jar:git-Paper-80]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.2.jar:git-Paper-80]
	at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[patched_1.14.2.jar:git-Paper-80]
	at co.aikar.timings.TimingHandler.close(TimingHandler.java:203) ~[patched_1.14.2.jar:git-Paper-80]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[patched_1.14.2.jar:git-Paper-80]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-80]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-80]
	at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.handleDirectWireInput(MechanicListenerAdapter.java:345) ~[?:?]
	at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.handleRedstoneForBlock(MechanicListenerAdapter.java:316) ~[?:?]
	at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.onBlockRedstoneChange(MechanicListenerAdapter.java:184) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.2.jar:git-Paper-80]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-80]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-80]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-80]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callRedstoneChange(CraftEventFactory.java:1243) ~[patched_1.14.2.jar:git-Paper-80]
	at net.minecraft.server.v1_14_R1.BlockObserver.tick(BlockObserver.java:35) ~[patched_1.14.2.jar:git-Paper-80]
	at net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:201) ~[patched_1.14.2.jar:git-Paper-80]
	at net.minecraft.server.v1_14_R1.WorldServer.b(WorldServer.java:553) ~[patched_1.14.2.jar:git-Paper-80]
	at net.minecraft.server.v1_14_R1.TickListServer.a(TickListServer.java:90) ~[patched_1.14.2.jar:git-Paper-80]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:268) ~[patched_1.14.2.jar:git-Paper-80]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.2.jar:git-Paper-80]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-80]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-80]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-80]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
`Plugins (89): AdditionsAPI, AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, AsyncWorldEdit, BuntetesLogolo, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, CombatLogX, CommandHook, CommandSigns, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, EnderContainers, EntityDetection, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HonapStaffja, HungerGames, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PlaceholderAPI*, PlayerHeads, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaAdditions, RestrictedCreative, SignEdit*, StaffChat, StaffTime, Stats, SuperLuckyBlock, SzulinapiTuzijatek, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, Votifier, VotingPlugin, VoxelSniper*, WDLCompanion*, WDLCompanionGriefPreventionSupport*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge`

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-80 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

**Comment by sm1ck** [comment]
I have the same problem
`[18:14:12] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:world - World Save - Chunks} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-96]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-96]
	at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[paper.jar:git-Paper-96]
	at co.aikar.timings.TimingHandler.close(TimingHandler.java:203) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:774) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1087) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[paper.jar:git-Paper-96]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[18:14:12] [Server thread/ERROR]: Encountered an unexpected exception
java.util.concurrent.CompletionException: net.minecraft.server.v1_14_R1.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_191]
	at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:57) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91) ~[paper.jar:git-Paper-96]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_191]
Caused by: net.minecraft.server.v1_14_R1.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$16(PlayerChunkMap.java:522) ~[paper.jar:git-Paper-96]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$b$18(PlayerChunkMap.java:507) ~[paper.jar:git-Paper-96]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_191]
	... 11 more
Caused by: java.lang.UnsupportedOperationException: Custom generator is missing required method generateChunkData
	at org.bukkit.generator.ChunkGenerator.generateChunkData(ChunkGenerator.java:87) ~[paper.jar:git-Paper-96]
	at org.bukkit.craftbukkit.v1_14_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:81) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ChunkStatus.lambda$static$6(ChunkStatus.java:51) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ChunkStatus$d.doWork(ChunkStatus.java:239) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ChunkStatus.a(ChunkStatus.java:185) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$16(PlayerChunkMap.java:509) ~[paper.jar:git-Paper-96]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$b$18(PlayerChunkMap.java:507) ~[paper.jar:git-Paper-96]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_191]
	... 11 more
[18:14:12] [Server thread/ERROR]: 	Cause of unexpected exception was
net.minecraft.server.v1_14_R1.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$16(PlayerChunkMap.java:522) ~[paper.jar:git-Paper-96]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$b$18(PlayerChunkMap.java:507) ~[paper.jar:git-Paper-96]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_191]
	at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:57) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91) ~[paper.jar:git-Paper-96]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_191]
Caused by: java.lang.UnsupportedOperationException: Custom generator is missing required method generateChunkData
	at org.bukkit.generator.ChunkGenerator.generateChunkData(ChunkGenerator.java:87) ~[paper.jar:git-Paper-96]
	at org.bukkit.craftbukkit.v1_14_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:81) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ChunkStatus.lambda$static$6(ChunkStatus.java:51) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ChunkStatus$d.doWork(ChunkStatus.java:239) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.ChunkStatus.a(ChunkStatus.java:185) ~[paper.jar:git-Paper-96]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$16(PlayerChunkMap.java:509) ~[paper.jar:git-Paper-96]
	... 14 more`

**Comment by andris155** [comment]
My error fixed. Disabled Craftbook pipes.

**Comment by jeracom** [comment]
same Problem
Console	: [0 21:14:19 WARN]: java.lang.Exception: Error occurred detecting class name
Console	: [0 21:14:19 WARN]: 	at co.aikar.timings.MinecraftTimings.lambda$getPluginTaskTimings$0(MinecraftTimings.java:76)
Console	: [0 21:14:19 WARN]: 	at java.util.concurrent.ConcurrentMap.computeIfAbsent(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at co.aikar.timings.MinecraftTimings.getPluginTaskTimings(MinecraftTimings.java:70)
Console	: [0 21:14:19 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.<init>(CraftTask.java:62)
Console	: [0 21:14:19 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:206)
Console	: [0 21:14:19 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:188)
Console	: [0 21:14:19 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:152)
Console	: [0 21:14:19 WARN]: 	at org.bukkit.scheduler.BukkitRunnable.runTaskLater(BukkitRunnable.java:79)
Console	: [0 21:14:19 WARN]: 	at com.minelazz.epicworldgenerator.structures.StructureObject.h(hda:12)
Console	: [0 21:14:19 WARN]: 	at minelazz.hsb.h(ffa:84)
Console	: [0 21:14:19 WARN]: 	at minelazz.hsb.h(ffa:190)
Console	: [0 21:14:19 WARN]: 	at minelazz.otb.h(fla:293)
Console	: [0 21:14:19 WARN]: 	at com.minelazz.epicworldgenerator.nativeAPI.implementations.v1_15_R1.generator.NativeEpicChunkProvider2.addDecorations(cca:427)
Console	: [0 21:14:19 WARN]: 	at net.minecraft.server.v1_15_R1.ChunkStatus.lambda$static$9(ChunkStatus.java:65)
Console	: [0 21:14:19 WARN]: 	at net.minecraft.server.v1_15_R1.ChunkStatus.a(ChunkStatus.java:186)
Console	: [0 21:14:19 WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$23(PlayerChunkMap.java:767)
Console	: [0 21:14:19 WARN]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
Console	: [0 21:14:19 WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$b$25(PlayerChunkMap.java:765)
Console	: [0 21:14:19 WARN]: 	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58)
Console	: [0 21:14:19 WARN]: 	at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(ThreadedMailbox.java:78)
Console	: [0 21:14:19 WARN]: 	at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(ThreadedMailbox.java:120)
Console	: [0 21:14:19 WARN]: 	at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(ThreadedMailbox.java:86)
Console	: [0 21:14:19 WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Console	: [0 21:14:19 WARN]: Caused by: java.lang.InternalError: Malformed class name
Console	: [0 21:14:19 WARN]: 	at java.lang.Class.getSimpleBinaryName(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at java.lang.Class.getSimpleName(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at java.lang.Class.isAnonymousClass(Unknown Source)
Console	: [0 21:14:19 WARN]: 	at co.aikar.timings.MinecraftTimings.lambda$getPluginTaskTimings$0(MinecraftTimings.java:72)
Console	: [0 21:14:19 WARN]: 	... 29 more
Console	: [0 21:14:19 WARN]: Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -14
Console	: [0 21:14:19 WARN]: 	at java.lang.String.substring(Unknown Source)
Console	: [0 21:14:19 WARN]: 	... 33 more
Console	: [0 21:15:00 INFO]: [Server] Saving world data. Expect lag for a short while.
Console	: [0 21:15:00 INFO]: Saving the game (this may take a moment!)
Console	: [0 21:15:05 INFO]: Saved the game
Console	: [0 21:15:05 INFO]: [Server] Save Complete
Console	: [0 21:15:05 WARN]: Can't keep up! Is the server overloaded? Running 5336ms or 106 ticks behind
Console	: [0 21:19:03 WARN]: Can't keep up! Is the server overloaded? Running 5024ms or 100 ticks behind
Console	: [0 21:19:15 INFO]: Evilknuffel was slain by The Darkness
Console	: [0 21:19:22 INFO]: Evilknuffel issued server command: /back
Console	: [0 21:20:17 WARN]: Can't keep up! Is the server overloaded? Running 5013ms or 100 ticks behind

**Comment by wizjany** [comment]
that's completely unrelated
