### ISSUE TITLE
1.14.2 Maps not properly saving

### ISSUE THREAD

**Issue by CaptainAmpersand** [PaperMC/Paper#2198]
### What behavior is expected:
___What you expected to see___
Properly working maps, which don't create an error. Some players were complaining a few days ago about maps not being properly populated, and that it is having an issue saying "This map exists"

### What behavior is observed:
___What you actually saw___
This is the first error I've properly seen for maps, and now I can begin to actually report the errors I see with maps. I believe it might be related to #2170 , however my server didn't crash. The only consistency between his issue and mine is the fact that my players timed out, but it was 3 minutes later

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
N/A | The only world that which was upgraded from 1.13 was a spawn. There were no maps in said spawn.
This is a 1.14.2 world, running Paper-93 (I saw that paper 94 came out, however it doesn't seem to have anything to do with maps), just ElectronicBoy being an MVP.
The steps which I took were upgrading a spawn from 1.13, deleting the `world` file as to regenerate a fresh 1.14 main world, and that's all I can truly say for this.

### Plugin list:
___A list of your plugins___
Plugins (81): AdvancedEnchantments, AdvancedHelp, ArmorStandTools, AutoRestart, Bank, BarAPI, BetterRTP, BileTools, BossShopPro, Citizens, CombatLogX, CommandNPC, CommandSpy, Core, CoreProtect, CraftingStore, CrateReloaded, CrazyAuctions, DeluxeChat, DeluxeCommands, DeluxeJoin, DeluxeMenus, DeluxeTags, Denizen, DiscordSRV, DiscordSRV-Staff-Chat, Duels, EasyBackup, EasyBackupCore, EditableSign, EliteMobs, Essentials, EssentialsChat, EssentialsGeoIP, EZRanksPro, FishingEvent, GriefPrevention, GriefPreventionAddPvPToggle, GriefPreventionNoMobs, GuiRedeemMCMMO, HalfSleepServer, HeadDatabase, HideMyPlugins, HolographicDisplays, HopperFilter, HorseTpWithMe, Item2Chat, ItemShops, Jobs, LimitedCreative, LiteBans, MarriageMaster, mcMMO, MessageAnnouncer, MineableSpawners, Minepacks, Multiverse-Core, NanoReport, OpenInv, PatchNotes, PermissionsEx, PlaceholderAPI, PlayerParticles, PlayerWarps, PraiseTheSun, PremiumVanish, ProtocolLib, RandomLootChest, RedeemMe, ReferralRemastered, SimpleSit, TAB*, Vault, VoidGenerator, VoidSpawn, VoteParty, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-93 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
Has occurred 

### Anything else:
___Anything else you think may help us resolve the problem___
Error itself (Not asked for here, kinda interesting kinda cool sure sure sure:
```[08:15:05] [Server thread/ERROR]: Error loading saved data: idcounts
java.lang.ArrayIndexOutOfBoundsException: null
	at java.io.PushbackInputStream.unread(PushbackInputStream.java:235) ~[?:1.8.0_201]
	at net.minecraft.server.v1_14_R1.WorldPersistentData.a(WorldPersistentData.java:153) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.WorldPersistentData.a(WorldPersistentData.java:87) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.WorldPersistentData.b(WorldPersistentData.java:59) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.WorldPersistentData.a(WorldPersistentData.java:36) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.WorldServer.getWorldMapCount(WorldServer.java:1489) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.ItemWorldMap.a(ItemWorldMap.java:50) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.ItemWorldMap.createFilledMapView(ItemWorldMap.java:23) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootItemFunctionExplorationMap.a(SourceFile:70) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootItemFunctionConditional.apply(SourceFile:35) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootItemFunctionConditional.apply(SourceFile:24) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootItemFunction.a(SourceFile:16) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootItem.a(SourceFile:28) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootSelectorEntry$1.a(LootSelectorEntry.java:23) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootSelector.b(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootSelector.a(SourceFile:99) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootTable.populateLootDirect(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootTable.populateLoot(SourceFile:84) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootTable.populateLoot(SourceFile:89) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.LootTable.fillInventory(SourceFile:108) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.TileEntityLootable.d(TileEntityLootable.java:62) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.TileEntityLootable.createMenu(TileEntityLootable.java:130) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.EntityPlayer.openContainer(EntityPlayer.java:1133) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.BlockChest.interact(BlockChest.java:202) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.IBlockData.interact(IBlockData.java:221) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:487) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1393) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:976) ~[patched_1.14.2.jar:git-Paper-93]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-93]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]```

**Comment by electronicboy** [comment]
quick peek makes it look like you have a map file that wasn't saved to the disk fully

**Comment by CaptainAmpersand** [comment]
How would I go about removing/fixing such a thing?

**Comment by aikar** [comment]
Closing due to 1.14, please reopen a new ticket if still persists on 1.15.2 latest
