### ISSUE TITLE
Error when check version

### ISSUE THREAD

**Issue by netherstar** [PaperMC/Paper#222]
```
[03:15:59] [Server thread/INFO]: This server is running Paper version git-Paper-689 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)[m
[03:15:59] [Server thread/INFO]: Checking version, please wait...[m
[03:15:59] [Thread-66/WARN]: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[03:15:59] [Thread-66/WARN]:    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[03:15:59] [Thread-66/WARN]:    at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
[03:15:59] [Thread-66/WARN]:    at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
[03:15:59] [Thread-66/WARN]:    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
[03:15:59] [Thread-66/WARN]:    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[03:15:59] [Thread-66/WARN]:    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[03:15:59] [Thread-66/WARN]:    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[03:15:59] [Thread-66/WARN]:    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[03:15:59] [Thread-66/WARN]:    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[03:15:59] [Thread-66/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
[03:15:59] [Thread-66/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[03:15:59] [Thread-66/WARN]:    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[03:15:59] [Thread-66/WARN]:    at java.net.URL.openStream(URL.java:1045)
[03:15:59] [Thread-66/WARN]:    at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:87)
[03:15:59] [Thread-66/WARN]:    at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
[03:15:59] [Thread-66/WARN]:    at com.google.common.io.CharSource.openBufferedStream(CharSource.java:106)
[03:15:59] [Thread-66/WARN]:    at org.bukkit.command.defaults.VersionCommand.getFromJenkins(VersionCommand.java:275)
[03:15:59] [Thread-66/WARN]:    at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:248)
[03:15:59] [Thread-66/WARN]:    at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:196)
[03:15:59] [Thread-66/WARN]:    at org.bukkit.command.defaults.VersionCommand.access$0(VersionCommand.java:191)
[03:15:59] [Thread-66/WARN]:    at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:181)
[03:15:59] [Thread-66/WARN]:    at java.lang.Thread.run(Thread.java:745)
[03:15:59] [Thread-66/INFO]: Error obtaining version information[m
```

**Comment by zachbr** [comment]
Issue is resolved on our end. Your side will eventually update to resolve this.

**Comment by zachbr** [comment]
Edit: we'll double check this in a few hours I guess just to be safe.

**Comment by zachbr** [comment]
For anyone else that sees this, this is caused by Cloudflare's [Browser Integrity Check](https://support.cloudflare.com/hc/en-us/articles/200170086-What-does-the-Browser-Integrity-Check-do-). Supposedly it can be worked around by sending some valid looking headers with the request, but for now we've just disabled it for buildNumber requests. We may eventually look at changing the code to support this, but for now it's unnecessary.

[Relevant StackOverflow Post](https://stackoverflow.com/questions/23445493/java-http-get-request-gives-403-forbidden-but-works-in-browser)

**Comment by WonderDave** [comment]
@Zbob750 I'm seeing this exact sequence of error messages when I issue a "version" command, either from the console or in-game. I just moved my Minecraft server to a CentOS 7 server, which is when the problem started.  Can you point me in the right direction for what I need to do on my end to fix this problem? This isn't a major issue, but it's still kind of annoying.  Thanks.

**Comment by zachbr** [comment]
Exactly this or the other issue you commented on? They're two separate issues. Give us the error stack trace either here or in IRC please.

**Comment by WonderDave** [comment]
@Zbob750  Here's the stack trace:

```
version
[06:10:14 INFO]: This server is running Paper version git-Paper-764 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
[06:10:14 INFO]: Checking version, please wait...
[06:10:15 WARN]: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[06:10:15 WARN]:        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[06:10:15 WARN]:        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
[06:10:15 WARN]:        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
[06:10:15 WARN]:        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
[06:10:15 WARN]:        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[06:10:15 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[06:10:15 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[06:10:15 WARN]:        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[06:10:15 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[06:10:15 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
[06:10:15 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[06:10:15 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[06:10:15 WARN]:        at java.net.URL.openStream(URL.java:1045)
[06:10:15 WARN]:        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:87)
[06:10:15 WARN]:        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
[06:10:15 WARN]:        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:106)
[06:10:15 WARN]:        at org.bukkit.command.defaults.VersionCommand.getFromJenkins(VersionCommand.java:275)
[06:10:15 WARN]:        at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:248)
[06:10:15 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:196)
[06:10:15 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$0(VersionCommand.java:191)
[06:10:15 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:181)
[06:10:15 WARN]:        at java.lang.Thread.run(Thread.java:745)
[06:10:15 INFO]: Error obtaining version information
```

**Comment by zachbr** [comment]
Stop the server, start it again, let me know if it's working now. Although I cannot reproduce your problems.

**Comment by WonderDave** [comment]
No change, same info/warning messages.

**Comment by zachbr** [comment]
Welp, I have no idea. I assume Cloudflare is blocking you, but it seems specific to you. Host/Provider? Geographical location? Are you the guy who flooded the CI earlier today xD (?)

**Comment by WonderDave** [comment]
Yeah, it's starting to sound like it's specific to me.  It was working fine two weeks ago when I was still using MCProHosting.  It works just fine when I run a sandbox server from my local computer.  It must be something about my new Linode CentOS 7 setup.  Maybe I'll try to make some inquiries with them.

BTW, I have no idea what "CI" is or what it stands for, so I'm fairly sure I've haven't flooded it.  I'm actually pretty harmless.  I manage a tiny whitelisted server that usually has no one on it.  But, hey, it's fun.

**Comment by zachbr** [comment]
Was more of a joke, someone flooded our server with requests today. The Continuous Integration, or CI, server is where we provide downloads and version info. It's not something you accidentally flood, no worries :).

If you do find out why it's happening, post it here so everyone can know.

**Comment by ChanceSD** [comment]
Also got the same issue with Centos 7

**Comment by zachbr** [comment]
Entirely possible centos 7 has an outdated network package that's causing an issue somewhere.
Not much we can do about it, other than swallow the stacktrace that gets put in console.

Edit: I also do not run any CentOS machines, nor do I really want to for reasons external to this issue.

**Comment by NachtRaben** [comment]
People running on centos could try updating their ca-certificates package to see if it can alleviate this issue. I run on debian so i can't personally test this.
