### ISSUE TITLE
Citizens NPCS not working 

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2235]
### What behaviour is expected:
Citizen npcs working as intended

### What behaviour is observed:
No Citizen npcs at all

### Steps/models to reproduce:
Use 1.14.3 build 111

### Plugin list:
Citizens

### Paper build number:
111

### Anything else:
[17:19:59 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-111]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-111]
        at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-111]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-111]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-111]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-111]        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-111]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

I got similar error messages for all my npcs.

**Comment by electronicboy** [comment]
You're missing the actual error, more than likely you need to go update your plugins.
