### ISSUE TITLE
TIMING_STACK_CORRUPTION

### ISSUE THREAD

**Issue by Kalamityy** [PaperMC/Paper#2249]
### Link/paste of stack trace (No players were online at all when this was taken)

[20:09:25 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-112]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-112]
        at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-112]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-112]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-112]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-112]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-112]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-112]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[20:09:26 WARN]: Can't keep up! Is the server overloaded? Running 5847ms or 116 ticks behind
[20:09:29 INFO]: [GoldenCrates/INFO] Auto-save: Saved 0 online users | 0 offline users.
[20:09:32 INFO]: Starting UUID caching
[20:09:32 INFO]: [P2] Starting player data caching for: survival
[20:09:32 INFO]: Fast mode UUID caching enabled!
[20:09:32 INFO]: [P2] Cached a total of: 1 UUIDs
[20:09:34 FATAL]: ChunkTooLarge! Someone is trying to duplicate. (r.-3.-1.mca - -66,-30) Go clean it up to remove this message. /minecraft:tp -1056 128 -480 - DO NOT REPORT THIS TO PAPER - You may ask for help on Discord, but do not file an issue. These error messages can not be removed.
[20:09:35 FATAL]: ChunkTooLarge even after reduction. Trying in overzealous mode. (r.-3.-1.mca - -66,-30) Go clean it up to remove this message. /minecraft:tp -1056 128 -480 - 

### Plugin list:
[20:14:54 INFO]: Plugins (37): AdvancedPortals, BlockParticles, Citizens, ClearLag, CoreProtect, CustomCrafting, DiscordSRV, Essentials, EssentialsAntiBuild, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, GoldenCrates, GriefPrevention, GriefPreventionFlags, HeadBuy, ItemEdit, JupiterCore, LuckPerms, Multiverse-Core, Multiverse-Inventories, OpenInv*, PlaceholderAPI*, PlotSquared, ProtocolLib*, Ptest, Residence, Shop, Shopkeepers, TAB*, Vault, VentureChat, Wild, WolfyUtilities, WorldEdit, WorldGuard

### Actions to reproduce (if known):
running server / starting server

### Paper build number:
[20:15:27 INFO]: This server is running Paper version git-Paper-112 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
[20:15:27 INFO]: Checking version, please wait...
[20:15:27 INFO]: Previous version: git-Paper-59 (MC: 1.14.2)
[20:15:27 INFO]: You are 3 version(s) behind

**Comment by electronicboy** [comment]
There will be a stack trace before the timings error, You'll need to try the latest dev build of citizens
