### ISSUE TITLE
1.14.3: Custom entity pig fails to attack

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Paper#2300]
Minecraft 1.14.3
Paper build 126

**Problem**:
While adding a custom entity pig to the world that would attack player, once the pig reaches a player to attack in survival mode, instead of attacking it disappears and the following error appears in the console.

**Code**:
![a](https://i.imgur.com/OD29e3j.png)

**Error**:

```
[07:07:24 WARN]: Entity threw exception at world:162.25884290112532,4.0,-56.48282167082963
[07:07:24 WARN]: java.lang.NullPointerException
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.EntityInsentient.C(EntityInsentient.java:1282)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.PathfinderGoalMeleeAttack.a(SourceFile:139)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.PathfinderGoalMeleeAttack.e(SourceFile:131)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.e(SourceFile:55)
[07:07:24 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[07:07:24 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[07:07:24 WARN]:        at java.util.Iterator.forEachRemaining(Iterator.java:116)
[07:07:24 WARN]:        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[07:07:24 WARN]:        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[07:07:24 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[07:07:24 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[07:07:24 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[07:07:24 WARN]:        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[07:07:24 WARN]:        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:80)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:662)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2528)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:504)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:28)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2317)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:580)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.World.a(World.java:930)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
[07:07:24 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[07:07:24 WARN]:        at java.lang.Thread.run(Thread.java:748)
[07:07:24 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - org.mineacademy.crux.TestCommand$CustomEntity} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-126]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-126]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:368) ~[patched_1.14.3.jar:git-Paper-126]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-126]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-126]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-126]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-126]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by Spottedleaf** [comment]
Not sure why this is an issue here.
Looking at the source says the pig is missing an `ATTACK_DAMAGE` attribute. Further spection reveals that pigs, unsurprisingly, don't actually register that attribute. This is your issue.

**Comment by kangarko** [comment]
Thanks, I thought this could be Paper/Spigot since I was using purely NMS code for that section.
