### ISSUE TITLE
[1.14.4] Breaking and interacting with shulkers/ender chests causes errors

### ISSUE THREAD

**Issue by vincewip** [PaperMC/Paper#2350]
### Link/paste of stack trace
```
[16:02:58] [Server thread/FATAL]: Error executing task on Server
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
	at net.minecraft.server.v1_14_R1.WorldServer.notify(WorldServer.java:1281) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.World.notifyAndUpdatePhysics(World.java:497) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.World.setTypeAndData(World.java:473) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.World.a(World.java:538) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:345) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:261) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:235) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-135]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

### Plugin list:
PlaceholderAPI, CoreProtect, TabList, WorldBorder

### Actions to reproduce (if known):
https://streamable.com/7tggp

Place an ender chest / shulker box on the ground. Interacting with either throws the above error. Breaking the shulker box didn't drop the box, and breaking the ender chest with a silk touch pickaxe didn't drop anything.

### Paper build number:
Paper-135

**Comment by gorudoninjin** [comment]
Weirdly enough when I went to record a video to reproduce the problem the blocks properly dropped again, and the errors stopped.

**Comment by Spottedleaf** [comment]
cannot produce locally

**Comment by NullCase** [comment]
I had a problem like this early on while testing 1.14. I don't know what finally resolved this , but now that I see you still have it, it seems like updating plugins to 1.14 might have done the trick.

**Comment by electronicboy** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/3a713bd57bc6db10de2ab6dcb79c294236e26209
