### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by calendryx** [PaperMC/Paper#2375]
```26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1228) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:167) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.d(PlayerList.java:757) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:906) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.CommandDispatcher.a(CommandDispatcher.java:249) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at net.minecraft.server.v1_14_R1.CommandDispatcher.a(CommandDispatcher.java:276) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:20) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:39) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at com.sk89q.bukkit.util.DynamicPluginCommand.testPermissionSilent(DynamicPluginCommand.java:100) ~[?:?]
26.07 10:10:19 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitCommandInspector.testPermission(BukkitCommandInspector.java:80) ~[?:?]
26.07 10:10:19 [Server] INFO at com.sk89q.worldedit.command.util.PermissionCondition.satisfied(PermissionCondition.java:47) ~[?:?]
26.07 10:10:19 [Server] INFO at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at com.sk89q.worldedit.command.util.PermissionCondition.lambda$satisfied$0(PermissionCondition.java:47) ~[?:?]
26.07 10:10:19 [Server] INFO at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:164) ~[?:?]
26.07 10:10:19 [Server] INFO at com.sk89q.wepif.PermissionsResolverManager.hasPermission(PermissionsResolverManager.java:174) ~[?:?]
26.07 10:10:19 [Server] INFO at com.sk89q.wepif.GroupManagerResolver.hasPermission(GroupManagerResolver.java:104) ~[?:?]
26.07 10:10:19 [Server] INFO at com.sk89q.wepif.GroupManagerResolver.getPermissionHandler(GroupManagerResolver.java:66) ~[?:?]
26.07 10:10:19 [Server] INFO at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldPermissions(WorldsHolder.java:489) ~[?:?]
26.07 10:10:19 [Server] INFO at org.anjocaido.groupmanager.dataholder.WorldDataHolder.getPermissionsHandler(WorldDataHolder.java:1213) ~[?:?]
26.07 10:10:19 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[patched_1.14.4.jar:git-Paper-135]
26.07 10:10:19 [Server] INFO at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_222]
26.07 10:10:19 [Server] INFO java.lang.IllegalStateException: zip file closed
26.07 10:10:19 [Server] WARN Failed to handle packet for /74.192.218.162:53007```

**Comment by calendryx** [comment]
An error occurred when I teleported a player using multiverse and then every time they try to join they get this exact error every time.

*Paper Version: git-Paper-135 (MC: 1.14.4)*

**Comment by Spottedleaf** [comment]
please don't use /reload

**Comment by calendryx** [comment]
But I haven't used /reload ever on my server

**Comment by clrxbl** [comment]
What about Plugman @CatMaster3645

**Comment by calendryx** [comment]
What's Plugman?

**Comment by electronicboy** [comment]
A plugin (probably GM) likely didn't load properly and left itself in a state where it's disabled but still has classes floating around, I'd suggest seeking support on discord/the forums and providing your full log file

**Comment by calendryx** [comment]
alright
