### ISSUE TITLE
Random NPE

### ISSUE THREAD

**Issue by Ghost-chu** [PaperMC/Paper#2378]
### What behaviour is expected:
___What you expected to see___
No errors.
### What behaviour is observed:
___What you actually saw___
```
[12:02:50 FATAL]: Error executing task on Server
java.lang.NullPointerException: null
at net.minecraft.server.v1_14_R1.ChunkMapDistance.b(ChunkMapDistance.java:245) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1039) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:586) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:493) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.PacketPlayInTeleportAccept.a(SourceFile:31) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.PacketPlayInTeleportAccept.a(SourceFile:8) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[PaperSpigot-1.14.4.jar:git-Paper-146]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Randomly
### Plugin list:
___A list of your plugins___
```
:11:22 INFO]: Plugins (70): AntiMCLeaks, AT, BungeeTabListPlus*, Citizens, CmdConfirm*, CommandNotifier, Confiscate, ConsoleSpamFix, CoreProtect, CoreProtectTNT, CraftBook, DeathBarrel, dynmap*, Dynmap-Essentials*, EasyBackup*, EasyBackupCore*, EntityDetection, EntityStats, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, F3Name, F3NPerm, FastFarmStopper, FixMyData*, FuckCR, GoodByeSkullLagg, HamsterEcoHelper, HeadDropsSS, HopperFilter, InventoryRollback, LangUtils, Lift, LockettePro, Lores*, LuckPerms, mcMMO, MineSecure*, MineSync*, MobFarmManager, Multiverse-Core, MyPet, NoCreativePhantoms, NoSpawnerChange, NyaaCore, PetMaster, PictureLogin*, PlaceholderAPI*, Plan*, PlayTimeTracker, PlugMan*, PortalFix*, PortForwardCraft*, ProtocolLib*, QuickShop, ravager-anti-grief, SafetyReboot*, SAML, Shell*, SmoothSleep, spark, SuperVanish, TitleManager*, Vault, WorldEdit, yasui, YouAreNotLostConnection*
```
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
#135 1.14.4
### Anything else:
___Anything else you think may help us resolve the problem___
I turned on the X-Ray

**Comment by electronicboy** [comment]
Please update before reporting any further issues.
