### ISSUE TITLE
PlayerStatisticIncrementEvent called async at shutdown

### ISSUE THREAD

**Issue by Rvby1** [PaperMC/Paper#2379]
### Link/paste of stack trace

You can find the stack trace that occurs after the server times out [here](https://pastebin.com/Zb5zc9MJ).

### Plugin list:
AutoRestart, CoreProtect, DiscordSRV, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FastLeafDecay, GriefPrevention, Harbor, HorseTpWithMe, Jobs, LuckPerms, MarriageMaster, PlayerParticles, ProtocolLib, QuickShop, SAML, SuperVanish, Vault, VillagerOptimiser, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Opening sunken chest located inside ship at -1162, 65, 5949 OR -1529, 64, 5891 causes the server to stall. Chat still works, and blocks will break and stay broken. However, broken blocks do not drop entities, and if players drop entities, they can not pick them up again. After 60 seconds of the server stalling, the server crashes per the timeout settings in the config. 

Cannot absolutely confirm that the stalls only occur in r.3.11. However, players on my server have opened sunken chests in plenty of other regions without causing the server to stall and crash. 

Other chests placed in the region do not cause the server to stall when opened. Have not confirmed this with naturally generated chests in the region. 

Have not confirmed if other sunken ships in the region aside from the two listed cause the server to stall and crash. 

[You can find the region file and level.dat in this 7zip archive.](https://github.com/PaperMC/Paper/files/3437881/Paper-SunkenTreasure-Crash.zip)

### Paper build number:
git-Paper-135 (MC: 1.14.4)

**Comment by electronicboy** [comment]
Duplicate of #2312

**Comment by zachbr** [comment]
Relevant part of this ticket is the event being called from shutdown. That stacktrace is below. The watchdog shutdown cause is being tracked in 2312.
```
[20:38:36 WARN]: Exception in thread "Thread-2" java.lang.IllegalStateException: PlayerStatisticIncrementEvent may only be triggered synchronously.
[20:38:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533)
[20:38:36 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleStatisticsIncrease(CraftEventFactory.java:1449)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.StatisticManager.b(StatisticManager.java:17)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:1287)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.EntityHuman.b(EntityHuman.java:1430)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.EntityHuman.a(EntityHuman.java:1422)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.PlayerList.disconnect(PlayerList.java:403)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.disconnect(PlayerConnection.java:279)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.PlayerList.shutdown(PlayerList.java:1099)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:737)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:742)
[20:38:36 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.close(MinecraftServer.java:703)
[20:38:36 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.util.ServerShutdownThread.run(ServerShutdownThread.java:17)
```

**Comment by ImPrithibi** [comment]
> ### Link/paste of stack trace
> You can find the stack trace that occurs after the server times out [here](https://pastebin.com/Zb5zc9MJ).
> 
> ### Plugin list:
> AutoRestart, CoreProtect, DiscordSRV, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FastLeafDecay, GriefPrevention, Harbor, HorseTpWithMe, Jobs, LuckPerms, MarriageMaster, PlayerParticles, ProtocolLib, QuickShop, SAML, SuperVanish, Vault, VillagerOptimiser, WorldBorder, WorldEdit, WorldGuard
> 
> ### Actions to reproduce (if known):
> Opening sunken chest located inside ship at -1162, 65, 5949 OR -1529, 64, 5891 causes the server to stall. Chat still works, and blocks will break and stay broken. However, broken blocks do not drop entities, and if players drop entities, they can not pick them up again. After 60 seconds of the server stalling, the server crashes per the timeout settings in the config.
> 
> Cannot absolutely confirm that the stalls only occur in r.3.11. However, players on my server have opened sunken chests in plenty of other regions without causing the server to stall and crash.
> 
> Other chests placed in the region do not cause the server to stall when opened. Have not confirmed this with naturally generated chests in the region.
> 
> Have not confirmed if other sunken ships in the region aside from the two listed cause the server to stall and crash.
> 
> [You can find the region file and level.dat in this 7zip archive.](https://github.com/PaperMC/Paper/files/3437881/Paper-SunkenTreasure-Crash.zip)
> 
> ### Paper build number:
> git-Paper-135 (MC: 1.14.4)

Hey im planing to use it on 1.16.1 server. I dont know if it will work.

**Comment by aikar** [comment]
Events firing async was mostly handled in 1.15+, as this code is skipped off main thread.

sunken ship issue is still tracked as linked.

**Comment by ImPrithibi** [comment]
Soo it wont work on 1.16?
