### ISSUE TITLE
Server crashes upon firing projectile

### ISSUE THREAD

**Issue by ssterling** [PaperMC/Paper#2404]
### Link/paste of stack trace

```
java.util.concurrent.CompletionException: net.minecraft.server.v1_14_R1.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:58)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: net.minecraft.server.v1_14_R1.ReportedException: Feature placement
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$17(PlayerChunkMap.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$b$19(PlayerChunkMap.java:553)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 11 more
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | -14 -134217728
	at net.minecraft.server.v1_14_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:96)
	at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:80)
	at net.minecraft.server.v1_14_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:64)
	at net.minecraft.server.v1_14_R1.RegionLimitedWorldAccess.getType(RegionLimitedWorldAccess.java:131)
	at net.minecraft.server.v1_14_R1.WorldGenLakes.a(SourceFile:83)
	at net.minecraft.server.v1_14_R1.WorldGenLakes.generate(SourceFile:20)
	at net.minecraft.server.v1_14_R1.WorldGenFeatureConfigured.a(SourceFile:36)
	at net.minecraft.server.v1_14_R1.WorldGenDecorator.a(SourceFile:85)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.minecraft.server.v1_14_R1.WorldGenDecorator.a(SourceFile:84)
	at net.minecraft.server.v1_14_R1.WorldGenDecoratorConfigured.a(SourceFile:35)
	at net.minecraft.server.v1_14_R1.WorldGenFeatureComposite.a(SourceFile:20)
	at net.minecraft.server.v1_14_R1.WorldGenFeatureComposite.generate(SourceFile:13)
	at net.minecraft.server.v1_14_R1.WorldGenFeatureConfigured.a(SourceFile:36)
	at net.minecraft.server.v1_14_R1.BiomeBase.a(BiomeBase.java:255)
	at net.minecraft.server.v1_14_R1.ChunkGenerator.addDecorations(ChunkGenerator.java:92)
	at net.minecraft.server.v1_14_R1.ChunkStatus.lambda$static$9(ChunkStatus.java:63)
	at net.minecraft.server.v1_14_R1.ChunkStatus.a(ChunkStatus.java:185)
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$17(PlayerChunkMap.java:555)
	... 14 more
```

The original log file as well as the crash report file are attached below:
* [crash-2019-08-03_22.42.32-server.txt](https://github.com/PaperMC/Paper/files/3464401/crash-2019-08-03_22.42.32-server.txt)
* [latest.log](https://github.com/PaperMC/Paper/files/3464402/latest.log)

### Plugin list:

I usually have quite a few running, but this crash also happens with no plugins loaded.

### Actions to reproduce (if known):

Fire any type of projectile.  However, I can't reproduce this on a test server using unmodified config.

### Paper build number:

git-Paper-156 (MC: 1.14.4)

**Comment by Proximyst** [comment]
Works fine on 1.16.2. Create a new issue if you can reproduce on newer versions.
