### ISSUE TITLE
Server Crash BlockState

### ISSUE THREAD

**Issue by andfont** [PaperMC/Paper#2410]
Server: paper 1.14.4 build 156
description:
Our server was SPIGOT and we decided to try PAPER the first day! We have tried it, THE SERVER HAS NOT FALLEN! the first day! They did not say that it was better paper but we are saying that it is not true, so for the moment we pass you the error and we will return to SPIGOT! regards!
Complete error:
https://pastebin.com/XNTrpF60
Error console:
19:08:56] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Failed to read BlockState at: world: mundoabf location: (368, 11, -536)
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:48) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftCreatureSpawner.<init>(CraftCreatureSpawner.java:15) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState0(CraftBlock.java:359) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState(CraftBlock.java:322) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.CraftChunk.getTileEntities(CraftChunk.java:147) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:122) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:104) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:119) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:75) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1142) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-156]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassCastException: Cannot cast net.minecraft.server.v1_14_R1.TileEntityChest to net.minecraft.server.v1_14_R1.TileEntityMobSpawner
	at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_212]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:28) ~[patched_1.14.4.jar:git-Paper-156]
	... 12 more
[19:08:56] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.ClassCastException: Cannot cast net.minecraft.server.v1_14_R1.TileEntityChest to net.minecraft.server.v1_14_R1.TileEntityMobSpawner
	at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_212]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:28) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftCreatureSpawner.<init>(CraftCreatureSpawner.java:15) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState0(CraftBlock.java:359) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState(CraftBlock.java:322) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.CraftChunk.getTileEntities(CraftChunk.java:147) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:122) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:104) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:119) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:75) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1142) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-156]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by electronicboy** [comment]
Disable timings and go break the block its complaining about, your world is inconsistent

**Comment by andfont** [comment]
what?? My world works perfectly! and we need timings! to see the stability of the entire server! Is this an answer? really? REPITO THAT IN SPIGOT WE HAVE NOT HAD THIS PROBLEM! and close the case and you stay so perfect trankilos! I see how you work nothing nothing continue like this!

**Comment by Spottedleaf** [comment]
Duplicate of https://github.com/PaperMC/Paper/issues/2202

**Comment by electronicboy** [comment]
Spigot doesn't have timings v2 (meaning it doesn't care about some of the stats that paper records). You have a chest block in the world that has a mobspawner TileEntity, which causes craftbukkit to throw an exception, the only fix on your side is to go break the affected block; There is a suspected deeper cause that needs to be looked into

**Comment by andfont** [comment]
I understand the problem, what I don't understand is that I throw the server completely! indicating the damaged / corrupt block etc. but never never never stop the server! with spigot that didn't happen to me! I am using the paper now because it has xray but if it happens again I will have to make a decision! please do not stop the server simply exit the console error etc. greetings
