### ISSUE TITLE
i am getings this error

### ISSUE THREAD

**Issue by CyberGodbg** [PaperMC/Paper#2434]
[global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 WARN]: Entity threw exception at world:-714.8821,79.0,326.9152
[12:24:16 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
[12:24:16 WARN]:        at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
[12:24:16 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:310)
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:584)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.World.a(World.java:936)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:356)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
[12:24:16 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:24:16 WARN]: Entity threw exception at world:-740.2998,74.0,303.5307
[12:24:16 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
[12:24:16 WARN]:        at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
[12:24:16 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:310)
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:584)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.World.a(World.java:936)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:356)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
[12:24:16 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:24:16 WARN]: Entity threw exception at world:-794.3537,90.0,388.514
[12:24:16 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
[12:24:16 WARN]:        at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
[12:24:16 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:310)
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:584)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.World.a(World.java:936)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:356)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
[12:24:16 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:24:16 WARN]: Entity threw exception at world:-757.5932,88.0,288.6958
[12:24:16 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
[12:24:16 WARN]:        at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
[12:24:16 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:310)
[12:24:16 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:584)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.World.a(World.java:936)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:356)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074)
[12:24:16 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
[12:24:16 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:24:16 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[paper.jar:git-Paper-"aa022fda"]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:370) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-"aa022fda"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-"aa022fda"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by electronicboy** [comment]
`[12:24:16 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z` issue is down to an incorrect version of citizens for your server
