### ISSUE TITLE
Player gets "bad packet id 26" on join when unbanned from tempban

### ISSUE THREAD

**Issue by LinuxSquare** [PaperMC/Paper#2437]
**To clear everybody up, I'm trying to create my own ban-system plugin (more like servertools with playerinformation and similar stuff)**
Source Code: https://git.dragon-clouds.com/linuxsquare/ServerTools

### What behaviour is expected:
The Player can join without any issues or errors, after being automatically unbanned after tempban.

### What behaviour is observed:
On first join, the Player gets the message:
```
Internal Exception: io.netty.handler.codec.DecoderException:
java.io.IOException: Bad packet id 26
```
on the second try, the player can join without any issues.

### Steps/models to reproduce:
Load my plugin into a minecraft-server running paper-spigot (obviously).
Join one or two users onto the server and tempban one of them using `/tempban <Playername> (duration)` or `tempban <Playername> (duration)` via console.

i.e.
`/tempban LinuxSquare 7s`

### Plugin list:
ServerTools (My plugin)

### Paper build number:
```
This server is running Paper version git-Paper-163 (MC: 1.14.4)
(Implementing API version 1.14.4-R0.1-SNAPSHOT)
```
### Anything else:
Terminal Log:
```
[15:27:49 WARN]: Failed to handle packet for /127.0.0.1:56976
java.lang.NullPointerException: null
        at net.minecraft.server.v1_14_R1.PlayerList.attemptLogin(PlayerList.java:515) ~[patched_1.14.4.jar:git-Paper-163]
        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:154) ~[patched_1.14.4.jar:git-Paper-163]
        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-163]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-163]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-163]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-163]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-163]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-163]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-163]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`
```

The sourcecode of my `TempbanCommand.java`:
```java
public class TempbanCommand implements CommandExecutor {

	@Override
	public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {

		if (args.length >= 2) {
			OfflinePlayer target = Bukkit.getOfflinePlayer(Bukkit.getPlayerUniqueId(args[0]));
			if (target.isBanned()) {
				sender.sendMessage("§4" + target.getName() + " is already banned");
				return true;
			}

			if (PlayersConfigManager.get().get(target.getUniqueId() + ".UUID") == null) {
				sender.sendMessage("§4The player §6" + args[0] + " §4has never played on this server!");
				return true;
			}
			long secs = 0;

			if (args[1].contains(".") || args[1].contains(",")) {
				sender.sendMessage("§4Time can't have fractional digits");
				return true;
			} else {
				if (args[1].contains("s")) {
					long sec = Integer.parseInt(args[1].replaceAll(".*?(\\d+).*", "$1"));
					secs = sec * 1000;
				} else if (args[1].contains("min")) {
					long min = Integer.parseInt(args[1].replaceAll(".*?(\\d+).*", "$1"));
					secs = (min * 60) * 1000;
				} else if (args[1].contains("h")) {
					long hours = Integer.parseInt(args[1].replaceAll(".*?(\\d+).*", "$1"));
					secs = ((hours * 60) * 60) * 1000;
				} else if (args[1].contains("d")) {
					long days = Integer.parseInt(args[1].replaceAll(".*?(\\d+).*", "$1"));
					secs = (((days * 24) * 60) * 60) * 1000;
				} else if (args[1].contains("m")) {
					long month = Integer.parseInt(args[1].replaceAll(".*?(\\d+).*", "$1"));
					secs = ((((month * 30) * 24) * 60) * 60) * 1000;
				} else if (args[1].contains("y")) {
					long years = Integer.parseInt(args[1].replaceAll(".*?(\\d+).*", "$1"));
					secs = (((((years * 12) * 30) * 24) * 60) * 60) * 1000;
				} else {
					sender.sendMessage("§4Invalid time format. Please specify (s/min/h/d/m/y)");
					return true;
				}
			}

			String reason;
			if (args.length > 2) {
				StringBuffer sb = new StringBuffer();
				for (int i = 2; i < args.length; i++) {
					sb.append(args[i]);
					sb.append(" ");
				}
				sb.substring(0, (sb.length() - 1));
				sb.append("!");
				reason = sb.toString();
			} else {
				reason = "The Ban-Hammer has spoken";
			}

			BanManager.tempban(target.getUniqueId(), reason, sender.getName(), secs);

		} else {
			sender.sendMessage("§4Please use /tempban <Player> <duration> (reason)");
		}

		return false;
	}

}
```

Sourcecode of the `tempban` method inside `BanManager.java`:
```java
public static void tempban(UUID tUID, String reason, String executor, long secs) {
		OfflinePlayer target = Bukkit.getOfflinePlayer(tUID);
		Date d = new Date(new Date().getTime() + secs);
		FileConfiguration conf = PlayersConfigManager.get();
		conf.set(target.getUniqueId() + ".ban.isBanned", true);
		conf.set(target.getUniqueId() + ".ban.executor", executor);
		conf.set(target.getUniqueId() + ".ban.reason", reason);
		conf.set(target.getUniqueId() + ".ban.until", d);
		PlayersConfigManager.save();
		target.banPlayer("§4You've been banned by: §6" + conf.getString(tUID + ".ban.executor") + "\n" + "§4for: §6"
				+ conf.getString(tUID + ".ban.reason") + "\n" + "§4Until: §6" + conf.getString(tUID + ".ban.until"),
				d);
	}
```

**Comment by TNTUP** [comment]
Had that issue on 1.12.2 with EssentialsX, can't say why it does that (sorry if its not related, saw your ticket and found I had that issue way back.

**Comment by Spottedleaf** [comment]
This issue goes to vanilla but it will be fixed soon (tm)
