### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by woolw0w** [PaperMC/Paper#2454]
### Link/paste of stack trace

    [08:10:32 INFO]: spore12345678910 lost connection: Disconnected
[08:10:34 INFO]: spore12345678910 left the game
[08:10:38 WARN]: Can't keep up! Is the server overloaded? Running 5252ms or 105 ticks behind
[08:13:03 WARN]: Can't keep up! Is the server overloaded? Running 77722ms or 1554 ticks behind
[08:13:03 ERROR]: ------------------------------
[08:13:03 ERROR]: The server has stopped responding! This is (probably) not a Paper bug.
[08:13:03 ERROR]: If you see a plugin in the Server thread dump below, then please report it to that author
[08:13:03 ERROR]:        *Especially* if it looks like HTTP or MySQL operations are occurring
[08:13:03 ERROR]: If you see a world save or edit, then it means you did far more than your server can handle at once
[08:13:03 ERROR]:        If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
[08:13:03 ERROR]: If you are unsure or still think this is a Paper bug, please report this to https://github.com/PaperMC/Paper/issues
[08:13:03 ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[08:13:03 ERROR]: Paper version: git-Paper-166 (MC: 1.14.4)
[08:13:03 ERROR]: ------------------------------
[08:13:03 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[08:13:03 INFO]: Rangerwield lost connection: Disconnected
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Server thread
[08:13:04 ERROR]:       PID: 20 | Suspended: false | Native: false | State: RUNNABLE
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.EntityLiving.b(EntityLiving.java:498)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.EntityHuman.b(EntityHuman.java:727)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.EntityPlayer.b(EntityPlayer.java:232)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.Entity.save(Entity.java:1618)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.WorldNBTStorage.save(WorldNBTStorage.java:195)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.PlayerList.savePlayerFile(PlayerList.java:385)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.PlayerList.disconnect(PlayerList.java:425)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.NetworkManager.handleDisconnection(NetworkManager.java:356)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:163)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Entire Thread Dump:
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Server-Worker-2590
[08:13:04 ERROR]:       PID: 2866 | Suspended: false | Native: false | State: WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.misc.Unsafe.park(Native Method)
[08:13:04 ERROR]:               java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Server-Worker-2588
[08:13:04 ERROR]:       PID: 2864 | Suspended: false | Native: false | State: TIMED_WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.misc.Unsafe.park(Native Method)
[08:13:04 ERROR]:               java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Netty Server IO #3
[08:13:04 ERROR]:       PID: 44 | Suspended: false | Native: false | State: RUNNABLE
[08:13:04 ERROR]:       Thread is waiting on monitor(s):
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.SelectorImpl.select(Unknown Source)
[08:13:04 ERROR]:               io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
[08:13:04 ERROR]:               io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
[08:13:04 ERROR]:               io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
[08:13:04 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Netty Server IO #2
[08:13:04 ERROR]:       PID: 37 | Suspended: false | Native: true | State: RUNNABLE
[08:13:04 ERROR]:       Thread is waiting on monitor(s):
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.SelectorImpl.select(Unknown Source)
[08:13:04 ERROR]:               io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
[08:13:04 ERROR]:               io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
[08:13:04 ERROR]:               io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
[08:13:04 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Netty Server IO #1
[08:13:04 ERROR]:       PID: 36 | Suspended: false | Native: true | State: RUNNABLE
[08:13:04 ERROR]:       Thread is waiting on monitor(s):
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.SelectorImpl.select(Unknown Source)
[08:13:04 ERROR]:               io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
[08:13:04 ERROR]:               io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
[08:13:04 ERROR]:               io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
[08:13:04 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Craft Async Scheduler Management Thread
[08:13:04 ERROR]:       PID: 35 | Suspended: false | Native: false | State: WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.misc.Unsafe.park(Native Method)
[08:13:04 ERROR]:               java.util.concurrent.locks.LockSupport.park(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Timer-1
[08:13:04 ERROR]:       PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               java.lang.Object.wait(Native Method)
[08:13:04 ERROR]:               java.util.TimerThread.mainLoop(Unknown Source)
[08:13:04 ERROR]:               java.util.TimerThread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Resource IO {0}
[08:13:04 ERROR]:       PID: 33 | Suspended: false | Native: false | State: WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.misc.Unsafe.park(Native Method)
[08:13:04 ERROR]:               java.util.concurrent.locks.LockSupport.park(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Netty Server IO #0
[08:13:04 ERROR]:       PID: 32 | Suspended: false | Native: true | State: RUNNABLE
[08:13:04 ERROR]:       Thread is waiting on monitor(s):
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:13:04 ERROR]:               sun.nio.ch.SelectorImpl.select(Unknown Source)
[08:13:04 ERROR]:               io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
[08:13:04 ERROR]:               io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
[08:13:04 ERROR]:               io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
[08:13:04 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: ObjectCleanerThread
[08:13:04 ERROR]:       PID: 31 | Suspended: false | Native: false | State: TIMED_WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               java.lang.Object.wait(Native Method)
[08:13:04 ERROR]:               java.lang.ref.ReferenceQueue.remove(Unknown Source)
[08:13:04 ERROR]:               io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54)
[08:13:04 ERROR]:               io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Timer-0
[08:13:04 ERROR]:       PID: 30 | Suspended: false | Native: false | State: TIMED_WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               java.lang.Object.wait(Native Method)
[08:13:04 ERROR]:               java.util.TimerThread.mainLoop(Unknown Source)
[08:13:04 ERROR]:               java.util.TimerThread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Paper Watchdog Thread
[08:13:04 ERROR]:       PID: 29 | Suspended: false | Native: false | State: RUNNABLE
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.management.ThreadImpl.dumpThreads0(Native Method)
[08:13:04 ERROR]:               sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
[08:13:04 ERROR]:               org.spigotmc.WatchdogThread.run(WatchdogThread.java:121)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Server console handler
[08:13:04 ERROR]:       PID: 24 | Suspended: false | Native: false | State: TIMED_WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               java.lang.Object.wait(Native Method)
[08:13:04 ERROR]:               org.jline.utils.NonBlockingPumpReader.wait(NonBlockingPumpReader.java:55)
[08:13:04 ERROR]:               org.jline.utils.NonBlockingPumpReader.read(NonBlockingPumpReader.java:101)
[08:13:04 ERROR]:               org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57)
[08:13:04 ERROR]:               org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133)
[08:13:04 ERROR]:               org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
[08:13:04 ERROR]:               org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
[08:13:04 ERROR]:               org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848)
[08:13:04 ERROR]:               org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868)
[08:13:04 ERROR]:               org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575)
[08:13:04 ERROR]:               org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418)
[08:13:04 ERROR]:               net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158)
[08:13:04 ERROR]:               net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.DedicatedServer$2.run(DedicatedServer.java:89)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: DestroyJavaVM
[08:13:04 ERROR]:       PID: 23 | Suspended: false | Native: false | State: RUNNABLE
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Server thread
[08:13:04 ERROR]:       PID: 20 | Suspended: false | Native: false | State: RUNNABLE
[08:13:04 ERROR]:       Thread is waiting on monitor(s):
[08:13:04 ERROR]:               Locked on:net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:163)
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               java.io.FileOutputStream.writeBytes(Native Method)
[08:13:04 ERROR]:               java.io.FileOutputStream.write(Unknown Source)
[08:13:04 ERROR]:               java.util.zip.GZIPOutputStream.finish(Unknown Source)
[08:13:04 ERROR]:               java.util.zip.DeflaterOutputStream.close(Unknown Source)
[08:13:04 ERROR]:               java.io.FilterOutputStream.close(Unknown Source)
[08:13:04 ERROR]:               java.io.FilterOutputStream.close(Unknown Source)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:64)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.WorldNBTStorage.save(WorldNBTStorage.java:199)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.PlayerList.savePlayerFile(PlayerList.java:385)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.PlayerList.disconnect(PlayerList.java:425)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.NetworkManager.handleDisconnection(NetworkManager.java:356)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:163)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Server Infinisleeper
[08:13:04 ERROR]:       PID: 22 | Suspended: false | Native: false | State: TIMED_WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               java.lang.Thread.sleep(Native Method)
[08:13:04 ERROR]:               net.minecraft.server.v1_14_R1.DedicatedServer$1.run(DedicatedServer.java:71)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Snooper Timer
[08:13:04 ERROR]:       PID: 19 | Suspended: false | Native: false | State: WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               java.lang.Object.wait(Native Method)
[08:13:04 ERROR]:               java.lang.Object.wait(Unknown Source)
[08:13:04 ERROR]:               java.util.TimerThread.mainLoop(Unknown Source)
[08:13:04 ERROR]:               java.util.TimerThread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Paper Async Task Handler Thread - 0
[08:13:04 ERROR]:       PID: 18 | Suspended: false | Native: false | State: WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.misc.Unsafe.park(Native Method)
[08:13:04 ERROR]:               java.util.concurrent.locks.LockSupport.park(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: WindowsStreamPump
[08:13:04 ERROR]:       PID: 14 | Suspended: false | Native: false | State: RUNNABLE
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               org.fusesource.jansi.internal.Kernel32.WaitForSingleObject(Native Method)
[08:13:04 ERROR]:               org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97)
[08:13:04 ERROR]:               org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:112)
[08:13:04 ERROR]:               org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:458)
[08:13:04 ERROR]:               org.jline.terminal.impl.AbstractWindowsTerminal$$Lambda$12/2104028992.run(Unknown Source)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Log4j2-TF-1-AsyncLogger[AsyncContext@5c647e05]-1
[08:13:04 ERROR]:       PID: 11 | Suspended: false | Native: false | State: TIMED_WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               sun.misc.Unsafe.park(Native Method)
[08:13:04 ERROR]:               java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
[08:13:04 ERROR]:               com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:38)
[08:13:04 ERROR]:               com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
[08:13:04 ERROR]:               com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159)
[08:13:04 ERROR]:               com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[08:13:04 ERROR]:               java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[08:13:04 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Attach Listener
[08:13:04 ERROR]:       PID: 5 | Suspended: false | Native: false | State: RUNNABLE
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Signal Dispatcher
[08:13:04 ERROR]:       PID: 4 | Suspended: false | Native: false | State: RUNNABLE
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Finalizer
[08:13:04 ERROR]:       PID: 3 | Suspended: false | Native: false | State: RUNNABLE
[08:13:04 ERROR]:       Thread is waiting on monitor(s):
[08:13:04 ERROR]:               Locked on:java.util.zip.Deflater.end(Unknown Source)
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               java.util.zip.Deflater.end(Native Method)
[08:13:04 ERROR]:               java.util.zip.Deflater.end(Unknown Source)
[08:13:04 ERROR]:               java.util.zip.Deflater.finalize(Unknown Source)
[08:13:04 ERROR]:               java.lang.System$2.invokeFinalize(Unknown Source)
[08:13:04 ERROR]:               java.lang.ref.Finalizer.runFinalizer(Unknown Source)
[08:13:04 ERROR]:               java.lang.ref.Finalizer.access$100(Unknown Source)
[08:13:04 ERROR]:               java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 ERROR]: Current Thread: Reference Handler
[08:13:04 ERROR]:       PID: 2 | Suspended: false | Native: false | State: WAITING
[08:13:04 ERROR]:       Stack:
[08:13:04 ERROR]:               java.lang.Object.wait(Native Method)
[08:13:04 ERROR]:               java.lang.Object.wait(Unknown Source)
[08:13:04 ERROR]:               java.lang.ref.Reference.tryHandlePending(Unknown Source)
[08:13:04 ERROR]:               java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
[08:13:04 ERROR]: ------------------------------
[08:13:04 INFO]: Startup script './start.sh' does not exist! Stopping server.
[08:13:15 INFO]: Stopping server
> [08:13:17 INFO]: Rangerwield left the game
[08:13:17 WARN]: Exception in thread "Thread-2" java.lang.IllegalStateException: WorldSaveEvent may only be triggered synchronously.
[08:13:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533)
[08:13:17 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:796)
[08:13:17 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.saveChunks(MinecraftServer.java:682)
[08:13:17 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:753)
[08:13:17 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:739)
[08:13:17 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.close(MinecraftServer.java:703)
[08:13:17 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.util.ServerShutdownThread.run(ServerShutdownThread.java:17)

C:\Users\Administrator\Desktop\Minecraft Paper Server>PAUSE
### Plugin list:
ServerRestorer
Treecapitator(modpack)

### Actions to reproduce (if known):
Unknown

### Paper build number:
got-Paper-166 (MC 1.14.4) (Implementing API versjon 1.14.4-R0.1-SNAPSHOT)

**Comment by thvozdovic** [comment]
Same here

**Comment by Spottedleaf** [comment]
without the incremental watchdog reports (should be earlier in the log), can't say what happened here

**Comment by electronicboy** [comment]
`[08:13:03 WARN]: Can't keep up! Is the server overloaded? Running 77722ms or 1554 ticks behind`
Your server is overloaded to the point that it can't even print out the needed warning logs, I would suggest seeking help via irc/discord if you're still having issues
