### ISSUE TITLE
Enjin Minecraft Plugin

### ISSUE THREAD

**Issue by slvlr** [PaperMC/Paper#2460]
### What behaviour is expected:
Plugin to load with no errors in console

### What behaviour is observed:
[05:37:09] [Server thread/INFO]: [EnjinMinecraftPlugin] Enabling EnjinMinecraftPlugin v3.5.7
[05:37:09] [Server thread/INFO]:    ___    _  _        _    ___    _  _ 
[05:37:09] [Server thread/INFO]:   | __|  | \| |    _ | |  |_ _|  | \| |
[05:37:09] [Server thread/INFO]:   | _|   | .` |   | || |   | |   | .` |
[05:37:09] [Server thread/INFO]:   |___|  |_|\_|    \__/   |___|  |_|\_|
[05:37:09] [Server thread/INFO]:   Enjin Minecraft Plugin 3.5.7
[05:37:09] [Server thread/INFO]: [com.enjin.bukkit.EnjinMinecraftPlugin] Initializing for the first time.
[05:37:10] [Server thread/ERROR]: [com.enjin.bukkit.EnjinMinecraftPlugin] Exception Caught: 
java.lang.NoSuchFieldException: knownCommands
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_191]
	at com.enjin.bukkit.command.CommandBank.getServerCommands(CommandBank.java:204) ~[?:?]
	at com.enjin.bukkit.command.CommandBank.unregisterCommand(CommandBank.java:189) ~[?:?]
	at com.enjin.bukkit.command.CommandBank.replaceCommandWithAlias(CommandBank.java:126) ~[?:?]
	at com.enjin.bukkit.EnjinMinecraftPlugin.initCommands(EnjinMinecraftPlugin.java:324) ~[?:?]
	at com.enjin.bukkit.EnjinMinecraftPlugin.init(EnjinMinecraftPlugin.java:203) ~[?:?]
	at com.enjin.bukkit.EnjinMinecraftPlugin.onEnable(EnjinMinecraftPlugin.java:132) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-167]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

### Steps/models to reproduce:
Loading server

### Plugin list:
Enjin Minecraft Plugin

### Paper build number:
1.14.4 build 163

### Anything else:
I have reported this issue to Enjin and they said it was due to me running paper. Could you add something to fix this error please ?

**Comment by MiniDigger** [comment]
this is not papers fault. this is a change introduced in spigot 1.13-pre7.

`CraftServer#commandMap` is no longer a `SimpleCommandMap` but a `CraftCommandMap`
Thus enjins `getDeclaredField("knownCommands")` doesn't work since it doesn't consider the field in the super class `SimpleCommandMap`.

Just install spigot for testing to confirm this and tell them to fix their shit. What they want to do is instead of just calling `getDeclaredField` once, they need to check if a superclass has that field.
(or instead, use the method `getKnownCommands` in `CraftCommandMap`)

**Comment by electronicboy** [comment]
is enjins plugin the only plugin on the server? Plugin itself starts up perfectly fine here
