### ISSUE TITLE
Timings crash

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2468]
### Link/paste of stack trace

[02:55:17 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! ( Tim                                                                                        ingIdentifier{id=Minecraft:Bukkit Scheduler}:co.aikar.timings.TimingHandler@12c)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:107) ~[p                                                                                        aper.jar:git-Paper-1608]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:                                                                                        841) ~[paper.jar:git-Paper-1608]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:                                                                                        423) ~[paper.jar:git-Paper-1608]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:                                                                                        774) ~[paper.jar:git-Paper-1608]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav                                                                                        a:666) ~[paper.jar:git-Paper-1608]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[02:55:17 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! ( Tim                                                                                        ingIdentifier{id=Minecraft:Full Server Tick}:co.aikar.timings.TimingHandler@12c)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:107) ~[p                                                                                        aper.jar:git-Paper-1608]
        at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandl                                                                                        er.java:29) ~[paper.jar:git-Paper-1608]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:                                                                                        835) ~[paper.jar:git-Paper-1608]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav                                                                                        a:666) ~[paper.jar:git-Paper-1608]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

### Plugin list:
EssentialsX and EssentialsXChat https://www.spigotmc.org/resources/essentialsx.9089/
Hibernate https://www.spigotmc.org/resources/hibernate.4441/
Multiverse-Core https://dev.bukkit.org/projects/multiverse-core
PixelPainter https://dev.bukkit.org/projects/pixelprinter
WorldEdit https://dev.bukkit.org/projects/worldedit
### Actions to reproduce (if known):
no

### Paper build number:
{"oldVersion":"git-Paper-1618 (MC: 1.12.2)","currentVersion":"git-Paper-1608 (MC: 1.12.2)"}

**Comment by zachbr** [comment]
MC 1.12.2 is no longer supported
