### ISSUE TITLE
Client error spam while connected to the server.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#2510]
Paper dev 176 (Spigot 1.14.4)
Waterfall dev 294 (BungeeCord 1.14.4)

What is the best way to diagnose the cause of client errors? While connecting to my server, the client seems to error quite often. This only happens while connected to the server, so I believe there may be some improper or broken data/packets being sent to the client from/by the server. 

I'm not sure if it's caused by armorstands/holograms, Citizen NPCs, tile data like player heads, particles, worldedit destruction, or even a custom BungeeCord tab list with placeholders. But surely it can't be good and impacts the client negatively with lag spikes? Especially when it only happens while connected to the server?

Client error.
```
[13:29:48] [Client thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at cti.d(SourceFile:199) ~[1.14.4.jar:?]
	at dkc.a(SourceFile:2004) ~[1.14.4.jar:?]
	at nb.a(SourceFile:122) ~[1.14.4.jar:?]
	at nb.a(SourceFile:16) ~[1.14.4.jar:?]
	at ke.a(SourceFile:21) ~[1.14.4.jar:?]
	at ke$$Lambda$1808/1119661176.run(Unknown Source) ~[?:?]
	at agq.h(SourceFile:144) [1.14.4.jar:?]
	at agu.h(SourceFile:23) [1.14.4.jar:?]
	at agq.q(SourceFile:118) [1.14.4.jar:?]
	at agq.bh(SourceFile:103) [1.14.4.jar:?]
	at cyc.e(SourceFile:915) [1.14.4.jar:?]
	at cyc.b(SourceFile:410) [1.14.4.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [1.14.4.jar:?]
```

Client logs.
https://paste.ubuntu.com/p/MnC95Bs2mW/

Client error while using Optifine.
```
[14:10:22] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at cti.d(SourceFile:199) ~[cti.class:?]
	at dkc.a(SourceFile:2004) ~[dkc.class:?]
	at nb.a(SourceFile:122) ~[nb.class:?]
	at nb.a(SourceFile:16) ~[nb.class:?]
	at ke.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[ke.class:?]
	at ke$$Lambda$1821/1189745618.run(Unknown Source) ~[?:?]
	at agq.h(ThreadTaskExecutor.java:170) [agq.class:?]
	at agu.h(SourceFile:23) [agu.class:?]
	at agq.q(ThreadTaskExecutor.java:135) [agq.class:?]
	at agq.bh(ThreadTaskExecutor.java:115) [agq.class:?]
	at cyc.e(SourceFile:915) [cyc.class:?]
	at cyc.b(SourceFile:410) [cyc.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
```

The client is on 1.14.4. It occurs with a vanilla unmodified client, as well as optifine installed. I do not have any protocol hacks or remappings to support older versions.

**Comment by MiniDigger** [comment]
class cti is net/minecraft/scoreboard/Scoreboard
dkc is net/minecraft/client/network/play/ClientPlayNetHandler

so I am assuming something is sending invalid scoreboard data. do you connect via bungee? might be worse to eliminate that middle man and try again.

for future references, 1.14.4 mcp mappings are here, just control f `cti net` and you find the class: https://raw.githubusercontent.com/MinecraftForge/MCPConfig/master/versions/1.14.4/joined.tsrg

**Comment by successed** [comment]
remove world>data>scoreboard.dat

**Comment by mibby** [comment]
Apologies for the late reply!

I do use and connect via BungeeCord (Waterfall). Deleting the scoreboard.dat didn't seem to fix the issue either. Is there any proper way to debug scoreboard sending to the client and finding out what is causing it? Quite a few plugins I use seem to touch scoreboards but I can't find any doing anything incorrectly.

**Comment by mibby** [comment]
After rigorous testing, I narrowed the issue down to the plugin TAB. I got in contact with the developer and the issue has been fixed. 

For posterity sake, the issue was related to an invalid action being sent to unregister team packets before registering teams to avoid BungeeCord kicking on team re-grouping/re-sending for player nametags.
