### ISSUE TITLE
TIMING_STACK_CORRUPTION

### ISSUE THREAD

**Issue by StealWonders** [PaperMC/Paper#2526]
### Link/paste of stack trace

`[10:59:53 WARN]: net.minecraft.server.v1_13_R2.ExceptionWorldConflict: Failed to check session lock for world located at ./Conwy, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
[10:59:53 WARN]: at net.minecraft.server.v1_13_R2.WorldNBTStorage.checkSession(WorldNBTStorage.java:136)
[10:59:53 WARN]: at net.minecraft.server.v1_13_R2.World.checkSession(World.java:2825)
[10:59:53 WARN]: at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:912)
[10:59:53 WARN]: at net.minecraft.server.v1_13_R2.WorldServer.save(WorldServer.java:876)
[10:59:53 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.save(CraftWorld.java:954)
[10:59:53 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:972)
[10:59:53 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[10:59:53 WARN]: at java.lang.Thread.run(Thread.java:748)
[10:59:53 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:Conwy - World Save - Level} did not stopTiming)
java.lang.Throwable: null
at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.13.2.jar:git-Paper-643]
at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.13.2.jar:git-Paper-643]
at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:32) ~[patched_1.13.2.jar:git-Paper-643]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:1005) ~[patched_1.13.2.jar:git-Paper-643]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-643]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[10:59:53 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:Conwy - World Save} did not stopTiming)
java.lang.Throwable: null
at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.13.2.jar:git-Paper-643]
at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.13.2.jar:git-Paper-643]
at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:32) ~[patched_1.13.2.jar:git-Paper-643]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:1005) ~[patched_1.13.2.jar:git-Paper-643]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-643]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] `

### Plugin list:
BuycraftX, CastleSiege, Citizens, LibsDisguises, OldCombatMechanics, ProtocolLib*, spark, ViaVersion*, Votifier*, WorldEdit

### Actions to reproduce (if known):
World download: https://www.dropbox.com/s/yuroxnf5xheuf1o/Conwy.zip?dl=0

### Paper build number:
git-Paper-643 (MC:1.13.2)

**Comment by Spottedleaf** [comment]
`[10:59:53 WARN]: net.minecraft.server.v1_13_R2.ExceptionWorldConflict: Failed to check session lock for world located at ./Conwy, aborting. Stop the server and delete the session.lock in this world to prevent further issues.`
Must have started the server twice if this check fails, another server is using the world
