### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Matzuake** [PaperMC/Paper#2553]
java.util.concurrent.CompletionException: net.minecraft.server.v1_14_R1.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:58)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123)
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: net.minecraft.server.v1_14_R1.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$19(PlayerChunkMap.java:678)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$b$21(PlayerChunkMap.java:663)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 11 more
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.generateChunkData(BukkitPlotGenerator.java:136)
	at org.bukkit.craftbukkit.v1_14_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:83)
	at net.minecraft.server.v1_14_R1.ChunkStatus.lambda$static$6(ChunkStatus.java:51)
	at net.minecraft.server.v1_14_R1.ChunkStatus$d.doWork(ChunkStatus.java:240)
	at net.minecraft.server.v1_14_R1.ChunkStatus.a(ChunkStatus.java:186)
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$19(PlayerChunkMap.java:665)
	... 14 more

**Comment by electronicboy** [comment]
```
Caused by: java.lang.IllegalStateException: zip file closed
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
at java.util.jar.JarFile.getEntry(JarFile.java:240)
at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.generateChunkData(BukkitPlotGenerator.java:136)
a
```
You missed out the template... Your issue is also down to a plugin likely not being enabled properly, check for earlier errors
