### ISSUE TITLE
TIMING_STACK_CORRUPTION with custom AI

### ISSUE THREAD

**Issue by KlenerTeufel96** [PaperMC/Paper#2560]
I make new Mobs with the plugin "MythicMobs". 
If i create a mob with a custom AI like a aggressive Sheep and this sheep touch me, it throws this error:

`[19:39:53 WARN]: Entity threw exception at farmwelt:148.6762502152396,69.0,-3241.507796115736
[19:39:53 WARN]: java.lang.NullPointerException
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.EntityInsentient.C(EntityInsentient.java:1282)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.PathfinderGoalMeleeAttack.a(SourceFile:139)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.PathfinderGoalMeleeAttack.e(SourceFile:131)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.e(SourceFile:55)
[19:39:53 WARN]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[19:39:53 WARN]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[19:39:53 WARN]: 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
[19:39:53 WARN]: 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[19:39:53 WARN]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[19:39:53 WARN]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[19:39:53 WARN]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[19:39:53 WARN]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[19:39:53 WARN]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:39:53 WARN]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:80)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:662)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2532)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:504)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:28)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.EntitySheep.movementTick(EntitySheep.java:86)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2321)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:665)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.World.a(World.java:936)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:437)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075)
[19:39:53 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919)
[19:39:53 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[19:39:53 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.minecraft.server.v1_14_R1.EntitySheep} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.4.jar:git-Paper-187]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.4.jar:git-Paper-187]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:451) ~[patched_1.14.4.jar:git-Paper-187]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-187]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-187]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-187]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-187]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

Here in Pastebin :
https://pastebin.com/zMGVjxDc

**Comment by electronicboy** [comment]
Sheep don't have attack attributes set, so that's going to throw an NPE when something makes them try to attack
