### ISSUE TITLE
Odd error

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2564]
Getting this error occasionally, can't track it down to anything.

```
[00:11:50] [File IO Thread/WARN]: java.io.IOException: Stream Closed
[00:11:50] [File IO Thread/WARN]: 	at java.base/java.io.RandomAccessFile.seek0(Native Method)
[00:11:50] [File IO Thread/WARN]: 	at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:591)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.RegionFile.a(RegionFile.java:272)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.RegionFile.a(RegionFile.java:209)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.RegionFile$ChunkBuffer.close(RegionFile.java:481)
[00:11:50] [File IO Thread/WARN]: 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.RegionFileCache.writeRegion(RegionFileCache.java:102)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.RegionFileCache.e(RegionFileCache.java:251)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkRegionLoader.b(ChunkRegionLoader.java:245)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkRegionLoader.processSaveQueueEntry(ChunkRegionLoader.java:223)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:194)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.FileIOThread.c(FileIOThread.java:35)
[00:11:50] [File IO Thread/WARN]: 	at net.minecraft.server.v1_12_R1.FileIOThread.run(FileIOThread.java:28)
[00:11:50] [File IO Thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by zachbr** [comment]
1.12.2 is no longer supported here.
