### ISSUE TITLE
Server constantly crashing

### ISSUE THREAD

**Issue by AnthonyLNguyen** [PaperMC/Paper#2586]
```
[01:03:20 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_14_R1.ReportedException: Exception ticking world
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1221) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-196]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.AttributeModifiable.getModifiers(SourceFile:62) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.PacketPlayOutUpdateAttributes.<init>(SourceFile:26) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.EntityTrackerEntry.c(EntityTrackerEntry.java:364) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:199) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:1441) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:666) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:529) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:348) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-196]
... 4 more
[01:03:20 ERROR]: Cause of unexpected exception was
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.AttributeModifiable.getModifiers(SourceFile:62) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.PacketPlayOutUpdateAttributes.<init>(SourceFile:26) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.EntityTrackerEntry.c(EntityTrackerEntry.java:364) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:199) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:1441) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:666) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:529) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:348) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-196]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-196]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

### Plugin list:
Plugins (44): BankNote (2.1-SNAPSHOT), BentoBox (1.7.0), Citizens (2.0.25-SNAPSHOT (build 1745)), ClearLag (3.0.6), CommandCooldown (1.0.1), CommandItems (2.1.1), CommandNPC (1.9.1), CoreProtect (2.17.5), CrazyAuctions (1.2.10), CrazyCrates (1.9.10), CrazyEnchantments (1.8-Dev-Build-v6.1), CustomOreGen (1.3.17-SNAPSHOT), DailyRewards (1.3.7d), DeluxeMenus (1.12.0), DiscordBotAPI (3.0), DiscordChatWM (3.1.2), Essentials (2.17.1.0), EssentialsSpawn (2.17.1.0), ExperienceBottle (1.0), HolographicDisplays (2.4.0), IslandBorder (Build 2), JetsMinions (5.1.6), KeepItems (1.3.2), LeaderHeadsRevamped (4.0.5), LuckPerms (4.4.30), Matrix (2.4.4), mcMMO (2.1.107), MFHoppers (3.04-v1.14), MiniaturePets (2.3.1), MorphRedeem (1.1.1), Multiverse-Core (4.0.0-b766), PlaceholderAPI (2.10.3), Plan (4.9.4), PlugMan (2.1.6), ProtocolLib (4.5.0-SNAPSHOT), ShopGUIPlus (1.20.6), TokenManager (3.2.4), TradeSystem (1.1.1), Vault (1.7.2-b107), VentureChat (2.16.0), WarpSystem (3.1.13), WildStacker (3 Pre-1), WorldEdit (7.0.1;61bc012), WorldGuard (7.0.0;02b731f)

### Paper build number:
[01:33:01 INFO]: This server is running Paper version git-Paper-196 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[01:33:01 INFO]: Previous version: git-Paper-187 (MC: 1.14.4)
[01:33:01 INFO]: You are running the latest version

**Comment by electronicboy** [comment]
Some plugin on your server is modifying entity attributes from another thread
