### ISSUE TITLE
Drinking suspicious stew throws an error

### ISSUE THREAD

**Issue by Aaron2550** [PaperMC/Paper#2609]
### What behaviour is expected:
Drink suspicious stew, get no error

### What behaviour is observed:
Drink suspicious stew, get error

### Steps/models to reproduce:
1. start a 1.14.4 server
2. get and drink a  suspicious stew
3. see error

### Plugin list:
CMI, CoreProtect, CraftBook, Cubit, F3Name, Limitpillagers, Luckperms, Matrix, McMMO, React, Vault, Worldedit, WorldGuard, PlaceholderAPI and ProtocolLib

### Paper build number:
git-Paper-199

### Anything else:
Nothing

**Comment by Aaron2550** [comment]
```

>.... [19:04:08 WARN]: java.io.NotSerializableException: org.bukkit.potion.PotionEffect
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [19:04:08 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
>.... [19:04:08 WARN]: at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
>.... [19:04:08 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [19:04:08 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [19:04:08 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [19:04:08 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
>.... [19:04:08 WARN]: at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
>.... [19:04:08 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [19:04:08 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [19:04:08 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [19:04:08 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [19:04:08 WARN]: at net.coreprotect.Functions.convertByteData(Functions.java:372)
>.... [19:04:08 WARN]: at net.coreprotect.database.Database.insertContainer(Database.java:281)
>.... [19:04:08 WARN]: at net.coreprotect.database.Logger.container_logger(Logger.java:195)
>.... [19:04:08 WARN]: at net.coreprotect.database.Logger.log_container(Logger.java:360)
>.... [19:04:08 WARN]: at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:324)
>.... [19:04:08 WARN]: at net.coreprotect.consumer.Process.processConsumer(Process.java:153)
>.... [19:04:08 WARN]: at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
>.... [19:04:08 WARN]: at java.lang.Thread.run(Thread.java:748)

```

**Comment by Remski01** [comment]
Been enable to see the error would be usefull.

**Comment by Aaron2550** [comment]
im dumb, i just read its from coreprotect. sorry guys ^^'
