### ISSUE TITLE
"Could not paste timings" when generating /timings report

### ISSUE THREAD

**Issue by Kenajcrap** [PaperMC/Paper#2612]
### What behaviour is expected:
after typing "/timings report". a link to timings.aikar.co with the timings report

### What behaviour is observed:
```[15:48:24 INFO]: Preparing Timings Report...
[15:48:45 INFO]: Error uploading timings, check your logs for more information
[15:48:45 ERROR]: Could not paste timings
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_221]
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_221]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_221]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_221]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_221]
        at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_221]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_221]
        at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_221]
        at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_221]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:1.8.0_221]
        at co.aikar.timings.TimingsExport.run(TimingsExport.java:296) ~[patched_1.14.4.jar:git-Paper-209]
```

### Steps/models to reproduce:
not sure, maybe use a vpn to connect to aikar.co with a Brazillian IP?

### Plugin list:
none, fresh server

### Paper build number:
209

### Anything else:
I seem to not be able to connect to aikar.co at all, his blog posts, and stuff like that.
My connection with the internet is ok
I've tried disabling PiHole and renewing my WAN Lease on the modem to get a new IP from my ISP but no luck, still times out
I am able to reach the side through my mobile connection

**Comment by kickash32** [comment]
Many Brazilian IPs are banned due DDoS attacks.

**Comment by MiniDigger** [comment]
this is not really an issue with paper but with aikars services, so I guess its best to contact @aikar directly, maybe he can see how you got blocked. 
Aikar#0001 on discord.

**Comment by Kenajcrap** [comment]
Yeah, I was half expecting something like this to be the case but was hopeful it was something simpler, I will get in touch with Aikar to see what can be done. Thanks!
Honestly, how can someone be so dense as to DDOS his site? Dude has useful blog posts and free services and that's it...
