### ISSUE TITLE
I have a little ERROR [Help me !]

### ISSUE THREAD

**Issue by zR3bo0t** [PaperMC/Paper#264]
```
        at org.bukkit.craftbukkit.v1_8_R3.block.CraftSign.update(CraftSign.java:56) ~[SurvivalGames.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlockState.update(CraftBlockState.java:148) ~[SurvivalGames.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlockState.update(CraftBlockState.java:144) ~[SurvivalGames.jar:git-PaperSpigot-"8b18730"]
        at me.wazup.survivalgames.Arena.updateSignPlayers(Arena.java:790) ~[?:?]
        at me.wazup.survivalgames.main$8.run(main.java:1705) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[SurvivalGames.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [SurvivalGames.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [SurvivalGames.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [SurvivalGames.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [SurvivalGames.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [SurvivalGames.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by kashike** [comment]
Please use the issue template.

**Comment by aikar** [comment]
This looks like a bug with your Survival Games plugin.

Please ask that plugins author for help fixing the issue.

**Comment by zR3bo0t** [comment]
SurvivalGames is the name of spigot :)

**Comment by liach** [comment]
plugins?

**Comment by kashike** [comment]
@zR3bo0t:

```
        at me.wazup.survivalgames.Arena.updateSignPlayers(Arena.java:790) ~[?:?]
        at me.wazup.survivalgames.main$8.run(main.java:1705) ~[?:?]
```

**Comment by liach** [comment]
@kashike 
Well @zR3bo0t should not report the issue here, as it seems to be from a custom server pack.
There are also

```
[?:?]
```

on the stack trace of the plugin, which make it hard to find the buggy jar.
