### ISSUE TITLE
LeashHitch Spawning

### ISSUE THREAD

**Issue by MisterErwin** [PaperMC/Paper#2663]
### Link/paste of stack trace
>Patching vanilla jar...
System Info: Java 11 (OpenJDK 64-Bit Server VM 11.0.2+9) Host:  Linux 4.9.0-9-amd64 (amd64)
Loading libraries, please wait...
[17:12:20 INFO]: Starting minecraft server version 1.14.4
[17:12:20 INFO]: Loading properties
[17:12:21 INFO]: This server is running Paper version git-Paper-"527073aa" (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
> [ ... snip ...]
>java.lang.IllegalStateException: Unable to get CCW facing of down
        at net.minecraft.server.v1_14_R1.EnumDirection.f(SourceFile:253) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.EntityHanging.calculateBoundingBox(EntityHanging.java:65) ~[patched_1.14.4.jar:git-Paper-223]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.createEntity(CraftWorld.java:1795) ~[patched_1.14.4.jar:git-Paper-223]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawn(CraftWorld.java:1878) ~[patched_1.14.4.jar:git-Paper-223]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawn(CraftWorld.java:1465) ~[patched_1.14.4.jar:git-Paper-223]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnEntity(CraftWorld.java:751) ~[patched_1.14.4.jar:git-Paper-223]
        at com.abc.spawnLeashHitch(abc.java:240) ~[?:?]
        at com.CustomBlockListener.onClickCustomBlock(CustomBlockListener.java:79) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor139.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-223]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-223]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-223]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-223]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:440) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-223]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-223]
        at java.lang.Thread.run(Thread.java:834) [?:?]

(Pardon the snipping and removal of class names)

### Plugin list:
does not matter

### Actions to reproduce (if known):
By simply spawning a leash hitch
```java
world.spawnEntity(loc, EntityType.LEASH_HITCH);
```

### Paper build number:
This server is running Paper version git-Paper-"527073aa" (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Cause
The culprit seems to be that a fix for [SPIGOT-4674](https://hub.spigotmc.org/jira/browse/SPIGOT-4674) added the BlockFaces UP and DOWN for all hanging entity types, while it only would make sense for item frames.

The commit introducing the issue seems to be [d65a2576e40e58c8e446b330febe6799d13a604f](https://hub.spigotmc.org/stash/users/aquazus/repos/craftbukkit/commits/d65a2576e40e58c8e446b330febe6799d13a604f)

My suggestion for a fix would be https://github.com/MisterErwin/Paper/commit/171265a2d68d558cf9c3342b8e3acd62f5f44d77

**Comment by MisterErwin** [comment]
Closing as #2664 was merged

Thanks!
