### ISSUE TITLE
Server Crash - EntityTrackerEntry updatePassengers

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#268]
Paper 720

@aikar Caused by https://github.com/PaperMC/Paper/commit/53abbfdc4c1832973ed17145060436ad1ab6f5fe ?

```
Time: 5/5/16 11:12 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at net.minecraft.server.v1_9_R1.EntityTrackerEntry.lambda$updatePassengers$0(EntityTrackerEntry.java:487)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at net.minecraft.server.v1_9_R1.EntityTrackerEntry.updatePassengers(EntityTrackerEntry.java:487)
    at net.minecraft.server.v1_9_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:450)
    at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:199)
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:901)
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723)
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by Gabscap** [comment]
+1 Same happened to me.
