### ISSUE TITLE
Null Item Crash

### ISSUE THREAD

**Issue by KSashaDF** [PaperMC/Paper#2718]
### Paste of stack trace

    `java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_14_R1.ItemStack.checkEmpty(ItemStack.java:109) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.ItemStack.setCount(ItemStack.java:897) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.ItemStack.add(ItemStack.java:901) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.ItemStack.subtract(ItemStack.java:905) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:64) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:24) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:185) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:502) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-233]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

_I do not believe a log will help in any way, this is a pretty straightforward issue._

### Plugin list:
_Irrelevant_

### Actions to reproduce:
When the player right clicks a block item, set the player's held item to `null` through the Inventory#setItem(int, ItemStack) method. Note that the ItemStack parameter is marked as nullable.

When the server attempts to place the block, a fatal error is thrown. This will not occur if the right click event is cancelled, but will still occur if the place block event is cancelled. I have not tested for other places in which this issue will occur (such as clicking an inventory slot).

It may also be helpful to mention that I have noticed this error being thrown on 1.13 versions of paper, but I have never seen this result in a fatal error.

### Paper build number:
233

**Comment by Draycia** [comment]
Set their hand to AIR instead of null

EDIT:
#2687 
Seems this happens when you set to air also

**Comment by bartyrealms** [comment]
Are you trying to empty their hand? Why are you setting it to null?

**Comment by Phoenix616** [comment]
Well the API specifies that the item is Nullable in Inventory#setItem(int, ItemStack) so yeah, that is a bug.

**Comment by 0-x-2-2** [comment]
yeah, I don't think air has been null since 1.9?
