### ISSUE TITLE
Chunk doesn't save when giving a profession to a villager

### ISSUE THREAD

**Issue by misdocumeno** [PaperMC/Paper#2725]
This happens when I try to give a profession to a villager. I put the block (composter for example), and the villager keeps with no profession, and that comes out on the console

```    [14:59:09 FATAL]: Error executing task on Server
java.lang.IllegalStateException: POI data mismatch: already registered at BlockPosition{x=1545, y=161, z=-413}
        at net.minecraft.server.v1_14_R1.VillagePlaceSection.a(SourceFile:81) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.VillagePlaceSection.a(SourceFile:65) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.VillagePlace.a(VillagePlace.java:36) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.WorldServer.lambda$null$14(WorldServer.java:1838) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-235]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

But sometimes the profession is changed, and when the chunk is unloaded, this comes out on the console, and the chunk is not saved, it goes back to an earlier version. People is using this bug to duplicate things ([example video](https://cdn.discordapp.com/attachments/289587909051416579/653873389689372673/villager_bug.mp4))

```
[15:14:49 ERROR]: Failed to serialize unloading chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkSaveTask, for world 'world', (96,-26), hashcode:1292807779, priority: -1, falling back to a synchronous execution
net.minecraft.server.v1_14_R1.ReportedException: Saving entity NBT
        at net.minecraft.server.v1_14_R1.Entity.save(Entity.java:1660) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.Entity.c(Entity.java:1535) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.Entity.d(Entity.java:1543) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:463) ~[patched_1.14.4.jar:git-Paper-235]
        at com.destroystokyo.paper.io.chunk.ChunkSaveTask.run(ChunkSaveTask.java:39) ~[patched_1.14.4.jar:git-Paper-235]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.14.4.jar:git-Paper-235]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.14.4.jar:git-Paper-235]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_14_R1.DimensionManager.a(DimensionManager.java:85) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.GlobalPos.a(SourceFile:62) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.BehaviorController.a(SourceFile:238) ~[patched_1.14.4.jar:git-Paper-235]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_231]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.server.v1_14_R1.BehaviorController.a(SourceFile:240) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityLiving.b(EntityLiving.java:545) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityInsentient.b(EntityInsentient.java:307) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityAgeable.b(EntityAgeable.java:130) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityVillagerAbstract.b(EntityVillagerAbstract.java:130) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityVillager.b(EntityVillager.java:410) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.Entity.save(Entity.java:1618) ~[patched_1.14.4.jar:git-Paper-235]
        ... 6 more
[15:14:49 FATAL]: Failed to synchronously serialize unloading chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkSaveTask, for world 'world', (96,-26), hashcode:1292807779, priority: -1! Chunk data will be lost
net.minecraft.server.v1_14_R1.ReportedException: Saving entity NBT
        at net.minecraft.server.v1_14_R1.Entity.save(Entity.java:1660) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.Entity.c(Entity.java:1535) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.Entity.d(Entity.java:1543) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:463) ~[patched_1.14.4.jar:git-Paper-235]
        at com.destroystokyo.paper.io.chunk.ChunkSaveTask.lambda$run$0(ChunkSaveTask.java:51) ~[patched_1.14.4.jar:git-Paper-235]
        at com.destroystokyo.paper.io.chunk.ChunkTaskManager.pollChunkWaitQueue(ChunkTaskManager.java:186) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:806) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:426) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1038) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-235]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_14_R1.DimensionManager.a(DimensionManager.java:85) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.GlobalPos.a(SourceFile:62) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.BehaviorController.a(SourceFile:238) ~[patched_1.14.4.jar:git-Paper-235]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_231]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.server.v1_14_R1.BehaviorController.a(SourceFile:240) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityLiving.b(EntityLiving.java:545) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityInsentient.b(EntityInsentient.java:307) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityAgeable.b(EntityAgeable.java:130) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityVillagerAbstract.b(EntityVillagerAbstract.java:130) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.EntityVillager.b(EntityVillager.java:410) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.Entity.save(Entity.java:1618) ~[patched_1.14.4.jar:git-Paper-235]
```

### Paper build number:
git-Paper-235 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Plugin list:
```ActionHealth.jar
advancedregionmarket.jar
AdvancedTimber_1.5.3.jar
AsyncWorldEdit-3.6.11.jar
AuthMe-5.6.0-SNAPSHOT.jar
AuthMeTitle.jar
AutoRestart-v3.jar
BetterRTP.jar
BKCommonLib-1.14.4-v1.jar
ChatControl-Free-5.8.7.jar
ColoredSigns-2.2.jar
Command Regions REBORN (v1.2.1).jar
ConsoleScheduler.jar
DeathCoordinates.jar
DeluxeMenus-1.12.0.jar
EssentialsX-2.17.1.0.jar
EssentialsXChat-2.17.1.0.jar
EssentialsXGeoIP-2.17.1.0.jar
EssentialsXProtect-2.17.1.0.jar
EssentialsXSpawn-2.17.1.0.jar
GravityTubes.jar
GroupManager.jar
HolographicDisplays.jar
IllegalStack.jar
images-1.0.6-SNAPSHOT.jar
Jobs4.14.3.jar
JupiterCore.jar
LightCleaner-1.14.4-v1.jar
MapManager_v1.7.3-SNAPSHOT.jar
Multiverse-Core-4.1.0.jar
Multiverse-Inventories-3.0.0.jar
MyCommand.jar
NetherPortal-0.2.1.jar
OpenInv.jar
PacketListenerAPI_v3.7.3-SNAPSHOT.jar
PlaceholderAPI-2.10.4.jar
PMS_Light.jar
ProtectionStones-2.1.3.jar
ProtocolLib.jar
QuickShop-Reremake.2.4.8.4.jar
SimpleScore-3.2.2.jar
SkinsRestorer.jar
SkQuery.jar
Skript.jar
Spigot-CommandSigns.jar
StockMarket.jar
SuperBlockCommands.jar
TabList.jar
Vault.jar
VoidGenerator-1.4.2.jar
Warps_2d.jar
WorldBorder.jar
worldedit-bukkit-7.0.1.jar
worldguard-bukkit-7.0.1-rc2-dist.jar
WorldGuardExtraFlags.jar
```

**Comment by electronicboy** [comment]
Unable to reproduce, works as intended here; Are you able to reproduce this without plugins?

**Comment by misdocumeno** [comment]
> Unable to reproduce, works as intended here; Are you able to reproduce this without plugins?

it saved the chunk fine without plugins, no bugs

**Comment by electronicboy** [comment]
You would need to work out replication steps, could be a plugin bug, could
be a server issue

**Comment by Chew** [comment]
Author sadly never worked out replication steps. If you're able to provide some on a supported version, don't hesitate to open a new issue (and fill out the template). Thanks for the report!
