### ISSUE TITLE
Hoppers are broken in git-Paper-1 (MC: 1.15)

### ISSUE THREAD

**Issue by 811Alex** [PaperMC/Paper#2735]
### What behaviour is expected:
Hoppers should be moving items around.

### What behaviour is observed:
Hoppers half the time don't move items, don't suck items and often eat items.
At the same time, an error like this pops up in the server console:
```
[20:34:54 WARN]: TileEntity threw exception at world:-138,102,1487
[20:34:54 WARN]: java.lang.AssertionError: TRAP
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.ItemStack.checkEmpty(ItemStack.java:114)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.ItemStack.setCount(ItemStack.java:912)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.TileEntityHopper.hopperPush(TileEntityHopper.java:202)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.TileEntityHopper.j(TileEntityHopper.java:330)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.TileEntityHopper.a(TileEntityHopper.java:135)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.TileEntityHopper.tick(TileEntityHopper.java:117)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.World.tickBlockEntities(World.java:786)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:499)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1239)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106)
[20:34:54 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933)
[20:34:54 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

### Steps/models to reproduce:
Place some items in a hopper that leads to a chest, or in an inventory above the hopper.

### Plugin list:
- CS-CoreLib
- Dynmap-3.0-beta-5-spigot
- EntityDetection-1.1.3
- FastLeafDecay-1.0
- InventoryRollback-1.3.6
- LuckPerms-Bukkit-4.4.1
- multiworld-5.2.8
- NoMobGriefing-0.2.3
- PingPlayer-1.3.2
- RankPrefix+ v1.7.2
- SafeCrystals-1.0.3
- Sickle-1.8.3
- skDragon2dev-0.15
- Skript-2.4
- Vault-1.7.2-b107
- worldedit-bukkit-7.0.1
- worldguard-bukkit-7.0.1

### Paper version:
git-Paper-1 (MC: 1.15)

### Anything else:
I have tried the same with Spigot and it seems to work properly.

**Comment by ensorcell** [comment]
I have this same problem. One item gets transferred then the rest disappear

Running no plugins
