### ISSUE TITLE
Empty Item Crash (AssertionError)

### ISSUE THREAD

**Issue by KSashaDF** [PaperMC/Paper#2762]
### Paste of stack trace

    java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_14_R1.ItemStack.checkEmpty(ItemStack.java:109)
        at net.minecraft.server.v1_14_R1.ItemStack.setCount(ItemStack.java:897)
        at net.minecraft.server.v1_14_R1.ItemStack.add(ItemStack.java:901)
        at net.minecraft.server.v1_14_R1.ItemStack.subtract(ItemStack.java:905)
        at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:64)
        at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:24)
        at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:185)
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:502)
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361)
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006)
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929)
        at java.lang.Thread.run(Thread.java:748)

This issue was reported and closed [here](https://github.com/PaperMC/Paper/issues/2718), however, the fix does not seem to work.

### Actions to reproduce:

Set the player's held item to `null` or air when the player attempts to place a block on the right click event. Cancelling the event will prevent the crash.

### Paper build number:
236

**Comment by kickash32** [comment]
This is not something wrong with the method, but rather how setting the item to null interacts while the player is attempting to place a block. Can you tell me exactly what event you used?

**Comment by KSashaDF** [comment]
An extra check needs to be added for whether the used item is empty, and if so, immediately return as if the event was cancelled. The error that is currently thrown is a fatal error.

That is exactly what [this](https://github.com/PaperMC/Paper/commit/86daffa21c13f46361313120dd49f4bb9118b8d9#diff-40e0782b4258bbbf2e3abbedf662ec2a) commit seems to be doing, but for one reason or another it does not work.

EDIT: Whoops, I misread your comment. It's the right click event (player interact event).

**Comment by kickash32** [comment]
Can you test in 1.15, the patch might have been ported badly to 1.14

**Comment by KSashaDF** [comment]
Yes, it seems that this is a 1.14 only issue.

**Comment by Brokkonaut** [comment]
Got the same exception in 1.15.1: https://pastebin.com/raw/xjVhNYcW
