### ISSUE TITLE
Weird Chunk loading Crash

### ISSUE THREAD

**Issue by Joly0** [PaperMC/Paper#2782]
### Link/paste of stack trace

`[20:53:07] [Paper Async Chunk Task Thread #0/ERROR]: Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'FarmWorld1', (-9,-9), hashcode:1011980928, priority: -1
java.lang.ArrayIndexOutOfBoundsException: 256
	at net.minecraft.server.v1_14_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:65) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:117) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.14.4.jar:git-Paper-237]
[20:53:07] [Paper Async Chunk Task Thread #0/ERROR]: Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'FarmWorld1', (-10,-10), hashcode:1643021510, priority: -1
java.lang.ArrayIndexOutOfBoundsException: 256
	at net.minecraft.server.v1_14_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:65) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:117) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:49) ~[patched_1.14.4.jar:git-Paper-237]
[20:53:07] [Paper Async Chunk Task Thread #0/ERROR]: Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'FarmWorld1', (-9,-10), hashcode:1059046398, priority: -1
java.lang.ArrayIndexOutOfBoundsException: 256
	at net.minecraft.server.v1_14_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:65) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:117) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:49) ~[patched_1.14.4.jar:git-Paper-237]
[20:53:07] [Paper Async Chunk Task Thread #0/ERROR]: Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'FarmWorld1', (-8,-10), hashcode:286389581, priority: -1
java.lang.ArrayIndexOutOfBoundsException: 256
	at net.minecraft.server.v1_14_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:65) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:117) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:49) ~[patched_1.14.4.jar:git-Paper-237]
[20:53:07] [Paper Async Chunk Task Thread #0/ERROR]: Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'FarmWorld1', (-10,-9), hashcode:564459637, priority: -1
`

### Plugin list:
___A list of your plugins___
AnvilBreaknt 0.0.1
BeterBed
ChopTree
DeadChest 2.1
Farmland
FarmWorld
ItemStackReloaded
PickupArrow
PluginConstructorAPI
ServerRestorer
Sickle
SinglePlayerSleep
SpawnerSilk
StackableItems
VillagerOptimiser
XPKeeper

### Actions to reproduce (if known):
Switched from Spigot to Paper and as soon as i try to start the server, it starts, then the above message drop a while for every world that exists and then restarts and keeps doing that forever.

### Paper build number:
paper-237

**Comment by electronicboy** [comment]
Don't really see how that could happen unless something was screwing with the chunks data as it was loading, can you replicate this with a minimal set of plugins or something?

**Comment by Joly0** [comment]
Well, now i cant replicate anything. After a loong time of loading, the Server started but the whole world was just gone. It was like a fresh new World.

**Comment by hkedjnane** [comment]
I think I might know what the problem is.This error happens can happen when using a map generated with a newer version on an older one. In this case, I'm guessing you switched from Spigot 1.15 to Paper 1.14.4. Do you think this might explain what's happening to you? If it is, you might want to download Paper 1.15 instead. That should fix it.

**Comment by MRaK26** [comment]
Is it possible to solve this problem without moving to 1.15, and it only with the Nether?

**Comment by MRaK26** [comment]
> I think I might know what the problem is.This error happens can happen when using a map generated with a newer version on an older one. In this case, I'm guessing you switched from Spigot 1.15 to Paper 1.14.4. Do you think this might explain what's happening to you? If it is, you might want to download Paper 1.15 instead. That should fix it.

Is it possible to solve this problem without moving to 1.15, and it only with the Nether?

**Comment by ghost** [comment]
> I think I might know what the problem is.This error happens can happen when using a map generated with a newer version on an older one. In this case, I'm guessing you switched from Spigot 1.15 to Paper 1.14.4. Do you think this might explain what's happening to you? If it is, you might want to download Paper 1.15 instead. That should fix it.

Is it possible to solve this problem without moving to 1.15, and it only with the Nether?

**Comment by electronicboy** [comment]
Closing due to the fact that this is no longer an issue for OP, nor do we have much more information on its cause

if your world was loaded by 1.15, your world is only supported by 1.15+, world downgrades are totally unsupported, best you can do is to regenerate the affected world

**Comment by iOshawott** [comment]
I've got that kind of issue on fresh 1.15.2 world [mostly above chunks with a lot of oceans]

https://pastebin.com/4fRfjneB

//deleting poi of regionfile fixed issue
