### ISSUE TITLE
TimingStack ERROR

### ISSUE THREAD

**Issue by p82183645** [PaperMC/Paper#2795]
`[17:07:48 WARN]: Entity threw exception at world:-125.32028626554282,34.0,-18.282981859652367
[17:07:48 WARN]: java.util.ConcurrentModificationException
[17:07:48 WARN]:        at java.util.HashMap$HashIterator.nextNode(Unknown Source)
[17:07:48 WARN]:        at java.util.HashMap$KeyIterator.next(Unknown Source)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.NBTTagCompound.clone(NBTTagCompound.java:382)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.ItemStack.cloneItemStack(ItemStack.java:492)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.ItemStack.cloneItemStack(ItemStack.java:486)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.Container.c(Container.java:137)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.EntityPlayer.tick(EntityPlayer.java:371)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:702)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.World.a(World.java:936)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:472)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
[17:07:48 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[17:07:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:07:48 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.minecraft.server.v1_14_R1.EntityPlayer} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.4.jar:git-Paper-233]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:486) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-233]        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-233]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

![image](https://user-images.githubusercontent.com/5382252/71440744-57ed2580-2739-11ea-9621-1c34610c225f.png)

**Comment by electronicboy** [comment]
You're missing like, the template....
But, you have something that's screwing with inventories async
