### ISSUE TITLE
TIMING_STACK_CORRUPTION

### ISSUE THREAD

**Issue by trickman325** [PaperMC/Paper#2826]
### Paper build number:
Paper 33 1.15.1

###
this is the console error.

[18:14:05 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.minecraft.server.v1_15_R1.EntityPlayer} did not stopTiming)

java.lang.Throwable: null

**Comment by RossKor** [comment]
Ditto, Running paper-33 here

[21:07:41 INFO]: Villager EntityVillager['Farmer'/1555, uuid='786ef0f9-b2ff-4e53-b6d8-84c87589b341', l='world', ,,, cx=-135, cz=643, tl=702764, v=true, d=false] died, message: 'Farmer went up in flames'
[21:07:52 INFO]: Villager EntityVillager['Farmer'/1554, uuid='43e128d4-fd56-4dac-94ef-8d13b463a0f3', l='world', ,,, cx=-136, cz=643, tl=446623, v=true, d=false] died, message: 'Farmer burned to death'
[21:08:00 INFO]: Villager EntityVillager['Farmer'/1558, uuid='4988f0ea-6e4c-45a8-98a9-aff49a5e9e68', l='world', ,,, cx=-135, cz=643, tl=714167, v=true, d=false] died, message: 'Farmer was blown up by ..'
[21:08:00 WARN]: Entity threw exception at world:-2159.3918137835826,71.5625,10287.707653833748
[21:08:00 WARN]: java.lang.IllegalStateException: Unhandled damage of EntityVillager['Farmer'/1556, uuid='29290a49-e4f4-461d-b924-45eb53b83194', l='world', ,,, cx=-135, cz=643, tl=485821, v=true, d=false] by EntityTNTPrimed['Primed TNT'/7134, uuid='e5f04391-4549-4816-8f48-661e29e117e4', l='world', ,,, cx=-135, cz=642, tl=80, v=true, d=false] from inFire
[21:08:00 WARN]: at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:932)
[21:08:00 WARN]: at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:836)
[21:08:00 WARN]: at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1025)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1689)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1047)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.Entity.burn(Entity.java:1086)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:691)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.Entity.updateSize(Entity.java:2844)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.Entity.a(Entity.java:2821)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.EntityLiving.a(EntityLiving.java:2914)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.EntityAgeable.a(EntityAgeable.java:166)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.DataWatcher.set(DataWatcher.java:132)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.Entity.setPose(Entity.java:326)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.EntityLiving.entityWakeup(EntityLiving.java:3217)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.EntityVillager.entityWakeup(EntityVillager.java:970)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:996)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.Explosion.a(Explosion.java:187)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.World.createExplosion(World.java:1023)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.WorldServer.createExplosion(WorldServer.java:1520)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.World.createExplosion(World.java:1013)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.EntityTNTPrimed.explode(EntityTNTPrimed.java:113)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.EntityTNTPrimed.tick(EntityTNTPrimed.java:72)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:722)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.World.a(World.java:878)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:488)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1239)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106)
[21:08:00 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933)
[21:08:00 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:08:00 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.minecraft.server.v1_15_R1.EntityTNTPrimed} did not stopTiming)
java.lang.Throwable: null
at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.15.1.jar:git-Paper-33]
at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:502) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1239) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-33]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by electronicboy** [comment]
OP, without the full set of logs, that basically means nothing; 9/10 times, something else broke and that warning is basically irrelevant

@RossKor
Your issue is unrelated to this:

```
[21:08:00 WARN]: Entity threw exception at world:-2159.3918137835826,71.5625,10287.707653833748
[21:08:00 WARN]: java.lang.IllegalStateException: Unhandled damage of EntityVillager['Farmer'/1556, uuid='29290a49-e4f4-461d-b924-45eb53b83194', l='world', ,,, cx=-135, cz=643, tl=485821, v=true, d=false] by EntityTNTPrimed['Primed TNT'/7134, uuid='e5f04391-4549-4816-8f48-661e29e117e4', l='world', ,,, cx=-135, cz=642, tl=80, v=true, d=false] from inFire
```

**Comment by zachbr** [comment]
Closing as incomplete.
