### ISSUE TITLE
java.lang.IllegalStateException after updating to 1.15.1

### ISSUE THREAD

**Issue by DerScherenmann** [PaperMC/Paper#2829]
### What behaviour is expected:
___What you expected to see___

Server receives message over Socket Server and proceeds to set text on a sign. BlockState is read from block and can be parsed later.

### What behaviour is observed:
___What you actually saw___

Tile is null but is at this exact location `CraftBlock{pos=BlockPosition{x=236, y=114, z=238},type=OAK_WALL_SIGN,data=Block{minecraft:oak_wall_sign}[facing=south,waterlogged=false],fluid=net.minecraft.server.v1_15_R1.FluidTypeEmpty@560348e6}` and proceeds to throw an error

`java.lang.RuntimeException: Failed to read BlockState at: world: lobby location: (236, 114, 238)
at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlockEntityState.<init (CraftBlockEntityState.java:48)
at org.bukkit.craftbukkit.v1_15_R1.block.CraftSign.<init>(CraftSign.java:19)
at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.getState0(CraftBlock.java:341)
at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.getState(CraftBlock.java:319)
at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.getState(CraftBlock.java:313)
at io.github.broesel233.socket.ClientHandler.run(ClientHandler.java:174)
at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=236, y=114, z=238},type=OAK_WALL_SIGN,data=Block{minecraft:oak_wall_sign}[facing=south,waterlogged=false],fluid=net.minecraft.server.v1_15_R1.FluidTypeEmpty@560348e6}
at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:29)
  ... 6 more`

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Call `BlockState block = Main.getInstance().getServer().getWorld("world").getBlockAt(coord_sign.get(0), coord_sign.get(1), coord_sign.get(2)).getState();` in a Thread (`Thread t = new Thread(new ClientHandler);`)

### Plugin list:
___A list of your plugins___
LagMonitor

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-34 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by DerScherenmann** [comment]
Apperently this method cannot be called in a Thread because bukkit is not Thread safe
