### ISSUE TITLE
FATAL Error executing task on Server

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#2850]
### What behaviour is expected:
___What you expected to see___
No write this fatal error.

### What behaviour is observed:
___What you actually saw___
Write this fatal error randomly.
```
[20:54:52] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.b(ChunkMapDistance.java:230) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1297) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:738) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1144) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1096) ~[patched_1.15.1.jar:git-Paper-41]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-41]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
I don't know. I find this error on console.

### Plugin list:
___A list of your plugins___
`Plugins (106): AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, ArmorStandEditor, AsyncWorldEdit, BuntetesLogolo, ChangeSkin, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CombatLogX, CommandHook, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, DyedBackpacks, EnderContainers, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, GriefPrevention, GriefPreventionFlags, HeadDatabase*, HideAndSeek, HolographicDisplays, HonapStaffja, HotbarPets, HungerGames, JukeBox, Kemkedes, Kezdes, LibsDisguises, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, Shopkeepers, SignEdit*, Sleepy*, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunPomaFix, StaffChat, StaffTime, Stats, Szilveszter, SzulinapiTuzijatek, TimeIsMoney*, TitleManager, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge`

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
[18:44:46 INFO]: This server is running Paper version git-Paper-41 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[18:44:46 INFO]: Checking version, please wait...
[18:44:46 INFO]: Previous version: git-Paper-35 (MC: 1.15.1)
Java 11.0.5

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by nahia95** [comment]
I'm also having this error. Some player's can't run commands after it and are completely invisible to other players

**Comment by electronicboy** [comment]
last I looked, this didn't seem all that viable or went down other varying forms of hell, We'd need some form of reproduction steps or way to reproduce/diagnose this, best advice I've got is "replicate without plugins"

**Comment by nahia95** [comment]
The best way I found of reproducing it was having a lot of players online (40 or more) and then switching dimensions. Sometimes it takes longer but after a couple of tries you get bugged and that error appears in the log. I've tried to reproduce it too lagging the server generating chunks but it didn't work, the best way I found to do it was having multiple players online

**Comment by Spottedleaf** [comment]
duplicate of https://github.com/PaperMC/Paper/issues/2803
