### ISSUE TITLE
Anti xray breaks spreadplayers command

### ISSUE THREAD

**Issue by brecht-vermeersch** [PaperMC/Paper#2889]
### Link/paste of stack trace

[13:16:03 FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.server.v1_15_R1.ChunkMapDistance.b(ChunkMapDistance.java:230) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1303) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:743) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:496) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.PacketPlayInTeleportAccept.a(SourceFile:30) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.PacketPlayInTeleportAccept.a(SourceFile:8) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:834) [?:?]

### Plugin list
Clans, ClansChatAddon, ClansKillAddon, LuckPerms

### Actions to reproduce (if known):
I used a command block with the spreadplayers command. If anti xray is on I get this error.

### Paper build number:
git-paper-65

**Comment by electronicboy** [comment]
Cannot replicate, can you reproduce this consistently? Have you tried without plugins?

**Comment by brecht-vermeersch** [comment]
Did some testing and found the conditions for this error to happen
- worldborder that instantly kills you
- you spawn on pressure plate that activates the command block
- command block teleports you outside the worldborder

The error only sometimes happens.

**Comment by Spottedleaf** [comment]
teleporting (out of world)/dying in move logic sounds like it could produce that

**Comment by Spottedleaf** [comment]
duplicate of https://github.com/PaperMC/Paper/issues/2803
