### ISSUE TITLE
1.14.4 - Executing command block

### ISSUE THREAD

**Issue by nullexcept1on** [PaperMC/Paper#2892]
### Paper build number:
git-Paper-238 (MC: 1.14.4)

### Plugin list:
* CoreProtect-2.17.5
* worldedit-bukkit-7.0.1

### Actions to reproduce:
**OS:** Debian GNU/Linux 9
Script for starting
```shell
java -Xms1G -Xmx2G -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -server -noverify -jar server.jar
```
Java -version
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```
server.properties
```
...
enable-command-block=true
...
```

### Stack trace
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/22/20 12:53 PM
Description: Executing command block

java.lang.NullPointerException: Executing command block
	at net.minecraft.server.v1_14_R1.TileEntityCommand$1.getWrapper(TileEntityCommand.java:39)
	at net.minecraft.server.v1_14_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:110)
	at net.minecraft.server.v1_14_R1.BlockCommand.a(BlockCommand.java:98)
	at net.minecraft.server.v1_14_R1.BlockCommand.tick(BlockCommand.java:84)
	at net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:206)
	at net.minecraft.server.v1_14_R1.WorldServer.b(WorldServer.java:676)
	at net.minecraft.server.v1_14_R1.TickListServer.b(TickListServer.java:90)
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:388)
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231)
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.v1_14_R1.TileEntityCommand$1.getWrapper(TileEntityCommand.java:39)

-- Command to be executed --
Details:
	Command: /title @a title ["",{"text":"привет","green":"red"}]
	Name: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_14_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:110)
	at net.minecraft.server.v1_14_R1.BlockCommand.a(BlockCommand.java:98)
	at net.minecraft.server.v1_14_R1.BlockCommand.tick(BlockCommand.java:84)
	at net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:206)
	at net.minecraft.server.v1_14_R1.WorldServer.b(WorldServer.java:676)

-- Block being ticked --
Details:
	Block location: World: (162,4,-301), Chunk: (at 2,0,3 in 10,-19; contains blocks 160,0,-304 to 175,255,-289), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.server.v1_14_R1.TickListServer.b(TickListServer.java:90)
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:388)

-- Affected level --
Details:
	All players: 3 total; [EntityPlayer['_P0ZA_'/45023, uuid='dce79eb3-4916-4ad1-bd3d-469986d5c2c6', l='world', x=135.41, y=9.53, z=-291.12, cx=8, cz=-19, tl=320376, v=true, d=false](_P0ZA_ at 135.40664041488537,9.52744780952103,-291.1231360950151), EntityPlayer['BioKitteny'/45078, uuid='36103878-0020-4edb-9307-899bc816915b', l='world', x=147.70, y=11.33, z=-288.20, cx=9, cz=-19, tl=3619, v=true, d=false](BioKitteny at 147.69949194547243,11.325297602666057,-288.1971141450878), EntityPlayer['MrNyt'/45079, uuid='7236a347-a95a-4c60-9bbe-d4c3a7b46e9a', l='world', x=161.16, y=4.00, z=-301.25, cx=10, cz=-19, tl=73313, v=true, d=false](MrNyt at 161.15656509180238,4.0,-301.2515447251521)]
	Chunk stats: ServerChunkCache: 2814
	Level dimension: minecraft:overworld
	Level name: world
	Level seed: 6227768415083384519
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: {flat_world_options:""}
	Level spawn location: World: (32,4,64), Chunk: (at 0,0,0 in 2,4; contains blocks 32,0,64 to 47,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 18476679 game time, 1000 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231)
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 4.19-ovh-xxxx-std-ipv6-64
	Java Version: 1.8.0_232, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 873296520 bytes (832 MB) / 2090860544 bytes (1994 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 14 total; -Xms1G -Xmx2G -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -Xverify:none
	CraftBukkit Information: 
   Running: Paper version git-Paper-238 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT) true
   Plugins: { CoreProtect v2.17.5 net.coreprotect.CoreProtect [Intelli], WorldEdit v7.0.1;61bc012 com.sk89q.worldedit.bukkit.WorldEditPlugin [],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { WAITING Paper Async Chunk Task Thread #0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Thread-17: [java.lang.Thread.sleep(Native Method), net.coreprotect.thread.CheckUpdate.run(CheckUpdate.java:106), java.lang.Thread.run(Thread.java:748)], WAITING Paper Async Chunk Task Thread #6: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Server-Worker-13662: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], WAITING Paper Async Chunk Task Thread #5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Paper Async Chunk Task Thread #4: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Paper Async Chunk Task Thread #1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Paper Async Task Handler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Log4j2-TF-1-AsyncLogger[AsyncContext@74a14482]-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078), com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:38), com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56), com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159), com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Abandoned connection cleanup thread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)], TIMED_WAITING Server-Worker-13661: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], TIMED_WAITING WorldEdit Session Manager: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING ObjectCleanerThread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Thread.java:748)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1610), org.bukkit.craftbukkit.v1_14_R1.CraftCrashReport.call(CraftCrashReport.java:33), net.minecraft.server.v1_14_R1.CrashReportSystemDetails.a(SourceFile:79), net.minecraft.server.v1_14_R1.CrashReport.h(CrashReport.java:71), net.minecraft.server.v1_14_R1.CrashReport.<init>(CrashReport.java:35), net.minecraft.server.v1_14_R1.CrashReport.a(CrashReport.java:269), net.minecraft.server.v1_14_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:112), net.minecraft.server.v1_14_R1.BlockCommand.a(BlockCommand.java:98), net.minecraft.server.v1_14_R1.BlockCommand.tick(BlockCommand.java:84), net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:206), net.minecraft.server.v1_14_R1.WorldServer.b(WorldServer.java:676), net.minecraft.server.v1_14_R1.WorldServer$$Lambda$2941/183693610.accept(Unknown Source), net.minecraft.server.v1_14_R1.TickListServer.b(TickListServer.java:90), net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:388), net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231), net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417), net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098), net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925), java.lang.Thread.run(Thread.java:748)], RUNNABLE Netty Epoll Server IO #3: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.util.TimerThread.mainLoop(Timer.java:526), java.util.TimerThread.run(Timer.java:505)], WAITING Craft Async Scheduler Management Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Timer-1: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Netty Epoll Server IO #1: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], WAITING Paper RegionFile IO Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING Thread-15: [java.lang.Thread.sleep(Native Method), net.coreprotect.thread.CacheCleanUp.run(CacheCleanUp.java:15), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_14_R1.DedicatedServer$1.run(DedicatedServer.java:71)], WAITING Server-Worker-13666: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], RUNNABLE Server console handler: [java.io.FileInputStream.read0(Native Method), java.io.FileInputStream.read(FileInputStream.java:207), org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73), org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141), net.minecraft.server.v1_14_R1.DedicatedServer$2.run(DedicatedServer.java:89)], WAITING Paper Async Chunk Task Thread #3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Paper Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:148)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.lang.ref.Reference.tryHandlePending(Reference.java:191), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)], WAITING Server-Worker-13660: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], WAITING Server-Worker-13667: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], RUNNABLE Netty Epoll Server IO #2: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], WAITING Server-Worker-13668: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], WAITING Paper Async Chunk Task Thread #2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Thread-16: [java.lang.Thread.sleep(Native Method), net.coreprotect.consumer.Consumer.run(Consumer.java:122), java.lang.Thread.run(Thread.java:748)],}
   
   Force Loaded Chunks: { world: {}, world_the_end: {},}
	Player Count: 3 / 20; [EntityPlayer['_P0ZA_'/45023, uuid='dce79eb3-4916-4ad1-bd3d-469986d5c2c6', l='world', x=135.41, y=9.53, z=-291.12, cx=8, cz=-19, tl=320376, v=true, d=false](_P0ZA_ at 135.40664041488537,9.52744780952103,-291.1231360950151), EntityPlayer['BioKitteny'/45078, uuid='36103878-0020-4edb-9307-899bc816915b', l='world', x=147.70, y=11.33, z=-288.20, cx=9, cz=-19, tl=3619, v=true, d=false](BioKitteny at 147.69949194547243,11.325297602666057,-288.1971141450878), EntityPlayer['MrNyt'/45079, uuid='7236a347-a95a-4c60-9bbe-d4c3a7b46e9a', l='world', x=161.16, y=4.00, z=-301.25, cx=10, cz=-19, tl=73313, v=true, d=false](MrNyt at 161.15656509180238,4.0,-301.2515447251521)]
	Data Packs: vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

### Part of the log:
```
12:53:14] [Server thread/INFO]: BioKitteny issued server command: //wanf
[12:53:16] [Server thread/INFO]: BioKitteny issued server command: /pl
[12:53:27] [Server thread/WARN]: Unable to parse CustomName from {auto:0b,powered:0b,LastExecution:6055L,SuccessCount:1,UpdateLastExecution:1b,conditionMet:1b,CustomName:"@",Command:'/title @a title ["",{"text":"привет","green":"red"}]',x:162,y:4,z:-301,id:"minecraft:command_block",LastOutput:'{"extra":[{"translate":"commands.title.success"}],"text":"[17:22:30] "}',TrackOutput:1b}: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
[12:53:32] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_14_R1.ReportedException: Executing command block
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1244) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-238]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_14_R1.TileEntityCommand$1.getWrapper(TileEntityCommand.java:39) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:110) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.BlockCommand.a(BlockCommand.java:98) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.BlockCommand.tick(BlockCommand.java:84) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:206) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.WorldServer.b(WorldServer.java:676) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.TickListServer.b(TickListServer.java:90) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:388) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-238]
	... 4 more
[12:53:32] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at net.minecraft.server.v1_14_R1.TileEntityCommand$1.getWrapper(TileEntityCommand.java:39) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:110) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.BlockCommand.a(BlockCommand.java:98) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.BlockCommand.tick(BlockCommand.java:84) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:206) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.WorldServer.b(WorldServer.java:676) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.TickListServer.b(TickListServer.java:90) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:388) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-238]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[12:53:32] [Server thread/ERROR]: This crash report has been saved to: /home/nullexcept1on/TestServer/./crash-reports/crash-2020-01-22_12.53.32-server.txt
[12:53:32] [Server thread/INFO]: Stopping server
[12:53:32] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.0.1;61bc012
[12:53:32] [Server thread/INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[12:53:32] [Server thread/INFO]: [CoreProtect] Disabling CoreProtect v2.17.5
[12:53:32] [Server thread/INFO]: [CoreProtect] Finishing up data logging. Please wait...
[12:53:33] [Server thread/INFO]: [CoreProtect] Success! Disabled CoreProtect v2.17.5
[12:53:33] [Server thread/INFO]: Saving players
[12:53:33] [Server thread/INFO]: _P0ZA_ lost connection: Server closed
[12:53:33] [Server thread/INFO]: _P0ZA_ left the game
[12:53:33] [Server thread/INFO]: BioKitteny lost connection: Server closed
[12:53:33] [Server thread/INFO]: BioKitteny left the game
[12:53:33] [Server thread/INFO]: MrNyt lost connection: Server closed
[12:53:33] [Server thread/INFO]: MrNyt left the game
[12:53:33] [Server thread/INFO]: Saving worlds
[12:53:33] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[12:53:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:53:33] [Server thread/INFO]: Saving chunks for level 'world_the_end'/minecraft:the_end
[12:53:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:53:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:53:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved

```

**Comment by electronicboy** [comment]
Your command block has an invalid custom name
