### ISSUE TITLE
Log Error

### ISSUE THREAD

**Issue by PatoTheBest** [PaperMC/Paper#2932]
### Link/paste of stack trace

Error logged after the first stacktrace
```
[23:45:42 WARN]: AsyncLogger error handling event seq=1858, value='Error occurred while enabling TheTowersRemastered v2.0-SNAPSHOT (Is it up to date?)':
[23:45:42 WARN]: org.apache.logging.log4j.core.appender.AppenderLoggingException: An exception occurred processing Appender ServerGuiConsole
[23:45:42 WARN]:        at org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:75)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.handleAppenderError(AppenderControl.java:165)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:158)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:337)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29)
[23:45:42 WARN]:        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
[23:45:42 WARN]:        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
[23:45:42 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:45:42 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:45:42 WARN]:        at java.lang.Thread.run(Unknown Source)
[23:45:42 WARN]: Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: zip file closed
[23:45:42 WARN]:        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
[23:45:42 WARN]:        at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
[23:45:42 WARN]:        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
[23:45:42 WARN]:        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
[23:45:42 WARN]:        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
[23:45:42 WARN]:        at com.google.inject.internal.util.StackTraceElements.forType(StackTraceElements.java:87)
[23:45:42 WARN]:        at com.google.inject.internal.Errors.formatSource(Errors.java:814)
[23:45:42 WARN]:        at com.google.inject.internal.Errors.formatSource(Errors.java:796)
[23:45:42 WARN]:        at com.google.inject.internal.Errors.format(Errors.java:590)
[23:45:42 WARN]:        at com.google.inject.CreationException.getMessage(CreationException.java:50)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:134)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEvent.getThrownProxy(RingBufferLogEvent.java:330)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:333)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:323)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:208)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:57)
[23:45:42 WARN]:        at com.mojang.util.QueueLogAppender.append(QueueLogAppender.java:39)
[23:45:42 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
[23:45:42 WARN]:        ... 16 more
[23:45:42 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[23:45:42 WARN]:        at java.util.zip.ZipFile.ensureOpen(Unknown Source)
[23:45:42 WARN]:        at java.util.zip.ZipFile.getEntry(Unknown Source)
[23:45:42 WARN]:        at java.util.jar.JarFile.getEntry(Unknown Source)
[23:45:42 WARN]:        at java.util.jar.JarFile.getJarEntry(Unknown Source)
[23:45:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133)
[23:45:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[23:45:42 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[23:45:42 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[23:45:42 WARN]:        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:46)
[23:45:42 WARN]:        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:43)
[23:45:42 WARN]:        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
[23:45:42 WARN]:        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
[23:45:42 WARN]:        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
[23:45:42 WARN]:        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
[23:45:42 WARN]:        ... 36 more
```
First stacktrace https://pastebin.com/wmccNZhP

### Plugin list:
ChatControl, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, HolographicDisplays, LuckPerms, ProtocolLib, TheTowersRemastered, Vault, ViaVersion

### Actions to reproduce (if known):
It's when enabling a plugin I'm working on but I have no idea what causes this error. Don't even know what information to provide that would be useful.

### Paper build number:

```
[23:49:18 INFO]: This server is running Paper version git-Paper-90 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[23:49:18 INFO]: Checking version, please wait...
[23:49:19 INFO]: Previous version: git-Paper-43 (MC: 1.15.1)
[23:49:19 INFO]: You are running the latest version
```

**Comment by PatoTheBest** [comment]
I loaded up an older test server with the same jar, this was the result:
https://pastebin.com/GscvRttU

The full stacktrace was shown without issue.

**Comment by PatoTheBest** [comment]
Update: tested with latest version of spigot
```
[00:12:32] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-c574e08-807a677 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[00:12:32] [Server thread/INFO]: Checking version, please wait...
[00:12:33] [Thread-92/INFO]: You are running the latest version
```

It does give out the correct stacktrace
```
[00:12:20] [Server thread/INFO]: [TheTowersRemastered] Enabling TheTowersRemastered v2.0-SNAPSHOT
[00:12:20] [Server thread/INFO]:  _____ _        _____
[00:12:20] [Server thread/INFO]: |_   _| |      |_   _|
[00:12:20] [Server thread/INFO]:   | | | |__   ___| | _____      _____ _ __ ___
[00:12:20] [Server thread/INFO]:   | | | '_ \ / _ \ |/ _ \ \ /\ / / _ \ '__/ __|
[00:12:20] [Server thread/INFO]:   | | | | | |  __/ | (_) \ V  V /  __/ |  \__ \
[00:12:20] [Server thread/INFO]:   \_/ |_| |_|\___\_/\___/ \_/\_/ \___|_|  |___/
[00:12:20] [Server thread/INFO]:
[00:12:20] [Server thread/INFO]:
[00:12:20] [Server thread/INFO]: [TheTowersRemastered 2.0-SNAPSHOT]
[00:12:20] [Server thread/INFO]: === ENABLE START ===
[00:12:20] [Server thread/INFO]: Loading dependencies...
[00:12:20] [Server thread/INFO]: Identified the following dependencies: [HIKARICP, SLF4J_SIMPLE, SLF4J_API, COMMONS_IO, FASTUTIL]
[00:12:21] [Server thread/ERROR]: Error occurred while enabling TheTowersRemastered v2.0-SNAPSHOT (Is it up to date?)
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Could not find a suitable constructor in net.megaplanet.thetowers.command.commands.admin.DebugCommands. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at net.megaplanet.thetowers.command.commands.admin.DebugCommands.class(DebugCommands.java:23)
  at net.megaplanet.gamecore.injector.AbstractBukkitModule.registerModule(AbstractBukkitModule.java:33) (via modules: net.megaplanet.gamecore.injector.BukkitModule -> net.megaplanet.thetowers.TheTowersModule)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[?:?]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[?:?]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[?:?]
        at com.google.inject.Guice.createInjector(Guice.java:99) ~[?:?]
        at com.google.inject.Guice.createInjector(Guice.java:84) ~[?:?]
        at net.megaplanet.gamecore.injector.BukkitInjector.<init>(BukkitInjector.java:24) ~[?:?]
        at net.megaplanet.gamecore.CorePlugin.onEnable(CorePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-c574e08-807a677]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-c574e08-807a677]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432) [spigot-1.15.2.jar:git-Spigot-c574e08-807a677]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-c574e08-807a677]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-c574e08-807a677]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-c574e08-807a677]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-c574e08-807a677]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-c574e08-807a677]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

So summary of my testing, the bug is not present on the latest build of spigot but is present on the latest build of paperspigot

**Comment by PatoTheBest** [comment]
After discussing this with @MiniDigger, it appears that the plugin classloader unloads the plugin before the error is logged because the logger is async. It's a race condition.

I'm catching the error now with a try, catch. I don't know if it's worth fixing this bug.

**Comment by electronicboy** [comment]
This is intentional and not a race condition, Paper will disable plugins when they fail to load properly, as opposed to leaving them dangling in a half mismashed state
