### ISSUE TITLE
Cannot get property BlockStateInteger

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#2964]
### Link/paste of stack trace

```
[18:17:59] [Server thread/WARN]: Entity threw exception at world2:5984.244988950357,77.4375,-8955.826057094002
[18:17:59] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot get property BlockStateInteger{name=eggs, clazz=class java.lang.Integer, values=[1, 2, 3, 4]} as it does not exist in Block{minecraft:air}
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.BlockDataAbstract.get(BlockDataAbstract.java:91)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.BlockTurtleEgg.a(BlockTurtleEgg.java:65)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.BlockTurtleEgg.a(BlockTurtleEgg.java:57)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.BlockTurtleEgg.stepOn(BlockTurtleEgg.java:26)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:628)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityItem.tick(EntityItem.java:90)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:759)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.a(World.java:856)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[18:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[18:17:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[18:17:59] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.minecraft.server.v1_15_R1.EntityItem} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.15.2.jar:git-Paper-103]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.15.2.jar:git-Paper-103]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:511) ~[patched_1.15.2.jar:git-Paper-103]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-103]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-103]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-103]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-103]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
Plugins (105): AdminVedelem, antiRedstoneClock, AreaShop, ArmorStandEditor, AsyncWorldEdit, BuntetesLogolo, ChangeSkin, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CombatLogX, CommandHook, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, DyedBackpacks, EnderContainers, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, GriefPrevention, GriefPreventionFlags, HeadDatabase*, HideAndSeek, HolographicDisplays, HonapStaffja, HotbarPets, HungerGames, JukeBox, Kemkedes, Kezdes, LibsDisguises, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, Shopkeepers, SignEdit, Sleepy*, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunPomaFix, StaffChat, StaffTime, Stats, Szilveszter, SzulinapiTuzijatek, TimeIsMoney*, TitleManager, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
I don't know.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-103 (MC: 1.15.2)

**Comment by mikroskeem** [comment]
Seems like something modified world unsafely

**Comment by electronicboy** [comment]
Something modified the world in an unexpected manner, i.e. setting the egg to air without cancelling the event
We have no interest in tryna deal with all of these edge-cases, too many to case up, plugins should just be sane
