### ISSUE TITLE
NullPointerException on InventoryClickEvent

### ISSUE THREAD

**Issue by EmilioBarradas** [PaperMC/Paper#2967]
### What behavior is expected:
Nothing

### What behavior is observed:
Java throws a NullPointerException when clicking outside the inventory. Tested on player, dispenser, and chest inventories. It does not throw an exception when tested on a creative inventory.

### Steps/models to reproduce:
```
public class Main extends JavaPlugin {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(new BoardListener(), this);
    }
```
```
public class BoardListener implements Listener {
    @EventHandler
    public void onInventoryClick(InventoryClickEvent event) {
    }
}
```

### Thrown exception:
```
[14:28:37 ERROR]: Could not pass event InventoryClickEvent to Bingo v1.0
java.lang.NullPointerException: null
        at org.decalers.BingoListener.onInventoryClick(BingoListener.java:16) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor14.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-105]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2329) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-105]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

### Plugin list:
Bingo (Plugin used to reproduce exception)

### Paper build number:
Paper-105

**Comment by electronicboy** [comment]
This is an issue with your plugin, which you've not provided the actual code for; if you click outside of the inventory, you're not interacting with the inventory, but, a packet is still sent from the client
