### ISSUE TITLE
max-auto-save-chunks-per-tick at -1 causes IAE right after server finishes booting

### ISSUE THREAD

**Issue by RoboMWM** [PaperMC/Paper#2981]
## Context
https://korobi.vq.lc/network/spigot/channel/paper/logs/#L209

### Link/paste of stack trace

https://hasteb.in/ocikuzax.txt

```
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Illegal Capacity: -1
	at java.base/java.util.ArrayList.<init>(Unknown Source)
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.saveIncrementally(PlayerChunkMap.java:367)
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.saveIncrementally(ChunkProviderServer.java:562)
	at net.minecraft.server.v1_15_R1.WorldServer.saveIncrementally(WorldServer.java:952)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1138)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Plugin list:
Too many

### Actions to reproduce (if known):
In `paper.yml`, set `max-auto-save-chunks-per-tick` to `-1` which afaik was the default value over a year or so ago.

### Paper build number:
git-Paper-118 (MC: 1.15.2)

**Comment by BillyGalbreath** [comment]
@Spottedleaf https://github.com/PaperMC/Paper/commit/d16a5d8813465b1b03c50adb756b9d324062f1f6#diff-ca6cdc4c5c87ca828b113323fbc357c6R198

**Comment by electronicboy** [comment]
was -1 an actual default value? if so, needs migrating, otherwise
![image](https://user-images.githubusercontent.com/1228900/75112604-4347e380-563d-11ea-8494-d219088391ca.png)

**Comment by FreeMonoid** [comment]
Yeah, sorry Robo, but this looks like a case of PEBKAC.

`max-auto-save-chunks-per-tick` was first introduced in 0fc642a1:

```
$ git log --all --oneline --reverse --source -S 'max-auto-save-chunks-per-tick' | head -1
0fc642a1        refs/remotes/origin/ver/1.10.2 Auto Save Improvements
```

with `24` as default, and it was never changed since then:

```
$ git log --all --oneline --reverse -S 'max-auto-save-chunks-per-tick' -p | grep 'max-auto-save-chunks-per-tick'
++        maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
+         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
+         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
-+        maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
-         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
++        maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
+         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
++        maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
-+        maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
+         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
-         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
+         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
-         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
-         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
++        maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
-+        maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
+         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
+         maxAutoSaveChunksPerTick = getInt("max-auto-save-chunks-per-tick", 24);
```

**Comment by RoboMWM** [comment]
I've had it set at -1 for over a year, will see if I can identify when I changed it, if I did.

**Comment by RoboMWM** [comment]
Ok, so I've had it set to `-1` for over 3 years. I guess I assumed -1 would set it to default like the other auto-save options introduced around that time. That, or it caused it to be disabled, I'm not sure which.

Authored Sep. 25, 2016
```diff
diff --git a/paper.yml b/paper.yml
index 3c391467f8abd11c1e5efedcfc0a163dca9023c6..c85c2572c9f71cfa8e6124a4e89e11232ec40c9f 100644
--- a/paper.yml
+++ b/paper.yml
@@ -85,7 +85,7 @@ world-settings:
     keep-spawn-loaded: false
     spawner-nerfed-mobs-should-jump: false
     delay-chunk-unloads-by: 30s
-    max-auto-save-chunks-per-tick: 24
+    max-auto-save-chunks-per-tick: -1
     optimize-explosions: true
     portal-search-radius: 128
     use-vanilla-world-scoreboard-name-coloring: false
```

**Comment by Spottedleaf** [comment]
the patch I modified assumed the max autosaves was always >= 0, before that didn't explode but now does
although previous behaviour (1.14+ before my patch) was to still save at least one chunk so there could be some arguing over values <= 0 anyways...
