### ISSUE TITLE
1.15.2 Nodes must be provided

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Paper#2996]
Sometimes I am getting an odd error while saving a config file. Restarting the server seems to solve the problem until it happens again, at random. There are no changes done to the file.

### What behaviour is observed:
Error:

```
java.lang.NullPointerException: Nodes must be provided.
	at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[patched_1.15.2.jar:git-Paper-122]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164) ~[patched_1.15.2.jar:git-Paper-122]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.15.2.jar:git-Paper-122]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.15.2.jar:git-Paper-122]
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[patched_1.15.2.jar:git-Paper-122]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307) ~[patched_1.15.2.jar:git-Paper-122]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:271) ~[patched_1.15.2.jar:git-Paper-122]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:246) ~[patched_1.15.2.jar:git-Paper-122]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39) ~[patched_1.15.2.jar:git-Paper-122]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[patched_1.15.2.jar:git-Paper-122]
	at org.mineacademy.fo.settings.ConfigInstance.save(YamlConfig.java:1976) ~[?:?]
	at org.mineacademy.fo.settings.YamlConfig.save(YamlConfig.java:428) ~[?:?]
	at org.mineacademy.fo.settings.YamlConfig.saveIfNecessary0(YamlConfig.java:322) ~[?:?]
	at org.mineacademy.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:312) ~[?:?]
	at org.mineacademy.arena.model.ArenaPlayer.<init>(ArenaPlayer.java:137) ~[?:?]
	at org.mineacademy.arena.model.ArenaPlayer.getCache(ArenaPlayer.java:545) ~[?:?]
	at org.mineacademy.arena.model.ArenaPlayer.getCache(ArenaPlayer.java:532) ~[?:?]
	at org.mineacademy.arena.mysql.ArenaDatabase.load(ArenaDatabase.java:67) ~[?:?]
	at org.mineacademy.arena.model.ArenaListener.lambda$onJoin$0(ArenaListener.java:153) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-122]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-122]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

### Steps/models to reproduce:
Use YamlConfiguration save method for file containing this: https://pastebin.com/v8mQTsrB

### Plugin list:
Arena

### Paper build number:
git-Paper-122 (MC: 1.15.2)

**Comment by electronicboy** [comment]
You have a null value in your config somewhere

**Comment by kangarko** [comment]
Can't this be gracefully handled?

How can I find where the value is?

**Comment by electronicboy** [comment]
> Can't this be gracefully handled

Not really, this is in snakeyaml territory, not API/Paper territory

> How can I find where the value is?

"easiest" option I know is to grab your debugger and analyze the contents of what you're tryna save

**Comment by kangarko** [comment]
Thanks so much!

If I grab the YamlConfiguration#getValues(true) and then save the toString value of the HashMap from it to a file would that be sufficient to see the null values?
