### ISSUE TITLE
potential bug in Paper

### ISSUE THREAD

**Issue by Monohitoxx** [PaperMC/Paper#3003]
### Link/paste of stack trace
[15:51:03] [Server thread/WARN]: Entity threw exception at world:-8536364.5,53.9375002,-2.41893965E7
[15:51:03] [Server thread/WARN]: net.minecraft.server.v1_15_R1.ReportedException: Colliding entity with block
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:671)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityLiving.e(EntityLiving.java:2257)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2624)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:525)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityAgeable.movementTick(EntityAgeable.java:171)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2383)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityVillager.tick(EntityVillager.java:185)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:759)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer$$Lambda$4434/0000000000000000.accept(Unknown Source)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.a(World.java:858)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[15:51:03] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:821)
[15:51:03] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Unhandled damage of EntityVillager['Villager'/985, uuid='ee16a8f8-89a0-4d19-9a56-5b5b32a01cfe', l='world', x=-8536364.50, y=53.94, z=-24189396.50, cx=-533523, cz=-1511838, tl=58463, v=true, d=false] from sweetBerryBush
[15:51:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:984)
[15:51:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:842)
[15:51:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1031)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.BlockSweetBerryBush.a(BlockSweetBerryBush.java:46)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IBlockData.a(IBlockData.java:218)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.Entity.checkBlockCollisions(Entity.java:950)
[15:51:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:665)
[15:51:03] [Server thread/WARN]: 	... 16 more
[15:51:03] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.minecraft.server.v1_15_R1.EntityVillager} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.15.2.jar:git-Paper-126]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:511) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-126]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_242]

### Plugin list:
DiscordSRV,MythicMobs,MyPet,BKCommonLib,worldedit,CMI,ItemAdder
React,Matrix,ProtocolLib,mcMMO,PlugMan,LuckPerms,Minepacks.MythicMobsExtension
MMOItem.worldguard,IridiumSkyblock,LibsDisguises,RandomTeleport,ShopGUIPlus
VentureChat,CoreProtect,PlaceholderAPI,NametagEdit,GriefPrevention,Vault,TrMenu,SAML
MyWorlds,HeadDatabase,MMOLib,PlayerHeads,WorldBorder,TabList,SimplePortals,LightAPI,AutoMessager
SinglePlayerSleep,VillagerOptimiser,EntityTrackerFixer

### Actions to reproduce (if known):

Suddenly appears in the console

### Paper build number:
git-paper-126(MC: 1.15.2)

**Comment by wizjany** [comment]
There is likely another error before this that's causing it that you're not providing.

**Comment by Monohitoxx** [comment]
> There is likely another error before this that's causing it that you're not providing.

oh sorry, i edited in post

**Comment by BillyGalbreath** [comment]
This error means something modified the `CraftEventFactory#blockDamage` field when a Villager tried to take damage from a sweetberry bush.

**Comment by Proximyst** [comment]
I've no record of this on a lot of production server logs. If you run into this on later versions, make a new issue. This is most definitely a plugin issue.
