### ISSUE TITLE
BlockDispenseEvent error

### ISSUE THREAD

**Issue by LogGits** [PaperMC/Paper#3007]
### Link/paste of stack trace
```
[09:41:55 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_15_R1.ReportedException: Exception while ticking
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1258) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-126]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_15_R1.ItemStack.checkEmpty(ItemStack.java:114) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.ItemStack.setCount(ItemStack.java:911) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.ItemStack.cloneAndSubtract(ItemStack.java:160) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DispenseBehaviorItem.a(DispenseBehaviorItem.java:25) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:15) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DispenseBehaviorShulkerBox.a(DispenseBehaviorShulkerBox.java:40) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:15) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.BlockDispenser.dispense(BlockDispenser.java:63) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.BlockDispenser.tick(BlockDispenser.java:89) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.IBlockData.a(IBlockData.java:210) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.WorldServer.b(WorldServer.java:732) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:90) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:411) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-126]
	... 4 more
[09:41:55 ERROR]: 	Cause of unexpected exception was
java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_15_R1.ItemStack.checkEmpty(ItemStack.java:114) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.ItemStack.setCount(ItemStack.java:911) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.ItemStack.cloneAndSubtract(ItemStack.java:160) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DispenseBehaviorItem.a(DispenseBehaviorItem.java:25) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:15) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DispenseBehaviorShulkerBox.a(DispenseBehaviorShulkerBox.java:40) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:15) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.BlockDispenser.dispense(BlockDispenser.java:63) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.BlockDispenser.tick(BlockDispenser.java:89) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.IBlockData.a(IBlockData.java:210) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.WorldServer.b(WorldServer.java:732) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:90) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:411) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-126]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-126]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
### Actions to reproduce (if known):
I was trying to change the behaviour of dispensers when dispensing a shulkerbox when I noticed this crash. I was trying to make it so the dispenser would dispense nothing and i'd force create the block. The block gets created as per my code but when i went to change the item to air (to remove it from the dispenser) it caused the crash. This can be reproduced using:
```java
@EventHandler
public void onDispense (BlockDispenseEvent event) {
   event.setItem(new ItemStack(Material.AIR));
}
```

### Paper build number:
paper 1.15.2 build 126

**Comment by electronicboy** [comment]
Quite simply, don't; You can't dispense air, and vanilla has already done it's "can we dispense this checks", there is no intent to patch every single instance where this error can be caused
