### ISSUE TITLE
Server crash when player login, is random is not every time.

### ISSUE THREAD

**Issue by broken1arrow** [PaperMC/Paper#3019]
### Link/paste of stack trace

  ---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 3/9/20 3:56 PM
Description: Exception in server tick loop

java.lang.StackOverflowError: Exception in server tick loop
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.getProgress(AdvancementDataPlayer.java:423)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.g(AdvancementDataPlayer.java:494)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.f(AdvancementDataPlayer.java:469)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:439)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:462)
	at net.minecraft.server.v1_15_R1.AdvancementDataPlayer.e(AdvancementDataPlayer.java:454)
	at 

### Plugin list:
Plugins: { dynmap v3.0-beta-10-257* org.dynmap.bukkit.DynmapPlugin [mikeprimm], 

WorldEdit v7.1.0;8e55131 com.sk89q.worldedit.bukkit.WorldEditPlugin [], PluginConstructorAPI v1.0.51 me.zombie_striker.pluginconstructor.PluginConstructorAPI [Zombie_Striker], 

EntityTrackerFixer v1.2.2 net.minemora.entitytrackerfixer.EntityTrackerFixer [Esmorall], VeinMiner v1.14.0 wtf.choco.veinminer.VeinMiner [2008Choco],

 PortableCraftingInvs v1.1.6 com.itsschatten.portablecrafting.PortableCraftingInvsPlugin [ItsSchatten], 

PlaceholderAPI v2.10.4 me.clip.placeholderapi.PlaceholderAPIPlugin [extended_clip, Glare], 

VillagerOptimiser v1.1.2 com.froobworld.avl.Avl [froobynooby], 

WorldBorder v1.9.10 (beta) com.wimbli.WorldBorder.WorldBorder [Brettflan], Oh_the_dungeons_youll_go v1.2.9 otd.Main [zhehe, atomicstryker, greymerk, jaredbgreat, shadow_wind, yeregorix], Votifier v2.6.0-SNAPSHOT com.vexsoftware.votifier.NuVotifierBukkit [Ichbinjoe, blakeman8192, Kramer, tuxed], ProtocolLib v4.5.0 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], 

ChestSort v7.1 de.jeffclan.JeffChestSort.JeffChestSortPlugin [mfnalex], 

WorldGuard v7.0.2-SNAPSHOT;bf2593e com.sk89q.worldguard.bukkit.WorldGuardPlugin [], 

RPGChest v2.2.1.0 me.gilles_m.RPGChestPremium.RPGChest [gilles_m], 

CommandPrompter v0.1.18 com.cyr1en.cp.CommandPrompter [CyRien],

 MVdWPlaceholderAPI v3.0.1* be.maximvdw.placeholderapi.PlaceholderAPI [Maximvdw], 

MobFarmManager v1.5.5.0 com.MobFarmManager.Zrips.MFM [Zrips], 

DeluxeMenus v1.12.0 com.extendedclip.deluxemenus.DeluxeMenus [extended_clip], 

LimitPillagers v2.12.0 me.hexedhero.lp.LimitPillagers [HexedHero], 

mcMMOHorse v4.3.58 com.blueskullgames.horserpg.HorseRPG [GetGoodKid, Zombie_Striker], 

mcMMO v2.1.122 com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy, kashike], 

CraftingStore v2.2.1 net.craftingstore.bukkit.CraftingStoreBukkit [Tim_kwakman, thijs_a], 

UltraPermissions v4.4.8 me.TechsCode.UltraPermissions.base.loader.SpigotLoader [], CoreProtect v2.18.2 net.coreprotect.CoreProtect [Intelli], 

OreAnnouncer v2.4.6 com.alessiodp.oreannouncer.bukkit.bootstrap.BukkitOreAnnouncerBootstrap [AlessioDP], 

CustomEnderChest v1.12.2 net.craftersland.customenderchest.EnderChest [CraftersLand], FractalForest v1.10.1 com.eclipsekingdom.fractalforest.FractalForest [sword], Vault v1.7.2-b107 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], 

TokenManager v3.2.4 me.realized.tokenmanager.TokenManagerPlugin [Realized],
 
BottledExp v2.2.6.1 me.Zrips.bottledexp.BottledExp 

[Zrips], NPCAuctions v1.0.62 me.zombie_striker.npcauctions.Main [Zombie_Striker], 

JetsHoppers v3.0.1 me.jet315.jetshoppers.JetsHoppersPlugin [Jet315], 

Lands v4.5.3.0 me.angeschossen.lands.Lands [Angeschossen], Jobs v4.15.5 com.gamingmesh.jobs.Jobs [phrstbrn, Zrips, montlikadani], LWC v2.2.4-52f8c06 com.griefcraft.lwc.LWCPlugin [Hidendra, pop4959, Me_Goes_RAWR], 

DiscordSRV v1.18.4 github.scarsz.discordsrv.DiscordSRV [Scarsz, Androkai], 

WildChests v1.4.0 com.bgsoftware.wildchests.WildChestsPlugin [Ome_R], 

UltimateTimber v2.0.4 com.songoda.ultimatetimber.
UltimateTimber [Songoda, Esophose], TheNewEconomy v0.1.1.9 net.tnemc.core.TNE [creatorfromhell], 

ChatControl v8.6.6 org.mineacademy.chatcontrol.ChatControl [kangarko], CMI v8.6.20.3 com.Zrips.CMI.CMI [Zrips], 
QuickShop v3.1.4.19 org.maxgamer.quickshop.
QuickShop [BukkitCommonsStudio, Netherfoam, Timtower, KaiNoMood, Ghost_chu, Mgazul, TiaraRinne],}

### Actions to reproduce (if known):
Crash when player login (but is not every time is random when it happen). We have delete  Advancement before, when we upgrade from 14.4 to 1.15.0 (spigot 8 i think it was) we have crash daily, so we have to delete  Advancement (and it work approximately one month but now is problem back).

### Paper build number:
git-Paper-129 (the problem start in 15 uppdate)
[crash-2020-03-10_18.35.41-server.txt](https://github.com/PaperMC/Paper/files/4319267/crash-2020-03-10_18.35.41-server.txt)
[crash-2020-03-10_17.30.05-server.txt](https://github.com/PaperMC/Paper/files/4319268/crash-2020-03-10_17.30.05-server.txt)
[crash-2020-03-09_15.56.37-server.txt](https://github.com/PaperMC/Paper/files/4319269/crash-2020-03-09_15.56.37-server.txt)

**Comment by electronicboy** [comment]
Seen people talk about this once or twice, but, not replicated
Do you have datapacks or something? affected players advancement data?

**Comment by broken1arrow** [comment]
No, no datapacks, only plugins so the worlds is vanilla. 

Far as know can players get and don't lose advancement (no player has complaining), my own works and the server crash when i try to login last time.

**Comment by electronicboy** [comment]
I'm asking for a copy of an affected players advancement data, there is more than likely something wrong with the saved data

**Comment by broken1arrow** [comment]
Yes my and other player some cause a crash before. (have to use zip file for this, github not support this files)
[Ny komprimerad mapp.zip](https://github.com/PaperMC/Paper/files/4319353/Ny.komprimerad.mapp.zip)

**Comment by electronicboy** [comment]
cannot replicate with those files

**Comment by broken1arrow** [comment]
Is not happen every time i´m login, before we remove/"reset" advancement, so can i repeat the error with hard serverload (dig lots of sand) and the console start spamming (and not so long time after server crash). Was some time ago now, but i think server crash when some try to join after i´m hard load the server.

**Comment by broken1arrow** [comment]
So have to get use to the bugg or turn off advancement?

**Comment by sandtechnology** [comment]
I noticed that:`JVM Flags: 4 total; -Xmx5120M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512`
May be ThreadStackSize is too low? What if remove `-XX:ThreadStackSize=512` in JVM Flags?

**Comment by broken1arrow** [comment]
We use a host, so i cant see any place to change it. But I shall see if I can change it some how or my host can.

**Comment by broken1arrow** [comment]
Is working now, we use own server and we not get any issue (run it for months on that server and not counter this).

So it feels like it was our host's fault, either poor performance or settings.
