### ISSUE TITLE
Error executing task on Server

### ISSUE THREAD

**Issue by Ghost-chu** [PaperMC/Paper#3022]
### What behaviour is expected:
___What you expected to see___
Server running without errors.

### What behaviour is observed:
___What you actually saw___
Console throw an exception. [https://paste.ubuntu.com/p/dC4gMZJbPy/]

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. Start a server
2. The error will random throw out (fully random), sometimes will but not always.

### Plugin list:
___A list of your plugins___
```
Plugins (98): AdvancedAchievements, AFKTitle*, AlertMineWorld, AlwaysOnline*, BBSToper*, BeehiveInfo, BlockLocker, BlocksHub, BorderProtect, CaulCrafting*, ChatReplay, ChatSync, ChineseCommand*, Citizens, CitizensCMD, CmdConfirm*, ColorAnvil*, ColoredBooks*, ColoredPrefix, CommandNotifier, Confiscate, ConsoleSpamFix, CoreProtect, CoreProtectTNT, CraftBook, DeluxeChat, EntityDetection, EntityTrackerFixer, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EusPrivChat, F3Name, FakeSeed, FixMyData*, ForceResourcepacks, GreenFingers, GSit, HamsterEcoHelper, HeadDropsSS, HolographicDisplays, HopperFilter, IllegalStack, InventoryRollback, JetsMinions*, KickIdlePlayer, LangUtils, Lift, LimitPillagers, LiteBans, Lock, Lores*, LuckPerms, mcMMO, MineSync*, MobArena, MobFarmManager, Multiverse-Core, MyPet, NewbieProtection, NyaaCore, NyaaUtils, OpenInv, ourtown, PetMaster, PhantomSMP, PlaceholderAPI, PlayerReport*, PlayTimeTracker, PluginConstructorAPI, PlugMan*, ProtocolLib, QualityArmory, QuickShop, ravager-anti-grief, RememberHighestOnline*, RideMe-Plus*, RPGItems, Shell*, Signature, SmoothSleep, spark, StarGate, SuperVanish, TitleManager, UniBan, UniBanCopy, Vault, ViaBackwards, ViaVersion, VillagerOptimiser, VoidGenerator, WorldEdit, yasui, YouAreNotLostConnection*
```

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

```
[07:41:27 INFO]: This server is running Paper version git-Paper-132 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[07:41:27 INFO]: Checking version, please wait...
[07:41:28 INFO]: Previous version: git-Paper-126 (MC: 1.15.2)
[07:41:28 INFO]: You are running the latest version
```

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Ghost-chu** [comment]
```
[21:22:11 FATAL]: Error executing task on Server
java.lang.NullPointerException: null
at net.minecraft.server.v1_15_R1.ChunkMapDistance.b(ChunkMapDistance.java:230) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1362) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:827) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1145) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[PaperSpigot-1.15.2.jar:git-Paper-143]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```
Error still on 143

**Comment by i0xHeX** [comment]
Still on b146
```
[15:44:52] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.b(ChunkMapDistance.java:230) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1362) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:827) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1145) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-146]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by aikar** [comment]
Ok good to know this isn't from my changes, as I also had this.

Worth also noting, that the player who caused it also printed with it:
smp6:[21:12:33] [Server thread/INFO]: Attempt to teleport dead player <player> restricted

**Comment by aikar** [comment]
This should now be fixed in build 160
