### ISSUE TITLE
I can not join my local server

### ISSUE THREAD

**Issue by hamza-cskn** [PaperMC/Paper#3040]
### What behaviour is expected:
___What you expected to see___
i want to join to my server

### What behaviour is observed:
___What you actually saw___
i can not join to my server :d (Console Error: `Mr_Obliviate lost connection: Internal Exception: java.lang.IllegalStateException: EvtPacket may only be triggered synchronously.`)

### Plugin list:
![image](https://user-images.githubusercontent.com/36128276/76804428-402fb580-67ed-11ea-9662-0b9b84d27d92.png)

### Paper build number:
 git-Paper-243 (MC: 1.14.4) R0.1-SNAPSHOT

Also: 
```[02:56:44 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-243 (MC: 1.14.4) ---
[02:56:44 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[02:56:44 ERROR]: ------------------------------
[02:56:44 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[02:56:44 ERROR]: The server is waiting on these chunks: []
[02:56:44 ERROR]: ------------------------------
[02:56:44 ERROR]: Current Thread: Server thread
[02:56:44 ERROR]:       PID: 21 | Suspended: false | Native: false | State: RUNNABLE
[02:56:44 ERROR]:       Stack:
[02:56:44 ERROR]:               java.lang.invoke.MethodHandleNatives.refKindIsMethod(Unknown Source)
[02:56:44 ERROR]:               java.lang.invoke.MemberName.<init>(Unknown Source)
[02:56:44 ERROR]:               java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source)
[02:56:44 ERROR]:               java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source)
[02:56:44 ERROR]:               me.xanium.gemseconomy.listeners.EconomyListener.onJoin(EconomyListener.java:67)
[02:56:44 ERROR]:               com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor11.execute(Unknown Source)
[02:56:44 ERROR]:               org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[02:56:44 ERROR]:               org.bukkit.plugin.EventExecutor$$Lambda$2249/314743132.execute(Unknown Source)
[02:56:44 ERROR]:               co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:56:44 ERROR]:               org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:56:44 ERROR]:               org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[02:56:44 ERROR]:               net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191)
[02:56:44 ERROR]:               net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174)
[02:56:44 ERROR]:               net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65)
[02:56:44 ERROR]:               net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256)
[02:56:44 ERROR]:               net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139)
[02:56:44 ERROR]:               net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255)
[02:56:44 ERROR]:               net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[02:56:44 ERROR]:               net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
[02:56:44 ERROR]:               net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[02:56:44 ERROR]:               java.lang.Thread.run(Unknown Source)
[02:56:44 ERROR]: ------------------------------
[02:56:44 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[02:56:44 ERROR]: ------------------------------

**Comment by Brokkonaut** [comment]
You should fix your server. You have a lot of outdated and/or not loading plugins. So the first thing you should do is updating your plugins and remove the outdated ones.

For the first exception a stack trace is required (the whole log around that exception) otherwise its impossible to say what happened there. 

For the second exception: Thats not a server bug, but a laggy plugin. Have a look at this:
me.xanium.**gemseconomy**.listeners.EconomyListener.onJoin(EconomyListener.java:67)

**Comment by Obliviated** [comment]
i updated holographic display so skript-holo and holographic display been enabled.  and i delete citizens and gems economy. (when i delete only citizens don't working still) and i try to start my server.

```Downloading vanilla jar...
Failed to download vanilla jar
java.io.IOException: Diskte yeterli yer yok
        at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.pwrite(Unknown Source)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.write(Unknown Source)
        at sun.nio.ch.FileChannelImpl.writeInternal(Unknown Source)
        at sun.nio.ch.FileChannelImpl.write(Unknown Source)
        at sun.nio.ch.FileChannelImpl.transferFromArbitraryChannel(Unknown Source)
        at sun.nio.ch.FileChannelImpl.transferFrom(Unknown Source)
        at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:114)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:45)
Restart? [Y/N]```
...and i got that.

**Comment by hamza-cskn** [comment]
i tried everything. i deleted gems economy and citizens. i updated others. all plugins been enabled.

[Click to see full console log.](https://paste.ubuntu.com/p/Fg39HFPVFw/)

**Comment by Redned235** [comment]
Update to 1.15. 1.14 is no longer supported.

**Comment by Brokkonaut** [comment]
It looks like some of the plugins is still doing things that it should not do. Try to remove the plugins one by one to find the plugin that causes this.

**Comment by hamza-cskn** [comment]
> It looks like some of the plugins is still doing things that it should not do. Try to remove the plugins one by one to find the plugin that causes this.

skript causes. but i need it than all

**Comment by Draycia** [comment]
>Try to remove the plugins one by one

Binary search is better than one by one.

**Comment by electronicboy** [comment]
> EvtPacket may only be triggered synchronously

You have a plugin firing an event in an unsupported manner (event is being fired on a network thread, but is marked to only be called from the server thread), you'll need to work out what plugin and update/get it fixed/remove it
