### ISSUE TITLE
[Crash] when the server try to read a chunk data

### ISSUE THREAD

**Issue by Tiplish** [PaperMC/Paper#3063]
Hi, since few days now, we are facing some troubles. It seems that it happends when we try to go in another world just after load/unload a world

### Link/paste of stack trace
https://pastebin.com/GvMTeaLm

### Plugin list:
DungeonsXL 0.18-SNAPSHOT-819
Multiverse 4.1.0

### Actions to reproduce (if known):
Create a dungeon (Which will create a map)
Leave this dungeon 
Try to change world

### Paper build number:
git-Paper-120 (MC: 1.15.2)

Any idea ? Thanks

**Comment by Brokkonaut** [comment]
Similar to what I mentioned here: https://github.com/PaperMC/Paper/issues/2991#issuecomment-592996516

Somehow paper sometimes closes the files when it should not...

**Comment by Tiplish** [comment]
Another clue : 
It happends for every player who has the fakejoin. When they do the /va to became visible again, the server crash.

**Comment by mikroskeem** [comment]
Please reproduce with latest version

**Comment by Tiplish** [comment]
I'm on the #143 version and i reproduce this already

**Comment by Tiplish** [comment]
this still occure in #146 :s 
```
[16:34:12] [Paper RegionFile IO Thread/FATAL]: Failed to read chunk data for task: Task for world: 'DXL_Game_0' at 1,-8 poi: false, hash: 178714162
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:150) ~[?:?]
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:790) ~[?:?]
	at net.minecraft.server.v1_15_R1.RegionFile.a(RegionFile.java:142) ~[paperspigot.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.RegionFileCache.read(RegionFileCache.java:141) ~[paperspigot.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.read(PlayerChunkMap.java:1129) ~[paperspigot.jar:git-Paper-146]
	at net.minecraft.server.v1_15_R1.WorldServer$2.readData(WorldServer.java:138) ~[paperspigot.jar:git-Paper-146]
	at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:557) ~[paperspigot.jar:git-Paper-146]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paperspigot.jar:git-Paper-146]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paperspigot.jar:git-Paper-146]
[16:34:12] [Paper Async Chunk Task Thread #0/ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.ch
```

**Comment by Tiplish** [comment]
Any news ?

**Comment by Tiplish** [comment]
still occure with #161 build of paper.

**Comment by Sataniel98** [comment]
I am not very experienced with programming on server software level, but I am currently 80% sure that at least one possible cause of this is calling Bukkit.unloadWorld(world, true) and deleting the world folder in the same tick. I imagine at least parts of unloading the world are done asynchronously, and that these async tasks aren't finished when the folder is deleted.

The reason why I was doing it is that Bukkit.unloadWorld(world, false) [used to be severely broken until 1.14.4](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/da62a66ab70e926e86755ceba15d8b7759d3c36f#src/main/java/org/bukkit/craftbukkit/CraftServer.java).

**Comment by PierreBouchet** [comment]
Still occure in paper#227
Failed to read chunk data for task: Task for world: 'DXL_Game_0' at 5,8 poi: true, hash: 687973975

**Comment by aikar** [comment]
https://github.com/DRE2N/DungeonsXL/blob/master/core/src/main/java/de/erethon/dungeonsxl/world/DGameWorld.java#L461

This is source of the issue. DungeonsXL needs to fix this to not go blindly deleting the folder so fast.

**Comment by aikar** [comment]
though based on @Sataniel98's comment, may be resolved now in updated DXL

**Comment by Sataniel98** [comment]
I think @PierreBouchet's comment is an unrelated problem. It has nothing to do with Paper.

**Comment by Squawkykaka** [comment]
Happened to me to to deleted the world file though

**Comment by electronicboy** [comment]
This is generally a limitation of the world system, unloading worlds is about as supported as "it works", there's much work which needs to be done to fix these types of things
