### ISSUE TITLE
Server crash when Nether Portal was lit with a dispenser + flint & steel while an explosion occurred nearby

### ISSUE THREAD

**Issue by widd** [PaperMC/Paper#3084]
```
net.minecraft.server.v1_15_R1.ReportedException: Exception while ticking
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1258) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: Cannot get property BlockStateDirection{name=facing, clazz=class net.minecraft.server.v1_15_R1.EnumDirection, values=[north, east, south, west, up, down]} as it does not exist in Block{minecraft:air}
        at net.minecraft.server.v1_15_R1.BlockDataAbstract.get(BlockDataAbstract.java:91) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:18) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.BlockDispenser.dispense(BlockDispenser.java:63) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.BlockDispenser.tick(BlockDispenser.java:89) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.IBlockData.a(IBlockData.java:210) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.WorldServer.b(WorldServer.java:738) ~[patched_1.15.2.jar:git-Paper-151]
        at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:296) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:46) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:418) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-151]
        ... 4 more
[03:17:53 ERROR]:       Cause of unexpected exception was
java.lang.IllegalArgumentException: Cannot get property BlockStateDirection{name=facing, clazz=class net.minecraft.server.v1_15_R1.EnumDirection, values=[north, east, south, west, up, down]} as it does not exist in Block{minecraft:air}
        at net.minecraft.server.v1_15_R1.BlockDataAbstract.get(BlockDataAbstract.java:91) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:18) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.BlockDispenser.dispense(BlockDispenser.java:63) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.BlockDispenser.tick(BlockDispenser.java:89) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.IBlockData.a(IBlockData.java:210) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.WorldServer.b(WorldServer.java:738) ~[patched_1.15.2.jar:git-Paper-151]
        at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:296) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:46) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:418) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-151]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

### Actions to reproduce (if known):
Make a dispenser light a Nether Portal, and spawn an explosion at the same time at the same location. Seems to only occur when explosion is timed to remove blocks at the same tick (or close to same tick) as the portal/redstone contraption lighting the portal.

### Paper build number:
Paper 151

**Comment by GRAnimated** [comment]
Cannot reproduce. Can you show your setup for it?

**Comment by widd** [comment]
> Cannot reproduce. Can you show your setup for it?

Was able to reproduce almost 100% of the time using a simple listener plugin (to make the explosion) on a new paper 151 install:

```
@EventHandler
public void onPortalCreate(PortalCreateEvent event) {
        Random rng = new Random();
	List<BlockState> states = event.getBlocks();

	if (event.getReason() == PortalCreateEvent.CreateReason.FIRE) {
                // pick a random portal block to place the explosion
		BlockState state = states.get(rng.nextInt(states.size()));
		event.getWorld().createExplosion(state.getLocation(), 5F, true, true);
	}
}
```

Light a portal via dispenser + flint and steel and it should trigger the crash.

Also confirmed it happens as of paper 158.
