### ISSUE TITLE
NSM Skeleton Cause TIMING_STACK_CORRUPTION/or NoSuchMethod in PapareShotEvent

### ISSUE THREAD

**Issue by DaRichardX** [PaperMC/Paper#3101]
### What behaviour is expected:
Deadly Accurate Skeleton, I Override the shot function

### What behaviour is observed:
Disappear When Shooting

### Steps/models to reproduce:
Use My Plugin And Spawn A Skeleton

### Plugin list:
MyPlugin and EssentialsX

### Paper build number:
243

### Anything else:
Error In Console

[15:12:33 WARN]: Entity threw exception at world:-202.31545867842078,64.0,29.44260244687138
[15:12:33 WARN]: java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityShootBowEvent(Lnet/minecraft/server/v1_14_R1/EntityLiving;Lnet/minecraft/server/v1_14_R1/ItemStack;Lnet/minecraft/server/v1_14_R1/Entity;F)Lorg/bukkit/event/entity/EntityShootBowEvent;
[15:12:33 WARN]:        at me.RichardX.Milktea.AdvanceMob.NSMMobs.SniperSkeleton.a(SniperSkeleton.java:36)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.PathfinderGoalBowShoot.e(SourceFile:128)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.e(SourceFile:55)
[15:12:33 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[15:12:33 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[15:12:33 WARN]:        at java.util.Iterator.forEachRemaining(Unknown Source)
[15:12:33 WARN]:        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
[15:12:33 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[15:12:33 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[15:12:33 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[15:12:33 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[15:12:33 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[15:12:33 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:80)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:662)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2533)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:504)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.EntityMonster.movementTick(EntityMonster.java:23)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.EntitySkeletonAbstract.movementTick(EntitySkeletonAbstract.java:85)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2322)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.EntityMonster.tick(EntityMonster.java:37)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:702)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.World.a(World.java:936)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:472)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
[15:12:33 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[15:12:33 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:12:33 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - me.RichardX.Milktea.AdvanceMob.NSMMobs.SniperSkeleton} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.4.jar:git-Paper-243]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:486) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[15:12:33 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - me.RichardX.Milktea.AdvanceMob.NSMMobs.SniperSkeleton} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.4.jar:git-Paper-243]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:486) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by electronicboy** [comment]
this is a plugin issue, apparently, it doesn't support that version of paper, nor do we
