### ISSUE TITLE
Cannot Send Chat Message

### ISSUE THREAD

**Issue by FreeMonoid** [PaperMC/Paper#3114]
### What behaviour is expected:
Players being able to read/send chat messages and commands.

### What behaviour is observed:
Occasionally, some players are unable to read/send chat messages and commands until they re-login.

### Steps/models to reproduce:
Seems to be very intermittent; happened to me while being in Spectator mode and "possessing" another player.

### Plugin list:
```
Plugins (55): ArenaSpleef, BattleArena, Citizens, CMI, CMIEInjector*, CommandDoesNotExist, CoralStay, CoreProtect, DeluxeMenus, DiceFurniture, EntityDetection, Essentials, EssentialsSpawn, FurnitureLib, GriefPrevention, GriefPreventionFlags, IllegalStack, InventoryRollback, ItemJoin, LangUtils, LastLoginAPI, LibsDisguises, LimitPillagers, LuckPerms, MarriageMaster, Minepacks, MobArena, Multiverse-Core, PacketLimiter, Parties, PetMaster, PhantomX, PhatLoots, PlaceholderAPI, Plan, PlayerParticles, ProtectionLib*, ProtocolLib, ProtocolSupport, PvPToggle, QuickShop, RestrictedCreative, SelectionVisualizer, spark, Spartan, TradeMe, TreasureChestReloaded, UltimateTimber, Vault, VoidGenerator, VoidWorld*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags
```

### Paper build number:
```
[00:44:56 INFO]: This server is running Paper version git-Paper-162 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[00:44:56 INFO]: Checking version, please wait...
[00:44:57 INFO]: Previous version: git-Tuinity-"b2e87f8" (MC: 1.15.2)
[00:44:57 INFO]: You are 2 version(s) behind
```

### Anything else:

CME was thrown when this happened:

```
[00:38:59 WARN]: Entity threw exception at world:1587.0934021929868,71.0,-4382.642132101442
[00:38:59 WARN]: java.util.ConcurrentModificationException
[00:38:59 WARN]:        at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
[00:38:59 WARN]:        at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
[00:38:59 WARN]:        at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
[00:38:59 WARN]:        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
[00:38:59 WARN]:        at java.base/java.util.HashMap.putMapEntries(Unknown Source)
[00:38:59 WARN]:        at java.base/java.util.HashMap.<init>(Unknown Source)
[00:38:59 WARN]:        at com.google.common.collect.Maps.newHashMap(Maps.java:333)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.NBTTagCompound.clone(NBTTagCompound.java:405)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.ItemStack.cloneItemStack(ItemStack.java:494)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.ItemStack.cloneItemStack(ItemStack.java:485)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.Container.c(Container.java:137)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.EntityPlayer.tick(EntityPlayer.java:382)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:769)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.World.a(World.java:862)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:504)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[00:38:59 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[00:38:59 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```

Users of Tuinity report similar issue if that's any help: https://github.com/Spottedleaf/Tuinity/issues/78

**Comment by zachbr** [comment]
Thanks

**Comment by aikar** [comment]
Can you reproduce without plugins, especially CMI?

This means something is modifying the players inventory asynchronously. 
This then kills the player from the world and causes the described behavior.

Ultimately, this most likely a plugin causing it.

Though linked issue doesnt seem to have CMI, so cross reference what plugins you have in common.

**Comment by Spottedleaf** [comment]
Context: talking about teleportAsync (to different worlds)
```
Z750Today at 2:58 PM
Yeah I had a report of that in paper the other day
only 2 so far so its pretty rare
Mr Worldwide!Today at 2:58 PM
I've seen a lot of people reporting it on this Discord Z
Z750Today at 2:58 PM
people were still showing up in tab o its like the playerlist is getting out of sync somewhere
SpottedleafToday at 2:58 PM
lines up with theory then
ok since paper is involved lemme give the working theory
Z750Today at 2:59 PM
maybe that illegalentitytracking catch changes?
SpottedleafToday at 2:59 PM
no
Z750Today at 2:59 PM
ok
SpottedleafToday at 2:59 PM
it's more or less to do with vanilla entity adding
they restrict it when ticking
when ticking entities *
so let's say an entity causes a sync load
entities get added to world - that's fine, they have logic to help that
removed? oh shit it explodes
sync loads call plugin logic
i.e they can remove entities
unload chunks
and god fucking knows
and teleport players
i.e teleportAsync
now if you try to remove while ticking you're fucked
it throws
but guess what
it's behind a completable future
IT WONT FUCKING PRINT THE EXCEPTION
so we don't know if that'
s the case
(and it's the debug I added in latest builds)
```

Code shows a real risk of causing this if the teleport call throws due to the remove entity call throwing - which is right after setting dead to true. Thus leaving the entity in a dead state, and since completablefuture swallows the exception, us none the wiser about what happened.

**Comment by FreeMonoid** [comment]
For the record, common plugins between our two reports are:

```
CoreProtect
Essentials
EssentialsSpawn
GriefPrevention
LibsDisguises
LimitPillagers
LuckPerms
Minepacks
Multiverse-Core
ProtocolLib
Vault
WorldEdit
WorldGuard
WorldGuardExtraFlags
```

I will try to reproduce without plugins.

**Comment by aikar** [comment]
The reported issue here in this ticket is not relating to teleporting.

I do see the risk that if you teleport a player to another world during the ticking process, I can see the removeEntity failing, but thats for all teleporting, not just async, asyncs actually looking less risky due to it waiting for a chunk load which is most likely going to fall OUT of the tickingEntities block.

But that is a different issue with just similar outcomes.

**Comment by FreeMonoid** [comment]
It _might be_ somewhat related to teleporting since player died while I was "possessing" them, although I wasn't able to repro it in a reliable fashion yet.

**Comment by Proximyst** [comment]
Copying [this comment on Tuinity's issue](https://github.com/Spottedleaf/Tuinity/issues/78#issuecomment-612401493) here:

I reverted Paper's commits https://github.com/PaperMC/Paper/commit/16287d01e279f758e15ef3db0e51d7f059818c09 and https://github.com/PaperMC/Paper/commit/cfaf32cf66ac786be2bc9d34a1c7bb4c9de967ad on a local fork and the issue seems to have vanished.

A temporary fix would be patching these two commits away.

EDIT: I spoke a few minutes too soon.. seems this wasn't enough; first report is in :/

**Comment by aikar** [comment]
@Proximyst that doesn't stop the illegal teleport. The real issue here is that async chunk loads can fire in the middle of entity ticking. 
In your scenario it was caused by Tuinity's version of of mid tick chunks, but that will occur in paper too.

But, it can appen even regardless of those 2 ticks if any entity causes a sync chunk load in that same world a load is pending for.

As well as it can happen if any PLUGIN tries to teleport based on an entity event cross world....

For example "On being hit in overworld, 5% chance the monster sends you to the nether" would trigger this without any of those patches.

Ultimate solution would be to get rid of mojangs exception and make it work to remove an entity mid entity ticking.
