### ISSUE TITLE
No chunk holder after ticket has been added

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#3125]
### What behaviour is expected:
___What you expected to see___
The player no kicked this error.

### What behaviour is observed:
___What you actually saw___
The player kicked this error.
```
[00:18:06 INFO]: nns[/IP address] logged in with entity id 9358876 at ([world2]3010.3641705613054, 62.07326471152709, -1901.1756721096108)
[00:18:06 INFO]: [+] nns
[00:18:29 WARN]: Failed to handle packet for /IP address
net.minecraft.server.v1_15_R1.ReportedException: Ticking player
at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:520) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:149) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1284) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1127) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:935) ~[patched_1.15.2.jar:git-Paper-167]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: No chunk holder after ticket has been added
at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:454) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:387) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:325) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:270) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.World.getChunkAtWorldCoords(World.java:257) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.ItemWorldMap.a(ItemWorldMap.java:99) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.ItemWorldMap.a(ItemWorldMap.java:329) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.ItemStack.a(ItemStack.java:543) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.PlayerInventory.j(PlayerInventory.java:287) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.EntityHuman.movementTick(EntityHuman.java:426) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2383) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:438) ~[patched_1.15.2.jar:git-Paper-167]
... 8 more
[00:18:29 INFO]: nns lost connection: Internal server error
```

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Randomly. I don't know.

### Plugin list:
___A list of your plugins___
`Plugins (105): AdminVedelem, antiRedstoneClock, ArmorStandEditor, AsyncWorldEdit, BetterGUI, ChangeSkin, ChatControl, ChestShop, ChestShopNotifier*, ChestSort, ChestTerminal, Citizens, CitizensCMD, CombatLogX, CommandHook, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, DisablePistonFarming, Duels, DyedBackpacks, EasterEggs*, EnderContainers, EntityDetection, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, ExtraTools, GPAccruals*, GriefPrevention, GriefPreventionFlags, HeadDatabase*, HideAndSeek, HolographicDisplays, HonapStaffja, HotbarPets, HungerGames, Kemkedes, Kezdes, LibsDisguises, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, OpenInv, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, Shopkeepers, SignEdit, Sleepy*, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunPomaFix, StaffChat, StaffTime, TimeIsMoney*, TitleManager, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, VillagerOptimiser, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge`

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-167 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by aikar** [comment]
This was fixed (hopefully) in 168, please update.
