### ISSUE TITLE
Failed to handle packet

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#3126]
### What behaviour is expected:
___What you expected to see___
No fail this?

### What behaviour is observed:
___What you actually saw___
```
[18:18:45] [Server thread/WARN]: Failed to handle packet for /IP address
net.minecraft.server.v1_15_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:520) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:149) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1284) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1127) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:935) ~[patched_1.15.2.jar:git-Paper-167]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_15_R1.StructureGenerator.a(StructureGenerator.java:163) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.StructureGenerator.a(StructureGenerator.java:55) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.StructureGenerator.b(StructureGenerator.java:86) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.CriterionConditionLocation.a(SourceFile:83) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.CriterionConditionLocation.a(SourceFile:60) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.CriterionTriggerLocation$a.a(SourceFile:54) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.CriterionTriggerLocation.a(SourceFile:30) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.CriterionTriggerAbstract.a(SourceFile:49) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.CriterionTriggerLocation.a(SourceFile:30) ~[patched_1.15.2.jar:git-Paper-167]
	at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:502) ~[patched_1.15.2.jar:git-Paper-167]
	... 8 more
```

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Randomly. I don't know.

### Plugin list:
___A list of your plugins___
`Plugins (105): AdminVedelem, antiRedstoneClock, ArmorStandEditor, AsyncWorldEdit, BetterGUI, ChangeSkin, ChatControl, ChestShop, ChestShopNotifier*, ChestSort, ChestTerminal, Citizens, CitizensCMD, CombatLogX, CommandHook, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, DisablePistonFarming, Duels, DyedBackpacks, EasterEggs*, EnderContainers, EntityDetection, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, ExtraTools, GPAccruals*, GriefPrevention, GriefPreventionFlags, HeadDatabase*, HideAndSeek, HolographicDisplays, HonapStaffja, HotbarPets, HungerGames, Kemkedes, Kezdes, LibsDisguises, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, OpenInv, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, Shopkeepers, SignEdit, Sleepy*, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunPomaFix, StaffChat, StaffTime, TimeIsMoney*, TitleManager, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, VillagerOptimiser, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge`

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-167 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by hurrgurl** [comment]
Update to https://papermc.io/downloads 168 (aikar edit: please use downloads page and not jenkins :))

**Comment by aikar** [comment]
This was fixed in 168
