### ISSUE TITLE
[Crash] Frequent server crashes - multiple per day

### ISSUE THREAD

**Issue by pelennor2170** [PaperMC/Paper#3146]
### Link/paste of stack trace
---- Minecraft Crash Report ----
// Sorry :(

Time: 4/15/20 6:59 AM
Description: Watching Server

java.lang.Error
	at bjk$1.tryAdvance(SourceFile:115)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at abt$1.tryAdvance(SourceFile:31)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at cwc.a(SourceFile:197)
	at akq.a(SourceFile:839)
	at akq.a(SourceFile:828)
	at akq.e(SourceFile:782)
	at akq.a(SourceFile:546)
	at akz.e(SourceFile:2012)
	at akz.k(SourceFile:2360)
	at ala.k(SourceFile:490)
	at ako.k(SourceFile:159)
	at atc.k(SourceFile:44)
	at akz.h(SourceFile:2173)
	at ala.h(SourceFile:295)
	at xd.a(SourceFile:602)
	at xd$$Lambda$2480/202947181.accept(Unknown Source)
	at bjw.a(SourceFile:534)
	at xd.a(SourceFile:398)
	at net.minecraft.server.MinecraftServer.b(SourceFile:854)
	at wd.b(SourceFile:347)
	at net.minecraft.server.MinecraftServer.a(SourceFile:793)
	at net.minecraft.server.MinecraftServer.run(SourceFile:655)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at bjk$1.tryAdvance(SourceFile:115)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at abt$1.tryAdvance(SourceFile:31)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at cwc.a(SourceFile:197)
	at akq.a(SourceFile:839)
	at akq.a(SourceFile:828)
	at akq.e(SourceFile:782)
	at akq.a(SourceFile:546)
	at akz.e(SourceFile:2012)
	at akz.k(SourceFile:2360)
	at ala.k(SourceFile:490)
	at ako.k(SourceFile:159)
	at atc.k(SourceFile:44)
	at akz.h(SourceFile:2173)
	at ala.h(SourceFile:295)
	at xd.a(SourceFile:602)
	at xd$$Lambda$2480/202947181.accept(Unknown Source)
	at bjw.a(SourceFile:534)
	at xd.a(SourceFile:398)
	at net.minecraft.server.MinecraftServer.b(SourceFile:854)
	at wd.b(SourceFile:347)
	at net.minecraft.server.MinecraftServer.a(SourceFile:793)

-- Thread Dump --
Details:
	Threads: "Server Watchdog" Id=27 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at wg.run(SourceFile:45)
	at java.lang.Thread.run(Thread.java:748)

"RCON Listener #1" Id=26 RUNNABLE (in native)
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:560)
	at java.net.ServerSocket.accept(ServerSocket.java:528)
	at aaf.run(SourceFile:58)
	at java.lang.Thread.run(Thread.java:748)

"Netty Epoll Server IO #1" Id=25 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:114)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)

"poi IO worker" Id=24 WAITING on java.lang.String@1a8c8b36
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.lang.String@1a8c8b36
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at caz.c(SourceFile:124)
	at caz.d(SourceFile:134)
	at caz$$Lambda$2097/1012524754.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"chunk IO worker" Id=23 WAITING on java.lang.String@1a8c8b36
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.lang.String@1a8c8b36
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at caz.c(SourceFile:124)
	at caz.d(SourceFile:134)
	at caz$$Lambda$2097/1012524754.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"poi IO worker" Id=22 WAITING on java.lang.String@1a8c8b36
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.lang.String@1a8c8b36
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at caz.c(SourceFile:124)
	at caz.d(SourceFile:134)
	at caz$$Lambda$2097/1012524754.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"chunk IO worker" Id=21 WAITING on java.lang.String@1a8c8b36
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.lang.String@1a8c8b36
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at caz.c(SourceFile:124)
	at caz.d(SourceFile:134)
	at caz$$Lambda$2097/1012524754.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"poi IO worker" Id=20 WAITING on java.lang.String@1a8c8b36
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.lang.String@1a8c8b36
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at caz.c(SourceFile:124)
	at caz.d(SourceFile:134)
	at caz$$Lambda$2097/1012524754.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"chunk IO worker" Id=19 WAITING on java.lang.String@1a8c8b36
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.lang.String@1a8c8b36
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at caz.c(SourceFile:124)
	at caz.d(SourceFile:134)
	at caz$$Lambda$2097/1012524754.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"Netty Epoll Server IO #0" Id=18 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:114)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)

"ObjectCleanerThread" Id=17 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@1efb3883
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@1efb3883
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

"DestroyJavaVM" Id=15 RUNNABLE

"Server thread" Id=12 RUNNABLE
	at bjk$1.tryAdvance(SourceFile:115)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at abt$1.tryAdvance(SourceFile:31)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at cwc.a(SourceFile:197)
	at akq.a(SourceFile:839)
	at akq.a(SourceFile:828)
	at akq.e(SourceFile:782)
	...

"Server Infinisleeper" Id=13 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at wd$1.run(SourceFile:94)

"Snooper Timer" Id=11 WAITING on java.util.TaskQueue@7a095ccb
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@7a095ccb
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	at java.util.TimerThread.run(Timer.java:505)

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@56044de9
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@56044de9
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@282fb924
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@282fb924
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

Stacktrace:
	at wg.run(SourceFile:61)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.15.0-96-generic
	Java Version: 1.8.0_242, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1312936168 bytes (1252 MB) / 2027421696 bytes (1933 MB) up to 3040870400 bytes (2900 MB)
	CPUs: 1
	JVM Flags: 2 total; -Xmx3000M -Xms2000M
	Player Count: 2 / 20; [xe['PikaPunchMan'/267, l='world', x=-113.90, y=65.25, z=-216.10], xe['blupancake'/982, l='world', x=-107.40, y=62.46, z=-207.88]]
	Data Packs: vanilla
	Is Modded: Unknown (can't tell)
	Type: Dedicated Server (map_server.txt)
### Plugin list:
None, vanilla server install

### Actions to reproduce (if known):
Unknown
### Paper build number:
1.15.2

**Comment by Spottedleaf** [comment]
you're running vanilla

**Comment by aikar** [comment]
not sure how you ended up on our project for vanilla issues, but please report to mojang
