### ISSUE TITLE
Server Crash - feature placement?

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#3208]
Paper 208, mostly vanilla

`---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 4/22/20, 7:47 PM
Description: Exception in server tick loop

java.util.concurrent.CompletionException: net.minecraft.server.v1_15_R1.ReportedException: Feature placement
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58)
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(ThreadedMailbox.java:78)
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(ThreadedMailbox.java:120)
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(ThreadedMailbox.java:86)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: net.minecraft.server.v1_15_R1.ReportedException: Feature placement
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$23(PlayerChunkMap.java:846)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$b$25(PlayerChunkMap.java:831)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	... 11 more
Caused by: java.lang.ThreadDeath
	at java.base/java.lang.Thread.stop(Thread.java:943)
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:733)
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752)
	at net.minecraft.server.v1_15_R1.MinecraftServer.close(MinecraftServer.java:712)
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:155)`

**Comment by aikar** [comment]
Ugh, wish futures wouldn't catch death....

Technically your server crashed by watchdog before this occurred. This was watchdog trying to stop the main thread so it can save data for you and shutdown gracefully, but that got interrupted.

Check your logs above that.

Ideally that wouldn't of happened though, will see if we can prevent crash reports from kicking in there too on watchdog.

**Comment by hurrgurl** [comment]
Time out before the crash https://pastebin.com/4FqhL2e3

**Comment by aikar** [comment]
Ty, does appear to be a valid CraftBukkit bug. Will try to fix soon.

**Comment by hurrgurl** [comment]
Thanks a lot!
