### ISSUE TITLE
Failed to verify username!

### ISSUE THREAD

**Issue by mateulusz** [PaperMC/Paper#3213]
Hi,
after daily restart I have problem with paperspigot + waterfall.
I didn't change anything, it appeared after restart.

I have online-mode: false in bungee config and server.properties, because its non premium server.
If user connect directly to paperspigot can join. If by bungee, he can't.
`Disconnecting com.mojang.authlib.GameProfile@44d991cb[id=<uuid>,name=<name>,properties={},legacy=false] (/89.39.171.208:35097): Failed to verify username!`
`
[16:54:52 WARN]: Exception verifying <name>
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[hypersi_skyblock.jar:git-Paper-1555]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186) ~[hypersi_skyblock.jar:git-Paper-1555]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:35) ~[hypersi_skyblock.jar:git-Paper-1555]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) ~[hypersi_skyblock.jar:git-Paper-1555]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:28) ~[hypersi_skyblock.jar:git-Paper-1555]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:177) ~[hypersi_skyblock.jar:git-Paper-1555]
        at net.minecraft.server.v1_12_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:300) ~[hypersi_skyblock.jar:git-Paper-1555]
        at net.minecraft.server.v1_12_R1.LoginListener$2.run(LoginListener.java:206) ~[hypersi_skyblock.jar:git-Paper-1555]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
`

**Comment by electronicboy** [comment]
1.12.2 is no longer supported; probs mojang API issues too...

**Comment by xDefcon** [comment]
@electronicboy the same happens in the latest build (211) even with online-mode set to false. Why is Paper contacting the Mojang's API server even when online-mode is set to false?

**Comment by electronicboy** [comment]
Because your server is misconfigured, spigot makes bungee mode == online
mode, there is an option I paper.yml to break that assumption

**Comment by aikar** [comment]
do you have bungeecord: true in paper.yml? if you do, turn that off.
