### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Gorderok** [PaperMC/Paper#3214]
Paper 208

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 4/24/20, 1:19 AM
Description: Writing into PalettedContainer from multiple threads (other thread: name: Craft Scheduler Thread - 6700, class: class java.lang.Thread)

java.lang.IllegalStateException
    at net.minecraft.server.v1_15_R1.DataPaletteBlock.a(DataPaletteBlock.java:37)
    at net.minecraft.server.v1_15_R1.DataPaletteBlock.setBlock(DataPaletteBlock.java:144)
    at net.minecraft.server.v1_15_R1.ChunkSection.setType(ChunkSection.java:68)
    at net.minecraft.server.v1_15_R1.ChunkSection.setType(ChunkSection.java:61)
    at net.minecraft.server.v1_15_R1.Chunk.setType(Chunk.java:480)
    at net.minecraft.server.v1_15_R1.World.setTypeAndData(World.java:364)
    at net.minecraft.server.v1_15_R1.BlockObserver.tick(BlockObserver.java:39)
    at net.minecraft.server.v1_15_R1.IBlockData.a(IBlockData.java:210)
    at net.minecraft.server.v1_15_R1.WorldServer.b(WorldServer.java:764)
    at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:296)
    at net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:46)
    at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:428)
    at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1294)
    at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1152)
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by electronicboy** [comment]
`Description: Writing into PalettedContainer from multiple threads (other thread: name: Craft Scheduler Thread - 6700, class: class java.lang.Thread)`

Replicate without plugins

**Comment by Gorderok** [comment]
The crash occurred after 23 hours of use with an average of 40 players. How do you want me to try to reproduce the crash with 0 plugins for 23 hours and 40 players?

**Comment by wizjany** [comment]
How do you want the paper team to "fix" something which is being caused by plugins doing dumb things?

**Comment by aikar** [comment]
Well the error says 100% it's a plugin's fault. 

If it happens gain, see if the stack trace shows CraftTask instead (opposite side of check) and see which plugin is doing it.

Ultimately, its a plugin accessing the world async, and we know it's not a paper issue.

**Comment by electronicboy** [comment]
There is logic to try to dump all the threads, hit or miss as to if it actually catches the offender, but would be in the log files if it managed to hit it

**Comment by Gorderok** [comment]
Here is the full crash report, we think a problem with bm-local
https://pastebin.com/GaDMAt9z

**Comment by electronicboy** [comment]
```
Craft Scheduler Thread - 6700:
    at java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.6/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
    at java.base@11.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
    at java.base@11.0.6/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
    at java.base@11.0.6/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
    at app//net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:442)
    at xuan.cat.NMSCatAPI.code.v1_15_R1.world.CodeExtendWorld.getChunk(CodeExtendWorld.java:63)
    at xuan.cat.ExtendViewDistance.b.a(Unknown Source)
    at xuan.cat.ExtendViewDistance.Index.a(Unknown Source)
    at xuan.cat.ExtendViewDistance.Index$$Lambda$3848/0x00007fa11537b040.run(Unknown Source)
    at app//org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
```
ExtendViewDistance

**Comment by Gorderok** [comment]
Indeed ! Thank you, it will be difficult to do without :(
