### ISSUE TITLE
MoCreatures' is breaking my server

### ISSUE THREAD

**Issue by Deducts** [PaperMC/Paper#3215]
Had an error with my modded server after removing MoCreatures' - Is there any way to fix this?

```
24.04 21:17:56 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 79160ms behind, skipping 1583 tick(s)
24.04 21:18:00 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 3788ms behind, skipping 75 tick(s)
24.04 21:18:40 [Server] Server thread/ERROR "Silently" catching entity tracking error.
24.04 21:18:40 [Server] INFO net.minecraft.util.ReportedException: Adding entity to track
24.04 21:18:40 [Server] INFO at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
24.04 21:18:40 [Server] INFO at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) [EntityRegistry.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) [mn.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
24.04 21:18:40 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
24.04 21:18:40 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
24.04 21:18:40 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
24.04 21:18:40 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
24.04 21:18:40 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.SpawnerAnimals.func_151350_a(SpawnerAnimals.java:32) [aho.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:100) [aho.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161) [mt.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
24.04 21:18:40 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
24.04 21:18:40 [Server] INFO Caused by: java.lang.IllegalStateException: Entity is already tracked!
24.04 21:18:40 [Server] INFO at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
24.04 21:18:40 [Server] INFO ... 24 more
24.04 21:19:41 [Server] Server thread/ERROR "Silently" catching entity tracking error.
24.04 21:19:41 [Server] INFO net.minecraft.util.ReportedException: Adding entity to track
24.04 21:19:41 [Server] INFO at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
24.04 21:19:41 [Server] INFO at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) [EntityRegistry.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) [mn.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
24.04 21:19:41 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
24.04 21:19:41 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
24.04 21:19:41 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
24.04 21:19:41 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
24.04 21:19:41 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313) [mt.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) [mt.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
24.04 21:19:41 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
24.04 21:19:41 [Server] INFO Caused by: java.lang.IllegalStateException: Entity is already tracked!
24.04 21:19:41 [Server] INFO at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
24.04 21:19:41 [Server] INFO ... 23 more
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Mole
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Crocodile
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Crocodile
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Goat
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Deer
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Goat
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Bird
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Bunny
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.KomodoDragon
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Bird
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Deer
24.04 21:20:01 [Server] Server thread/WARN Skipping Entity with id MoCreatures.Bunny
24.04 21:24:13 [Disconnect] User ghostwalker13 has disconnected, reason: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
24.04 21:24:14 [Server] Server thread/INFO ghostwalker13 left the game
24.04 21:24:14 [Disconnect] User JerryEgg has disconnected, reason: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
24.04 21:24:14 [Server] Server thread/INFO JerryEgg left the game
24.04 21:24:14 [Disconnect] User SupremeEdgeBoy has disconnected, reason: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
24.04 21:24:14 [Server] Server thread/INFO SupremeEdgeBoy left the game
```

**Comment by electronicboy** [comment]
nothing to do with paper, I'd suggest speaking to the mod authors
