### ISSUE TITLE
26 ram and when i pre generating world i got this error and server shutdown

### ISSUE THREAD

**Issue by a7ssan** [PaperMC/Paper#3224]
[04:27:53 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:world - chunkAwait} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[BeeSpigot.jar:git-Purpur-d02efdf]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[BeeSpigot.jar:git-Purpur-d02efdf]
        at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[BeeSpigot.jar:git-Purpur-d02efdf]
        at co.aikar.timings.TimingHandler.close(TimingHandler.java:203) ~[BeeSpigot.jar:git-Purpur-d02efdf]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:88) ~[BeeSpigot.jar:git-Purpur-d02efdf]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[BeeSpigot.jar:git-Purpur-d02efdf]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1275) ~[BeeSpigot.jar:git-Purpur-d02efdf]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:467) ~[BeeSpigot.jar:git-Purpur-d02efdf]        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1193) ~[BeeSpigot.jar:git-Purpur-d02efdf]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:980) ~[BeeSpigot.jar:git-Purpur-d02efdf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

Discord: Hassan™#1178
### Paper build number:
git-Purpur-d02efdf (MC: 1.15.2)

**Comment by MiniDigger** [comment]
> Paper build number:
> git-Purpur-d02efdf (MC: 1.15.2)
> ~[BeeSpigot.jar:git-Purpur-d02efdf

Either reproduce using paper or report to purpur/whatever beespigot is

Edit: it's a 25usd mcm version, lmao.
Imagine paying for free and open source software
