### ISSUE TITLE
Illegal PlayerChunkMap::addEntity for world world2: EntityPlayer

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#3227]
### Link/paste of stack trace
```
[18:50:45] [Server thread/WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world2: EntityPlayer['Ezredes'/10306809, uuid='db038dea-0c6b-31f8-bd04-e3dee5c388a2', l='world2', x=-8606.45, y=86.00, z=2055.30, cx=-538, cz=128, tl=866098, v=false, d=false](Ezredes at -8606.45387916525,86.0,2055.300000011921)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1561)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:244)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.lambda$a$0(PlayerList.java:181)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$getChunkFutureAsynchronously$3(ChunkProviderServer.java:183)
[18:50:45] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
[18:50:45] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
[18:50:45] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:999)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1045)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:484)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:325)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:270)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.getType(World.java:649)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:84)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityPlayer.tick(EntityPlayer.java:378)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:794)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.a(World.java:863)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:516)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1293)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1151)
[18:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
[18:50:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[18:50:45] [Server thread/INFO]: Ezredes[/IP address:43984] logged in with entity id 10306809 at ([world2]-8606.45387916525, 86.0, 2055.300000011921)
[18:50:45] [Server thread/INFO]: [+] Ezredes

```

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
Plugins (104): AdminVedelem, antiRedstoneClock, ArmorStandEditor, AsyncWorldEdit, BetterGUI, ChangeSkin, ChatControl, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CombatLogX, CommandHook, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, DisablePistonFarming, Duels, DyedBackpacks, EnderContainers, EntityDetection, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, ExtraToolsPlugin, GPAccruals*, GriefPrevention, GriefPreventionFlags, HeadDatabase*, HideAndSeek, HolographicDisplays, HonapStaffja, HotbarPets, HungerGames, Kemkedes, Kezdes, LibsDisguises, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, OpenInv, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, Shopkeepers, SignEdit, sleep-most*, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunPomaFix, SpleefPlusPlus, StaffChat, StaffTime, TimeIsMoney*, TitleManager, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, VillagerOptimiser, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Sometimes when player join.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-212 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by perseus5** [comment]
#3111

**Comment by aikar** [comment]
Is there more above in the log? seems like something else may of occurred before this.

**Comment by andris155** [comment]
`[18:50:44] [User Authenticator #222/INFO]: UUID of player Ezredes is db038dea-0c6b-31f8-bd04-e3dee5c388a2`

**Comment by aikar** [comment]
Did they get teleported or something?

Were they dead?

Please try without EntityTrackerFixer

This is different than what's seen before - but it makes zero sense the player would be removed from the world during this process where this is triggering.

Feels like some plugin is doing something naughty and removed the player from the world.

I can move this line down farther though after they are forced back in.

**Comment by andris155** [comment]
They did nothing. This error is written when the player join.

**Comment by aikar** [comment]
can you try without that plugin. I really don't understand why people use that plugin.

I'm running 9k entities here with 20 TPS.

**Comment by andris155** [comment]
Okay, thanks!
