### ISSUE TITLE
Server Crash while attempting to run on latest Paper Build (225)

### ISSUE THREAD

**Issue by moxvallix** [PaperMC/Paper#3233]
Console gave this error, then exited, after updating to Paper build 225

java.lang.NumberFormatException: For input string: "2020-04-27T07:35:38Z"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.bukkit.craftbukkit.Main.main(Main.java:216)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:54)

**Comment by aikar** [comment]
fixed in 226
