### ISSUE TITLE
Does not block Illegal Packet

### ISSUE THREAD

**Issue by LemonCaramel** [PaperMC/Paper#3256]
I have asked the Discord channel several times and I am writing an issue because there is no answer.

I am not good at English and used a translator.

I'm not sure on a server that can only access 1.15.2, but it's a very serious problem for a 1.12.2-1.15.2 server.

When using "LogSpammer Hack"(1.12.2 hack) in paper 1.15.2, the player join, server shutdown(/stop command) and other(...) do not work with the error below.

If I have to turn off the server, I have to click the console window close button to force it to shut down.

I think this is a very serious problem. I hope it will be resolved quickly.

### Steps/models to reproduce:
[Youtube Video](https://youtu.be/ed938k9kFDA)

### Plugin list: 
ProtocolSupport, ProtocolSupportLegacyChest

### Error log:

> [23:48:42 FATAL]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: 209770667
        at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[?:1.8.0_241]
        at net.minecraft.server.v1_15_R1.NonNullList.get(SourceFile:46) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.PlayerInventory.c(PlayerInventory.java:135) ~[patched_1.15.2.jar:git-Paper-227]        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:686) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.PacketPlayInPickItem.a(SourceFile:30) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.PacketPlayInPickItem.a(SourceFile:8) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035) ~[patched_1.15.2.jar:git-Paper-227]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-227]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[23:48:43 INFO]: caramel_moe lost connection: Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(4) exceeds writerIndex(0): AbstractPooledDerivedByteBuf$PooledNonRetainedSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 496))

**Comment by Proximyst** [comment]
Try to reproduce without a plugin doing borderline criminal acts on the packets.

**Comment by aikar** [comment]
This is now fixed in latest build.

The wording had me going back and forth on was this for 1.12 or not...

**Comment by tomassurna** [comment]
I've run into an issue on the latest build where you will be kicked if the item you are trying to pick is not on the Hotbar. Even if the item is in your inventory. 

**Reproduce:**
Have an item in your inventory but not Hotbar and try to middle mouse click to hot select item.

**Comment by rekryt** [comment]
> [16:57:58] [Server thread/WARN]: BanaMan tried to set an invalid carried item
[16:57:58] [Server thread/INFO]: BanaMan lost connection: Invalid hotbar selection (Hacking?)
[16:57:58] [Server thread/WARN]: handleDisconnection() called twice

mouse3 click on empty slot (with select block that have in inventory) server kick player

**Comment by Subilan** [comment]
> > [16:57:58] [Server thread/WARN]: BanaMan tried to set an invalid carried item
> > [16:57:58] [Server thread/INFO]: BanaMan lost connection: Invalid hotbar selection (Hacking?)
> > [16:57:58] [Server thread/WARN]: handleDisconnection() called twice
> 
> mouse3 click on empty slot (with select block that have in inventory) server kick player

Same here too.

**Comment by HexedHero** [comment]
Same issue here with normal building when getting new item stacks from inventory into hotbar

**Comment by aikar** [comment]
This is fixed in latest build
