### ISSUE TITLE
Silently catching entity tracking error

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#328]
Paper dev 776

```
[16:49:46] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_10_R1.ReportedException: Adding entity to track
    at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:141) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.EntityTracker.track(EntityTracker.java:80) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.WorldManager.a(WorldManager.java:19) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.World.b(World.java:1112) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.WorldServer.b(WorldServer.java:1137) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.World.addEntity(World.java:1105) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:523) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:519) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:530) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.MobSpawnerAbstract.c(MobSpawnerAbstract.java:111) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.TileEntityMobSpawner.E_(SourceFile:90) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1589) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:635) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:865) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.jar:git-Paper-776]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.jar:git-Paper-776]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
    at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:108) ~[patched_1.10.jar:git-Paper-776]
    ... 17 more
```

**Comment by aikar** [comment]
was this on a players login?

I'm tracking that down on my own server too.

**Comment by mibby** [comment]
Perhaps, but I'm not sure. I've had the error occur numerous times since 1.10's release and do have players come and go frequently. I haven't experienced the error any time recently, but I'll look into what is happening if/when it occurs again.

**Comment by aikar** [comment]
I'm actually seeing this mob spawner one too. Not sure about it yet.

**Comment by aikar** [comment]
this issue is actually deeper - its caused by spider jockeys it seems... maybe...

its actually double adding to the world (look at your logs and you should see Double Chunk Add warning above it)

Its caused by an entity spawning with passengers and the passenger is getting added twice.

I still gotta dig deeper.
