### ISSUE TITLE
Server freezed

### ISSUE THREAD

**Issue by Kesims** [PaperMC/Paper#3310]
Server freezed.

[14:20:30] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:bskyblock_world - Sync Chunk Load} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.15.2.jar:git-Paper-258]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.15.2.jar:git-Paper-258]
	at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[patched_1.15.2.jar:git-Paper-258]
	at co.aikar.timings.TimingHandler.close(TimingHandler.java:203) ~[patched_1.15.2.jar:git-Paper-258]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[patched_1.15.2.jar:git-Paper-258]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:746) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:671) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2128) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.PacketPlayInClientCommand.a(SourceFile:30) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1220) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-258]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[14:20:30] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to BentoBox v1.12.0
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:853) [?:1.8.0_252]
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:733) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752) ~[patched_1.15.2.jar:git-Paper-258]
	at net.minecraft.server.v1_15_R1.MinecraftServer.close(MinecraftServer.java:712) ~[patched_1.15.2.jar:git-Paper-258]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:156) ~[patched_1.15.2.jar:git-Paper-258]

**Comment by electronicboy** [comment]
Your server took too long to tick, for support with this, please use the discord
