### ISSUE TITLE
Doing the command "/playsound <ANY sound> master" without player name generates a stacktrace

### ISSUE THREAD

**Issue by TheShwarma** [PaperMC/Paper#3315]
### Link/paste of stack trace

   [14:17:29 WARN]: Unknown CommandBlock failed to handle command
java.lang.ArrayIndexOutOfBoundsException: 2
        at net.minecraft.server.v1_12_R1.CommandPlaySound.execute(SourceFile:48) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:109) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:38) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_241]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

### Plugin list:
BattleRoyalMode, CrackShot, WorldEdit

### Actions to reproduce (if known):
Simply do "/playsound <ANY sound> master" without specifying a target. It SHOULD say "player not found" or something like that. Instead it does an ArrayOutOfBounds
I personally tried it on entity.cat.hurt.

### Paper build number:
[14:22:57 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[14:22:57 INFO]: You are running the latest version

**Comment by zachbr** [comment]
We do not support 1.12.2 any longer.

**Comment by TheShwarma** [comment]
@zachbr ok, but maybe this error happens on 1.15.2 too? You should check anyway, it'll take like 5 seconds.

**Comment by zachbr** [comment]
Doesn't occur. Even if it did, we wouldn't fix it for 1.12.2 so it wouldn't help you much.

**Comment by TheShwarma** [comment]
Alright, thank you anyway
