### ISSUE TITLE
Non [a-z0-9/._-] character in path of location

### ISSUE THREAD

**Issue by Megaro96** [PaperMC/Paper#3326]
### What behaviour is expected:
unloading a world while server is on

### What behaviour is observed:
world won't be unloaded due to an exeption

### Steps/models to reproduce:
using the plugin "WorldSystem": unloading worlds did work with Paper build 262 but not with 264. Reverting back to 262 fixes the issue.

### Paper build number:
Build with exeption: 264
Without exeption: 262

### Exeption:
`[10:38:51] [Server thread/INFO]: Schoky_ issued server command: /ws leave
[10:38:51] [Server thread/INFO]: /ws
[10:38:58] [Server thread/INFO]: Schoky_ lost connection: Disconnected
[10:39:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (ID54-f879b748-cf26-4b4d-95a4-90c383883f6a): All chunks are saved
[10:39:12] [Server thread/WARN]: [WorldSystem] Task #767 for WorldSystem v2.4.8.2 generated an exception
net.minecraft.server.v1_15_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:ID54-f879b748-cf26-4b4d-95a4-90c383883f6a
	at net.minecraft.server.v1_15_R1.MinecraftKey.<init>(MinecraftKey.java:29) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftKey.<init>(MinecraftKey.java:34) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.DimensionManager.lambda$unregister$0(DimensionManager.java:27) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.DimensionManager.unregister(DimensionManager.java:25) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.unloadWorld(CraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.Bukkit.unloadWorld(Bukkit.java:570) ~[patched_1.15.2.jar:git-Paper-264]
	at de.butzlabben.world.wrapper.SystemWorld.lambda$unloadLater$3(SystemWorld.java:260) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1252) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-264]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[10:41:58] [User Authenticator #6/INFO]: UUID of player Schoky_ is f879b748-cf26-4b4d-95a4-90c383883f6a
[10:41:58] [Server thread/INFO]: Schoky_[/92.209.56.182:49662] logged in with entity id 11715 at ([Lobby]0.5, 67.0, 0.5)
[10:42:00] [Craft Scheduler Thread - 81/INFO]: [MysqlPlayerDataBridge] Saving online players data...
[10:42:00] [Craft Scheduler Thread - 81/INFO]: [MysqlPlayerDataBridge] Data save complete for 1 players in 29 ms.
[10:42:06] [Server thread/INFO]: Schoky_ issued server command: /ws home
[10:42:06] [Server thread/INFO]: /ws
[10:43:00] [Server thread/INFO]: » Empty teams: 0. Purge: true.
[10:43:00] [Server thread/WARN]: The save for world located at ./ID10-c518cbd0-669c-49c5-83b7-40081a0827c2 is being accessed from another location, aborting
[10:43:00] [Server thread/WARN]: The save for world located at ./ID54-f879b748-cf26-4b4d-95a4-90c383883f6a is being accessed from another location, aborting
[10:43:00] [Server thread/WARN]: The save for world located at ./ID54-f879b748-cf26-4b4d-95a4-90c383883f6a is being accessed from another location, aborting`

**Comment by Phoenix616** [comment]
The error stems from [this line](https://github.com/PaperMC/Paper/commit/a71a4ec21544217cdb82f10a54647fc4a873c0a5#diff-2a3eaf58c832b3ad52a0aa25db06be8bR118) in the world unloading patch, it has to also convert to lowercase like the method before.
