### ISSUE TITLE
Failed to schedule load callback for chunk - CompletionException

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#3330]
### Link/paste of stack trace

Crash log
https://paste.ubuntu.com/p/wkdSVcfcfd/

```
[23:22:01] [Server-Worker-5/ERROR]: Requested chunk : -14 13
[23:22:01] [Server-Worker-5/ERROR]: Region bounds : -13 13 | -13 13
[23:22:01] [Server-Worker-5/FATAL]: Failed to schedule load callback for chunk [-13, 13]
java.util.concurrent.CompletionException: net.minecraft.server.v1_15_R1.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(ThreadedMailbox.java:78) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(ThreadedMailbox.java:120) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(ThreadedMailbox.java:86) ~[patched_1.15.2.jar:git-Paper-270]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: net.minecraft.server.v1_15_R1.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$29(PlayerChunkMap.java:1041) ~[patched_1.15.2.jar:git-Paper-270]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$b$31(PlayerChunkMap.java:1026) ~[patched_1.15.2.jar:git-Paper-270]
	... 12 more
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | -14 13
	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:98) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:66) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getType(RegionLimitedWorldAccess.java:133) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ICollisionAccess.getBlockCollision(ICollisionAccess.java:119) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ICollisionAccess.a(ICollisionAccess.java:47) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ICollisionAccess.a(ICollisionAccess.java:34) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.SpawnerCreature.a(SpawnerCreature.java:239) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkProviderGenerate.addMobs(ChunkProviderGenerate.java:39) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkStatus.lambda$static$12(ChunkStatus.java:77) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkStatus$d.doWork(ChunkStatus.java:243) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkStatus.a(ChunkStatus.java:187) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$29(PlayerChunkMap.java:1028) ~[patched_1.15.2.jar:git-Paper-270]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$b$31(PlayerChunkMap.java:1026) ~[patched_1.15.2.jar:git-Paper-270]
	... 12 more
[23:22:01] [Server-Worker-5/WARN]: java.util.concurrent.CompletionException: net.minecraft.server.v1_15_R1.ReportedException: Exception generating new chunk
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(ThreadedMailbox.java:78)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(ThreadedMailbox.java:120)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(ThreadedMailbox.java:86)
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[23:22:01] [Server-Worker-5/WARN]: Caused by: net.minecraft.server.v1_15_R1.ReportedException: Exception generating new chunk
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$29(PlayerChunkMap.java:1041)
[23:22:01] [Server-Worker-5/WARN]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$b$31(PlayerChunkMap.java:1026)
[23:22:01] [Server-Worker-5/WARN]: 	... 12 more
[23:22:01] [Server-Worker-5/WARN]: Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | -14 13
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:98)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:66)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getType(RegionLimitedWorldAccess.java:133)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ICollisionAccess.getBlockCollision(ICollisionAccess.java:119)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ICollisionAccess.a(ICollisionAccess.java:47)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ICollisionAccess.a(ICollisionAccess.java:34)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.SpawnerCreature.a(SpawnerCreature.java:239)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ChunkProviderGenerate.addMobs(ChunkProviderGenerate.java:39)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ChunkStatus.lambda$static$12(ChunkStatus.java:77)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ChunkStatus$d.doWork(ChunkStatus.java:243)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.ChunkStatus.a(ChunkStatus.java:187)
[23:22:01] [Server-Worker-5/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$29(PlayerChunkMap.java:1028)
[23:22:01] [Server-Worker-5/WARN]: 	... 14 more
[23:22:01] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_15_R1.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1329) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-270]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | -14 13
	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:98) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:66) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getType(RegionLimitedWorldAccess.java:133) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ICollisionAccess.getBlockCollision(ICollisionAccess.java:119) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ICollisionAccess.a(ICollisionAccess.java:47) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ICollisionAccess.a(ICollisionAccess.java:34) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.SpawnerCreature.a(SpawnerCreature.java:239) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkProviderGenerate.addMobs(ChunkProviderGenerate.java:39) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkStatus.lambda$static$12(ChunkStatus.java:77) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkStatus$d.doWork(ChunkStatus.java:243) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkStatus.a(ChunkStatus.java:187) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$29(PlayerChunkMap.java:1028) ~[patched_1.15.2.jar:git-Paper-270]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$b$31(PlayerChunkMap.java:1026) ~[patched_1.15.2.jar:git-Paper-270]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(ThreadedMailbox.java:78) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(ThreadedMailbox.java:120) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(ThreadedMailbox.java:86) ~[patched_1.15.2.jar:git-Paper-270]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[23:22:01] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.RuntimeException: We are asking a region for a chunk out of bound | -14 13
	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:98) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:66) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.RegionLimitedWorldAccess.getType(RegionLimitedWorldAccess.java:133) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ICollisionAccess.getBlockCollision(ICollisionAccess.java:119) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ICollisionAccess.a(ICollisionAccess.java:47) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ICollisionAccess.a(ICollisionAccess.java:34) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.SpawnerCreature.a(SpawnerCreature.java:239) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkProviderGenerate.addMobs(ChunkProviderGenerate.java:39) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkStatus.lambda$static$12(ChunkStatus.java:77) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkStatus$d.doWork(ChunkStatus.java:243) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ChunkStatus.a(ChunkStatus.java:187) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$29(PlayerChunkMap.java:1028) ~[patched_1.15.2.jar:git-Paper-270]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$b$31(PlayerChunkMap.java:1026) ~[patched_1.15.2.jar:git-Paper-270]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(ThreadedMailbox.java:78) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(ThreadedMailbox.java:120) ~[patched_1.15.2.jar:git-Paper-270]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(ThreadedMailbox.java:86) ~[patched_1.15.2.jar:git-Paper-270]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
```
### Plugin list:
None.

### Actions to reproduce (if known):
Fresh new server instance, no worlds or configs existing.

### Paper build number:
Paper dev 270

**Comment by aikar** [comment]
271 just fixed this
