### ISSUE TITLE
Essentials backup halts restart/stop

### ISSUE THREAD

**Issue by ice-fly** [PaperMC/Paper#3337]
### What behaviour is expected:
Server handles the exception where essentials was backing up during shutdown/restart

### What behaviour is observed:
```
[05:52:29 INFO]: Flushing Chunk IO
[05:52:29 INFO]: Closing Thread Pool
[05:52:29 INFO]: Closing Server
[05:53:55 ERROR]: [DiscordSRV] Could not send message to channel TC:server(690273186977153191): The Requester has been shutdown! No new requests can be requested!
[06:07:27 INFO]: [Essentials] World Backup - Code 0
[06:08:54 INFO]: [Essentials] Nether Backup - Code 1
[06:12:33 INFO]: [Essentials] End Backup - Code 1
[06:12:33 INFO]: [Essentials] Attempting to remove old files..
[06:12:51 INFO]: [Essentials]
[06:12:51 INFO]: [Essentials] Deleting "C:\Users\MDL-DOWNSTAIRS\Downloads\Minecraft\logs\2020-04-27-7.log.gz"
[06:12:51 INFO]: [Essentials] Deleting "C:\Users\MDL-DOWNSTAIRS\Downloads\Minecraft\logs\2020-04-28-1.log.gz"
[06:12:51 INFO]: [Essentials] Deleting "C:\Users\MDL-DOWNSTAIRS\Downloads\Minecraft\logs\2020-04-28-2.log.gz"
[06:12:51 INFO]: [Essentials] Deleting "C:\Users\MDL-DOWNSTAIRS\Downloads\Minecraft\logs\2020-04-28-3.log.gz"
[06:12:51 INFO]: [Essentials] Deleting "C:\Users\MDL-DOWNSTAIRS\Downloads\Minecraft\logs\2020-04-28-4.log.gz"
[06:12:52 INFO]: [Essentials] Deleting "C:\Users\MDL-DOWNSTAIRS\Downloads\Minecraft\logs\2020-04-28-5.log.gz"
[06:12:52 WARN]: [Essentials] Plugin Essentials v2.17.2.0 generated an exception while executing task 63981
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:527) ~[patched_1.15.2.jar:git-Paper-271]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:205) ~[patched_1.15.2.jar:git-Paper-271]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:196) ~[patched_1.15.2.jar:git-Paper-271]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:191) ~[patched_1.15.2.jar:git-Paper-271]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:155) ~[patched_1.15.2.jar:git-Paper-271]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:124) ~[patched_1.15.2.jar:git-Paper-271]                                                                                                at com.earth2me.essentials.Essentials.scheduleSyncDelayedTask(Essentials.java:813) ~[?:?]                               at com.earth2me.essentials.Backup$1.run(Backup.java:122) ~[?:?]                                                         at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-271]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-271]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-271]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```
Doesn't shutdown, needs prodded

### Steps/models to reproduce:

1. Start latest paper with EssentialsX installed
2. Configure essentials to call backup script with /restart
3. Use a backup script with slowed file i/o (IPG with robocopy)
4. Attempt shutdown with backup running

### Plugin list:
`AsyncWorldEdit, AutoRestart*, ChopTree2, DiscordSRV, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GriefPrevention, LuckPerms, MineableSpawners, OreAnnouncer, ProtocolLib, Vault, WorldEdit, WorldGuard`

### Paper build number:
`paper-271`

### Anything else:
Thanks for your hard work!

**Comment by aikar** [comment]
This is a bug in that plugin. Report it to them, nothing to do with Paper, but it did expose the fact shutdowns could benefit from the same system reload has for waiting for async tasks and nagging if they are still running, so I added that.
