### ISSUE TITLE
Console Error - EntityDeathEvent

### ISSUE THREAD

**Issue by ForestCrazy** [PaperMC/Paper#3340]
### What behaviour is expected:
Console Error - EntityDeathEvent

### What behaviour is observed:

> [10:40:24] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MythicMobs v4.9.0-3255
java.lang.NullPointerException: null
	at io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitItemStack.getAmount(BukkitItemStack.java:195) ~[?:?]
	at io.lumine.xikage.mythicmobs.drops.droppables.ItemDrop.getDrop(ItemDrop.java:76) ~[?:?]
	at io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:421) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1059.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-273]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-273]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-273]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-273]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:767) ~[patched_1.15.2.jar:git-Paper-273]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1382) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1113) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1706) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2088) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1047) ~[patched_1.15.2.jar:git-Paper-273]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-273]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

### Paper build number:
paper-273

### Anything else:
Thanks for your hard work!

**Comment by kickash32** [comment]
Hard to say if its the API's fault or MythicMobs, ask them to confirm this.

**Comment by Lufrut** [comment]
i have same error but with another plugin ultimate stacker
 `[11:40:55] [Server thread/ERROR]: Could not pass event EntityDeathEvent to UltimateStacker v1.11.12
java.lang.NullPointerException: null
	at com.songoda.ultimatestacker.lootables.loot.LootManager.runLoot(LootManager.java:36) ~[?:?]
	at com.songoda.ultimatestacker.lootables.LootablesManager.runLoot(LootablesManager.java:80) ~[?:?]
	at com.songoda.ultimatestacker.lootables.LootablesManager.getDrops(LootablesManager.java:47) ~[?:?]
	at com.songoda.ultimatestacker.listeners.DeathListeners.onEntityDeath(DeathListeners.java:46) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor258.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-280]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-280]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-280]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-280]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:767) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1113) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1706) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2088) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1094) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1087) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1221) ~[patched_1.15.2.jar:git-Paper-280]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:959) ~[patched_1.15.2.jar:git-Paper-280]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`
