### ISSUE TITLE
Cannot login into the server when last logout was in the Nether

### ISSUE THREAD

**Issue by SentinelCraft** [PaperMC/Paper#3355]
### What behaviour is expected:
Expectations: Logging into the server when my last logout was in the Nether and proceed to play.

### What behaviour is observed:
[09:34:01] [Server thread/INFO]: migas94 logged in with entity id 270405 at ([Horizon_nether]0.5, 64.0, 5.5)
[09:34:01] [Server thread/INFO]: migas94 joined the server!
[09:34:01] [Netty Epoll Server IO #3/ERROR]: java.lang.NullPointerException
[09:34:01] [Netty Epoll Server IO #3/WARN]: java.lang.NullPointerException
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayOutRespawn.b(SourceFile:46)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_15_R1.PacketEncoder.encode(PacketEncoder.java:42)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_15_R1.PacketEncoder.encode(PacketEncoder.java:12)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.util.PipelineUtil.callEncode(PipelineUtil.java:71)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:50)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:160)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_15_R1.NetworkManager.lambda$b$4(NetworkManager.java:266)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[09:34:01] [Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:34:01] [Server thread/INFO]: migas94 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[09:34:01] [Server thread/INFO]: migas94 left the server.

### Steps/models to reproduce:
Minecraft Launcher, Version 1.15.2. Log out in the Nether - Try to login back into the server in the same location where you logged out. You will get kicked and console will show up the message above.

### Plugin list:
14:44:27 CONSOLE: [INFO] Plugins (53): AuthMe, BanManager*, BattleArena, BattleTracker, BentoBox, BukkitCompat*, Citizens, dynmap*, Dynmap-Towny, Elevators, EnjinMinecraftPlugin, EntityTrackerFixer, Essentials, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, HolographicDisplays, JDynmapGriefPrevention*, LibsDisguises, LogBlock, LuckPerms, LWC, mcMMO, MineableSpawners, Minepacks, MobArena, Multiverse-Core, Multiverse-NetherPortals, MultiWorldMoney*, MyCommand, OpenInv, OtherDrops, PerWorldInventory, PlaceholderAPI*, PortableCraftingInvs, ProtocolLib, PvPManager, Quests, RFChairs, SkinsRestorer, Statz, TAB, Towny, TownyChat, TreasureChestReloaded, Vault, ViaVersion*, Votifier, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV2*

### Paper build number:
Paper version git-Paper-282 (MC: 1.15.2)

### Anything else:
This was not happening in older versions. I reverted to build 260 and works fine.

Thank you.

**Comment by aikar** [comment]
There is some plugin issue going on here. I reviewed the code and there is absolutely no way paper is sending a null dimension manager.
No one else is having this issue either. So your going to need to first rule out ViaVersion. If it works without Via, report it to Via.

if it still happens without Via, try cutitng out any plugins dealing with login/spawn/respawn and find which one and report it to them.

Paper is not sending this packet.
