### ISSUE TITLE
Paper 304 time out, LightEngineGraph?

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#3410]
`[23:45:01] [Server thread/ERROR]: Remove callback for map threw exception 
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 513
	at it.unimi.dsi.fastutil.longs.Long2ByteOpenHashMap.rehash(Long2ByteOpenHashMap.java:1138) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.LightEngineGraph$2.rehash(SourceFile:61) ~[patched_1.15.2.jar:git-Paper-301]
	at it.unimi.dsi.fastutil.longs.Long2ByteOpenHashMap.insert(Long2ByteOpenHashMap.java:267) ~[patched_1.15.2.jar:git-Paper-301]
	at it.unimi.dsi.fastutil.longs.Long2ByteOpenHashMap.put(Long2ByteOpenHashMap.java:275) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.LightEngineGraph.a(SourceFile:125) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.LightEngineGraph.a(SourceFile:167) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.LightEngineGraph.a(SourceFile:137) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.ChunkMap.b(SourceFile:69) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.removeTicket(ChunkMapDistance.java:165) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.removeTicketAtLevel(ChunkMapDistance.java:229) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.removeTicketAtLevel(ChunkProviderServer.java:432) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$new$5(PlayerChunkMap.java:373) ~[patched_1.15.2.jar:git-Paper-301]
	at com.destroystokyo.paper.util.misc.AreaMap.removeObjectFrom(AreaMap.java:262) ~[patched_1.15.2.jar:git-Paper-301]
	at com.destroystokyo.paper.util.misc.AreaMap.removeObject(AreaMap.java:291) ~[patched_1.15.2.jar:git-Paper-301]
	at com.destroystokyo.paper.util.misc.AreaMap.remove(AreaMap.java:151) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.removePlayerFromDistanceMaps(PlayerChunkMap.java:209) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1703) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.removeEntity(PlayerChunkMap.java:1898) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.removeEntity(ChunkProviderServer.java:971) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.WorldServer.unregisterEntity(WorldServer.java:1422) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.WorldServer.removeEntity(WorldServer.java:1519) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.WorldServer.removePlayer(WorldServer.java:1535) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:678) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:800) ~[patched_1.15.2.jar:git-Paper-301]
	at com.playerteleport.player.MPlayer.teleportPlayer(MPlayer.java:251) ~[?:?]
	at com.playerteleport.player.MPlayer.teleport(MPlayer.java:200) ~[?:?]
	at com.playerteleport.teleport.TeleportController.lambda$teleport$2(TeleportController.java:188) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-301]
	at java.lang.Thread.run(Thread.java:835) [?:?]`

Crash log
https://pastebin.com/zSrTQZ5q

**Comment by TNTUP** [comment]
Confirmin this issue on 301, 

https://hasteb.in/apiyilas.bash

EDIT: looks like caused by EssentialsX: https://hasteb.in/hecemoku.bash (PaperLib?)

**Comment by aikar** [comment]
Please try build 305, which contains a huge amount of improvements. Please open a NEW issue if a new issue is found.

**Comment by TNTUP** [comment]
Thanks Aikar! Yar the best' :aikar:
