### ISSUE TITLE
server crashes

### ISSUE THREAD

**Issue by Mineinjava** [PaperMC/Paper#3415]
### Link/paste of stack trace
```
    [09:18:10 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:world - Sync Chunk Load} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.15.2.jar:git-Paper-304]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.15.2.jar:git-Paper-304]
	at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[patched_1.15.2.jar:git-Paper-304]
	at co.aikar.timings.TimingHandler.close(TimingHandler.java:203) ~[patched_1.15.2.jar:git-Paper-304]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[patched_1.15.2.jar:git-Paper-304]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-304]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:723) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-304]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Plugin list:

none

### Actions to reproduce (if known):

run command /forceload

### Paper build number:

#304, 7e1525e

**Comment by aikar** [comment]
you left out the real error above it. what is the error before this?

**Comment by Athemis** [comment]
Might this be related to #3416? At least the log from the OP and my own have a similar error inside...

**Comment by aikar** [comment]
Please try build 305, which contains a huge amount of improvements. Please open a NEW issue if a new issue is found.
