### ISSUE TITLE
The stacktrace is displayed when the command block is opened.

### ISSUE THREAD

**Issue by noonmaru** [PaperMC/Paper#3441]
### Link/paste of stack trace

```log
[04:20:50 FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: No such argument 'targets' exists on this command
        at com.mojang.brigadier.context.CommandContext.getArgument(CommandContext.java:85) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.ArgumentEntity.c(ArgumentEntity.java:57) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.ArgumentEntity.b(ArgumentEntity.java:47) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.CommandTag.a(SourceFile:45) ~[patched_1.15.2.jar:git-Paper-300]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.15.2.jar:git-Paper-300]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.15.2.jar:git-Paper-300]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.PlayerConnection.lambda$a$4(PlayerConnection.java:584) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-300]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Paper-300]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

### Plugin list:
* AutoSave
* CPCameraStudio-1.0
* PermissionsEx-1.23.4
* VoxelSniper-5.171.0
* worldedit-bukkit-7.1.0

### Paper build number:
**313**

### The command:
`/execute if entity @a[name=Notch] run tag @a[name=!Notch] remove admin`

**Comment by MWHunter** [comment]
I am also getting the same error on a vanilla server.  This is not a paper issue and either the command is wrong or there is a bug in vanilla and a mojang jira bug report should be filed.
