### ISSUE TITLE
Chunk Generation (WorldBorder)

### ISSUE THREAD

**Issue by Lusteroth** [PaperMC/Paper#3451]
### Link/paste of stack trace
```
[03:02:26 ERROR]: [global] TIMING_STACK_CORRUPTION - Look above this for any errors and report this to Paper unless it has a plugin in the stack trace (TimingIdentifier{id=Minecraft:farmwelt_nether - World Save - Chunks} did not stopTiming)
[03:02:26 WARN]: [WorldBorder] Task #3 for WorldBorder v1.9.10 (beta) generated an exception
java.lang.NullPointerException: null
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_242]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_242]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.save(PlayerChunkMap.java:834) ~[patched_1.15.2.jar:git-Paper-318]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.save(ChunkProviderServer.java:681) ~[patched_1.15.2.jar:git-Paper-318]
at net.minecraft.server.v1_15_R1.WorldServer.save(WorldServer.java:1036) ~[patched_1.15.2.jar:git-Paper-318]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.save(CraftWorld.java:1404) ~[patched_1.15.2.jar:git-Paper-318]
at com.wimbli.WorldBorder.WorldFillTask.reportProgress(WorldFillTask.java:526) ~[?:?]
at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:282) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-318]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-318]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-318]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-318]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-318]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-318]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

https://pastebin.com/4H9QWs8u

### Plugin list:
WorldBorder, spark

### Actions to reproduce (if known):

Looks like chunk generation with WorldBorder is broken. WorldBorder doesn't work anymore after a while.

### Paper build number: Paper-318

```
[08:32:13 INFO]: This server is running Paper version git-Paper-318 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[08:32:13 INFO]: Checking version, please wait...
[08:32:13 INFO]: Previous version: git-Paper-313 (MC: 1.15.2)
[08:32:13 INFO]: You are running the latest version
```

**Comment by Lusteroth** [comment]
The issue still persits in Paper-321:

```
[01:32:50 INFO]: [WorldBorder] world: farmwelt_nether padding: 208 repeats: 500 ticks: 1
[01:32:50 INFO]: WorldBorder map generation task for world "farmwelt_nether" started.
[01:32:54 WARN]: [WorldBorder] Task #3 for WorldBorder v1.9.10 (beta) generated an exception
java.lang.IllegalStateException: Chunk not there when requested: Unloaded [-6, -26] Unloaded [0, -18] Unloaded [-8, -18]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$getChunkAt$11(ChunkProviderServer.java:502) ~[patched_1.15.2.jar:git-Paper-321]
at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:498) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:332) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:277) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.WorldServer.setForceLoaded(WorldServer.java:1950) ~[patched_1.15.2.jar:git-Paper-321]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.setChunkForceLoaded(CraftWorld.java:698) ~[patched_1.15.2.jar:git-Paper-321]
at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:318) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-321]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-321]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by Brokkonaut** [comment]
I had the same exception with chunk saving as in the first post using Paper-321 and doing a WorldBorder fill. The crash happened after some hours of creating chunks.

Plugins: WorldBorder (nothing else)
