### ISSUE TITLE
IllegalArgumentException on save: Name and ID cannot both be blank

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#347]
Paper 791

Got this exception every time the world auto-saved.

```
[16:20:13] [Server thread/INFO]: Saving...
[16:20:13] [Server thread/WARN]: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[16:20:13] [Server thread/WARN]:    at com.mojang.authlib.GameProfile.<init>(GameProfile.java:25)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.UserCache.a(UserCache.java:90)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.UserCache.getProfile(UserCache.java:158)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Village.b(Village.java:444)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.PersistentVillage.b(PersistentVillage.java:256)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.PersistentCollection.a(PersistentCollection.java:99)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.PersistentCollection.a(PersistentCollection.java:84)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1083)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.WorldServer.save(WorldServer.java:1024)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.CommandSaveAll.execute(SourceFile:36)
[16:20:13] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:122)
[16:20:13] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:44)
[16:20:13] [Server thread/WARN]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[16:20:13] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665)
[16:20:13] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:628)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:441)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730)
[16:20:13] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629)
[16:20:13] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[16:20:13] [Server thread/INFO]: Saved the world
```

**Comment by Puremin0rez** [comment]
Have you tried deleting (but first backing up) your usercache.json file in the root of the server directory? This file can sometimes become corrupt for some people and cause errors similar to this.

**Comment by mibby** [comment]
The error stopped occurring today after the server restarted. So no need to delete the json file. Just thought I'd report the error anyways in case there was a way to prevent saving UUIDs that are blank.

**Comment by zedwick** [comment]
I am also getting this, but my usercache.json appears to have no errors in its structure. Had seen it just after updating to 1.10, but like above it seemed to go away after a reboot or maybe just when a certain player was not online. It returned today.

**Comment by Tych0n** [comment]
@mibby & @zedwick people say this is [old bug](https://bugs.mojang.com/browse/MC-50221), check the workaround in the link if it is still actual for you.
