### ISSUE TITLE
Exception loading entity java.lang.AssertionError: TRAP

### ISSUE THREAD

**Issue by jokbon** [PaperMC/Paper#3472]
### Link/paste of stack trace
https://timings.aikar.co/?id=375f90807a8a4731a6ec9aec9c606ac0

[22:04:31 INFO]: jokbon issued server command: /home
[22:05:28 INFO]: jokbon issued server command: /spawn
[22:05:34 INFO]: jokbon issued server command: /timings report
[22:05:34 INFO]: Please wait at least 3 minutes before generating a Timings report. Unlike Timings v1, v2 benefits from longer timings and is not as useful with short timings. (95 seconds)
[22:10:25 WARN]: Exception loading entity:
net.minecraft.server.v1_15_R1.ReportedException: Loading entity NBT
        at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1857) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.EntityTypes.lambda$a$1(EntityTypes.java:305) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.EntityTypes$$Lambda$3731/0000000000000000.accept(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_15_R1.SystemUtils.a(SystemUtils.java:231) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:302) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.EntityTypes.b(EntityTypes.java:346) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:327) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:606) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.ChunkRegionLoader.lambda$createLoadEntitiesConsumer$6(ChunkRegionLoader.java:296) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.ChunkRegionLoader$$Lambda$3433/0000000000000000.accept(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_15_R1.Chunk.addEntities(Chunk.java:826) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$41(PlayerChunkMap.java:1221) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap$$Lambda$3536/0000000000000000.apply(Unknown Source) ~[?:?]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[patched_1.15.2.jar:git-Paper-321]
        at com.mojang.datafixers.util.Either$$Lambda$3033/0000000000000000.apply(Unknown Source) ~[?:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.15.2.jar:git-Paper-321]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$c$42(PlayerChunkMap.java:1204) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap$$Lambda$3533/0000000000000000.apply(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_252]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_252]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_252]
        at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter$$Lambda$3684/0000000000000000.run(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1070) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1117) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:616) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Paper-321]
        at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
Caused by: java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_15_R1.ItemStack.checkEmpty(ItemStack.java:114) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.ItemStack.setCount(ItemStack.java:912) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.EntityEnderSignal.c(SourceFile:46) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.EntityEnderSignal$$Lambda$4681/0000000000000000.accept(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_15_R1.SystemUtils.a(SystemUtils.java:194) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.EntityEnderSignal.b(SourceFile:46) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.EntityEnderSignal.a(SourceFile:194) ~[patched_1.15.2.jar:git-Paper-321]
        at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1770) ~[patched_1.15.2.jar:git-Paper-321]
        ... 34 more
[22:10:48 INFO]: jokbon issued server command: /timings report
[22:10:48 INFO]: Preparing Timings Report...
[22:10:48 INFO]: View Timings Report: https://timings.aikar.co/?id=744e9cbaac284b80848fe0df90c10d97

### Plugin list:
![UntitAGSEGgled](https://user-images.githubusercontent.com/29400409/83299309-99a95d00-a1fe-11ea-9ea6-fbe070569def.png)

### Actions to reproduce (if known):
I was just flying around to test if no tick viev distance got any good impact in performance.

### Paper build number:
321

**Comment by jokbon** [comment]
also had wrongly pointing spawn which i reported in other isusue fill

**Comment by A248** [comment]
Might be a plugin. See possible:
https://hub.spigotmc.org/jira/browse/SPIGOT-3020
https://stackoverflow.com/questions/41235190/java-trap-assertion-error

Although the stacktrace may not mention which plugin specifically, it seems that, in the case of other users, this was caused by a plugin setting invalid state, namely that the player's tool is AIR. When this state is read, later, the error is thrown.

**Comment by electronicboy** [comment]
invalid entity in the world, the server should recover from this on its own, but, this is well documented as occurring in a few places since 1.14 or even 1.13+, not something we can really fix
