### ISSUE TITLE
Skyfactory 4 client cant join to the paper server

### ISSUE THREAD

**Issue by jonathanmizzi18** [PaperMC/Paper#3487]
### What behaviour is expected:
TO connect to my bungee server using skyfactory 4 forge server, other forge servers work fine
### What behaviour is observed:
Invalid payload Register! message and this using the skuyfactory 4 client

[14:01:58 ERROR]: Couldn't register custom payload
java.lang.IllegalStateException: Cannot register channel 'l:crafttweaker'. Too many channels registered!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:518) ~[patched_1.15.2.jar:git-Paper-333]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1478) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2693) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1164) ~[patched_1.15.2.jar:git-Paper-333]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-333]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

### Steps/models to reproduce:
Use travertine and run a paper server and a forge server using skyfactory 4 and try to connect with the skyfactory 4 client

### Plugin list:
 AutoSave, BagOfGold, Citizens, ClearChat*, ClearLag, CommandButtons, CoreProtect, dynmap*, EasyPrefix, Essentials, GriefPrevention, HolographicDisplays, LibsDisguises, LuckPerms, LWC, mcMMO, MicroJump*, MobHunting, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, NametagEdit*, NBTEditor, OpenInv, PlaceholderAPI, PlugMan, ProtocolLib, ProtocolSupport, ServerInfo*, SimpleSignEditor, SkinsRestorer, Vault, ViaVersion*, WorldEdit, WorldGuard, XConomy*
### Paper build number:
[14:09:09 INFO]: Previous version: git-Paper-331 (MC: 1.15.2)
[14:09:09 INFO]: You are running the latest version

**Comment by mikroskeem** [comment]
Add `-Dpaper.disableChannelLimit=true`  to JVM flags

**Comment by jonathanmizzi18** [comment]
how do I do that please?

**Comment by MiniDigger** [comment]
Pls consider joining the discord for such support. If you explain how you start your server, ppl there will be able to help you adding that argument to your start command.

**Comment by jonathanmizzi18** [comment]
java -Xmx8G -Xms6G -jar paper.jar nogui
PAUSE

Edit: I joined discord but I still need to wait 10 min

**Comment by electronicboy** [comment]
You add the `-D...` before the -jar flag
