### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by crazykidney** [PaperMC/Paper#3494]
### Link/paste of stack trace
https://pastebin.com/8VNkgdEg

### Plugin list:
none

### Actions to reproduce (if known):
Not sure what caused it. Something to do with nether portals?

### Paper build number:
328

**Comment by electronicboy** [comment]
Need the *full* crash report and the lines from before that.

**Comment by crazykidney** [comment]
> 
> 
> Need the _full_ crash report and the lines from before that.

Sorry, got build version wrong, it was actually 328.

This is the only thing I have in logs besides what's already included.

```
Failed to handle packet
net.minecraft.server.v1_15_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:534) ~[patched_1.15.2.jar:git-Paper-328]
	at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:159) ~[patched_1.15.2.jar:git-Paper-328]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:343) ~[patched_1.15.2.jar:git-Paper-328]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:140) ~[patched_1.15.2.jar:git-Paper-328]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1344) ~[patched_1.15.2.jar:git-Paper-328]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-328]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-328]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-328]
	at java.lang.Thread.run(Thread.java:835) [?:?]

```

**Comment by juls0730** [comment]
does this always happen or was it only a one time thing?

**Comment by juls0730** [comment]
does this always happen or was it only a one time thing?
(changed my name)

**Comment by electronicboy** [comment]
issue is inactive and still no full logs, if it was portals, probably fixed with recent improvements...
