### ISSUE TITLE
is the ender dragon okay?

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#3522]
I'm not sure what it's doing there, but the dragon might be unhappy.

`[16:17:06] [Server thread/WARN]: java.lang.IllegalArgumentException: bound must be positive
[16:17:06] [Server thread/WARN]: 	at java.base/java.util.Random.nextInt(Random.java:388)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DragonControllerHold.j(SourceFile:70)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DragonControllerHold.c(SourceFile:37)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityEnderDragon.movementTick(EntityEnderDragon.java:180)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2396)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:807)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.a(World.java:879)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:532)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1319)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173)
[16:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962)
[16:17:06] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:835)`

**Comment by aikar** [comment]
well that dragon is probably not ok. It's probably very dead.

Looks like a vanilla bug as this file is not changed by either us or spigot.

But doesn't make sense on what could be erroring there.

**Comment by BigBadE** [comment]
Seems to be because EnderDragonBattle believes that there are -3 ender crystals alive (from field h in EnderDragonBattle)
The only other call to random with a variable bound is with an absolute value + 2, so that can't be negative unless something is really wrong.

Actually, h appears to be the total amount of crystals and is never decremented. 
Either the integer cache got corrupted somehow, or some plugin/patch modifies the field because h is either 0 or the returned value of Collection#size (so always >=0).
