### ISSUE TITLE
Logback logger not working with PaperMC, but works fine with SpigotMC

### ISSUE THREAD

**Issue by CC007** [PaperMC/Paper#3532]
### What behaviour is expected:
The ability to use the Logback logger in my plugin

### What behaviour is observed:
```
[22:02:27 ERROR]: Error occurred while enabling HeadsPluginAPI v2.0.0-rc1 (Is it up to date?)
java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.apache.logging.slf4j.Log4jLoggerFactory loaded from file:/D:/local/servers/minecraft/vanilla%20papermc%201.15.2/cache/patched_1.15.2.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.apache.logging.slf4j.Log4jLoggerFactory
        at org.springframework.util.Assert.instanceCheckFailed(Assert.java:696) ~[?:?]
        at org.springframework.util.Assert.isInstanceOf(Assert.java:596) ~[?:?]
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:281) ~[?:?]
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:104) ~[?:?]
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:239) ~[?:?]
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:220) ~[?:?]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[?:?]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[?:?]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[?:?]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[?:?]
        at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:70) ~[?:?]
        at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:47) ~[?:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[?:?]
        at com.github.cc007.headsplugin.HeadsPlugin.onEnable(HeadsPlugin.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-345]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-345]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-345]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-345]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-345]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-345]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-345]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:907) ~[patched_1.15.2.jar:git-Paper-345]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

### Steps/models to reproduce:
 - Get paper-345.jar and add these release candidate HeadsPluginAPI and HeadsInventory plugins: https://we.tl/t-OsmLMXbviJ
 - accept the eula and start the server.

### Plugin list:
 - HeadsPluginAPI 2.0.0-rc1 (see link above)
 - HeadsInventory 1.10.0-rc1 (see link above)

### Paper build number:
345

### Anything else:
The plugins work without any issues in SpigotMC (built on 31-05-2020)

**Comment by CC007** [comment]
My plugin uses Spring Boot. It logs all Spring Boot logs to /plugins/<pluginName>/logs with a similar format to the general logs. I use logback for this (the default logger in spring-boot-starter-logging)

**Comment by aikar** [comment]
Paper Includes log4j-slf4j-impl where as Spigot doesn't.

So ultimately, this is going to be on you to figure out as I really have no idea what your code is doing and how its injecting into the logger to take it over.

But I doubt your going to be table to take over the logger factory entirely, that's not something a plugin should be able to do. 

I had never heard of this logback, but looked it up and found this:
https://stackify.com/compare-java-logging-frameworks/

Sounds like that has been replaced by log4j2 which is what minecraft already uses.

So surely there is a way for you to do this through log4j2 configuration instead of using this older system?

Ultimately, this is a Won't Fix category. @Minecrell may be able to help you do what you're wanting to do without using Spring Boot.
Recommend joining discord for any dev discussion on how to update your code.

**Comment by stephan-gh** [comment]
> Either **remove Logback** or the competing implementation (class org.apache.logging.slf4j.Log4jLoggerFactory loaded from file:/D:/local/servers/minecraft/vanilla%20papermc%201.15.2/cache/patched_1.15.2.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.apache.logging.slf4j.Log4jLoggerFactory

To me it sounds like you should just remove Logback and make Spring use slf4j somehow. That will be a much better integration with log4j2 anyway.
