### ISSUE TITLE
Paper build 344 break the RestrictedCreative plugin Asynchronous ChunkMapDistance::addTicket! error

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#3533]
### What behaviour is expected:
___What you expected to see___
RestrictedCreative database load perfectly if I started server.

### What behaviour is observed:
___What you actually saw___
RestrictedCreative database no load if I started server.
```
[23:08:54] [Craft Scheduler Thread - 31/WARN]: [RestrictedCreative] Plugin RestrictedCreative v2.3.6 generated an exception while executing task 491
java.lang.IllegalStateException: Asynchronous ChunkMapDistance::addTicket!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.addTicket(ChunkMapDistance.java:158) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.addTicket(ChunkMapDistance.java:311) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.addTicket(ChunkProviderServer.java:958) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:402) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:1016) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.Location.getChunk(Location.java:123) ~[patched_1.15.2.jar:git-Paper-345]
	at me.prunt.restrictedcreative.storage.DataHandler$2.run(DataHandler.java:529) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-345]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-345]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
RestrictedCreative plugin works perfectly on Paper build 343. The build 344 breaks this plugin.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Start server with Paper build 344 or build 345 and RestrictedCreative plugin.

### Plugin list:
___A list of your plugins___
Plugins (1): RestrictedCreative

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-345 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[23:32:03 INFO]: Checking version, please wait...
[23:32:03 INFO]: Previous version: git-Paper-343 (MC: 1.15.2)
[23:32:03 INFO]: You are running the latest version

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by iamceph** [comment]
This was mentioned in the new commit, will be probably fixed in some future time

**Comment by electronicboy** [comment]
`me.prunt.restrictedcreative.storage.DataHandler` is causing operations which could crash your server, Paper is preventing that and warning you, you should speak to the plugin author

**Comment by andris155** [comment]
This plugin never caused server crash. I have been using it for 3 years.

**Comment by andris155** [comment]
Very big thanks for this fix @aikar
