### ISSUE TITLE
ERROR and WARN in server log

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3534]
### This is the server log:
```
[16:52:25 INFO]: Starting minecraft server version 1.15.2
[16:52:25 INFO]: Loading properties
[16:52:25 ERROR]: Failed to read console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:272) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:282) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:181) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:326) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:392) ~[?:?]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:180) ~[patched_1.15.2.jar:git-Paper-347]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[patched_1.15.2.jar:git-Paper-347]
	at net.minecraft.server.v1_15_R1.DedicatedServer$2.run(DedicatedServer.java:90) ~[patched_1.15.2.jar:git-Paper-347]
	Suppressed: java.io.IOException: The handle is invalid
		at java.io.FileDescriptor.close0(Native Method) ~[?:?]
		at java.io.FileDescriptor.close(FileDescriptor.java:297) ~[?:?]
		at java.io.FileInputStream$1.close(FileInputStream.java:368) ~[?:?]
		at java.io.FileDescriptor.closeAll(FileDescriptor.java:355) ~[?:?]
		at java.io.FileInputStream.close(FileInputStream.java:366) ~[?:?]
		at java.io.BufferedInputStream.close(BufferedInputStream.java:481) ~[?:?]
		at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:391) ~[?:?]
		at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:204) ~[?:?]
		at java.io.InputStreamReader.close(InputStreamReader.java:196) ~[?:?]
		at java.io.BufferedReader.close(BufferedReader.java:528) ~[?:?]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:183) ~[patched_1.15.2.jar:git-Paper-347]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[patched_1.15.2.jar:git-Paper-347]
		at net.minecraft.server.v1_15_R1.DedicatedServer$2.run(DedicatedServer.java:90) ~[patched_1.15.2.jar:git-Paper-347]
[16:52:25 INFO]: This server is running Paper version git-Paper-347 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[16:52:25 INFO]: Debug logging is disabled
[16:52:25 INFO]: Server Ping Player Sample Count: 10
[16:52:25 INFO]: Using 16 threads for Netty based IO
[16:52:25 INFO]: Default game type: ADVENTURE
[16:52:25 INFO]: Generating keypair
[16:52:26 INFO]: Starting Minecraft server on *:25550
[16:52:26 INFO]: Using default channel type
[16:52:26 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[16:52:28 WARN]: Legacy plugin LightAPI v3.4.3 does not specify an api-version.
[16:52:28 INFO]: Loading WorldEdit v7.1.0;8e55131
[16:52:29 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@45689219]
[16:52:29 INFO]: Loading LightAPI v3.4.3
[16:52:29 INFO]: Loading ProtocolLib v4.5.1
[16:52:29 WARN]: Version (MC: 1.15.2) has not yet been tested! Proceed with caution.
[16:52:29 INFO]: Loading SuperVanish v6.1.5
[16:52:29 INFO]: Loading InteractionVisualizer v1.11.3
[16:52:29 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:52:29 INFO]: Enabling WorldEdit v7.1.0;8e55131
[16:52:29 INFO]: WEPIF: Using the Bukkit Permissions API.
[16:52:29 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_15_R2 as the Bukkit adapter
[16:52:30 INFO]: Enabling ProtocolLib v4.5.1
[16:52:30 INFO]: Started structure compiler thread.
[16:52:30 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[16:52:30 WARN]: The server will make no attempt to authenticate usernames. Beware.
[16:52:30 WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[16:52:30 WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[16:52:30 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[16:52:30 INFO]: Preparing level "world"
[16:52:30 INFO]: Reloading ResourceManager: Default, bukkit, Clear Entity Lag v2.zip, Player Health Display v5.zip
[16:52:31 INFO]: Loaded 6 recipes
[16:52:32 INFO]: Loaded 4 custom command functions
[16:52:32 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[16:52:32 INFO]: Enabling LightAPI v3.4.3*
[16:52:32 INFO]: §b[LightAPI] §r§7Loading implementation for §fPaper§r§7 server §fv1_15_R1§r§7.
[16:52:32 INFO]: Enabling SuperVanish v6.1.5
[16:52:32 INFO]: Enabling InteractionVisualizer v1.11.3
[16:52:32 INFO]: §d[InteractionVisualizer] InteractionVisualizer has hooked into SuperVanish/PremiumVanish!
[16:52:32 INFO]: §a[InteractionVisualizer] Opened Sqlite database successfully
[16:52:32 INFO]: §a[InteractionVisualizer] InteractionVisualizer has been enabled!
[16:52:32 INFO]: Starting remote control listener
[16:52:32 INFO]: RCON running on 0.0.0.0:25570
[16:52:32 INFO]: Running delayed init tasks
[16:52:32 INFO]: Done (7.146s)! For help, type "help"
[16:52:32 INFO]: Timings Reset
```
### Plugin list:
1. InteractionVisualizer-1.11.3
2. LightAPI-fork-3.4.3
3. ProtocolLib
4. SuperVanish
5. worldedit-bukkit-7.1.0

### Actions to reproduce:
Just start the server and read the "latest.log" file.

Messages _"[16:52:25 ERROR]: Failed to read console input"_ and _"[16:52:29 WARN]: Version (MC: 1.15.2) has not yet been tested! Proceed with caution."_ appear.

### Paper build number:
git-Paper-347 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT

**Comment by electronicboy** [comment]
the error on startup is generally down to OSes not providing a console, side-effect of running on windows which can't really be fixed as windows or some other OS tends to break in the most stupid of ways when we deal with this

as for your other warnings, that's your plugins

**Comment by ghost** [comment]
---This helped me---
create a RUN.bat file containing this:
@echo off

java -Xms512M -Xmx512M -jar [nameofyour.jarfile].jar
pause

**Comment by assasin541** [comment]
@electronicboy what plugins?
I'm running on linux...
