### ISSUE TITLE
Chunk Generation broken (WorldBorder)

### ISSUE THREAD

**Issue by Lusteroth** [PaperMC/Paper#3541]
### Link/paste of stack trace
```
[20:02:24 INFO]: [WorldBorder] [Fill] Saving the world to disk, just to be on the safe side. (free mem: 12914 MB)
[20:02:25 ERROR]: [global] TIMING_STACK_CORRUPTION - Look above this for any errors and report this to Paper unless it has a plugin in the stack trace (TimingIdentifier{id=Minecraft:farmwelt - World Save - Chunks} did not stopTiming)
[20:02:25 WARN]: [WorldBorder] Task #692 for WorldBorder v1.9.10 (beta) generated an exception
java.lang.NullPointerException: null
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_242]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_242]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.save(PlayerChunkMap.java:859) ~[patched_1.15.2.jar:git-Paper-348]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.save(ChunkProviderServer.java:689) ~[patched_1.15.2.jar:git-Paper-348]
at net.minecraft.server.v1_15_R1.WorldServer.save(WorldServer.java:1040) ~[patched_1.15.2.jar:git-Paper-348]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.save(CraftWorld.java:1419) ~[patched_1.15.2.jar:git-Paper-348]
at com.wimbli.WorldBorder.WorldFillTask.reportProgress(WorldFillTask.java:526) ~[?:?]
at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:282) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-348]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-348]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-348]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-348]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-348]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-348]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] 
```

https://pastebin.com/anKWk4qY

### Plugin list:
WorldBorder, spark

### Actions to reproduce (if known):

The chunk generation with WorldBorder is broken again. WorldBorder doesn't work anymore after a while. Looks like issue #3451

### Paper build number: Paper-348

```
[22:44:21 INFO]: This server is running Paper version git-Paper-348 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[22:44:21 INFO]: Checking version, please wait...
[22:44:21 INFO]: Previous version: git-Paper-347 (MC: 1.15.2)
[22:44:21 INFO]: You are running the latest version
```

**Comment by HauserGrim** [comment]
Do not use WorldBorder. He has problems working at 1.13+
Try Chunkmaster.

**Comment by Chew** [comment]
Duplicate of #3253 

As suggested by HauserGrim, consider using a more updated fork of WorldBorder, like Chunkmaster or Chunky, if you still plan on pre-generating your world. Thank you!
