### ISSUE TITLE
server crash random

### ISSUE THREAD

**Issue by jiongjionger** [PaperMC/Paper#358]
Server version : latest 1.9.4

`Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at net.minecraft.server.v1_9_R2.EntityTracker.updatePlayers(EntityTracker.java:176)
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:874)
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403)
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723)
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622)
    at java.lang.Thread.run(Unknown Source)`

Even if I delete all the plugins, the server will have a random crash. It looks like a synchronized problem.

**Comment by jiongjionger** [comment]
I change
private Set<EntityTrackerEntry> c = Sets.newtHashSet();
to
private Set<EntityTrackerEntry> c = Sets.newConcurrentHashSet();
(EntityTracker.java)

I'm testing this change.

**Comment by jiongjionger** [comment]
After the modification has been a month without a crash

**Comment by Techcable** [comment]
@jiongjionger Changing from a HashSet to a ConcurrentHashSet hides the underlying concurrency issue. You're corrupting your data instead of throwing an exception.

**Comment by jiongjionger** [comment]
@Techcable  But if you don't make any changes, the server will crash random, even if I don't install any plugins. :(
