### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DenisJ9798** [PaperMC/Paper#3608]
### Link/paste of stack trace

https://pastebin.com/g7E8qhHz
https://pastebin.com/VAbcMYTA
https://pastebin.com/G3dWSsjf

### Plugin list:
I removed all plugins, it didn't help

### Actions to reproduce (if known):
Standing still doesn't matter

### Paper build number:
paper-370

**Comment by Prof-Bloodstone** [comment]
Which log is without plugins?
The first 2 have plugins and are on old build.
The third one has a lot of plugins and doesn't have any information what version it is.

**Comment by electronicboy** [comment]
I don't really see how that could happen, the fact that you also had a segmentation fault there screams that you have JVM/OS/hardware issues...

**Comment by DenisJ9798** [comment]
> Which log is without plugins?
> The first 2 have plugins and are on old build.
> The third one has a lot of plugins and doesn't have any information what version it is.

https://pastebin.com/zaQYHNBZ

**Comment by DenisJ9798** [comment]
> I don't really see how that could happen, the fact that you also had a segmentation fault there screams that you have JVM/OS/hardware issues...

What can be problems, yesterday I installed everything on VDS according to this instruction https://codebeer.ru/ustanovka-java-8-v-debian-8-rabotayushhij-sposob/

**Comment by Jikoo** [comment]
Try running MCRegionFixer. I had a similar issue which ended up being a couple corrupt chunks and an invalid region. Paper will segfault, Spigot will crash hard. Spigot runs fine now but Paper still crashes. Started occurring after updating to Paper 212, but unfortunately I hadn't updated since 148 at the time. I wasn't about to open an issue without investing significant time (which I never ended up finding) into tracking it down, but if this is already open more info may help.

<details>
<summary>Crash 1 - NPE</summary>

```
java.lang.NullPointerException: Exception ticking world
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$tickChunks$12(ChunkProviderServer.java:857)
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:458)
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:801)
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:715)
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:435)
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1315)
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169)
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$tickChunks$12(ChunkProviderServer.java:857)
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:458)
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:801)
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:715)
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:435)
```
</details>
<details>
<summary>Crash 2 - IndexOutOfBounds</summary>

```
java.lang.ArrayIndexOutOfBoundsException: 3
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$tickChunks$12(ChunkProviderServer.java:857)
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:451)
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:801)
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:715)
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:435)
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303)
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$tickChunks$12(ChunkProviderServer.java:857)
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:451)
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:801)
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:715)
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:435)
```
</details>

Both of these traces are from Paper 261 I believe.

Edit: Should note, the original world corruption was my fault for unrelated reasons, not Paper. I have a world save that can probably reproduce this, so I'll start making time for tracing this down.

**Comment by DenisJ9798** [comment]
> Try running MCRegionFixer. I had a similar issue which ended up being a couple corrupt chunks and an invalid region. Paper will segfault, Spigot will crash hard. Spigot runs fine now but Paper still crashes. Started occurring after updating to Paper 212, but unfortunately I hadn't updated since 148 at the time. I wasn't about to open an issue without investing significant time (which I never ended up finding) into tracking it down, but if this is already open more info may help.
> 
> Crash 1 - NPE
> Crash 2 - IndexOutOfBounds
> Both of these traces are from Paper 261 I believe.
> 
> Edit: Should note, the original world corruption was my fault for unrelated reasons, not Paper. I have a world save that can probably reproduce this, so I'll start making time for tracing this down.

I installed Spigot and there were no such problems

**Comment by Proximyst** [comment]
The pastes are expired (use <https://paste.gg> in the future). I'll close with a quote of cat:

> I don't really see how that could happen, the fact that you also had a segmentation fault there screams that you have JVM/OS/hardware issues...

Please join our Discord if you need help with segmentation faults.
