### ISSUE TITLE
1.16 Joining from a deleted world

### ISSUE THREAD

**Issue by nahia95** [PaperMC/Paper#3660]
### What behaviour is expected:
When a player joins from a deleted world, it should teleport it to the spawn or some other location.

### What behaviour is observed:
When a player tries to join from a no longer existing world, the server generates an exception and cancels the connection.
`
[19:16:02] [User Authenticator #1/INFO]: UUID of player Chistian95 is 05d19879-8fa5-392f-9fbd-454cae17becc
[19:16:02] [Server thread/WARN]: Unknown respawn dimension ResourceKey[minecraft:dimension / minecraft:the_nether], defaulting to overworld
[19:16:02] [Server thread/WARN]: Failed to handle packet for /***.***.***.***:38535
java.lang.NullPointerException: null
	at net.minecraft.server.v1_16_R1.PlayerList.a(PlayerList.java:180) ~[patched_1.16.1.jar:git-Paper-10]
	at net.minecraft.server.v1_16_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.16.1.jar:git-Paper-10]
	at net.minecraft.server.v1_16_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.16.1.jar:git-Paper-10]
	at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:369) ~[patched_1.16.1.jar:git-Paper-10]
	at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-10]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.1.jar:git-Paper-10]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-10]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-10]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-10]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-10]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
`

### Steps/models to reproduce:
Set "allow-nether" to "true" in "server.properties". Go to the nether. While in the nether, stop the server and set "allow-nether" to "false". Delete the nether world folder (optional) and start the server again. Try to join the server.

### Plugin list:
none

### Paper build number:
git-Paper-10 (MC: 1.16.1)

### Anything else:
This can be really problematic with plugins like MultiVerse if you are creating and deleting worlds.
Deleting the player .dat file inside the playerdata folder "solves" the issue.

**Comment by Proximyst** [comment]
This was fixed upstream: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/33ea98fc42b85d2849346d8831b6403ac95b4baa

**Comment by nahia95** [comment]
I'm reopening it because even if there has been a commit that fixed the issue, it's still there. You can reproduce it doing the steps mentioned above.

I am using git-Paper-13 now.

`java.lang.NullPointerException: null
        at net.minecraft.server.v1_16_R1.PlayerList.a(PlayerList.java:188) ~[patched_1.16.1.jar:git-Paper-13]
        at net.minecraft.server.v1_16_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.16.1.jar:git-Paper-13]
        at net.minecraft.server.v1_16_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.16.1.jar:git-Paper-13]
        at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:369) ~[patched_1.16.1.jar:git-Paper-13]
        at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-13]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.1.jar:git-Paper-13]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-13]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-13]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-13]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-13]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by aikar** [comment]
this is now fixed in latest
