### ISSUE TITLE
Citizens NPC Item Inventory Serialization Exception

### ISSUE THREAD

**Issue by themonomers** [PaperMC/Paper#3686]
The server throws an exception when Citizens (version 2.0.27-SNAPSHOT (build 2016)) is:
1.  Auto-saving or when a
2.  'citizens save' command is manually executed:

(1) server log
[20:04:04] [Server thread/WARN]: [Citizens] Task #110 for Citizens v2.0.27-SNAPSHOT (build 2016) generated an exception
java.lang.NullPointerException: null
at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:301) ~[patched_1.16.1.jar:git-Paper-19]
at net.citizensnpcs.api.util.ItemStorage.serialiseMeta(ItemStorage.java:547) ~[?:?]
at net.citizensnpcs.api.util.ItemStorage.saveItem(ItemStorage.java:342) ~[?:?]
at net.citizensnpcs.api.trait.trait.Inventory.save(Inventory.java:154) ~[?:?]
at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:351) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:183) ~[?:?]
at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85) ~[?:?]
at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91) ~[?:?]
at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:484) ~[?:?]
at net.citizensnpcs.Citizens$4.run(Citizens.java:401) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-19]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-19]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-19]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-19]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-19]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-19]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-19]
at java.lang.Thread.run(Thread.java:834) [?:?]

(2) server log
[20:11:10] [Server thread/INFO]: Saving Citizens...
[20:11:10] [Server thread/WARN]: java.lang.NullPointerException
[20:11:10] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:301)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.api.util.ItemStorage.serialiseMeta(ItemStorage.java:547)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.api.util.ItemStorage.saveItem(ItemStorage.java:342)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.api.trait.trait.Inventory.save(Inventory.java:154)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:351)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:183)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:484)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:488)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.commands.AdminCommands.save(AdminCommands.java:64)
[20:11:10] [Server thread/WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:11:10] [Server thread/WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:11:10] [Server thread/WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:11:10] [Server thread/WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[20:11:10] [Server thread/WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[20:11:10] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:11:10] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[20:11:10] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792)
[20:11:10] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:754)
[20:11:10] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[20:11:10] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[20:11:10] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[20:11:10] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[20:11:10] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[20:11:10] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:834)

### Plugin list:
WorldBorder-v2.0.5.jar
LuckPerms-Bukkit-5.1.63.jar
Multiverse-Core-4.1.0.jar
Citizens-2.0.27-b2016.jar
Sentinel-2.1.5-SNAPSHOT-b360.jar
F3NPerm-2.4.jar

### Paper build number:
This server is running Paper version git-Paper-19 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
This is on a Paper 1.16.1 server running worlds and citizens previously running on a Paper 1.15.2 server

**Comment by themonomers** [comment]
I just deleted some of the NPCs' inventory and equipment and that seems to have prevented the exception.  I'll open the issue again if it comes up again.

**Comment by Lord-Lofi** [comment]
hey @themonomers were you able to readd the equipment after? I'm having this same issue

**Comment by themonomers** [comment]
Hi @Lord-Lofi, it's hard to tell because I wasn't sure exactly which equipment was causing the exception.  I got lazy and started deleted multiple lines instead of being more scientific about it.  It hasn't thrown that exception again but that doesn't mean it was fixed.
