### ISSUE TITLE
Empty, Invisible Chests - Failed to load data for block entity minecraft:chest

### ISSUE THREAD

**Issue by RWoof** [PaperMC/Paper#3687]
### What behaviour is expected:
Brought a 1.15.2 map into 1.16.1 on the latest paper version #19 (at this time)
When moving into chunks from the old version that haven't yet been explored in the new version, I get many errors in the log relating to chests I think. The chests in the area can be invisible and empty instead of visible and full. The error doesn't seem to appear again if I stop the server, reload and go back to the same areas however the chests are still empty (although now visible). In one example, the two chests in a jungle temple were affected.

### What behaviour is observed:
Log error (one for example):
```
[22:34:54 ERROR]: Failed to load data for block entity minecraft:chest
java.lang.NullPointerException: null
        at net.minecraft.server.v1_16_R1.GameProfileSerializer.a(SourceFile:167) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.NBTTagCompound.a(NBTTagCompound.java:145) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.NBTTagCompound.getUUID(NBTTagCompound.java:142) ~[patched_1.16.1.jar:git-Paper-19]
        at com.destroystokyo.paper.loottable.PaperLootableInventoryData.loadNbt(PaperLootableInventoryData.java:128) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.TileEntityLootable.b(TileEntityLootable.java:27) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.TileEntityChest.load(TileEntityChest.java:71) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.TileEntity.lambda$create$1(TileEntity.java:130) ~[patched_1.16.1.jar:git-Paper-19]
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_251]
        at net.minecraft.server.v1_16_R1.TileEntity.create(TileEntity.java:128) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:620) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.ChunkRegionLoader.lambda$createLoadEntitiesConsumer$6(ChunkRegionLoader.java:295) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.Chunk.addEntities(Chunk.java:830) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$null$45(PlayerChunkMap.java:1282) ~[patched_1.16.1.jar:git-Paper-19]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[patched_1.16.1.jar:git-Paper-19]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.1.jar:git-Paper-19]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$c$46(PlayerChunkMap.java:1265) ~[patched_1.16.1.jar:git-Paper-19]
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_251]
        at net.minecraft.server.v1_16_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1001) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1048) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:635) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1145) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-19]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[22:34:54 WARN]: Skipping BlockEntity with id minecraft:chest
```
### Steps/models to reproduce:
Load a 1.15.2 world with structures (may have to be player placed?) in 1.16.1 with Paper 19 and move around into those player areas that haven't been explored in 1.16.1 yet.

### Plugin list:
Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, FarmLimiter, GriefPrevention, GriefPreventionFlags, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, PlayerShopGUIPlus, SilkSpawners, Spartan, Vault, ViaBackwards, ViaVersion, VillagerOptimiser

### Paper build number:
This server is running Paper version git-Paper-19 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[22:48:36 INFO]: Checking version, please wait...
[22:49:01 INFO]: Previous version: git-Paper-372 (MC: 1.15.2)
[22:49:01 INFO]: You are running the latest version

### Anything else:
I've seen similar posts relating to signs and other things, mine seems to specifically be chests so far. I notice the error when I warp to somebody's home that hasn't been loaded yet in 1.16.1.
*Update 1* - I tried just now instead of just loading the world and jumping in, to do a --forceUpgrade on start, it's working on it so far but I've noticed errors saying "Unable to resolve blockentity" popping up for spawners and bee nests. It might be deleting those as well, I'm not sure, I haven't joined in yet to check.
*Update 2* - After the worlds finished loading I popped in to check, most chests with loot tables seem to be empty and invisible, shipwrecks, underwater ruins, other chests I generated in 1.15.2 with loot tables from Minecraft (dungeon chests, end city loot etc) are all invisible and empty. I did see one chest that was full in a shipwreck that I know I generated with commands, perhaps that one wasn't looted afterwards? Maybe it's only chests that have been looted and refilled (automatically via paper settings) that are now invisible? I checked the few spawners and bees nests I am aware of in my server and they seemed to be visible.
*Update 3* - Downloaded spigot 1.16.1 using buildtools and hopped right into the world, no issues with the chests. Spawners and beehives seemed normal. Later I tried a --forceUpgrade using spigot and it also had the error unable to resolve blockentity regarding spawners and beehives. Spawners seem to be visible as are beehives, but I couldn't find a full beehive to test if the bees have disappeared or not.

**Comment by aikar** [comment]
should be fixed build 20+ (use latest)
