### ISSUE TITLE
1.16 NPE When right click a waterlogged block with water bucket

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3694]
### What behaviour is expected:
No errors.

### What behaviour is observed:
When you right click a **waterlogged block** with a water bucket, console prints NPE Error executing task.

`[14:33:45] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:416) ~[patched_1.16.1.jar:git-Paper-21]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:405) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.ItemBucket.a(ItemBucket.java:115) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.ItemBucket.a(ItemBucket.java:98) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.ItemBucket.a(ItemBucket.java:124) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.ItemBucket.a(ItemBucket.java:72) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.ItemStack.a(ItemStack.java:340) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:412) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1522) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-21]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

### Steps/models to reproduce:
1- Switch to creative mode.
2- Place any bottom slab (for example).
3- Right click it with water bucket to make it waterlogged.
4- Repeat step 2 and see the error on the console.

### Plugin list:
None.

### Paper build number:
git-Paper-21

### Anything else:
Nothing.

**Comment by lordrius** [comment]
Fixed in build-24, thanks!
