### ISSUE TITLE
[main/FATAL]: Failed to start the minecraft server

### ISSUE THREAD

**Issue by RedTeaDev** [PaperMC/Paper#3743]
### Link/paste of stack trace
```
[00:21:52] [main/FATAL]: Failed to start the minecraft server
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:495) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:545) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:541) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:549) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.GeneratorSettings.a(SourceFile:203) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.DedicatedServerProperties.<init>(DedicatedServerProperties.java:107) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.DedicatedServerProperties.load(DedicatedServerProperties.java:112) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.DedicatedServerSettings.<init>(DedicatedServerSettings.java:17) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.Main.main(Main.java:64) [spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at org.bukkit.craftbukkit.Main.main(Main.java:202) [spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.songoda.serverjars.ServerJars.main(ServerJars.java:54) [Updater-1.0.0.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564) ~[Updater-1.0.0.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1405) ~[Updater-1.0.0.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:594) ~[Updater-1.0.0.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:426) ~[Updater-1.0.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:700) ~[Updater-1.0.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698) ~[Updater-1.0.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:894) ~[Updater-1.0.0.jar:?]
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:493) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
	... 14 more
```

### Plugin list:
none

### Actions to reproduce (if known):
force upgrade the server `java -jar paper-1.16.1.jar --forceUpgrade --nogui`
the issue fixed only if all .yml was removed

### Paper build number:
Paper 1.16.1 Build # 34

### system environment

- OS: Linux version 5.4.0-kali4-amd64 (devel@kali.org) (gcc version 9.2.1 20200203 (Debian 9.2.1-28)) #1 SMP Debian 5.4.19-1kali1 (2020-02-17)
- Java Version: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

**Comment by Prof-Bloodstone** [comment]
Please put all you `*.json` files through json linter - ops.json, whitelist.json, ...

Probably one of those got corrupted.

**Comment by SamB440** [comment]
`at com.songoda.serverjars.ServerJars.main(ServerJars.java:54) [Updater-1.0.0.jar:?]`

hmm...

`spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f`

Uhh...

**Comment by Chew** [comment]
This repository is for issues relating to Paper, not Spigot. If you have an issue with Spigot I recommend asking on their forums.

**Comment by aikar** [comment]
Please, for the love of all tacos, burritos, or any diety you wish to worship, DO NOT USE THAT WEBSITE!!!

Only download paper from our website at https://papermc.io/downloads

But to fix the issue, delete the generator-settings from server.properties

apparently mojang broke that.

**Comment by TheArcaneBrony** [comment]
no need to re-open but "do not use that website", which website?

**Comment by aikar** [comment]
server jars

**Comment by guoguoaidaogu** [comment]
I had the same problem as yours. I found it on Mojang website that they broke the 'generator-settings' option on Minecraft versions 1.13+. So maybe you should delete the option in server.properties and restart your server. 😄
