### ISSUE TITLE
Nullpointer exeption on player join

### ISSUE THREAD

**Issue by GillesVanPellicom** [PaperMC/Paper#3746]
This is not me asking for help in coding. Please read "Anything else" to understand why i posted this here.
### What behaviour is expected:
My plugin should create a player specific config using a join listener. I know this works because it did work before 1.16.1

### What behaviour is observed:
`[00:11:45 WARN]: java.lang.NullPointerException
[00:11:45 WARN]:        at me.ballistic_wombat.managers.ConfigManager.createConfig(ConfigManager.java:14)
[00:11:45 WARN]:        at me.ballistic_wombat.utils.Utils.createNewPlayerConfig(Utils.java:43)
[00:11:45 WARN]:        at me.ballistic_wombat.listeners.JoinListener.newPlayerConfig(JoinListener.java:47)
[00:11:45 WARN]:        at me.ballistic_wombat.listeners.JoinListener.onJoin(JoinListener.java:32)
[00:11:45 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor14.execute(Unknown Source)
[00:11:45 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[00:11:45 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:11:45 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:11:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.PlayerList.postChunkLoadJoin(PlayerList.java:262)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.PlayerList.lambda$null$1(PlayerList.java:209)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.tick(PlayerConnection.java:150)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:373)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[00:11:45 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[00:11:45 WARN]:        at java.lang.Thread.run(Unknown Source)
[00:11:45 ERROR]: Could not pass event PlayerJoinEvent to MysticCore v1.0.3-INDEV
java.lang.NullPointerException: null
        at me.ballistic_wombat.listeners.JoinListener.joinAnnounce(JoinListener.java:68) ~[?:?]
        at me.ballistic_wombat.listeners.JoinListener.onJoin(JoinListener.java:35) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor14.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-30]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-30]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-30]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.PlayerList.postChunkLoadJoin(PlayerList.java:262) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.PlayerList.lambda$null$1(PlayerList.java:209) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:373) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-30]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-30]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

### Steps/models to reproduce:
here is the relevant code:
This is the listener:
`    @EventHandler
    public void onJoin(PlayerJoinEvent event) throws IOException {
        event.setJoinMessage(null);
        Player player = event.getPlayer();
        //WARNING Do not place anything before the config generation without thinking as this could cause nullpointer exeptions.
        newPlayerConfig(player);
        //You can place code after this comment.

    }

    //Creates a new personal config if none exists
    private void newPlayerConfig(Player player) throws IOException {
        //Creates a new instance of the ConfigManager class
        ConfigManager cm = new ConfigManager();
        //Checks if there already is a config named with the UUID of the player in question
        if (!(cm.configExists(String.valueOf(player.getUniqueId()), "PlayerData", plugin))) {
            //If not, a new instance of the CreateNewPlayerConfig is created.
            Utils utils = new Utils();
            //And the command to create a new config for the player is given.
            utils.createNewPlayerConfig(player);
        }
    }`
And this is the config manager:
`package me.ballistic_wombat.managers;

import me.ballistic_wombat.Main;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.io.IOException;

public class ConfigManager {

    //I'm not going to bother writing what does what in this class because i'm never going to be in here anyways.
    public void createConfig(String configName, String subdirectory, Main plugin) throws IOException {
        File dir = new File(plugin.getDataFolder() + File.separator + subdirectory);
        File file = new File(dir, configName + ".yml");
        FileConfiguration config = YamlConfiguration.loadConfiguration(file);
        try {
            config.save(file);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setConfig(String YAMLlocaton, String value, String configName, String subdirectory, Main plugin) {
        File dir = new File(plugin.getDataFolder() + File.separator + subdirectory);
        File file = new File(dir, configName + ".yml");
        FileConfiguration config = YamlConfiguration.loadConfiguration(file);
        try {
            config.set(YAMLlocaton, value);
            config.save(file);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String getConfig(String YAMLlocaton, String configName, String subdirectory, Main plugin) {
        File dir = new File(plugin.getDataFolder() + File.separator + subdirectory);
        File file = new File(dir, configName + ".yml");
        FileConfiguration config = YamlConfiguration.loadConfiguration(file);
        return config.getString(YAMLlocaton);
    }

    public boolean configExists(String configName, String subdirectory, Main plugin) {
        File dir = new File(plugin.getDataFolder() + File.separator + subdirectory);
        File file = new File(dir, configName + ".yml");
        if (file.exists()) {
            return true;
        } else {
            return false;
        }
    }
}
`
### Plugin list:
My plugin, luckperms

### Paper build number:
git-Paper-34 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
I am posting this here and not for example on the spigot forums because my IDE tells me nothing has been deprecate. Also, stacktraces are usually printed in red, this one was 1/2 in yellow. Since i had never seen this before i assume this means it's not my plugin's fault. This is why i think it has to be a bug in paper or minecraft.
If this is not the case i am terribly sorry for taking up your time.

**Comment by limwa** [comment]
What is the content of line 14 in ConfigManager.java?

**Comment by GillesVanPellicom** [comment]
If you mean "File dir = new File(plugin.getDataFolder() + File.separator + subdirectory);" then it fetches directory of where the file is, so the datafolder + the pre specified sub directory.

**Comment by Proximyst** [comment]
Run this using Java 14/15EA and the flag `-XX:+ShowCodeDetailsInExceptionMessages` and you'll have this fixed in no time.

If you need further help with issues that are not inherently caused by Paper, use our Discord's channel #paper-dev.

**Comment by limwa** [comment]
I agree. Most likely, the issue is that the variable plugin is null.

**Comment by GillesVanPellicom** [comment]
I solved it. It was the most stupid mistake ever made. And how come i never knew -XX:+ShowCodeDetailsInExceptionMessages was a thing? this could have saved me hours...
Thanks for helping.
