### ISSUE TITLE
Can't call a event

### ISSUE THREAD

**Issue by alexisvisco** [PaperMC/Paper#377]
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-36]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-36]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-PaperSpigot-36]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:300) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:185) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:192) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:789) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-36]
Caused by: java.lang.NullPointerException
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[spigot.jar:git-PaperSpigot-36]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) ~[spigot.jar:git-PaperSpigot-36]
        at fr.kwizzy.hcfclasses.event.custom.ArmorListener.onJoin(ArmorListener.java:68) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-PaperSpigot-36]
        ... 14 more

**Comment by zachbr** [comment]
You are running 1.7 and are way off in unsupported land. We do not provide support for 1.7 any longer. It is up to you to maintain and/or modify it as you wish.

**Comment by kamcio96** [comment]
Btw, plugin error
