### ISSUE TITLE
Exception: Attempted to place a tile entity where there was no entity tile!

### ISSUE THREAD

**Issue by Vilican** [PaperMC/Paper#380]
# Crash, Stacktrace
### Link/paste of stack trace

```
12:19:02 [INFO] Preparing start region for level 6 (Seed: 202961)
12:19:02 [WARN] com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_10_R1.TileEntityChest@305cbecc) at -294,56,458 (STONE) where there was no entity tile!
12:19:02 Chunk coordinates: -304,448
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:782)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:755)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:427)
12:19:02 [WARN]     at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
12:19:02 [WARN]     at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
12:19:02 [WARN]     at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
12:19:02 [WARN]     at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
12:19:02 [WARN]     at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.lambda$syncChunkLoad$0(ChunkIOExecutor.java:18)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:55)
12:19:02 [WARN]     at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:157)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:136)
12:19:02 [WARN]     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.createWorld(CraftServer.java:968)
12:19:02 [WARN]     at org.bukkit.Bukkit.createWorld(Bukkit.java:485)
12:19:02 [WARN]     at multiworld.data.WorldManager.loadWorld(WorldManager.java:347)
12:19:02 [WARN]     at multiworld.data.WorldManager.loadWorlds(WorldManager.java:658)
12:19:02 [WARN]     at multiworld.data.DataHandler.load(DataHandler.java:242)
12:19:02 [WARN]     at multiworld.data.DataHandler.<init>(DataHandler.java:61)
12:19:02 [WARN]     at multiworld.MultiWorldPlugin.onEnable(MultiWorldPlugin.java:256)
12:19:02 [WARN]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
12:19:02 [WARN]     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
12:19:02 [WARN]     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
12:19:02 [WARN]     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358)
12:19:02 [WARN]     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:409)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:374)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:328)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275)
12:19:02 [WARN]     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:575)
12:19:02 [WARN]     at java.lang.Thread.run(Thread.java:745)
```
### Plugin list:

```
Plugins (50): SecretDoors, NTApi, Staff, SuperHub, Websend, OneWayBlocks, MultiWorld, SkinsRestorer, SuperTrails, uCommands, ChatMoney, VIPSlots, AntiCursePro, ParticleLIB, MaintenanceMode, AFK, SuperEffects, UserCache, LoginSecurity, PacketListenerApi, AdvancedBan, ProtocolLib, AdvancedPortals, AutoRespawnPlus, eZProtector, FastAsyncWorldEdit, QueuedCommands, OpGuard, PinPlease, PermissionsEx, TimeIsMoney, Vault, MassiveCore, Pl3xMOTD, PerWorldInventory, PlayerPoints, ASkyBlock, BossShop, ChatManager, WorldEdit, TreasureChest, Citizens, Sentinel, ColorMe, WorldGuard, CompatNoCheatPlus, NoCheatPlus, CraftBook, WorldGuardFix, MyPet
```
### Actions to reproduce (if known):

Just starting my server. Appears every start.
### Paper build number:

```
This server is running Paper version git-Paper-824 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
```

**Comment by zachbr** [comment]
Always on the same map? Always the same few places or one place? Sounds like a map issue.

The server is trying to create a chest tile entity at that location but all it sees there when it goes to place is a stone block. This can be caused by a plugin or general map corruption. Not a ton to go off, pretty general issue.

**Comment by aikar** [comment]
Well, this is for sure a case of a corrupted chunk file, but it may be a good idea for us to add "recovery" for this, as this is a recoverable issue with worse case of a single TE being lost.

But how this could of happened is odd, did you mess with chunks in an external editor?

**Comment by Vilican** [comment]
Yes, always on the same map and the same place.
And yes, this is externally downloaded map done with external editor. However, this message has never showed before.

**Comment by mibby** [comment]
I get this error as well when worldediting with fastasyncworldedit. Removing some buildings that contain tile entities cause the error to spew out every time the chunk is loaded. Even with FAWE removed. Easily reproducible by pasting a schematic and then undoing the paste.

Adding a form of recovery or a type of validation check to see if there should be a tile entity present would be nice. At least to avoid errors and to properly remove / not look for the entities in areas that aren't suppose to have it anymore :) 

http://paste.ubuntu.com/23073982/
http://paste.ubuntu.com/23073979/

```
[10:56:49] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_10_R1.TileEntityChest@603e536f) at 28035,81,15911 (AIR) where there was no entity tile!
Chunk coordinates: 28032,15904
[10:56:49] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:782)
[10:56:49] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:755)
[10:56:49] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:427)
[10:56:49] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
[10:56:49] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
[10:56:49] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[10:56:49] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[10:56:49] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[10:56:49] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:807)
[10:56:49] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[10:56:49] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[10:56:49] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[10:56:49] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mibby** [comment]
Still occurring for me randomly as of Paper dev 845. :( 

http://paste.ubuntu.com/23123428/

```
[16:49:05] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_10_R1.TileEntityChest@53a80b13) at 12714,67,19116 (AIR) where there was no entity tile!
Chunk coordinates: 12704,19104
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:782)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:755)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:425)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:807)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[16:49:05] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[16:49:05] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_10_R1.TileEntityChest@22863f63) at 12715,67,19115 (AIR) where there was no entity tile!
Chunk coordinates: 12704,19104
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:782)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:755)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:425)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[16:49:05] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:807)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[16:49:05] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[16:49:05] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
```
