### ISSUE TITLE
Server shuts down after initial startup, then hangs.

### ISSUE THREAD

**Issue by spsquared** [PaperMC/Paper#3809]
I would run the startup script, allocating the memory and running the jarfile
The server should start, and regularly report tick times.

However, it finds validation errors with the datapacks. From there, it spits nonsense, then stops the server. It saves the world, flushes the chunk IO, and closes the thread pool. At last it says closing server. Then hangs for a long time, ramping up CPU usage. I have to kill the program every time.

I used Build #68, with tweaked server.properties
`#Minecraft server properties
#Sun Jul 05 09:35:15 EDT 2020
spawn-protection=0
max-tick-time=60000
query.port=25565
generator-settings=
sync-chunk-writes=true
force-gamemode=false
allow-nether=true
enforce-whitelist=false
gamemode=survival
broadcast-console-to-ops=true
enable-query=true
player-idle-timeout=0
difficulty=normal
spawn-monsters=true
broadcast-rcon-to-ops=true
op-permission-level=4
pvp=true
entity-broadcast-range-percentage=100
snooper-enabled=true
level-type=default
hardcore=false
enable-status=true
enable-command-block=true
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
function-permission-level=2
rcon.port=25575
server-port=25565
debug=false
server-ip=MC.Radioactive64.net
spawn-npcs=true
allow-flight=true
level-name=Survival
view-distance=10
resource-pack=//www.dropbox.com/s/6ns3uz2aymuod80/VanillaTweaks%20Rescource%20Packs.zip?dl\=1
spawn-animals=true
white-list=false
rcon.password=PASSWORD
generate-structures=true
online-mode=true
max-build-height=256
level-seed=3705019
prevent-proxy-connections=false
use-native-transport=true
enable-jmx-monitoring=false
motd=Radioactive64's Minecraft Server\!
enable-rcon=false`

Plugins:
WorldEdit 7.2.0 beta
All EssentialX 2.17.2.0

Build #68 was used. I also had it set to 2G of RAM and started it with a file.
`#!/bin/sh

java -Xms2G -Xmx2G -jar paper.jar`

It said there was a validation problem with the datapacks

I'm using Vanillatweaks and a Grumbot datapack that the server thread said it couldn't download

**Comment by electronicboy** [comment]
We need logs, and likely a jstack, so that we can actually see what is going on

**Comment by Machine-Maker** [comment]
Can you post your latest.log using a pastebin site?

**Comment by spsquared** [comment]
[latest.log](https://github.com/PaperMC/Paper/files/4874993/latest.log)
Oops, I forgot to add it, here it is.
[09:35:15] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[09:35:16] [main/WARN]: Couldn't get pack info for: net.minecraft.server.v1_16_R1.ResourceNotFoundException: 'pack.mcmeta' in ResourcePack './Survival/datapacks/Grumbot Datapack.zip'
[09:35:16] [main/INFO]: Found new data pack file/VanillaTweaks Crafting.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/afk display v1.0.1.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/anti creeper grief v1.0.2.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/anti enderman grief v1.0.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/anti ghast grief v1.0.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/armour statues v2.7.1.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/count mob deaths v1.0.1.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/custom villager shops v1.1.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/double shulker shells v1.2.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/item averages v1.2.1.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/more mob heads v2.6.2.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/multiplayer sleep v1.0.2.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/nether portal coords v1.0.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/player head drops v1.0.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/real time clock v1.0.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/sethome v1.3.1.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/silence mobs v1.0.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/spawning spheres v1.0.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/spectator conduit power v1.0.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/spectator night vision v1.0.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/track raw statistics v1.3.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/track statistics v1.0.1.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/villager death messages v1.1.0.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/villager workstation highlights v1.0.1.zip, loading it automatically
[09:35:16] [main/INFO]: Found new data pack file/wandering trades v1.2.1.zip, loading it automatically
[09:35:17] [main/INFO]: Reloading ResourceManager: Default, bukkit, VanillaTweaks Crafting.zip, afk display v1.0.1.zip, anti creeper grief v1.0.2.zip, anti enderman grief v1.0.0.zip, anti ghast grief v1.0.0.zip, armour statues v2.7.1.zip, count mob deaths v1.0.1.zip, custom villager shops v1.1.0.zip, double shulker shells v1.2.0.zip, item averages v1.2.1.zip, more mob heads v2.6.2.zip, multiplayer sleep v1.0.2.zip, nether portal coords v1.0.0.zip, player head drops v1.0.0.zip, real time clock v1.0.0.zip, sethome v1.3.1.zip, silence mobs v1.0.0.zip, spawning spheres v1.0.0.zip, spectator conduit power v1.0.0.zip, spectator night vision v1.0.0.zip, track raw statistics v1.3.0.zip, track statistics v1.0.1.zip, villager death messages v1.1.0.zip, villager workstation highlights v1.0.1.zip, wandering trades v1.2.1.zip
[09:35:20] [Server-Worker-3/INFO]: Loaded 7 recipes
[09:35:20] [Server-Worker-3/WARN]: Found validation problem in {minecraft:entities/ender_dragon}.pools[0].entries[0]: Unknown loot table called minecraft:entities/reference/extra/ender_dragon
[09:35:20] [Server-Worker-3/WARN]: Found validation problem in {minecraft:entities/villager}.pools[0].entries[0]: Unknown loot table called minecraft:entities/reference/villager/villager_head
[09:35:22] [main/INFO]: [STDERR]: java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
[09:35:22] [main/INFO]: [STDERR]: 	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
[09:35:22] [main/INFO]: [STDERR]: 	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
[09:35:22] [main/INFO]: [STDERR]: 	at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
[09:35:22] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_16_R1.ServerGUI.a(ServerGUI.java:44)
[09:35:22] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.bb(DedicatedServer.java:455)
[09:35:22] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_16_R1.Main.lambda$main$0(Main.java:182)
[09:35:22] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:183)
[09:35:22] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_16_R1.Main.main(Main.java:170)
[09:35:22] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.Main.main(Main.java:276)
[09:35:22] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:35:22] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:35:22] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:35:22] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:35:22] [main/INFO]: [STDERR]: 	at io.papermc.paperclip.Paperclip.main(Paperclip.java:54)
[09:35:23] [Thread-2/INFO]: Stopping server (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[09:35:23] [Thread-2/INFO]: Saving worlds
[09:35:23] [Thread-2/INFO]: Flushing Chunk IO
[09:35:23] [Thread-2/INFO]: Closing Thread Pool
[09:35:23] [Thread-2/INFO]: Closing Server

**Comment by electronicboy** [comment]
Need a jstack to see why it didn't stop properly, but, your environment is busted
```
[09:35:22] [main/INFO]: [STDERR]: java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
[09:35:22] [main/INFO]: [STDERR]: 	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
[09:35:22] [main/INFO]: [STDERR]: 	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
[09:35:22] [main/INFO]: [STDERR]: 	at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
[09:35:22] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_16_R1.ServerGUI.a(ServerGUI.java:44)
```

You'd need to work out what's busted in order to get the gui to work, or, just run with --nogui

**Comment by spsquared** [comment]
I may have forgotten to update. That was an issue since I tried vanilla.
org.GNOME.Accessibility.AtkWrapper is missing probably

**Comment by spsquared** [comment]
I found this on another post
> I've had the same issue with Kubuntu 18.04 when launching Umlet this morning. It appears to be caused by an unattended security upgrade for the openjdk packages.
> 
> The [answer by rdrever to this askubuntu SE question](https://askubuntu.com/questions/695560/assistive-technology-not-found-error-while-building-aprof-plot) fixed the error.
> 
> Quoting the fix:
> 
> > This can be done by editing the accessibility.properties file for OpenJDK:
> > `sudo vim /etc/java-8-openjdk/accessibility.properties`
> > Comment out the following line:
> > `assistive_technologies=org.GNOME.Accessibility.AtkWrapper`
> 
> Hope this helps.

There was no permission to access it, most likely. Would updating java work? Or should I just go into accessibility.properties?

**Comment by spsquared** [comment]
IT was the issue,
