### ISSUE TITLE
NoSuchMethodError: Relating to Inventory Names/Titles

### ISSUE THREAD

**Issue by The-SourceCode** [PaperMC/Paper#3813]
### What behaviour is expected:
I ran a `InventoryClickEvent `so I could record items put in, into a database. Normal when I run a .getName or .getTitle, it will return back with no issue. 

### What behaviour is observed:
`[14:56:42 ERROR]: Could not pass event InventoryClickEvent to SMPGuilds v1.0.0
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.inventory.Inventory.getTitle()'
        at dev.thesourcecode.guild.vault.VaultEvents.interactInventory(VaultEvents.java:49) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor59.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-68]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-68]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-68]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2421) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-68]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-68]        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-68]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

### Steps/models to reproduce:
use` .getName` / `.getTitle` for `InventoryClickEvent`

### Plugin list:
Multiverse, Essentials, CoreProtect

### Paper build number:
`This server is running Paper version git-Paper-68 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
`
### Anything else:
I noticed that if I tried to cause an intential error like Casting` InventoryView` to `.getInventory()` it would say that I was casting InventoryView to CraftedInventoryDoubleChest.

**Comment by electronicboy** [comment]
You need to get the inventory view from the click event, not try to blindly cast; getTitle was removed from Inventory a few majors ago due to vanilla changes
