### ISSUE TITLE
Failed to schedule unload callback for chunk [-301, 505]

### ISSUE THREAD

**Issue by ENTER17** [PaperMC/Paper#3824]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

[21:58:33] [Server thread/FATAL]: Failed to schedule unload callback for chunk [-301, 505]
java.util.concurrent.CompletionException: net.minecraft.server.v1_16_R1.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.e(ThreadedMailbox.java:90) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.a(ThreadedMailbox.java:137) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.run(ThreadedMailbox.java:102) ~[patched_1.16.1.jar:git-Paper-74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: net.minecraft.server.v1_16_R1.ReportedException: Feature placement
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$null$38(PlayerChunkMap.java:1222) ~[patched_1.16.1.jar:git-Paper-74]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$b$40(PlayerChunkMap.java:1207) ~[patched_1.16.1.jar:git-Paper-74]
	... 10 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.WeightedList.b(SourceFile:60) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureStateProviderWeighted.a(SourceFile:42) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureFlower.b(SourceFile:33) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureFlower.b(SourceFile:11) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFlowers.generate(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureConfigured.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenDecorator.a(SourceFile:91) ~[patched_1.16.1.jar:git-Paper-74]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.IntPipeline$4$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.WorldGenDecorator.a(SourceFile:90) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenDecoratorConfigured.a(SourceFile:28) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureComposite.a(SourceFile:20) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureComposite.generate(SourceFile:13) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureConfigured.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.BiomeBase.a(BiomeBase.java:367) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkGenerator.addDecorations(ChunkGenerator.java:173) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkStatus.lambda$static$9(ChunkStatus.java:71) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkStatus.a(ChunkStatus.java:193) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$null$38(PlayerChunkMap.java:1209) ~[patched_1.16.1.jar:git-Paper-74]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$b$40(PlayerChunkMap.java:1207) ~[patched_1.16.1.jar:git-Paper-74]
	... 10 more
[21:58:33] [Server thread/FATAL]: Failed to schedule unload callback for chunk [-301, 504]
java.util.concurrent.CompletionException: net.minecraft.server.v1_16_R1.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.e(ThreadedMailbox.java:90) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.a(ThreadedMailbox.java:137) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.run(ThreadedMailbox.java:102) ~[patched_1.16.1.jar:git-Paper-74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: net.minecraft.server.v1_16_R1.ReportedException: Feature placement
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$null$38(PlayerChunkMap.java:1222) ~[patched_1.16.1.jar:git-Paper-74]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$b$40(PlayerChunkMap.java:1207) ~[patched_1.16.1.jar:git-Paper-74]
	... 10 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.WeightedList.b(SourceFile:60) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureStateProviderWeighted.a(SourceFile:42) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureFlower.b(SourceFile:33) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureFlower.b(SourceFile:11) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFlowers.generate(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureConfigured.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenDecorator.a(SourceFile:91) ~[patched_1.16.1.jar:git-Paper-74]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.IntPipeline$4$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.WorldGenDecorator.a(SourceFile:90) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenDecoratorConfigured.a(SourceFile:28) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureComposite.a(SourceFile:20) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureComposite.generate(SourceFile:13) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureConfigured.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.BiomeBase.a(BiomeBase.java:367) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkGenerator.addDecorations(ChunkGenerator.java:173) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkStatus.lambda$static$9(ChunkStatus.java:71) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkStatus.a(ChunkStatus.java:193) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$null$38(PlayerChunkMap.java:1209) ~[patched_1.16.1.jar:git-Paper-74]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$b$40(PlayerChunkMap.java:1207) ~[patched_1.16.1.jar:git-Paper-74]
	... 10 more
[21:58:33] [Server thread/FATAL]: Failed to schedule unload callback for chunk [-302, 505]
java.util.concurrent.CompletionException: net.minecraft.server.v1_16_R1.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.e(ThreadedMailbox.java:90) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.a(ThreadedMailbox.java:137) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.run(ThreadedMailbox.java:102) ~[patched_1.16.1.jar:git-Paper-74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: net.minecraft.server.v1_16_R1.ReportedException: Feature placement
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$null$38(PlayerChunkMap.java:1222) ~[patched_1.16.1.jar:git-Paper-74]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$b$40(PlayerChunkMap.java:1207) ~[patched_1.16.1.jar:git-Paper-74]
	... 10 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.WeightedList.b(SourceFile:60) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureStateProviderWeighted.a(SourceFile:42) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureFlower.b(SourceFile:33) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureFlower.b(SourceFile:11) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFlowers.generate(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureConfigured.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenDecorator.a(SourceFile:91) ~[patched_1.16.1.jar:git-Paper-74]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.IntPipeline$4$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.WorldGenDecorator.a(SourceFile:90) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenDecoratorConfigured.a(SourceFile:28) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureComposite.a(SourceFile:20) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureComposite.generate(SourceFile:13) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureConfigured.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.BiomeBase.a(BiomeBase.java:367) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkGenerator.addDecorations(ChunkGenerator.java:173) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkStatus.lambda$static$9(ChunkStatus.java:71) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkStatus.a(ChunkStatus.java:193) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$null$38(PlayerChunkMap.java:1209) ~[patched_1.16.1.jar:git-Paper-74]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$b$40(PlayerChunkMap.java:1207) ~[patched_1.16.1.jar:git-Paper-74]
	... 10 more
[21:58:33] [Server thread/ERROR]: Exception stopping the server
java.util.concurrent.CompletionException: net.minecraft.server.v1_16_R1.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.e(ThreadedMailbox.java:90) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.a(ThreadedMailbox.java:137) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ThreadedMailbox.run(ThreadedMailbox.java:102) ~[patched_1.16.1.jar:git-Paper-74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: net.minecraft.server.v1_16_R1.ReportedException: Feature placement
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$null$38(PlayerChunkMap.java:1222) ~[patched_1.16.1.jar:git-Paper-74]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$b$40(PlayerChunkMap.java:1207) ~[patched_1.16.1.jar:git-Paper-74]
	... 10 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.WeightedList.b(SourceFile:60) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureStateProviderWeighted.a(SourceFile:42) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureFlower.b(SourceFile:33) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureFlower.b(SourceFile:11) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFlowers.generate(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureConfigured.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenDecorator.a(SourceFile:91) ~[patched_1.16.1.jar:git-Paper-74]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.IntPipeline$4$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R1.WorldGenDecorator.a(SourceFile:90) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenDecoratorConfigured.a(SourceFile:28) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureComposite.a(SourceFile:20) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureComposite.generate(SourceFile:13) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldGenFeatureConfigured.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.BiomeBase.a(BiomeBase.java:367) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkGenerator.addDecorations(ChunkGenerator.java:173) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkStatus.lambda$static$9(ChunkStatus.java:71) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.ChunkStatus.a(ChunkStatus.java:193) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$null$38(PlayerChunkMap.java:1209) ~[patched_1.16.1.jar:git-Paper-74]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$b$40(PlayerChunkMap.java:1207) ~[patched_1.16.1.jar:git-Paper-74]
	... 10 more

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

git Paper-68 (MC : 1.16.1)

**Comment by Snewmy** [comment]
Duplicate issue https://github.com/PaperMC/Paper/issues/3732
