### ISSUE TITLE
BlockEntity Problem

### ISSUE THREAD

**Issue by Sulort** [PaperMC/Paper#3827]
[17:37:59] [Paper Async Chunk Task Thread #1/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:bee_nest
[17:38:05] [Paper Async Chunk Task Thread #0/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:bee_nest
[17:38:05] [Paper Async Chunk Task Thread #0/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:bee_nest
[17:38:10] [Server thread/ERROR]: Not a string
[17:38:10] [Server thread/ERROR]: Error loading saved data: map_227
java.lang.IllegalArgumentException: Invalid map dimension: 126
	at net.minecraft.server.v1_16_R1.WorldMap.lambda$a$0(WorldMap.java:98) ~[patched_1.16.1.jar:git-Paper-71]
	at java.util.Optional.orElseGet(Optional.java:369) ~[?:?]
	at net.minecraft.server.v1_16_R1.WorldMap.a(WorldMap.java:81) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.WorldPersistentData.c(WorldPersistentData.java:68) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.WorldPersistentData.b(WorldPersistentData.java:52) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.WorldServer.a(WorldServer.java:1700) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.ItemWorldMap.a(ItemWorldMap.java:29) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.ItemWorldMap.getSavedMap(ItemWorldMap.java:34) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:90) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.EntityTrackerEntry.tick(EntityTrackerEntry.java:75) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2039) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.g(PlayerChunkMap.java:2050) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:863) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.ChunkProviderServer.tick(ChunkProviderServer.java:742) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:455) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1353) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-71]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-71]
	at java.lang.Thread.run(Thread.java:834) [?:?]

### Paper build number:
Paper-71

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by electronicboy** [comment]
1) Missing template
2) Vanilla issues
