### ISSUE TITLE
[1.16.1] Failed to read chunk data for task: Task for world

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3829]
### What behaviour is observed:
Just flying around the world.

`[18:44:07] [Paper RegionFile IO Thread/FATAL]: Failed to read chunk data for task: Task for world: 'world' at 8,11 poi: false, hash: 2139218398
net.minecraft.server.v1_16_R1.ReportedException: Loading NBT data
	at net.minecraft.server.v1_16_R1.NBTTagCompound.b(NBTTagCompound.java:474) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagCompound.access$200(NBTTagCompound.java:26) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:52) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:37) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagCompound.b(NBTTagCompound.java:467) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagCompound.access$200(NBTTagCompound.java:26) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:52) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:37) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:118) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:87) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:77) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.RegionFileCache.read(RegionFileCache.java:161) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.IChunkLoader.read(IChunkLoader.java:104) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.PlayerChunkMap.read(PlayerChunkMap.java:1608) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.WorldServer$2.readData(WorldServer.java:150) ~[patched_1.16.1.jar:git-Paper-74]
	at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508) ~[patched_1.16.1.jar:git-Paper-74]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.16.1.jar:git-Paper-74]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.16.1.jar:git-Paper-74]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.server.v1_16_R1.NBTTagList$1.b(NBTTagList.java:25) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagList$1.b(NBTTagList.java:18) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagList$1.b(NBTTagList.java:36) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagList$1.b(NBTTagList.java:18) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.NBTTagCompound.b(NBTTagCompound.java:467) ~[patched_1.16.1.jar:git-Paper-74]
	... 17 more
[18:44:07] [Paper Async Chunk Task Thread #0/ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (8,11), hashcode:1806426188, priority: -1, file IO thread has dumped the relevant exception above`

### Steps/models to reproduce:
I don't know, it just appeared on console. 

### Plugin list:
None.

### Paper build number:
git-Paper-74

**Comment by aikar** [comment]
you have a corrupt chunk, run mc region fixer on it.

**Comment by realS1NgL3** [comment]
Hi, i have the same problem on aternos server. I have installed paper on my server. We were casually playing but suddenly half of my friend's house dissapeard. I don't know what to do... His all stuff from chests is gone :/ There is just grass... Can I somehow fix it? And now we continue playing, but I'm scared that it will happen again  :/

**Comment by webcrawls** [comment]
> Hi, i have the same problem on aternos server. I have installed paper on my server. We were casually playing but suddenly half of my friend's house dissapeard. I don't know what to do... His all stuff from chests is gone :/ There is just grass... Can I somehow fix it? And now we continue playing, but I'm scared that it will happen again :/

Open a new issue with the relevant information

**Comment by simone123171** [comment]
how can i fix it?

**Comment by electronicboy** [comment]
Please don't bump old tickets, use the discord, and provide the actual
exception which should be logged above that
