### ISSUE TITLE
IndexOutOfBoundsExceptions - Couldn't pick item & Couldn't handle book info

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#388]
Paper dev 832

New users who join my server for the first time join vanished and without any items. So he shouldn't have any access to receiving or obtaining a book. 

Is this a cheat client that sends invalid and fake packet data to the server or something?

```
[11:59:52] [User Authenticator #118/INFO]: UUID of player FuryKills43093 is 3c4d6179-df01-4677-af97-db4512c9d7d9
[11:59:52] [Server thread/INFO]: [VanishNoPacket] FuryKills43093 disappeared.
[11:59:52] [Server thread/INFO]: FuryKills43093[/97.101.128.73:43267] logged in with entity id 1200999 at ([world]-6290.5, 149.0, 2109.5)
[11:59:52] [Server thread/INFO]: [+] FuryKills43093 has joined the server.
[11:59:52] [pool-18-thread-1/INFO]: Creating empty config: /home/minecraft/multicraft/servers/server2/plugins/Essentials/userdata/3c4d6179-df01-4677-af97-db4512c9d7d9.yml
[11:59:53] [Server thread/ERROR]: Couldn't pick item
java.lang.ArrayIndexOutOfBoundsException: 8573
    at net.minecraft.server.v1_10_R1.PlayerInventory.d(PlayerInventory.java:119) ~[patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2532) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-832]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-832]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[11:59:53] [Server thread/INFO]: FuryKills43093 lost connection: Invalid item data!
[11:59:53] [Server thread/INFO]: [-] FuryKills43093 has left the server.
[11:59:53] [Server thread/WARN]: handleDisconnection() called twice
[11:59:58] [User Authenticator #119/INFO]: UUID of player FuryKills43093 is 3c4d6179-df01-4677-af97-db4512c9d7d9
[11:59:58] [Server thread/INFO]: [VanishNoPacket] FuryKills43093 disappeared.
[11:59:58] [Server thread/INFO]: FuryKills43093[/97.101.128.73:47396] logged in with entity id 1201334 at ([world]-6282.5, 115.0, 2086.5)
[11:59:58] [Server thread/INFO]: [+] FuryKills43093 has joined the server.
[12:00:00] [Server thread/ERROR]: Couldn't handle book info
java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readShort(EmptyByteBuf.java:450) ~[patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.readShort(PacketDataSerializer.java:595) ~[patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.k(PacketDataSerializer.java:262) ~[patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2220) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-832]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-832]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-832]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[12:00:00] [Server thread/INFO]: FuryKills43093 lost connection: Invalid book data!
[12:00:00] [Server thread/INFO]: [-] FuryKills43093 has left the server.
[12:00:00] [Server thread/WARN]: handleDisconnection() called twice
```

**Comment by Brokkonaut** [comment]
Looks like a hack client, the sent packets are these:
http://wiki.vg/Plugin_channels#MC.7CPickItem
http://wiki.vg/Plugin_channels#MC.7CBEdit

The client can send them at any time, but of course they are not always accepted by the server. Both of this should not contain any invalid data on a "notchian" client.

**Comment by mibby** [comment]
@Zbob750 Safe to ignore the errors then? Just a precautionary exception notice that doesn't need to be caught?

**Comment by zachbr** [comment]
Yep, the server is handling it as intended.

**Comment by mibby** [comment]
Alright, sounds good. I'll just ignore the error if it ever comes up again. ^^

**Comment by mibby** [comment]
I'd assume this error is safe to ignore too. A bit different / something new than the above ones, but generally the same.

```
[10:19:46] [Server thread/WARN]: EricZeBaws moved wrongly!
[10:19:57] [Server thread/ERROR]: Couldn't select trade
java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readInt(EmptyByteBuf.java:470) ~[patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.readInt(PacketDataSerializer.java:611) ~[patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2288) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-837]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-837]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[10:19:57] [Server thread/INFO]: EricZeBaws lost connection: Invalid trade data!
```

And then of course these two occurred again shortly afterwards. Guess that cheat is spreading far and wide if it is becoming so common. :P

```
[10:20:00] [Server thread/INFO]: [+] EricZeBaws has joined the server.
[10:20:02] [Server thread/ERROR]: Couldn't handle book info
java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readShort(EmptyByteBuf.java:450) ~[patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.readShort(PacketDataSerializer.java:595) ~[patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.k(PacketDataSerializer.java:262) ~[patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2220) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-837]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-837]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[10:20:02] [Server thread/INFO]: EricZeBaws lost connection: Invalid book data!
```

```
[10:20:05] [Server thread/INFO]: [+] EricZeBaws has joined the server.
[10:20:06] [Server thread/ERROR]: Couldn't pick item
java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440) ~[patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.readByte(PacketDataSerializer.java:587) ~[patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.g(PacketDataSerializer.java:147) ~[patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2531) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-837]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-837]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[10:20:06] [Server thread/INFO]: EricZeBaws lost connection: Invalid item data!
```

**Comment by zachbr** [comment]
Yep looks like people are trying to hit outdated/vanilla servers with it. You should be fine.
