### ISSUE TITLE
IndexOutOfBoundsException: Odd repeating error

### ISSUE THREAD

**Issue by Kinjah** [PaperMC/Paper#390]
Paper 1.8.8 (Build: 443)

Various duplication issues have risen, and I thought this would be the best place to bring this up!
Thanks

Random error that occurs:
`[14:45:21] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [paper.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [paper.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paper.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paper.jar:git-PaperSpigot-"8b18730"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_91]
    at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_91]
    at net.minecraft.server.v1_8_R3.Container.getSlot(Container.java:109) ~[paper.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1540) ~[paper.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) ~[paper.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) ~[paper.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[paper.jar:git-PaperSpigot-"8b18730"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[paper.jar:git-PaperSpigot-"8b18730"]
    ... 5 more`

**Comment by zachbr** [comment]
Paper 1.8.8 is no longer supported.
