### ISSUE TITLE
Server Crashes with java.lang.AssertionError: TRAP

### ISSUE THREAD

**Issue by minoneer** [PaperMC/Paper#3904]
Hi, we had the server crash multiple times today due to the same issue below. This was after updating from build 79 to build 90 and has not happened before - however I cannot say if this is coincidence or not.

### Link/paste of stack trace

```
[Server thread/ERROR]: Encountered an unexpected exception
java.lang.AssertionError: TRAP
at net.minecraft.server.v1_16_R1.ItemStack.checkEmpty(ItemStack.java:156) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.ItemStack.setCount(ItemStack.java:970) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.ItemStack.add(ItemStack.java:974) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.ItemStack.subtract(ItemStack.java:978) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.ItemBlock.a(ItemBlock.java:80) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.ItemBlock.a(ItemBlock.java:24) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.ItemStack.placeItem(ItemStack.java:234) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:525) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-90]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

### Actions to reproduce (if known):
Unknown, but I assume it has to do with block placement. > 50 players on server at the time, hard to know who caused it.

### Paper build number:
```
This server is running Paper version git-Paper-90 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-79 (MC: 1.16.1)
You are running the latest version
```

**Comment by electronicboy** [comment]
You have plugins modifying itemstacks in an unexpected manner
