### ISSUE TITLE
"Invalid tag id" when running --forceUpgrade from 1.15.2 to 1.16.1

### ISSUE THREAD

**Issue by ersgonzalo** [PaperMC/Paper#3919]
Hey y'all. I just wanted to get some potential insight into why my server is throwing this error whenever I try to --forceUpgrade my server. I was cleaning up a bunch of chunks with mcaselector and after troubleshooting switched chunk locations, it seems that this is the final blocker to the server being fully upgraded.

### Link/paste of stack trace

```
[23:12:23 INFO]: 25% completed (86511 / 337002 chunks)...
[23:12:24 INFO]: 27% completed (92982 / 337002 chunks)...
[23:12:25 ERROR]: Error upgrading world
java.lang.IllegalArgumentException: Invalid tag id: 116
        at net.minecraft.server.v1_16_R1.NBTTagType$1.b(SourceFile:21) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagType$1.b(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound.b(NBTTagCompound.java:467) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound.access$200(NBTTagCompound.java:26) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:52) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:37) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagList$1.b(NBTTagList.java:36) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagList$1.b(NBTTagList.java:18) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound.b(NBTTagCompound.java:467) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound.access$200(NBTTagCompound.java:26) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:52) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:37) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound.b(NBTTagCompound.java:467) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound.access$200(NBTTagCompound.java:26) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:52) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTTagCompound$1.b(NBTTagCompound.java:37) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:118) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:87) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:77) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.RegionFileCache.read(RegionFileCache.java:161) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.IChunkLoader.read(IChunkLoader.java:104) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.WorldUpgrader.i(WorldUpgrader.java:119) ~[patched_1.16.1.jar:git-Paper-91]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[23:12:25 INFO]: -------- World Settings For [world] --------
[23:12:25 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[23:12:25 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
```
### Plugin list:
No Plugins

### Actions to reproduce (if known):
Attempting to run the Paper 91 jar with the --forceUpgrade argument from a world that was previously on 1.15.2 `git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

Batch File command below:
`java -Xms1024M -Xmx8192M -jar server.jar -o true --forceUpgrade
PAUSE`

### Paper build number:
```
> version
[23:00:41 INFO]: This server is running Paper version git-Paper-91 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[23:00:41 INFO]: Checking version, please wait...
[23:00:43 INFO]: Previous version: git-Paper-372 (MC: 1.15.2)
[23:00:43 INFO]: You are 1 version(s) behind
```

### Additional Notes
I did try renaming the map_116.dat and map_118.dat files and it seemed to have changed the error as I had originally gotten an invalid tag id for 118, and now we are at invalid tag 116. 
![image](https://user-images.githubusercontent.com/5564973/87623131-b2a89780-c6f2-11ea-8c17-9ac9496a1b81.png)

**Comment by TNTUP** [comment]
~~Can confirm while upgrading a 1.12.2 world to 1.16.1, I'll try that renaming those maps_ dat files if that solves it (backing up these and delete and try again)

https://pastebin.com/PgmyjrKy

EDIT: I don't have map_116.dat in the world files~~

Edit2: I guess this is an issue with chunk conversion as I'm getting that same error because if I try converting my 1.12.2 to 1.13.2, no issues. Sorry if this comment is offtopic, imma mark as it

**Comment by aikar** [comment]
this has nothing to do with your map_ files, so please stop renaming them.

It looks like your data is potentially corrupt, as there is no NBT tag type of 116 is what its complaining about.

**Comment by electronicboy** [comment]
This is a corrupted region file, nothing to do with map files as aikar stated; Paper tries to ensure that region files won't corrupt, but, beyond that, it's down to the OS; best advice at this point would be to just use one of the many tools to just zap the corrupted regions

**Comment by ersgonzalo** [comment]
Actually @TNTUP I was able to fix my issue, with a combination of https://github.com/Fenixin/Minecraft-Region-Fixer and https://github.com/Querz/mcaselector I was able to remove the bad chunks and then get everything running successfully. For anyone who comes across this thread, investigate those two tools (Minecraft Region Fixer is the first choice to start with) and then you should be able to resolve the --forceUpgrade errors happening!
