### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Cuki1998** [PaperMC/Paper#3921]
[13:25:22 WARN]: Illegal Entity Teleport EntityExperienceOrb['Experience Orb'/62907, uuid='a43fae13-6f74-4a4e-a417-59a2de1bf4f5', l='ServerLevel[world
_the_end]', x=2.21, y=59.73, z=1.58, cx=0, cz=0, tl=94, v=true, d=true] to ServerLevel[world]:null
java.lang.Throwable: null
        at net.minecraft.server.v1_16_R1.Entity.teleportTo(Entity.java:2592) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.Entity.a(Entity.java:2584) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.BlockEnderPortal.a(BlockEnderPortal.java:45) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.BlockBase$BlockData.a(BlockBase.java:560) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.Entity.checkBlockCollisions(Entity.java:1013) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.Entity.move(Entity.java:748) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.EntityExperienceOrb.tick(EntityExperienceOrb.java:157) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:832) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.World.a(World.java:932) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:526) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1353) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-90]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by electronicboy** [comment]
When submitting an issue, fill in the template...
Looks like something killed the entity during teleport, replicate without plugins, etc
