### ISSUE TITLE
AuthenticationException: The client has sent too many requests within a certain amount of time

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#395]
Paper dev 837.

Error occurred immediately after start-up was finished. Something that can be fixed or just have to ignore it since it would be the authentication servers blocking the request?

```
[04:00:22] [Head Conversion Thread - 0/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@66dbf152[id=uuid,name=player,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[patched_1.10.2.jar:git-Paper-837]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [patched_1.10.2.jar:git-Paper-837]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.TileEntitySkull$1.load(TileEntitySkull.java:76) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.TileEntitySkull$1.load(TileEntitySkull.java:43) [patched_1.10.2.jar:git-Paper-837]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [patched_1.10.2.jar:git-Paper-837]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [patched_1.10.2.jar:git-Paper-837]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [patched_1.10.2.jar:git-Paper-837]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [patched_1.10.2.jar:git-Paper-837]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [patched_1.10.2.jar:git-Paper-837]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [patched_1.10.2.jar:git-Paper-837]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [patched_1.10.2.jar:git-Paper-837]
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [patched_1.10.2.jar:git-Paper-837]
    at net.minecraft.server.v1_10_R1.TileEntitySkull$3.run(TileEntitySkull.java:201) [patched_1.10.2.jar:git-Paper-837]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by zachbr** [comment]
Not really, Mojang rate limits requests. So all tha has happened here is a bunch of skulls tried to fetch profiles and were rate limited by Mojang services.

**Comment by mibby** [comment]
A similar authentication issue occurred again with Paper 845. Darn you mojang servers! >:o

```
[00:45:14] [Head Conversion Thread - 1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@746d9860[id=uuid,name=player,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:71) ~[patched_1.10.2.jar:git-Paper-845]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [patched_1.10.2.jar:git-Paper-845]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.TileEntitySkull$1.load(TileEntitySkull.java:76) [patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.TileEntitySkull$1.load(TileEntitySkull.java:43) [patched_1.10.2.jar:git-Paper-845]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [patched_1.10.2.jar:git-Paper-845]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [patched_1.10.2.jar:git-Paper-845]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [patched_1.10.2.jar:git-Paper-845]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [patched_1.10.2.jar:git-Paper-845]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [patched_1.10.2.jar:git-Paper-845]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [patched_1.10.2.jar:git-Paper-845]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [patched_1.10.2.jar:git-Paper-845]
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.TileEntitySkull$3.run(TileEntitySkull.java:201) [patched_1.10.2.jar:git-Paper-845]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_102]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_102]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_102]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_102]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_102]
    at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_102]
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[?:1.8.0_102]
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_102]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[?:1.8.0_102]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[?:1.8.0_102]
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_102]
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_102]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_102]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148) ~[?:1.8.0_102]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[?:1.8.0_102]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_102]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[?:1.8.0_102]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_102]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_102]
    at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:126) ~[patched_1.10.2.jar:git-Paper-845]
    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:54) ~[patched_1.10.2.jar:git-Paper-845]
    ... 16 more
```

**Comment by daddyparodz** [comment]
can you help me please 

`com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[server.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [server.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [server.jar:?]
	at bkd.b(SourceFile:135) [server.jar:?]
	at bkd.f(SourceFile:111) [server.jar:?]
	at bkd.a(SourceFile:107) [server.jar:?]
	at bkd.b(SourceFile:60) [server.jar:?]
	at bji.c(SourceFile:78) [server.jar:?]
	at bnv.a(SourceFile:548) [server.jar:?]
	at bnv.a(SourceFile:144) [server.jar:?]
	at tc.a(SourceFile:102) [server.jar:?]
	at tk.<init>(SourceFile:43) [server.jar:?]
	at tl.c(SourceFile:172) [server.jar:?]
	at tl.a(SourceFile:203) [server.jar:?]
	at vp.a(SourceFile:273) [server.jar:?]
	at vp.c(SourceFile:342) [server.jar:?]
	at vp.a(SourceFile:166) [server.jar:?]
	at ue.b(SourceFile:113) [server.jar:?]
	at ue.Y_(SourceFile:65) [server.jar:?]
	at hw.a(SourceFile:238) [server.jar:?]
	at ub.c(SourceFile:171) [server.jar:?]
	at net.minecraft.server.MinecraftServer.b(SourceFile:773) [server.jar:?]
	at so.b(SourceFile:360) [server.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:681) [server.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:584) [server.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

**Comment by JanTuck** [comment]
This has nothing to do with Paper, and should not be addressed as such.
