### ISSUE TITLE
Skull ItemStack saved to file with YamlConfiguration in Spigot won't load in Paper

### ISSUE THREAD

**Issue by DerFrZocker** [PaperMC/Paper#3950]
### Link/paste of stack trace

```
[12:57:15] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[patched_1.16.1.jar:git-Paper-100]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.16.1.jar:git-Paper-100]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.16.1.jar:git-Paper-100]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.16.1.jar:git-Paper-100]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.16.1.jar:git-Paper-100]
	at net.minecraft.server.v1_16_R1.TileEntitySkull$3.call(TileEntitySkull.java:221) ~[patched_1.16.1.jar:git-Paper-100]
	at net.minecraft.server.v1_16_R1.TileEntitySkull$3.call(TileEntitySkull.java:218) ~[patched_1.16.1.jar:git-Paper-100]
	at net.minecraft.server.v1_16_R1.TileEntitySkull.b(TileEntitySkull.java:237) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:95) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:535) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftItemFactory.ensureServerConversions(CraftItemFactory.java:340) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.inventory.ItemStack.ensureServerConversions(ItemStack.java:613) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:542) ~[patched_1.16.1.jar:git-Paper-100]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[patched_1.16.1.jar:git-Paper-100]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:398) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:186) ~[patched_1.16.1.jar:git-Paper-100]
	at de.derfrzocker.testplugin.TestPlugin.onEnable(TestPlugin.java:19) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-100]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.1.jar:git-Paper-100]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-100]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-100]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_16_R1.TileEntitySkull$1.load(TileEntitySkull.java:80) ~[patched_1.16.1.jar:git-Paper-100]
	at net.minecraft.server.v1_16_R1.TileEntitySkull$1.load(TileEntitySkull.java:47) ~[patched_1.16.1.jar:git-Paper-100]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.16.1.jar:git-Paper-100]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.16.1.jar:git-Paper-100]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.16.1.jar:git-Paper-100]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.16.1.jar:git-Paper-100]
	... 48 more
```

### Plugin list:
TestPlugin

### Actions to reproduce (if known):
Set up a normal spigot server (not paper)
Start the server and join with a Player, so that a playerdata gets generated
Now save an ItemStack with the Owner of the player that just joined to a file via YamlConfiguration
Stop the server and switch the spigot jar with paper
Start the server again with paper and try to load the saved ItemStack

Loading a skull ItemStack saved with Paper in normal Spigot throws no error.
Code used: 
```
    @Override
    public void onEnable() {
        YamlConfiguration yamlConfiguration = YamlConfiguration.loadConfiguration(new File("test.yml"));

        ItemStack itemStack = new ItemStack(Material.PLAYER_HEAD);

        SkullMeta skullMeta = (SkullMeta) itemStack.getItemMeta();

        skullMeta.setOwningPlayer(getServer().getOfflinePlayer(UUID.fromString("29a4042b-05ab-4c72-9460-7aa3b567e8da")));

        itemStack.setItemMeta(skullMeta);

        yamlConfiguration.set("test", itemStack);

        try {
            yamlConfiguration.save(new File("test.yml"));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```
By looking in to the serialize ItemStack it appears that the `internal` value is different when saving in Spigot than in Paper

Spigot serialize ItemStack:
```
test:
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: PLAYER_HEAD
  meta:
    ==: ItemMeta
    meta-type: SKULL
    internal: H4sIAAAAAAAAAONiYOBi4AnOLs3JCSjKT8vMSeVmYPJMYWBgYNFcwqLNutqnaEpC1eKt6S9ucTCw+CXmpjJwu6QWuRVF5SdnpxYxMAAA+4jSZUEAAAA=
    skull-owner: DerFrZocker
```

Paper serialize ItemStack:

```
test:
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: PLAYER_HEAD
  meta:
    ==: ItemMeta
    meta-type: SKULL
    internal: H4sIAAAAAAAAAONiYOBi4AnOLs3JCSjKT8vMSeVgYPFLzE1l4HZJLXIrispPzk4t4mZg8kxhYGBg0VzCos262qdoSkLV4q3pL24xMAAApa5iAEEAAAA=
    skull-owner: DerFrZocker
```

### Spigot / Paper build number:
Spigot: 
```
[13:01:42] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-0509002-6b95d59 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)[m
[13:01:42] [Server thread/INFO]: Checking version, please wait...[m
[13:01:42] [Thread-10/INFO]: You are running the latest version[m
```
Paper: 
```
[12:57:23] [Server thread/INFO]: This server is running Paper version git-Paper-100 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[12:57:23] [Server thread/INFO]: Checking version, please wait...
[12:57:23] [Thread-13/INFO]: Previous version: git-Paper-90 (MC: 1.16.1)
[12:57:23] [Thread-13/INFO]: You are running the latest version
```

**Comment by Proximyst** [comment]
Cannot reproduce on b111. Given there doesn't seem to have been any fixing commits, can you share your configuration files?

**Comment by DerFrZocker** [comment]
Just tested a little more, and it seams that the player from which the skull gets saved must played on the server before, means a playerdata file of the player must be present during the saving of the Skull ItemStack. I updated the Actions to reproduce to make this clear.

> 
> 
> Cannot reproduce on b111. Given there doesn't seem to have been any fixing commits, can you share your configuration files?

Its a fresh Spigot / Paper server with no configuration changes.

[bukkit.yml](https://pastebin.com/GfdJXUBj)
[spigot.yml](https://pastebin.com/RFvgYc8M)
[paper.yml](https://pastebin.com/4fp2TPaH)

**Comment by WolfyScript** [comment]
Are you still encountering that issue?
I get tons of reports of my users of CustomCrafting that their items aren't loading.
I tested the items on Spigot and Paper and tracked the issue down to be caused by Paper. 

The configs are saved in json format, but I just convert the yaml from the YAMLConfiguration to json and back.
Only items with the internal meta seem to break it.

**Comment by aikar** [comment]
@WolfyScript Are you getting the same null pointer error? If not, please open a new issue with as much details as you can

We've had no reports on this since and we did revert some skull changes around that time, so this is likely fixed.

**Comment by WolfyScript** [comment]
@aikar 
Thanks for the quick response,

I got the same error once, but after I tried to reproduce it, it failed silently and I got a null value instead.

I will do some more testing on Spigot and Paper and see if I can track the issue down. Once I got enough details I am going to open a new issue.

**Comment by DerFrZocker** [comment]
Just tested it again with Minecraft version 1.16.3, paper version: 240 and spigot version: git-Spigot-57bbdd8-b8dd5ec
And the error no longer appears. Therefor I will close this for now.
