### ISSUE TITLE
NPE  on player.teleport from World.isOutsideWorld(World.java:270) ~[patched_1.16.1.jar:git-Paper-100]

### ISSUE THREAD

**Issue by RossKor** [PaperMC/Paper#3955]
Teleports are occasionally causing the NPE below. This problem is new (introduced somewhere between 92 and 100) and does not appear to cause any real issues assuming surrounding (plugin) code is sufficiently hardened against it as players are still able to teleport.

There is NO CLEAR REPRO other than it may happen more often when teleporting between worlds.

### What behaviour is observed:
java.lang.NullPointerException: null
at net.minecraft.server.v1_16_R1.World.isOutsideWorld(World.java:270) ~[patched_1.16.1.jar:git-Paper-100]
at net.minecraft.server.v1_16_R1.World.getType(World.java:715) ~[patched_1.16.1.jar:git-Paper-100]
at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:857) ~[patched_1.16.1.jar:git-Paper-100]
at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:813) ~[patched_1.16.1.jar:git-Paper-100]

### Paper build number:
[17:32:01 INFO]: This server is running Paper version git-Paper-100 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[17:32:01 INFO]: Checking version, please wait...
[17:32:01 INFO]: Previous version: git-Paper-92 (MC: 1.16.1)

**Comment by Proximyst** [comment]
This is already fixed. Update.
