### ISSUE TITLE
org.bukkit.command.CommandException on executing commands from a disabled plugin (after loading it successfully)

### ISSUE THREAD

**Issue by dementisimus** [PaperMC/Paper#3988]
Hi!

Stacktrace:

`
[21:33:53 ERROR]: null
 org.bukkit.command.CommandException: Cannot execute command 'mc' in plugin MapCreator v1.0.0 - plugin is disabled.
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper.jar:git-Paper-24]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper.jar:git-Paper-24]
    at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[paper.jar:git-Paper-24]
    at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[paper.jar:git-Paper-24]
    at java.lang.Thread.run(Thread.java:834) [?:?]
`

Command gets registered as follows:

`
getCommand("CMD")#setExecutor(OBJ);
`

Thanks!

**Comment by Proximyst** [comment]
Obviously the plugin didn't enable. Not a Paper issue.
If you'd like help with this, join our Discord/IRC.

Fill the template properly next time, by the way.

**Comment by dementisimus** [comment]
Hi!

I am sorry for that. I'll stick to it next time!

The Plugin is still in /pl - after disabling it successfully:

![image](https://user-images.githubusercontent.com/54750441/88332019-30415880-cd2e-11ea-8483-672567c28370.png)
![image](https://user-images.githubusercontent.com/54750441/88332047-3afbed80-cd2e-11ea-866d-58f11b71cdb7.png)

Thanks!

**Comment by Proximyst** [comment]
Your terminal does not support colours; the plugin will show up as *red* in that list. Check the logs as to why it disabled.

**Comment by dementisimus** [comment]
My terminal does support colors: 

![image](https://user-images.githubusercontent.com/54750441/88332246-86160080-cd2e-11ea-8403-dca606d0ee7e.png)

![image](https://user-images.githubusercontent.com/54750441/88332286-90d09580-cd2e-11ea-81b2-144d599d2164.png)
(Java itself)

I'll check the logs, thank you!

**Comment by dementisimus** [comment]
![image](https://user-images.githubusercontent.com/54750441/88332371-bbbae980-cd2e-11ea-97f7-de8d3a728e19.png)

nothing to see in latest.log either.

**Comment by dementisimus** [comment]
but: it does get marked red in /pl (ingame):

![image](https://user-images.githubusercontent.com/54750441/88332479-ea38c480-cd2e-11ea-911f-ba7d4af0a11c.png)

**Comment by electronicboy** [comment]
provide the actual log file, you're clearly missing info out

**Comment by BillyGalbreath** [comment]
Reloading/Disabling plugins at runtime is unsupported, iirc.

**Comment by dementisimus** [comment]
here's the log file: https://hastebin.com/woviwajite.md

**Comment by BillyGalbreath** [comment]
Ya'll misunderstood the ticket. He's reporting that the thrown exception should not be thrown on a disabled plugin.

[But this is expected behavior](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/command/PluginCommand.java#37)

Not a bug.

**Comment by electronicboy** [comment]
It was clearly disabled, the commands then refuse to execute due to the plugin being disabled; nothing unexpected here, speak to the plugin author

**Comment by dementisimus** [comment]
okay, thank you all for your help!

Thanks!
