### ISSUE TITLE
[1.16.1][21:47:33 ERROR]: Couldn't register custom payload

### ISSUE THREAD

**Issue by yuankun1** [PaperMC/Paper#4006]
[21:47:33 ERROR]: Couldn't register custom payload
java.lang.IllegalStateException: Cannot register channel 'l:bibliorenderupdate'. Too many channels registered!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:518) ~[patched_1.16.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1548) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2749) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-117]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

**Comment by Proximyst** [comment]
Fill in the template.

`Cannot register channel 'l:bibliorenderupdate'. Too many channels registered!` - Remove plugins, you've got too many channels.

**Comment by yuankun1** [comment]
Use the ProtocolSupport plug-in to load 1.16.1
Mods Customer Service Terminal Loaded in Mass with 1.12.2forge
Entering the server causes this error report

**Comment by aikar** [comment]
your client needs to reduce the amount of channels its trying to register.

not a paper related issue.
