### ISSUE TITLE
what happen on MapManager???????

### ISSUE THREAD

**Issue by crusherkr** [PaperMC/Paper#4024]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___
??
### Description of issue:
___If applicable___
[17:55:30 ERROR]: Error occurred while enabling MapManager v1.7.8-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: SEM_VER_SNAPSHOT
        at org.inventivetalent.mapmanager.MapManagerPlugin.onEnable(MapManagerPlugin.java:109) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

### Plugin list:
___All plugins running on the server___
AnimatedFrames, Citizens, CoreProtect-Uploader, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, HolographicDisplays, LuckPerms, MapManager, Multiverse-Core, PacketListenerApi, paper12.2pl1, Shopkeepers, SkQuery, skRayFall, Skript, skUtilities, SuperTrails, Vault, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___
i have ho links but i download MaoManager 1.7.8 but there is that horrible error in start.bat :(
so i report this error
  
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[18:15:09 INFO]: Checking version, please wait...
[18:15:12 INFO]: You are running the latest version

**Comment by sbienkow** [comment]
Unsupported version. And a plugin issue - you should contact the author. Maybe you forgot to set "PaperSpigot" to true in config?

**Comment by CDFN** [comment]
Paper's github isn't support of MapManager plugin. Head [there](https://github.com/InventivetalentDev/MapManager).
