### ISSUE TITLE
Error executing task - ExecutionException ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#404]
Paper dev 845

New error I noticed after updating to Paper 845. No idea what caused it. Nothing prior or after the error. :o 

```
[19:40:39] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_102]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:46) [patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-845]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_102]
    at java.util.ArrayList.get(ArrayList.java:431) ~[?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.Container.getSlot(Container.java:111) ~[patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1822) ~[patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.10.2.jar:git-Paper-845]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.10.2.jar:git-Paper-845]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) ~[patched_1.10.2.jar:git-Paper-845]
    ... 5 more
```

**Comment by aikar** [comment]
this could only happen if something modifies the inventory async, meaning a naughty plugin.

```
    for (int j = 0; j < this.c.size(); ++j) {
        Slot slot = (Slot) this.c.get(j);
```

**Comment by mibby** [comment]
Is there any way to log which plugin may be touching the inventory async or prevent it from occurring out of thread safety? There is nothing in the logs as far as commands entered the same time the error occurs. Just something I noticed recently as of updating Paper.

**Comment by Brokkonaut** [comment]
no, it's reproducible without plugins:

open a chest inventory (some other inventorys work too), take any item in your hand and middle click in the window outside of any slot.

no async bug, but a bug in inventory click handling.

PlayerConnection.java, Line 1819 should be "... < 0" instead of "... == -999" (similar to line 1776)
