### ISSUE TITLE
World lock crash

### ISSUE THREAD

**Issue by Bluenix2** [PaperMC/Paper#4044]
### Link/paste of stack trace
```
[16:21:33 FATAL]: Failed to start the minecraft server
net.minecraft.server.v1_16_R1.SessionLock$ExceptionWorldConflict: /home/minecraft/paper-1.16/./world/session.lock: 
already locked (possibly by other Minecraft instance?)
        at net.minecraft.server.v1_16_R1.SessionLock$ExceptionWorldConflict.a(SourceFile:98) ~[patched_1.16.1.jar:g
it-Paper-130]
        at net.minecraft.server.v1_16_R1.SessionLock.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.Convertable$ConversionSession.<init>(Convertable.java:198) ~[patched_1.16.
1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.Convertable.c(Convertable.java:180) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.Main.main(Main.java:113) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.Main.main(Main.java:276) ~[patched_1.16.1.jar:git-Paper-130]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:54) ~[paper.jar:?]
```
### Plugin list:
___A list of your plugins___
BetterSleeping
CoreProtect
DropHeads
LuckPerms
ProtocolLib
LockettePro

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Start server I guess

### Paper build number:
130

**Comment by electronicboy** [comment]
> net.minecraft.server.v1_16_R1.SessionLock$ExceptionWorldConflict: /home/minecraft/paper-1.16/./world/session.lock: 
already locked (possibly by other Minecraft instance?)

The session lock file was already locked, this is an environment issue, e.g. there is already a copy of the server running

**Comment by Bluenix2** [comment]
Aaaaaaah, you saying that made me remember that I set up to start with the computer.
