### ISSUE TITLE
World creating throws an Exception

### ISSUE THREAD

**Issue by SemperEtAnte** [PaperMC/Paper#4087]
Hello. I try to create a new world on 1.16.1 (paper-133) from my plugin with following code:
```
       String worldName = configUtils.getString("villagesWorld", "villages");
        villagesWorld = Bukkit.getWorld(worldName);
        if (villagesWorld == null)
        {
            WorldCreator wc = new WorldCreator(worldName);

            wc.type(WorldType.FLAT);
            wc.generatorSettings("2;0;1;");

            villagesWorld = wc.createWorld();
            villagesWorld.save();
        }
```

But it throws me an exception:
```
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:495) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:545) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:541) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:549) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.GeneratorSettings.a(SourceFile:203) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createWorld(CraftServer.java:1112) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:570) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[patched_1.16.1.jar:git-Paper-133]
	at ru.SemperAnte.FreeServer.VillageUpgrade.VillageUpgrade.postInit(VillageUpgrade.java:155) ~[?:?]
	at ru.SemperAnte.API.Plugins.APIPlugin.onEnable(APIPlugin.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-133]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patched_1.16.1.jar:git-Paper-133]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[patched_1.16.1.jar:git-Paper-133]
	at com.google.gson.stream.JsonReader.isLiteral(JsonReader.java:751) ~[patched_1.16.1.jar:git-Paper-133]
	at com.google.gson.stream.JsonReader.peekNumber(JsonReader.java:706) ~[patched_1.16.1.jar:git-Paper-133]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:584) ~[patched_1.16.1.jar:git-Paper-133]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[patched_1.16.1.jar:git-Paper-133]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:716) ~[patched_1.16.1.jar:git-Paper-133]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[patched_1.16.1.jar:git-Paper-133]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:493) ~[patched_1.16.1.jar:git-Paper-133]
	... 19 more
```
It creates world folder with only `session.lock` file.
(Sry for my English...)

**Comment by electronicboy** [comment]
invalid generator settings, it's now some json thing

**Comment by SemperEtAnte** [comment]
> invalid generator settings, it's now some json thing

and where can i read about this?..

**Comment by electronicboy** [comment]
https://minecraft.gamepedia.com/Java_Edition_level_format#generatorOptions_tag_format I'd guess

**Comment by SemperEtAnte** [comment]
> https://minecraft.gamepedia.com/Java_Edition_level_format#generatorOptions_tag_format I'd guess

thx
