### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by hotspuraz** [PaperMC/Paper#4118]
### Link/paste of stack trace

https://pastebin.com/FU7EKXbD

It does say "Do Not Report to Paper"
But at the bottom is also says says:

[global] TIMING_STACK_CORRUPTION - Look above this for any errors and report this to Paper unless it has a plugin in the stack trace (TimingIdentifier{id=Minecraft:world - Sync Chunk Load} did not stopTiming)
[18:28:25] [Server thread/ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:853) [?:1.8.0_265]
	at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:763) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.close(MinecraftServer.java:737) ~[patched_1.16.1.jar:git-Paper-135]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157) ~[patched_1.16.1.jar:git-Paper-135]

So figured I'd see if anyone knows what's happened :s

### Plugin list:
AdvancedRegionMarket, BuycraftX, ChestShop, ClearLag, CMI, CMIEInjector*, CMIPaperLib, CoreProtect, EasyBackup, EnchantGui, EntityDetection, FogusCore, GoldenCrates, GriefPrevention, Harbor, HeadDatabase*, HolographicDisplays, HolographicExtension, Images, Insights, LastLoginAPI, LeaderHeadsRevamped, LiteBans, LuckPerms, MarriageMaster, MineableSpawners, MobFarmManager, Parties, PL-Hide, PlaceholderAPI, PlayerParticles, PluginConstructorAPI, PlugMan, PremiumVanish, ProtocolLib, Rankup, ShopGUIPlus, SuperLog, SuperTrailsPro*, TAB, UltimateAutoRestart, UltimateTimber, Vault, ViaVersion, Votifier, VotingPlugin, Welcome*, Wild, WorldBorder, WorldEdit, WorldGuard

### Paper build number:
Paper-135 1.16.1

**Comment by electronicboy** [comment]
timing stack corruption is normal during watchdog kills, this issue is #2312 however
