### ISSUE TITLE
Error: Timing Stack Corruption/Hard Crash

### ISSUE THREAD

**Issue by Slackadays** [PaperMC/Paper#4143]
This issue happened while I had speed 255 and teleported to a previously ungenerated area.
### The Errors:
[21:35:34 ERROR]: ------------------------------
[21:35:34 ERROR]: Current Thread: Keep-Alive-Timer
[21:35:34 ERROR]:       PID: 142 | Suspended: false | Native: false | State: TIMED_WAITING
[21:35:34 ERROR]:       Stack:
[21:35:34 ERROR]:               java.base@11.0.8/java.lang.Thread.sleep(Native Method)
[21:35:34 ERROR]:               java.base@11.0.8/sun.net.www.http.KeepAliveCache.run(Ke

[21:35:34 ERROR]:               java.base@11.0.8/java.lang.Thread.run(Thread.java:834)
[21:35:34 ERROR]: ------------------------------
[21:35:34 ERROR]: Current Thread: Keep-Alive-Timer
[21:35:34 ERROR]:       PID: 142 | Suspended: false | Native: false | State: TIMED_WAITING
[21:35:34 ERROR]:       Stack:
[21:35:34 ERROR]:               java.base@11.0.8/java.lang.Thread.sleep(Native Method)
[21:35:34 ERROR]:               java.base@11.0.8/sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:168)
[21:35:34 ERROR]:               java.base@11.0.8/java.lang.Thread.run(Thread.java:834)
[21:35:34 ERROR]:               java.base@11.0.8/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
[21:35:34 ERROR]: ------------------------------
[21:35:35 INFO]: Stopping main thread
[21:35:35 ERROR]: [global] TIMING_STACK_CORRUPTION - Look above this for any errors and report this to Paper unless it has a plugin in the stack trace (TimingIdentifier{id=Minecraft:world - Sync Chunk Load} did not stopTiming)
[21:35:35 ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
        at java.lang.Thread.stop(Thread.java:942) [?:?]
        at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:763) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.close(MinecraftServer.java:737) ~[patched_1.16.1.jar:git-Paper-135]
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157) ~[patched_1.16.1.jar:git-Paper-135]
[21:35:35 INFO]: Stopping server
[21:35:35 INFO]: Saving players
...
### Plugin list:
None
### Actions to reproduce (if known):
/tp to an ungenerated area. CPU usage does not increase to generate a new area, but rather stays the same or falls and thus causes the crash.

### Paper build number:
135

### Notes:
Java has almost no CPU usage when saving the world because of this hard crash. This is not an I/O error or world saving would have generated errors earlier. Also, Aikar's flags are being used.

**Comment by Chew** [comment]
Unfortunately, we don't have enough information to keep this open. This issue was likely fixed in the numerous builds since this release, especially the 1.16.2 update. If you still experience this issue, don't hesitate to open a new issue, and please provide a log on a site such as gist.github.com or paste.gg. Thank you for the report!
