### ISSUE TITLE
Server crash caused by collideRule

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#415]
Paper dev 854

@Zbob750 Had two server crashes thus far since updating today.

```
  enable-player-collisions: false
  save-empty-scoreboard-teams: false
```

```
Description: Exception in server tick loop

java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'collideRule_-182'.
    at net.minecraft.server.v1_10_R1.Scoreboard.removePlayerFromTeam(SourceFile:273)
    at net.minecraft.server.v1_10_R1.ScoreboardServer.removePlayerFromTeam(ScoreboardServer.java:78)
    at net.minecraft.server.v1_10_R1.PlayerList.disconnect(PlayerList.java:417)
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1069)
    at net.minecraft.server.v1_10_R1.NetworkManager.handleDisconnection(NetworkManager.java:318)
    at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:186)
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:893)
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:732)
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:631)
    at java.lang.Thread.run(Thread.java:745)
```

In both crash cases, it seems to have occurred immediately after someone disconnected. I do use another plugin to colorize player nametags based on their grouping using scoreboards if that is of any concern - though prior to updating, I never had these crashes with no collision. 

The crash doesn't occur every time someone disconnects, just rarely.

**Comment by AlfieC** [comment]
It is the nametag plugin - Paper should check if they're on another team and set the collide rule there. All that needs to be done is a simple check whether the player is still on that team. I suspect that @Zbob750 forgot that a player can only be on one team per scoreboard ;P

**Comment by mibby** [comment]
For reference, this is the plugin I use to colorize player nametags.
https://dev.bukkit.org/bukkit-plugins/colored-tags/

I also have scoreboards set when players enter an arena and revert to their previous team on exit.

Did a change to collision setting break recently? It use to work fine alongside nametag plugins without conflict / crashing. :o

**Comment by zachbr** [comment]
We fixed it so it'd properly work without making everyone create and manage NMS teams.

I thought about this earlier today on the drive home but didn't get to it unfortunately. Easy fix.

**Comment by zachbr** [comment]
Should be fixed in builds 858+
