### ISSUE TITLE
Error on player connection 1.15.2

### ISSUE THREAD

**Issue by MuravlevAS** [PaperMC/Paper#4157]
### Link/paste of stack trace

```
[08:44:21 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@4682cc9[id=33cfb8a1-853d-310c-986d-e83f0473f488,name=OlegMiner100,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:89) ~[patched_1.15.2.jar:git-Paper-385]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) ~[patched_1.15.2.jar:git-Paper-385]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:37) ~[patched_1.15.2.jar:git-Paper-385]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) ~[patched_1.15.2.jar:git-Paper-385]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:30) ~[patched_1.15.2.jar:git-Paper-385]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:186) ~[patched_1.15.2.jar:git-Paper-385]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:179) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:313) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.LoginListener$1.run(LoginListener.java:212) ~[patched_1.15.2.jar:git-Paper-385]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.15.2.jar:git-Paper-385]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:67) ~[patched_1.15.2.jar:git-Paper-385]
        ... 11 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.15.2.jar:git-Paper-385]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:67) ~[patched_1.15.2.jar:git-Paper-385]
        ... 11 more
[08:44:21 INFO]: UUID of player OlegMiner100 is 33cfb8a1-853d-310c-986d-e83f0473f488
[08:44:21 INFO]: OlegMiner100[/37.79.16.198:46881] logged in with entity id 53194 at ([world]-336.22926814587305, 72.0, -453.47919587042946)
```

after a few minutes this player leaved from server. I think it could play normally because it's not disconnected immediately.

*UPD*: 
later some other player disconnected, changed minecraft version on 1.15.2 and i've got the same error in console:
```
[09:01:01 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@6814ad7c[id=ec55e285-4642-38be-9235-f58d10c578f7,name=dimonpx1203,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:89) ~[patched_1.15.2.jar:git-Paper-385]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) ~[patched_1.15.2.jar:git-Paper-385]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:37) ~[patched_1.15.2.jar:git-Paper-385]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) ~[patched_1.15.2.jar:git-Paper-385]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:30) ~[patched_1.15.2.jar:git-Paper-385]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:186) ~[patched_1.15.2.jar:git-Paper-385]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:179) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:313) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.LoginListener$1.run(LoginListener.java:212) ~[patched_1.15.2.jar:git-Paper-385]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.15.2.jar:git-Paper-385]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:67) ~[patched_1.15.2.jar:git-Paper-385]
        ... 11 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.15.2.jar:git-Paper-385]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:67) ~[patched_1.15.2.jar:git-Paper-385]
        ... 11 more
[09:01:01 INFO]: UUID of player dimonpx1203 is ec55e285-4642-38be-9235-f58d10c578f7
[09:01:01 INFO]: dimonpx1203[/45.157.213.23:54725] logged in with entity id 72576 at ([world]-7737.300000011921, 69.0, -5560.263721224083)

```

### Plugin list:
```
AbstractCooldown*, AdvancedEnchantments, AntiRelog, AutoRestarter, Chatty, Citizens, ClearLag, CMI, CMIEInjector*,
CMIPaperLib, Coins, CoreProtect, CrazyAuctionsPlus, CrazyCrates, DeluxeMenus, DeluxeTags*, Dreamiki, DreamTimeAPI*,
DTBots, DTBotsAPI, DTCoins, DTDefender, DTMySQLPlaceholders*, EpicSpawners, Guilds, Insights, LiteBans, LuckPerms,
Matrix, Multiverse-Core, NerfPhantoms, PlaceholderAPI, PluginHiderPlus*, PlugMan, ProtectionStones, ProtocolLib,
ReportManager*, RuneStone, SAML, SkinsRestorer, StackMob, TAB, Vault, ViaBackwards, ViaVersion, VillagerOptimiser,
WGExtender, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags
```

some of plugins are "selfcoded" and are not in public access 

### Actions to reproduce:
Player with nickname OlegMiner100 just joined on server. No more

*UPD*: 
later some other player disconnected, changed minecraft version on 1.15.2 and i've got the same error in console but player is normally playing on server

### Paper build number:
```
> paper version
[09:09:04 INFO]: This server is running Paper version git-Paper-385 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[09:09:04 INFO]: Checking version, please wait...
[09:09:04 INFO]: Previous version: git-Paper-375 (MC: 1.15.2)
[09:09:04 INFO]: You are running the latest version
```

**Comment by electronicboy** [comment]
> com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server

out of our control
