### ISSUE TITLE
ScreamingBedWars (BedWars v0.2.12 stable) not working

### ISSUE THREAD

**Issue by samuel-obiedzinski** [PaperMC/Paper#4159]
Hello,

As in the topic:
[Server thread/WARN]: [BedWars] Task #3359 for BedWars v0.2.12 generated an exception
java.lang.NullPointerException: null
	at org.screamingsandals.bedwars.game.Game.run(Game.java:1675) ~[?:?]
	at org.screamingsandals.bedwars.game.Game$7.run(Game.java:2182) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-385]
	at java.lang.Thread.run(Unknown Source) [?:?]

Could someone help please?

**Comment by rrvk** [comment]
It looks like it is a bedwars issue
https://github.com/ScreamingSandals/BedWars/issues

**Comment by Chew** [comment]
Hello! Thanks for reporting, unfortunately this does appear to be an issue with a 3rd party plugin. I recommend making an issue (or joining their Discord server) and asking for more help. If this ends up being a Paper issue, feel free to open a (more descriptive) issue, following the template. Thank you!
