### ISSUE TITLE
Allow customization of actions to take when player is kicked for invalid item data

### ISSUE THREAD

**Issue by RoboMWM** [PaperMC/Paper#419]
Would like the ability to, for example, run a custom command when the following occur (e.g. to /mail myself and/or ban the player instead of a mere kick with a non-configurable message).

```
2016-09-11 11:43:58 [Server thread/ERROR] Couldn't sign book
io.netty.handler.codec.EncoderException: java.io.EOFException
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.j(PacketDataSerializer.java:231) ~[patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.k(PacketDataSerializer.java:269) ~[patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2264) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-862]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:732) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:631) [patched_1.10.2.jar:git-Paper-862]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.io.EOFException
    at java.io.DataInputStream.readFully(Unknown Source) ~[?:1.8.0_101]
    at java.io.DataInputStream.readUTF(Unknown Source) ~[?:1.8.0_101]
    at java.io.DataInputStream.readUTF(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.server.v1_10_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:80) ~[patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53) ~[patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.j(PacketDataSerializer.java:229) ~[patched_1.10.2.jar:git-Paper-862]
    ... 13 more
2016-09-11 11:43:58 [Server thread/INFO] AJH01 lost connection: Invalid book data!
2016-09-11 11:43:58 [Server thread/INFO] AJH01 disconnected from Creative Fortress
2016-09-11 11:43:58 [Server thread/WARN] handleDisconnection() called twice

2016-09-11 11:44:01 [Server thread/ERROR] Couldn't pick item
java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440) ~[patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.readByte(PacketDataSerializer.java:587) ~[patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.g(PacketDataSerializer.java:147) ~[patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2545) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-862]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:732) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:631) [patched_1.10.2.jar:git-Paper-862]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
2016-09-11 11:44:01 [Server thread/INFO] AJH01 lost connection: Invalid item data!
2016-09-11 11:44:01 [Server thread/INFO] AJH01 disconnected from Creative Fortress
2016-09-11 11:44:01 [Server thread/WARN] handleDisconnection() called twice

2016-09-11 11:44:23 [Server thread/ERROR] Couldn't select trade
java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readInt(EmptyByteBuf.java:470) ~[patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketDataSerializer.readInt(PacketDataSerializer.java:611) ~[patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2302) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-862]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:732) [patched_1.10.2.jar:git-Paper-862]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:631) [patched_1.10.2.jar:git-Paper-862]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
2016-09-11 11:44:23 [Server thread/INFO] AJH01 lost connection: Invalid trade data!
2016-09-11 11:44:23 [Server thread/INFO] [TechFortress] AJH01 quit
2016-09-11 11:44:23 [Server thread/WARN] handleDisconnection() called twice
```

**Comment by aikar** [comment]
I have events for this already. I can just backport them for others to use too.
I use it to auto ban people :P
