### ISSUE TITLE
java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by zLupa** [PaperMC/Paper#4218]
```
[root@lupa lobby]# java -jar server.jar 
Downloading vanilla jar...
Exception in thread "main" java.lang.InternalError: java.util.zip.ZipException: error in opening zip file
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1052)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:215)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:233)
	at sun.security.jca.ProviderList.getService(ProviderList.java:331)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:99)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:1002)
	at java.net.URL.openStream(URL.java:1068)
	at io.papermc.paperclip.Paperclip.checkVanillaJar(Paperclip.java:181)
	at io.papermc.paperclip.Paperclip.checkPaperJar(Paperclip.java:112)
	at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:91)
	at io.papermc.paperclip.Paperclip.main(Paperclip.java:45)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:940)
	at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:801)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:886)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:879)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:878)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1050)
	... 31 more
```

### Plugin list:
- No plugins

### Actions to reproduce (if known):
Start the server and that error appear

### Paper version:
Can't run the server to do '/version,' but i'm using the build **148** from papermc 1.16.2

**Comment by Proximyst** [comment]
Corrupt jar. Redownload the file from our website.

**Comment by zLupa** [comment]
I re-downloaded the jar same error

**Comment by JRoy** [comment]
> I re-downloaded the jar same error

Delete your cache folder in your server directory and try re-running the jar.

**Comment by Chew** [comment]
Also duplicate of #3483

**Comment by zLupa** [comment]
> > I re-downloaded the jar same error
> 
> Delete your cache folder in your server directory and try re-running the jar.

Deleted the cache folder, the same error.

**Comment by Chew** [comment]
0) Ensure server is off
1) Delete cache folder
2) Delete old paper-148.jar
3) Download new paper-150.jar
4) Boot?

**Comment by zLupa** [comment]
1. Server doesn't start so is off.
2. Deleted the cache folder.
3. deleted paper and re-download.

Also i tested in a new folder with no data and the same error appears

**Comment by Chew** [comment]
Definitely weird, what OS are you running this on? Also, try and verify checksums:
Download from: https://papermc.io/api/v1/paper/1.16.2/150/download
md5: `5d581ed3b8734052d64644c505832535`
sha1: `c2bfe9bb18b3ed63c84004c3970854eb34380d12`
And had no issues booting.

**Comment by zLupa** [comment]
I'm using CentOS 7. md5sum is ok
![image](https://user-images.githubusercontent.com/56929033/91500648-4648b880-e89a-11ea-910b-797f376d2fc0.png)

**Comment by Chew** [comment]
Alright, next question is what version of Java? `java -version` output

**Comment by zLupa** [comment]
![image](https://user-images.githubusercontent.com/56929033/91500859-b5bea800-e89a-11ea-89b4-7afa224b692d.png)

openJDK 1.8.0
