### ISSUE TITLE
[BUG] Player is kicked while fishing

### ISSUE THREAD

**Issue by Zefferis** [PaperMC/Paper#4235]
### What behaviour is expected:
Player can fish normally without being kicked

### What behaviour is observed:
Player is kicked randomly when fishing

Error Log:

```[07:15:54] [Server thread/ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace@134f697 for Thneed777[/108.39.147.160:53865]
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.EntityItem.setItemStack(EntityItem.java:453) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.EntityItem.<init>(EntityItem.java:42) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.EntityFishingHook.b(EntityFishingHook.java:436) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.ItemFishingRod.a(ItemFishingRod.java:18) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.ItemStack.a(ItemStack.java:379) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:412) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1521) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

### Steps/models to reproduce:
1. Fishing
2. Crash randomly

### Plugin list:
Plugins (18): AcceptTheRules, BuycraftX, ChestSort, DeathLocation*, DeluxeMenus, DiscordSRV, Essentials, EssentialsChat, GSit, InventoryRollback, LuckPerms, PlaceholderAPI, ResourceWorld, SmoothSleep, spark, TAB, Vault, WorldEdit

All on the latest versions

### Paper version:
Paper version git-Paper-148 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
We are using a custom datapack which modifies fishing loottables, but the tables are registered correctly and were working in 1.16.1; so we don't believe that is the source of the problem.

If the loot-table is required, I can post it as well.

**Comment by Proximyst** [comment]
Always post all the info you can provide :) The loot table would indeed be appreciated.

**Comment by Zefferis** [comment]
```
|   pack.mcmeta
|   
\---data
    \---minecraft
        +---loot_tables
        |   \---gameplay
        |       |   biome_loot.json
        |       |   fishing.json
        |       |   
        |       \---fishing
        |               empty.json
        |               fish.json
        |               junk.json
        |               treasure.json
        |               
...

```

fishing.json:
```
{
    "pools": [
        {
            "rolls": 1,
            "entries": [
                {
                    "type": "loot_table",
                    "name": "minecraft:gameplay/fishing/junk",
                    "weight": 10,
                    "quality": -2
                },
                {
                    "type": "loot_table",
                    "name": "minecraft:gameplay/biome_loot",
                    "weight": 10,
                    "quality": -3
                },
                {
                    "type": "loot_table",
                    "name": "minecraft:gameplay/fishing/treasure",
                    "weight": 5,
                    "quality": 2
                },
                {
                    "type": "loot_table",
                    "name": "minecraft:gameplay/fishing/fish",
                    "weight": 75,
                    "quality": -1
                }
            ]
        }
    ]
}
```
biome_loot.json:
https://paste.gg/p/anonymous/e7b343c34482487ebd501092e9c422b5

fish.json:
https://paste.gg/p/anonymous/4f3414b7c94848e3a340ff1464372e12

junk.json:
https://paste.gg/p/anonymous/3be4fca584e54f939ae60df7671c086f

treasure.json:
https://paste.gg/p/anonymous/8e56ba6cfc0c45d3a886adfc9a1dbc0f


Full Loottable Pack:
[KoG Loot Table Edits v1.1.zip](https://github.com/PaperMC/Paper/files/5140449/KoG.Loot.Table.Edits.v1.1.zip)


You can ignore empty.json; it isn't referenced

**Comment by Chew** [comment]
Build 149 fixed things with loot table handling. Does this error still happen on latest (151)?

**Comment by Zefferis** [comment]
> Build 149 fixed things with loot table handling. Does this error still happen on latest (151)?

b148 is on my production server so I haven't been able to test player kicking with a pool of players on the latest builds.

**Comment by Zefferis** [comment]
Post-kick, when the player re-joins they've got 2 hooks in the water, both bob; the bobber that exists from crash -> rejoin wont go away unless you drop the rod itself.

![image](https://user-images.githubusercontent.com/15270437/91533795-5b870c80-e8c5-11ea-99d0-68ce0c959535.png)

![image](https://user-images.githubusercontent.com/15270437/91533952-95f0a980-e8c5-11ea-9247-c981dba16d79.png)

As a reminder this is still on Build 148; I haven't been able to check if it's still an issue in later builds

**Comment by Zefferis** [comment]
Fishing still prompts a player kick in Build 175, all previously listed plugins and datapacks are the same

```[01:37:00] [Craft Scheduler Thread - 7344/INFO]: [BuycraftX] Fetching all due players...
[01:37:00] [Craft Scheduler Thread - 7344/INFO]: [BuycraftX] Fetched due players (1 found).
[01:38:35] [Server thread/ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace@17c80ca for Zefferis[/73.235.215.205:62461]
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.EntityItem.setItemStack(EntityItem.java:454) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.EntityItem.<init>(EntityItem.java:42) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.EntityFishingHook.b(EntityFishingHook.java:436) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.ItemFishingRod.a(ItemFishingRod.java:18) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.ItemStack.a(ItemStack.java:379) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:412) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1517) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-175]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-175]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[01:38:35] [Server thread/INFO]: Zefferis lost connection: Packet processing error
[01:38:35] [Server thread/INFO]: Potato | `MrZeffy left the game
[01:38:54] [Craft Scheduler Thread - 7351/INFO]: [BuycraftX] Sending 1 analytic events
[01:39:29] [Server thread/INFO]: MissLovedChi issued server command: /home
[01:39:49] [Server thread/INFO]: This server is running Paper version git-Paper-175 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[01:39:49] [Server thread/INFO]: Checking version, please wait...
[01:39:50] [Thread-192/INFO]: Previous version: git-Paper-174 (MC: 1.16.2)
[01:39:50] [Thread-192/INFO]: You are 4 version(s) behind```

**Comment by chickeneer** [comment]
Although the error message mentions Air. It can also trigger if it is a stack of quantity zero (or less).
I don't use custom loot-tables. But I find this part in your tables suspicious. https://paste.gg/p/anonymous/e7b343c34482487ebd501092e9c422b5
`"functions": [{"function": "minecraft:set_count","count": {"min": 0.0,"max": 1.0}}],`
or `{"function": "minecraft:set_count","count": {"min": -7.0,"max": 1.0}}`

I would be interested if anyone knows more about that. It is entirely possible that it erroring is a bug, but just looking to identify what about the custom loot-table is causing the problem.

**Comment by Zefferis** [comment]
@chickeneer I changed the loottables to remove the negative values and set them to a min of 0 and max of 1; the error persists

```[06:28:58] [Server thread/ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace@3e1f308a for Zefferis[/98.208.98.141:57117]
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.EntityItem.setItemStack(EntityItem.java:454) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.EntityItem.<init>(EntityItem.java:42) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.EntityFishingHook.b(EntityFishingHook.java:436) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.ItemFishingRod.a(ItemFishingRod.java:18) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.ItemStack.a(ItemStack.java:379) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:412) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1522) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-184]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[06:28:59] [Server thread/INFO]: Zefferis lost connection: Packet processing error``

**Comment by Chew** [comment]
Wouldn't 0 of an item be air?

**Comment by Zefferis** [comment]
No, that just means you didn't get an item, in Vanilla Singpleplayer you don't get an item but still gain exp

I just retested it with the loot table having a min and max of both 0.


@Chew 

edit: And no errors are thrown in the minecraft output log

**Comment by Zefferis** [comment]
Alright yeah I double checked with a local hosted paper server

On Vanilla MC (Single Player 1.16.2) a loot table that gives no item simply gives no item but grants exp and the game continues on with no errors thrown and no issues

On Paper fishing up no item results in that error, so it deviates from Vanilla by kicking the client.

**Comment by Chew** [comment]
Ah, I see. There might be some weird behavior of no items == air or whatever. It would be absolutely lovely if you could reproduce on spigot or craftbukkit so we can toss the error up There as well if it's on their end!

**Comment by Zefferis** [comment]
@Chew I don't have built tools so I got an outdated spigot version, the error is still thrown but the player is not kicked

Spigot 1.16.2: (Also having an error but no kick)
```[23:26:41 FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityItem.setItemStack(EntityItem.java:412) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityItem.<init>(EntityItem.java:39) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityFishingHook.b(EntityFishingHook.java:431) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.ItemFishingRod.a(ItemFishingRod.java:18) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.ItemStack.a(ItemStack.java:318) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:397) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1347) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[23:27:15 INFO]: This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

[23:27:15 INFO]: You are 47 version(s) behind
```
Reminder for readers: Vanilla MC does not throw this error or kick players, no item in fishing loottable (potentially others too)  is intended behavior that doesn't work in spigot and paper

**Comment by ccorp2002** [comment]
Getting a similar error, but when mobs are killed/mobs kill eachother, the player gets kicked, and/or the mob just vanishes. When the player rejoins, no items are dropped.

EDIT: 1.16.3; paper-220.


**When Mobs exist.**
`[12:52:01 WARN]: Entity threw exception at Earth:712.0396460896923,15.07032995476941,-71.25
[12:52:01 WARN]: java.lang.IllegalArgumentException: Cannot drop air
[12:52:01 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityItem.setItemStack(EntityItem.java:462)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityItem.<init>(EntityItem.java:44)
[12:52:01 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.dropItem(CraftWorld.java:750)
[12:52:01 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:826)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityLiving.d(EntityLiving.java:1514)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityLiving.die(EntityLiving.java:1441)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1270)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityInsentient.damageEntity(EntityInsentient.java:275)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityBat.damageEntity(EntityBat.java:237)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.Entity.burnFromLava(Entity.java:567)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.Entity.entityBaseTick(Entity.java:506)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityLiving.entityBaseTick(EntityLiving.java:267)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityInsentient.entityBaseTick(EntityInsentient.java:244)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.Entity.tick(Entity.java:455)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2455)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityInsentient.tick(EntityInsentient.java:332)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.EntityBat.tick(EntityBat.java:123)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:1300)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:900)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:959)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1429)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:381)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1280)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1006)
[12:52:01 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[12:52:01 WARN]:        at java.lang.Thread.run(Thread.java:748)`



**When Mobs are killed by players/other mobs**
`
[11:47:16] [Server thread/ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R2.PacketPlayInUseEntity@2d2cba39 for C_Corp2002[/192.168.86.1:39588]
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.EntityItem.setItemStack(EntityItem.java:454) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.EntityItem.<init>(EntityItem.java:42) ~[patched_1.16.3.jar:git-Paper-220]
	at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.dropItem(CraftWorld.java:748) ~[patched_1.16.3.jar:git-Paper-220]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:814) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.EntityLiving.d(EntityLiving.java:1491) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.EntityLiving.die(EntityLiving.java:1420) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1262) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.EntityHuman.attack(EntityHuman.java:1087) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.EntityPlayer.attack(EntityPlayer.java:1828) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2136) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[11:47:16] [Server thread/INFO]: C_Corp2002 lost connection: Packet processing error
[11:47:16] [Server thread/INFO]: C_Corp2002 left the game
`

**Comment by Zefferis** [comment]
Just as a quick reminder, these issues do not pop up in **Vanilla MC** at all, 

Errors are thrown in **Spigot** but no crashes;

On **Paper** the client crashes.

**Comment by schoentoon** [comment]
I managed to reproduce this quite easily, it's very much the item count being 0 or even negative. I could see the use for an item count of 0 (no item at all). But I would also say that the negative number is undefined behaviour and only does what it does by chance.
