### ISSUE TITLE
NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_10_R1.CrashReport

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#425]
Paper dev 865

@Zbob750 Updated Paper today and had a server crashed. No idea what caused it, no crash log was generated. Now any time someone logs in, server crashes. :( 

```
[13:42:53] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Error generating crash report
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:858) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632) [patched_1.10.2.jar:git-Paper-865]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_10_R1.CrashReport
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:856) ~[patched_1.10.2.jar:git-Paper-865]
    ... 4 more
[13:42:53] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_10_R1.CrashReport
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:856) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632) [patched_1.10.2.jar:git-Paper-865]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

```
[13:48:45] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Error generating crash report
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:858) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632) [patched_1.10.2.jar:git-Paper-865]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_10_R1.CrashReport
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:856) ~[patched_1.10.2.jar:git-Paper-865]
    ... 4 more
[13:48:45] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_10_R1.CrashReport
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:856) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632) [patched_1.10.2.jar:git-Paper-865]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by AlfieC** [comment]
Did you update it whilst it was running? I've done it once by accident and had that exact error.

**Comment by zachbr** [comment]
That's what it looks like happened.

**Comment by mibby** [comment]
I do not update while the server is running. The crash was hours after the update and occurred every time someone tried logging in when restarting after it initially occurred.

The crashing issue seemed to have been caused by a chunk corruption with worldedit usage from someone. Replacing everything in a chunk region selection entirely with 175:2 (grass). I ran a region recovery and cleaned up all the grass. Server doesn't crash when loading the area anymore. Though it is odd that a crash report wasn't generated. Is the class missing?

I had another crash occur post 'region fix'. Entirely different error. Restarted the server again and loaded into the area, no crash. 

```
[14:30:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_10_R1.ReportedException: Ticking player
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:878) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632) [patched_1.10.2.jar:git-Paper-865]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
    at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:232) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.World.g(World.java:1713) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:666) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:643) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:867) ~[patched_1.10.2.jar:git-Paper-865]
    ... 4 more
[14:30:50] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.NullPointerException
    at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:232) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.World.g(World.java:1713) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:666) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:643) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:867) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733) ~[patched_1.10.2.jar:git-Paper-865]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632) [patched_1.10.2.jar:git-Paper-865]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

That crash did generate a crash log. So, I dunno. :D 

```
Description: Ticking player

java.lang.NullPointerException: Ticking player
    at java.util.LinkedList$ListItr.next(LinkedList.java:893)
    at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:232)
    at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738)
    at net.minecraft.server.v1_10_R1.World.g(World.java:1713)
    at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:666)
    at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496)
    at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:643)
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:867)
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733)
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
    at java.util.LinkedList$ListItr.next(LinkedList.java:893)
    at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:232)
    at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738)
    at net.minecraft.server.v1_10_R1.World.g(World.java:1713)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.server.v1_10_R1.EntityPlayer)
    Entity ID: 8591
    Entity Name: player
    Entity's Exact location: -6465.42, 85.50, 1947.68
    Entity's Block location: World: (-6466,85,1947), Chunk: (at 14,5,11 in -405,121; contains blocks -6480,0,1936 to -6465,255,1951), Region: (-13,3; contains chunks -416,96 to -385,127, blocks -6656,0,1536 to -6145,255,2047)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:666)
    at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496)
    at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:643)

```

Is this crash a problem that can be fixed or is it something to ignore / one off issue?

**Comment by AlfieC** [comment]
Looks like one of your plugins is doing something async - maybe some more AsyncCatchers will identify your issue.
