### ISSUE TITLE
Exception ticking world (1.16.2)

### ISSUE THREAD

**Issue by PapiCapi** [PaperMC/Paper#4255]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___
```
[12:34:02] [Server thread/INFO]: Worao issued server command: /warp end
[12:34:25] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R2.ReportedException: Exception ticking world
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1373) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-168]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:368) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.flagDirty(ChunkProviderServer.java:901) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.WorldServer.notify(WorldServer.java:1542) ~[patched_1.16.2.jar:git-Paper-168]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:185) ~[patched_1.16.2.jar:git-Paper-168]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:167) ~[patched_1.16.2.jar:git-Paper-168]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:784) ~[patched_1.16.2.jar:git-Paper-168]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:773) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.BlockGrowingTop.tick(BlockGrowingTop.java:32) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.b(BlockBase.java:562) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:705) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:847) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:825) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:743) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.2.jar:git-Paper-168]
	... 5 more
[12:34:25] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:368) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.flagDirty(ChunkProviderServer.java:901) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.WorldServer.notify(WorldServer.java:1542) ~[patched_1.16.2.jar:git-Paper-168]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:185) ~[patched_1.16.2.jar:git-Paper-168]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:167) ~[patched_1.16.2.jar:git-Paper-168]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:784) ~[patched_1.16.2.jar:git-Paper-168]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:773) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.BlockGrowingTop.tick(BlockGrowingTop.java:32) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.b(BlockBase.java:562) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:705) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:847) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:825) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:743) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-168]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-168]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[12:34:25] [Server thread/ERROR]: This crash report has been saved to: /home/server/sky1.15/./crash-reports/crash-2020-08-31_12.34.25-server.txt
[12:34:25] [Server thread/INFO]: Stopping server
```

### Plugin list:
___A list of your plugins___
AntiAFK*, AntiDecoCombat*, AsyncWorldEdit, Bank, BentoBox, BlockLocker, ChatItem, ChestCommands, ChestShop, Core, CoreProtect, DeACoudre, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, Fe*, Grades, HolographicDisplays, IllegalStack, LuckPerms, MinewebBridge*, ModReq*, MoncubeCore, Multiverse-Core, OnTime*, OpenInv, PlanningsEvents, PlugMan, ProtocolLib, ProtocolSupport, PVPControl, RFChairs, Shopkeepers, SkQuery, Skript, TAB, TokenManager, UltimateStacker, Vault, VillagerOptimiser, VoidGenerator, VoteMoncube, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Seems to happen when the player teleports in end in my case.

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
git-Paper-172 (MC: 1.16.2) , however in git-Paper-168 (MC: 1.16.2) i don't have any issue

**Comment by PapiCapi** [comment]
I just had the issue using paper 168 and while the player was teleporting to nether, so what i said a few days ago was wrong. Sorry

**Comment by Mikgreg** [comment]
This is happening on our server too,  when players teleport around the server stops with the error posted in the OP. Using paper 182.

**Comment by PapiCapi** [comment]
Can you send your plugins so we can compare which ones we have in common ?

**Comment by Mikgreg** [comment]
[20:49:02 INFO]: Plugins (64): AdvancedAchievements, AdvancedSpawners, AntiCooldown, BeehivesPro, BlockyRanks, BuycraftX, ChatControl, ChatGames, CheckFly*, Chunky, Citizens, CommandRegions*, CoreProtect, CrazyCrates, CS-CoreLib, DeathMessagesPrime, DeluxeChat, eGlow, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, FastAsyncWorldEdit, GriefPrevention, GriefPreventionFlags, GSit, GuiRedeemMCMMO*, HeadsPlus, HideStream*, HolographicDisplays, ImmortalTags, LuckPerms, Marriage, mcMMO, MoneyPouch*, Multiverse-Core, MVdWPlaceholderAPI*, MysterySpawners*, NerfPhantoms, NoFlyZone, OldCombatMechanics, PlaceholderAPI, PlayerBTH*, PlayerVaults, PortableHorses, ProtocolLib, ProtocolSupport, Quests, QuickShop, SignEdit, SilkSpawners, spark, SuperVanish, TAB, TempFly, UltimateAutoRestart, Vault, VoidGenerator, VoidSpawn, Vouchers, Wild, WorldBorder, WorldEdit, WorldGuard

**Comment by PapiCapi** [comment]
So the ones we have in common are : 
CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, HolographicDisplays, LuckPerms, Multiverse-Core, ProtocolLib, ProtocolSupport, TAB, Vault, VoidGenerator, WE and WG.

It's really strange because i got all these plugins on others server in paper 1.16.2 but don't have any issue on them

**Comment by PapiCapi** [comment]
I still have this issue and don't understand why this is happening. @Mikgreg , did you find any clue ?

**Comment by Mikgreg** [comment]
For us it was caused by our AdvancedSpawners plugin spawning an obscene amount of entities (thousands per minute) from spawners. Fixing this stopped our crashes. Try checking your timings to see if something similar is happening to you in terms of mass amounts of entities?

**Comment by PapiCapi** [comment]
I really don't understand what's wrong with my timings. If you have a bit of time and want to help me, would you help me seeing what's wrong here : https://timings.aikar.co/?id=0ade5fada097464b979055ca761ca85a#timings

**Comment by biels** [comment]
Same issue here on paper 1.16.3 v206. Server crashes completely.
```
version
[23:41:50 INFO]: This server is running Paper version git-Paper-206 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[23:41:50 INFO]: Checking version, please wait...
[23:41:50 INFO]: Previous version: git-Paper-99 (MC: 1.16.1)
[23:41:50 INFO]: You are running the latest version
```

**Comment by aikar** [comment]
@biels please provide logs from 206. as 206 should have this fixed....

**Comment by biels** [comment]
Here are the logs @aikar 
The server crashes when a player joins. Without any players the server doesn't crash.
```
[23:42:42 INFO]: biel[/81.45.41.224:24410] logged in with entity id 230 at ([world]266.5, 64.0, 257.5)
[23:42:45 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R2.ReportedException: Exception ticking world
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1373) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-206]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_172]
        at net.minecraft.server.v1_16_R2.WorldAccess.addAllEntities(WorldAccess.java:13) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.SpawnerCreature.spawnMobsInternal(SpawnerCreature.java:254) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.SpawnerCreature.spawnMobs(SpawnerCreature.java:180) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.SpawnerCreature.a(SpawnerCreature.java:154) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:843) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:825) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:743) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-206]
        ... 5 more
[23:42:45 ERROR]:       Cause of unexpected exception was
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_172]
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_172]
        at net.minecraft.server.v1_16_R2.WorldAccess.addAllEntities(WorldAccess.java:13) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.SpawnerCreature.spawnMobsInternal(SpawnerCreature.java:254) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.SpawnerCreature.spawnMobs(SpawnerCreature.java:180) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.SpawnerCreature.a(SpawnerCreature.java:154) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:843) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:825) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:743) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-206]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
[23:42:45 ERROR]: This crash report has been saved to: F:\Servers MC\FSTestServer\.\crash-reports\crash-2020-09-28_23.42.45-server.txt
[23:42:45 INFO]: Stopping server
[23:42:45 INFO]: [PlugReloader] Disabling PlugReloader v1.0
[23:42:45 INFO]: [WorldEdit] Disabling WorldEdit v7.1.0;8e55131
```

**Comment by Proximyst** [comment]
That is not the same issue. Please open a new issue.
