### ISSUE TITLE
Automatic server update 1.16.2

### ISSUE THREAD

**Issue by SergiSvK** [PaperMC/Paper#4263]
### Server Crash , Alert!
I usually use version 1.16.1, and without prior notice it was updated to a non-stable experimental version. 
Then when I realized that it had been updated to version 1.16.2. I decided to go back to the previous one and the following errors come out.
[Log Server Full](https://mcpaste.io/e74e3479ec64b802)
```md
01.09 09:02:09 [Server] INFO [TrMenu] INFO | Cargado. TrMenu v1.22 ha sido activado.
01.09 09:02:09 [Server] INFO [TrHologram] INFO | Loaded. TrHologram v1.11 has been enabled.
01.09 09:02:09 [Server] INFO [AuctionHouse] Registered Service Provider Vault for Vault's Economy API
01.09 09:02:09 [Server] INFO [AuctionHouse] Registered Service Provider LuckPerms for Vault's Chat API
01.09 09:02:09 [Server] INFO [Jobs] Successfully linked with Vault.
01.09 09:02:10 [Server] INFO [Citizens] Cargando a 15 NPCs.
01.09 09:02:10 [Server] INFO [Minecord] Hooking into PlaceholderAPI...
01.09 09:02:10 [Server] INFO [TrMenu] INFORMACION | Cargado 24 menus... [2419 Ms]
01.09 09:02:10 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [1]
01.09 09:02:10 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [2]
01.09 09:02:10 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [3]
01.09 09:02:10 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [4]
01.09 09:02:10 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [5]
01.09 09:02:10 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [6]
01.09 09:02:10 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [7]
01.09 09:02:10 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [8]
01.09 09:02:15 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [9]
01.09 09:02:15 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [10]
01.09 09:02:15 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [11]
01.09 09:02:15 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [12]
01.09 09:02:15 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [13]
01.09 09:02:15 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [14]
01.09 09:02:15 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [15]
01.09 09:02:17 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [16]
01.09 09:02:19 [Server] INFO [INFO] [BannerBoard] Succesfully loaded BannerBoard [17]
01.09 09:02:19 [Server] INFO [TrHologram] INFO | Loaded 4 holograms... [124 Ms]
01.09 09:02:19 [Server] Startup Done (99.795s)! For help, type "help"
01.09 09:02:19 [Server] WARN Can't keep up! Is the server overloaded? Running 14583ms or 291 ticks behind
01.09 09:02:19 [Server] INFO Timings Reset
01.09 09:02:19 [Server] INFO [Vault] Checking for Updates ...
01.09 09:02:20 [Server] INFO [RandomTeleport] Safe location added for Survival (1/5)
01.09 09:02:20 [Server] INFO [Vault] No new version available
01.09 09:02:20 [Server] INFO [RandomTeleport] Safe location added for Survival (2/5)
01.09 09:02:20 [Server] WARN java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2578 > 2567
01.09 09:02:20 [Server] WARN at net.minecraft.server.v1_16_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)
01.09 09:02:20 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)
01.09 09:02:20 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)
01.09 09:02:20 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)
01.09 09:02:20 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)
01.09 09:02:21 [Server] INFO Stopping server
```

### Plugin list:
___A list of your plugins:___
![Image of Plugin Server](https://i.imgur.com/7vS5vE3.png)

### Paper version:

Current version paper-1.16.1.jar

**Comment by rrvk** [comment]
This looks like a feature that is added that prefents chunk to be loaded if they are generated with a higher minecraft version
See https://github.com/PaperMC/Paper/commit/7470c3ef69fa31044473e39ad03a8e133026d45d

Also the newest 1.16.2 version of paper is stable! (and 1.16.1 is not supported anymore)

**Comment by danny6167** [comment]
Paper doesn't automatically update by itself.
Either you or your host has something in place that did this.

The errors are by design, to prevent you from corrupting your world

**Comment by electronicboy** [comment]
World downgrades are unsupported, there is a flag to bypass that, or using an older version before that safety patch, but, expect world corruption. best advice will be to use a host which doesn't update jars on you...
