### ISSUE TITLE
scoreboard tag error

### ISSUE THREAD

**Issue by tjwogud** [PaperMC/Paper#4309]
### What behaviour is expected:
add scoreboard tag

### What behaviour is observed:
when i use '/tag @p list' after addScoreboardTag() work, i lose connection and exception on bukkit.

### Steps/models to reproduce:
Failed to save player data for tjwogud
net.minecraft.server.v1_16_R2.ReportedException: Saving entity NBT
        at net.minecraft.server.v1_16_R2.Entity.save(Entity.java:1637) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.WorldNBTStorage.save(WorldNBTStorage.java:30) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PlayerList.savePlayerFile(PlayerList.java:486) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PlayerList.disconnect(PlayerList.java:526) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1590) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.NetworkManager.handleDisconnection(NetworkManager.java:497) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:165) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-187]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_16_R2.NBTTagString.a(NBTTagString.java:45) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.Entity.save(Entity.java:1586) ~[patched_1.16.2.jar:git-Paper-187]

### Plugin list:
there's only one plugin.(i made) it uses addScoreboardTag().

### Paper version:
git-Paper-187 (MC: 1.16.2)

**Comment by electronicboy** [comment]
Looks like you added a null string, there is no logic to prevent that, but that will cause this exception

**Comment by tjwogud** [comment]
ohhhhhh thanks there was wrong code
