### ISSUE TITLE
Failed to schedule load callback for chunk 

### ISSUE THREAD

**Issue by jeanhissette** [PaperMC/Paper#4323]
```
>.... [11:07:16 FATAL]: Failed to schedule load callback for chunk [66, 136]
java.util.concurrent.CompletionException: net.minecraft.server.v1_15_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:Sign
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_262]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_262]
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618) ~[?:1.8.0_262]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_262]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_262]
at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1057) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1104) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:634) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1115) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-387]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: net.minecraft.server.v1_15_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:Sign
at net.minecraft.server.v1_15_R1.MinecraftKey.<init>(MinecraftKey.java:29) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftKey.<init>(MinecraftKey.java:34) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.TileEntity.create(TileEntity.java:121) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:636) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.ChunkRegionLoader.lambda$createLoadEntitiesConsumer$6(ChunkRegionLoader.java:310) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.Chunk.addEntities(Chunk.java:829) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$46(PlayerChunkMap.java:1277) ~[patched_1.15.2.jar:git-Paper-387]
at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[patched_1.15.2.jar:git-Paper-387]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.15.2.jar:git-Paper-387]
at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$c$47(PlayerChunkMap.java:1260) ~[patched_1.15.2.jar:git-Paper-387]
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_262]
... 14 more
>.... [11:07:16 ERROR]: Encountered an unexpected exception
java.lang.UnsupportedOperationException: Not supported.
at org.bukkit.craftbukkit.v1_15_R1.scheduler.MinecraftInternalPlugin.getLogger(MinecraftInternalPlugin.java:75) ~[patched_1.15.2.jar:git-Paper-387]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.MinecraftInternalPlugin.getLogger(MinecraftInternalPlugin.java:18) ~[patched_1.15.2.jar:git-Paper-387]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-387]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

Paper version: Latest (387)

```
Plugins:
(28): AdvancedRegionMarket, AuthMe, ChestShop, Citizens, CoreProtect, DeluxeTags*, DWG_OasisDesert, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, HolographicDisplays, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, PlaceholderAPI, PlayerKits, ProtocolLib, Shopkeepers, SignBoard, SkinsRestorer, SuperVanish, Vault, VoidGenerator, WorldEdit, WorldGuard
```

**Comment by aikar** [comment]
Please post full logs of stuff before this too.

Ultimately, you have a corrupt chunk in that it has a tile entity with a really old format.

Are you converting a really old world or loading any old schematics? something went wrong with Data Fixers or you somehow got a chunk with a current version marked with unconverted data.


So need more context on your world state and whats special about this chunk.

One improvement I can see we can do is to try catch E/TE creation so it only erases the invalid TE instead of crashing the load process.

**Comment by jeanhissette** [comment]
https://pastebin.com/CVw5wmUM

Full crash-report, sorry for not posting earlier.

It's a custom map, but not old one. It was designed for versions 1.14 ~ 1.16, if i'm not wrong. No schematics, just the map.

**Comment by electronicboy** [comment]
using worldpainter or something? Pretty sure there was somebody who painted a world and was having this issue

**Comment by jeanhissette** [comment]
The map was created using worldpainter, but right now, there are only players playing vanilla. No one is using worldedit the moment the crash happen.

When we restart the server, we quickly tp the player out of the chunk.

**Comment by aikar** [comment]
This would be a world painter issue putting TE data in a corrupt state into the chunk data then.
