### ISSUE TITLE
Strange Crash

### ISSUE THREAD

**Issue by RJhan02** [PaperMC/Paper#4329]
### Link/paste of stack trace
Log:
[14:34:55] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R2.ReportedException: Exception while ticking
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1373) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-196]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:368) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.flagDirty(ChunkProviderServer.java:901) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.WorldServer.notify(WorldServer.java:1563) ~[patched_1.16.3.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:185) ~[patched_1.16.3.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:167) ~[patched_1.16.3.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:787) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.BlockFire.tickAlways(BlockFire.java:219) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:558) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.WorldServer.b(WorldServer.java:803) ~[patched_1.16.3.jar:git-Paper-196]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:306) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.TickListServer.b(TickListServer.java:47) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:461) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-196]
	... 5 more
[14:34:55] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:368) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.flagDirty(ChunkProviderServer.java:901) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.WorldServer.notify(WorldServer.java:1563) ~[patched_1.16.3.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:185) ~[patched_1.16.3.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:167) ~[patched_1.16.3.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:787) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.BlockFire.tickAlways(BlockFire.java:219) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:558) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.WorldServer.b(WorldServer.java:803) ~[patched_1.16.3.jar:git-Paper-196]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:306) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.TickListServer.b(TickListServer.java:47) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:461) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-196]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[14:34:55] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Juan\Desktop\DC\.\crash-reports\crash-2020-09-15_14.34.55-server.txt
[14:34:55] [Server thread/INFO]: Stopping server

Crash Report: https://pastebin.com/YU6B3EdD

### Plugin list:
{ BetterSleeping3 v3.0.3 be.dezijwegel.bettersleeping.BetterSleeping [vallas], ClearLag v3.1.6 me.minebuilders.clearlag.Clearlag [bob7l], SkinsRestorer v13.8.4 skinsrestorer.bukkit.SkinsRestorer [Th3Tr0LLeR, McLive, DoNotSpamPls, knat], TAB v2.8.6 me.neznamy.tab.platforms.bukkit.Main [NEZNAMY], BlockLocker v1.8.1 nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl [Rutger Kok],}

### Paper version:
This server is running Paper version git-Paper-196 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT).

**Comment by Chew** [comment]
99% sure this is plugin related, but please upload C:\Users\Juan\Desktop\DC.\crash-reports\crash-2020-09-15_14.34.55-server.txt to https://pastebin.com and send the link

**Comment by RJhan02** [comment]
https://pastebin.com/YU6B3EdD 
it's this?

**Comment by RJhan02** [comment]
Well, I think I found the reason for the crash but it’s too weird, I tried it with all the default settings, no plugins and no datapacks (counting I tested it on different devices).

Make a platform on layer 1 (Y=1) of spruce_leaves in the end dimension and then burn it, after a few seconds the server crashes.

Here the crash report evidence: https://pastebin.com/RLzaqESg

**Comment by HexedHero** [comment]
> Well, I think I found the reason for the crash but it’s too weird, I tried it with all the default settings, no plugins and no datapacks (counting I tested it on different devices).
> 
> Make a platform on layer 1 (Y=1) of spruce_leaves in the end dimension and then burn it, after a few seconds the server crashes.
> 
> Here the crash report evidence: https://pastebin.com/RLzaqESg

lmfao, that doesn't do anything for me. Feel like I've been trolled.

**Comment by Chew** [comment]
Reproduce without plugins, likely some plugin messing up

**Comment by Proximyst** [comment]
Fixed by https://github.com/PaperMC/Paper/commit/5a988f2e45e9fc9450645bb65cfffb4d9ce6c886
