### ISSUE TITLE
Server bug with crashing

### ISSUE THREAD

**Issue by auriium** [PaperMC/Paper#4337]
### What behaviour is expected:
Paper able to unload slimeworldmanager maps correctly

### What behaviour is observed:
Whenever a slimeworldmanager map is unloaded using the Bukkit.unloadWorld(map, false) method the server will crash

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___
![image](https://user-images.githubusercontent.com/29739282/93542891-12980600-f90f-11ea-98f1-89c17cbc4912.png)

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
![image](https://user-images.githubusercontent.com/29739282/93542907-1d529b00-f90f-11ea-898b-26387f6d72ad.png)

### Anything else:
___Anything else you think may help us resolve the problem___
>.... [20:00:14 ERROR]: Add callback for map threw exception
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
at net.minecraft.server.v1_15_R1.DataWatcherRegistry$19.a(SourceFile:177) ~[server.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.DataWatcher$Item.d(DataWatcher.java:301) ~[server.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.DataWatcher.c(DataWatcher.java:198) ~[server.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PacketPlayOutEntityMetadata.<init>(SourceFile:21) ~[server.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:285) ~[server.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:267) ~[server.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:2393) ~[server.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:2206) ~[server.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:1500) ~[server.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$new$9(PlayerChunkMap.java:431) ~[server.jar:git-Paper-385]

**Comment by auriium** [comment]
Oops, wrong plugins list
![image](https://user-images.githubusercontent.com/29739282/93543217-dca75180-f90f-11ea-9d79-a315da30ad37.png)

**Comment by auriium** [comment]
Disregard this; I don't know how to use the datawatcher. Issue solved :)
