### ISSUE TITLE
Paper not ignoring invalid LootTable on storage blocks when it should.

### ISSUE THREAD

**Issue by mygizli04** [PaperMC/Paper#4341]
### What behaviour is expected:
When trying to create a block with invalid lootTable NBT ( such as {LootTable:"minecraft:"} ) the server should ignore this NBT.

### What behaviour is observed:
When trying with /give this issue doesn't occur and the server ignores the invalid lootTable as it should, but when using /data merge the server does not ignore the invalid NBT and applies it to the block ( unlike with Vanilla, Craftbukkit, and spigot which ignore it as they should ). This results in a block that's not interactable, because if you try to use/break it outside of /setblock or /fill, you will immediately get kicked with "Packet processing error"

When trying to use the chest:
```
[14:35:59 INFO]: how_are_you issued server command: /data merge block -175 4 -140 {LootTable:"minecraft:"}
[14:35:59 INFO]: §7§o[how_are_you: Modified block data of -175, 4, -140]
[14:36:00 ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R2.PacketPlayInUseItem@31aed1e for how_are_you[/127.0.0.1:50558]
java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: 
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:49) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_16_R2.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.16.3.jar:git-Paper-198]
	at com.destroystokyo.paper.loottable.PaperTileEntityLootableInventory.getLootTable(PaperTileEntityLootableInventory.java:19) ~[patched_1.16.3.jar:git-Paper-198]
	at com.destroystokyo.paper.loottable.PaperLootableInventoryData.shouldReplenish(PaperLootableInventoryData.java:43) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.TileEntityLootable.d(TileEntityLootable.java:52) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.TileEntityLootable.createMenu(TileEntityLootable.java:148) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.EntityPlayer.openContainer(EntityPlayer.java:1257) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.BlockChest.interact(BlockChest.java:217) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.interact(BlockBase.java:578) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:515) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-198]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[14:36:00 INFO]: how_are_you lost connection: Packet processing error
```

When breaking it ( which does break but kicks you anyway ):
```
[14:39:49 ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R2.PacketPlayInBlockDig@3c0786e3 for how_are_you[/127.0.0.1:50666]
java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: 
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:49) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_16_R2.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.16.3.jar:git-Paper-198]
	at com.destroystokyo.paper.loottable.PaperTileEntityLootableInventory.getLootTable(PaperTileEntityLootableInventory.java:19) ~[patched_1.16.3.jar:git-Paper-198]
	at com.destroystokyo.paper.loottable.PaperLootableInventoryData.shouldReplenish(PaperLootableInventoryData.java:43) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.TileEntityLootable.d(TileEntityLootable.java:52) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.TileEntityLootable.getItem(TileEntityLootable.java:92) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.InventoryUtils.dropInventory(SourceFile:26) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.InventoryUtils.dropInventory(SourceFile:17) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.BlockChest.remove(BlockChest.java:201) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.remove(BlockBase.java:554) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.Chunk.setType(Chunk.java:502) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.World.a(World.java:404) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:367) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.World.a(World.java:527) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:367) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:173) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1385) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-198]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[14:39:49 INFO]: how_are_you lost connection: Packet processing error
```

/setblock and /fill does work on these blocks, but they'll not update on the client, and require for it to be updated ( for example putting a block in it's place )

### Steps/models to reproduce:
1. Put a chest down
2. Use` /data merge block x y z {LootTable:"minecraft:"}` on the block ( using /give with the NBT doesn't work, but getting the chest with the NBT on player's creative inventory does )
3. The issue above occurs.

### Plugin list:
No plugins with completely new server.

### Paper version:
```
This server is running Paper version git-Paper-198 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
You are running the latest version
```

**Comment by aikar** [comment]
Minecraft does not handle invalid here either. If you do minecraft:A it also errors in single player

The only difference is the bukkit validation also disallows empty strings where as mojang does not.

But both are invalid, and mojang should disallow empty too.

Nothing to do here.
