### ISSUE TITLE
Fire spreading to invalid locations crashes the server

### ISSUE THREAD

**Issue by Proximyst** [PaperMC/Paper#4350]
### Link/paste of stack trace

```
[20:39:18 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R2.ReportedException: Exception while ticking
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1373) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-202]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:368) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.flagDirty(ChunkProviderServer.java:905) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.WorldServer.notify(WorldServer.java:1570) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:185) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.update(CraftBlockState.java:167) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:787) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.BlockFire.tickAlways(BlockFire.java:219) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:558) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.WorldServer.b(WorldServer.java:803) ~[patched_1.16.3.jar:git-Paper-202]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:306) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.TickListServer.b(TickListServer.java:47) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:461) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-202]
	... 5 more
```

### Plugin list:
None required; I used WorldEdit to make this easy to reproduce, however.

### Actions to reproduce (if known):

1. Lay out a large square of leaves at Y 0.
1. `//overlay fire`
1. Observe the server crash

### Paper version:

`This server is running Paper version git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)`

**Comment by Chew** [comment]
Dang reported and fixed in like minutes, you love to see it.
