### ISSUE TITLE
ServerInternalException: Attempted to place a tile entity where there was no entity tile!

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#437]
Paper (Spigot 1.10.2) dev 881
WorldEdit v6.1.5 dev 3623

These errors occur all the time for me when loading chunks that had a worldedit schematic pasted and undone, or a player fully rolled back from a grief. Even seemingly random in areas that don't look to have been touched by worldedit / a player rollback.

Should some form of recovery or suppression be added or just safe to ignore all the exceptions that occur? 

```
[23:17:33] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_10_R1.TileEntityChest@6ec73fd) at -9626,102,-5459 (AIR) where there was no entity tile!
Chunk coordinates: -9632,-5472
[23:17:33] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:782)
[23:17:33] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:755)
[23:17:33] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:425)
[23:17:33] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[23:17:33] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[23:17:33] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[23:17:33] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[23:17:33] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[23:17:33] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:820)
[23:17:33] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[23:17:33] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734)
[23:17:33] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633)
[23:17:33] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by zachbr** [comment]
Will work on mitigation soon, likely just remove these corrupt TEs.

**Comment by birkhofflee** [comment]
I still get the error.

```
[22:06:12 INFO]: UUID of player Birkhoff is fe90fe38-f25c-4a51-953d-644b632a103e
[22:06:12 WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_11_R1.TileEntityChest@6ad64b4) at 1584,58,80
9 (AIR) where there was no entity tile!
Chunk coordinates: 1584,800
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.Chunk.a(Chunk.java:782)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.Chunk.a(Chunk.java:755)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:439)
[22:06:12 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[22:06:12 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[22:06:12 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[22:06:12 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[22:06:12 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.lambda$syncChunkLoad$0(ChunkIOExecutor.java:18)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.MCUtil.ensureMain(MCUtil.java:66)
[22:06:12 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[22:06:12 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:174)
[22:06:12 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:618)
[22:06:12 WARN]:        at com.wasteofplastic.askyblock.GridManager.removeMobs(GridManager.java:1587)
[22:06:12 WARN]:        at com.wasteofplastic.askyblock.listeners.JoinLeaveEvents.onPlayerJoin(JoinLeaveEvents.java:277)
[22:06:12 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor785.execute(Unknown Source)
[22:06:12 WARN]:        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[22:06:12 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[22:06:12 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:06:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[22:06:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:352)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:178)
[22:06:12 WARN]:        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:121)
[22:06:12 WARN]:        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:115)
[22:06:12 WARN]:        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:74)
[22:06:12 WARN]:        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.F_(SpigotLoginListenerPlay.java:67)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
[22:06:12 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
[22:06:12 WARN]:        at java.lang.Thread.run(Thread.java:745)
[22:06:12 INFO]: Birkhoff[/114.34.2.165:37511] logged in with entity id 101 at ([Skyblock1]1604.6740100444006, 58.2140280096921, 813.5346471374934)
```

**Comment by electronicboy** [comment]
Have you enabled the option to remove corrupt tile entities? Your servers map has an issue in that there is TileEntity data stored for a block on the map that is air

**Comment by birkhofflee** [comment]
Sorry, but where’s that option?

**Comment by electronicboy** [comment]
paper.yml   remove-corrupt-tile-entities

**Comment by birkhofflee** [comment]
Will it break any blocks thats not air? Should I keep it enabled?

**Comment by reverofevil** [comment]
@BirkhoffLee While you're waiting for an answer, I'd recommend to make a backup of your world and check it yourself. You'll need a backup anyway in case that option goes wrong.

**Comment by electronicboy** [comment]
No, it won't remove any blocks from the map, that option will only remove a TE, not any blocks themselves, in the event that it's considered invalid: e.g. there is a TE where there is no block for a TE, it shouldn't have any negative effects for most people, however, is left configurable and disabled by default, you could theoretically fix this manually by modifying the map, however that's out of scope.
it **should** be safe to leave that option enabled

**Comment by birkhofflee** [comment]
Alright, thank you all! I enabled that option and I no longer see that error.

**Comment by diamkil** [comment]
Hey, I'm now facing this same error and I'm wondering why this option doesn't exist anymore?

**Comment by electronicboy** [comment]
Because the entire TE system changed in a way that outside of generation bugs or janky plugins meant that this was much less likely to occur, and given the patch was broken nobody cared to update it given such
