### ISSUE TITLE
Server seems crashed

### ISSUE THREAD

**Issue by izeroo** [PaperMC/Paper#440]
### Description of issue:

**_If applicable**_

Loading libraries, please wait...
2016-10-01 09:39:10,686 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
        at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:204)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.init(WindowsTerminal.java:82)
        at org.bukkit.craftbukkit.libs.jline.TerminalFactory.create(TerminalFactory.java:101)
        at org.bukkit.craftbukkit.libs.jline.TerminalFactory.get(TerminalFactory.java:158)
        at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:229)
        at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:221)
        at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:213)
        at net.minecraft.server.v1_8_R3.MinecraftServer.<init>(MinecraftServer.java:141)
        at net.minecraft.server.v1_8_R3.DedicatedServer.<init>(DedicatedServer.java:43)
        at net.minecraft.server.v1_8_R3.MinecraftServer.main(MinecraftServer.java:984)
        at org.bukkit.craftbukkit.Main.main(Main.java:201)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.destroystokyo.paperclip.Paperclip.main(Paperclip.java:177)

[09:39:26 INFO]: Starting minecraft server version 1.8.8

...............

[09:39:58 INFO]: Stopping the server
[09:39:58 INFO]: Stopping server
[09:39:58 INFO]: Saving players
[09:39:58 INFO]: Saving worlds
[09:39:58 INFO]: Saving chunks for level 'world'/Overworld
[09:39:59 INFO]: Saving chunks for level 'world_nether'/Nether
[09:40:01 INFO]: Saving chunks for level 'world_the_end'/The End

> [WARN] Task failed
> java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
>         at org.fusesource.jansi.internal.WindowsSupport.setConsoleMode(WindowsSupport.java:60)
>         at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.setConsoleMode(WindowsTerminal.java:208)
>         at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.restore(WindowsTerminal.java:95)
>         at org.bukkit.craftbukkit.libs.jline.TerminalSupport$1.run(TerminalSupport.java:52)
>         at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.runTasks(ShutdownHooks.java:66)
>         at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.access$000(ShutdownHooks.java:22)
>         at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks$1.run(ShutdownHooks.java:47)
### Plugin list:

none

JavaVersion:8u101

**Comment by izeroo** [comment]
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode)

**Comment by liach** [comment]
That is not a crash. That error is actually reproducible on most platforms, but it never affects the game.

**Comment by izeroo** [comment]
My English is poor,I don't understand what you said, but how to work it out?

**Comment by izeroo** [comment]
So you mean it isn't a big deal?

**Comment by liach** [comment]
Can you run the server for more than 5 minutes? If yes then it is good. If you do not understand you can use a translator, such as http://translate.google.com/

**Comment by izeroo** [comment]
Ok,thanks,I'm a Chinese student,so my English is not very well,but I can run the server

**Comment by liach** [comment]
呵呵说中文

**Comment by izeroo** [comment]
我靠

**Comment by izeroo** [comment]
所以并没有什么影响？
只是这个看起来好烦

**Comment by liach** [comment]
对，还是关掉issue吧

**Comment by izeroo** [comment]
哦
