### ISSUE TITLE
FATAL: Failed to read chunk data for task

### ISSUE THREAD

**Issue by Liftyee** [PaperMC/Paper#4587]
I'm running a Paper 204 server on ubuntu 18.04 server, but when I run I get this error:

```[19:23:24 ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (-17,-15), hashcode:1348909552, priority: -1, file IO thread has dumped the relevant exception above
[19:23:24 FATAL]: Failed to read chunk data for task: Task for world: 'world' at -17,-16 poi: true, hash: 238231995
java.nio.file.AccessDeniedException: ./world/poi/r.-1.-1.mca
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182) ~[?:?]
        at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
        at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
        at net.minecraft.server.v1_16_R2.RegionFile.<init>(RegionFile.java:88) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.RegionFile.<init>(RegionFile.java:68) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.RegionFileCache.getFile(RegionFileCache.java:59) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.RegionFileCache.read(RegionFileCache.java:143) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.VillagePlace.read(VillagePlace.java:285) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.WorldServer$1.readData(WorldServer.java:116) ~[patched_1.16.3.jar:git-Paper-204]
        at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508) ~[patched_1.16.3.jar:git-Paper-204]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.16.3.jar:git-Paper-204]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.16.3.jar:git-Paper-204]
[19:23:24 ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (-17,-16), hashcode:991394697, priority: -1, file IO thread has dumped the relevant exception above
```

and then the server starts 'normally'. I am able to join, place blocks, generally play the game. Is this a problem? How serious is it? How should I fix it? 

(I'm pretty inexperienced with this)

**Comment by Octol1ttle** [comment]
`java.nio.file.AccessDeniedException` Reading stacktraces in 2020
Fix your file permissions

**Comment by Proximyst** [comment]
Make sure your user has at least rw on the server directory (`6` in octal; `600` is sufficient if you own it).

**Comment by Liftyee** [comment]
@Proximyst sorry, but how would I do this?
the server directory is in my home directory.

**Comment by Chew** [comment]
https://duckduckgo.com/?q=change+directory+permissions+ubuntu+18.04&t=osx&ia=web#
