### ISSUE TITLE
PAPER 1.16.3 #209 SERVER CRASHED

### ISSUE THREAD

**Issue by AnateXP** [PaperMC/Paper#4601]
### Link/paste of stack trace

[11:50:38] [Netty Server IO #0/WARN]: [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 提供了一个无效的参数。
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_231]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[?:1.8.0_231]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[?:1.8.0_231]
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110) ~[patched_1.16.3.jar:git-Paper-209]
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107) ~[patched_1.16.3.jar:git-Paper-209]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_231]
	at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107) ~[patched_1.16.3.jar:git-Paper-209]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:141) ~[patched_1.16.3.jar:git-Paper-209]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) ~[patched_1.16.3.jar:git-Paper-209]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) ~[patched_1.16.3.jar:git-Paper-209]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) ~[patched_1.16.3.jar:git-Paper-209]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[patched_1.16.3.jar:git-Paper-209]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[patched_1.16.3.jar:git-Paper-209]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.16.3.jar:git-Paper-209]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

### Plugin list:
___A list of your plugins___

ChestCommands, Citizens, ClearLag, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GroupManager*, HolographicDisplays, mcMMO, MPHealthPower, Multiverse-Core, Multiverse-Portals, PlaceholderAPI, ProtocolLib, QuickShop, Residence, ScriptBlockPlus, TitleManager, Vault, WorldEdit, WorldGuard

### Paper version:
[11:58:05 INFO]: This server is running Paper version git-Paper-209 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[11:58:05 INFO]: Checking version, please wait...
[11:58:11 INFO]: Previous version: git-Paper-202 (MC: 1.16.3)
[11:58:11 INFO]: You are 2 version(s) behind

**Comment by electronicboy** [comment]
I can't read that, but, something caused the connection to close improperly, not a paper issue, such is the art of networking
