### ISSUE TITLE
I recently updated my server after not turning it on in a while and it instantly crashes

### ISSUE THREAD

**Issue by TastyGuava** [PaperMC/Paper#4617]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

[16:27:23 FATAL]: Failed to start the minecraft server
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point ' ' (0x0) special characters are not allowed
in "'string'", position 0
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.16.3.jar:git-Paper-214]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.3.jar:git-Paper-214]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.Main.loadConfigFile(Main.java:230) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.Main.main(Main.java:70) ~[patched_1.16.3.jar:git-Paper-214]
        at org.bukkit.craftbukkit.Main.main(Main.java:276) ~[patched_1.16.3.jar:git-Paper-214]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:58) ~[server.jar:?]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:118) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[patched_1.16.3.jar:git-Paper-214]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:398) ~[patched_1.16.3.jar:git-Paper-214]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.3.jar:git-Paper-214]
        ... 10 more

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

No plugins.

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

I can't launch the server but 1.16.3 #214

**Comment by electronicboy** [comment]
You have an invalid configuration file, likely the spigot.yml one

**Comment by TastyGuava** [comment]
Yeah, I deleted my spigot.yml & paper.yml as both were completely corrupted. It works perfectly now.
