### ISSUE TITLE
Player unable to connect to Server over IPv6 when using Velocity Proxy

### ISSUE THREAD

**Issue by cfulton** [PaperMC/Paper#4638]
### What behaviour is expected:
Player should be able to connect to Paper Server from Velocity Proxy over IPv6

### What behaviour is observed:
Player is unable to connect to Paper Server due to following exception when player is connecting over IPv6:

com.mojang.authlib.GameProfile@6cc6e3e5[id=<null>,name=[Redacted],properties={},legacy=false]: (/0:0:0:0:0:0:0:1%0:48406) lost connection: 

Internal Exception: java.lang.IllegalArgumentException: '2001:db8:0:0:0:0:0:7754%0' is not an IP string literal.

at com.google.common.net.InetAddresses.forString(InetAddresses.java:144)
at com.destroystokyo.paper.proxy.VelocityProxy.readAddress(VelocityProxy.java:49)
at net.minecraft.server.v1_16_R2.LoginListener.a(LoginListener.java:356)
at net.minecraft.server.v1_16_R2.PacketLoginInCustomPayload.a(PacketLoginInCustomPayload.java:42)
at net.minecraft.server.v1_16_R2.PacketLoginInCustomPayload.a(PacketLoginInCustomPayload.java:5)
at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:159)
at net.minecraft.server.v1_16_R2.NetworkManager.channelRead0(NetworkManager.java:148)
at net.minecraft.server.v1_16_R2.NetworkManager.channelRead0(NetworkManager.java:30)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at java.lang.Thread.run(Thread.java:748)

### Steps/models to reproduce:
1. Configure a Paper Server with a binding address of 'blank'
2. Configure a Velocity Proxy with the target server being the Paper server (shouldn't matter if uses its IPv4/IPv6 address)
3. Configure Velocity Proxy with method being the Modern Method (Not Legacy)
4. Connect to Server over IPv4 to validate setup
5. Connect to Server over IPv6

### Plugin list:
None

### Paper version:
This server is running Paper version git-Paper-220 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by astei** [comment]
This problem is more with Velocity. I'd never taken IPv6 scoped addresses into account when creating the support.

This is now fixed (by chopping off the scope).
