### ISSUE TITLE
Failed to save chunk java.lang.NullPointerException: null Paper-234

### ISSUE THREAD

**Issue by SentinelCraft** [PaperMC/Paper#4658]
### What behaviour is expected:
Server is supposed to start without errors

### What behaviour is observed:
A bunch of errors about NBT Data and chunk errors in some of our worlds, spawn world and all of the nether and end worlds.

[05:32:43] [Paper RegionFile IO Thread/ERROR]: Failed to save chunk
java.lang.NullPointerException: null
    at net.minecraft.server.v1_16_R2.NBTTagCompound.a(NBTTagCompound.java:451) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.NBTTagCompound.write(NBTTagCompound.java:92) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.NBTTagCompound.a(NBTTagCompound.java:454) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.NBTTagCompound.write(NBTTagCompound.java:92) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.NBTTagCompound.a(NBTTagCompound.java:454) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.NBTTagCompound.write(NBTTagCompound.java:92) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:163) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:156) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.RegionFileCache.write(RegionFileCache.java:199) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.IChunkLoader.write(IChunkLoader.java:116) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.PlayerChunkMap.write(PlayerChunkMap.java:1632) ~[patched_1.16.3.jar:git-Paper-234]
    at net.minecraft.server.v1_16_R2.WorldServer$2.writeData(WorldServer.java:146) ~[patched_1.16.3.jar:git-Paper-234]
    at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:566) ~[patched_1.16.3.jar:git-Paper-234]
    at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.16.3.jar:git-Paper-234]
    at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:49) ~[patched_1.16.3.jar:git-Paper-234]

### Steps/models to reproduce:
Just starting the server

### Plugin list:
Irrelevant

### Paper version:
Paper Version: Started when I updated our server to Paper-234

### Anything else:
When returning back to Paper-232, it shows me this:

[05:45:38] [Paper Async Chunk Task Thread #0/ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'Fedgardia', (82,97), hashcode:362136671, priority: -1, file IO thread has dumped the relevant exception above
[05:45:38] [Paper RegionFile IO Thread/FATAL]: Failed to read chunk data for task: Task for world: 'Fedgardia' at 83,97 poi: false, hash: 370861064
net.minecraft.server.v1_16_R2.ReportedException: Loading NBT data
	at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:475) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:53) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:468) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:53) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:176) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:145) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:135) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.RegionFileCache.read(RegionFileCache.java:162) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.IChunkLoader.read(IChunkLoader.java:104) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.read(PlayerChunkMap.java:1621) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.WorldServer$2.readData(WorldServer.java:151) ~[patched_1.16.3.jar:git-Paper-232]
	at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508) ~[patched_1.16.3.jar:git-Paper-232]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.16.3.jar:git-Paper-232]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.16.3.jar:git-Paper-232]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[?:1.8.0_161]
	at net.minecraft.server.v1_16_R2.NBTTagCompound.c(NBTTagCompound.java:459) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound.access$000(NBTTagCompound.java:27) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:49) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38) ~[patched_1.16.3.jar:git-Paper-232]
	at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:468) ~[patched_1.16.3.jar:git-Paper-232]
	... 17 more

**Comment by Proximyst** [comment]
Fixed on b235.

EDIT: Revert to backup.

**Comment by SentinelCraft** [comment]
I am very emotionally upset with this. Unfortunately, this has literally caused corrupt chunks in all of my worlds, some of them almost 6 years old, and others that I don't have recent backups, due to server space management. Any advice on what to do or how to approach this issue, since Paper-235 reflects the same errors as on Paper-232? 

Is waiting for 1.16.4 an option that would fix this?

**Comment by clrxbl** [comment]
Unless a developer finds a way to recover the chunks (perhaps it might be possible), restoring from a backup or deleting the affected chunks is the only way possible. A reminder to never auto-update your server and test server updates.

**Comment by Proximyst** [comment]
If you've got a 6 yr old world, you should've been doing backups for quite a while. Paper never releases stable builds, we release testable builds which may or may not work well (hint: this is why we never, ever recommend auto-updating). Storage is fairly cheap, you should at *least* have a backup before updating.

Minecraft 1.16.4 will _not_ fix the issues. As Cat pointed out on Discord, https://github.com/Spottedleaf/Tuinity *might* fix the issue for you, but it's only a "worth a shot" measure.

It's also worth noting that the 2nd sentence in the commit description reads as follows:
> This update has **not been tested** by PaperMC and as with ANY update, **please do your own testing**

**Comment by clrxbl** [comment]
Having tested Tuinity on a b234 world, this does **not** appear to fix the problem.

**Comment by SentinelCraft** [comment]
Thank you so much for your attention. Our server and staff will try to come up on top of this unexpected situation for us, we've been around for a long time so I'm sure things will work out in some way. I do understand I took a risk but I've never experienced any issue so I thought it would be the case again. The struggles are always what makes us learn and improve. 

I definitely am not an expert at this, I always rely on the help of others and my staff team so this is definitely a massive learning experience for me.

**Comment by SentinelCraft** [comment]
Sorry to revive this post but I need external help/advice since my experience on this is almost non-existant.

Let's consider I want to delete the chunks. So for example the "Fedgardia" world chunk area affected is 82,97. That means I only have to delete the respective region file, this case r.2.2.mca? Or do I have to do anything else more?

**Comment by clrxbl** [comment]
Correct.
