### ISSUE TITLE
Villager Trades using only second buy slot crashes entire server

### ISSUE THREAD

**Issue by bahfheuv** [PaperMC/Paper#4665]
### What behaviour is expected:
For me to be able to trade with villagers using only the second trade slot (`buyB` in NBT).

### What behaviour is observed:
A server crash:
java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_16_R2.ItemStack.checkEmpty(ItemStack.java:156) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.ItemStack.setCount(ItemStack.java:976) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.ItemStack.add(ItemStack.java:980) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.ItemStack.subtract(ItemStack.java:984) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.MerchantRecipe.b(MerchantRecipe.java:212) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.SlotMerchantResult.a(SourceFile:58) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.Container.b(Container.java:371) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.Container.a(Container.java:183) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2445) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-229]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-229]
        at java.lang.Thread.run(Thread.java:832) [?:?]

### Steps/models to reproduce:
`/summon minecraft:wandering_trader ~ ~ ~ {Offers:{Recipes:[{buyB:{id:"minecraft:stick",Count:1b},sell:{id:"minecraft:stick",Count:1b}}]},NoAI:1b}`
And then try to trade.
The reasoning for only using the second slot is that it's not affected by in-game events. The first slot pricing is influenced by restocks, demand and other gameplay style parameters that shouldn't be influencing adventure-style servers.

### Plugin list:
None

### Paper version:
`git-Paper-240 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)`

### Side Note:
When this gets fixed, how do I update? Do I have to wait for a major release, can I download it instantly from the website, does it update automatically?

**Comment by drunderscore** [comment]
Paper does not make releases, (mostly) every commit here is automatically built and hosted on https://papermc.io/downloads

So to answer your question, yes, the website will update it automatically.

**Comment by Chew** [comment]
You're also a few builds behind. Please reproduce on latest, as stated you can download that [here](https://Papermc.io/downloads)

**Comment by bahfheuv** [comment]
@Chew Still occurs on latest version (updated version in description)
