### ISSUE TITLE
Couldn't register custom payload

### ISSUE THREAD

**Issue by 2233bbb123** [PaperMC/Paper#4685]
[21:51:08 INFO]: UUID of player 2233 is f8c06981-0144-3169-be4b-d4290b84cb84
[21:51:08 INFO]: 2233[/27.137.98.60:58841] logged in with entity id 167 at ([world]-267.8167696464792, 66.0, 345.9594135241675)
[21:51:08 ERROR]: Couldn't register custom payload
>java.lang.IllegalStateException: Too many channels registered
at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1159) ~[minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2557) [minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) [minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) [minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.1.12.2.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[21:51:08 INFO]: 2233 lost connection: Invalid payload REGISTER!
[21:51:08 INFO]: 2233 left the game

**Comment by electronicboy** [comment]
1.12.2 hasn't been supported in years, 

> java.lang.IllegalStateException: Too many channels registered

CB limits the number of registered channels, there is a jvm flag inside of paper to remove that limit, but I have no idea if it exists in 1.12.2, `-Dpaper.disableChannelLimit`
