### ISSUE TITLE
Console history?

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#4692]
### What behaviour is expected:
I don't need to save console history. How to just disable it?..

### What behaviour is observed:
After each command sent.
```
[22:28:52] [org.jline] Failed to save history
java.nio.file.AccessDeniedException: H:\Survival Test Server\.console_history
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_261]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_261]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_261]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:1.8.0_261]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source) ~[?:1.8.0_261]
        at java.nio.file.Files.newOutputStream(Unknown Source) ~[?:1.8.0_261]
        at java.nio.file.Files.newBufferedWriter(Unknown Source) ~[?:1.8.0_261]
        at java.nio.file.Files.newBufferedWriter(Unknown Source) ~[?:1.8.0_261]
        at org.jline.reader.impl.history.DefaultHistory.internalWrite(DefaultHistory.java:231) ~[server.jar:git-Paper-"cfc098be"]
        at org.jline.reader.impl.history.DefaultHistory.save(DefaultHistory.java:223) ~[server.jar:git-Paper-"cfc098be"]
        at org.jline.reader.impl.history.DefaultHistory.add(DefaultHistory.java:375) ~[server.jar:git-Paper-"cfc098be"]
        at org.jline.reader.impl.LineReaderImpl.finishBuffer(LineReaderImpl.java:1026) ~[server.jar:git-Paper-"cfc098be"]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:612) ~[server.jar:git-Paper-"cfc098be"]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[server.jar:git-Paper-"cfc098be"]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[server.jar:git-Paper-"cfc098be"]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[server.jar:git-Paper-"cfc098be"]
        at net.minecraft.server.v1_16_R2.DedicatedServer$1.run(DedicatedServer.java:64) ~[server.jar:git-Paper-"cfc098be"]
```

### Steps/models to reproduce:
I just removed the file ".console_history" because I don't need to save console history.

### Paper version:
git-Paper-"cfc098be" (MC: 1.16.3)

**Comment by Proximyst** [comment]
You can't. This points towards an underlying issue of your permissions being broken.
