### ISSUE TITLE
WorldGuard Incompatibility

### ISSUE THREAD

**Issue by wallxq** [PaperMC/Paper#4858]
Any version of WorldGuard doesn't work with lastest Paper on java 11.
I use AdoptOpenJDK 11 hotspot.
With dev WorldGuard too:

`Error occurred while disabling WorldGuard v7.0.5-SNAPSHOT+2084-035a645 (Is it up to date?)
java.lang.NullPointerException: null
        at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.unload(BukkitWorldGuardPlatform.java:149) ~[?:?]
        at com.sk89q.worldguard.WorldGuard.disable(WorldGuard.java:205) ~[?:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:264) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-318]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-318]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-318]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-318]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-318]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-318]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Machine-Maker** [comment]
I mean... this looks like an NPE on WorldGuards end. Probably not a Paper issue. I'd talk to the WG devs.

**Comment by electronicboy** [comment]
In the future, please fill in the template, also, we need the full log; ideally on paste.gg or pastebin

**Comment by wallxq** [comment]
I create new server, only authme+worldedit+worldguard.
Logs from this:

https://pastebin.pl/view/567f4b8b

**Comment by aurorasmiles** [comment]
Your issue is your worldguard configuration. For more support please contact WorldGuard, this is not a Paper issue.

**Comment by wallxq** [comment]
True, that was problem with yaml. Thanks.
