### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by hydralica** [PaperMC/Paper#4862]
[18:27:12 INFO]: UUID of player hydralica is 4ba09d58-72c1-476b-bacc-9d614d664672
[18:27:12 WARN]: Failed to handle packet for /127.0.0.1:62217
net.minecraft.server.v1_16_R3.ReportedException: Sending packet
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1731) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1696) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:197) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:168) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:66) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:383) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1381) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalStateException: Cannot use reflection.
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:30) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:353) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:291) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:247) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:223) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.4.jar:git-Paper-318]
	... 12 more
Caused by: java.lang.IllegalAccessException: Can not set final net.minecraft.server.v1_16_R3.Packet field net.minecraft.server.v1_16_R3.NetworkManager$$Lambda$5488/0x0000000801b8dce8.arg$4 to net.minecraft.server.v1_16_R3.PacketPlayOutEntityStatus
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80) ~[?:?]
	at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79) ~[?:?]
	at java.lang.reflect.Field.set(Field.java:793) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:26) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:353) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:291) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:247) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:223) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.4.jar:git-Paper-318]
	... 12 more
[18:27:12 INFO]: hydralica lost connection: Internal server error

### Plugin list:
Plugins (9): BKCommonLib, Citizens, ColoredSigns*, FastAsyncWorldEdit (WorldEdit), GFly, ImageMaps, LibsDisguises, LightCleaner, ProtocolLib

### Actions to reproduce (if known):
Unknown

### Paper version:
Paper version git-Paper-318 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by HexedHero** [comment]
Seems related to ProtocolLib

**Comment by katekerllenevich** [comment]
Are you on Java 15?

**Comment by JRoy** [comment]
Not a paper related issue.

See https://github.com/dmulloy2/ProtocolLib/pull/1025 to track ProtocolLib's fix for this

**Comment by katekerllenevich** [comment]
> Not a paper related issue.
> 
> See [dmulloy2/ProtocolLib#1025](https://github.com/dmulloy2/ProtocolLib/pull/1025) to track ProtocolLib's fix for this

Speaking of that, a fix was implemented by a third party (https://github.com/ZentriaMC/ProtocolLib/releases/tag/v4.6.0-java15fix-2) and has been proven to have a significant performance deficit.

The only current fix is this patch in Origami (https://github.com/Minebench/Origami/blob/1.16/patches/server/0031-Fix-ProtocolLib-issues-on-Java-15.patch). This was ported into Purpur and should probably be shoved as far upstream as possible.

**Comment by JRoy** [comment]
imo better for plugins to handle this correctly on newer java versions than for paper to hack it out but I guess it could work

**Comment by mikroskeem** [comment]
This should indeed be handled by plugins - implementation is not an API after all
