### ISSUE TITLE
Unable to create new native thread

### ISSUE THREAD

**Issue by Infinite-Blocks** [PaperMC/Paper#4921]
### Link/paste of stack trace

  ```
 [21:18:02] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:18:02] [main/INFO]: Reloading ResourceManager: Default, bukkit
[21:18:03] [Worker-Main-1/INFO]: Loaded 7 recipes
[21:18:05] [main/INFO]: [STDERR]: java.lang.OutOfMemoryError: unable to create new native thread
[21:18:05] [main/INFO]: [STDERR]: 	at java.lang.Thread.start0(Native Method)
[21:18:05] [main/INFO]: [STDERR]: 	at java.lang.Thread.start(Thread.java:717)
[21:18:05] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:188)
[21:18:05] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_16_R3.Main.main(Main.java:185)
[21:18:05] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.Main.main(Main.java:276)
[21:18:05] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:18:05] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:18:05] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:18:05] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:18:05] [main/INFO]: [STDERR]: 	at io.papermc.paperclip.Paperclip.main(Paperclip.java:58)


```

### Plugin list:
Arceon
ArmorstandTools
BuildersUtilities
CraftFlowers
FaWe
FaVs
We Selection visualizer

### Actions to reproduce (if known):
The server worked fine already but gives me all sorts of errors since I am trying to change worlds

screen java -Xss320k -Xmx2GM -jar paper.jar nogui

### Paper version: 1.16.4-337

**Comment by BillyGalbreath** [comment]
```[STDERR]: java.lang.OutOfMemoryError: unable to create new native thread```

Not enough ram

**Comment by Chew** [comment]
Your arguments also look wrong...

> `screen java -Xss320k -Xmx2GM -jar paper.jar nogui`

Should be G not "GM", also need [Aikar's flags](https://mcflags.emc.gs/), and both should be "2G".

**Comment by electronicboy** [comment]
This is not a paper issue, you either ran out of memory or hit a ulimit somewhere
