### ISSUE TITLE
MY SERVER CRASHED

### ISSUE THREAD

**Issue by pigling123** [PaperMC/Paper#4964]
`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/18/20 6:19 PM
Description: Exception while ticking a block

java.lang.IllegalArgumentException: Cannot set property BlockStateInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 0 on block minecraft:fire, it is not an allowed value
	at net.minecraft.server.v1_12_R1.BlockStateList$BlockData.set(SourceFile:184)
	at net.minecraft.server.v1_12_R1.BlockFire.b(BlockFire.java:120)
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:793)
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:324)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:905)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
	at java.lang.Thread.run(Thread.java:823)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.v1_12_R1.BlockStateList$BlockData.set(SourceFile:184)
	at net.minecraft.server.v1_12_R1.BlockFire.b(BlockFire.java:120)

-- Block being ticked --
Details:
	Block: minecraft:fire[age=0,east=false,north=false,south=false,up=false,west=false]
	Block location: World: (-5400,69,1261), Chunk: (at 8,4,13 in -338,78; contains blocks -5408,0,1248 to -5393,255,1263), Region: (-11,2; contains chunks -352,64 to -321,95, blocks -5632,0,1024 to -5121,255,1535)
Stacktrace:
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:793)
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:324)

-- Affected level --
Details:
	Level name: Survival
	All players: 3 total; [EntityPlayer['EMULATOR'/7334, uuid='3283224f-5867-39b1-a346-753072cc3b41', l='Survival', x=-5398.18, y=69.00, z=1258.67, cx=-338, cd=78, tl=3363384, v=true, d=false](EMULATOR at -5398.180525721233,69.0,1258.6735009660633), EntityPlayer['Galaxy_Outputz'/3796, uuid='381af687-bd20-3f22-a4d0-3570695d7275', l='Survival', x=-5400.82, y=69.00, z=1259.19, cx=-338, cd=78, tl=3380304, v=true, d=false](Galaxy_Outputz at -5400.823756151831,69.0,1259.185084339998), EntityPlayer['Welcome_234'/2396, uuid='2bc6e944-08c1-3611-8ddc-a3f0e5ca999a', l='Survival', x=-5401.54, y=69.00, z=1261.40, cx=-338, cd=78, tl=79881779, v=true, d=false](Welcome_234 at -5401.540428372958,69.0,1261.3971638593932)]
	Chunk stats: ServerChunkCache: 377 Drop: 0
	Level seed: 8539290206554702663
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-14,63,2), Chunk: (at 2,3,2 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 406904527 game time, 414266971 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 108543 (now: false), thunder time: 12744 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:905)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
	at java.lang.Thread.run(Thread.java:823)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-106-generic
	Java Version: 1.8.0_272, Eclipse OpenJ9
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201022_822 (JIT enabled, AOT enabled)`

Please please please fix this My server crashes with minecraft:fire thing

**Comment by electronicboy** [comment]
1.12.2 is no longer supported, something caused a world modification to occur in an unexpected manner, known CB/plugin interop issue
