### ISSUE TITLE
Server Watchdog crash

### ISSUE THREAD

**Issue by Xaerie** [PaperMC/Paper#4966]
I'm not familiar with reading these crash logs. What exactly can I do or look into, to fix this server crashing on me?

I increased the max timeout from the default of 60000 to 88000.
Update: I changed the max timeout a bit more after reading https://bugs.mojang.com/browse/MC-63590

Just looking for thoughts on what else I can look at. If I'm in the wrong place my apologies, I was directed here.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/30/20 8:51 PM
Description: Watching Server

java.lang.Error: Watchdog
	at aag.a(SourceFile:411)
	at net.minecraft.server.MinecraftServer.b(SourceFile:871)
	at zg.b(SourceFile:312)
	at net.minecraft.server.MinecraftServer.a(SourceFile:811)
	at net.minecraft.server.MinecraftServer.w(SourceFile:670)
	at net.minecraft.server.MinecraftServer.a(SourceFile:257)
	at net.minecraft.server.MinecraftServer$$Lambda$3290/13067268.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at aag.a(SourceFile:411)
	at net.minecraft.server.MinecraftServer.b(SourceFile:871)
	at zg.b(SourceFile:312)
	at net.minecraft.server.MinecraftServer.a(SourceFile:811)
	at net.minecraft.server.MinecraftServer.w(SourceFile:670)
	at net.minecraft.server.MinecraftServer.a(SourceFile:257)

-- Thread Dump --
Details:
	Threads: "Worker-Main-26" Id=58 WAITING on java.util.concurrent.ForkJoinPool@208705
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@208705
	at java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

"Worker-Main-25" Id=57 WAITING on java.util.concurrent.ForkJoinPool@208705
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@208705
	at java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

"Worker-Main-24" Id=56 TIMED_WAITING on java.util.concurrent.ForkJoinPool@208705
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@208705
	at java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

"Worker-Main-23" Id=55 WAITING on java.util.concurrent.ForkJoinPool@208705
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@208705
	at java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

"Worker-Main-22" Id=54 WAITING on java.util.concurrent.ForkJoinPool@208705
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@208705
	at java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

"Worker-Main-21" Id=53 WAITING on java.util.concurrent.ForkJoinPool@208705
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@208705
	at java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

"Worker-Main-20" Id=52 WAITING on java.util.concurrent.ForkJoinPool@208705
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@208705
	at java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

"Netty Server IO #1" Id=48 RUNNABLE
	at aay$$Lambda$3993/24896979.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(Unknown Source)
	at java.lang.invoke.LambdaMetafactory.metafactory(Unknown Source)
	at java.lang.invoke.LambdaForm$DMH/7865310.invokeStatic_L6_L(LambdaForm$DMH)
	...

"Server Watchdog" Id=47 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at zj.run(SourceFile:49)
	at java.lang.Thread.run(Unknown Source)

"Netty Server IO #0" Id=41 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@e76931
	-  locked java.util.Collections$UnmodifiableSet@d8ec75
	-  locked sun.nio.ch.WindowsSelectorImpl@1da630a
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	...

"ObjectCleanerThread" Id=40 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@144dd1b
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@144dd1b
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)

"D3D Screen Updater" Id=38 TIMED_WAITING on java.lang.Object@dd8ba3
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@dd8ba3
	at sun.java2d.d3d.D3DScreenUpdateManager.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"DestroyJavaVM" Id=37 RUNNABLE

"Server thread" Id=26 RUNNABLE
	at aag.a(SourceFile:411)
	at net.minecraft.server.MinecraftServer.b(SourceFile:871)
	at zg.b(SourceFile:312)
	at net.minecraft.server.MinecraftServer.a(SourceFile:811)
	at net.minecraft.server.MinecraftServer.w(SourceFile:670)
	at net.minecraft.server.MinecraftServer.a(SourceFile:257)
	at net.minecraft.server.MinecraftServer$$Lambda$3290/13067268.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Thread-3" Id=33 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1a96b09
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1a96b09
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
	at com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77)
	at zm.a(SourceFile:137)
	at zm$$Lambda$3305/6315277.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"TimerQueue" Id=34 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@b420e5
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@b420e5
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
	at java.util.concurrent.DelayQueue.take(Unknown Source)
	at javax.swing.TimerQueue.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@1f59c45

"AWT-EventQueue-0" Id=32 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@243bc3
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@243bc3
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at java.awt.EventQueue.getNextEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	...

"AWT-Windows" Id=30 RUNNABLE (in native)
	at sun.awt.windows.WToolkit.eventLoop(Native Method)
	at sun.awt.windows.WToolkit.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"AWT-Shutdown" Id=29 WAITING on java.lang.Object@ade3ed
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@ade3ed
	at java.lang.Object.wait(Unknown Source)
	at sun.awt.AWTAutoShutdown.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Java2D Disposer" Id=28 WAITING on java.lang.ref.ReferenceQueue$Lock@1bb4509
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@1bb4509
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at sun.java2d.Disposer.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Snooper Timer" Id=27 WAITING on java.util.TaskQueue@e9fbd3
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@e9fbd3
	at java.lang.Object.wait(Unknown Source)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

"Timer hack thread" Id=18 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at x$6.run(SourceFile:636)

"Worker-Bootstrap-7" Id=17 RUNNABLE
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	at com.mojang.datafixers.functions.Apply.one(Apply.java:45)
	at com.mojang.datafixers.functions.PointFreeRule$One.rewrite(PointFreeRule.java:651)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	at com.mojang.datafixers.functions.Comp.one(Comp.java:43)
	at com.mojang.datafixers.functions.PointFreeRule$One.rewrite(PointFreeRule.java:651)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	...

"Worker-Bootstrap-6" Id=16 RUNNABLE
	at com.mojang.datafixers.functions.PointFreeRule$CompRewrite$$Lambda$1340/10082271.get$Lambda(Unknown Source)
	at java.lang.invoke.LambdaForm$DMH/5074563.invokeStatic_L_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/6793289.linkToTargetMethod(LambdaForm$MH)
	at com.mojang.datafixers.functions.PointFreeRule$CompRewrite.rewrite(PointFreeRule.java:180)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	...

"Worker-Bootstrap-5" Id=15 RUNNABLE
	at com.mojang.datafixers.functions.PointFreeRule$CompRewrite.rewrite(PointFreeRule.java:180)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	at com.mojang.datafixers.functions.Comp.one(Comp.java:43)
	at com.mojang.datafixers.functions.PointFreeRule$One.rewrite(PointFreeRule.java:651)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	at com.mojang.datafixers.functions.Comp.one(Comp.java:43)
	at com.mojang.datafixers.functions.PointFreeRule$One.rewrite(PointFreeRule.java:651)
	...

"Worker-Bootstrap-4" Id=14 RUNNABLE
	at com.mojang.datafixers.functions.PointFreeRule.orElseStrict(PointFreeRule.java:553)
	at com.mojang.datafixers.functions.PointFreeRule.once(PointFreeRule.java:601)
	at com.mojang.datafixers.functions.PointFreeRule.lambda$once$3(PointFreeRule.java:601)
	at com.mojang.datafixers.functions.PointFreeRule$$Lambda$552/30085344.get(Unknown Source)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	at com.mojang.datafixers.functions.Comp.one(Comp.java:43)
	at com.mojang.datafixers.functions.PointFreeRule$One.rewrite(PointFreeRule.java:651)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	...

"Worker-Bootstrap-3" Id=13 RUNNABLE
	at com.mojang.datafixers.functions.PointFreeRule$SortInj.doRewrite(PointFreeRule.java:290)
	at com.mojang.datafixers.functions.PointFreeRule$CompRewrite.rewrite(PointFreeRule.java:198)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	at com.mojang.datafixers.functions.Apply.lambda$one$5(Apply.java:46)
	at com.mojang.datafixers.functions.Apply$$Lambda$1385/31072657.get(Unknown Source)
	at java.util.Optional.orElseGet(Unknown Source)
	at com.mojang.datafixers.functions.Apply.one(Apply.java:46)
	...

"Worker-Bootstrap-2" Id=12 RUNNABLE
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:567)
	at com.mojang.datafixers.functions.Apply.lambda$one$5(Apply.java:46)
	at com.mojang.datafixers.functions.Apply$$Lambda$1385/31072657.get(Unknown Source)
	at java.util.Optional.orElseGet(Unknown Source)
	at com.mojang.datafixers.functions.Apply.one(Apply.java:46)
	...

"Worker-Bootstrap-1" Id=11 BLOCKED on java.lang.ref.Reference$Lock@1623b2e owned by "Worker-Bootstrap-4" Id=14
	at com.mojang.datafixers.functions.PointFreeRule.one(PointFreeRule.java:597)
	-  blocked on java.lang.ref.Reference$Lock@1623b2e
	at com.mojang.datafixers.functions.PointFreeRule.lambda$once$3(PointFreeRule.java:601)
	at com.mojang.datafixers.functions.PointFreeRule$$Lambda$552/30085344.get(Unknown Source)
	at com.mojang.datafixers.functions.PointFreeRule$OrElse.rewrite(PointFreeRule.java:571)
	at com.mojang.datafixers.functions.Apply.lambda$one$5(Apply.java:46)
	at com.mojang.datafixers.functions.Apply$$Lambda$1385/31072657.get(Unknown Source)
	at java.util.Optional.orElseGet(Unknown Source)
	at com.mojang.datafixers.functions.Apply.one(Apply.java:46)
	...

"Attach Listener" Id=5 RUNNABLE

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@971564
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@971564
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@1623b2e owned by "Worker-Bootstrap-4" Id=14
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@1623b2e
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference.tryHandlePending(Unknown Source)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

Stacktrace:
	at zj.run(SourceFile:65)
	at java.lang.Thread.run(Unknown Source)

-- Performance stats --
Details:
	Random tick rate: 3
	Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 1, entities: 181 [minecraft:creeper:31,minecraft:cod:22,minecraft:sheep:17,minecraft:skeleton:16,minecraft:zombie:15], block_entities: 23 [minecraft:mob_spawner:13,minecraft:chest:10], block_ticks: 9001, fluid_ticks: 7468, chunk_source: ServerChunkCache: 2025,
ResourceKey[minecraft:dimension / minecraft:the_nether]: players: 0, entities: 0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: ServerChunkCache: 0,
ResourceKey[minecraft:dimension / minecraft:the_end]: players: 0, entities: 0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: ServerChunkCache: 0

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 7683504 bytes (7 MB) / 259522560 bytes (247 MB) up to 259522560 bytes (247 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Player Count: 1 / 20; [aah['Me'/134, l='ServerLevel[world]', x=-115.50, y=71.00, z=-252.50]]
	Data Packs: vanilla
	Is Modded: Unknown (can't tell)
	Type: Dedicated Server (map_server.txt)

**Comment by electronicboy** [comment]
That's not even paper...

**Comment by Xaerie** [comment]
> That's not even paper...

Oh crap, my bad. Where does this go then?

**Comment by Chew** [comment]
What software are you running?
Vanilla -> https://bugs.mojang.com
Spigot/CraftBukkit -> https://hub.spigotmc.org/jira/secure/Dashboard.jspa
Anything else -> probably not worth reporting
