### ISSUE TITLE
Server Crash 1.10 build 916

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#498]
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/22/16 6:39 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:511)
    at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator.next(Long2ObjectOpenHashMap.java:706)
    at net.minecraft.server.v1_10_R1.PaperLightingQueue.processQueue(PaperLightingQueue.java:23)
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:792)
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by zachbr** [comment]
Duplicate, out of formal support.

**Comment by PhanaticD** [comment]
whats that mean

**Comment by DenWav** [comment]
1.10 is not supported.
