### ISSUE TITLE
Warning in the Server Console

### ISSUE THREAD

**Issue by Flearl** [PaperMC/Paper#4981]
I'm not sure it's a Paper bug
Paper Version : 1.16.4-345

ServerConsole Warning
[05:21:39] [Server thread/WARN]: Entity threw exception at world:-1333.501447293327,41.0,-4859.2467035607515
[05:21:39] [Server thread/WARN]: java.util.NoSuchElementException
[05:21:39] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.util.UnsafeList$Itr.next(UnsafeList.java:263)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:978)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.World.b(World.java:1161)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.IEntityAccess.b(IEntityAccess.java:213)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PathfinderGoalNearestAttackableTarget.g(PathfinderGoalNearestAttackableTarget.java:47)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PathfinderGoalNearestAttackableTarget.a(PathfinderGoalNearestAttackableTarget.java:36)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PathfinderGoalWrapped.a(PathfinderGoalWrapped.java:23)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:129)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.EntityInsentient.inactiveTick(EntityInsentient.java:139)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:847)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.World.a(World.java:884)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1356)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[05:21:39] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[05:21:39] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by electronicboy** [comment]
replicate without plugins, chances are something is messing with a chunks entity list from another thread or something

**Comment by Chew** [comment]
Also, 21 builds behind, please only report issues on the latest version.
