### ISSUE TITLE
Iron golem related issue

### ISSUE THREAD

**Issue by Namrise** [PaperMC/Paper#4988]
using latest paper 1.16.4 and epic spawners 6.10.4. players are getting client side errors when iron golems are spawning from their spawners and their logs are filling like crazy (1 gigabyte in like 20 minutes) I don't know what is causing it so im trying to post anywhere I can about this issue.

basically, with iron golem spawners there is no spinning miniature inside the spawner and so I think it is related to this error:

[20:16:29] [Render thread/INFO]: [STDOUT]: Negative index in crash report handler (0/21)
[20:16:29] [Render thread/WARN]: Exception loading entity: 
u: Loading entity NBT
	at aqa.f(SourceFile:1663) ~[1.16.4.jar:?]
	at aqe.a(SourceFile:473) ~[1.16.4.jar:?]
	at aqe$$Lambda$3812/1604372534.accept(Unknown Source) ~[?:?]
	at x.a(SourceFile:402) ~[1.16.4.jar:?]
	at aqe.a(SourceFile:472) ~[1.16.4.jar:?]
	at aqe.b(SourceFile:535) [1.16.4.jar:?]
	at aqe.a(SourceFile:516) [1.16.4.jar:?]
	at bqz.d(SourceFile:254) [1.16.4.jar:?]
	at ecp.a(SourceFile:22) [1.16.4.jar:?]
	at ecp.a(SourceFile:12) [1.16.4.jar:?]
	at ecd.a(SourceFile:107) [1.16.4.jar:?]
	at ecd.b(SourceFile:96) [1.16.4.jar:?]
	at ecd$$Lambda$3710/634225415.run(Unknown Source) [1.16.4.jar:?]
	at ecd.a(SourceFile:128) [1.16.4.jar:?]
	at ecd.a(SourceFile:96) [1.16.4.jar:?]
	at eae.a(SourceFile:1260) [1.16.4.jar:?]
	at dzz.a(SourceFile:727) [1.16.4.jar:?]
	at dzz.a(SourceFile:546) [1.16.4.jar:?]
	at djz.e(SourceFile:1048) [1.16.4.jar:?]
	at djz.e(SourceFile:681) [1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:215) [1.16.4.jar:?]
Caused by: java.lang.ClassCastException

any help appreciated

**Comment by electronicboy** [comment]
can you replicate without plugins?

**Comment by Namrise** [comment]
> can you replicate without plugins?

So i've unloaded epic spawners and used a new iron golem spawner also generated a new log file and I get a slightly different error:


[20:26:49] [Render thread/WARN]: Exception loading entity: 
u: Loading entity NBT
	at aqa.f(SourceFile:1663) ~[1.16.4.jar:?]
	at aqe.a(SourceFile:473) ~[1.16.4.jar:?]
	at aqe$$Lambda$3829/975678871.accept(Unknown Source) ~[?:?]
	at x.a(SourceFile:402) ~[1.16.4.jar:?]
	at aqe.a(SourceFile:472) ~[1.16.4.jar:?]
	at aqe.b(SourceFile:535) [1.16.4.jar:?]
	at aqe.a(SourceFile:516) [1.16.4.jar:?]
	at bqz.d(SourceFile:254) [1.16.4.jar:?]
	at ecp.a(SourceFile:22) [1.16.4.jar:?]
	at ecp.a(SourceFile:12) [1.16.4.jar:?]
	at ecd.a(SourceFile:107) [1.16.4.jar:?]
	at ecd.b(SourceFile:96) [1.16.4.jar:?]
	at ecd$$Lambda$3711/1174282991.run(Unknown Source) [1.16.4.jar:?]
	at ecd.a(SourceFile:128) [1.16.4.jar:?]
	at ecd.a(SourceFile:96) [1.16.4.jar:?]
	at eae.a(SourceFile:1260) [1.16.4.jar:?]
	at dzz.a(SourceFile:727) [1.16.4.jar:?]
	at dzz.a(SourceFile:546) [1.16.4.jar:?]
	at djz.e(SourceFile:1048) [1.16.4.jar:?]
	at djz.e(SourceFile:681) [1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:215) [1.16.4.jar:?]
Caused by: java.lang.ClassCastException: dwt cannot be cast to aag
	at bai.a(SourceFile:170) ~[1.16.4.jar:?]
	at aqa.f(SourceFile:1654) ~[1.16.4.jar:?]
	... 20 more

Still no iron golem miniature in the spawner
I want to post to epic spawners or the main mojang bugs website but figured I should start here first since im using paper spigot

**Comment by electronicboy** [comment]
https://bugs.mojang.com/browse/MC-189565 - known vanilla issue
