### ISSUE TITLE
Villager randomly disappears

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4997]
I've played one my server and one of my villagers randomly disappears.
Sorry for my english, its not my main language.
Thanks for help,
 - StudioCrusader

Here is result of /version in console:
[15:35:13 INFO]: This server is running Paper version git-Paper-253 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[15:35:13 INFO]: You are running the latest version

Here is result of /plugins in console:  
[15:36:02 INFO]: Plugins (63): AdvancedOreGen, AFKFishing, AFKPlus, AmkMcAuth, BentoBox, BetterDispensers, BetterSleeping3, ChatFilter, DeathCoordinates, DeathMessagesPrime, DiscordSRV, dynmap*, Emoji*, EmojiChat*, Essentials, EssentialsChat, Gaea, Geyser-Spigot, GoldenEnchants, HealthViewr, HolographicDisplays, InfoHUD, InventoryRollback, LaunchMultiCommands, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, MyCommand, NametagHide*, NetherWater, NexEngine, PhatLoots, PictureLogin, PlaceholderAPI, Plan, PlayerControl, PlayTime*, ProtocolLib, QuickBar*, RemoteChat*, SeePlayerInventory, ServerRestorer, ShulkerRespawner, SkinsRestorer, SkQuery, Skript, SuperLobby, TAB, Terra, TridentTweaks, VarLight, Vault, ViaBackwards, ViaVersion, VillagerOptimiser, VoidGenerator, WebConsole, WorldBorder, WorldEdit, ZombieApocalypse

And here is console message of villager disappear:
[15:26:42 WARN]: Entity threw exception at skygrid:-165.18265835795947,125.0,70.90465728456638
[15:26:42 WARN]: java.lang.IllegalStateException: No offered ingredients
[15:26:42 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
[15:26:42 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMerchantRecipe.toMinecraft(CraftMerchantRecipe.java:86)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityVillagerAbstract.a(EntityVillagerAbstract.java:240)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityVillager.eW(EntityVillager.java:827)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityVillagerAbstract.getOffers(EntityVillagerAbstract.java:92)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityVillager.fm(EntityVillager.java:315)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityVillager.fc(EntityVillager.java:353)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.BehaviorWork.a(SourceFile:58)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.BehaviorWork.a(SourceFile:18)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.Behavior.e(SourceFile:49)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.BehaviorGate$Execution$1.lambda$a$1(BehaviorGate.java:85)
[15:26:42 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[15:26:42 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[15:26:42 WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[15:26:42 WARN]:        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
[15:26:42 WARN]:        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
[15:26:42 WARN]:        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
[15:26:42 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[15:26:42 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[15:26:42 WARN]:        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
[15:26:42 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[15:26:42 WARN]:        at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.BehaviorGate$Execution$1.a(BehaviorGate.java:86)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.BehaviorGate.a(BehaviorGate.java:44)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.Behavior.e(SourceFile:49)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.BehaviorController.d(SourceFile:506)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.BehaviorController.a(SourceFile:465)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityVillager.mobTick(EntityVillager.java:169)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityVillager.mobTick(EntityVillager.java:166)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityInsentient.doTick(EntityInsentient.java:763)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityLiving.movementTick(EntityLiving.java:2753)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityInsentient.movementTick(EntityInsentient.java:543)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityAgeable.movementTick(EntityAgeable.java:143)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2478)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityInsentient.tick(EntityInsentient.java:306)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.EntityVillager.tick(EntityVillager.java:211)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:841)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:884)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:526)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:26:42 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:26:42 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by JRoy** [comment]
1.16.3 is unsupported

**Comment by ghost** [comment]
but where i can ask for help?

**Comment by Titaniumtown** [comment]
You can't if you don't use the latest version. Only the latest version has support.

**Comment by ghost** [comment]
Oh

**Comment by ghost** [comment]
But thanks for review

**Comment by Chew** [comment]
Please reproduce on the latest build (1.16.4). Open a new issue if this persists because you didn't fill out the template. Thank you for the report, regardless!
