### ISSUE TITLE
BSP (BossShopPro) PlayerShops addon not working after Paper-355 1.16.4

### ISSUE THREAD

**Issue by EkonC** [PaperMC/Paper#5022]
### What behavior is expected:
___Plugin Playershops (https://www.spigotmc.org/resources/playershops-gui-bsp-allow-players-to-create-public-shops.29568/) should just open its GUI.___

### What behavior is observed:
___Player gets message "An internal error occurred while attempting to perform this command" and I get a long error in the console (the error is on the bottom of this report)___

### Steps/models to reproduce:
___Use /playershop or /ps command___

### Plugin list:
___Plugins (40): AdvancedEnchantments, AdvancedMonthlyCrates, BossShopPro, BottledExp, BungeeGuard, Citizens, CMI, CMIPaperLib, CoreProtect, CraftingStore, CustomCrafting, DiscordSRV, DragonSlayer, InventoryRollback, Jobs, LuckPerms, Matrix, MobFarmManager, Multiverse-Core, PlaceholderAPI, Plan, PlayerShops, ProtectionLib*, ProtocolLib, QuickShop, Residence, SkinsRestorer, TAB, TradeMe, TryMe, TutorialCreator, UltimateCatcher, Vault, Votifier, VotingPlugin, WolfyUtilities, WorldEdit, WorldEditGlobalizerBukkit*, WorldGuard, WorldGuardExtraFlags___

### Paper version:
```
>....=>.... [11:57:52 INFO]: This server is running Paper version git-Paper-393 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
>.... [11:57:52 INFO]: Previous version: git-Paper-355 (MC: 1.16.4)
>.... [11:57:52 INFO]: You are running the latest version
```
### Anything else:
___You need BossShopPro (https://www.spigotmc.org/resources/bossshoppro-the-most-powerful-chest-gui-shop-menu-plugin.222/) and PlayerShops plugins for this (https://www.spigotmc.org/resources/playershops-gui-bsp-allow-players-to-create-public-shops.29568/). The last version this plugin was working on was Paper-355. The error is here:___
```
>.... [11:47:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ps' in plugin PlayerShops v1.2.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-393]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-393]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[?:git-Paper-393]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[?:git-Paper-393]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[?:git-Paper-393]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1082) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-393]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 50
at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[?:1.8.0_275]
at net.minecraft.server.v1_16_R3.NonNullList.get(SourceFile:46) ~[patched_1.16.4.jar:git-Paper-393]
at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryCustom$MinecraftInventory.getItem(CraftInventoryCustom.java:72) ~[patched_1.16.4.jar:git-Paper-393]
at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.16.4.jar:git-Paper-393]
at org.black_ixx.bossshop.managers.ShopCustomizer.addItem(ShopCustomizer.java:191) ~[?:?]
at org.black_ixx.bossshop.managers.ShopCustomizer.createInventory(ShopCustomizer.java:155) ~[?:?]
at org.black_ixx.bossshop.managers.ShopCustomizer.createInventory(ShopCustomizer.java:41) ~[?:?]
at org.black_ixx.bossshop.core.BSShop.createInventory(BSShop.java:198) ~[?:?]
at org.black_ixx.bossshop.core.BSShop.openInventory(BSShop.java:293) ~[?:?]
at org.black_ixx.bossshop.core.BSShop.openInventory(BSShop.java:268) ~[?:?]
at org.black_ixx.bossshop.addon.playershops.managers.PlayerShopsManager.openShoplist(PlayerShopsManager.java:155) ~[?:?]
at org.black_ixx.bossshop.addon.playershops.managers.CommandManager.onCommand(CommandManager.java:34) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-393]
... 19 more

**Comment by electronicboy** [comment]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 50
at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[?:1.8.0_275]
at net.minecraft.server.v1_16_R3.NonNullList.get(SourceFile:46) ~[patched_1.16.4.jar:git-Paper-393]
at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryCustom$MinecraftInventory.getItem(CraftInventoryCustom.java:72) ~[patched_1.16.4.jar:git-Paper-393]
```

The plugin is trying to access an inventory slot that does not exist, this sounds like a config issue on your side or a plugin issue

**Comment by EkonC** [comment]
Okay, but why does it always work when I go back to Paper-355? You must've changed something in Paper-356 that causes this

**Comment by electronicboy** [comment]
Spigot modified the way legacy text is handled in 356, that has nothing to do with inventories so can only assume that the plugin derp'd itself due to some changes in spigot, I'd suggest speaking the developer for support, if there is some disparity between spigot here, we can look into it but would need info on such

Given their code, this is 100% unlikely to be a relevant change at all to your actual error

**Comment by EkonC** [comment]
Okay, thank you
