### ISSUE TITLE
ArrayIndexOutOfBoundsException when modifying chunk entity list

### ISSUE THREAD

**Issue by pizzanakin** [PaperMC/Paper#5044]
**Stack trace**
`java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 17
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.rehash(Int2IntOpenHashMap.java:1139) ~[patched_1.16.4.jar:git-Paper-400]
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.insert(Int2IntOpenHashMap.java:267) ~[patched_1.16.4.jar:git-Paper-400]
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.putIfAbsent(Int2IntOpenHashMap.java:462) ~[patched_1.16.4.jar:git-Paper-400]
	at com.destroystokyo.paper.util.maplist.EntityList.add(EntityList.java:54) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:596) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.WorldServer.chunkCheck(WorldServer.java:943) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Entity.setPosition(Entity.java:394) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Entity.af(Entity.java:398) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Entity.setPositionRotation(Entity.java:1331) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:557) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:587) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:535) ~[patched_1.16.4.jar:git-Paper-400]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:90) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelManager.moveModelToLocation(ModelManager.java:71) ~[?:?]
	at net.libercraft.custom_entities.CustomEntityManager$2.run(CustomEntityManager.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-400]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-400]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

`[05:27:11] [Craft Scheduler Thread - 3941/WARN]: [LiberCore] Plugin LiberCore v0.3 generated an exception while executing task 1335
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 17
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.rehash(Int2IntOpenHashMap.java:1139) ~[patched_1.16.4.jar:git-Paper-400]
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.insert(Int2IntOpenHashMap.java:267) ~[patched_1.16.4.jar:git-Paper-400]
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.putIfAbsent(Int2IntOpenHashMap.java:462) ~[patched_1.16.4.jar:git-Paper-400]
	at com.destroystokyo.paper.util.maplist.EntityList.add(EntityList.java:54) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:596) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.WorldServer.chunkCheck(WorldServer.java:943) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Entity.setPosition(Entity.java:394) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Entity.af(Entity.java:398) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Entity.setPositionRotation(Entity.java:1331) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:557) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:587) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:535) ~[patched_1.16.4.jar:git-Paper-400]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:90) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:94) ~[?:?]
	at net.libercraft.armorstand_models.ModelManager.moveModelToLocation(ModelManager.java:71) ~[?:?]
	at net.libercraft.custom_entities.CustomEntityManager$2.run(CustomEntityManager.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-400]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-400]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

`[05:27:25] [Server thread/WARN]: Entity threw exception at world:-377.62183609800877,45.03592334710505,1648.098834383508
[05:27:25] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 17
[05:27:25] [Server thread/WARN]: 	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.rehash(Int2IntOpenHashMap.java:1139)
[05:27:25] [Server thread/WARN]: 	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.insert(Int2IntOpenHashMap.java:267)
[05:27:25] [Server thread/WARN]: 	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.putIfAbsent(Int2IntOpenHashMap.java:462)
[05:27:25] [Server thread/WARN]: 	at com.destroystokyo.paper.util.maplist.EntityList.add(EntityList.java:54)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:596)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.chunkCheck(WorldServer.java:943)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.Entity.recalcPosition(Entity.java:949)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.Entity.move(Entity.java:626)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityLiving.a(EntityLiving.java:2378)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityLiving.g(EntityLiving.java:2337)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityLiving.movementTick(EntityLiving.java:2804)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityInsentient.movementTick(EntityInsentient.java:546)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityAgeable.movementTick(EntityAgeable.java:143)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityAnimal.movementTick(EntityAnimal.java:34)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityBee.movementTick(EntityBee.java:355)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2489)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:309)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityBee.tick(EntityBee.java:164)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.World.a(World.java:886)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992)
[05:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[05:27:25] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)`

`[05:27:25] [Craft Scheduler Thread - 3940/WARN]: [LiberCore] Plugin LiberCore v0.3 generated an exception while executing task 1335
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 17
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.rehash(Int2IntOpenHashMap.java:1139) ~[patched_1.16.4.jar:git-Paper-400]
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.insert(Int2IntOpenHashMap.java:267) ~[patched_1.16.4.jar:git-Paper-400]
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.putIfAbsent(Int2IntOpenHashMap.java:462) ~[patched_1.16.4.jar:git-Paper-400]
	at com.destroystokyo.paper.util.maplist.EntityList.add(EntityList.java:54) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:596) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.WorldServer.chunkCheck(WorldServer.java:943) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Entity.setPosition(Entity.java:394) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Entity.af(Entity.java:398) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.Entity.setPositionRotation(Entity.java:1331) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:557) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:587) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:535) ~[patched_1.16.4.jar:git-Paper-400]
	at net.libercraft.armorstand_models.ModelUpdater.moveBodyPartToLocation(ModelUpdater.java:90) ~[?:?]
	at net.libercraft.armorstand_models.ModelManager.moveModelToLocation(ModelManager.java:71) ~[?:?]
	at net.libercraft.custom_entities.CustomEntityManager$2.run(CustomEntityManager.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-400]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-400]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

after these errors, the Server thread dump kicks in and starts posting logs until the server shuts itself down.

**Plugin list:**
- Armor Stand Editor
- BlockLocker
- Buycraft
- CommandAPI
- CoreProtect
- DiscordSRV
- Dynmap
- EmojiChat
- Item NBT API
- LiberCore (my own custom plugin)
- NuVotifier
- OpenInv
- SAML
- Vault
- WorldBorder
- WorldEdit
- WorldEdit SUI
- WorldGuard
- WorldGuardExtraFlags

**Reproduction:**
So this is quite a specific bug caused by quite specific circumstances. Like I mentioned in the plugin list, I have my own custom plugin, which adds most of the custom features to my server. One of these features is the ability for players to buy 'custom pets'. These are 'entities' with custom models that will walk around like regular mobs, and follow the player.

These custom entity models are made using armor stands that get teleported around to make it appear as if there is an actual entity walking. These crashes tend to be caused by these specific entities getting teleported (probably as they are 'walking' into a new chunk). It is probably caused by the fact that there's many entities around the same place getting teleported almost instantly, making it hard for the entity list to be updated properly (just guessing).

I understand if this type of behaviour will not be fully supported, as it's quite a unique case and it doesn't prohibit most paper servers from functioning properly. However, I quite like being able to add custom entities to my world like this, so I would really appreciate it if there can be a fix for this problem. Perhaps a different implementation of my own code would suffice. I am mostly reporting this to gain some understanding over the situation.

**Version**
I am running Paper version git-Paper-403 (MC: 1.16.4)
(altho this issue has been around for a long time, only decided to report on it now)

**Comment by HexedHero** [comment]
It's your plugin...
"[LiberCore] Plugin LiberCore v0.3"

**Comment by Trigary** [comment]
You are doing stuff async that's not safe. This is a thread-safety issue in your plugin. Namely, you call `#teleport` inside a scheduled async task.

**Comment by pizzanakin** [comment]
you're right! I usually try to put all of the API calls in a synchronized thread. but I checked again and my teleport call is indeed made asynchronously. I must have missed this particular method. thanks!
