### ISSUE TITLE
AsyncPlayerPreLoginEvent.address NPE while spoofing ip via cheat-client

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5065]
### Link/paste of stack trace

```
[22:10:21.998] [User Authenticator #89/ERROR] Could not pass event AsyncPlayerPreLoginEvent to JustPunishment v1.0.0
java.lang.NullPointerException: event.address must not be null
	at ru.justmc.punishment.bukkit.BukkitPunishmentManager.onLoginAddressBan(BukkitPunishmentManager.kt:101) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor48.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
	at net.minecraft.server.v1_16_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:336) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
	at net.minecraft.server.v1_16_R3.LoginListener$1.run(LoginListener.java:228) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[22:10:22.025] [User Authenticator #89/INFO] UUID of player XjCyan1de is 71241f21-2ff5-34d8-926e-818ef9a01b7a
[22:10:22.113] [Server thread/INFO] XjCyan1de joined the game
[22:10:22.155] [Server thread/INFO] XjCyan1de[fuckyou/<unresolved>:41137] logged in with entity id 1344903 at ([snow_japan_spawn]0.0, 69.0, 2.0)
```

### Plugin list:
Custom private plugins

### Actions to reproduce (if known):
Somebody joined by my nickname via cheat-client with IP spoof

### Paper version:
git-Paper-416 (MC: 1.16.4)

**Comment by electronicboy** [comment]
You're not running paper, nor is there really too much we can do about this, fix your firewall setup
