### ISSUE TITLE
Cannot Build Server.

### ISSUE THREAD

**Issue by AverageComet250** [PaperMC/Paper#5081]
End of log (part with issue):
```
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at net.md_5.ss.SpecialSource.map(SpecialSource.java:78)
        at net.md_5.ss.SpecialSource.main(SpecialSource.java:49)
Failed to build Paper
```
PS. I got rid of the template intentionally, because it didn't fit the requirements of my issue.

Environment: AWS Cloud9 IDE, running on an Ubuntu 18.04 EC2 instance. I have OpenJDK 8 (jre and jdk), as well as oracle java 8, but I'm not sure whether that's jdk or jre.

**Comment by Proximyst** [comment]
Corrupt jar. Delete cache and try again.

**Comment by AverageComet250** [comment]
How do I clear my cache?

**Comment by HexedHero** [comment]
Delete your "cache" folder in the root dir of the server.

**Comment by AverageComet250** [comment]
Thanks!
