### ISSUE TITLE
Server crash while startup

### ISSUE THREAD

**Issue by 12jking** [PaperMC/Paper#5090]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

```
---- Minecraft Crash Report ----
// You're mean.

Time: 20.01.21, 14:52
Description: Exception in server tick loop

java.lang.RuntimeException: net.minecraft.server.v1_16_R3.SessionLock$ExceptionWorldConflict: /home/pi/Desktop/Server/Paper/./world_nether/session.lock: already locked (possibly by other Minecraft instance?)
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:360)
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: net.minecraft.server.v1_16_R3.SessionLock$ExceptionWorldConflict: /home/pi/Desktop/Server/Paper/./world_nether/session.lock: already locked (possibly by other Minecraft instance?)
	at net.minecraft.server.v1_16_R3.SessionLock$ExceptionWorldConflict.a(SourceFile:98)
	at net.minecraft.server.v1_16_R3.SessionLock.a(SourceFile:44)
	at net.minecraft.server.v1_16_R3.Convertable$ConversionSession.<init>(Convertable.java:218)
	at net.minecraft.server.v1_16_R3.Convertable.c(Convertable.java:200)
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:358)
	... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (arm) version 5.4.72-v7+
	Java Version: 11.0.9.1, Raspbian
	Java VM Version: OpenJDK Server VM (mixed mode), Raspbian
	Memory: 85192480 bytes (81 MB) / 213520384 bytes (203 MB) up to 1037959168 bytes (989 MB)
	CPUs: 4
	JVM Flags: 1 total; -Xmx1G
	CraftBukkit Information: 
   Running: Paper version git-Paper-436 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) true
   Plugins: { FastAsyncWorldEdit v1.16-560;6895fe3 com.sk89q.worldedit.bukkit.WorldEditPlugin [Empire92, MattBDev, IronApollo, dordsor21, NotMyFault], Doomofstation v1.0-SNAPSHOT de.j.doom.main.Main [],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { TIMED_WAITING pool-4-thread-1: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123), java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING Java2D Disposer: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.desktop@11.0.9.1/sun.java2d.Disposer.run(Disposer.java:144), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING Paper Async Chunk Urgent Task Thread: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Finalizer: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@11.0.9.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)], WAITING Paper Async Chunk Task Thread #1: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Paper Watchdog Thread: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), app//org.spigotmc.WatchdogThread.run(WatchdogThread.java:170)], TIMED_WAITING pool-10-thread-1: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123), java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING Timer hack thread: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), app//net.minecraft.server.v1_16_R3.SystemUtils$5.run(SystemUtils.java:465)], WAITING Worker-Main-1: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING Common-Cleaner: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@11.0.9.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834), java.base@11.0.9.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)], RUNNABLE Reference Handler: [java.base@11.0.9.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@11.0.9.1/java.lang.ref.Reference.processPendingReferences(Reference.java:241), java.base@11.0.9.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)], RUNNABLE Server console handler: [java.base@11.0.9.1/java.io.FileInputStream.read0(Native Method), java.base@11.0.9.1/java.io.FileInputStream.read(FileInputStream.java:231), app//org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73), app//org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), app//org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), app//org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), app//org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), app//org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), app//org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), app//org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848), app//org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868), app//org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575), app//org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418), app//net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158), app//net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141), app//net.minecraft.server.v1_16_R3.DedicatedServer$1.run(DedicatedServer.java:67)], WAITING Paper Async Chunk Task Thread #0: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING WorldEdit Session Manager: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:553), java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)], RUNNABLE Log4j2-TF-1-AsyncLogger[AsyncContext@d8cfe0]-1: [java.base@11.0.9.1/jdk.internal.loader.BootLoader.getDefinedPackage(BootLoader.java:182), java.base@11.0.9.1/jdk.internal.loader.BootLoader.definePackage(BootLoader.java:170), java.base@11.0.9.1/java.lang.Class.getPackage(Class.java:968), app//org.apache.logging.log4j.core.impl.ThrowableProxy.toCacheEntry(ThrowableProxy.java:598), app//org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:647), app//org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:138), app//org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122), app//org.apache.logging.log4j.core.async.RingBufferLogEvent.getThrownProxy(RingBufferLogEvent.java:330), app//org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61), app//org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38), app//org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:455), app//org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:232), app//org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:217), app//org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57), app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177), app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170), app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161), app//org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:218), app//org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156), app//org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129), app//org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120), app//org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84), app//org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448), app//org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433), app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417), app//org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79), app//org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:337), app//org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161), app//org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45), app//org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29), app//com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168), app//com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING Snooper Timer: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.Object.wait(Object.java:328), java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:527), java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)], RUNNABLE DestroyJavaVM: [], RUNNABLE Signal Dispatcher: [], RUNNABLE Netty Server IO #0: [java.base@11.0.9.1/sun.nio.ch.EPoll.wait(Native Method), java.base@11.0.9.1/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120), java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124), java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141), app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68), app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:803), app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457), app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989), app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING Paper Async Chunk Task Thread #2: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Worker-Main-2: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING process reaper: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234), java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462), java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361), java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], RUNNABLE Server thread: [java.base@11.0.9.1/java.lang.Thread.dumpThreads(Native Method), java.base@11.0.9.1/java.lang.Thread.getAllStackTraces(Thread.java:1658), app//org.bukkit.craftbukkit.v1_16_R3.CraftCrashReport.call(CraftCrashReport.java:33), app//net.minecraft.server.v1_16_R3.CrashReportSystemDetails.a(SourceFile:79), app//net.minecraft.server.v1_16_R3.CrashReport.i(CrashReport.java:71), app//net.minecraft.server.v1_16_R3.CrashReport.<init>(CrashReport.java:35), app//net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1028), app//net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173), app//net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3141/0x2d289c28.run(Unknown Source), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)],}
   
   Force Loaded Chunks: { world: {},}
	Player Count: 0 / 4; []
	Data Packs: vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
FaWe (Fastasyncworldedit)

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
#436

**Comment by clrxbl** [comment]
java.lang.RuntimeException: net.minecraft.server.v1_16_R3.SessionLock$ExceptionWorldConflict: /home/pi/Desktop/Server/Paper/./world_nether/session.lock: already locked (possibly by other Minecraft instance?)

**Comment by Proximyst** [comment]
Read the error message. Use your eyes.
![https://media1.tenor.com/images/94e7550dbf3fced4a78ece71b887ad71/tenor.gif](https://media1.tenor.com/images/94e7550dbf3fced4a78ece71b887ad71/tenor.gif?itemid=15852212)
