### ISSUE TITLE
Noticed  io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by ricsal1** [PaperMC/Paper#5098]
### Link/paste of stack trace
[11:00:56 WARN]: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 69
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:00:56 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[11:00:56 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[11:00:56 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[11:00:56 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[11:00:56 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[11:00:56 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[11:00:56 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:00:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[11:00:56 WARN]: Caused by: java.io.IOException: Bad packet id 69
[11:00:56 WARN]:        at net.minecraft.server.v1_16_R3.PacketDecoder.decode(SourceFile:37)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[11:00:56 WARN]:        ... 35 more
[11:00:56 WARN]: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 84
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:00:56 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:00:56 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:00:56 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[11:00:56 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[11:00:56 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[11:00:56 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[11:00:56 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[11:00:56 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[11:00:56 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:00:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[11:00:56 WARN]: Caused by: java.io.IOException: Bad packet id 84
[11:00:56 WARN]:        at net.minecraft.server.v1_16_R3.PacketDecoder.decode(SourceFile:37)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[11:00:56 WARN]:        ... 35 more
[11:00:56 WARN]: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/32 (PacketPlayInItemName) was larger than I expected, found 136 bytes extra whilst reading packet 32
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[11:00:56 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
[11:00:56 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[11:00:56 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[11:00:56 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[11:00:56 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
[11:00:56 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[11:00:56 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[11:00:56 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
[11:00:56 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[11:00:56 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:00:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[11:00:56 WARN]: Caused by: java.io.IOException: Packet 0/32 (PacketPlayInItemName) was larger than I expected, found 136 bytes extra whilst reading packet 32
[11:00:56 WARN]:        at net.minecraft.server.v1_16_R3.PacketDecoder.decode(SourceFile:42)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[11:00:56 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[11:00:56 WARN]:        ... 27 more

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
DeadChest-4.3.0, DragonDropElytra-1.13_1.0.3, OpenInv, PlayerHeads, UnlimitedAnvil-1.0.6-R

### Paper version:
using paper-1.16.5-439.jar

**Comment by Proximyst** [comment]
Someone thinks they're funny and sends you malformed packets.

**Comment by ricsal1** [comment]
Thank you for your reply.
Any chance this can get a more controlled output (like attack attempt with no exception dump ) and logged into file so we can know the IP who sent it and what was sent?
Regards
