### ISSUE TITLE
Common  java.io.IOException with or without player disconnection

### ISSUE THREAD

**Issue by ricsal1** [PaperMC/Paper#5100]
Hello,

I have been noticing this error (in English is translated as reset by peer) with or without player dropping.
Would recommendnd a more controlled output stating IP address connection was closed without the stack trace, for admin control.

Thanks

### Link/paste of stack trace (these are 2 traces)

[17:52:48 WARN]: java.io.IOException: Uma ligação existente foi forçada a fechar pelo anfitrião remoto
[17:52:48 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
[17:52:48 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
[17:52:48 WARN]:        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
[17:52:48 WARN]:        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
[17:52:48 WARN]:        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
[17:52:48 WARN]:        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
[17:52:48 WARN]:        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
[17:52:48 WARN]:        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
[17:52:48 WARN]:        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
[17:52:48 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
[17:52:48 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[17:52:48 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[17:52:48 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[17:52:48 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[17:52:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:52:48 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:52:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:52:48 INFO]: Tom_Frost lost connection: Disconnected

[17:08:34 INFO]: ****_Minecraftz fell from a high place
[17:08:49 WARN]: java.io.IOException: Uma ligação estabelecida foi anulada pelo software no computador anfitrião
[17:08:49 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
[17:08:49 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
[17:08:49 WARN]:        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
[17:08:49 WARN]:        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
[17:08:49 WARN]:        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
[17:08:49 WARN]:        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
[17:08:49 WARN]:        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:408)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
[17:08:49 WARN]:        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)[17:08:49 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
[17:08:49 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
[17:08:49 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.flushNow(FlushConsolidationHandler.java:204)[17:08:49 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.flush(FlushConsolidationHandler.java:138)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
[17:08:49 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[17:08:49 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[17:08:49 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:273)
[17:08:49 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249)
[17:08:49 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225)
[17:08:49 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.exceptionCaught(NetworkManager.java:133)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[17:08:49 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.exceptionCaught(FlushConsolidationHandler.java:159)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[17:08:49 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[17:08:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[17:08:49 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
[17:08:49 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125)
[17:08:49 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
[17:08:49 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[17:08:49 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[17:08:49 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[17:08:49 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[17:08:49 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:08:49 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:08:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:08:49 WARN]: java.io.IOException: Uma ligação estabelecida foi anulada pelo software no computador anfitrião
[17:08:49 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
[17:08:49 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
[17:08:49 WARN]:        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
[17:08:49 WARN]:        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
[17:08:49 WARN]:        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
[17:08:49 WARN]:        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
[17:08:49 WARN]:        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
[17:08:49 WARN]:        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
[17:08:49 WARN]:        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
[17:08:49 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
[17:08:49 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[17:08:49 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[17:08:49 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[17:08:49 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[17:08:49 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:08:49 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:08:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:08:51 INFO]: UUID of player Tom_Frost is c2045c2f-b037-4e6e-893e-cb32b4086564
[

### Plugin list:
DeadChest-4.3.0, DragonDropElytra-1.13_1.0.3, OpenInv, PlayerHeads, UnlimitedAnvil-1.0.6-R

### Actions to reproduce (if known):
Just wait with it running and having users on it

### Paper version:
paper-1.16.5-439.jar

**Comment by electronicboy** [comment]
A connection was closed, externally, in an unexpected manner

**Comment by ricsal1** [comment]
Hello, thanks for the fast reply.
Although that is known, have some KB of log files with stacktrace may be a a sign of resource leak (memory, threads, sockets, semaphores, ...) 
Also for admin purposes it gives no info if it ir from an external cause and/or its origin.

Would recommend a better exception handling.
Regards

**Comment by Proximyst** [comment]
We don't control the message, your OS does. Complain to the Linux mailing list, Apple Support, or Microsoft Support/forums.

Look at #895 for info about the issue

**Comment by ricsal1** [comment]
Hello,
I don't mean the message it self, or the issue origin, I know it is a fact and how we get it at tcp low level.
I mean the exception handling in java, i am insisting on these because i have some experience (good and bad) in this area.

Will look into your sources, too look at the possible impact of these exceptions and if i find a good way to handle it, if needed, I will reply here again.

Thanks for your fast reply

**Comment by electronicboy** [comment]
There is nothing that we can do to provide a more "useful" message bar tryna see if it's worth the effort of shoving the IP into there
