### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by Mensh123** [PaperMC/Paper#5133]
Version: 1.16.5-449 (MS Windows 10)

I get an error: `java.io.IOException: Das Handle ist ungültig`(Im'm not running an english verion of Windows. translated: `java.io.IOException: the handle is invalid`). The Plugin that caused the 2nd error message is my own plugin (name replaced with `my/plugin/path` and filename replaced with `my_plugin_file.jar`) but when I hadn't installed it the 1st error was displayed anyway.

I can still join my server. Everything changed: `eula` in `eula.txt` is `true`. Whitelist is on (scince first try - issue existed before). I've whitelistet my self and I'm operator as well (scince first try). `plugins/my_plugin_file.jar` added (2nd try).

Her's the log:

---------------------
```
[08:16:00 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[08:16:00 INFO]: Reloading ResourceManager: Default, bukkit
[08:16:02 INFO]: Loaded 7 recipes
[08:16:07 INFO]: Starting minecraft server version 1.16.5
[08:16:07 INFO]: Loading properties
[08:16:07 ERROR]: Failed to read console input
java.io.IOException: Das Handle ist ungültig
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:273) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:283) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:344) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:185) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:326) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:392) ~[?:?]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:180) ~[patched_1.16.5.jar:git-Paper-449]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[patched_1.16.5.jar:git-Paper-449]
	at net.minecraft.server.v1_16_R3.DedicatedServer$1.run(DedicatedServer.java:67) ~[patched_1.16.5.jar:git-Paper-449]
	Suppressed: java.io.IOException: Das Handle ist ungültig
		at java.io.FileDescriptor.close0(Native Method) ~[?:?]
		at java.io.FileDescriptor.close(FileDescriptor.java:297) ~[?:?]
		at java.io.FileInputStream$1.close(FileInputStream.java:369) ~[?:?]
		at java.io.FileDescriptor.closeAll(FileDescriptor.java:355) ~[?:?]
		at java.io.FileInputStream.close(FileInputStream.java:367) ~[?:?]
		at java.io.BufferedInputStream.close(BufferedInputStream.java:482) ~[?:?]
		at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:391) ~[?:?]
		at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:204) ~[?:?]
		at java.io.InputStreamReader.close(InputStreamReader.java:200) ~[?:?]
		at java.io.BufferedReader.close(BufferedReader.java:528) ~[?:?]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:183) ~[patched_1.16.5.jar:git-Paper-449]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[patched_1.16.5.jar:git-Paper-449]
		at net.minecraft.server.v1_16_R3.DedicatedServer$1.run(DedicatedServer.java:67) ~[patched_1.16.5.jar:git-Paper-449]
[08:16:07 INFO]: This server is running Paper version git-Paper-449 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[08:16:07 INFO]: Debug logging is disabled
[08:16:07 INFO]: Using 4 threads for Netty based IO
[08:16:07 INFO]: Server Ping Player Sample Count: 12
[08:16:07 INFO]: Default game type: SURVIVAL
[08:16:07 INFO]: Generating keypair
[08:16:08 INFO]: Starting Minecraft server on *:25565
[08:16:08 INFO]: Using default channel type
[08:16:10 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[08:16:20 WARN]: Legacy plugin creeperwalk_challenge v1.0 does not specify an api-version.
[08:16:20 ERROR]: Could not load 'plugins\my_plugin_file.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/mensh123/creeperwalk_challenge/Main has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 57.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-449]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-449]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-449]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-449]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: my/plugin/path/Main has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 57.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:178) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-449]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:416) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-449]
	... 7 more
[08:16:20 INFO]: Server permissions file permissions.yml is empty, ignoring it
[08:16:20 INFO]: Preparing level "world"
[08:16:20 INFO]: Preparing start region for dimension minecraft:overworld
[08:16:21 INFO]: Loaded 0 spawn chunks for world world
[08:16:21 INFO]: Time elapsed: 365 ms
[08:16:21 INFO]: Preparing start region for dimension minecraft:the_nether
[08:16:21 INFO]: Loaded 0 spawn chunks for world world_nether
[08:16:21 INFO]: Time elapsed: 135 ms
[08:16:21 INFO]: Preparing start region for dimension minecraft:the_end
[08:16:21 INFO]: Loaded 0 spawn chunks for world world_the_end
[08:16:21 INFO]: Time elapsed: 131 ms
[08:16:21 INFO]: Running delayed init tasks
[08:16:21 INFO]: Done (14.007s)! For help, type "help"
[08:16:21 INFO]: Timings Reset
```

**Comment by TheDGOfficial** [comment]
I don’t know about the first error, but the second is Java version
incompatibility. Your server is running on class file version 57 (Java 13)
and your plugin is compiled with 59 (Java 15)

So you have to either switch the server to Java 15 or compile your plugin
with Java 13 (or add —release 13)

You might need -DPaper.IgnoreJavaVersion=true to use Java 15.

**Comment by Proximyst** [comment]
The first exception is just your terminal not having the features required for console to operate correctly. Try using a modern terminal and shell such as PowerShell with [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab).

The second error is an invalid plugin. See TheDGOfficial's comment.
