### ISSUE TITLE
main class does not extend JavaPlugin

### ISSUE THREAD

**Issue by Mensh123** [PaperMC/Paper#5135]
### What behaviour is expected:
install my java plugin

### What behaviour is observed:
`org.bukkit.plugin.InvalidPluginException: main class \`example.thatsMe.pluginname.Main' does not extend JavaPlugin`

### Some information:
`plugin.yml`:
```
name: plugin_name
version: 1.0
author: thatsMe
main: example.thatsMe.pluginname.Main

commands:
    mycommand:
        aliasses: [mc]
```
`Main.java`:
```
package example.thatsme.pluginname;

import org.bukkit.plugin.java.JavaPlugin;

import example.thatsme.pluginname.commands.ACommand; //ACommand.java registrates the command. I'm not going to append it because I think you'll not need it to fix this Issue.

public class Main extends JavaPlugin {
    
    @Override
    public void onEnable() {
        new ACommand();
    }
}

```

### Plugin list:
 - bStats
 - (my plugin but actually it's not installed. See log bellow)

### Paper version:
1.16.5-449

-----

### Anything else:
Log:
```
org.bukkit.plugin.InvalidPluginException: main class `example.thatsme.pluginname.Main' does not extend JavaPlugin
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-449]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-449]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-449]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-449]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-449]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassCastException: class example.thatsme.pluginname.Main
	at java.lang.Class.asSubclass(Class.java:3851) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[patched_1.16.5.jar:git-Paper-449]
	... 8 more
```

**Comment by Proximyst** [comment]
Not a Paper issue. Join our Discord for help in troubleshooting this.
