### ISSUE TITLE
Client side freeze on player.teleport() across worlds when dying!

### ISSUE THREAD

**Issue by Wolf2323** [PaperMC/Paper#5151]
I am a developer of BetonQuest. Some of our users started to complain about exceptions seemingly stemming from our plugin after updateing to the latest paper version.
The exception happens when the player is teleported from the nether to the overworld. This happens only when the player would die. I explained it in more detail below.

### What behaviour is expected:
___What you expected to see___
When a player would die from the damage of a EntityDamageEvent we cancel the event and heal him. Then we teleport him to the overworld.

### What behaviour is observed:
___What you actually saw___
When the player is damaged by a zombified_piglin (seems to be damaged by entities in general) the player get not teleported and the sever seems to be freezed for the client. He is still in the nether and no entity move he is not able to write anything in the chat and so on.

This is the stacktrace:
```
[17:13:02 ERROR]: Could not pass event EntityDamageByEntityEvent to BetonQuest v2.0.0-DEV-UNOFFICIAL
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_16_R3.WorldServer.removeEntity(WorldServer.java:1478) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.WorldServer.removePlayer(WorldServer.java:1498) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:735) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(CraftPlayer.java:835) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:535) ~[patched_1.16.5.jar:git-Paper-457]
        at org.betonquest.betonquest.objectives.DieObjective.onLastDamage(DieObjective.java:74) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor279.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-457]        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1067) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:954) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:910) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1099) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1838) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:842) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1166) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:759) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:845) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityInsentient.attackEntity(EntityInsentient.java:1523) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityZombie.attackEntity(EntityZombie.java:299) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.a(SourceFile:142) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.e(SourceFile:134) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PathfinderGoalZombieAttack.e(SourceFile:28) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:149) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityInsentient.doTick(EntityInsentient.java:761) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityLiving.movementTick(EntityLiving.java:2771) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityInsentient.movementTick(EntityInsentient.java:547) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityMonster.movementTick(EntityMonster.java:23) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityZombie.movementTick(EntityZombie.java:206) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2497) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:310) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityZombie.tick(EntityZombie.java:176) ~[patched_1.16.5.jar:git-Paper-457]        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:846) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.World.a(World.java:887) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:531) ~[patched_1.16.5.jar:git-Paper-457]        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1357) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
First here is the original code of the plugin: https://github.com/BetonQuest/BetonQuest/blob/ea1b94958dcb77c2afac2c49a81d4ce86e5a4294/src/main/java/pl/betoncraft/betonquest/objectives/DieObjective.java#L75
As you can see, we cancel the event and remove all effects and so on, so that it looks like the player was respawned. Then we teleport the player.

### Plugin list:
___A list of your plugins___
BetonQuest

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
`This server is running Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

### Anything else:
___Anything else you think may help us resolve the problem___
For us it looks like it is not possible anymore to cancel a EntityDamageEvent  caused by entities and teleport the player to an other word.

**Comment by electronicboy** [comment]
Don't think that anything has changed here in a good while, if it has, we'd need more info on where the regression was introduced; Teleporting entities in general mid-tick is sketchy, the game works around knowing that there are general points in which it can do stuff, e.g. cross world teleportation is done in a specific phase of the tick where it knows that it's not specifically ticking entities, I'm not really sure that we can even really sanely fix this one without butchering that logic or delaying the teleport on our side

**Comment by Wolf2323** [comment]
Sorry that i did not checked this before, but this is also the case on spigot.
So i think this can be closed here and i need to open a issue on spigot.
Is there anything else i can do or just reporting to Spigot?

**Comment by Wolf2323** [comment]
found the issue on Spigot: https://hub.spigotmc.org/jira/browse/SPIGOT-5285
