### ISSUE TITLE
Server Not Starting?

### ISSUE THREAD

**Issue by kazi-kaz** [PaperMC/Paper#5164]
C:\Users\user\Desktop\1.16.5 Server>java -Xmx7G -jar server.jar nogui
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:167)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:80)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:49)

C:\Users\user\Desktop\1.16.5 Server>PAUSE
Press any key to continue . . .

**I haven't ever got this error before. I also have the latest version of java.**

**Comment by electronicboy** [comment]
the path to the folder includes either invalid characters, weird environment issues, e.g. onedrive, etc
