### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Kgym-Hina** [PaperMC/Paper#5165]
### Link/paste of stack trace

    https://pastebin.com/Nim15CVf
`Patching vanilla jar...
Failed to read vanilla jar and patch file
java.util.zip.ZipException: invalid code lengths set
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
at java.io.FilterInputStream.read(FilterInputStream.java:133)
at io.papermc.paperclip.Paperclip.readFully(Paperclip.java:311)
at io.papermc.paperclip.Paperclip.checkPaperJar(Paperclip.java:139)
at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:95)
at io.papermc.paperclip.Paperclip.main(Paperclip.java:49)`

### Plugin list:

    NO PLUGINS

### Actions to reproduce (if known):

 Download latest build of paper on papermc.io, start the server.

### Paper version:

Paper 1.16.4
#416

**Comment by Proximyst** [comment]
Corrupt jar, delete the cache

**Comment by Kgym-Hina** [comment]
> Corrupt jar, delete the cache
Tried, then it repeats.

**Comment by Kgym-Hina** [comment]
Works just fine with these files on local but not remote server.

**Comment by aurorasmiles** [comment]
Enable binary mode in Filezilla if you're using that
