### ISSUE TITLE
GUI Issues & Dupes

### ISSUE THREAD

**Issue by slvlr** [PaperMC/Paper#5222]
### What behaviour is expected:
/openinv <target> should open the targets inventory. This works while they are online or offline.

/redeem should open up a GUI, which lets you spend mcmmo credits.

### What behaviour is observed:
Inventory did not open, and nothing printed in chat.

/Redeem did open up the GUI, however players were able to simply remove items from the GUI menu, duping them.

### Steps/models to reproduce:
/openinv <target> - https://dev.bukkit.org/projects/openinv
/redeem https://www.spigotmc.org/resources/morphredeem-1-13-x-1-16-mcmmo-redeem.67435/updates

### Plugin list:
![image](https://user-images.githubusercontent.com/8680731/108713126-b4033380-750f-11eb-8b0d-7fc2cc24fe48.png)

https://dev.bukkit.org/projects/openinv
https://www.spigotmc.org/resources/morphredeem-1-13-x-1-16-mcmmo-redeem.67435/updates

### Paper version:
1.16.5 Build 477

### Anything else:
I backdated from build 477 to build 470 and this issue did not happen. This is how I know it is a paper issue.

**Comment by kashike** [comment]
@slvlr Can you test to see if this is fixed with build 482 (currently building)?

**Comment by selfslaughter** [comment]
Dunno bout the redeem plugin, but openinv just throws a slightly different error on 482.

**477**
```
[23:31:38 WARN]: Task #1283030 for OpenInv v4.1.5 generated an exception
java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract net.kyori.adventure.text.Component title()' of abstract class org.bukkit.inventory.InventoryView.
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftContainer.<init>(CraftContainer.java:54) ~[patched_1.16.5.jar:git-Paper-477]
        at com.lishid.openinv.internal.v1_16_R3.PlayerDataManager$3.<init>(PlayerDataManager.java:237) ~[?:?]
        at com.lishid.openinv.internal.v1_16_R3.PlayerDataManager.openInventory(PlayerDataManager.java:237) ~[?:?]
        at com.lishid.openinv.OpenInv.openInventory(OpenInv.java:265) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:173) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand.access$100(OpenInvCommand.java:34) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:92) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-477]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-477]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-477]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-477]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-477]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-477]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-477]
```

**482**        
```
        [23:41:06 WARN]: Task #5924 for OpenInv v4.1.5 generated an exception
java.lang.AbstractMethodError: Receiver class com.lishid.openinv.internal.v1_16_R3.PlayerDataManager$2 does not define or inherit an implementation of the resolved method 'abstract net.kyori.adventure.text.Component title()' of abstract class org.bukkit.inventory.InventoryView.
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftContainer.<init>(CraftContainer.java:54) ~[patched_1.16.5.jar:git-Paper-482]
        at com.lishid.openinv.internal.v1_16_R3.PlayerDataManager$3.<init>(PlayerDataManager.java:237) ~[?:?]
        at com.lishid.openinv.internal.v1_16_R3.PlayerDataManager.openInventory(PlayerDataManager.java:237) ~[?:?]
        at com.lishid.openinv.OpenInv.openInventory(OpenInv.java:265) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:173) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand.access$100(OpenInvCommand.java:34) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:92) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-482]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-482]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-482]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-482]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-482]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-482]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-482]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by kashike** [comment]
Try build 483 when it is available.

**Comment by Jikoo** [comment]
For reference in case it helps, here's how I hacked around the 1.15? inventory title changes in OpenInv:
https://github.com/lishid/OpenInv/blob/dad00d2d9c86981e0c24c9fb7af72985b1403412/internal/v1_16_R3/src/main/java/com/lishid/openinv/internal/v1_16_R3/PlayerDataManager.java#L190-L273

The container should have a valid title set that can be converted by a default implementation.

/e: I see you've already done that just now while I was typing this. Whoops.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/75625135/108753831-8507b480-7545-11eb-8db5-e0204052a1c7.png)

after use [i] on the chat (the plugin displays on the chat the player's item/inventory /ender chest)
I'am using paper #483

**Comment by ghost** [comment]
LOL

**Comment by Chew** [comment]
Please refrain from off-topic comments.

**Comment by slvlr** [comment]
I see this is marked as "To Do" in Adventure.
For now, has this change been reverted? I am 26 versions behind, not sure if I should update, but obviously don't want to update and have this issues occurring again.

**Comment by kashike** [comment]
> 
> 
> Try build 483 when it is available.

@slvlr I said this the other day, you did not respond - try the latest build.

**Comment by slvlr** [comment]
Both Openinv and Morphredeem seem to be working fine now.

**Comment by slvlr** [comment]
Tested this on build 496
