### ISSUE TITLE
Strange Bug with papermc build #473

### ISSUE THREAD

**Issue by Wolf2323** [PaperMC/Paper#5273]
### What behaviour is expected:
___What you expected to see___
I am the developer of BetonQuest. We have a system for conversations with NPCs. Normally if you click on an NPC the conversation starts. This looks normaly like this: https://betonquest.github.io/BetonQuest/DEV/media/content/User-Documentation/Conversations/MenuConvIO.mp4

### What behaviour is observed:
___What you actually saw___
Now if a player clicks on an npc first nothing happens and then a view seconds later the Conversation starts but cannot be controlled anymore. That is how that looks like https://cdn.discordapp.com/attachments/814871919165833227/814936982323986482/Untitled.mp4
We also tested it without Citizens and started the conversation over a comment but that also dose not help.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
I tried a long time to find how it can be reproduced. Unfortunately i cannot reproduce it. At the moment two users of BetonQuest have this issue, and they can not get rid of it.
After long testing on there servers, we figured out that everything works fine on papermc build #472 but with papermc build #473 and all following builds up to #499 it breaks.

I tryed to to reproduce it withe the same version but it was not possible.

### Plugin list:
___A list of your plugins___
BetonQuest (2.0.0-DEV-23)
Citizens (2.0.27-SNAPSHOT (build 2272))
ProtocolLib (4.6.0)

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-499 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
but every version from 473 up to 499 what is the latest wight now

### Anything else:
___Anything else you think may help us resolve the problem___
I really tried to give more information how it can be reproduced. The things that i managed to figure out is, that you only need BetonQuest as plugin to reproduce the issue,  if you are effected.
That is the line of code, that produce this issue: https://github.com/BetonQuest/BetonQuest/blob/cccc002258163a36674f83a952bef8de04da7f4c/src/main/java/org/betonquest/betonquest/conversation/Conversation.java#L333

I will continue try to replicate this issue or get more information.

**Comment by Wolf2323** [comment]
We have the next user with a simular issue and i can provide a stacktrace, but i am not sure, if that is exactly the same issue as above or not.

EDIT: The following stacktrace is not related to the above issue and can be ignored.
```
[20:30:05] [Async Chat Thread - #14/ERROR]: [BetonQuest] Unhandled exception occured in onPacketSending(PacketEvent) for BetonQuest
java.lang.ClassCastException: net.kyori.adventure.text.TextComponentImpl cannot be cast to [Lnet.md_5.bungee.api.chat.BaseComponent;
	at pl.betoncraft.betonquest.compatibility.protocollib.conversation.PacketInterceptor$1.onPacketSending(PacketInterceptor.java:60) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1742) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1715) ~[patched_1.16.5.jar:git-Paper-503]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2144) ~[patched_1.16.5.jar:git-Paper-503]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:274) ~[patched_1.16.5.jar:git-Paper-503]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:195) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2003) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1855) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1793) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.5.jar:git-Paper-503]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[20:30:05] [Async Chat Thread - #14/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@2e854ee[
    a=<null>
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]

```

**Comment by electronicboy** [comment]
The plugin is accessing server internals and making an assumption about the implementation, I don't believe that there is much we can do here, the plugin needs to update

**Comment by Wolf2323** [comment]
The above stacktrace is not related to the described issue above that. The stacktrace can be ignored.

**Comment by MiniDigger** [comment]
you mean the bug you are describing here still occurs once you fixed that classcastexception?

**Comment by Wolf2323** [comment]
yes, but i am also not sure if the ClassCastException is related to the original issue.

**Comment by Wolf2323** [comment]
Ok, i investigated it more and i think i have found the issue. For me it now looks like that ProtocolLib has not full papermc support for the new Adventure api. I opend a ticket there and i will give feedback here if it was solved and the issue in BetonQuest is also solved. 

https://github.com/dmulloy2/ProtocolLib/issues/1109

**Comment by Wolf2323** [comment]
It seems to be related to ProtocolLib. I opened a issue there: https://github.com/dmulloy2/ProtocolLib/issues/1110
i will give feedback if that solved everything or any other issue appears.

**Comment by LaurenceBarnes** [comment]
did you try the most recent build from that link (their jenkins)?

https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by MonzterDev** [comment]
I'm also experiencing this issue, thanks for reporting it!

**Comment by Chew** [comment]
Yes, please confirm with the latest ProtocolLib build. There was a recent commit that might have fixed it.

**Comment by LaurenceBarnes** [comment]
yeah, it is 4.6.1-Snapshot if we go by version number and not build number, so the OP ist not using this most recent build.

**Comment by LaurenceBarnes** [comment]
Also if you test that newest protocolLib version, make sure to use the newest paper build (as of now, 509) as well

**Comment by Wolf2323** [comment]
I already tested it with both latest versions. And it is still the same. Because of that i opened the issue on ProtocolLib ;)

**Comment by LaurenceBarnes** [comment]
you mentioned Paper build-499 and ProtocolLib 4.6.0, which equals to build-495 in that issue. So do you confirm you used ProtocolLib 4.6.1 build-498?

**Comment by Wolf2323** [comment]
git-Paper-509 and ProtocolLib v4.6.1-SNAPSHOT-b498

**Comment by Wolf2323** [comment]
dmulloy2 from ProtocolLib wrote an answer: https://github.com/dmulloy2/ProtocolLib/issues/1110#issuecomment-790658634

Is that now a new paper behaviour that every plugin has to handle by there own or is that am bug or unwanted change?
If it is a new behaviour that would be bad, because plugins are no longer compatible with the spigot/bukkit api.

**Comment by SirYwell** [comment]
Packets aren't part of the API.

**Comment by electronicboy** [comment]
Don't rely on server internals if you do not wish to have to deal with server internals changing. By relying on server internals, you took up the burden of dealing with internals changing, even bukkit and spigot will act differently here. You're going to need to handle the adventure components.

**Comment by Lorias-Jak** [comment]
I have the same Issue as discribed. Isnt there a way to implement it, that it works in the old way again?

**Comment by Proximyst** [comment]
Packets are not API. This is sadly a side-effect of relying on internals. Either PR API to ProtocolLib to support both Bungee components and Adventure components, or change your code to not do assumptions. You could alternatively look into doing it like [ViaVersion](https://github.com/ViaVersion/ViaVersion) and operate on a purely networking level to avoid this, as then it will all be JSON.

Closing as nothing to fix on our side.

**Comment by Wolf2323** [comment]
Only to help everyone that ran into the same problem.

The package has the following format on Spigot:
```
0: IChatBaseComponent
1: BaseComponent[]
2: ChatMessageType
3: UUID
```
And the following format on Paper:
```
0: IChatBaseComponent
1: Component (From Adventure API)
2: BaseComponent[]
3: ChatMessageType
4: UUID
```

As you can see a new field with the index 1 has been introduced and the other fields are now increased by one.
So now you need to handle this by your own, in your code.

**Comment by Proximyst** [comment]
You should not rely on the ordering of fields nonetheless; find it based on type and/or name instead.

**Comment by kennytv** [comment]
(Or do something smorter and use the PacketContainer's meta / something *actually* smart and use the sender uuid)

**Comment by Wolf2323** [comment]
The sender uuid is `00000000-0000-0000-0000-000000000000` every time and it is not possible to set it.

**Comment by kennytv** [comment]
0,0 is for "system" senders if you don't specify one, Paper/adventure provide methods to set that (or you could also just use PL directly as well), then in your listener, wait for your custom UUID for the sender, pass that through and replace it with 0,0 - cancel and store everything else without your UUID

**Comment by SaltyAimbOtter** [comment]
Thank you for your suggestions and help! 😄 👍 
We have tested the UUID method using the Spigot method of setting the UUID - that did not work out. Since we do not want to depend on Paper just yet, we cannot use the other method now. 
We will definitely improve the way we handle packets during our 2.0 rework, this was more of a hotfix. 😉
