### ISSUE TITLE
server is always crashing

### ISSUE THREAD

**Issue by StefCoders** [PaperMC/Paper#5297]
My server always crashes !

I have no plugins

version is 1.16.4

Please help me

```
[17:57:15 INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[17:57:15 ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
at java.lang.Thread.stop(Thread.java:942) [?:?]
at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:753) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:704) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.MinecraftServer.close(MinecraftServer.java:727) ~[patched_1.16.4.jar:git-Paper-416]
at org.bukkit.craftbukkit.v1_16_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[patched_1.16.4.jar:git-Paper-416]
[17:57:15 INFO]: Stopping server
[17:57:15 INFO]: Saving players
[17:57:15 INFO]: Saving worlds
[17:57:15 INFO]: Saving chunks for level 'ServerLevel[spawn]'/minecraft:overworld
```

**Comment by Proximyst** [comment]
(Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)

And you cut out the useful parts.
