### ISSUE TITLE
EntityFishingHook warn

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#531]
# Crash, Stacktrace

### Link/paste of stack trace
```
[16:42:08] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.EntityFishingHook.<init>(net.minecraft.server.v1_11_R1.World)
[16:42:08] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[16:42:08] [Server thread/WARN]: 	at java.lang.Class.getConstructor(Class.java:1825)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityTypes.a(SourceFile:153)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Entity.teleportTo(Entity.java:2331)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Entity.c(Entity.java:2272)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Entity.U(Entity.java:364)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Entity.A_(Entity.java:325)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityFishingHook.A_(EntityFishingHook.java:82)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1760)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.g(World.java:1735)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1552)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:638)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:885)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749)
[16:42:08] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648)
[16:42:08] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:42:10] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.EntityFishingHook.<init>(net.minecraft.server.v1_11_R1.World)
[16:42:10] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[16:42:10] [Server thread/WARN]: 	at java.lang.Class.getConstructor(Class.java:1825)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityTypes.a(SourceFile:153)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Entity.teleportTo(Entity.java:2331)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Entity.c(Entity.java:2272)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Entity.U(Entity.java:364)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Entity.A_(Entity.java:325)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityFishingHook.A_(EntityFishingHook.java:82)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1760)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.g(World.java:1735)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1552)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:638)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:885)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749)
[16:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648)
[16:42:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

### Plugin list:
`GroupManager, FreshWilderness, Vehicles, TintHealth, PerWorldPlugins, PlugMan, EnchantsPlus, NametagEdit, MineMarket-Universal, GeneralLib, EnchantmentAPI, RandomLootChest, RPGPlayerLeveling, EntityDetection, SkinsRestorer, TitleAPI, Healthbar, MaxBans, Hordes, ParticleLIB, CustomArrow, WorldEdit, OpenInv, XRayDetector, ClearLag, AutoMessage, ChatControl, CreativeLimiter, Launchpad, WorldBorder, Multiverse-Core, ProtocolLib, NoCheatPlus, ResourcePackApi, SignEdit, IPWhitelist, EnchantActivePack, ShowItem, Vault, ButtonTP, MobLoot, WorldGuard, SeparateWorldItems, RandomTeleport, ScratchCards, MyCommand, AutoCommandsPlus, Essentials, Kingdoms, TreasureChest, OnTime, AdvancedAchievements, EssentialsChat, CS-CoreLib, ArtMap, BattleTracker, Thirst, Slimefun, EssentialsGeoIP, EssentialsSpawn, PvPManager, TitleManager, SlimefunOres, ProRecipes, BarAPI, CaseOpening, MiniPets`

### Paper build number:
`git-Paper-958`

**Comment by Gabscap** [comment]
Steps to reproduce: Cast the fishing rod into a nether portal.
This Exception also happens on a vanilla server. Please report this problem to [Mojang](https://bugs.mojang.com).

**Comment by Fonzee9** [comment]
Yup this is a bug i tested it on my server got the same error any chance paper can fix it?

**Comment by zachbr** [comment]
Probably pretty simple fix, but its not a priority. This is harmless.

**Comment by aikar** [comment]
this actually seems like a vanilla bug, as i dont see CB/Spigot comments.

This entity has no World only constructor, which is a requirement for entity loading

**Comment by zachbr** [comment]
Yes, we've already established its a vanilla issue.
