### ISSUE TITLE
PaperLib: IllegalStateException: RegionFile is closed

### ISSUE THREAD

**Issue by mfnalex** [PaperMC/Paper#5343]
Hi, one of my plugin's users is getting the following stacktrace whenever my plugin attempts to use the PaperLib's isChunkGenerated method:

```
[11:46:45 WARN]: [AngelChest] Task #2177 for AngelChest v2.22.2 generated an exception
java.lang.IllegalStateException: RegionFile is closed
at net.minecraft.server.v1_16_R3.RegionFile.getStatusIfCached(RegionFile.java:60) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.getChunkStatusOnDisk(PlayerChunkMap.java:1686) ~[patched_1.16.5.jar:git-Paper-499]
at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.isChunkGenerated(CraftWorld.java:461) ~[patched_1.16.5.jar:git-Paper-499]
at de.jeff_media.AngelChest.paperlib.features.chunkisgenerated.ChunkIsGeneratedApiExists.isChunkGenerated(ChunkIsGeneratedApiExists.java:8) ~[?:?]
at de.jeff_media.AngelChest.paperlib.environments.Environment.isChunkGenerated(Environment.java:96) ~[?:?]
at de.jeff_media.AngelChest.paperlib.PaperLib.isChunkGenerated(PaperLib.java:179) ~[?:?]
at de.jeff_media.AngelChest.paperlib.PaperLib.isChunkGenerated(PaperLib.java:168) ~[?:?]
at de.jeff_media.AngelChest.Main.lambda$onEnable$2(Main.java:103) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-499]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1299) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-499]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

Line 103 in de.jeff_media.AngelChest.Main is the following:

```java
if(!PaperLib.isChunkGenerated(comb.block.getLocation())) {
```

Anyone has any idea why this happens? Everything seems to work fine for all other users. Any help would be appreciated, thanks!

Paper version: 499 (1.16.5)
My plugin: AngelChest 2.22.2

**Comment by electronicboy** [comment]
is that the only plugin on the server? This is generally caused by plugins messing with chunks/region files in an unsafe manner

**Comment by mfnalex** [comment]
> is that the only plugin on the server? This is generally caused by plugins messing with chunks/region files in an unsafe manner

Probably not! I will ask the user to post a list of their plugins here.

**Comment by Evil0ctal** [comment]
**Here is my plugin list:**

[ANSI]PlugMan.jar
[EM前置]LibsDisguises-10.0.24-Free.jar
[mcMMO]mcMMO.jar
[NPC]Citizens-2.0.27-b2220.jar
[Ping]SpigotPing_v2.6.jar
[PVP管理]PvPManager.jar
[tag]NametagEdit.jar
[VIP]PixelVip-3.0.3-b82-Universal.jar
[保护]CoreProtect-19.4.jar
[保护]WorldGuardExtraFlags.jar
[备份]ebackup-1.1.4.jar
[背包还原]InventoryRollback-1.4.0.jar
[比特币]Bitcoin.jar
[编辑描述]Editlore.jar
[标题管理]TitleManager-2.3.1.jar
[彩票系统]Lottery.jar
[菜单]TrMenu-2.08.jar
[称号]DeluxeTags.jar
[宠物]MyPet-3.11-SNAPSHOT-B1588.jar
[抽奖]GoldenCrates.jar
[传送门]AncientGates.jar
[创世神]worldedit-bukkit-7.2.2-dist.jar
[村民优化]VillagerLobotomizatornator.jar
[大厅]SuperLobbyDeluxe-4.2.9-shaded.jar
[登录]AuthMe-5.6.0-SNAPSHOT.jar
[地皮]PlotSquared-Bukkit-5.13.10-Premium.jar
[地图图片]ImageOnMap-4.0.jar
[地下城副本]OhTheDungeon.jar
[地狱门]Multiverse-NetherPortals-4.2.1.jar
[点券]PlayerPoints.jar
[电梯]Lift.jar
[动作]GSit.jar
[多背包]Multiverse-Inventories-4.2.1.jar
[多世界核心]Multiverse-Core-4.2.2.jar
[反世界下载MOD]OSZOAntiWDL.jar
[高级成就]AdvancedAchievements.jar
[高级封禁]AdvancedBan-Bundle-2.3.0-RELEASE.jar
[更多附魔]GoldenEnchants.jar
[更好的音效]PlayMoreSounds.jar
[公共坐标]PlayerWarps 6.4.0.jar
[管理界面]AdminGUI-1.4.8.jar
[光源前置]LightAPI-fork-3.4.6.jar
[红包]RedPacket-1.5.4.jar
[饥饿游戏]HungerGames-4.15.5.jar
[基础]EssentialsX-2.18.2.0.jar
[基础]EssentialsXSpawn-2.18.2.0.jar
[加入事件]JoinEventsPro.jar
[结婚]MarriageMaster.jar
[经济]GemsEconomy-4.9.1.jar
[经济前置]Vault-1.7.3.jar
[精英怪物]EliteMobs7241.jar
[砍树]UltimateTimber-2.2.2.jar
[空岛战争]SkyWarsReloaded 5.4.1.jar
[聊天]VentureChat.jar
[领地管理]Residence4.9.2.9.jar
[农场保护]FarmProtect-v1.9.0.jar
[皮肤管理]SkinsRestorer.jar
[签到]LiteSignIn.jar
[前置]EpicPluginLib.jar
[前置]NexEngine.jar
[前置]PlaceholderAPI-2.10.6.jar
[前置]ProtocolLib.jar
[权限]LuckPerms-Bukkit-5.2.76.jar
[全球市场]CrazyAuctionsPlus-1.1.4.3.jar
[全息]HolographicDisplays-2.4.6.jar
[全息掉落]HoloDrops.jar
[全息拓展]TouchscreenHolograms.jar
[任务系统]beautyquests-0.18.5.jar
[商店]QuantumShop.jar
[商店]QuickShop-4.0.7.5.jar
[实体牵引]SolidTraction.jar
[世界保护]worldguard-bukkit-7.0.4.jar
[世界编辑GUI]WorldEditSUI-1.7.1.jar
[世界范围]WorldBorder.jar
[死亡箱子]AngelChest.jar
[随机传送]RandomTeleport-7.9.2.jar
[特效装扮]ProCosmetics.jar
[限制刷怪]SpawnLimit.jar
[箱子锁]LockettePro-2.10.8.jar
[小地图]ServerMinimap.jar
[烟花伤害]FireTweaks.jar
[移除全息]HoloRemove.jar
[音乐]ZMusic-Plugin-2.0.5.jar
[优化]AntiSeedCracker-1.0.jar
[优化]EntityTrackerFixer.jar
[优化]IllegalStack-2.2.2a.jar
[优化]LaggRemover-2.0.6.jar
[游戏规则]GameruleManager.jar
[娱乐-汽车]Carz-7.2.jar
[娱乐前置]BentoBox-1.15.5.jar
[娱乐-血月]bloodmoon.jar
[在线奖励]TimeIsMoney.jar
[粘液科技]ExtraHeads - DEV 21 (git a2c68).jar
[粘液科技]WhatIsThis-3.3.jar
[粘液科技-已汉化]ExoticGarden-vDEV-68-.git.42d8abc6.jar
[粘液科技-已汉化]ExtraGear.jar
[粘液科技-已汉化]Slimefun-v4.9-stable-210130.jar
[展示物品]ShowItem.jar
[职业掉落]MoneyHunters.jar
[资源世界]ResourceWorld-1.9.4.jar
[自动清除]AdvancedCleaner-1.2.jar
[自动整理]ChestSort.jar
PluginConstructorAPI.jar
SkQuery.jar
Skript.jar

**Comment by e-im** [comment]
With so many other plugins in play that could be causing this, it's a bit hard to test and the issue most likely comes from one of them. Have you been able to reproduce this with only your plugin or are able to narrow it down at all since then?

**Comment by mfnalex** [comment]
Hi, neither I nor any other of my plugin's users could reproduce it with my plugin. @Evil0ctal did you try to disable all other plugins? Otherwise I think this can be closed.

**Comment by electronicboy** [comment]
Closing, there is very little we can do to diagnose issues when you have 100 odd plugins, this exception is occurring as the server is upset that there is a region file which is closed, this code is pretty tightly held together and it's practically unviable that a closed chunk cache ref could leak
