### ISSUE TITLE
Couldn't sign book

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#537]
```
[15:21:29] [Server thread/INFO]: [-] MarciMarcell
[15:21:30] [Server thread/ERROR]: Couldn't sign book
java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readShort(EmptyByteBuf.java:450) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.readShort(PacketDataSerializer.java:594) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.k(PacketDataSerializer.java:260) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2229) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-958]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-958]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[15:21:31] [Server thread/INFO]: 3cyber lost connection: Invalid book data!
[15:21:31] [Server thread/INFO]: [-] 3cyber
[15:21:31] [Server thread/WARN]: handleDisconnection() called twice
[15:21:31] [Server thread/ERROR]: Couldn't select trade
java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readInt(EmptyByteBuf.java:470) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.readInt(PacketDataSerializer.java:610) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2267) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-958]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-958]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[15:21:31] [Server thread/ERROR]: Couldn't select trade
java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readInt(EmptyByteBuf.java:470) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.readInt(PacketDataSerializer.java:610) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2267) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-958]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-958]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[15:21:31] [Server thread/ERROR]: Couldn't pick item
java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.readByte(PacketDataSerializer.java:586) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.g(PacketDataSerializer.java:147) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2510) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-958]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-958]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[15:21:31] [Server thread/ERROR]: Couldn't sign book
java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readShort(EmptyByteBuf.java:450) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.readShort(PacketDataSerializer.java:594) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.k(PacketDataSerializer.java:260) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2229) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-958]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-958]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[15:21:31] [Server thread/ERROR]: Couldn't select trade
java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readInt(EmptyByteBuf.java:470) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.readInt(PacketDataSerializer.java:610) ~[patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2267) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-958]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-958]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Paper build number:**
git-Paper-958

**Plugins:**
`Vehicles, MobEggSpawnerBlocker, PlugMan, BetterChairs, NametagEdit, MineMarket-Universal, EntityDetection, SkinsRestorer, Stats, AsyncWorldEditInjector, CoreProtect, Deadbolt, OpenInv, LimitCreative, CreativeNbtControl, ClearLag, AutoMessage, ChatControl, WorldBorder, ProtocolLib, weeTrade, AsyncWorldEdit, IPWhitelist, RedstoneClockDetector, PermissionsEx, Lottery, mcMMO, Vault, MyCommand, WorldEdit, Essentials, PlotMe, CompatNoCheatPlus, Auctions, NoCheatPlus, TreasureChest, EssentialsChat, PlotMe-DefaultGenerator, WorldGuard, myZone, EssentialsGeoIP, EssentialsSpawn, PvPManager, TitleManager, Multiverse-Core, Shopkeepers, CraftBook, ChestShop, MobArena, LimitedCreative, AreaShop, SurvivalGames, MyPet, XrayInformer`

**Comment by aikar** [comment]
This is simply someone using a hack client trying to spam your logs with invalid data. It's a feature of the Wurst client.

Maybe we can adjust the error messages to make that clearer.
