### ISSUE TITLE
[stacktrace][small bug] Dead entity teleporting through netherportal console error

### ISSUE THREAD

**Issue by stepech** [PaperMC/Paper#5380]
### Link/paste of stack trace
```
[22:40:06] [Server thread/WARN]: Illegal Entity Teleport EntityFireworks['Firework Rocket'/65898, uuid='😋', l='ServerLevel[world]', x=55.96, y=79.12, z=1536.01, cx=3, cz=96, tl=2, v=true, d=true] to ServerLevel[world_nether]:null
java.lang.Throwable: null
	at net.minecraft.server.v1_16_R3.Entity.teleportTo(Entity.java:2663) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.Entity.b(Entity.java:2655) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.Entity.doPortalTick(Entity.java:2279) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.Entity.postTick(Entity.java:505) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.World.a(World.java:946) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:644) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1476) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-556]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-556]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

### Plugin list:
[22:50:55 INFO]: Plugins (15): BlueMap, CoreProtect, DiscordSRV, dynmap*, Dynmap-Essentials*, dynmap-mobs*, eBackup, Essentials, EssentialsChat, LuckPerms, Maintenance, mcMMO, PlaceholderAPI, SkinsRestorer, Vault

### Actions to reproduce (if known):
Occured on the server when I wasn't online. Described by player as an issue occuring when firing fireworks through nether portal. (In game there is no visible error, just prints this stacktrace in console, it's just a small bug)

### Paper version:
[22:52:57 INFO]: This server is running Paper version git-Paper-556 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Thanks a lot to all people maintaining Paper. It's super project, love you all ❤

**Comment by e-im** [comment]
I wasn't able to reproduce this however it does sound plausible and I may have missed something, have you been able to? If you're able to reproduce reliably, would you mind trying without plugins?

Thanks

**Comment by Proximyst** [comment]
Known bug with all projectiles through portals. I'll dig up the reproduction steps later today (with an alarm, of course, because we all know how good my memory is).

**Comment by e-im** [comment]
Nevermind, did a bit more looking into this and was able to reproduce. It's just trying to teleport a dead entity.

**Comment by HexedHero** [comment]
Reproducible everytime with
```
    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void a(EntityPortalEnterEvent event) {
        if (event.getEntity() instanceof Item) { event.getEntity().remove(); }
    }
```
