### ISSUE TITLE
EntityInsentient.setGoalTarget - Unknown target reason (null) on locally built jars

### ISSUE THREAD

**Issue by Prof-Bloodstone** [PaperMC/Paper#5456]
### Expected behavior

No stacktrace is thrown.

### Observed/Actual behavior

Stacktrace is thrown:

```
[22:49:47 WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.server.v1_16_R3.EntityInsentient.setGoalTarget(EntityInsentient.java:259) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.EntityInsentient.setGoalTarget(EntityInsentient.java:249) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.PathfinderGoalNearestAttackableTarget.c(PathfinderGoalNearestAttackableTarget.java:63) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.PathfinderGoalWrapped.c(PathfinderGoalWrapped.java:40) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:141) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.EntityInsentient.inactiveTick(EntityInsentient.java:208) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.World.a(World.java:946) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:644) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1476) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Steps/models to reproduce

I have no steps - this happened during testing of final version of PR: https://github.com/PaperMC/Paper/pull/5454
You can check that my commit hash matches Paper version.

My workflow on fresh server was run it once with EssentialsX+Chat and once without. Randomly found it in logs.

### Plugin list

EssentialsX
EssentialsX Chat

### Paper version

This server is running Paper version git-Paper-"b87c0c0d7" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

I don't have enough information to be able to pinpoint it further. Seems to happen consistently on locally-built jars, while works fine on the downloaded one. I suspect there might be some environment influence unaccounted for in the paper scripts? Just a theory.

Creating issue to remember about it and maybe investigate it further one day.

**Comment by electronicboy** [comment]
I don't really see how that could happen?
PathfinderGoalNearestAttackableTarget.c(PathfinderGoalNearestAttackableTarget.java:63) ~[paper-1.16.5.jar:git-Paper-"b87c0c0d7"]
Seems to always define a reason? o.O

**Comment by Prof-Bloodstone** [comment]
I have no idea how it could happen, and I'm too tired to debug it today. Created issue just so it's out there.

I've built Paperclip based on currently latest master commit https://github.com/PaperMC/Paper/commit/a111b136556b543836e5942f2d79b6c1a8e7dde5: https://drive.google.com/file/d/11wkBkCyMU4irv_FqeLGZl8kmyEGsZHYl/view?usp=sharing

The new stacktrace is similar:

<details>
<summary>Stacktrace</summary>

```
[23:29:11 WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.server.v1_16_R3.EntityInsentient.setGoalTarget(EntityInsentient.java:259) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.EntityInsentient.setGoalTarget(EntityInsentient.java:249) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.PathfinderGoalNearestAttackableTarget.c(PathfinderGoalNearestAttackableTarget.java:63) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.PathfinderGoalWrapped.c(PathfinderGoalWrapped.java:40) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:141) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.EntityInsentient.inactiveTick(EntityInsentient.java:208) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.World.a(World.java:946) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:644) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1476) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-"a111b1365"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
</details>

**Comment by electronicboy** [comment]
that drace doesn't even make sense, somehow you're calling the wrong setGoalTarget method in that trace.. o.O
Like,
![image](https://user-images.githubusercontent.com/1228900/113522596-cd30e280-9599-11eb-82c1-9c1f6eaa6c87.png)

That 2nd method is what should be called, are you sure that all patches where applied? o.O

**Comment by Prof-Bloodstone** [comment]
In my source code `PathfinderGoalNearestAttackableTarget:63` :
```java
    @Override
    public void c() {
        this.e.setGoalTarget(this.c); // Line 63
        super.c();
    }
```
I wonder if this is another bug similar to https://github.com/PaperMC/Paper/pull/5387

Because my global `.gitignore` does ignore `target/` folder, and the path to this file contains it:
> src/main/java/net/minecraft/world/entity/ai/goal/**target**/PathfinderGoalNearestAttackableTarget.java

**Comment by Prof-Bloodstone** [comment]
Of course that was it. After removing my global `.gitignore` it patched it just fine.
Will see tomorrow about fixing it.

CC: @Proximyst cause you asked to be pinged last time :)
