### ISSUE TITLE
Restart doesn't  work

### ISSUE THREAD

**Issue by Jagerente** [PaperMC/Paper#5469]
### Expected behavior

Server shutdown and restarts.

### Observed/Actual behavior

Server shutdowns, trying to launch and then errors in console. 
```bash
------------------- SERVER RESTARTS -------------------
System Info: Java 11 (Java HotSpot(TM) 64-Bit Server VM 11.0.9+7-LTS) Host: Linux 5.10.25-v8+ (aarch64)
Loading libraries, please wait...
[15:53:36 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:53:36 FATAL]: Failed to start the minecraft server
net.minecraft.server.v1_16_R3.SessionLock$ExceptionWorldConflict: /home/pi/minecraft/GucciCraftServers/Vanilla Paper 1.16.5/./world/session.lock: already locked (possibly by other Minecraft instance?)
        at net.minecraft.server.v1_16_R3.SessionLock$ExceptionWorldConflict.a(SourceFile:98) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.SessionLock.a(SourceFile:44) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.Convertable$ConversionSession.<init>(Convertable.java:245) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.Convertable.c(Convertable.java:227) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.Main.main(Main.java:153) ~[patched_1.16.5.jar:git-Paper-584]
        at org.bukkit.craftbukkit.Main.main(Main.java:278) ~[patched_1.16.5.jar:git-Paper-584]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:58) ~[paper-1.16.5-584.jar:?]
----- Press enter to prevent the server from restarting in 5 seconds -----

```

### Steps/models to reproduce

/restart 

start.sh
```bash
#!/bin/bash

JAR=paper-1.16.5-584.jar
MAXRAM=4
MINRAM=1
TIME=5

while [ true ]; do
    /usr/java/jdk-11.0.9/bin/java -Xms${MINRAM}G -Xmx${MAXRAM}G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1$
    echo "----- Press enter to prevent the server from restarting in $TIME seconds -----";
    read -t $TIME input;
    if [ $? == 0 ]; then
        break;
    else
        echo "------------------- SERVER RESTARTS -------------------";
    fi
done
```

### Plugin list

none

### Paper version

584

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
You're running the server in a while true loop, meaning that /restart is irrelevant
IF you are using /restart to actually start up the script you're using to start the server, that's the entire issue here, you're causing the server to restart on another process, which when you're while true loop comes to it is already running in the background

Beyond that, past the process closing, it's down to the JRE to ensure that all stuff is closed, if not, either that is something wrong with your OS or there is something else going on there with it

**Comment by Jagerente** [comment]
So what should I do to keep the Mc running in console?

**Comment by Titaniumtown** [comment]
do `/stop` instead

**Comment by electronicboy** [comment]
point the restart script in spigot.yml to a file which doesn't exist, your while loop will take control of restarting as I've said

**Comment by Prof-Bloodstone** [comment]
@Jagerente If you want to have both `/stop` and `/restart` work as expected (first one stops the server, second causes it to restart), you can easily do this with 2 small scripts. For example:

`start.sh` - this is what you'd start from screen/tmux.
```sh
#!/usr/bin/env bash
set -euo pipefail

rm .restart_flag &>/dev/null || true # Remove restart flag if it exists, ignore errors

while :; do # while true
  java -jar paper.jar --nogui # run paper - should add flags here :)
  [ -e .restart_flag ] || break # If restart file is not present, stop the loop
  echo 'Restarting server in 10 seconds'
  sleep 10s || break # Give time for server to release everything, or to you to manually cancel the loop with ctrl+c
done
```

Then have a super simple `restart.sh` script, which will just create the file the start script looks for.
```sh
#!/usr/bin/env bash

touch .restart_flag
```

Make sure to point `spigot.yml` to use your `restart.sh` script!
Of course adapt it to your exact needs. Can for example replace `sleep 10s || break` with `read -t "${TIME}" _ && break` as in your script.
