### ISSUE TITLE
Plugins Will Not Load

### ISSUE THREAD

**Issue by LynxError** [PaperMC/Paper#5488]
### Expected behavior

Plugins Will Not Load went from went from 584 to git-Paper-590 
several plugins will not longer load I am gonna pick one of many and that is worldedit

### Observed/Actual behavior

install 590 and several plugins will not load worldedit-bukkit-7.2.2-dist.jar

no errors on 584

### Steps/models to reproduce

went back to 584 and no errors

org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org.apache.logging.log4j.util.ReflectionUtil
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:251) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3129/000000000000000000.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:836) [?:?]
Caused by: java.lang.NoClassDefFoundError: org.apache.logging.log4j.util.ReflectionUtil
	at com.sk89q.worldedit.log4jbridge.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42) ~[?:?]

### Plugin list

luckperm jetminons rewardpro worldedit ess. and many more

### Paper version

[21:17:48] [Server thread/INFO]: This server is running Paper version git-Paper-590 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by Camotoy** [comment]
It looks like you're not on the latest version of WorldEdit. Try updating: https://dev.bukkit.org/projects/worldedit/files/3237689

**Comment by electronicboy** [comment]
Update your plugins
