### ISSUE TITLE
Deserializing Skull Items Saved on Older Versions Throws Error

### ISSUE THREAD

**Issue by NathanWolf** [PaperMC/Paper#5499]
### Expected behavior

Items saved (serialized to Yaml) on older server versions should still load properly on currentversions.

[skull_zuko.yml.txt](https://github.com/PaperMC/Paper/files/6326112/skull_zuko.yml.txt)

### Observed/Actual behavior

For skulls without `internal` stored in their ItemMeta, in other words skulls that only reference a player id without having the texture URL stored, Paper will throw an error on load and fail to load the item.

This seems to be recent behavior, I do not see the issue on paper-574 (~ March 30) but do see it on paper-593 (~April 15). I also do not see the issue upstream.

I looked through the commit history and I see nothing related to skulls at all. There are a few tile entity changes but it doesn't seem like they would be the cause. Stack trace attached.

### Steps/models to reproduce

Save the attacked skull_zuko file and try to load it with a YamlConfiguration. You should see an error like in the attached stack trace. I can provide a test plugin if that's helpful, or my Magic plugin will load the file if you place it in `plugins/Magic/items`

https://jenkins.elmakers.com/job/MagicPlugin/3688/artifact/Magic/target/Magic-8.6-SNAPSHOT.jar

### Plugin list

ChatFormat*, Citizens, Fe*, LibsDisguises, LightAPI, LuckPerms, Magic, MagicArenas, MagicAttributes*, Mars, MobArena, PlaceholderAPI, PreciousStones, ProtocolLib, spark, Vault*

### Paper version

 This server is running Paper version git-Paper-593 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
missing trace?
I don't recall anything which has changed here which would be relevant o.O

**Comment by NathanWolf** [comment]
Agreed, I could be wrong but I did a bunch of a/b testing to try to narrow down where it changed. 

Sorry about the trace, I attached it so not sure what happened there, here it is inline:

```
[15:09:11 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[patched_1.16.5.jar:git-Paper-593]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.16.5.jar:git-Paper-593]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.16.5.jar:git-Paper-593]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.16.5.jar:git-Paper-593]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.16.5.jar:git-Paper-593]
	at net.minecraft.server.v1_16_R3.TileEntitySkull$3.call(TileEntitySkull.java:231) ~[patched_1.16.5.jar:git-Paper-593]
	at net.minecraft.server.v1_16_R3.TileEntitySkull$3.call(TileEntitySkull.java:228) ~[patched_1.16.5.jar:git-Paper-593]
	at net.minecraft.server.v1_16_R3.TileEntitySkull.b(TileEntitySkull.java:247) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:104) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:535) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemFactory.ensureServerConversions(CraftItemFactory.java:348) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.inventory.ItemStack.ensureServerConversions(ItemStack.java:619) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:542) ~[patched_1.16.5.jar:git-Paper-593]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Paper-593]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.5.jar:git-Paper-593]
	at com.elmakers.mine.bukkit.utility.CompatibilityUtils.loadConfiguration(CompatibilityUtils.java:727) ~[?:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.loadOverrides(ConfigurationLoadTask.java:361) ~[?:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.loadConfigFile(ConfigurationLoadTask.java:383) ~[?:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.run(ConfigurationLoadTask.java:786) ~[?:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.runNow(ConfigurationLoadTask.java:825) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2301) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2278) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2274) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2266) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.load(MagicController.java:2340) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.initialize(MagicController.java:1486) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.initialize(MagicPlugin.java:184) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:178) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-593]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-593]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-593]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-593]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-593]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_16_R3.TileEntitySkull$1.load(TileEntitySkull.java:90) ~[patched_1.16.5.jar:git-Paper-593]
	at net.minecraft.server.v1_16_R3.TileEntitySkull$1.load(TileEntitySkull.java:57) ~[patched_1.16.5.jar:git-Paper-593]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.16.5.jar:git-Paper-593]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.16.5.jar:git-Paper-593]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.16.5.jar:git-Paper-593]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.16.5.jar:git-Paper-593]
	... 66 more
```

**Comment by electronicboy** [comment]
That looks like you're enabling too early or something

**Comment by electronicboy** [comment]
Yea, you loaded on startup, service stuff for skulls is done between STARTUP and POST_WORLD

**Comment by electronicboy** [comment]
https://github.com/elBukkit/MagicPlugin/commit/5f317ae0de93c3b74286cc415cac17d375f960f4
That broke it, you're basically gonna have to delay loading your data stuff or something as the servers just not setup at this point

**Comment by NathanWolf** [comment]
Ok thanks- but still strange that it works fine on older Paper version and upstream spigot?

And yes that change has caused me all manner of problems. I recently added some world gen and changed to startup so I can modify spawn chunks in default worlds, it's been very challenging to find ways to have everything load and integrate with other plugins at the correct time.

**Comment by electronicboy** [comment]
Because spigot doesn't go out of it's way to ensure data consistency on items, shamefully, we do, so when you call into the server too early for it to be fully init'd you potentially hit "fun" stuff like this

**Comment by NathanWolf** [comment]
Ah ok that makes sense. Thank you!
I'll see if I can move item loading to after startup.
