### ISSUE TITLE
Failed to save chunk

### ISSUE THREAD

**Issue by Byl3x** [PaperMC/Paper#5513]
### Stack trace

```
[10:56:06 ERROR]: Failed to save chunk -8,-12
java.lang.NullPointerException: null
        at net.minecraft.server.v1_16_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:746) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:644) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:439) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.saveChunk(PlayerChunkMap.java:1510) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$save$28(PlayerChunkMap.java:953) ~[patched_1.16.5.jar:git-Paper-601]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.save(PlayerChunkMap.java:949) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.save(ChunkProviderServer.java:718) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.WorldServer.save(WorldServer.java:1119) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.MinecraftServer.saveChunks(MinecraftServer.java:835) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.CommandSaveAll.a(SourceFile:34) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.CommandSaveAll.b(SourceFile:20) ~[patched_1.16.5.jar:git-Paper-601]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[patched_1.16.5.jar:git-Paper-601]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:267) ~[patched_1.16.5.jar:git-Paper-601]
        at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[patched_1.16.5.jar:git-Paper-601]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-601]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-601]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:452) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-601]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-601]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Plugin list

none

### Actions to reproduce (if known)

bring a world from fabric(with lithium) to paper(i tried using tuinity because someone suggested it might fix the issue and then reverted to paper because it didn't fix it, the issue happened when transferring to paper and didn't chage when tuinity was involved)

### Paper version

[11:05:37 INFO]: This server is running Paper version git-Paper-601 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Tuinity-"7d36676" (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Byl3x** [comment]
Forgot to mention, the trace isn't just for this chunk, it's for multiple chunks and they are different each time the it tries to save

**Comment by Proximyst** [comment]
We need your world in order to do anything.

**Comment by Byl3x** [comment]
I'm really sorry, I just discovered that the hard drive it was saved on had died and the data got corrupted, it isn't a paper issue

**Comment by Proximyst** [comment]
That's alright! Good luck with the data :p
