### ISSUE TITLE
Unknown Console Error

### ISSUE THREAD

**Issue by skyman478** [PaperMC/Paper#5524]
### Expected behavior

I Expected to see no ocasional errors in console

### Observed/Actual behavior

It happens randomly on the console when someone do something, i don't exactly what, but triggers that.

[15:39:39 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor640.execute(Unknown Source)
[15:39:39 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[15:39:39 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[15:39:39 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:39:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[15:39:39 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1171)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.BlockCrops.tick(BlockCrops.java:90)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.BlockBase$BlockData.b(BlockBase.java:622)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.a(WorldServer.java:825)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:871)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:683)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:849)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:767)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1486)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[15:39:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[15:39:39 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor640.execute(Unknown Source)
[15:39:39 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[15:39:39 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[15:39:39 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:39:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[15:39:39 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1171)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.BlockCrops.tick(BlockCrops.java:90)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.BlockBase$BlockData.b(BlockBase.java:622)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.a(WorldServer.java:825)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:871)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:683)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:849)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:767)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1486)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126)
[15:39:39 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[15:39:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

### Steps/models to reproduce

I don't know exactly what is needed to reproduce this error, i just know it appears on console when someone do something, like a command, or fly, or eat.

### Plugin list

Plugin List:
![image](https://user-images.githubusercontent.com/59271049/115605259-b0deb680-a2b8-11eb-9a2e-0a1a5c9fbb24.png)

### Paper version

Paper Version:
Paper-603

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by aurorasmiles** [comment]
That doesn't look like a full error/warning. Please provide the full error/log, preferably using a paste service like paste.gg

**Comment by Chew** [comment]
Also, this is likely a plugin issue, please reproduce without them.

**Comment by electronicboy** [comment]
You're missing the full exception and this is likely, as already stated, a plugin issue
Please use the discord/forums/IRC for support
