### ISSUE TITLE
Serialization from AdventureComponent to Component

### ISSUE THREAD

**Issue by DeJayDev** [PaperMC/Paper#5580]
### Expected behavior

When setting this component, it's added to the specified displayposition

### Observed/Actual behavior

Instead, an error is thrown that an `AdventureComponent` cannot be serialized to a... Adventure Component

### Steps/models to reproduce

Create a plugin that does this, or something... similar to this impl:
```java
package dev.dejay.componentbug;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.plugin.java.JavaPlugin;

public final class ComponentBug extends JavaPlugin {

    @Override
    public void onEnable() {
        Component badName = Component.text("♥", NamedTextColor.RED);
        getServer().getScoreboardManager().getMainScoreboard().registerNewObjective(
            "showhealth", // This can be anything, but this is important to know.
            "health", // Vanilla criterion
            badName
        );
    }

}
```

Run: `/scoreboard objective setdisplay belowName showhealth`
Note Stacktrace... https://ghostbin.co/paste/hqdhfa

### Plugin list

ComponentBug (this one!)

### Paper version

 This server is running Paper version git-Paper-645 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

In further testing it actually doesn't matter what you put into the component or where the `setdisplay` target is.
I tested with a `Component.text("nodders", NamedTextColor.RED)` and got the same error.

A similar result (the same?) is also noted when using the deprecated `registerNewObjective(String name, String criteria, String displayName)`

**Comment by ArvedEh** [comment]
I am getting the same error in my plugin, but it's **scoreboard teams** for me:

When I add a player to my scoreboard team and he joins, he gets kicked for Internal Server Error and I receive a stacktrace without a mention of my code in it anywhere: 
```
[11:36:55 WARN]: Failed to handle packet for /127.0.0.1:51528
java.lang.IllegalArgumentException: Don't know how to serialize io.papermc.paper.adventure.AdventureComponent@49a8577 as a Component
        at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.serialize(IChatBaseComponent.java:327) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.serialize(IChatBaseComponent.java:281) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.serialize(IChatBaseComponent.java:302) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.serialize(IChatBaseComponent.java:109) ~[patched_1.16.5.jar:git-Paper-645]
        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[patched_1.16.5.jar:git-Paper-645]
        at com.google.gson.Gson.toJson(Gson.java:669) ~[patched_1.16.5.jar:git-Paper-645]
        at com.google.gson.Gson.toJsonTree(Gson.java:562) ~[patched_1.16.5.jar:git-Paper-645]
        at com.google.gson.Gson.toJsonTree(Gson.java:541) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.b(IChatBaseComponent.java:363) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.toJsonTree(IChatBaseComponent.java:361) ~[patched_1.16.5.jar:git-Paper-645]
        at io.papermc.paper.adventure.PaperAdventure.asAdventure(PaperAdventure.java:128) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:355) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:159) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1511) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-645]        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-645]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-645]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[11:36:55 INFO]: Username lost connection: Internal server error
```

The error goes away when I comment out this line:
```java
scoreboardTeam.prefix(Component.text(name).color(TextColor.color(0,255,0)).append(Component.text(" ")));
```

When I remove the plugin completely, the teams still stay and the players in them can join.
When someone creates a new "group" in my plugin (which creates a new team with the prefix), they don't get disconnected either, they just can't join again.
(and yes, creating a new group ingame as a player is running the same code as creating a group from the database on server startup)

Version:  This server is running Paper version git-Paper-645 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by ArvedEh** [comment]
Also see #5371

**Comment by DeJayDev** [comment]
Tested with @jpenilla's version locally with the same plugin I used to report this issue and scoreboard objectives load fine without triggering an error. LGTM?
