### ISSUE TITLE
Citizens

### ISSUE THREAD

**Issue by danil20028191** [PaperMC/Paper#5661]
### Expected behavior

On the latest PaperSpigot cant't open any GUI menu(the spam in console when interracting with NPC), and it works after downgrading. I contacted to Citizens dev, he says that the problem is in Paper.
net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Вещи Дьявола", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Ценности", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Кузнец", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Механизмы", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Декорации", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Полублоки", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Блоки (2)", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Блоки (1)", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Оружейник", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Красители", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Разное", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Стёкла", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Еда", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Зелья", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]: at net.kyori.adventure.text.TextComponentImpl.(TextComponentImpl.java:58)
[08:59:27 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.(EntityHumanNPC.java:92)
[08:59:27 WARN]: at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]: at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]: at net.citizensnpcs.EventListen$1.run(EventListen.java:156)

### Observed/Actual behavior

j

### Steps/models to reproduce

j

### Plugin list

j

### Paper version

h

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
#5659

Fill the template
