### ISSUE TITLE
zip file closed

### ISSUE THREAD

**Issue by seema84** [PaperMC/Paper#5679]
### Expected behavior

-

### Observed/Actual behavior

[21:50:49] [Server thread/INFO]: Flushing Chunk IO
[21:50:49] [Server thread/INFO]: Closing Thread Pool
[21:50:49] [Server thread/INFO]: Closing Server
[21:50:49] [Thread-57/WARN]: java.lang.IllegalStateException: zip file closed
[21:50:49] [Thread-57/WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:915)
[21:50:49] [Thread-57/WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:347)
[21:50:49] [Thread-57/WARN]: 	at java.base/java.util.zip.ZipFile$1.getEntry(ZipFile.java:1121)
[21:50:49] [Thread-57/WARN]: 	at java.base/java.util.jar.JarFile.getEntry0(JarFile.java:578)
[21:50:49] [Thread-57/WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:508)
[21:50:49] [Thread-57/WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:470)
[21:50:49] [Thread-57/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165)
[21:50:49] [Thread-57/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[21:50:49] [Thread-57/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[21:50:49] [Thread-57/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[21:50:49] [Thread-57/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[21:50:49] [Thread-57/WARN]: 	at org.avaje.datasource.pool.PooledConnectionQueue.createStatus(PooledConnectionQueue.java:118)
[21:50:49] [Thread-57/WARN]: 	at org.avaje.datasource.pool.PooledConnectionQueue.shutdown(PooledConnectionQueue.java:378)
[21:50:49] [Thread-57/WARN]: 	at org.avaje.datasource.pool.ConnectionPool.shutdown(ConnectionPool.java:750)
[21:50:49] [Thread-57/WARN]: 	at io.ebeaninternal.server.core.SimpleDataSourceProvider.shutdown(SimpleDataSourceProvider.java:34)
[21:50:49] [Thread-57/WARN]: 	at io.ebeaninternal.server.transaction.TransactionManager.shutdown(TransactionManager.java:150)
[21:50:49] [Thread-57/WARN]: 	at io.ebeaninternal.server.core.DefaultServer.shutdownInternal(DefaultServer.java:431)
[21:50:49] [Thread-57/WARN]: 	at io.ebeaninternal.server.core.DefaultServer.shutdownManaged(DefaultServer.java:399)
[21:50:49] [Thread-57/WARN]: 	at io.ebeaninternal.server.lib.ShutdownManager.shutdown(ShutdownManager.java:147)
[21:50:49] [Thread-57/WARN]: 	at io.ebeaninternal.server.lib.ShutdownHook.run(ShutdownHook.java:19)

### Steps/models to reproduce

stop the paper server

### Plugin list

-

### Paper version

This server is running Paper version git-Paper-703 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
Please fill out the template- some common causes for this are a plugin was disabled (either explicitly or failed on enable), /reload was used, a plugin didn't clean up after itself correctly, or a plugin was updated while the server was running. Please come by our discord for support at [discord.gg/papermc](https://discord.gg/papermc)

**Comment by seema84** [comment]
I have found out that it is the plugin https://github.com/andune/HomeSpawnPlus
but i didn't get this message some paper versions ago (the plugin didn't get an update either)
