### ISSUE TITLE
Exception on start

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5696]
### Stack trace

```
Exception in thread "main" java.lang.IllegalArgumentException
        at java.instrument/sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.appendToSystemClassLoaderSearch(InstrumentationImpl.java:223)
        at io.papermc.paperclip.Agent.addToClassPath(Agent.java:39)
        at io.papermc.paperclip.Paperclip.getMainMethod(Paperclip.java:225)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:51)
```

### Plugin list

No Plugin.

### Actions to reproduce (if known)

![image](https://user-images.githubusercontent.com/65204013/119064987-8ac34800-ba17-11eb-9dce-d0bbcc1e14cc.png)

### Paper version

1.16.5 last build(707)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
It is likely that you are running paperclip from within a directory with bad characters. Could you ensure there are no special characters anywhere in the name of the folder your server is running in?

**Comment by MiniDigger** [comment]
additionally, please provide your java version

**Comment by Machine-Maker** [comment]
Should this issue be moved to the paperclip repo?

**Comment by electronicboy** [comment]
Likely, https://github.com/PaperMC/Paperclip/issues/31
