### ISSUE TITLE
Random player disconnect with Internal Server Error

### ISSUE THREAD

**Issue by kirillsemyonkin** [PaperMC/Paper#570]
# Crash, Stacktrace

### Link/paste of stack trace

```06.01 20:57:04 [Server] WARN Failed to handle packet for /IP:PORT
06.01 20:57:04 [Server] INFO net.minecraft.server.v1_11_R1.ReportedException: Ticking player
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.EntityPlayer.playerTick(EntityPlayer.java:366) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.F_(PlayerConnection.java:139) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:916) [patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
06.01 20:57:04 [Server] INFO Caused by: java.util.ConcurrentModificationException
06.01 20:57:04 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_91]
06.01 20:57:04 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_91]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.NBTTagCompound.g(NBTTagCompound.java:358) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.NBTTagCompound.clone(NBTTagCompound.java:435) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.NBTTagCompound.g(NBTTagCompound.java:360) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.ItemStack.cloneItemStack(ItemStack.java:468) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayOutEntityEquipment.<init>(SourceFile:21) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1882) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.EntityHuman.A_(EntityHuman.java:143) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO at net.minecraft.server.v1_11_R1.EntityPlayer.playerTick(EntityPlayer.java:285) ~[patched_1.11.2.jar:git-Paper-1020]
06.01 20:57:04 [Server] INFO ... 8 more
06.01 20:57:04 [Disconnect] User PLAYERNAME has disconnected, reason: Internal server error
```

### Plugin list:
Almost all custom with the use of NMS (icJukeBox, Citizens, WorldEdit, HolographicDisplays, FishWrapper, FishNav, FishHub)
### Actions to reproduce (if known):
Random appearance
### Paper build number:
Paper-1020
### Additional info:
The bug does not appear in latest Spigot (non-paper) with all same setup

**Comment by zachbr** [comment]
How often has this occurred?

**Comment by kirillsemyonkin** [comment]
Twice this day

**Comment by prplz** [comment]
Something is comodifying item stacks

**Comment by kirillsemyonkin** [comment]
@prplz Thats obvious, since NBT and ConcurrentModificationException. I do use nbt in my plugins, alot, but the problem appears only on paperspigot.

**Comment by zachbr** [comment]
We would need a reproduction method, as NMS calls this all over and doesn't have this issue.
Whether that be identifying the plugin or lines of code that trigger this or otherwise.

**Comment by kirillsemyonkin** [comment]
@Zbob750 Ill try to get more info about it tomorrow, like trying to make it appear or getting into the paper and spigot codes.

**Comment by zachbr** [comment]
Inactivity, no reproduction method.
