### ISSUE TITLE
Excessive velocity Exception: Stack trace

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#574]
Paper dev 1026
Fish Slapper 1.8 
https://www.spigotmc.org/resources/fish-slapper.17741/

@Zbob750 Hitting someone with a fish or typing ```/slap``` causes this excessive velocity exception to occur. This does not occur with Spigot-7d78b81-d5e7885 (MC: 1.11.2).

If it is caused by some velocity limit set in Paper, would it be possible to allow for that setting to be toggle-able so it can be disabled?

Edit: Assuming it is coming from this patch. 
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0060-Add-velocity-warnings.patch 
A toggle would be nice since it just spams exceptions otherwise.

```
[22:57:55] [Server thread/WARN]: Excessive velocity set detected: tried to set velocity of entity #141 to (6.417647706292123,-1.0769397679351842,2.5795345809202015).
[22:57:55] [Server thread/WARN]: java.lang.Exception: Stack trace
[22:57:55] [Server thread/WARN]: 	at java.lang.Thread.dumpStack(Unknown Source)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.setVelocity(CraftEntity.java:235)
[22:57:55] [Server thread/WARN]: 	at me.funnycube.fishslapper.Main.onDamge(Main.java:44)
[22:57:55] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor82.execute(Unknown Source)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[22:57:55] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:91)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:576)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:481)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:608)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1329)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:871)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:527)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1030)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1199)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1607)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:57:55] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:57:55] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648)
[22:57:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:57:55] [Server thread/WARN]: Excessive velocity set detected: tried to set velocity of entity #141 to (6.417647706292123,10.0,2.5795345809202015).
[22:57:55] [Server thread/WARN]: java.lang.Exception: Stack trace
[22:57:55] [Server thread/WARN]: 	at java.lang.Thread.dumpStack(Unknown Source)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.setVelocity(CraftEntity.java:235)
[22:57:55] [Server thread/WARN]: 	at me.funnycube.fishslapper.Main.onDamge(Main.java:45)
[22:57:55] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor82.execute(Unknown Source)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[22:57:55] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:91)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:576)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:481)
[22:57:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:608)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1329)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:871)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:527)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1030)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1199)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1607)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:57:55] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:57:55] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749)
[22:57:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648)
[22:57:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by scrayos** [comment]
Instead it would be a good idea for the plugin author to clamp the final velocity so, that none of the axes are longer than 4. Anything above would be ineffective anyways since the minecraft-protocol multiplies it by 8'000 to make a "Short" out of the "float" value. That means 4 is the maximum velocity you can send for each axis.

**Comment by zachbr** [comment]
This is not the first time we've received feedback about how verbosely we handle this issue.
After getting this feedback tens of times over, and the fact that the server can typically handle these itself without any negative behaviors, I have altered our handling of them with 50f2e124a1a6b5af1be8f6e91e6597e9bb866802.

Please read the commit message for additional information.
