### ISSUE TITLE
Sqlite broken for Freebsd

### ISSUE THREAD

**Issue by aldermath** [PaperMC/Paper#5789]
### Expected behavior

Plugins such as coreprotect that use sqlite should run without errors on freebsd.

### Observed/Actual behavior

Crash or plugin disable on startup with many errors related to sqlite:

Partial server log:

[19:17:30] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v19.5
--
[19:17:30] [Server thread/WARN]: java.sql.SQLException: no such column: 'type'
[19:17:30] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[19:17:30] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[19:17:30] [Server thread/WARN]: at net.coreprotect.Functions.createDatabaseTables(Functions.java:536)
[19:17:30] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:206)
[19:17:30] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:366)
[19:17:30] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:17:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[19:17:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[19:17:30] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[19:17:30] [Server thread/WARN]: java.sql.SQLException: no such column: 'id'
[19:17:30] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[19:17:30] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:400)
[19:17:30] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadWorlds(ConfigHandler.java:293)
[19:17:30] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:372)
[19:17:30] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:17:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[19:17:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[19:17:30] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[19:17:30] [Server thread/WARN]: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
[19:17:30] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(Unknown Source)
[19:17:30] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.flush(Unknown Source)
[19:17:30] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.decode(Unknown Source)
[19:17:30] [Server thread/WARN]: at java.base/java.nio.charset.Charset.decode(Unknown Source)
[19:17:30] [Server thread/WARN]: at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
[19:17:30] [Server thread/WARN]: at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
[19:17:30] [Server thread/WARN]: at org.sqlite.core.DB.column_names(DB.java:733)
[19:17:30] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
[19:17:30] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
[19:17:30] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:55)
[19:17:30] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:235)
[19:17:30] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[19:17:30] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:17:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[19:17:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[19:17:30] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[19:17:30] [Server thread/WARN]: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
[19:17:30] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(Unknown Source)
[19:17:30] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.flush(Unknown Source)
[19:17:30] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.decode(Unknown Source)
[19:17:30] [Server thread/WARN]: at java.base/java.nio.charset.Charset.decode(Unknown Source)
[19:17:30] [Server thread/WARN]: at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
[19:17:30] [Server thread/WARN]: at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
[19:17:30] [Server thread/WARN]: at org.sqlite.core.DB.column_names(DB.java:733)
[19:17:30] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
[19:17:30] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
[19:17:30] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:55)
[19:17:30] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:236)
[19:17:30] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[19:17:30] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:17:30] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:17:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[19:17:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[19:17:30] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[19:17:30] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[19:17:33] [Server thread/ERROR]: Error occurred while enabling CoreProtect v19.5 (Is it up to date?)
java.lang.OutOfMemoryError: Java heap space
at java.nio.HeapCharBuffer.&lt;init&gt;(Unknown Source) ~[?:?]
at java.nio.CharBuffer.allocate(Unknown Source) ~[?:?]
at java.nio.charset.CharsetDecoder.decode(Unknown Source) ~[?:?]
at java.nio.charset.Charset.decode(Unknown Source) ~[?:?]
at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507) ~[patched_1.16.5.jar:git-Paper-775]
at org.sqlite.core.NativeDB.errmsg(NativeDB.java:144) ~[patched_1.16.5.jar:git-Paper-775]
at org.sqlite.core.DB.newSQLException(DB.java:1024) ~[patched_1.16.5.jar:git-Paper-775]
at org.sqlite.core.DB.throwex(DB.java:989) ~[patched_1.16.5.jar:git-Paper-775]
at org.sqlite.core.NativeDB._exec_utf8(Native Method) ~[patched_1.16.5.jar:git-Paper-775]
at org.sqlite.core.NativeDB._exec(NativeDB.java:94) ~[patched_1.16.5.jar:git-Paper-775]
at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102) ~[patched_1.16.5.jar:git-Paper-775]
at net.coreprotect.patch.Patch.versionCheck(Patch.java:304) ~[?:?]
at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388) ~[?:?]
at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-775]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-775]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-775]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-775]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-775]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-775]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-775]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-775]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-775]
at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3151/0x0000001040b1b040.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
[19:17:33] [Server thread/INFO]: [CoreProtect] Disabling CoreProtect v19.5
[19:17:33] [Server thread/INFO]: [CoreProtect] Finishing up data logging. Please wait...
[19:17:33] [Server thread/INFO]: [CoreProtect] Success! Disabled CoreProtect v19.5

### Steps/models to reproduce

Run paper version 1.16.3-363 or higher with a plugin such as coreprotect that uses sqlite on freebsd 12.2. This happens on java 11 and java 16.

### Plugin list

coreprotect 19.5

### Paper version

This server is running Paper version git-Paper-775 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
--
You are running the latest version
Previous version: git-Paper-768 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This issue only occurs on paper version 1.16.4-363 and higher. I looked up the changelog and it says that it adds support for M1 Mac support for Sqlite. This change clearly broke support for Freebsd:
https://github.com/PaperMC/Paper/commit/7dea3dba6f1e486ee07b95921e004dc4e0f390c7

The only thing on the internet that mentions this issue is this:
https://www.truenas.com/community/threads/minecraft-plugin-issues-in-mineos.92689/

The paper commit above is still the most likely culprit.

**Comment by kashike** [comment]
> java.lang.OutOfMemoryError: Java heap space

You are out of memory.

**Comment by aldermath** [comment]
Pasted the wrong log. Memory is not the issue:



[18:24:14] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v19.5
--
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'type'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.Functions.createDatabaseTables(Functions.java:536)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:206)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:366)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'id'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:400)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadWorlds(ConfigHandler.java:293)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:372)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.flush(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.decode(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.Charset.decode(Unknown Source)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.DB.column_names(DB.java:733)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadTypes(ConfigHandler.java:246)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:373)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'version'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:57)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:235)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'version'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:57)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:236)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
