### ISSUE TITLE
Sqlite errors on Freebsd

### ISSUE THREAD

**Issue by aldermath** [PaperMC/Paper#5790]
### Expected behavior

See https://github.com/PaperMC/Paper/issues/5789

### Observed/Actual behavior

Pasted the wrong log in my previous issue and it was closed for containing an out of memory error. The true issue lies with sqlite:

[18:24:14] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v19.5
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'type'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.Functions.createDatabaseTables(Functions.java:536)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:206)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:366)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'id'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:400)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadWorlds(ConfigHandler.java:293)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:372)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.flush(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.decode(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.Charset.decode(Unknown Source)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.DB.column_names(DB.java:733)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadTypes(ConfigHandler.java:246)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:373)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'version'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:57)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:235)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'version'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:57)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:236)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)

### Steps/models to reproduce

Run paper version 1.16.3-363 or higher with a plugin such as coreprotect that uses sqlite on freebsd 12.2. This happens on java 11 and java 16.

### Plugin list

coreprotect 19.5

### Paper version

This server is running Paper version git-Paper-775 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-768 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I've tried updating sqlite on freebsd to no avail.
See https://github.com/PaperMC/Paper/issues/5789 for previous findings

**Comment by darbyjack** [comment]
This is not related to Paper. 
`at net.coreprotect.config.ConfigHandler.loadWorlds(ConfigHandler.java:293)`

**Comment by Proximyst** [comment]
Issue with plugin; the driver works fine.

**Comment by BLuFeNiX** [comment]
Just wanted to mention that I'm seeing similar behavior with my own plugin, and I think it may be a bug somewhere in the FreeBSD JVM implementation (or some library). Hopefully this helps someone:

https://github.com/BLuFeNiX/TeleportationRunes/issues/7#issuecomment-874494382
