### ISSUE TITLE
To test: Ensure expired temp bans work correctly. cc @mrfloris

### ISSUE THREAD

**Issue by mrfloris** [PaperMC/Paper#5805]
To test: Ensure expired temp bans work correctly. cc @mrfloris

_Originally posted by @Proximyst in https://github.com/PaperMC/Paper/issues/5785#issuecomment-859800244_

_I thought I would add some additional information:_

Set a temp ban of 30 seconds as op through a plugin. A handful of minutes later I let the client re-join which didn't work (various refreshes were needed) until a successful login.

One login attempt resulted in this:
```
[20:41:21] [User Authenticator #16/INFO]: UUID of player Paprikaatje is e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[20:41:21] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:65027
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.players.GameProfileBanEntry.hasExpired()" because the return value of "net.minecraft.server.players.GameProfileBanList.get(Object)" is null
	at net.minecraft.server.players.PlayerList.attemptLogin(PlayerList.java:577) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at net.minecraft.server.network.LoginListener.c(LoginListener.java:156) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1318) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1199) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1026) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[20:41:21] [Server thread/INFO]: com.mojang.authlib.GameProfile@17a392b8[id=e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c,name=Paprikaatje,properties={textures=[com.mojang.authlib.properties.Property@49a19c68]},legacy=false] (/127.0.0.1:65027) lost connection: Internal server error
```

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/121780001-3fbfcf00-cb96-11eb-836b-e3078050803d.png)

isBanned runs a contains, however, the get method removes expired entries, which means that in the event a ban is actually expired, it will return null; That just needs to be 

```java
if (this.getBans().isBanned(gameprofile) && !this.getBans().get(gameprofile) != null)
```

**Comment by electronicboy** [comment]
https://bugs.mojang.com/browse/MC-158900

We already have a patch for this in the tree, closing
