### ISSUE TITLE
Server thread/WARN issue caused on server stop

### ISSUE THREAD

**Issue by PlayingWithPi** [PaperMC/Paper#5812]
### Stack trace

```
[12:07:34] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:07:35] [main/INFO]: Reloading ResourceManager: Default, bukkit
[12:07:35] [Worker-Main-8/INFO]: Loaded 7 recipes
[12:07:36] [Server thread/INFO]: Starting minecraft server version 1.16.5
[12:07:36] [Server thread/INFO]: Loading properties
[12:07:36] [Server thread/INFO]: This server is running Paper version git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[12:07:36] [Server thread/INFO]: Debug logging is disabled
[12:07:36] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:07:36] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:07:36] [Server thread/INFO]: Default game type: SURVIVAL
[12:07:36] [Server thread/INFO]: Generating keypair
[12:07:36] [Server thread/INFO]: Starting Minecraft server on [IP ADDRESS REMOVED]
[12:07:36] [Server thread/INFO]: Using epoll channel type
[12:07:36] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:07:37] [Server thread/INFO]: Preparing level "world"
[12:07:37] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:07:37] [Server thread/INFO]: Preparing spawn area: 0%
[12:07:37] [Server thread/INFO]: Preparing spawn area: 0%
[12:07:38] [Server thread/INFO]: Preparing spawn area: 100%
[12:07:38] [Server thread/INFO]: Time elapsed: 1051 ms
[12:07:38] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[12:07:38] [Server thread/INFO]: Preparing spawn area: 0%
[12:07:38] [Server thread/INFO]: Time elapsed: 31 ms
[12:07:38] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[12:07:38] [Server thread/INFO]: Preparing spawn area: 0%
[12:07:38] [Server thread/INFO]: Time elapsed: 43 ms
[12:07:38] [Server thread/INFO]: Starting GS4 status listener
[12:07:38] [Server thread/INFO]: Thread Query Listener started
[12:07:38] [Query Listener #1/INFO]: Query running on [IP ADDRESS REMOVED]
[12:07:38] [Server thread/INFO]: Running delayed init tasks
[12:07:38] [Server thread/INFO]: Done (2.039s)! For help, type "help"
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * to at least Java 16. When Paper for Minecraft 1.17 is
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 16 will
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * be dropped.
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 11.0.11
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information: 
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] *   https://papermc.io/java16
[12:07:38] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[12:07:38] [Server thread/INFO]: Timings Reset
[12:09:19] [Server thread/INFO]: Saving the game (this may take a moment!)
[12:09:19] [Server thread/INFO]: Saved the game
[12:09:19] [Server thread/INFO]: Stopping the server
[12:09:19] [Server thread/WARN]: java.lang.Throwable: Server stopped
[12:09:19] [Server thread/WARN]: 	at io.papermc.paper.util.TraceUtil.dumpTraceForThread(TraceUtil.java:16)
[12:09:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.safeShutdown(MinecraftServer.java:996)
[12:09:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.safeShutdown(MinecraftServer.java:990)
[12:09:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.CommandStop.a(SourceFile:17)
[12:09:19] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[12:09:19] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
[12:09:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:268)
[12:09:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[12:09:19] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:09:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[12:09:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788)
[12:09:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470)
[12:09:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437)
[12:09:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
[12:09:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[12:09:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[12:09:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[12:09:19] [Server thread/INFO]: Stopping server
[12:09:19] [Server thread/INFO]: Saving players
[12:09:20] [Server thread/INFO]: Saving worlds
[12:09:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[12:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:09:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[12:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:09:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[12:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:09:20] [Server thread/INFO]: Flushing Chunk IO
[12:09:20] [Server thread/INFO]: Closing Thread Pool
[12:09:20] [Server thread/INFO]: Closing Server
[12:09:20] [Thread-1/WARN]: java.lang.Throwable: Server stopped
[12:09:20] [Thread-1/WARN]: 	at io.papermc.paper.util.TraceUtil.dumpTraceForThread(TraceUtil.java:16)
[12:09:20] [Thread-1/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.safeShutdown(MinecraftServer.java:996)

```

### Plugin list

Was asked to remove all plugins from server so it was only PaperMC running.

### Actions to reproduce (if known)

Basic, Empty server, using ApexMC client, clicked the stop button after server was fully up and running

### Paper version

This server is running Paper version git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
disable debug in server.properties, that's just a trace for debugging stuff

**Comment by Amelia-exe** [comment]
Awesome I'll do that.
I'll let you know if that fixes it
