### ISSUE TITLE
1.17: Paper dumpitem stacktrace

### ISSUE THREAD

**Issue by josephjthomas** [PaperMC/Paper#5858]
### Expected behavior

No stacktrace but the same response when using `paper fixlight` on console. -> "Only players can use this command".

### Observed/Actual behavior

```
> paper dumpitem
[02:24:04 WARN]: Unexpected exception while parsing console command "paper dumpitem"
org.bukkit.command.CommandException: Unhandled exception executing 'paper dumpitem' in com.destroystokyo.paper.PaperCommand(paper)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[paperclip.jar:git-Paper-"c943a10"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:825) ~[paperclip.jar:git-Paper-"c943a10"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:788) ~[paperclip.jar:git-Paper-"c943a10"]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:515) ~[paperclip.jar:git-Paper-"c943a10"]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:477) ~[paperclip.jar:git-Paper-"c943a10"]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404) ~[paperclip.jar:git-Paper-"c943a10"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180) ~[paperclip.jar:git-Paper-"c943a10"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paperclip.jar:git-Paper-"c943a10"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer are in unnamed module of loader 'app')
        at com.destroystokyo.paper.PaperCommand.doDumpItem(PaperCommand.java:483) ~[paperclip.jar:git-Paper-"c943a10"]
        at com.destroystokyo.paper.PaperCommand.execute(PaperCommand.java:172) ~[paperclip.jar:git-Paper-"c943a10"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paperclip.jar:git-Paper-"c943a10"]
        ... 8 more
```

### Steps/models to reproduce

1. Build Paper
2. run `paper dumpitem` in console
3. Observer stacktrace

### Plugin list

None

### Paper version

This server is running Paper version git-Paper-"c943a10" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by MiniDigger** [comment]
thanks!
