### ISSUE TITLE
[1.17] No key dirt provider

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5873]
### Expected behavior

Should work as normal.

### Observed/Actual behavior

Error appears in console 
```
18:28:12 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{offset:0,radius:2,type:"minecraft:acacia_foliage_placer"},heightma
p:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:acacia_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraf
t:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:
{base_height:5,height_rand_a:2,height_rand_b:2,type:"minecraft:forking_trunk_placer"},trunk_provider:{state:{Name:"minecraft:acacia_log",Properties
:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{offset:0,radius:2,type:"m
inecraft:acacia_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:acacia_leaves",Properties:{distanc
e:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_
feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:2,type:"minecraft:forking_trunk_placer"},trunk_provider:{stat
e:{Name:"minecraft:acacia_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key foliage_provider in MapLike[{decorators:[],
foliage_placer:{offset:0,radius:2,type:"minecraft:acacia_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"min
ecraft:acacia_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1
,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:2,type:"minecraft:fo
rking_trunk_placer"},trunk_provider:{state:{Name:"minecraft:acacia_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[18:28:12 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.lambda$new$0(WorldGenFeaturePillagerOutpostPoolPiec
e.java:54) ~[patched_1.17.jar:git-Paper-"ad7644c"]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(WorldGenFeaturePillagerOutpostPoolPiece.java
:54) ~[patched_1.17.jar:git-Paper-"ad7644c"]
        at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(StructureGenerator.java:129) ~[patched_1.17.jar:git-Paper-"ad7644c"]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:698) ~[patched_1.17.jar:git-Paper-"ad7644c"]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:272) ~[patched_1.17.jar:git-Paper-"ad7644c"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-"ad7644c"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-"ad7644c"]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-"ad7644c"]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-"ad7644c"]```

### Steps/models to reproduce

Seems to happen when loading 1.17 chunks in.

### Plugin list

Just paper.

### Paper version

```
This server is running Paper version git-Paper-"ad7644c" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

_No response_

**Comment by ghost** [comment]
Sorry this is my first time making an issue with paper, why was it closed?

**Comment by TwoLeggedCat** [comment]
Vanilla bug: https://bugs.mojang.com/browse/MC-227945

**Comment by electronicboy** [comment]
vanilla issue documented already in our release thread on discord, no need for yet another report of it

**Comment by ghost** [comment]
Ahh sorry, thanks for letting me though:)
