### ISSUE TITLE
[1.17] IRegistryCustom method name differs from the one in Spigot

### ISSUE THREAD

**Issue by eccentricdevotion** [PaperMC/Paper#5879]
### Stack trace

```
[01:18:12] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to TARDIS v4.7.1-b20.06.21-00:40
java.lang.NoSuchMethodError: 'net.minecraft.core.IRegistry net.minecraft.core.IRegistryCustom.d(net.minecraft.resources.ResourceKey)'
	at me.eccentric_nz.tardischunkgenerator.TARDISHelper.getBiomeKey(TARDISHelper.java:436) ~[?:?]
	at me.eccentric_nz.TARDIS.utility.TARDISStaticUtils.getBiomeAt(TARDISStaticUtils.java:365) ~[?:?]
	at me.eccentric_nz.TARDIS.listeners.TARDISSpawnListener.isTARDISBiome(TARDISSpawnListener.java:141) ~[?:?]
	at me.eccentric_nz.TARDIS.listeners.TARDISSpawnListener.onEntitySpawn(TARDISSpawnListener.java:117) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor137.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:709) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:629) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.level.WorldServer.addEntity0(WorldServer.java:1216) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1128) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.world.level.WorldAccess.lambda$addAllEntities$0(WorldAccess.java:16) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.WorldAccess.addAllEntities(WorldAccess.java:16) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.world.level.SpawnerCreature.spawnCategoryForPosition(SpawnerCreature.java:299) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.world.level.SpawnerCreature.spawnCategoryForChunk(SpawnerCreature.java:216) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:196) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.level.ChunkProviderServer.lambda$tickChunks$16(ChunkProviderServer.java:852) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.level.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:690) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.level.ChunkProviderServer.tickChunks(ChunkProviderServer.java:836) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.level.ChunkProviderServer.tick(ChunkProviderServer.java:753) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:581) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1551) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:476) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"ac95f25"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Plugin list

TARDIS v4.7.1
TARDISChunkGenerator v4.7.1
GameModeInventories v3.4.0

### Actions to reproduce (if known)

Install Paper 1.17
Start server
Watch errors fill log as mobs spawn

### Paper version

This server is running Paper version git-Paper-"ac95f25" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Looks like the method:

```
public <E> IRegistry<E> registryOrThrow(ResourceKey<? extends IRegistry<? extends E>> key) {
    return (IRegistry<E>)c(key).orElseThrow(() -> new IllegalStateException("Missing registry: " + resourceKey));
}
```

found in `net.minecraft.core.IRegistryCustom.java` has not been reobfuscated?

In the Spigot server jar `registryOrThrow` -> `d`

**Comment by electronicboy** [comment]
Tracked by https://github.com/PaperMC/paperweight/issues/24

**Comment by eccentricdevotion** [comment]
Thanks for the info.
I will check paperweight in future if submitting another issue.
