### ISSUE TITLE
[1.17] java.lang.NullPointerException: null at net.minecraft.world.level.lighting.LightEngineStorage.i(LightEngineStorage.java:83) ~[patched_1.17.jar:git-Paper-"3d43c5e"]

### ISSUE THREAD

**Issue by memikri** [PaperMC/Paper#5885]
### Stack trace

```
java.lang.NullPointerException: null
at net.minecraft.world.level.lighting.LightEngineStorage.i(LightEngineStorage.java:83) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.world.level.lighting.LightEngineLayer.c(LightEngineLayer.java:143) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.world.level.lighting.LightEngineGraph.a(LightEngineGraph.java:137) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.world.level.lighting.LightEngineBlock.a(LightEngineBlock.java:123) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.world.level.lighting.LightEngine.a(LightEngine.java:45) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.server.level.LightEngineThreaded.lambda$lightChunk$17(LightEngineThreaded.java:136) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.server.level.LightEngineThreaded$$Lambda$5266/0x000000005cc5f118.accept(Unknown Source) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
at net.minecraft.server.level.LightEngineThreaded.lambda$lightChunk$18(LightEngineThreaded.java:136) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.server.level.LightEngineThreaded$$Lambda$4327/0x000000005c79fa00.run(Unknown Source) ~[?:?]
at net.minecraft.server.level.LightEngineThreaded.e(LightEngineThreaded.java:171) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.server.level.LightEngineThreaded.lambda$addTask$13(LightEngineThreaded.java:108) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.server.level.LightEngineThreaded$$Lambda$4267/0x0000000040013218.run(Unknown Source) ~[?:?]
at net.minecraft.server.level.ChunkTaskQueueSorter.lambda$message$1(ChunkTaskQueueSorter.java:58) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.server.level.ChunkTaskQueueSorter$$Lambda$4286/0x00000000400162e8.run(Unknown Source) ~[?:?]
at net.minecraft.util.thread.ThreadedMailbox.f(ThreadedMailbox.java:87) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:129) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96) ~[patched_1.17.jar:git-Paper-"3d43c5e"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) [?:?] 
```

### Plugin list

No plugins.

### Actions to reproduce (if known)

Load a 1.16.5 world converted to 1.17 using `--forceUpgrade` and travel to un-generated chunks.

### Paper version

```
This server is running Paper version git-Paper-"3d43c5e" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I am using the official CavesAndCliffsPreview datapack from Mojang. https://launcher.mojang.com/v1/objects/622bf0fd298e1e164ecd05d866045ed5941283cf/CavesAndCliffsPreview.zip

**Comment by shinotheshino** [comment]
Server log: https://paste.gg/p/anonymous/82ec48feb49f43adb21db1d704eeb210

**Comment by MiniDigger** [comment]
what kinda java version do you run, its strange to not see the helpful nullpointer exceptions

**Comment by memikri** [comment]
```
System Info: Java 16 (Eclipse OpenJ9 VM openj9-0.26.0) Host: Linux 5.4.0-71-generic (amd64)
```

**Comment by memikri** [comment]
More specifically, running inside the `adoptopenjdk/openjdk16-openj9:alpine-jre` Docker image

**Comment by MiniDigger** [comment]
mfw openj9 didnt port that feature, because of course they didn't.
anyways, thank you,, we will look into that.

**Comment by tildearrow** [comment]
#5863 seemingly fixes the issue. The patch contains a fix to this problem.

**Comment by compieter-gh** [comment]
Also have the issue
```
[16:17:16 ERROR]: Caught exception in thread Thread[Worker-Main-6,4,main]
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.NibbleArray.a(int, int, int)" because "dataLayer" is null
        at net.minecraft.world.level.lighting.LayerLightSectionStorage.getStoredLevel(LayerLightSectionStorage.java:83) ~[?:?]
        at net.minecraft.world.level.lighting.LayerLightEngine.getLevel(LayerLightEngine.java:143) ~[?:?]
        at net.minecraft.world.level.lighting.DynamicGraphMinFixedPoint.checkEdge(DynamicGraphMinFixedPoint.java:137) ~[?:?]
        at net.minecraft.world.level.lighting.BlockLightEngine.onBlockEmissionIncrease(BlockLightEngine.java:123) ~[?:?]
        at net.minecraft.world.level.lighting.LevelLightEngine.onBlockEmissionIncrease(LevelLightEngine.java:45) ~[?:?]
        at net.minecraft.server.level.ThreadedLevelLightEngine.lambda$lightChunk$17(ThreadedLevelLightEngine.java:136) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.server.level.ThreadedLevelLightEngine.lambda$lightChunk$18(ThreadedLevelLightEngine.java:136) ~[?:?]
        at net.minecraft.server.level.ThreadedLevelLightEngine.runUpdate(ThreadedLevelLightEngine.java:171) ~[?:?]
        at net.minecraft.server.level.ThreadedLevelLightEngine.lambda$addTask$13(ThreadedLevelLightEngine.java:108) ~[?:?]
        at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:129) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Machine-Maker** [comment]
This smells like smth done accidentally when porting patches. Since that’s a de-obfuscated stack trace, should be able to track down the issue no problem.

**Comment by electronicboy** [comment]
Not entirely sure that that is the case, random exceptions from here afaik are rare but did happen, the optimisation patch iirc just added a little failsafe for that

**Comment by compieter-gh** [comment]
I should note my world is new (1.17) and has some datapacks & plugins in it and was pregenerating the nether while this happened.

Datapacks & plugins:
[file/A3-phantasmal-forest-addon-for-william-wythers-overhauled-overw.zip (world)], [file/A4-primordial-shores-add-on-for-william-wythers-overhauled-over.zip (world)], [file/B1-more-structures-addon-for-william-wythers-overhauled-overwor.zip (world)], [file/B2-more-srtuctures-add-on-by-kubek-villages-e1660.zip (world)], [file/B3-more-structures-add-on-by-kubek-bibanul-femeilor-outposts.zip (world)], [file/B4-more-structures-add-on-by-16bitmap.zip (world)], [file/B5-more-structures-addon-flower-forest-village-v-0-3.zip (world)], [file/B6-more-structures-add-on-by-ender-host-robert0213.zip (world)], [file/bukkit (world)], [file/A0-william-wythers-overhauled-overworld-for-1-17-e1760.zip (world)], [file/A1-william-wythers-caves-and-cliffs-add-on-for-overhauled-overw-e1760.zip (world)]

Plugins (23): Chunky, ChunkyBorder, Citizens, CMI, CMILib, CompatNoCheatPlus*, DiscordSRV, FeatherBoard, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI*, NoCheatPlus, PlaceholderAPI, ProtocolLib, ServerUtils, SilkSpawners, Skript, skript-placeholders*, Vault, ViaVersion, VotingPlugin, WorldEdit, WorldGuard

[16:50:37 INFO]: This server is running Paper version git-Paper-49 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 1c77d64)

**Comment by Plasman888** [comment]
> I should note my world is new (1.17) and has some datapacks & plugins in it and was pregenerating the nether while this happened.
> 
> Datapacks & plugins:
> [file/A3-phantasmal-forest-addon-for-william-wythers-overhauled-overw.zip (world)], [file/A4-primordial-shores-add-on-for-william-wythers-overhauled-over.zip (world)], [file/B1-more-structures-addon-for-william-wythers-overhauled-overwor.zip (world)], [file/B2-more-srtuctures-add-on-by-kubek-villages-e1660.zip (world)], [file/B3-more-structures-add-on-by-kubek-bibanul-femeilor-outposts.zip (world)], [file/B4-more-structures-add-on-by-16bitmap.zip (world)], [file/B5-more-structures-addon-flower-forest-village-v-0-3.zip (world)], [file/B6-more-structures-add-on-by-ender-host-robert0213.zip (world)], [file/bukkit (world)], [file/A0-william-wythers-overhauled-overworld-for-1-17-e1760.zip (world)], [file/A1-william-wythers-caves-and-cliffs-add-on-for-overhauled-overw-e1760.zip (world)]
> 
> Plugins (23): Chunky, ChunkyBorder, Citizens, CMI, CMILib, CompatNoCheatPlus*, DiscordSRV, FeatherBoard, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI*, NoCheatPlus, PlaceholderAPI, ProtocolLib, ServerUtils, SilkSpawners, Skript, skript-placeholders*, Vault, ViaVersion, VotingPlugin, WorldEdit, WorldGuard
> 
> [16:50:37 INFO]: This server is running Paper version git-Paper-49 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: [1c77d64](https://github.com/PaperMC/Paper/commit/1c77d647136053dd15098ee6d971b4c428f42bfa))

same but i used MCAselector to delete some chunks

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/commit/a831634d446341efc70f027851effe02a0e7f1d3
