### ISSUE TITLE
[1.17] Error when starting server from 1.16.5 to 1.17

### ISSUE THREAD

**Issue by LowScarlet** [PaperMC/Paper#5887]
### Expected behavior

Shouldn't that be?

### Observed/Actual behavior

Just an error on console

### Steps/models to reproduce

1. Update paper 1.16.5 to 1.17
2. start server
3. look at your console, you can see like this 
```hs
[21:37:00 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key foliage_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[21:37:00 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.lambda$new$0(WorldGenFeaturePillagerOutpostPoolPiece.java:54) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(WorldGenFeaturePillagerOutpostPoolPiece.java:54) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(StructureGenerator.java:129) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:717) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:272) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
[21:37:00 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key foliage_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[21:37:00 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.lambda$new$0(WorldGenFeaturePillagerOutpostPoolPiece.java:54) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(WorldGenFeaturePillagerOutpostPoolPiece.java:54) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(StructureGenerator.java:129) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:717) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:272) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-"bc4b23e"]```

### Plugin list

[21:40:07 INFO]: Plugins (53): AdvancedEnchantments, AdvancementsAddon*, AuthMe, ccNoSpecTeleport*, ConsoleSpamFix, DiSky, DriveBackupV2*, EpicPluginLib, Essentials, EssentialsSpawn, FunkySk, GSit, HeadDatabase, HolographicDisplays, Images, InteractiveChat, LuckPerms, mcMMO, MessageFilter*, Minepacks, Multiverse-Core, NoteBlockAPI, OpenInv, PerWorldInventory, PlaceholderAPI, PlayMoreSounds, PlugMan, ProtocolLib, RandomTeleport, RedProtect, Reqn*, SkBee, skDragon, Skellett, SkinsRestorer, SkQuery, skRayFall, Skript, Skript-Paper*, skript-placeholders*, skript-reflect*, skript-yaml, skUtilities*, Slimefun, spark, TAB, TuSKe*, UltimateChat, Vault, ViewDistanceTweaks, Votifier, WorldEdit, WorldGuard

### Paper version

[21:40:26 INFO]: Checking version, please wait...
[21:40:26 INFO]: This server is running Paper version git-Paper-"bc4b23e" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-768 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

_No response_

**Comment by electronicboy** [comment]
Vanilla issue

**Comment by LowScarlet** [comment]
> Vanilla issue

what is? and how to fix

**Comment by electronicboy** [comment]
That error is a vanilla issue, there is no fix bar waiting right now
