### ISSUE TITLE
Crash on startup, after loading nether world

### ISSUE THREAD

**Issue by Voten641** [PaperMC/Paper#5889]
### Expected behavior

.

### Observed/Actual behavior

[03:54:04 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.scores.ScoreboardTeam.getName()" because "team" is null
        at net.minecraft.world.scores.Scoreboard.removeTeam(Scoreboard.java:199) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:633) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"bc4b23e"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[03:54:06 ERROR]: This crash report has been saved to: /root/serwery/skyblock/./crash-reports/crash-2021-06-20_03.54.06-server.txt
[03:54:06 INFO]: Stopping server

### Steps/models to reproduce

java -jar paper.jar -nogui

### Plugin list

no plugins

### Paper version

i cant type /version because server crash, its paper-1.17 build #5

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by JustAMatt** [comment]
Also had the same issue when loading End world: https://bin.bloom.host/edipobenig.yaml

This is running Paper 1.17-17 (latest build at the moment of typing this)
