### ISSUE TITLE
[1.17] [11:24:41 FATAL]: Failed to schedule load callback for chunk NoSuchMethodError: 'net.minecraft.core.IRegistry net.minecraft.core.IRegistryCustom.d(net.minecraft.resources.ResourceKey)'

### ISSUE THREAD

**Issue by danirod12** [PaperMC/Paper#5898]
### Expected behavior

Without exception

### Observed/Actual behavior

```
[11:24:41 FATAL]: Failed to schedule load callback for chunk [-30, -85]
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'net.minecraft.core.IRegistry net.minecraft.core.IRegistryCustom.d(net.minecraft.resources.ResourceKey)'
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.level.ChunkTaskQueueSorter.lambda$message$1(ChunkTaskQueueSorter.java:58) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at net.minecraft.util.thread.ThreadedMailbox.f(ThreadedMailbox.java:87) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:129) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.core.IRegistry net.minecraft.core.IRegistryCustom.d(net.minecraft.resources.ResourceKey)'
        at org.terraform.v1_17_R1.NMSChunkGenerator.buildBase(NMSChunkGenerator.java:190) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$7(ChunkStatus.java:77) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at net.minecraft.world.level.chunk.ChunkStatus$d.doWork(ChunkStatus.java:276) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at net.minecraft.world.level.chunk.ChunkStatus.a(ChunkStatus.java:212) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$39(PlayerChunkMap.java:1296) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$41(PlayerChunkMap.java:1294) ~[patched_1.17.jar:git-Paper-"ea0336d"]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
        ... 8 more
```

### Steps/models to reproduce

`java.lang.NoSuchMethodError: 'net.minecraft.core.IRegistry net.minecraft.core.IRegistryCustom.d(net.minecraft.resources.ResourceKey)`

### Plugin list

I wont show all plugins list, but maybe information about my custom world generator - `TerraformGenerator` will be useful

### Paper version

This server is running Paper version git-Paper-"ea0336d" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
https://github.com/PaperMC/paperweight/issues/24
