### ISSUE TITLE
NPE using Furnace.setCookSpeedMultiplier

### ISSUE THREAD

**Issue by Stellrow** [PaperMC/Paper#5906]
### Expected behavior

The furnace to be ready to smelt faster

### Observed/Actual behavior

A NPE appears in the console
`
[20:04:00 ERROR]: Could not pass event BlockPlaceEvent to FasterFurnace v1.0
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.crafting.IRecipe.g()" because the return value of "net.minecraft.world.level.block.entity.TileEntityFurnace.getCurrentRecipe()" is null
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftFurnace.setCookSpeedMultiplier(CraftFurnace.java:79) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at ro.Stellrow.FasterFurnace.FasterFurnaceEvents.onPlace(FasterFurnaceEvents.java:34) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:387) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:374) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:568) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1743) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
        at java.lang.Thread.run(Thread.java:831) [?:?]`
https://pastebin.com/BGQFXcmt

### Steps/models to reproduce

Calling the method on BlockPlaceEvent will throw this error
`Furnace furnace = (Furnace) placed.getState();
                furnace.setCookSpeedMultiplier(4);
                furnace.update();`

### Plugin list

None but this one

### Paper version

This server is running Paper version git-Paper-"33d6b6f" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Is this method active or passive,as the javadoc doesn't specify if a check for smeltable item should be done before calling it

**Comment by Proximyst** [comment]
> Is this method active or passive,as the javadoc doesn't specify if a check for smeltable item should be done before calling it

It should *never* throw an NPE either way. Marking accepted; thanks for the report!
