### ISSUE TITLE
"this.configuration" is null

### ISSUE THREAD

**Issue by Nestoro** [PaperMC/Paper#5917]
### Stack trace

```
[00:39:15] [Server thread/INFO]: Starting minecraft server version 1.17
[00:39:15] [Server thread/INFO]: Loading properties
[00:39:15] [Server thread/INFO]: This server is running Paper version git-Paper-"e31ad11" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[00:39:15] [Server thread/INFO]: Console input is disabled due to --noconsole command argument
[00:39:15] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.YamlConfiguration.getString(String)" because "this.configuration" is null
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadCustomPermissions(CraftServer.java:1010) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.<init>(CraftServer.java:301) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at net.minecraft.server.players.PlayerList.<init>(PlayerList.java:158) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:15) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:203) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[00:39:15] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/server/./crash-reports/crash-2021-06-21_00.39.15-server.txt
```

### Plugin list

BattleArena
ChestShop
Dynmap
EssentialsX
LuckPerms
MobArena
Multiverse
promitopnessentials
Vault
worldEdit
worldGuard

### Actions to reproduce (if known)

/bin/java -Xmx8G -Xms512M -jar paper-1.17-19.jar --noconsole

### Paper version

[00:39:15] [Server thread/INFO]: This server is running Paper version git-Paper-"e31ad11" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

i already went to delete all yml files i could find and let them regenerate but that does not prevent the crash.

**Comment by alatnet** [comment]
Having the same issue.
> [04:57:21] [Server thread/INFO]: This server is running Paper version git-Paper-"321ddfe" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
> [04:57:21] [Server thread/INFO]: Console input is disabled due to --noconsole command argument
> [04:57:21] [Server thread/ERROR]: Encountered an unexpected exception
> java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.YamlConfiguration.getString(String)" because "this.configuration" is null
> 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadCustomPermissions(CraftServer.java:1010) ~[patched_1.17.jar:git-Paper-"321ddfe"]
> 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.<init>(CraftServer.java:301) ~[patched_1.17.jar:git-Paper-"321ddfe"]
> 	at net.minecraft.server.players.PlayerList.<init>(PlayerList.java:158) ~[patched_1.17.jar:git-Paper-"321ddfe"]
> 	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:15) ~[patched_1.17.jar:git-Paper-"321ddfe"]
> 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:203) ~[patched_1.17.jar:git-Paper-"321ddfe"]
> 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"321ddfe"]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"321ddfe"]
> 	at java.lang.Thread.run(Thread.java:831) [?:?]

command line:
`-Xms4G -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1`

running this in a docker container that is using openjdk:16-alpine.

crash report is reporting about failing to read the field "reloadCount":

> java.lang.NullPointerException: Cannot read field "reloadCount" because "net.minecraft.server.MinecraftServer.getServer().server" is null
> 	at org.bukkit.craftbukkit.v1_17_R1.CraftCrashReport.get(CraftCrashReport.java:31)
> 	at org.bukkit.craftbukkit.v1_17_R1.CraftCrashReport.get(CraftCrashReport.java:17)
> 	at net.minecraft.SystemReport.a(SystemReport.java:65)
> 	at net.minecraft.CrashReport.<init>(CrashReport.java:34)
> 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1211)
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
> 	at java.base/java.lang.Thread.run(Thread.java:831)

Bare bones, no plugins.
