### ISSUE TITLE
Compitability AntiRelog with NMS Class

### ISSUE THREAD

**Issue by RitaSister** [PaperMC/Paper#5919]
### Expected behavior

[00:11:08 WARN]: [AntiRelog] Could not detect bukkit version. Trying another method
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:622) ~[?:?]
        at ru.leymooo.antirelog.util.VersionUtils.detectServerVersion(VersionUtils.java:49) ~[?:?]
        at ru.leymooo.antirelog.util.VersionUtils.<clinit>(VersionUtils.java:19) ~[?:?]
        at ru.leymooo.antirelog.manager.BossbarManager.createBossBars(BossbarManager.java:26) ~[?:?]
        at ru.leymooo.antirelog.manager.PvPManager.onPluginEnable(PvPManager.java:88) ~[?:?]
        at ru.leymooo.antirelog.manager.PvPManager.<init>(PvPManager.java:36) ~[?:?]
        at ru.leymooo.antirelog.Antirelog.onEnable(Antirelog.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[?:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:784) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:515) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:11:08 WARN]: [AntiRelog] Loaded class com.sk89q.worldguard.WorldGuard from WorldGuard v7.0.6-SNAPSHOT+2130-1cd5818 which is not a depend, softdepend or loadbefore of this plugin.
[00:11:08 WARN]: [AntiRelog] Loaded class com.sk89q.worldedit.world.World from WorldEdit v7.3.0-SNAPSHOT+5835-b8a9c00 which is not a depend, softdepend or loadbefore of this plugin.
[00:11:08 WARN]: [AntiRelog] Loaded class com.comphenix.protocol.events.PacketListener from ProtocolLib v4.7.0-SNAPSHOT-b512 which is not a depend, softdepend or loadbefore of this plugin.
[00:11:08 ERROR]: Error occurred while enabling AntiRelog v3.0.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at ru.leymooo.antirelog.Antirelog.onEnable(Antirelog.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[?:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:784) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:515) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"17f71ac"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: Failed to find NMS class: Item
        at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$1(MinecraftReflection.java:2049) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2049) ~[?:?]
        at ru.leymooo.antirelog.util.ProtocolLibUtils.<clinit>(ProtocolLibUtils.java:35) ~[?:?]
        ... 17 more

### Observed/Actual behavior

Compitability spigot plugin for paper. But now AntiRelog cannot start on paper but on spigot builds works fine!

### Steps/models to reproduce

plugin cant found NMS class "Item"
![image](https://user-images.githubusercontent.com/64961330/122692244-95eadd00-d23c-11eb-8c61-2cb19a567528.png)

### Plugin list

[02:58:10 INFO]: Plugins (50): AntiRelog, AquaLimeAdmin, AquaLimeAutoDonate, AquaLimeAutoRespawn, AquaLimeChat, AquaLimeCommand, AquaLimeCoommandLog, AquaLimeCore, AquaLimeDonateCase, AquaLimeGuilds, AquaLimeStat, ArmorStandEditor, AuctionHouse, AuthMe, AutoMessage, ChestSort, Citizens, ConsoleSpamFix, DeluxeMenus, dtlTraders, EAdvancedBan, Economy*, Essentials, EssentialsSpawn, FastLogin, GSit, GWarp, HeadDatabase, HideStream, HolographicDisplays, LimitPillagers, LuckPerms, Marriage, PlaceholderAPI, PlaceItemsOnGroundRebuilt, PlugMan, ProtocolLib, Quests, QuickShop, SkinsRestorer, TAB, TigerReports, TradePlus, UltimateAutoRestart, UralChat, VampireRevamp, Vault, WGExtender, WorldEdit, WorldGuard

### Paper version

[02:57:44 INFO]: This server is running Paper version git-Paper-"17f71ac" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are 1 version(s) behind
Previous version: git-Paper-"bc4b23e" (MC: 1.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by qixils** [comment]
[update your ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/). NMS was repackaged, meaning (from my understanding) that the classes are no longer dumped in `net.mineceaft.server.v1_XX_RX` and instead have their full paths (i.e. `net.minecraft.world.item.Item`). this is not a paper issue
