### ISSUE TITLE
When running datapacks it throws stacktrace but works on vanilla and spigot.

### ISSUE THREAD

**Issue by compieter-gh** [PaperMC/Paper#5936]
### Stack trace

```
[16:47:50 ERROR]: Feature: Not a JSON object: "wythers:generic/patch_stones_east_3"; Not a JSON object: "wythers:generic/patch_stones_south_2"; Not a JSON object: "minecraft:vines"; Not a JSON object: "minecraft:patch_melon"; Not a JSON object: "minecraft:spring_water"; Not a JSON object: "wythers:desert/oasis_patch_sugar_cane"; Not a JSON object: "minecraft:red_mushroom_normal"; Not a JSON object: "minecraft:brown_mushroom_normal"; Not a JSON object: "minecraft:red_mushroom_swamp"; Not a JSON object: "minecraft:brown_mushroom_swamp"; Not a JSON object: "minecraft:patch_waterlilly"; Not a JSON object: "minecraft:seagrass_swamp"; Not a JSON object: "minecraft:seagrass_swamp"; Not a JSON object: "minecraft:patch_grass_jungle"; Not a JSON object: "wythers:generic/flower_lily_of_the_valley"; Not a JSON object: "wythers:desert/oasis_reeds"; Not a JSON object: "wythers:desert/oasis_vegetation"; Not a JSON object: "minecraft:classic_vines_cave_feature"; Not a JSON object: "minecraft:lush_caves_vegetation"; Not a JSON object: "minecraft:lush_caves_clay"; Not a JSON object: "minecraft:cave_vines"; Not a JSON object: "minecraft:lush_caves_ceiling_vegetation"; Not a JSON object: "minecraft:glow_lichen"
[16:47:50 ERROR]: Feature: Not a JSON object: "minecraft:seagrass_swamp"; Not a JSON object: "minecraft:vines"; Not a JSON object: "minecraft:patch_melon"; Not a JSON object: "minecraft:spring_water"; Not a JSON object: "wythers:desert/oasis_patch_sugar_cane"; Not a JSON object: "minecraft:red_mushroom_normal"; Not a JSON object: "minecraft:brown_mushroom_normal"; Not a JSON object: "minecraft:patch_waterlilly"; Not a JSON object: "minecraft:patch_grass_jungle"; Not a JSON object: "wythers:generic/flower_lily_of_the_valley"; Not a JSON object: "wythers:jungle/edge_vegetation"; Not a JSON object: "minecraft:glow_lichen"
[16:47:51 ERROR]: Encountered an unexpected exception
com.google.gson.JsonParseException: Error loading registry data: Not a JSON object: null
        at net.minecraft.core.IRegistryCustom.lambda$readRegistry$6(IRegistryCustom.java:221) ~[patched_1.17.jar:git-Paper-"47605b8"]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.core.IRegistryCustom.a(IRegistryCustom.java:221) ~[patched_1.17.jar:git-Paper-"47605b8"]
        at net.minecraft.core.IRegistryCustom.a(IRegistryCustom.java:212) ~[patched_1.17.jar:git-Paper-"47605b8"]
        at net.minecraft.resources.RegistryReadOps.a(RegistryReadOps.java:57) ~[patched_1.17.jar:git-Paper-"47605b8"]
        at net.minecraft.resources.RegistryReadOps.a(RegistryReadOps.java:51) ~[patched_1.17.jar:git-Paper-"47605b8"]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:458) ~[patched_1.17.jar:git-Paper-"47605b8"]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.17.jar:git-Paper-"47605b8"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"47605b8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"47605b8"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[16:47:51 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2021-06-21_16.47.51-server.txt
```

### Plugin list

None

### Actions to reproduce (if known)

I used https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/ 
as datapack the wierd thing is it worked last night but not anymore now regardless off what i try to do.

But still works on vanilla/spigot.

### Paper version

This server is running Paper version git-Paper-"47605b8" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by jackburkhardt** [comment]
I can reproduce this, and I've also been dealing with the same issue on the same datapack. Currently the last version of Paper I've found that does not have this problem is build 6 (git-Paper-"ce66102" (MC: 1.17)).

For visibility: There's another bug with structure modifying datapacks that may cause chunks to fail to generate and create server crashes. I've narrowed this down to a vanilla server bug and opened a bug report with Mojang.

**Comment by kohy-creates** [comment]
I am able to reproduce the issue as well on Paper 1.17 build 39

**Comment by alaajel** [comment]
~~i think this caused by this commit https://github.com/PaperMC/Paper/commit/c4c6e26c00665989d3c1c82fb115a8f7f8de659b since related to world gen api addition~~

oops see my last message

**Comment by G4stavoM1ster** [comment]
I'm dealing with the same issue too.

**Comment by Machine-Maker** [comment]
@G4stavoM1ster if you aren’t providing new information, there’s no need to bump issues.

**Comment by jackburkhardt** [comment]
This looks like it could be related to https://bugs.mojang.com/browse/MC-196068 since that has also been unresolved. I think @ham1255 is right that the worldgen api changes might have caused this, but it's weird that we don't also see it in Vanilla or Spigot if there's a related Vanilla bug.

**Comment by kohy-creates** [comment]
Still present on build 46 (Paper #46, can be easily reproduced and confirmed to malfunction

**Comment by kohy-creates** [comment]
Can still confirm on Build number 48
I really hope that you can fix this quickly, because it hurts a lot server owners that use worldgen datapacks

**Comment by kennytv** [comment]
Please don't unnecessarily bump the issue if you do not provide new information. If it were fixed, we would have closed the issue.

**Comment by alaajel** [comment]
> This looks like it could be related to https://bugs.mojang.com/browse/MC-196068 since that has also been unresolved. I think @ham1255 is right that the worldgen api changes might have caused this, but it's weird that we don't also see it in Vanilla or Spigot if there's a related Vanilla bug.

No its not related to it since it was reported after 1.16 release or something.

**Comment by alaajel** [comment]
okay found exact commit causing this https://github.com/PaperMC/Paper/commit/c89ec406193e8171f1a2e75159ba54ecaf6d66e4
patch: https://github.com/PaperMC/Paper/blob/master/patches/server/0715-Fix-Codec-log-spam.patch

**Comment by electronicboy** [comment]
There was some discussions about that patch this morning internally, I think that dropping it is okay bar the fact that it's otherwise spammy, speaking to mojang the issue here generally is that the server was saving data which sohuldn't have been saved, and at least in this specific case, it has no real harm in this instance
