### ISSUE TITLE
PaperSpigot 1.8.8 server error

### ISSUE THREAD

**Issue by Pluginsel** [PaperMC/Paper#594]
PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar and PaperSpigot-api-1.8.8-R0.1-SNAPSHOT-latest.jar server error:
C:\Users\Lenovo\Desktop\paperspigot>java -Xmx3072M -Xms3072M -Dfile.encoding=UTF-8 -jar craftbukkit.jar
Loading libraries, please wait...
2017-01-29 10:10:05,892 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:204)
at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.init(WindowsTerminal.java:82)
at org.bukkit.craftbukkit.libs.jline.TerminalFactory.create(TerminalFactory.java:101)
at org.bukkit.craftbukkit.libs.jline.TerminalFactory.get(TerminalFactory.java:158)
at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:229)
at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:221)
at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:213)
at net.minecraft.server.v1_8_R3.MinecraftServer.<init>(MinecraftServer.java:141)
at net.minecraft.server.v1_8_R3.DedicatedServer.<init>(DedicatedServer.java:43)
at net.minecraft.server.v1_8_R3.MinecraftServer.main(MinecraftServer.java:984)
at org.bukkit.craftbukkit.Main.main(Main.java:201)

[10:10:13 INFO]: Starting minecraft server version 1.8.8
[10:10:13 INFO]: Loading properties
[10:10:13 INFO]: Default game type: SURVIVAL
[10:10:14 INFO]: This server is running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[10:10:14 INFO]: Debug logging is disabled
[10:10:14 INFO]: Spigot Timings: true - Verbose: true - Interval: 5m - Length: 60m
[10:10:14 INFO]: Server Ping Player Sample Count: 12
[10:10:14 INFO]: Using 4 threads for Netty based IO
[10:10:14 INFO]: Data value allowed items:
[10:10:14 INFO]: Generating keypair
[10:10:16 INFO]: Starting Minecraft server on *:25565
[10:10:16 INFO]: Using default channel type
[10:10:16 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[10:10:16 INFO]: Preparing level "world"
[10:10:17 INFO]: -------- World Settings For [world] --------
[10:10:17 INFO]: Item Merge Radius: 2.5
[10:10:17 INFO]: Item Despawn Rate: 6000
[10:10:17 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:10:17 INFO]: Nerfing mobs spawned from spawners: false
[10:10:17 INFO]: Anti X-Ray: true
[10:10:17 INFO]: Engine Mode: 1
[10:10:17 INFO]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[10:10:17 INFO]: Replace Blocks: [1, 5]
[10:10:17 INFO]: Mob Spawn Range: 4
[10:10:17 INFO]: Max TNT Explosions: 100
[10:10:17 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:10:17 INFO]: Structure Info Saving: true
[10:10:17 INFO]: Cactus Growth Modifier: 100%
[10:10:17 INFO]: Cane Growth Modifier: 100%
[10:10:17 INFO]: Melon Growth Modifier: 100%
[10:10:17 INFO]: Mushroom Growth Modifier: 100%
[10:10:17 INFO]: Pumpkin Growth Modifier: 100%
[10:10:17 INFO]: Sapling Growth Modifier: 100%
[10:10:17 INFO]: Wheat Growth Modifier: 100%
[10:10:17 INFO]: NetherWart Growth Modifier: 100%
[10:10:17 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:10:17 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:10:17 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:10:17 INFO]: Random Lighting Updates: false
[10:10:17 INFO]: Sending up to 10 chunks per packet
[10:10:17 INFO]: Experience Merge Radius: 3.0
[10:10:17 INFO]: Chunks to Grow per Tick: 650
[10:10:17 INFO]: Clear tick list: false
[10:10:17 INFO]: Max Entity Collisions: 8
[10:10:17 INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[10:10:17 INFO]: View Distance: 10
[10:10:17 INFO]: Arrow Despawn Rate: 1200
[10:10:17 INFO]: Zombie Aggressive Towards Villager: true
[10:10:17 INFO]: -------- World Settings For [world] --------
[10:10:17 INFO]: Water over lava flow speed: 5
[10:10:17 INFO]: Fix TNT cannons: false
[10:10:17 INFO]: World async lighting: false
[10:10:17 INFO]: WorldServer TickNextTick cap set at 10000
[10:10:17 INFO]: WorldServer TickNextTickList cap always processes redstone: false
[10:10:17 INFO]: Player blocking damage multiplier set to 0.5
[10:10:17 INFO]: Remove invalid mob spawner tile entities: true
[10:10:17 INFO]: Max height for cactus growth 3. Max height for reed growth 3
[10:10:17 INFO]: Living Entity Despawn Ranges: Soft: 32 Hard: 128
[10:10:17 INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[10:10:17 INFO]: Keep spawn chunk loaded: true
[10:10:17 INFO]: Allow undead horse types to be leashed: false
[10:10:17 INFO]: -------- World Settings For [world_nether] --------
[10:10:17 INFO]: Item Merge Radius: 2.5
[10:10:17 INFO]: Item Despawn Rate: 6000
[10:10:17 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:10:17 INFO]: Nerfing mobs spawned from spawners: false
[10:10:17 INFO]: Anti X-Ray: true
[10:10:17 INFO]: Engine Mode: 1
[10:10:17 INFO]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[10:10:17 INFO]: Replace Blocks: [1, 5]
[10:10:17 INFO]: Mob Spawn Range: 4
[10:10:17 INFO]: Max TNT Explosions: 100
[10:10:17 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:10:17 INFO]: Structure Info Saving: true
[10:10:17 INFO]: Cactus Growth Modifier: 100%
[10:10:17 INFO]: Cane Growth Modifier: 100%
[10:10:17 INFO]: Melon Growth Modifier: 100%
[10:10:17 INFO]: Mushroom Growth Modifier: 100%
[10:10:17 INFO]: Pumpkin Growth Modifier: 100%
[10:10:17 INFO]: Sapling Growth Modifier: 100%
[10:10:17 INFO]: Wheat Growth Modifier: 100%
[10:10:17 INFO]: NetherWart Growth Modifier: 100%
[10:10:17 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:10:17 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:10:17 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:10:17 INFO]: Random Lighting Updates: false
[10:10:17 INFO]: Sending up to 10 chunks per packet
[10:10:17 INFO]: Experience Merge Radius: 3.0
[10:10:17 INFO]: Chunks to Grow per Tick: 650
[10:10:17 INFO]: Clear tick list: false
[10:10:17 INFO]: Max Entity Collisions: 8
[10:10:17 INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[10:10:17 INFO]: View Distance: 10
[10:10:17 INFO]: Arrow Despawn Rate: 1200
[10:10:17 INFO]: Zombie Aggressive Towards Villager: true
[10:10:17 INFO]: -------- World Settings For [world_nether] --------
[10:10:17 INFO]: Water over lava flow speed: 5
[10:10:17 INFO]: Fix TNT cannons: false
[10:10:17 INFO]: World async lighting: false
[10:10:17 INFO]: WorldServer TickNextTick cap set at 10000
[10:10:17 INFO]: WorldServer TickNextTickList cap always processes redstone: false
[10:10:17 INFO]: Player blocking damage multiplier set to 0.5
[10:10:17 INFO]: Remove invalid mob spawner tile entities: true
[10:10:17 INFO]: Max height for cactus growth 3. Max height for reed growth 3
[10:10:17 INFO]: Living Entity Despawn Ranges: Soft: 32 Hard: 128
[10:10:17 INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[10:10:17 INFO]: Keep spawn chunk loaded: true
[10:10:17 INFO]: Allow undead horse types to be leashed: false
[10:10:17 INFO]: -------- World Settings For [world_the_end] --------
[10:10:17 INFO]: Item Merge Radius: 2.5
[10:10:17 INFO]: Item Despawn Rate: 6000
[10:10:17 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:10:17 INFO]: Nerfing mobs spawned from spawners: false
[10:10:17 INFO]: Anti X-Ray: true
[10:10:17 INFO]: Engine Mode: 1
[10:10:17 INFO]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[10:10:17 INFO]: Replace Blocks: [1, 5]
[10:10:17 INFO]: Mob Spawn Range: 4
[10:10:17 INFO]: Max TNT Explosions: 100
[10:10:17 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:10:17 INFO]: Structure Info Saving: true
[10:10:17 INFO]: Cactus Growth Modifier: 100%
[10:10:17 INFO]: Cane Growth Modifier: 100%
[10:10:17 INFO]: Melon Growth Modifier: 100%
[10:10:17 INFO]: Mushroom Growth Modifier: 100%
[10:10:17 INFO]: Pumpkin Growth Modifier: 100%
[10:10:17 INFO]: Sapling Growth Modifier: 100%
[10:10:17 INFO]: Wheat Growth Modifier: 100%
[10:10:17 INFO]: NetherWart Growth Modifier: 100%
[10:10:17 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:10:17 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:10:17 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:10:17 INFO]: Random Lighting Updates: false
[10:10:17 INFO]: Sending up to 10 chunks per packet
[10:10:17 INFO]: Experience Merge Radius: 3.0
[10:10:17 INFO]: Chunks to Grow per Tick: 650
[10:10:17 INFO]: Clear tick list: false
[10:10:17 INFO]: Max Entity Collisions: 8
[10:10:17 INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[10:10:17 INFO]: View Distance: 10
[10:10:17 INFO]: Arrow Despawn Rate: 1200
[10:10:17 INFO]: Zombie Aggressive Towards Villager: true
[10:10:17 INFO]: -------- World Settings For [world_the_end] --------
[10:10:17 INFO]: Water over lava flow speed: 5
[10:10:17 INFO]: Fix TNT cannons: false
[10:10:17 INFO]: World async lighting: false
[10:10:17 INFO]: WorldServer TickNextTick cap set at 10000
[10:10:17 INFO]: WorldServer TickNextTickList cap always processes redstone: false
[10:10:17 INFO]: Player blocking damage multiplier set to 0.5
[10:10:17 INFO]: Remove invalid mob spawner tile entities: true
[10:10:17 INFO]: Max height for cactus growth 3. Max height for reed growth 3
[10:10:17 INFO]: Living Entity Despawn Ranges: Soft: 32 Hard: 128
[10:10:17 INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[10:10:17 INFO]: Keep spawn chunk loaded: true
[10:10:17 INFO]: Allow undead horse types to be leashed: false
[10:10:17 INFO]: Preparing start region for level 0 (Seed: -5732663450053246150)
[10:10:18 INFO]: Preparing spawn area: 6%
[10:10:19 INFO]: Preparing spawn area: 43%
[10:10:20 INFO]: Preparing start region for level 1 (Seed: -5732663450053246150)
[10:10:21 INFO]: Preparing spawn area: 48%
[10:10:22 INFO]: Preparing start region for level 2 (Seed: -5732663450053246150)
[10:10:23 INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:10:23 INFO]: Done (6,372s)! For help, type "help" or "?"
[10:10:23 INFO]: Timings Reset
>stop
[10:10:45 INFO]: Stopping the server
[10:10:45 INFO]: Stopping server
[10:10:45 INFO]: Saving players
[10:10:45 INFO]: Saving worlds
[10:10:45 INFO]: Saving chunks for level 'world'/Overworld
[10:10:46 INFO]: Saving chunks for level 'world_nether'/Nether
[10:10:46 INFO]: Saving chunks for level 'world_the_end'/The End
>[WARN] Task failed
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
at org.fusesource.jansi.internal.WindowsSupport.setConsoleMode(WindowsSupport.java:60)
at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.setConsoleMode(WindowsTerminal.java:208)
at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.restore(WindowsTerminal.java:95)
at org.bukkit.craftbukkit.libs.jline.TerminalSupport$1.run(TerminalSupport.java:52)
at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.runTasks(ShutdownHooks.java:66)
at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.access$000(ShutdownHooks.java:22)
at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks$1.run(ShutdownHooks.java:47)

C:\Users\Lenovo\Desktop\paperspigot>PAUSE
Premere un tasto per continuare . . .

Plugins: 0
On server is starting and stopping, an internal error occurred.
Please fix thank you!

**Comment by zachbr** [comment]
We do not support 1.8.8 any longer.

This issue is non-critical anyway, it's an issue with loading formatted console support on Windows.
