### ISSUE TITLE
No Such Method when enabling CommandAPI

### ISSUE THREAD

**Issue by toddharrison** [PaperMC/Paper#5963]
### Expected behavior

Clean startup.

### Observed/Actual behavior

[21:15:39 WARN]: [CommandAPI] Task #9 for CommandAPI v6.0.5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.server.packs.resources.IResourceManager net.minecraft.server.DataPackResources.i()'
	at dev.jorel.commandapi.nms.NMS_1_17_R1.reloadDataPacks(NMS_1_17_R1.java:861) ~[?:?]
	at dev.jorel.commandapi.CommandAPI.lambda$onEnable$0(CommandAPI.java:177) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"28aacb4"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-"28aacb4"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1127) ~[patched_1.17.jar:git-Paper-"28aacb4"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"28aacb4"]
	at java.lang.Thread.run(Thread.java:831) [?:?]

### Steps/models to reproduce

Using latest paper 1.17-39 jar. Looks like CommandAPI is relying on an i() method in DataPackResources. Any idea if this is going to be resolved to be compatible with the Spigot API or if these obfuscated methods are going to change?

### Plugin list

CommandAPI

### Paper version

1.17-39

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
https://github.com/PaperMC/paperweight/issues/24

**Comment by toddharrison** [comment]
thanks!
