### ISSUE TITLE
Error on console with Craftbook in latest Build

### ISSUE THREAD

**Issue by CloudeLecaw** [PaperMC/Paper#5968]
### Expected behavior

The plugin should load normaly..before i used Paper Build 30 and the plugin Craftbook was loading without an error...

### Observed/Actual behavior

what i saw: an error in the console...

### Steps/models to reproduce

The error in the console appeared today when i update to the latest paerMC build 42 of MC 1.17

**Versions**
- CraftBook_3.10.4-Build4700
- Paper version git-Paper-"4e2f0be" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

```
1:22:08] [Server thread/ERROR]: Could not load 'plugins\CraftBook_3.10.4-Build4700.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.minecraft.util.commands.CommandPermissionsException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	... 7 more
```

### Plugin list

CraftBook_3.10.4-Build4700

### Paper version

This server is running Paper version git-Paper-"4e2f0be" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by CloudeLecaw** [comment]
solved...why ever...worldedit was missing.....

**Comment by Chew** [comment]
Judging by the package it wouldn't be our issue anyway: `com/sk89q/minecraft/util/commands`
