### ISSUE TITLE
Stuck on saving new chunks

### ISSUE THREAD

**Issue by 4bitFox** [PaperMC/Paper#5985]
### Expected behavior

Server should save the world and close / restart.

### Observed/Actual behavior

Server gets stuck while saving the world when I try to close the server.

Someone always traveled to new chunks and loaded them in and built in them. After a while (2-3h) single chunks stop loading in. To fix this I tried to restart the Server which it never did, because it got stuck in the process of saving the world. 

This never happened when I and my Friends stayed in previously generated chunks.

When I close the terminal, java still remains running in the background and without killing it, the server will not relaunch.
Also the stuff that was built remained after relaunching and did not get lost.

### Steps/models to reproduce

- Load up an existing world (initial 1.14.1 and then every update afterwards in my case) and travel into new chunks.
- Play until chunks start to not load in properly anymore.
- close sever

### Plugin list

AFK-Kick:               https://www.spigotmc.org/resources/77913/
AutoStop:               https://github.com/pmdevita/AutoStop/releases
Coordinates:            https://www.spigotmc.org/resources/80304/
CoreProtect:            https://www.spigotmc.org/resources/8631/
DeathCoordinates:       https://www.spigotmc.org/resources/43318/
Dynmap:                 https://github.com/webbukkit/dynmap/releases/
GriefPrevention:        https://github.com/TechFortress/GriefPrevention/releases/
Harbor:                 https://github.com/nkomarn/Harbor/releases/
HomeSpawn:              https://www.spigotmc.org/resources/14108/
JDynmapGriefPrevention: https://www.spigotmc.org/resources/818/
PlaceholderAPI:         https://github.com/PlaceholderAPI/PlaceholderAPI/releases/
SimpleTPA:              https://www.spigotmc.org/resources/64270/
TabList:                https://github.com/montlikadani/TabList/releases/
ViaBackwards:           https://github.com/ViaVersion/ViaBackwards/releases/
ViaRewind:              https://www.spigotmc.org/resources/52109/
ViaVersion:             https://github.com/ViaVersion/ViaVersion/releases/
ViewDistanceTweaks:     https://www.spigotmc.org/resources/75164/
VoidSpawn:              https://github.com/endercrest/VoidSpawn/releases/

### Paper version

`This server is running Paper version git-Paper-45 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0be7cdb)`

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Terminal output when closing server:
```
[18:57:03] [Server thread/INFO]: Stopping the server
[18:57:03] [Server thread/INFO]: Stopping server
[18:57:03] [Server thread/INFO]: [JDynmapGriefPrevention] Disabling JDynmapGriefPrevention v2.5.1
[18:57:03] [Server thread/INFO]: [JDynmapGriefPrevention] Plugin JDynMapGriefPrevention disabled
[18:57:03] [Server thread/INFO]: [ViaRewind] Disabling ViaRewind v2.0.0
[18:57:03] [Server thread/INFO]: [VoidSpawn] Disabling VoidSpawn v1.19.3
[18:57:03] [Server thread/INFO]: [VoidSpawn] v1.19.3 saving config
[18:57:03] [Server thread/INFO]: [VoidSpawn] v1.19.3 disabled
[18:57:03] [Server thread/INFO]: [GriefPrevention] Disabling GriefPrevention v16.17.1-2b69191
[18:57:03] [Server thread/INFO]: [GriefPrevention] GriefPrevention disabled.
[18:57:03] [Server thread/INFO]: [ViaBackwards] Disabling ViaBackwards v4.0.0
[18:57:03] [Server thread/INFO]: [ViaVersion] Disabling ViaVersion v4.0.0
[18:57:03] [Server thread/INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[18:57:03] [Server thread/INFO]: [AFK-Kick] Disabling AFK-Kick v1.1
[18:57:03] [Server thread/INFO]: [HomeSpawn] Disabling HomeSpawn v3.1.15
[18:57:03] [Server thread/INFO]: [HomeSpawn] HomeSpawn has been disabled
[18:57:03] [Server thread/INFO]: [AutoStop] Disabling AutoStop v1.0
[18:57:03] [Server thread/INFO]: [TabList] Disabling TabList v5.5.4
[18:57:03] [Server thread/INFO]: [DeathCoordinates] Disabling DeathCoordinates v1.9.1
[18:57:03] [Server thread/INFO]: [DeathCoordinates] Has been disabled! Version: 1.9.1
[18:57:03] [Server thread/INFO]: [Coordinates] Disabling Coordinates v2.11
[18:57:03] [Server thread/INFO]: [ViewDistanceTweaks] Disabling ViewDistanceTweaks v1.3.3
[18:57:03] [Server thread/INFO]: [Harbor] Disabling Harbor v1.6.3
[18:57:03] [Server thread/INFO]: [dynmap] Disabling dynmap v3.2-beta-1-470
[18:57:03] [Server thread/INFO]: [dynmap] Unloaded 11 components.
[18:57:03] [Server thread/INFO]: [dynmap] Stopping map renderer...
[18:57:04] [Server thread/INFO]: [dynmap] Saved 13703 pending tile renders in world 'world'
[18:57:04] [Server thread/INFO]: [dynmap] Disabled
[18:57:04] [Server thread/INFO]: [SimpleTpa] Disabling SimpleTpa v5.4
[18:57:04] [Server thread/INFO]: [SimpleTpa] If you need support contact me at https://discord.gg/SZUkza9
[18:57:04] [Server thread/INFO]: [SimpleTpa] Simple Tpa has been disabled on version 5.4
[18:57:04] [Server thread/INFO]: [CoreProtect] Disabling CoreProtect v19.5
[18:57:04] [Server thread/INFO]: [CoreProtect] Finishing up data logging. Please wait...
[18:57:05] [Server thread/INFO]: [CoreProtect] Success! Disabled CoreProtect v19.5
[18:57:05] [Server thread/INFO]: Saving players
[18:57:05] [Server thread/INFO]: 4bitFox lost connection: Server closed.
[18:57:05] [Server thread/INFO]: 4bitFox left the game
[18:57:05] [Server thread/INFO]: Saving worlds
[18:57:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
```

When I then close the terminal I get following output in log:
```
[19:05:34] [Server console handler/ERROR]: Caught previously unhandled exception :
java.io.IOError: java.io.IOException: Input/output error
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:143) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[patched_1.17.jar:git-Paper-45]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[patched_1.17.jar:git-Paper-45]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[patched_1.17.jar:git-Paper-45]
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:112) ~[patched_1.17.jar:git-Paper-45]
Caused by: java.io.IOException: Input/output error
	at java.io.FileInputStream.read0(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:223) ~[?:?]
	at org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57) ~[patched_1.17.jar:git-Paper-45]
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133) ~[patched_1.17.jar:git-Paper-45]
	... 9 more
```

**Comment by Machine-Maker** [comment]
Duplicate of #5909 i think. Try latest version (which you aren’t on, build 46).

**Comment by alya-can-eat** [comment]
Oh whoops, I'll try it. 

And also I just noticed I should've looked in the resolved issues too *facepalm*. 
Sorry for that.

**Comment by Chew** [comment]
\> I am running the latest version of Paper available from papermc.io/downloads.
\> This server is running Paper version git-Paper-45

😢
