### ISSUE TITLE
No key dirt_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform"

### ISSUE THREAD

**Issue by antibitcoin** [PaperMC/Paper#6017]
### Expected behavior

No spam on console 

### Observed/Actual behavior

spam on console
```
[18:59:40 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[18:59:40 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-53]
[18:59:40 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[18:59:40 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-53]
[18:59:40 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{height:{type:"minecraft:uniform",value:{max_inclusive:4,min_inclusive:3}},offset:1,radius:1,type:"minecraft:pine_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:6,height_rand_a:4,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{height:{type:"minecraft:uniform",value:{max_inclusive:4,min_inclusive:3}},offset:1,radius:1,type:"minecraft:pine_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:6,height_rand_a:4,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[18:59:40 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-53]
[18:59:40 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[18:59:40 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-53]
[18:59:40 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[18:59:40 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-53]
[18:59:40 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{offset:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:0}},radius:{type:"minecraft:uniform",value:{max_inclusive:3,min_inclusive:2}},trunk_height:{type:"minecraft:uniform",value:{max_inclusive:2,min_inclusive:1}},type:"minecraft:spruce_foliage_placer"},foliage_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},force_dirt:0b,ignore_vines:1b,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[18:59:40 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-53]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-53]
```
### Steps/models to reproduce

Just running the server

### Plugin list

[19:07:15 INFO]: Plugins (94): AdvancedCrates, AdvancedEnchantments, AdvancedNMotd, AltDetector, antiRedstoneClock, ArmoredElytra, ArmorStandCrashFix*, AuctionHouse, AutoBroadcast, BanItem, BannerText, BungeeGuard, BuycraftX, ChatEx*, ChatSentinel, Citizens, ClearLag, CMILib, CommandAlias, CommandPanels, CrazyEnvoy, CubCustomDrops, DeathMessages, DeluxeCoinflip, DeluxeMenus, DeluxeTags*, DiscordSRV, dtlTraders, eBackup, EnchantmentNumbers, Essentials, EssentialsGeoIP, EvenMoreFish, ExecutableItems, EZColors, FarmControl, GambleBarLite*, GangsPlus, Gatekeeper*, HarmonyScoreboard, HeadDatabase, HolographicDisplays, HolographicPlaceholders, HolographicScoreboard*, IllegalStack, Insights, InteractiveChat, ItemEditor, ItemSoulBind, Jobs, JoinEventsPro, LPX*, LuckPerms, mcMMO, Mines, NoMobLag, OpenInv, PL-Hide-Pro, PlaceholderAPI, PlayerParticles, PlayerVaults, Playtimes*, PluginConstructorAPI, ProdigyMentionSpigot*, ProtocolLib, pvpstats, Quests, Regionerator, SaveRodOfficial*, SCore, ShopGUIPlus, Shopkeepers, SilkSpawners, SimpleGiveall, SimpleRename, Skript, SlotMachine, SpecializedCrates, StoreStats, TAB, Themis, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, VoteParty, Votifier, VotingPlugin, Vouchers, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper version

[19:07:42 INFO]: This server is running Paper version git-Paper-53 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ad5526)
You are running the latest version
Previous version: git-Paper-47 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Sometimes the server crashes randomly

**Comment by electronicboy** [comment]
spam is caused by a well-reported and known vanilla issue, please use the search feature.

**Comment by nicermak** [comment]
maybe jigsaw block

**Comment by nicermak** [comment]
maybe jigsaw block

**Comment by nicermak** [comment]
load structure error?

**Comment by electronicboy** [comment]
The underlying issues are generally known, no need to comment on all of them
