### ISSUE TITLE
[ERROR]: Could not load 'plugins/paper.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by arbirk** [PaperMC/Paper#6071]
### Expected behavior

No error when starting server

### Observed/Actual behavior

This error message:

[04:54:43 ERROR]: Could not load 'plugins/paper.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.17.jar:git-Paper-71]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.17.jar:git-Paper-71]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-71]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

### Steps/models to reproduce

Experienced on Papermc 1.17 61 and 71

### Plugin list

Geyser
Floodgate

Both up to date

### Paper version

> version
[04:55:10 INFO]: Checking version, please wait...
[04:55:10 INFO]: This server is running Paper version git-Paper-71 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ae6dd2)
You are running the latest version
Previous version: git-Paper-61 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Server start log:

~/3paper$ java -Xms3G -Xmx3G -jar paper.jar --nogui
Patching vanilla jar...
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9-Ubuntu-120.04) Host: Linux 5.4.0-77-generic (amd64)
Loading libraries, please wait...
[04:54:41 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:54:41 INFO]: Reloading ResourceManager: Default, bukkit
[04:54:42 INFO]: Loaded 7 recipes
[04:54:42 INFO]: Starting minecraft server version 1.17
[04:54:42 INFO]: Loading properties
[04:54:42 INFO]: This server is running Paper version git-Paper-71 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ae6dd2)
[04:54:42 INFO]: Debug logging is disabled
[04:54:42 INFO]: Server Ping Player Sample Count: 12
[04:54:42 INFO]: Using 4 threads for Netty based IO
[04:54:42 INFO]: Default game type: SURVIVAL
[04:54:42 INFO]: Generating keypair
[04:54:42 INFO]: Starting Minecraft server on *:25565
[04:54:42 INFO]: Using epoll channel type
**[04:54:43 ERROR]: Could not load 'plugins/paper.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.17.jar:git-Paper-71]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.17.jar:git-Paper-71]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-71]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more**
[04:54:43 INFO]: [floodgate] Loading floodgate v2.0-SNAPSHOT
[04:54:43 INFO]: [floodgate] Took 216ms to boot Floodgate
[04:54:43 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v1.4.0-SNAPSHOT
[04:54:43 INFO]: Server permissions file permissions.yml is empty, ignoring it
[04:54:43 INFO]: Preparing level "world"
[04:54:43 INFO]: Preparing start region for dimension minecraft:overworld
[04:54:45 INFO]: Preparing spawn area: 0%
[04:54:45 INFO]: Preparing spawn area: 0%
[04:54:45 INFO]: Preparing spawn area: 0%
[04:54:45 INFO]: Preparing spawn area: 0%
[04:54:45 INFO]: Time elapsed: 1640 ms
[04:54:45 INFO]: Preparing start region for dimension minecraft:the_nether
[04:54:46 INFO]: Preparing spawn area: 0%
[04:54:46 INFO]: Preparing spawn area: 0%
[04:54:46 INFO]: Preparing spawn area: 0%
[04:54:46 INFO]: Preparing spawn area: 0%
[04:54:47 INFO]: Preparing spawn area: 0%
[04:54:47 INFO]: Preparing spawn area: 2%
[04:54:48 INFO]: Time elapsed: 2818 ms
[04:54:48 INFO]: Preparing start region for dimension minecraft:the_end
[04:54:49 INFO]: Preparing spawn area: 0%
[04:54:49 INFO]: Preparing spawn area: 0%
[04:54:49 INFO]: Preparing spawn area: 0%
[04:54:49 INFO]: Time elapsed: 1261 ms
[04:54:49 INFO]: [floodgate] Enabling floodgate v2.0-SNAPSHOT
[04:54:49 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v1.4.0-SNAPSHOT
[04:54:49 INFO]: [Geyser-Spigot] Auto-loaded Floodgate key
[04:54:49 INFO]: [Geyser-Spigot] ******************************************
[04:54:49 INFO]: [Geyser-Spigot]
[04:54:49 INFO]: [Geyser-Spigot] Loading Geyser version 1.4.0-SNAPSHOT (git-master-7ae27c7)
[04:54:49 INFO]: [Geyser-Spigot]
[04:54:49 INFO]: [Geyser-Spigot] ******************************************
[04:54:52 INFO]: [Geyser-Spigot] Loaded Floodgate key!
[04:54:52 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:19132
[04:54:52 INFO]: [Geyser-Spigot] Done (2.849s)! Run /geyser help for help!
[04:54:52 INFO]: Running delayed init tasks
[04:54:52 INFO]: Done (9.889s)! For help, type "help"
[04:54:52 INFO]: Timings Reset
> version
[04:55:10 INFO]: Checking version, please wait...
[04:55:10 INFO]: This server is running Paper version git-Paper-71 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ae6dd2)
You are running the latest version
Previous version: git-Paper-61 (MC: 1.17)

**Comment by e-im** [comment]
It looks like you have put the paper jar in your plugins folder. Don't do this.

**Comment by arbirk** [comment]
Thanks. I feel stupid now. Will go drown in lava
