### ISSUE TITLE
Concurrent error when command block runs a command that calls WorldCreator#create() 

### ISSUE THREAD

**Issue by benwoo1110** [PaperMC/Paper#6072]
### Stack trace

Full logs: https://paste.gg/p/anonymous/6168fb83d14f4a098552de5d660e638a
Crash report: https://paste.gg/p/anonymous/45198f1c046047bba6ed8b62784de493

### Plugin list

```
> plugins
[17:30:30 INFO]: Plugins (1): TestPlugin
```

Just a simple plugin I created to reproduce the issue.

### Actions to reproduce (if known)

Command block created:
![image](https://user-images.githubusercontent.com/30431861/124349840-e6dad800-dc23-11eb-9819-ed051f6a536a.png)

When command block is activated by pressing a button it runs the following code:
```java
    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        World world = WorldCreator.name("testworld")
                .environment(World.Environment.NORMAL)
                .type(WorldType.NORMAL)
                .createWorld();

        getLogger().info(String.valueOf(world));

        return true;
    }
```

World creates successfully, but concurrent error will follow afterwards:
```
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:758) ~[?:?]
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1530) ~[patched_1.17.jar:git-Paper-71]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-71]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-71]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-71]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-71]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

I would like to add that running the command through the console or in chat does not result in such an issue. This issue is specific to when command blocks are used to execute the command.

### Paper version

```
> version
[17:27:54 INFO]: Checking version, please wait...
[17:27:54 INFO]: This server is running Paper version git-Paper-71 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ae6dd2)
You are running the latest version
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Zip file of the plugin code I used for testing: [TestPlugin.zip](https://github.com/PaperMC/Paper/files/6758169/TestPlugin.zip)

**Comment by Machine-Maker** [comment]
I think, like Proxi said in the mentioned PR, that it should be documented that you shouldn't create worlds while the world is ticking, there are probably tons of other ways to cause the CME, not just command blocks, creating worlds in certain events for example.
