### ISSUE TITLE
Error when players move arround the map

### ISSUE THREAD

**Issue by CloudeLecaw** [PaperMC/Paper#6081]
### Expected behavior

no error in console...
as im not sure what is creating this issue

### Observed/Actual behavior

an error in console

```
>.... [17:20:31 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
>.... [17:20:31 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-72]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-72]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-72]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-72]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-72]
```

### Steps/models to reproduce

we just have this errorlog that is coming from...we dont know where..
we dont even know acceptly what this error means..
I would say...players exploring the world...
besides i never heared of an item called minecraft:jigsaw
i just can see its a bock that i cant place...
![Snag_1f460fd1](https://user-images.githubusercontent.com/12080017/124391650-ee68b280-dcf1-11eb-87a5-394cbcd72e1b.png)

....

### Plugin list

![Snag_1f415723](https://user-images.githubusercontent.com/12080017/124391511-363b0a00-dcf1-11eb-80eb-b5987afba8fe.png)

### Paper version

![Snag_1f41ac67](https://user-images.githubusercontent.com/12080017/124391521-43f08f80-dcf1-11eb-8ec0-670444240e04.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by boonsboos** [comment]
know issue, vanilla bug

please use the search function
