### ISSUE TITLE
ASM event executor error

### ISSUE THREAD

**Issue by nklyshko** [PaperMC/Paper#610]
My plugin can't register event listener on paperspigot 1.9.4(build 773), but on original spigot all works fine.

https://aquifermc.org/threads/plugin-enabling-error-registerevents.457/#post-2408

**Comment by prplz** [comment]
Please confirm on the latest paper

**Comment by zachbr** [comment]
We do not support 1.9.4, you will need to update and re-test.

Edit: And providing all associated source code, or a small sample plugin or section we can use to reproduce outside of your own work.

**Comment by nklyshko** [comment]
https://hastebin.com/ehetiqowuw.java
https://hastebin.com/nocecifuxu.cs
https://hastebin.com/wucahokisi.java

And calling constructor of TestListener causes error:
`[17:49:51 ERROR]: Error occurred while enabling Test2 v1.1.1 (Is it up to date?)
java.lang.VerifyError: Illegal type at constant pool entry 20 in class com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2
Exception Details:
  Location:
    com/destroystokyo/paper/event/executor/asm/generated/GeneratedEventExecutor2.execute(Lorg/bukkit/event/Listener;Lorg/bukkit/event/Event;)V @8: invokevirtual
  Reason:
    Constant pool index 20 is invalid
  Bytecode:
    0x0000000: 2bc0 000e 2cc0 0010 b600 14b1
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_111]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_111]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_111]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_111]
        at org.bukkit.plugin.EventExecutor.create(EventExecutor.java:37) ~[patched_1.11.2.jar:git-Paper-1056]
        at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:290) ~[patched_1.11.2.jar:git-Paper-1056]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:548) ~[patched_1.11.2.jar:git-Paper-1056]
        at ru.cerebus.minecraft.ManagerBase.enable(ManagerBase.java:35) ~[?:?]
        at ru.cerebus.minecraft.ManagerBase.<init>(ManagerBase.java:24) ~[?:?]
        at ru.craftcoderr.test2.TestListener.<init>(TestListener.java:15) ~[?:?]
        at ru.craftcoderr.test2.BukkitPlugin.onEnable(BukkitPlugin.java:44) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1056]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1056]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1056]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1056]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1056]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1056]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1056]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1056]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1056]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1056]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

http://rgho.st/6zst6cv6v - test plugin

P.S. I test it on latest build

**Comment by jonesdj1** [comment]
hmm

**Comment by aikar** [comment]
At first I was shocked you were using an interface like this, but I think I see why you are doing it and can't really object to it.

Yes this is a bug in Paper's ASM event handler. I surely can't fix this, so if you're able to use an abstract class for now, i would suggest that, until someone who knows the ASM system can do it.

However it might be an idea to solve this architecturally, as this is a questionable approach. 

I'm not going to say its bad, but you're not really saving any effort on just adding the @EventHandler to the implementing object and use the event object.

**Comment by zachbr** [comment]
Should be fixed in builds 1057+
