### ISSUE TITLE
Missing HandlerList for PlayerBucketEvent

### ISSUE THREAD

**Issue by Goldmensch** [PaperMC/Paper#6113]
### Expected behavior

Use the PlayerBucketEvent

### Observed/Actual behavior

Error in the console:
```
[18:01:35 ERROR]: Error occurred while enabling ChunkProtect v1.0-SNAPSHOT (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:720) ~[patched_1.17.1.jar:git-Paper-88]
at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:718) ~[patched_1.17.1.jar:git-Paper-88]
at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:657) ~[patched_1.17.1.jar:git-Paper-88]
at de.goldmensch.smartutils.plugin.SmartPlugin.registerListener(SmartPlugin.java:21) ~[?:?]
at de.goldmensch.chunkprotect.core.ChunkProtect.onEnable(ChunkProtect.java:39) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-88]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-88]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-88]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-88]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-88]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-88]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-88]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-88]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-88]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Steps/models to reproduce

Using the PlayerBucketEvent

### Plugin list

my own plugin that uses the event ;)

### Paper version

This server is running Paper version git-Paper-88 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 648f607)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
https://papermc.io/javadocs/paper/1.17/org/bukkit/event/player/PlayerBucketEvent.html

Use a subclass

**Comment by Goldmensch** [comment]
> https://papermc.io/javadocs/paper/1.17/org/bukkit/event/player/PlayerBucketEvent.html
> 
> Use a subclass

I used the `PlayerBucketEvent` like this:
```java
    @EventHandler
    public void handlePlayerBucket(PlayerBucketEvent event) {
        if(access(event.getPlayer(), event.getBlock().getChunk())) {
            event.setCancelled(true);
        }
    }
```
