### ISSUE TITLE
issue on login in 1.17.1

### ISSUE THREAD

**Issue by CloudeLecaw** [PaperMC/Paper#6118]
### Expected behavior

well i think login without any errors in console :)

### Observed/Actual behavior

After llogin a massive amoutn of spam (repeating onces= was produced

```
[19:17:23] [Craft Scheduler Thread - 39/WARN]: [CMI] Plugin CMI v9.0.0.8 generated an exception while executing task 26114
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:506) ~[patched_1.17.1.jar:git-Paper-88]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$KeyIterator.next(Object2ObjectOpenHashMap.java:728) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:434) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftMetaLeatherArmor.<init>(CraftMetaLeatherArmor.java:32) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:303) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:273) ~[patched_1.17.1.jar:git-Paper-88]
	at com.Zrips.CMI.Modules.Animations.AnimationManager.setColor(AnimationManager.java:256) ~[?:?]
	at com.Zrips.CMI.Modules.Animations.AnimationManager.access$2(AnimationManager.java:220) ~[?:?]
	at com.Zrips.CMI.Modules.Animations.AnimationManager$2.run(AnimationManager.java:212) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-88]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-88]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

> 

You can view the issue here if you want
https://github.com/Zrips/CMI/issues/5824

### Steps/models to reproduce

i loged in game with plugin CMI installed

i was asking the CMI dev first because the plugin itsPlugingam was inside.
Her answered 

> This looks more like a paper bug as its failing on basic item.getItemMeta() for leather armor which are set to biome type colors

### Plugin list

CMI 9.0.08
CMILIB 1.0.2.8

### Paper version

Paper 1.17.1 Build 88

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
Can you reproduce this on spigot as well?

**Comment by CloudeLecaw** [comment]
well ... i dont know why... but since my testserver crashed from it i cant reproduce it anymore even not with spigot or paper.

im totaly clueless now...

**Comment by CloudeLecaw** [comment]
fixed
