### ISSUE TITLE
PlayerBucketEvent error

### ISSUE THREAD

**Issue by Heppy-Prog** [PaperMC/Paper#6120]
### Expected behavior

no error by using this xD

### Observed/Actual behavior

 org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:720) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:718) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:657) ~[patched_1.17.1.jar:git-Paper-90]
	at de.rudolf.heppner.heppyskyblock.HeppySkyBlock.registerListeners(HeppySkyBlock.java:171) ~[?:?]
	at de.rudolf.heppner.heppyskyblock.HeppySkyBlock.onEnable(HeppySkyBlock.java:75) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-90]
	at java.lang.Thread.run(Thread.java:831) [?:?]

### Steps/models to reproduce

@EventHandler
    public void onPlayerBucket(PlayerBucketEvent e) {
        hb.sendMessage("Bukkit Event");
    }

### Plugin list

WorldEdit

### Paper version

 [20:25:12 INFO]: This server is running Paper version git-Paper-90 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bb44da8)
[20:25:13 INFO]: Debug logging is disabled
[20:25:13 INFO]: Server Ping Player Sample Count: 12
[20:25:13 INFO]: Using 4 threads for Netty based IO

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
You can't listen to that event

**Comment by Heppy-Prog** [comment]
> 
> 
> You can't listen to that event

i must have missed that, thanks for the information and sorry for the message.
