### ISSUE TITLE
Shutdown Exception: zip file closed on server shutdown

### ISSUE THREAD

**Issue by mirolm** [PaperMC/Paper#6137]
### Expected behavior

I expect server to shutdown normally. 

### Observed/Actual behavior

I use a pretty old plugin - zPermissions and when paper decided to change the MySQL odbc driver from version 5 to 8 this error started to happen on server shutdown. I tested with spigot where jdbc driver is still the old one and this does not happen.

[19:59:17] [Thread-6/WARN]: Shutdown Exception: zip file closed
[19:59:17] [Thread-6/WARN]: java.lang.IllegalStateException: zip file closed
[19:59:17] [Thread-6/WARN]:     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[19:59:17] [Thread-6/WARN]:     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[19:59:17] [Thread-6/WARN]:     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[19:59:17] [Thread-6/WARN]:     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[19:59:17] [Thread-6/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[19:59:17] [Thread-6/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[19:59:17] [Thread-6/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[19:59:17] [Thread-6/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[19:59:17] [Thread-6/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[19:59:17] [Thread-6/WARN]:     at com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue.createStatus(PooledConnectionQueue.java:125)

### Steps/models to reproduce

Test with spigot 1.17.1 - there mysql jdbc is still the old 5 version and the class is com.mysql.jdbc.Driver. When you shutdown the server is goes down without issues.

Test with paper 1.17.1 - there mysql jdbc is newer one 8 version and the class is com.mysql.cj.jdbc.Driver. When you shutdown the server the above exception is shown.

As the exception is shown only on server shutdown i do not think it is something critical or harmfull. Plugins that use mysql work as usual without issues.  

### Plugin list

Plugins (9): Vault, Essentials, FarmLimiter, LoginSecurity, EssentialsSpawn, EssentialsChat, zPermissions, ProtocolLib, ChangeSkin

### Paper version

This server is running Paper version git-Paper-95 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0aa0a1d)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
This has nothing to do with the SQL driver, whatever plugin that is coming from isn't clearing up after itself properly, and paper explicitly closes resources on reload/shutdown, whatever that's from is failing to shutdown properly
