### ISSUE TITLE
Be more specific if plugin.yml is empty

### ISSUE THREAD

**Issue by josephjthomas** [PaperMC/Paper#6176]
### Is your feature request related to a problem?

Not unless you know what you are looking for.

### Describe the solution you'd like.

If the plugin.yml is empty, you receive the following stacktrace:
```
[02:09:04 ERROR]: Could not load 'plugins\TestPlugin-1.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: null is not properly structured.
        at org.bukkit.plugin.PluginDescriptionFile.asMap(PluginDescriptionFile.java:1261) ~[patched_1.17.1.jar:git-Paper-99]
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:259) ~[patched_1.17.1.jar:git-Paper-99]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:183) ~[patched_1.17.1.jar:git-Paper-99]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.17.1.jar:git-Paper-99]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.17.1.jar:git-Paper-99]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.1.jar:git-Paper-99]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-99]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-99]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
It would be better to include that the file is empty.

### Describe alternatives you've considered.

None.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by e-im** [comment]
Thank you for the suggestion, however this is likely not something we are interested in adding at this time. While what you do get currently contains a lot more information and may be hard to read initially, it actually does tell you the exact issue in saying

> null is not properly structured.

If the file is missing, a more specific message will be given as well.
