### ISSUE TITLE
InventoryView#setProperty throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ItsSchatten** [PaperMC/Paper#6184]
### Expected behavior

If I was to open a brewing stand inventory I would be able to manipulate and animate the brew time, fuel amount, etc.

https://www.youtube.com/watch?v=vRxOgB673uw 
Expected result. 

### Observed/Actual behavior

The inventory is not updated and an error is thrown in console.

https://www.youtube.com/watch?v=g0K8d9fByaE
Actual result.

```
[18:00:12 WARN]: [test] Plugin test v1.0 generated an exception while executing task 1366
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.setData(AbstractContainerMenu.java:744) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.setWindowProperty(CraftPlayer.java:1756) ~[patched_1.17.1.jar:git-Paper-104]
	at org.bukkit.inventory.InventoryView.setProperty(InventoryView.java:446) ~[patched_1.17.1.jar:git-Paper-104]
	at com.itsschatten.test.TestMainClass$1.lambda$run$0(TestMainClass.java:45) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.itsschatten.test.TestMainClass$1.run(TestMainClass.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-104]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-104]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-104]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Steps/models to reproduce

_Tested with Spigot 1.17.1-R0.1-SNAPSHOT_
1. Open an Inventory that has adjustable values like a brewing stand or a furnace. 
2. _Not necessary_ Create a task timer with whatever time intervals you feel appropriate
3. Call InventoryView.setProperty(Property, value).
4. An error should be thrown in console and the inventory is not animated/updated.

Full code:
```
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (args.length == 1 && args[0].equalsIgnoreCase("kill")) {
            this.getServer().getScheduler().cancelTasks(this);
            getLogger().log(Level.INFO, "Cancelled all tasks.");
            return true;
        }
        if (sender instanceof Player player) {
            Inventory inventory = Bukkit.createInventory(player, InventoryType.BREWING, "Bukkit Test");
            player.openInventory(inventory);
            new BukkitRunnable() {
                int time = 0;

                @Override
                public void run() {
                    if (time > 30) {
                        getLogger().log(Level.INFO, "Reset time.");
                        time = 0;
                    }
                    inventory.getViewers().forEach((viewer) -> viewer.getOpenInventory().setProperty(InventoryView.Property.BREW_TIME, time));
                    time++;
                }
            }.runTaskTimerAsynchronously(this, 0, 0);
        }
```

### Plugin list

test; only purpose is to open a brewing inventory and attempt to set the brewing time.

### Paper version

This server is running Paper version git-Paper-104 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 377a60d)
You are running the latest version
Previous version: git-Paper-46 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by LemonCaramel** [comment]
This problem seems to be caused by patch [0289-Restore-custom-InventoryHolder-support.patch](https://github.com/PaperMC/Paper/blob/master/patches/server/0289-Restore-custom-InventoryHolder-support.patch). 
This is because there's no problem if the holder is null.
To solve this problem, I want to open PR, but I can't think of any other better way than remove this patch.
