### ISSUE TITLE
issue with WorldEdit //setbiome command

### ISSUE THREAD

**Issue by DenaryDev** [PaperMC/Paper#6205]
### Expected behavior

Changing the biome in the selected area

### Observed/Actual behavior

When I try to change the biome, this error appears:

`[21:25:30 INFO]: DenaryDev issued server command: //setbiome plains
[21:25:30 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.MinecraftKey.getNamespace()" because "minecraft" is null
at org.bukkit.craftbukkit.v1_17_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.17.1.jar:git-Paper-108]
at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:518) ~[patched_1.17.1.jar:git-Paper-108]
at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getBiome(CraftWorld.java:1118) ~[patched_1.17.1.jar:git-Paper-108]
at com.sk89q.worldedit.bukkit.BukkitWorld.getBiome(BukkitWorld.java:540) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.getBiome(WatchdogTickingExtent.java:114) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.getBiome(WatchdogTickingExtent.java:114) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.ChangeSetExtent.setBiome(ChangeSetExtent.java:71) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
at com.sk89q.worldedit.EditSession.setBiome(EditSession.java:676) ~[?:?]
at com.sk89q.worldedit.function.biome.BiomeReplace.apply(BiomeReplace.java:66) ~[?:?]
at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?]
at com.sk89q.worldedit.command.BiomeCommands.setBiome(BiomeCommands.java:181) ~[?:?]
at com.sk89q.worldedit.command.BiomeCommandsRegistration.cmd$_setbiome(BiomeCommandsRegistration.java:171) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-108]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-108]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2180) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1991) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1972) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-108]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-108]
at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-108]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-108]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-108]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-108]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-108]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-108]
at java.lang.Thread.run(Thread.java:831) [?:?]`

### Steps/models to reproduce

1. Select pos1 and pos2
2. Run //setbiome [any_biome]

### Plugin list

![image](https://user-images.githubusercontent.com/70901429/125990594-0d918baa-b376-44b0-bedb-4ca7f98c3475.png)

### Paper version

`[21:15:36 INFO]: Starting minecraft server version 1.17.1
[21:15:36 INFO]: Loading properties
[21:15:36 INFO]: This server is running Paper version git-Paper-108 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: a5acf36)
[21:15:36 INFO]: Debug logging is disabled`

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I am use the latest version of WorldEdit
I wrote to the developers of worledit, they said to write to you

**Comment by DereC4** [comment]
Happening with me too

**Comment by jeremyryanp** [comment]
I just had this happen on a server I launched and then added some mods to.
I noticed what should have been swamp was labeled as Ocean (using f3 to peep world details).

BUT looking at the biome data with NBTExplorer shows that it is actually a -1 for everything in that chunk. I imagine grabbing biome[-1] is going to break a lot of stuff.

**Comment by DenaryDev** [comment]
> I just had this happen on a server I launched and then added some mods to.
> I noticed what should have been swamp was labeled as Ocean (using f3 to peep world details).
> 
> BUT looking at the biome data with NBTExplorer shows that it is actually a -1 for everything in that chunk. I imagine grabbing biome[-1] is going to break a lot of stuff.

**Comment by DenaryDev** [comment]
Oops

**Comment by DenaryDev** [comment]
//setbiome works for spigot, but does not work on paper

**Comment by electronicboy** [comment]
This is a spigot issue and it's basically apparently down their changes borking biome data in the world with custom biomes, if you interact with unaffected biomes, it won't cause this error, but, if you interact with ones spigot has borked, it will

**Comment by DenaryDev** [comment]
This problem appears only if a Caves and Cliffs Preview datapack is installed on the server.

**Comment by Owen1212055** [comment]
Paper has since added [API](https://github.com/PaperMC/Paper/blob/master/patches/api/0391-Add-NamespacedKey-biome-methods.patch) in order to avoid using the enum for biomes until it's converted. Additionally, this issue has generally remained quiet so it's most likely that this issue was fixed by WorldEdit.

If you are still experiencing this issue, please feel free to comment and this can be reopened. 😄
