### ISSUE TITLE
[Incompatability/Bug] CMI with a MySQL/MariaDB setup.

### ISSUE THREAD

**Issue by Terminal-Access** [PaperMC/Paper#6225]
### Expected behavior

Database tabled to be created with out issues upon initial startup of the server once the option in CMI has been set to use a MySQL setup over sqlite.

Note: The Following is taken from a Spigot setup that i have been testing against to see if i could replicate this error.

```
[14:21:56] [Server thread/INFO]: [CMI] Enabling CMI v9.0.1.2
[14:21:57] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[14:21:57] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[14:21:57] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[14:21:57] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[14:21:57] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[14:21:57] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[14:21:57] [Server thread/INFO]: _______________________________________________________
[14:21:57] [Server thread/INFO]:   Integrating PaperSpigot async methods
[14:21:57] [Server thread/INFO]:   40 Enabled and 16 Disabled modules
[14:21:57] [Server thread/INFO]:   Initialized Cipher256 AES
[14:21:57] [Server thread/INFO]:   Loaded (56) regular alias into memory. Took 32ms
[14:21:57] [Server thread/INFO]:   Loaded (3) custom text's into memory. Took 2ms
[14:21:57] [Server thread/INFO]:   Detected Java16
[14:21:57] [Server thread/INFO]:   5.5.5-10.4.20-MariaDB data base type detected
[14:21:57] [Server thread/INFO]:   UserTable creating CREATE TABLE `CMI_users` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `player_uuid` text, `username` text, `nickname` text, `LogOutLocation` text, `DeathLocation` text, `TeleportLocation` text, `teleportToggled` boolean, `Homes` text, `LastLoginTime` bigint, `LastLogoffTime` bigint, `TotalPlayTime` bigint, `tFly` bigint, `tGod` bigint, `Glow` text, `Ips` text, `Cuffed` boolean, `AlertUntil` bigint, `AlertReason` text, `JoinedCounter` boolean, `LockedIps` text, `pTime` bigint, `Kits` text, `Charges` text, `Cooldowns` longtext, `Balance` double, `Notes` text, `Rank` text, `TagSound` boolean, `SignShiftEdit` boolean, `Spy` boolean, `CommandSpy` boolean, `BannedUntil` bigint, `BannedAt` bigint, `BannedBy` text, `BanReason` text, `Ignores` text, `Vanish` text, `Economy` text, `Mail` text, `FlightCharge` double, `UserMeta` text, `Flying` boolean, `Votifier` int, `Jail` text, `JailedUntil` bigint, `FakeAccount` boolean, `PlaytimeOptimized` bigint, `flightChargeEnabled` boolean, `noPayToggled` boolean, `JailReason` text, `Skin` text, `SignSpy` boolean, `Collision` boolean, `NamePrefix` text, `NameSuffix` text, `Warnings` text, `msgToggle` boolean, `NameColor` text, `Muted` text, `ToggleBBCompassOff` boolean, `AFRecharge` text, `DisplayName` text);
[14:21:57] [Server thread/INFO]:   CREATE TABLE `CMI_users` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `player_uuid` text, `username` text, `nickname` text, `LogOutLocation` text, `DeathLocation` text, `TeleportLocation` text, `teleportToggled` boolean, `Homes` text, `LastLoginTime` bigint, `LastLogoffTime` bigint, `TotalPlayTime` bigint, `tFly` bigint, `tGod` bigint, `Glow` text, `Ips` text, `Cuffed` boolean, `AlertUntil` bigint, `AlertReason` text, `JoinedCounter` boolean, `LockedIps` text, `pTime` bigint, `Kits` text, `Charges` text, `Cooldowns` longtext, `Balance` double, `Notes` text, `Rank` text, `TagSound` boolean, `SignShiftEdit` boolean, `Spy` boolean, `CommandSpy` boolean, `BannedUntil` bigint, `BannedAt` bigint, `BannedBy` text, `BanReason` text, `Ignores` text, `Vanish` text, `Economy` text, `Mail` text, `FlightCharge` double, `UserMeta` text, `Flying` boolean, `Votifier` int, `Jail` text, `JailedUntil` bigint, `FakeAccount` boolean, `PlaytimeOptimized` bigint, `flightChargeEnabled` boolean, `noPayToggled` boolean, `JailReason` text, `Skin` text, `SignSpy` boolean, `Collision` boolean, `NamePrefix` text, `NameSuffix` text, `Warnings` text, `msgToggle` boolean, `NameColor` text, `Muted` text, `ToggleBBCompassOff` boolean, `AFRecharge` text, `DisplayName` text);
[14:21:58] [Server thread/INFO]:   InvTable creating CREATE TABLE `CMI_inventories` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `player_id` int, `inventories` longtext);
[14:21:58] [Server thread/INFO]:   CREATE TABLE `CMI_inventories` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `player_id` int, `inventories` longtext);
[14:21:58] [Server thread/INFO]:   PlayTime creating CREATE TABLE `CMI_playtime` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `player_id` int, `date` int, `h0` bigint, `h1` bigint, `h2` bigint, `h3` bigint, `h4` bigint, `h5` bigint, `h6` bigint, `h7` bigint, `h8` bigint, `h9` bigint, `h10` bigint, `h11` bigint, `h12` bigint, `h13` bigint, `h14` bigint, `h15` bigint, `h16` bigint, `h17` bigint, `h18` bigint, `h19` bigint, `h20` bigint, `h21` bigint, `h22` bigint, `h23` bigint);
[14:21:58] [Server thread/INFO]:   CREATE TABLE `CMI_playtime` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `player_id` int, `date` int, `h0` bigint, `h1` bigint, `h2` bigint, `h3` bigint, `h4` bigint, `h5` bigint, `h6` bigint, `h7` bigint, `h8` bigint, `h9` bigint, `h10` bigint, `h11` bigint, `h12` bigint, `h13` bigint, `h14` bigint, `h15` bigint, `h16` bigint, `h17` bigint, `h18` bigint, `h19` bigint, `h20` bigint, `h21` bigint, `h22` bigint, `h23` bigint);
[14:21:59] [Server thread/INFO]:   PlayTimeReward creating CREATE TABLE `CMI_playtimereward` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `player_id` int, `repeatable` text, `onetime` text);
[14:21:59] [Server thread/INFO]:   CREATE TABLE `CMI_playtimereward` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `player_id` int, `repeatable` text, `onetime` text);
[14:21:59] [Server thread/INFO]:   Started MySQL data base. Took 1703ms
[14:21:59] [Server thread/INFO]:   Vault was not found, you will have limited economy support
[14:21:59] [Server thread/INFO]:   Loaded (5) warning categories into memory. Took 0ms
[14:21:59] [Server thread/INFO]:   Loaded (3) warning commands into memory. Took 0ms
[14:21:59] [Server thread/INFO]:   Loaded (134) custom mob heads into memory. Took 12ms
[14:21:59] [Server thread/INFO]:   Loaded (0) cooldowns into memory. Took 18ms
[14:21:59] [Server thread/INFO]:   Loaded (3) warmups into memory. Took 0ms
[14:21:59] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[14:22:02] [Server thread/INFO]:   Loaded (5) kits into memory. Took 2599ms
[14:22:02] [Server thread/INFO]:   Loaded (7) ranks into memory. Took 7ms
[14:22:02] [Server thread/INFO]:   Loaded (8) playtime rewards into memory. Took 2ms
[14:22:02] [Server thread/INFO]:   Loaded (0) player data into memory. Took 1ms
[14:22:02] [Server thread/INFO]:   Loaded (0) playtime records into memory. Took 1ms
[14:22:02] [Server thread/INFO]:   Loaded (0) playtime reward records into memory. Took 0ms
[14:22:02] [Server thread/INFO]:   Loaded (18) custom alias into memory. Took 4ms
[14:22:02] [Server thread/INFO]:   Loaded (1) interactive commands into memory. Took 1ms
[14:22:02] [Server thread/INFO]:   Registered events. Took 88ms
[14:22:02] [Server thread/INFO]:   Loaded (0) event action commands into memory. Took 3ms
[14:22:02] [Server thread/INFO]:   Updated (EN) language file. Took 81ms
[14:22:02] [Server thread/INFO]:   Loaded (859) worth values into memory. Took 13ms
[14:22:02] [Server thread/INFO]:   Starting world timer.
[14:22:02] [Server thread/INFO]:   Initializing world manager.
[14:22:02] [Server thread/INFO]:   Loaded (5) schedules into memory. Took 5ms
[14:22:02] [Server thread/INFO]:   Loaded GeoLiteCity
[14:22:02] [Server thread/INFO]:   Loaded (0) skin cache entries into memory. Took 1ms
[14:22:02] [Server thread/INFO]:   Version 9.0.1.2 has been enabled
[14:22:02] [Server thread/INFO]: ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
```

### Observed/Actual behavior

The following Error when CMI is attempting to create the datatables.

```
[13:58:10] [Server thread/INFO]: [CMI] Enabling CMI v9.0.1.2
[13:58:10] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[13:58:10] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[13:58:10] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[13:58:10] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[13:58:10] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[13:58:10] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[13:58:10] [Server thread/INFO]: _______________________________________________________
[13:58:10] [Server thread/INFO]:   Integrating PaperSpigot async methods
[13:58:10] [Server thread/INFO]:   40 Enabled and 16 Disabled modules
[13:58:10] [Server thread/INFO]:   Initialized Cipher256 AES
[13:58:10] [Server thread/INFO]:   Loaded (56) regular alias into memory. Took 32ms
[13:58:11] [Server thread/INFO]:   Loaded (3) custom text's into memory. Took 1ms
[13:58:11] [Server thread/INFO]:   Detected Java16
[13:58:11] [Server thread/INFO]:   5.5.5-10.4.20-MariaDB data base type detected
[13:58:12] [Server thread/INFO]:   Started MySQL data base. Took 1439ms
[13:58:12] [Server thread/INFO]:   Vault was not found, you will have limited economy support
[13:58:12] [Server thread/INFO]:   Loaded (5) warning categories into memory. Took 0ms
[13:58:12] [Server thread/INFO]:   Loaded (3) warning commands into memory. Took 0ms
[13:58:12] [Server thread/INFO]:   Loaded (134) custom mob heads into memory. Took 10ms
[13:58:12] [Server thread/INFO]:   Loaded (0) cooldowns into memory. Took 14ms
[13:58:12] [Server thread/INFO]:   Loaded (3) warmups into memory. Took 0ms
[13:58:12] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[13:58:15] [Server thread/INFO]:   Loaded (5) kits into memory. Took 2517ms
[13:58:15] [Server thread/INFO]:   Loaded (7) ranks into memory. Took 8ms
[13:58:15] [Server thread/INFO]:   Loaded (8) playtime rewards into memory. Took 1ms
[13:58:15] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table 'spigotdev.cmi_users' doesn't exist
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[13:58:15] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1207)
[13:58:15] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:585)
[13:58:15] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1486)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:58:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[13:58:15] [Server thread/INFO]:   Loaded (0) player data into memory. Took 5ms
[13:58:15] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table 'spigotdev.cmi_playtime' doesn't exist
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[13:58:15] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadPlayTimes(DBDAO.java:1231)
[13:58:15] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:608)
[13:58:15] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1486)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:58:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[13:58:15] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table 'spigotdev.cmi_playtimereward' doesn't exist
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[13:58:15] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[13:58:15] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadPlayerPlayTimeRewards(DBDAO.java:1365)
[13:58:15] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:609)
[13:58:15] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1486)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:58:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[13:58:15] [Server thread/INFO]:   Loaded (18) custom alias into memory. Took 3ms
[13:58:15] [Server thread/INFO]:   Loaded (1) interactive commands into memory. Took 1ms
[13:58:15] [Server thread/INFO]:   Registered events. Took 111ms
[13:58:15] [Server thread/INFO]:   Loaded (0) event action commands into memory. Took 3ms
[13:58:15] [Server thread/INFO]:   Updated (EN) language file. Took 83ms
[13:58:15] [Server thread/INFO]:   Loaded (859) worth values into memory. Took 11ms
[13:58:15] [Server thread/INFO]:   Starting world timer.
[13:58:15] [Server thread/INFO]:   Initializing world manager.
[13:58:15] [Server thread/INFO]:   Loaded (5) schedules into memory. Took 4ms
[13:58:15] [Server thread/INFO]:   Loaded GeoLiteCity
[13:58:15] [Server thread/INFO]:   Loaded (0) skin cache entries into memory. Took 1ms
[13:58:15] [Server thread/INFO]:   Version 9.0.1.2 has been enabled
[13:58:15] [Server thread/INFO]: ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
```

### Steps/models to reproduce

Note: I am using MariaDB version stated below is taken directly from CMI's console output.

`[13:41:01] [Server thread/INFO]:   5.5.5-10.4.20-MariaDB data base type detected`

- Create a fresh install of PaperMC.
  - run the server to generate default configs.
- Shutdown the server.

- Download and place both in to the "plugins" folder. 
  - CMI Version: 9.0.1.2
  - CMILib Version: 1.0.2.13
    - Run the server to generate default plugin configs.
 - Shutdown the server.
 
- Edit the file "dataBaseInfo.yml" in "plugins\CMI" folder.
  - Change "method:" from "sqlite to "MySQL" (case sensitive).
  - Fill out the "mysql:" section specifying the correct details of your MySQL/MariaDB setup.
  - Leave all other settings default and save the config file.
 - Start the server and wait for CMI to report the following error via a stack trace.
 

-  java.sql.SQLSyntaxErrorException: Table 'warpedportalsdev.cmi_users' doesn't exist

- Check your MySQL/MariaDB database to see that no tables have been created.

### Plugin list

- CMI-9.0.1.2
- CMILib-1.0.2.13
- LuckPerms-Bukkit-5.3.47 (Have tested with out LP and the issue remains.)

### Paper version

Affected versions: 

- paper-1.17.1-90 through paper-1.17.1-112

> [13:31:10] [Server thread/INFO]: This server is running Paper version git-Paper-112 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bc127ea)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Please find the origional report here on the CMI Issues board.
> https://github.com/Zrips/CMI/issues/5876

**Please Note:**
This appears to be an incompatability issue with PaperMC and CMI, as i have tested the same setup with the very latest version of spigot and this issue dose not happen.

> Spigot Versio tested against ([13:25:27] [Server thread/INFO]: This server is running CraftBukkit version 3187-Spigot-d03d7f1-b8c522d (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT))

**Comment by Proximyst** [comment]
Not a Paper issue. The plugin doesn't ensure schemas actually exist.

**Comment by Terminal-Access** [comment]
**Update**
Not sure whay this happens with PaperMC and not spigot but here's my findings. (ill be reporting this back over at CMI also)
If you happen to be running an existing database that has CMI alredy setup, and then attempt to setup a second instance of CMI but running on a sepperate dataabse, the plugin's schema lookup dosent will find that the table exist but dosent take in to accoutn they are for a different database and there for will skip the creation method and attempt to write to those "existing tables" that dosent acctually exist in the second database you trying to setup, and have supplied credentails for..

> Not a Paper issue. The plugin doesn't ensure schemas actually exist.

So yes with theis updated information, initially this is not a PaperMC issue, it's down to how CMI are doing schema lookups,  however PaperMC is causing somet hing fnky to happen as again i do not have this issue when using Spigot.

when using a spigot jar, the table are created every time with out fail.

**Comment by Proximyst** [comment]
I find that highly unlikely, and I can't help you whatsoever as my totally legitimately obtained copy of CMI does not support 1.17. Sorry for the inconvenience 🤷🏻‍♀️ We might however still be of help on [our Discord server](https://discord.gg/papermc) in `#paper-help`.

**Comment by Terminal-Access** [comment]
> I find that highly unlikely, and I can't help you whatsoever as my totally legitimately obtained copy of CMI does not support 1.17. Sorry for the inconvenience 🤷🏻‍♀️ We might however still be of help on [our Discord server](https://discord.gg/papermc) in `#paper-help`.

Please dont assume i have Ilegaly obtained a 1.17 copy of CMI,  Just so you are aware you are under the incorrect assumption that CMI currently dosent support 1.17, Infact it does the CMI Team have releaced a version, that is avaliable on the spigot website that supports 1.17

CMI Version 9.0.0.8 - Updatel Log - [Jul 7, 2021]:
> Updated to support 1.17.1

We are now on Version: 9.0.1.2

I suggest that you get your facts correct before making the assumption and then accusing a person (however indirectly) of pirating software.

**Comment by Proximyst** [comment]
> > I find that highly unlikely, and I can't help you whatsoever as my totally legitimately obtained copy of CMI does not support 1.17. Sorry for the inconvenience 🤷🏻‍♀️ We might however still be of help on [our Discord server](https://discord.gg/papermc) in `#paper-help`.
> 
> Please dont assume i have Ilegaly obtained a 1.17 copy of CMI, Just so you are aware you are under the incorrect assumption that CMI currently dosent support 1.17, Infact it does the CMI Team have releaced a version, that is avaliable on the spigot website that supports 1.17
> 
> CMI Version 9.0.0.8 - Updatel Log - [Jul 7, 2021]:
> 
> > Updated to support 1.17.1
> 
> We are now on Version: 9.0.1.2
> 
> I suggest that you get your facts correct before making the assumption and then accusing a person (however indirectly) of pirating software.

I was alluding to my own copy not being purchased lol
