### ISSUE TITLE
Crash bukkit, Java WARN and UUID of added entity already exists

### ISSUE THREAD

**Issue by winker2204** [PaperMC/Paper#6311]
### Stack trace

**crash-2021-08-01_23.56.02-server.txt**

Description: Exception in server tick loop

java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:800)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1345)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:687)
	at app//net.minecraft.util.thread.ProcessorMailbox.registerForExecution(ProcessorMailbox.java:127)
	at app//net.minecraft.util.thread.ProcessorMailbox.tell(ProcessorMailbox.java:121)
	at app//net.minecraft.server.level.ThreadedLevelLightEngine.tryScheduleUpdate(ThreadedLevelLightEngine.java:324)
	at app//net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1072)
	at app//net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:662)
	at app//net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336)
	at app//net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320)
	at app//net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110)
	at app//net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:1274)
	at app//net.minecraft.server.MinecraftServer.loadSpawn(MinecraftServer.java:815)
	at app//net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:620)
	at app//net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306)
	at app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126)
	at app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
	at java.base/java.lang.Thread.run(Thread.java:831)

-----------------------------------------------------------------------------------------------------------------------------
**Java WARN**

02.08 03:20:03 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityPlayer
02.08 03:20:03 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
02.08 03:20:03 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
02.08 03:20:03 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
02.08 03:20:03 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
02.08 03:20:03 [Server] WARN at java.base/java.lang.Class.forName(Class.java:375)
02.08 03:20:03 [Server] WARN at com.nickuc.openlogin.bukkit.reflection.ReflectionUtils.getNSNMS(ReflectionUtils.java:29)
02.08 03:20:03 [Server] WARN at com.nickuc.openlogin.bukkit.reflection.packets.Packet.<clinit>(Packet.java:27)
02.08 03:20:03 [Server] WARN at com.nickuc.openlogin.bukkit.listeners.PlayerJoinListeners.onPlayerJoin(PlayerJoinListeners.java:64)
02.08 03:20:03 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source)
02.08 03:20:03 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
02.08 03:20:03 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
02.08 03:20:03 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
02.08 03:20:03 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
02.08 03:20:03 [Server] WARN at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359)
02.08 03:20:03 [Server] WARN at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301)
02.08 03:20:03 [Server] WARN at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:307)
02.08 03:20:03 [Server] WARN at net.minecraft.network.NetworkManager.a(NetworkManager.java:399)
02.08 03:20:03 [Server] WARN at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:196)
02.08 03:20:03 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1578)
02.08 03:20:03 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
02.08 03:20:03 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
02.08 03:20:03 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
02.08 03:20:03 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
02.08 03:20:03 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)

---------------------------------------------------------------------------------------------------------------------------------------
**WARN UUID**

02.08 12:39:59 [Server] WARN UUID of added entity already exists: EntityCow['Cow'/2126, uuid='6c8f44c9-b5f6-42fb-b574-b27820fa8f08', l='ServerLevel[world]', x=289.40, y=71.00, z=-74.55, cpos=[18, -5], tl=360530, v=false, rR=null]

### Plugin list

- WorldGuard
- WorldEdit
- TAB
- sleep-most
- SkinsRestorer
- Shopkeepers
- SetSpawn
- ProtocolLib
- PlayerKits
- PlaceholderAPI
- OpeNLogin
- LuckPerms
- LevelledMobs
- HubParkour
- HolographicDisplays
- Essentials
- CommandPanels
- Citizens
- bStats
- BeautyQuests

### Paper version

This server is running Paper version git-Paper-151 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6e7f9aa)
You are running the latest version
Previous version: git-Paper-119 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
> unable to create native thread: possibly out of memory or process/resource limits reached

you hit the systems resource limits, if self hosted ptero, see the wings config for the pid limit, otherwise, speak to your host or check your systems config
