### ISSUE TITLE
force-gamemode, and adding/removing effects inside of a PlayerGameModeChangeEvent causes stacktrace

### ISSUE THREAD

**Issue by ohowe1** [PaperMC/Paper#6319]
### Expected behavior

- Player logs out in different game mode than the forced one
- Player logs in
- Player now in forced game mode and the listener does what it needs to do

### Observed/Actual behavior

- Player logs out in different game mode than the forced one
- Player logs in
- Player now in forced game mode but a stacktrace is in console and if two effect operations were ordered only the first works
```java
@EventHandler
public void onGameModeChange(@NotNull PlayerGameModeChangeEvent event) {
    // Only absorption added
    event.getPlayer().addPotionEffect(new PotionEffect(PotionEffectType.ABSORPTION, 100, 100));
    event.getPlayer().addPotionEffect(new PotionEffect(PotionEffectType.BLINDNESS, 100, 100));
}
```
Error message:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.PlayerConnection.sendPacket(net.minecraft.network.protocol.Packet)" because "this.b" is null
        at net.minecraft.server.level.ServerPlayer.onEffectAdded(ServerPlayer.java:1728) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1118) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1084) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:427) ~[patched_1.17.1.jar:git-Paper-154]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:422) ~[patched_1.17.1.jar:git-Paper-154]
        at me.ohowe.gamemodechange.GameModeChangeListener.onGameModeChange(GameModeChangeListener.java:21) ~[gamemodechange-1.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-154]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-154]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-154]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-154]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.17.1.jar:git-Paper-154]
        at net.minecraft.server.level.ServerPlayer.loadGameTypes(ServerPlayer.java:2192) ~[app:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:262) ~[patched_1.17.1.jar:git-Paper-154]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:217) ~[app:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:199) ~[app:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:87) ~[app:?]
        at net.minecraft.network.Connection.tick(Connection.java:394) ~[app:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:196) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[patched_1.17.1.jar:git-Paper-154]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-154]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-154]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-154]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-154]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Steps/models to reproduce

Video: [YouTube link](https://youtu.be/tO99L4gdbKw)
Plugin: [GitHub link](https://github.com/carelesshippo/GameModeChange)

### Plugin list

- Custom plugin to test game mode change listener. [GitHub link here](https://github.com/carelesshippo/GameModeChange)

### Paper version

[12:18:53 INFO]: Checking version, please wait...
[12:18:53 INFO]: This server is running Paper version git-Paper-154 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9a74e70)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This is not a problem with spigot as spigot does not even call the listener on `force-gamemode` (which is still a problem but not the same one). If any other information is required please let me know.

**Comment by electronicboy** [comment]
issue here is that you're setting data on a player before they're even added to the world

**Comment by ohowe1** [comment]
> 
> 
> issue here is that you're setting data on a player before they're even added to the world

Yes, that is the issue. I don't think that the event should fire before they are added to the world.

**Comment by electronicboy** [comment]
Not viable as it stands, that would imply that either we just don't fire the event, or, we change the entire behaviour of where the event fires which has a lot of other side-effects

**Comment by Machine-Maker** [comment]
I think the only time this is the case is if the cause is `DEFAULT_GAMEMODE`. All other causes should only happen once the player has been added. 

Can probably add a note saying this to prevent mis-use of this event.

**Comment by Machine-Maker** [comment]
So the proper way to check for this would be making sure the player was online through `Player#isOnline`.
