### ISSUE TITLE
Some Error :|

### ISSUE THREAD

**Issue by Executioner1376** [PaperMC/Paper#632]
[04:04:13] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v6.1.3-SNAPSHOT;c904242
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot.jar:git-Paper-1063]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.teleport(CraftPlayer.java:571) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.teleport(CraftEntity.java:255) [PaperSpigot.jar:git-Paper-1063]
	at net.notfab.hubbasics.modules.JoinTeleport.onPlayerConnect(JoinTeleport.java:52) [HubBasics.jar:7]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) [PaperSpigot.jar:git-Paper-1063]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:352) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:178) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:153) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [PaperSpigot.jar:git-Paper-1063]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:222) ~[?:?]
	at com.sk89q.worldguard.bukkit.RegionQuery.getApplicableRegions(RegionQuery.java:94) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerTeleport(WorldGuardPlayerListener.java:361) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor720.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot.jar:git-Paper-1063]
	... 24 more
[04:04:13] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PlotSquared v3.5.0-SNAPSHOT-95f8aaa
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot.jar:git-Paper-1063]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.teleport(CraftPlayer.java:571) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.teleport(CraftEntity.java:255) [PaperSpigot.jar:git-Paper-1063]
	at net.notfab.hubbasics.modules.JoinTeleport.onPlayerConnect(JoinTeleport.java:52) [HubBasics.jar:7]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) [PaperSpigot.jar:git-Paper-1063]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:352) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:178) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:153) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [PaperSpigot.jar:git-Paper-1063]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.plotsquared.bukkit.util.BukkitUtil.getLocation(BukkitUtil.java:74) ~[?:?]
	at com.plotsquared.bukkit.listeners.PlayerEvents.playerMove(PlayerEvents.java:493) ~[?:?]
	at com.plotsquared.bukkit.listeners.PlayerEvents.onTeleport(PlayerEvents.java:479) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor127.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot.jar:git-Paper-1063]
	... 24 more
[04:04:13] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Core v2.5.0-SNAPSHOT-b725
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot.jar:git-Paper-1063]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.teleport(CraftPlayer.java:571) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.teleport(CraftEntity.java:255) [PaperSpigot.jar:git-Paper-1063]
	at net.notfab.hubbasics.modules.JoinTeleport.onPlayerConnect(JoinTeleport.java:52) [HubBasics.jar:7]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) [PaperSpigot.jar:git-Paper-1063]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:352) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:178) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:153) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [PaperSpigot.jar:git-Paper-1063]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:178) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor928.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot.jar:git-Paper-1063]
	... 24 more
[04:04:13] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Portals v2.5.0-SNAPSHOT-b748
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot.jar:git-Paper-1063]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.teleport(CraftPlayer.java:571) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.teleport(CraftEntity.java:255) [PaperSpigot.jar:git-Paper-1063]
	at net.notfab.hubbasics.modules.JoinTeleport.onPlayerConnect(JoinTeleport.java:52) [HubBasics.jar:7]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) [PaperSpigot.jar:git-Paper-1063]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:352) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:178) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:153) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [PaperSpigot.jar:git-Paper-1063]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.onarandombox.MultiversePortals.utils.PortalManager.getPortal(PortalManager.java:105) ~[?:?]
	at com.onarandombox.MultiversePortals.PortalPlayerSession.playerDidTeleport(PortalPlayerSession.java:224) ~[?:?]
	at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerTeleport(MVPPlayerListener.java:63) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor949.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot.jar:git-Paper-1063]
	... 24 more
[04:04:13] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to HubBasics v5.0-DEVELOPMENT
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot.jar:git-Paper-1063]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:352) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:178) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:153) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [PaperSpigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [PaperSpigot.jar:git-Paper-1063]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.teleport(CraftPlayer.java:587) ~[PaperSpigot.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.teleport(CraftEntity.java:255) ~[PaperSpigot.jar:git-Paper-1063]
	at net.notfab.hubbasics.modules.JoinTeleport.onPlayerConnect(JoinTeleport.java:52) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot.jar:git-Paper-1063]
	... 15 more

Hi This Is My Problem How We Can Fix This 
I Must Luck My Hub World On Firstspawn
How I Can Lock /hub or Spawn For Joining Server I Use Plugins And Not Working Now I Have This Problems
I Use 89 Plugins

**Comment by Executioner1376** [comment]
[latest.txt](https://github.com/PaperMC/Paper/files/846385/latest.txt)
My LogFile :X Tnx For Help

**Comment by prplz** [comment]
Hey, you shouldn't be posting issues here unless they are certainly caused by Paper.

**Comment by Executioner1376** [comment]
So what to do and where to get help from who?

**Comment by AlfieC** [comment]
This is approaching the 5th time you've used this issue tracker for an issue which has nothing to do with Paper. Please stop.

**Comment by mikroskeem** [comment]
Please, people. Learn to read.

> `Could not pass event PlayerTeleportEvent to WorldGuard`

How similiar is word "WorldGuard" to "Paper"? It isn't similiar at all, no?

Maybe [this link](http://bfy.tw/Af7j) helps you next time with similiar issue.
