### ISSUE TITLE
A problem with AsyncWorldEdit

### ISSUE THREAD

**Issue by Homi74** [PaperMC/Paper#6320]
### Expected behavior

Standard plugin startup

### Observed/Actual behavior

[21:47:55 ERROR]: Could not load 'plugins/AsyncWorldEdit-3.9.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.1.jar:git-Paper-154]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Paper-154]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Paper-154]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:404) ~[patched_1.17.1.jar:git-Paper-154]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.1.jar:git-Paper-154]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-154]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-154]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.setPlugin(ClassLoaderHelper.java:192) ~[AsyncWorldEdit-3.9.1.jar:?]
at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.cleanPlugin(ClassLoaderHelper.java:200) ~[AsyncWorldEdit-3.9.1.jar:?]
at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:99) ~[AsyncWorldEdit-3.9.1.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:466) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.1.jar:git-Paper-154]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Paper-154]

### Steps/models to reproduce

Downgrade, last working build paper-1.17.1-145

### Plugin list

[21:48:22 INFO]: Plugins (6): PluginManager, ProtocolLib, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

### Paper version

[21:54:55 INFO]: This server is running Paper version git-Paper-154 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9a74e70)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
We do not provide support around premium plugins, nor is there any info for us to really go off there

**Comment by Homi74** [comment]
> 
> 
> We do not provide support around premium plugins, nor is there any info for us to really go off there

Great, here is the free version https://github.com/SBPrime/AsyncWorldEdit/releases
which also doesn't work with the latest build of paper

**Comment by electronicboy** [comment]
the notation of a free version existing does not change our stance on this, we don't have the time to start running through issues of other peoples code as-is, especially not people who are generally paid for this

**Comment by Homi74** [comment]
> the notation of a free version existing does not change our stance on this, we don't have the time to start running through issues of other peoples code as-is, especially not people who are generally paid for this

In that case, I apologize for daring to ask, I was advised to contact here first before contacting the plugin author.

Have a nice rest of the evening.
