### ISSUE TITLE
Different name for method MinecraftServer#getLoottableRegistry on Paper

### ISSUE THREAD

**Issue by NichtStudioCode** [PaperMC/Paper#6367]
### Expected behavior

The method should exist under the name getLoottableRegistry, just like in normal spigot.

### Observed/Actual behavior

The method is called getLoottables

### Steps/models to reproduce

Install [Nova ](https://www.spigotmc.org/resources/93648/) on a paper server and place the auto fisher (requires water, power, fishing rod). This will throw a NoSuchMethodError as the method for getting the LoottableRegistry has a dfiferent name on paper.

### Plugin list

Nova: https://www.spigotmc.org/resources/93648/

### Paper version

This server is running Paper version git-Paper-167 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bfb3d42)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by jpenilla** [comment]
Please provide the stacktrace containing the NoSuchMethodError

**Comment by NichtStudioCode** [comment]
```
java.lang.NoSuchMethodError: 'net.minecraft.world.level.storage.loot.LootTableRegistry net.minecraft.server.dedicated.DedicatedServer.getLootTableRegistry()'
        at xyz.xenondevs.nova.tileentity.impl.agriculture.AutoFisher.fish(AutoFisher.kt:120) ~[Nova-0.4.1-shaded(1).jar:?]
        at xyz.xenondevs.nova.tileentity.impl.agriculture.AutoFisher.handleTick(AutoFisher.kt:90) ~[Nova-0.4.1-shaded(1).jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$4.invoke(TileEntityManager.kt:73) ~[Nova-0.4.1-shaded(1).jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$4.invoke(TileEntityManager.kt:73) ~[Nova-0.4.1-shaded(1).jar:?]
        at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTaskTimer$lambda-2(SchedulerUtils.kt:13) ~[Nova-0.4.1-shaded(1).jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-167]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-167]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
