### ISSUE TITLE
GSON not working

### ISSUE THREAD

**Issue by mowmowkittycat** [PaperMC/Paper#6370]
### Expected behavior

GSON should work because it is bundled with Bukkit, but it just gives me errors
```java
[23:05:29 ERROR]: Could not pass event PlayerQuitEvent to GenEyed v1.0
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.Object java.lang.ref.Reference.referent accessible: module java.base does not "opens java.lang.ref" to unnamed module @a4102b8
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:157) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.toJson(Gson.java:661) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.toJson(Gson.java:648) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.toJson(Gson.java:623) ~[patched_1.17.1.jar:git-Paper-137]
	at com.currupt.geneyed.GenEyed.SaveData(GenEyed.java:45) ~[?:?]
	at com.currupt.geneyed.Events.LeaveEvent(Events.java:18) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-137]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:606) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:591) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1875) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1855) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:566) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:216) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-137]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Observed/Actual behavior

```java
[23:05:29 ERROR]: Could not pass event PlayerQuitEvent to GenEyed v1.0
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.Object java.lang.ref.Reference.referent accessible: module java.base does not "opens java.lang.ref" to unnamed module @a4102b8
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:157) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.toJson(Gson.java:661) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.toJson(Gson.java:648) ~[patched_1.17.1.jar:git-Paper-137]
	at com.google.gson.Gson.toJson(Gson.java:623) ~[patched_1.17.1.jar:git-Paper-137]
	at com.currupt.geneyed.GenEyed.SaveData(GenEyed.java:45) ~[?:?]
	at com.currupt.geneyed.Events.LeaveEvent(Events.java:18) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-137]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:606) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:591) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1875) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1855) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:566) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:216) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-137]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
Gives this error

### Steps/models to reproduce

Use GSON

### Plugin list

My own plugin that uses GSON

### Paper version

This server is running Paper version git-Paper-137 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: a67959e)
You are 32 version(s) behind

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
Just commenting on this dichotomy
- [x] I am running the latest version of Paper available from papermc.io/downloads. 

> You are 32 version(s) behind

**Comment by electronicboy** [comment]
The version of gson bundled in the server is outdated, your class is designed in a way which this basically breaks, we basically need to look if it's safe to update gson (do they follow semver? er)

**Comment by mowmowkittycat** [comment]
> 
> 
> Just commenting on this dichotomy
> 
>     * [x]  I am running the latest version of Paper available from papermc.io/downloads.
> 
> 
> > You are 32 version(s) behind

Just tested on latest paper version, It gives same error.

**Comment by Machine-Maker** [comment]
> Just tested on latest paper version, It gives same error.

That's why it was just a comment on the fact that you checked a box saying something clearly not true, not a solution to your issue. See [electronicboy's comment](https://github.com/PaperMC/Paper/issues/6370#issuecomment-895715541)

**Comment by mowmowkittycat** [comment]
> semver? er

yea, they follow semver.
Latest version is 2.8.7

**Comment by mowmowkittycat** [comment]
```xml
        <!-- bundled with Minecraft, should be kept in sync -->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.0</version>
            <scope>compile</scope>
        <dependency>
 ```
 Bukkit's GSON Version is 4 years old

**Comment by Machine-Maker** [comment]
~~Bukkit~~Mojang's GSON Version is 4 years old

**Comment by mowmowkittycat** [comment]
yeaaaaaaaa

**Comment by giqnt** [comment]
same issue, please update.. ;-;

**Comment by electronicboy** [comment]
I did the compliance check nobody cared to do and it actually looks doable, but, I mean, if this is something you actually care about, you'd be much better off shading and relocating gson, especially if you care about more than just the latest version of paper

**Comment by NotMyFault** [comment]
As of 21w42a (Snapshots for 1.18), Mojang provides gson v2.8.8.

**Comment by John-H-Smith** [comment]
Same problem still here, server is running on
`git-Paper-64 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: b475c6a)`
and I compiled with the latest maven repo for 1.18-R0.1-SNAPSHOT.
Stacktrace:
```
[19:09:51 WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.Object java.lang.ref.Reference.referent accessible: module java.base does not "opens java.lang.ref" to unnamed module @5f20ad45
[19:09:51 WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
[19:09:51 WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[19:09:51 WARN]: 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
[19:09:51 WARN]: 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
[19:09:51 WARN]: 	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
[19:09:51 WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
[19:09:51 WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
[19:09:51 WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:458)
[19:09:51 WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
[19:09:51 WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
[19:09:51 WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
[19:09:51 WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:458)
[19:09:51 WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
[19:09:51 WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
[19:09:51 WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
[19:09:51 WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:458)
[19:09:51 WARN]: 	at com.google.gson.Gson.toJson(Gson.java:696)
[19:09:51 WARN]: 	at com.google.gson.Gson.toJson(Gson.java:683)
[19:09:51 WARN]: 	at com.google.gson.Gson.toJson(Gson.java:638)
[19:09:51 WARN]: 	at com.google.gson.Gson.toJson(Gson.java:618)
```
Any help?
