### ISSUE TITLE
shutdown server freeze

### ISSUE THREAD

**Issue by jassyel** [PaperMC/Paper#6438]
### Stack trace

```
[04:00:28] [Server thread/INFO]: Saving players
[04:00:28] [Server thread/INFO]: Saving worlds
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[NWLobby]'/minecraft:overworld
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[NWLobby_nether]'/minecraft:the_nether
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[NWLobby_the_end]'/minecraft:the_end
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Ceres]'/minecraft:ceres
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Marte]'/minecraft:marte
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Venus]'/minecraft:venus
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Urano]'/minecraft:urano
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[space]'/minecraft:space
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mercurio]'/minecraft:mercurio
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[arenasbb]'/minecraft:arenasbb
[04:00:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:survival
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[BuildBattle-Lobby]'/minecraft:buildbattle-lobby
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[dungeons]'/minecraft:dungeons
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[IridiumSkyblock]'/minecraft:iridiumskyblock
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[IridiumSkyblock_nether]'/minecraft:iridiumskyblock_nether
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival_nether]'/minecraft:survival_nether
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[arenastnt]'/minecraft:arenastnt
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival_the_end]'/minecraft:survival_the_end
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Ciudad]'/minecraft:ciudad
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[IridiumSkyblock_the_end]'/minecraft:iridiumskyblock_the_end
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Eventos]'/minecraft:eventos
[04:00:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mob-Arenas]'/minecraft:mob-arenas
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (NWLobby): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (Ceres): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (Marte): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (Venus): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (Urano): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (space): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (Mercurio): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (arenasbb): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (Survival): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (BuildBattle-Lobby): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (dungeons): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (IridiumSkyblock): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (arenastnt): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (Ciudad): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (Eventos): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (Mob-Arenas): All chunks are saved
[04:00:29] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[04:00:29] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.longs.LongArrayList.getLong(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:669) ~[patched_1.17.1.jar:git-Paper-196]
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:755) ~[patched_1.17.1.jar:git-Paper-196]
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:751) ~[patched_1.17.1.jar:git-Paper-196]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.h(PersistentEntitySectionManager.java:285) ~[patched_1.17.1.jar:git-Paper-196]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.c(PersistentEntitySectionManager.java:308) ~[patched_1.17.1.jar:git-Paper-196]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.close(PersistentEntitySectionManager.java:325) ~[patched_1.17.1.jar:git-Paper-196]
	at net.minecraft.server.level.WorldServer.close(WorldServer.java:2067) ~[patched_1.17.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:992) ~[patched_1.17.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:806) ~[patched_1.17.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1238) ~[patched_1.17.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Plugin list

AdvancedChests, AdvancedDevelopmentLibrary, AdvancedEnchantments, ajStartCommands*, AnimatedScoreboard, Aurora, BambooCollisionFix, BanItem, BedrockPlayerManager, BetterCrafts, BetterRTP, BKCommonLib, BuildBattle, ChatManager, Citizens, Clans, ClientDetector*, CMILib, CommandButtons, ConsoleSpamFix, DeathChestPro, DeathMessages, DiscordSRV, EliteMobs, EpicPluginLib, Essentials, EssentialsGeoIP, EssentialsSpawn, FancyBags, FastAsyncWorldEdit (WorldEdit), floodgate, FloodgatePlaceholders, ForcePack, Geyser-Spigot, GSit, GUIShop, HolographicDisplays, HolographicExtension, IllegalStack, Images, Iris, Jobs, LibsDisguises, LPC, LuckPerms, MagicalEvents, MCGStarCraft, MiniMOTD, MobArena, MoneyFromMobs, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MVdWPlaceholderAPI*, MyCommand, MythicMobs, NBTAPI, NoChunkLag, OldCombatMechanics, PlaceholderAPI, PlayerKits, PlayMoreSounds, PlotSquared, ProtectionStones, ProtocolLib, PureTpa, ServerRestart, SuggestionBlocker*, TAB, TNTRun_reloaded, UltimateShops, UltimateTNT, Vault, VoidGen, VoidSpawn, Voting, WarpSystem, Wind, WorldBorder, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known)

when many players are online, then use /stop or /restart
server freeze

### Paper version

Paper-196

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
Is this reproducible without plugins? This sounds like a plugin is modifying it improperly.

**Comment by jassyel** [comment]
> Is this reproducible without plugins? This sounds like a plugin is modifying it improperly.

I tried to reproduce it without plugins, the error persists but not always, it is too strange, apparently the error appears when there are many players online and I type /restart

**Comment by jassyel** [comment]
> Is this reproducible without plugins? This sounds like a plugin is modifying it improperly.

I tried to reproduce it without plugins, the error persists but not always, it is too strange, apparently the error appears when there are many players online and I type /restart

**Comment by e-im** [comment]
This has been mitigated, leave a comment if you are still experiencing this issue.
