### ISSUE TITLE
Mobs despawn when going through portal due to CB ticking all worlds

### ISSUE THREAD

**Issue by Krinios** [PaperMC/Paper#6456]
### Expected behavior

I expected a wither skeleton to come through the nether portal 

### Observed/Actual behavior

So I went to the farm and a wither skeleton spawned, so I saw it went into the nether portal and I followed it after going through the nether portal the wither skeleton was not found idk where it went

### Steps/models to reproduce

this is the wither skeleton farm that I'm using
https://www.youtube.com/watch?v=VL7HkV4y3Uo&t=684s

### Plugin list

No plugins I made a new server and just dragged the world folder into to test the farm

### Paper version

1.17.1 #196 latest

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by imDaniX** [comment]
> So I went to the farm and a wither skeleton spawned, so I saw it went into the nether portal and I followed it after going through the nether portal the wither skeleton was not found idk where it went

Did you test with anyone on the other end? I think skeletons just despawn.

**Comment by e-im** [comment]
Yes, it is more than likely that the skeletons just despawned. Please ensure you are close enough to the skeletons, or try with another user around. In addition, check your `despawn-ranges` in paper.yml. They are in blocks.

**Comment by e-im** [comment]
To recap conversation on discord apparently the wither skeletons will despawn when they go through the portal, behaviour that does not persist on vanilla or spigot. I haven't looked at this yet at all, but re-opening for the author until that is done.

**Comment by ghost** [comment]
It is also happening on spigot, however functions as intended on vanilla.

**Comment by e-im** [comment]
caused by https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/server/level/WorldServer.patch?at=9ed7e4fbe4c0cd2076a52d65a9ea8ae810d0e176#123-132 / https://github.com/Byteflux/CraftBukkit/commit/671a2893f42a66ce1e966369ce2212c4df9953eb. I haven't fully evaluated the possible ramifications of reverting this. but seems safeish? Keeping behaviour from 1.2.5 is a bit...

**Comment by Alex1337F** [comment]
Any updates on this?

**Comment by NBS-Paste** [comment]
I'm using a chunk loader plugin and they still despawn.

**Comment by SRK7Kyros** [comment]
Do we have any update? Isn't it just a matter of editing a few lines of code?

**Comment by NBS-Paste** [comment]
What lines would I have to change? Also how would I change them and what to? I don’t know  how to code in Java.

**Comment by theo2354** [comment]
> caused by https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/server/level/WorldServer.patch?at=9ed7e4fbe4c0cd2076a52d65a9ea8ae810d0e176#123-132 / [Byteflux/CraftBukkit@671a289](https://github.com/Byteflux/CraftBukkit/commit/671a2893f42a66ce1e966369ce2212c4df9953eb). I haven't fully evaluated the possible ramifications of reverting this. but seems safeish? Keeping behaviour from 1.2.5 is a bit...

Hello, any update on this? This bug seems to prevent any mob to pass a portal, which is the basic concept of almost all most efficitent farms in the game, as it takes the mobs out of the mob cap.

Looking at the link you sent, it seems like the variable `flag` is always true, which is a bit weird for a variable used in an `if` right after that.

**Comment by electronicboy** [comment]
If there's players in the other dimension that's not a bug, that's 100% how
mojang programmed it, all of those types of farms are designed for single
player

**Comment by NBS-Paste** [comment]
So there has to only be one person on the server?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EterNityCH** [comment]
yes @NBS-Paste as @electronicboy mentioned, that's indeed the Vanilla behavior there.

This question has been asked many times in paper-help Discord and my friend Kyle has made a simple plugin that allow entity to exist for an extended period of time without player within range,

https://bitbucket.org/otherside-plugin/otherside/src/master/

The source code can be vided on that page and this "should" make most portal farm works (given that the entity is then transported back relatively quickly)

I hope this helps you <3

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/pull/9025 - removes the override for the empty worlds, this ofc will not fix issues purely brought on by the fact that many farms are designed for single player servers (embedded/external)

**Comment by Vuntorion** [comment]
> yes @NBS-Paste as @electronicboy mentioned, that's indeed the Vanilla behavior there.
> 
> This question has been asked many times in paper-help Discord and my friend Kyle has made a simple plugin that allow entity to exist for an extended period of time without player within range,
> 
> https://hangar.papermc.io/Kyle/Otherside/
> 
> The source code can be viewed publicly and this "should" make most portal farm works (given that the entity is then transported back relatively quickly)
> 
> I hope this helps you <3

a year later, but this works great, thanks!!

**Comment by ghost** [comment]
I am experiencing weird behaviour similar to this on my folia server (though I believe that the root cause comes from paper). With farms that involve nether portal travel they seem to require everyone in the same dimension (farm built in the overworld needs everyone in the overworld). 

I have attempted to use the plugin suggested to see results but it does not supporting folia. I did override on the folia support but it fails to enable:

```
[Server thread/ERROR]: Error occurred while enabling Otherside v1.1 (Is it up to date?)
java.lang.UnsupportedOperationException: null
at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:517) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at org.bukkit.scheduler.BukkitRunnable.runTaskTimer(BukkitRunnable.java:117) ~[folia-api-1.21.8-R0.1-SNAPSHOT.jar:?]
at otherside-1.1.jar/dev.kqmvs2.otherside.Otherside.onEnable(Otherside.java:27) ~[otherside-1.1.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280) ~[folia-api-1.21.8-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[folia-api-1.21.8-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:785) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:353) ~[folia-1.21.8.jar:1.21.8-5-7a1c5c7]
```

Are there any other things I can explore or is this maybe a separate issue?
