### ISSUE TITLE
"Cound not schedule mailbox" when stopping the server

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#6532]
### Expected behavior

No exception

### Observed/Actual behavior

> stop
[22:20:09 INFO]: Stopping the server
[22:20:09 INFO]: Stopping server
[22:20:09 INFO]: Saving players
[22:20:09 INFO]: Saving worlds
[22:20:09 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[22:20:09 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[22:20:09 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[22:20:09 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:20:09 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:20:09 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:20:09 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[22:20:09 INFO]: Flushing Chunk IO
[22:20:10 INFO]: Closing Thread Pool
> [22:20:10 ERROR]: Cound not schedule mailbox
java.util.concurrent.RejectedExecutionException: Task sorter 2 false rejected from java.util.concurrent.ThreadPoolExecutor@53812d8d[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 56534]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357) ~[?:?]
        at net.minecraft.util.thread.ThreadedMailbox.h(ThreadedMailbox.java:130) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:121) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.server.level.ChunkTaskQueueSorter.a(ChunkTaskQueueSorter.java:142) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.server.level.ChunkTaskQueueSorter.lambda$pollTask$15(ChunkTaskQueueSorter.java:150) ~[patched_1.17.1.jar:git-Paper-233]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143) ~[?:?]
        at net.minecraft.util.thread.Mailbox$1.a(Mailbox.java:44) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.server.level.ChunkTaskQueueSorter.lambda$message$1(ChunkTaskQueueSorter.java:59) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.util.thread.ThreadedMailbox.g(ThreadedMailbox.java:87) [patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:141) [patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96) [patched_1.17.1.jar:git-Paper-233]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[22:20:10 INFO]: Closing Server

### Steps/models to reproduce

I just stopped the server by using the stop command.

### Plugin list

none

### Paper version

[22:23:35 INFO]: This server is running Paper version git-Paper-233 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2cd4bcf)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I was using the official caves and cliffs datapack from https://feedback.minecraft.net/hc/en-us/articles/4402614709389-Caves-Cliffs-Prototype-Data-Pack-for-Minecraft-Java-Edition

**Comment by e-im** [comment]
2973e1c56e52d28f259b25d685deb59fa3a3fe1f
