### ISSUE TITLE
Can't edit BlockState

### ISSUE THREAD

**Issue by gommzystudio** [PaperMC/Paper#6581]
### Expected behavior

I want to change the inventory of a chest block.

### Observed/Actual behavior

[13:30:19 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getHandle()" because "this.world" is null
[13:30:19 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getWorldHandle(CraftBlockState.java:69)
[13:30:19 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.CraftChest.getInventory(CraftChest.java:45)
[13:30:19 WARN]:        at bloodland.jar//de.gommzy.bloodland.BloodSurfaceGenerator.generateTreasure(BloodSurfaceGenerator.java:212)
[13:30:19 WARN]:        at bloodland.jar//de.gommzy.bloodland.BloodSurfaceGenerator.decorate(BloodSurfaceGenerator.java:108)
[13:30:19 WARN]:        at WorldGeneratorApi-1.2.2-bukkit.jar//nl.rutgerkok.worldgeneratorapi.internal.WorldDecoratorImpl.spawnCustomDecorations(WorldDecoratorImpl.java:198)
[13:30:19 WARN]:        at WorldGeneratorApi-1.2.2-bukkit.jar//nl.rutgerkok.worldgeneratorapi.internal.WorldDecoratorImpl.generate(WorldDecoratorImpl.java:75)
[13:30:19 WARN]:        at WorldGeneratorApi-1.2.2-bukkit.jar//nl.rutgerkok.worldgeneratorapi.internal.bukkitoverrides.InjectedChunkGenerator.addDecorations(InjectedChunkGenerator.java:180)
[13:30:19 WARN]:        at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$10(ChunkStatus.java:93)
[13:30:19 WARN]:        at net.minecraft.world.level.chunk.ChunkStatus.a(ChunkStatus.java:212)
[13:30:19 WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$37(PlayerChunkMap.java:1315)
[13:30:19 WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[13:30:19 WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$39(PlayerChunkMap.java:1313)
[13:30:19 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
[13:30:19 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[13:30:19 WARN]:        at net.minecraft.server.level.ChunkTaskQueueSorter.lambda$message$1(ChunkTaskQueueSorter.java:58)
[13:30:19 WARN]:        at net.minecraft.util.thread.ThreadedMailbox.g(ThreadedMailbox.java:87)
[13:30:19 WARN]:        at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:141)
[13:30:19 WARN]:        at net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96)
[13:30:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[13:30:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[13:30:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

### Steps/models to reproduce

Chest chest = (Chest) Bukkit.getWorld("world").getBlockAt(x,y,z).getState();
chest.getInventory().setItem(0,new ItemStack(Material.REDSTONE, 1)); //Error happens here

### Plugin list

Only one own plugin

### Paper version

This server is running Paper version git-Paper-255 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c3d5018)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
You're not supposed to access the world directly during generation, use the limited region which should be exposed to you, beyond that, your plugin is running in an environment in which some of the chunk gen related stuff has been hijacked by another plugin
