### ISSUE TITLE
Server crashes after a few hours reporting IO issues

### ISSUE THREAD

**Issue by Spomyx** [PaperMC/Paper#6585]
### Stack trace

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Paper RegionFile IO Thread"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "IO-Worker-101"
2021-09-09 22:00:34,485 Log4j2-AsyncAppenderEventDispatcher-1-Async ERROR Unable to write to stream logs/latest.log for appender File org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to RandomAccessFile logs/latest.log
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.writeToDestination(RollingRandomAccessFileManager.java:142)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:283)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.flush(RollingRandomAccessFileManager.java:164)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:251)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:84)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:84)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatch(AsyncAppenderEventDispatcher.java:119)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:81)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)
Caused by: java.io.IOException: Input/output error
        at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
        at java.base/java.io.RandomAccessFile.write(Unknown Source)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.writeToDestination(RollingRandomAccessFileManager.java:138)
        ... 23 more

2021-09-09 22:00:34,487 Log4j2-AsyncAppenderEventDispatcher-1-Async ERROR An exception occurred processing Appender File org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to RandomAccessFile logs/latest.log
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.writeToDestination(RollingRandomAccessFileManager.java:142)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:283)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.flush(RollingRandomAccessFileManager.java:164)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:251)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:84)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:84)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatch(AsyncAppenderEventDispatcher.java:119)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:81)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)
Caused by: java.io.IOException: Input/output error
        at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
        at java.base/java.io.RandomAccessFile.write(Unknown Source)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.writeToDestination(RollingRandomAccessFileManager.java:138)
        ... 23 more

and

[22:12:16 FATAL]: Failed to read chunk data for task: Task for world: 'world' at -53,32 poi: false, hash: 1777310071
java.io.IOException: Stale file handle
at sun.nio.ch.FileDispatcherImpl.pread0(Native Method) ~[?:?]
at sun.nio.ch.FileDispatcherImpl.pread(Unknown Source) ~[?:?]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:?]
at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:?]
at sun.nio.ch.FileChannelImpl.readInternal(Unknown Source) ~[?:?]
at sun.nio.ch.FileChannelImpl.read(Unknown Source) ~[?:?]
at net.minecraft.world.level.chunk.storage.RegionFile.a(RegionFile.java:594) ~[patched_1.17.1.jar:git-Paper-251]
at net.minecraft.world.level.chunk.storage.RegionFileCache.read(RegionFileCache.java:200) ~[patched_1.17.1.jar:git-Paper-251]
at net.minecraft.world.level.chunk.storage.RegionFileCache.read(RegionFileCache.java:192) ~[patched_1.17.1.jar:git-Paper-251]
at net.minecraft.world.level.chunk.storage.IChunkLoader.read(IChunkLoader.java:116) ~[patched_1.17.1.jar:git-Paper-251]
at net.minecraft.server.level.PlayerChunkMap.read(PlayerChunkMap.java:1680) ~[patched_1.17.1.jar:git-Paper-251]
at net.minecraft.server.level.WorldServer$2.readData(WorldServer.java:344) ~[patched_1.17.1.jar:git-Paper-251]
at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508) [patched_1.17.1.jar:git-Paper-251]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) [patched_1.17.1.jar:git-Paper-251]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) [patched_1.17.1.jar:git-Paper-251]

### Plugin list

none

### Actions to reproduce (if known)

happens after 2-3 hours of running server
storage is a NFS share

### Paper version

This server is running Paper version git-Paper-257 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8a2b23a)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
https://stackoverflow.com/questions/20105260/what-does-stale-file-handle-in-linux-mean
two-second google points to this, which, given the other log error, sounds like something else started running in the folder and deleting files or something weird

**Comment by Spomyx** [comment]
Hi,
yes i googled it too and i understand what state file handle means. The reason why i opened an issue here is that i'm confident nothing else is running in the folder. It is a dedicated network share specifically deployed for my minecraft installation.

I use similar dedicated shares for many software and paperMC is the only one thronwing IO issues. I was expecting help in order to determine if the error is due to a software incompatibility with network shares as i couldn't find recommandations on that point

**Comment by electronicboy** [comment]
Your error sounds nothingly inhereint to paper itself, nor is using network stores guaranteed to be stable with vanilla, it just wasn't ever wrote with them in mind, so incompat issues with the FS are really not something we have the will/means to dive into

The errors sound like something deleted a file when it wasn't expected, beyond that, you're basically on an unsupported setup
