### ISSUE TITLE
RuntimeException: An internal error occured (CME)

### ISSUE THREAD

**Issue by sionzee** [PaperMC/Paper#666]
Bug Name: **ConcurrentModificationException** when handling packet
Description: When player join to the server. Player is kicked with '**Internal server error**'
Version: git-Paper-**1081** (1.11.2-R0.1-SNAPSHOT)
Timings/plugins: [Aikar.co](https://timings.aikar.co/?id=ce36dbbda5a04859a58007842e84717f)

Stacktrace: 
`[16:19:09 INFO]: UUID of player radim111 is 9cb3f7a8-23ae-35ba-aadc-bd3b6ff6456f
[16:19:09 WARN]: Failed to handle packet for /178.77.244.58:59314
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_121]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_121]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:141) ~[?:1.8.0_121]
	at java.util.ArrayList.addAll(ArrayList.java:577) ~[?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.PacketPlayOutScoreboardTeam.(PacketPlayOutScoreboardTeam.java:46) ~[patched_1.11.2.jar:git-Paper-1081]
	at net.minecraft.server.v1_11_R1.PlayerList.sendScoreboard(PlayerList.java:249) ~[patched_1.11.2.jar:git-Paper-1081]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:162) ~[patched_1.11.2.jar:git-Paper-1081]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:121) ~[?:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:115) ~[?:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:74) ~[?:?]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.F_(SpigotLoginListenerPlay.java:67) ~[?:?]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) ~[patched_1.11.2.jar:git-Paper-1081]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.11.2.jar:git-Paper-1081]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925) [patched_1.11.2.jar:git-Paper-1081]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1081]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1081]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1081]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[16:19:10 INFO]: radim111 lost connection: Internal server error`

**Comment by electronicboy** [comment]
replicate without plugins

**Comment by sionzee** [comment]
Anyway, if is it due to plugin, there is missing exception for this.

**Comment by electronicboy** [comment]
Capturing every single case where a plugin does something stupid and modifies the server from another thread would be tedious, harmful to performance and in general a ballache. We can't replace every single collection on the server with something that would scream when a plugin tries to perform an operation async.

**Comment by IceString3** [comment]
It looks like the problem comes from ProtocolSupport and a player is likely joining with a Minecraft version which is glitchy (like 1.9.1)

**Comment by zachbr** [comment]
Nothing Paper can do about this, seek support with the plugin author.
