### ISSUE TITLE
Stacktraces while loading a world

### ISSUE THREAD

**Issue by Vlammar** [PaperMC/Paper#7066]
### Stack trace

```
[13:22:13 ERROR]: No key placement in MapLike[{config:{state_provider:{state:{Name:"minecraft:hay_block",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:block_pile"}]; No key feature in MapLike[{config:{state_provider:{state:{Name:"minecraft:hay_block",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:block_pile"}]
[13:22:13 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.jar:git-Paper-61]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.jar:git-Paper-61]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:790) ~[?:?]        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:363) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[paper-1.18.jar:git-Paper-61]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.jar:git-Paper-61]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.jar:git-Paper-61]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.jar:git-Paper-61]
```

### Plugin and Datapack List

ImageOnMap 
Luckperms
spark
VoteBanRevamped
VoxelSniper

### Actions to reproduce (if known)

Launch the server with a 1.17 world.

### Paper version

This server is running Paper version git-Paper-61 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 0e91b6a)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-266 (MC: 1.17.1)

### Other

There are multiples errors that are pretty similar but with different blocks affected.

**Comment by HexedHero** [comment]
"Harmless" vanilla issue
https://bugs.mojang.com/browse/MC-227945
