### ISSUE TITLE
NoSuchMethodError while reloading/loading config

### ISSUE THREAD

**Issue by IzzelAliz** [PaperMC/Paper#729]
Paper dev 1109 (MC 1.12)
When reload config or something, it will give you a NoSuchMethodError, it occured in many plugins, like QuickShop and Jobs Reborn.
StackTrace
`[13:43:00 WARN]: Unexpected exception while parsing console command "jobs reload
"org.bukkit.command.CommandException: Unhandled exception executing command jobs
 in plugin Jobs v3.9.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[pat
ched_1.12.jar:git-Paper-1109]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:15
1) ~[patched_1.12.jar:git-Paper-1109]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServ
er.java:669) ~[patched_1.12.jar:git-Paper-1109]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(Cra
ftServer.java:632) [patched_1.12.jar:git-Paper-1109]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java
:447) [patched_1.12.jar:git-Paper-1109]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
410) [patched_1.12.jar:git-Paper-1109]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
763) [patched_1.12.jar:git-Paper-1109]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:661) [patched_1.12.jar:git-Paper-1109]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfig
uration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/Y
amlConfiguration;
        at com.gamingmesh.jobs.config.YmlMaker.reloadConfig(YmlMaker.java:57) ~[
?:?]
        at com.gamingmesh.jobs.config.YmlMaker.getConfig(YmlMaker.java:76) ~[?:?
]
        at com.gamingmesh.jobs.i18n.Language.reload(Language.java:41) ~[?:?]
        at com.gamingmesh.jobs.Jobs.reload(Jobs.java:555) ~[?:?]
        at com.gamingmesh.jobs.commands.list.reload.perform(reload.java:17) ~[?:
?]
        at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java
:97) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[pat
ched_1.12.jar:git-Paper-1109]
        ... 8 more`
Thx for fixing!

**Comment by 0-x-2-2** [comment]
the plugin is outdated.
