### ISSUE TITLE
Error PlayerJoinEvent any ideas?

### ISSUE THREAD

**Issue by LogGits** [PaperMC/Paper#734]
Got an error on player join:
`java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;`

`Could not pass event PlayerJoinEvent to SimpleWarnings v1.0
Console 12/06/2017 16:03:03
16:03:03java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at me.odium.simplewarnings.PlayerListener.onPlayerJoin(PlayerListener.java:56) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor93.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1111]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1111]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1111]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1111]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:367) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:180) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:165) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:202) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:934) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:409) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.12.jar:git-Paper-1111]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.12.jar:git-Paper-1111]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

**Comment by electronicboy** [comment]
Plugin is outdated and uses a method inside bukkit that has since been updated

**Comment by LogGits** [comment]
Ok thanks i will close this.
