### ISSUE TITLE
MyPet Dev Build 2.3 NoClassDefFoundError: org/fusesource/jansi/Ansi

### ISSUE THREAD

**Issue by IzzelAliz** [PaperMC/Paper#735]
This error never occured while using previous 1.12 version paper.
`[19:53:04] [Server thread/INFO]: [MyPet] Loading MyPet v2.3.0
[19:53:04] [Server thread/ERROR]: org/fusesource/jansi/Ansi initializing MyPet v2.3.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/fusesource/jansi/Ansi
	at de.Keyle.MyPet.util.logger.MyPetLogger.<init>(MyPetLogger.java:50) ~[?:?]
	at de.Keyle.MyPet.MyPetPlugin.replaceLogger(MyPetPlugin.java:581) ~[?:?]
	at de.Keyle.MyPet.MyPetPlugin.onLoad(MyPetPlugin.java:102) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:216) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.Ansi
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.12.jar:git-Paper-1121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.jar:git-Paper-1121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	... 7 more`

**Comment by Black-Hole** [comment]
Same issue as https://github.com/PaperMC/Paper/issues/733
Ask the author of MyPet to not depend on internal console classes.
