### ISSUE TITLE
Console cyrillic input support?

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#736]
Paper buid №1121 or newer seems that does not support Cyrillic input.

I'm using Windows 8.1 x64, Java 1.8 x64.
Server is running via cmd.exe without custom codepage.
If I'm type "тест", in console it's always appears as "╤В╨╡╤Б╤В".

Initial discussion: https://github.com/PaperMC/Paper/pull/728#pullrequestreview-43427556

**Comment by stephan-gh** [comment]
It works without problems on Linux but I can reproduce a similar problem on Windows. Unlike for you it just prints `?` for all the characters though. Additionally, the same happens for all older Paper builds as well.

It's probably an encoding problem in JLine but I'm not quite sure how all of that works on Windows.

Can you paste the output of running `chcp` in your Windows command prompt?

**Comment by molor** [comment]
@Minecrell, Active code page: 866

**Comment by Black-Hole** [comment]
You could try to run "chcp 65001" before starting the server.

**Comment by molor** [comment]
> chcp 65001
```
Loading libraries, please wait...
2017-06-12 19:36:29,739 main ERROR Unable to inject fields into builder class for plugin type class org.apache.logging.log4j.core.appender.ConsoleAppender, element Console. java.nio.charset.UnsupportedCharsetException: cp65001
        at java.nio.charset.Charset.forName(Unknown Source)
        at org.apache.logging.log4j.util.PropertiesUtil.getCharsetProperty(PropertiesUtil.java:146)
        at org.apache.logging.log4j.util.PropertiesUtil.getCharsetProperty(PropertiesUtil.java:134)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Target.getCharset(ConsoleAppender.java:85)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Target$1.getDefaultCharset(ConsoleAppender.java:71)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Builder.build(ConsoleAppender.java:218)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Builder.build(ConsoleAppender.java:185)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
        at net.minecraft.server.v1_12_R1.MinecraftServer.<clinit>(MinecraftServer.java:55)
        at org.bukkit.craftbukkit.Main.main(Main.java:220)

2017-06-12 19:36:29,749 main ERROR Unable to invoke factory method in class clas
s org.apache.logging.log4j.core.appender.ConsoleAppender for element Console. java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.ConsoleAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:224)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:130)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
        at net.minecraft.server.v1_12_R1.MinecraftServer.<clinit>(MinecraftServer.java:55)
        at org.bukkit.craftbukkit.Main.main(Main.java:220)

2017-06-12 19:36:30,132 main ERROR Null object returned for Console in Appenders.
2017-06-12 19:36:30,140 main ERROR Unable to locate appender "WINDOWS_COMPAT" for logger config "root"
```

**Comment by molor** [comment]
Now, instead of cyrillic displayed ���������

**Comment by electronicboy** [comment]
Java doesn't support the unicode codepage,  does `chcp 855` produce any difference? I just woke up, so would have to take a look, but windows poor support for unicode could be a "fun" problem here

**Comment by zachbr** [comment]
I was testing chcp 1251 earlier to see if it helped and while I could now paste cyrillic characters, they seemed to get garbled by the time they entered ingame chat.

This could be something that needs to be handled at a system level by Windows, currently spinning up a VM to test.

**Comment by molor** [comment]
> does chcp 855 produce any difference?

Same problem..
![11](https://user-images.githubusercontent.com/19989717/27048271-d36b60c4-4fb3-11e7-9937-6d07e5b323c3.png)

**Comment by zachbr** [comment]
I can't even get it working on builds before all of the input and logging changes, tested against build 1112 on a fresh install of Windows 10, both with English/US region and language, as well as Russian region and language selected.

All input is always coming across as ?????.

**Comment by stephan-gh** [comment]
I'm pretty sure this is an issue in JLine, so I've opened https://github.com/jline/jline3/issues/133

**Comment by crevice** [comment]
try
-Dlog4j.configurationFile=log4j2.xml -Dfile.encoding=CP866 -jar spigot.jar 
in your server strart script

**Comment by zachbr** [comment]
@Minecrell did you ever look into what we need to do to use the jline fixes that have been committed? Is there anything we need to do or is it all handled by your implementation?

**Comment by stephan-gh** [comment]
@Zbob750 You'd need to update to the JLine snapshot version because there is no new release yet. I don't think we need any additional changes in Paper.

**Comment by zachbr** [comment]
Thanks, in retrospect I should've known that :(

For now, we will wait on the next Jline release. If this issue becomes more problematic or affects additional users we can reconsider waiting.
