### ISSUE TITLE
Server crush: TimingsHistory.java

### ISSUE THREAD

**Issue by enlyow** [PaperMC/Paper#744]
PaperSpigot 1104 (1.11.2)

```
[09:24:10] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:117) ~[spigot.jar:git-Paper-1104]
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:1) ~[spigot.jar:git-Paper-1104]
	at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:102) ~[spigot.jar:git-Paper-1104]
	at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) ~[spigot.jar:git-Paper-1104]
	at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:73) ~[spigot.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:824) ~[spigot.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [spigot.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[09:24:10] [Server thread/ERROR]: This crash report has been saved to: /home/roleplay/./crash-reports/crash-2017-06-14_09.24.10-server.txt
```

https://pastebin.com/wLFJQNzM

**Comment by aikar** [comment]
Looks like you have a corrupted chunk. One of your tile entities returned null on something it shouldn't have.

Try running a region fixer?

**Comment by enlyow** [comment]
Its not a corrupted chunk. I'm try it.

**Comment by zachbr** [comment]
Corrupted or not, this is should be caught by timings and presented in a friendlier way.

**Comment by enlyow** [comment]
So what to do with this error? The server shuts down after it.

**Comment by enlyow** [comment]
Will you fix it?

**Comment by zachbr** [comment]
While this is still an issue with your map, Timings will properly warn you and then ignore these entities as of builds 1141+
