### ISSUE TITLE
I keep getting this in crash reports all of a sudden:

### ISSUE THREAD

**Issue by CheatSupport** [PaperMC/Paper#790]
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.server.v1_8_R3.LoginListener.d(LoginListener.java:155)
	at net.minecraft.server.v1_8_R3.LoginListener.a(LoginListener.java:151)
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:312)
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Black-Hole** [comment]
1.8.8 isn't supported anymore, please update to 1.12
