### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#81]
What happened here?

```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    at net.minecraft.server.v1_9_R1.EntityTracker.untrackEntity(EntityTracker.java:157)
    at net.minecraft.server.v1_9_R1.WorldManager.b(WorldManager.java:26)
    at net.minecraft.server.v1_9_R1.World.c(World.java:1040)
    at net.minecraft.server.v1_9_R1.WorldServer.c(WorldServer.java:1168)
    at net.minecraft.server.v1_9_R1.World.kill(World.java:1075)
    at net.minecraft.server.v1_9_R1.PlayerList.disconnect(PlayerList.java:424)
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1060)
    at net.minecraft.server.v1_9_R1.NetworkManager.handleDisconnection(NetworkManager.java:315)
    at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:175)
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:876)
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714)
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Techcable** [comment]
Plugins?

**Comment by hurrgurl** [comment]
Mostly vanilla, have some custom coded stuff (mostly performance improvement) not exactly sure what to look for. First crash in a very long time. That was the entire crash log.

**Comment by zachbr** [comment]
How often are you seeing this issue? Update to latest and keep us apprised please.

**Comment by hurrgurl** [comment]
Only happened once.

**Comment by zachbr** [comment]
If it happens again we'll re-open this ticket.
