### ISSUE TITLE
ArrayIndexOutOfBoundsException - Possible Item Duping?

### ISSUE THREAD

**Issue by Platinteufel** [PaperMC/Paper#865]
**Paper 1167** (not the latest one, I know - but after the fixes of 1.12 dupe bugs)

I've noticed that one of my players had a lot of diamonds and I'm thinking about a possible duplication bug. Now I found some interesting parts in console: The player uses `/craft` (this should be an essentials command) and after some seconds there's an exception in console:

```
[...] issued server command: /craft
[13:54:15] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:47) [patched_1.12.jar:git-Paper-1167]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [patched_1.12.jar:git-Paper-1167]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1167]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1167]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1167]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[?:1.8.0_101]
    at net.minecraft.server.v1_12_R1.NonNullList.get(SourceFile:44) ~[patched_1.12.jar:git-Paper-1167]
    at net.minecraft.server.v1_12_R1.PlayerInventory.getItem(PlayerInventory.java:568) ~[patched_1.12.jar:git-Paper-1167]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2044) ~[patched_1.12.jar:git-Paper-1167]
    at net.minecraft.server.v1_12_R1.PacketPlayInAutoRecipe.a(SourceFile:77) ~[patched_1.12.jar:git-Paper-1167]
    at net.minecraft.server.v1_12_R1.PacketPlayInAutoRecipe.a(SourceFile:11) ~[patched_1.12.jar:git-Paper-1167]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.jar:git-Paper-1167]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.jar:git-Paper-1167]
    ... 5 more
```

Maybe some of you could tell me if this could be a reason for item duping? Thank you in advance!

**Comment by mikroskeem** [comment]
Just asking - why are you sitting on 1.12 instead of updating to 1.12.1?

**Comment by Platinteufel** [comment]
I'll update tonight and see if it will fix this issue.

**Comment by mikroskeem** [comment]
Any update on this?

**Comment by Platinteufel** [comment]
Seems to be fine now.  :)
