### ISSUE TITLE
/version Issue/Error after applying 1500/1501 (Went from 1499 to 1501

### ISSUE THREAD

**Issue by CDAGaming** [PaperMC/Paper#877]
### Issue Info:
`
[03:26:17 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ci.destroystokyo.com/job/PaperSpigot/lastSuccessfulBuild/buildNumber
[03:26:17 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
[03:26:17 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[03:26:17 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[03:26:17 WARN]:        at java.net.URL.openStream(URL.java:1045)
[03:26:17 WARN]:        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[03:26:17 WARN]:        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
[03:26:17 WARN]:        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:107)
[03:26:17 WARN]:        at org.bukkit.command.defaults.VersionCommand.getFromJenkins(VersionCommand.java:275)
[03:26:17 WARN]:        at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:248)
[03:26:17 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:196)
[03:26:17 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$0(VersionCommand.java:191)
[03:26:17 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:181)
[03:26:17 WARN]:        at java.lang.Thread.run(Thread.java:748)
`
### Paper build number:
This server is running Paper version git-Paper-1201 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
### What behavior is expected:
/version to correctly check if there is a new version
### What behavior is observed:
See Issue Info Section

**Comment by dignissimus** [comment]
is it still not working for you? I'm getting HTTP 200 for  https://ci.destroystokyo.com/job/PaperSpigot/lastSuccessfulBuild/buildNumber

**Comment by zachbr** [comment]
I tested this about 10 minutes after you posted this issue (last night, my time) and it was all up and working. I wonder if CloudFlare didn't have a hiccup.

**Comment by CDAGaming** [comment]
I'll check again when I'm home, might've been a small hiccup on Cloudflare end

**Comment by CDAGaming** [comment]
Yea, forgot to close this, and yes it was fixed
