### ISSUE TITLE
1.12.2 server crash (Failed to load data for block entity mine craft:sign)

### ISSUE THREAD

**Issue by zedwick** [PaperMC/Paper#886]
# Crash, Stacktrace

### Link/paste of stack trace

Two slightly different errors, but they seem very much related.

```
[15:41:08] [Server thread/ERROR]: Failed to load data for block entity minecraft:sign
java.lang.NullPointerException: null
        at net.minecraft.server.v1_12_R1.TileEntitySign$1.C_(TileEntitySign.java:63) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.ChatComponentScore.a(SourceFile:38) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.ChatComponentUtils.filterForDisplay(SourceFile:37) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.ChatComponentUtils.filterForDisplay(SourceFile:65) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.TileEntitySign.load(TileEntitySign.java:90) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.TileEntity.create(TileEntity.java:90) [patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:47) [patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) [patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:16) [patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:270) [patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.CraftChunk.getTileEntities(CraftChunk.java:111) [patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:121) [patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:1) [patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:108) [patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) [patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:73) [patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:828) [patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1205]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[15:41:08] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.$ava:27) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.$ava:11) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<in$t>(CraftBlockEntityState.java:27) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSig$.java:16) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(Craft$lock.java:270) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.CraftChunk.getTileEntities(Craf$Chunk.java:111) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:121) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:1) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:108) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:73) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:828) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1205]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

```
[15:56:43] [Server thread/ERROR]: Failed to load data for block entity minecraft:sign
java.lang.NullPointerException: null
        at net.minecraft.server.v1_12_R1.TileEntitySign$1.C_(TileEntitySig$.java:63) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.PlayerSelector.a(SourceFile:200) $[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.PlayerSelector.getPlayers(SourceF$le:146) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.ChatComponentUtils.filterForDispl$y(SourceFile:21) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.ChatComponentUtils.filterForDispl$y(SourceFile:65) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.TileEntitySign.load(TileEntitySig$.java:90) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.TileEntity.create(TileEntity.java$90) [patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.cre$teSnapshot(CraftBlockEntityState.java:47) [patched_1.12.2.jar:git-Paper-12$5]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<in$t>(CraftBlockEntityState.java:26) [patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSig$.java:16) [patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(Craft$lock.java:270) [patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.CraftChunk.getTileEntities(Craf$Chunk.java:111) [patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:121) $patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:1) [p$tched_1.12.2.jar:git-Paper-1205]
        at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:108) [patch$d_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) [patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:73) [patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:828) [patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1205]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[15:56:43] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.$ava:27) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.$ava:11) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<in$t>(CraftBlockEntityState.java:27) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:16) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:270) ~[patched_1.12.2.jar:git-Paper-1205]
        at org.bukkit.craftbukkit.v1_12_R1.CraftChunk.getTileEntities(CraftChunk.java:111) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:121) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:1) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:108) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) ~[patched_1.12.2.jar:git-Paper-1205]
        at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:73) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:828) ~[patched_1.12.2.jar:git-Paper-1205]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1205]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

### Plugin list:
None.

### Actions to reproduce (if known):

Signs with scoreboard/player data can result in a crash. Not worked out how to immediately cause a crash, but just having a sign with the following data in it will eventually (if not soon) cause a crash:

```
/blockdata ~ ~ ~ {Text1:"[\"\",{\"text\":\"Hours: \"},{\"score\":{\"name\":\"Hours\",\"objective\":\"Statistics\"}}]",Text2:"[\"\",{\"text\":\"Minutes: \"},{\"score\":{\"name\":\"Minutes\",\"objective\":\"Statistics\"}}]",Text3:"[\"\",{\"text\":\"Seconds \"},{\"score\":{\"name\":\"Seconds\",\"objective\":\"Statistics\"}}]",Text4:"[\"\",{\"text\":\"Ticks: \"},{\"score\":{\"name\":\"Ticks\",\"objective\":\"Statistics\"}}]"}
```

### Paper build number:
Paper version git-Paper-1206 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

# Other thoughts

I've not been able to reproduce the crash on Spigot, despite reapplying the blockdata repeatedly for several minutes and then leaving it running for several hours. Under Paper-1205 and 1206 it crashed within moments of adding the above to the sign, and again after some minutes the next few times I ran the server.

**Comment by kashike** [comment]
<sup>I've updated your description to fix the wrapping on the stacktraces.</sup>

**Comment by zedwick** [comment]
Ah, thanks. I hadn't even thought about that. (copied from a teeny terminal window)

**Comment by kashike** [comment]
Should be fixed with https://github.com/PaperMC/Paper/commit/60cdf86b8a1cbc059b36b4841443c714c30a70af.

**Comment by zedwick** [comment]
Thanks!

I still get

```
[22:56:25 ERROR]: Failed to load data for block entity minecraft:sign
java.lang.NullPointerException: null
        at net.minecraft.server.v1_12_R1.TileEntitySign$1.C_(TileEntitySign.java:63) ~[patched_1.12.2.jar:git-Paper-1207]
        at net.minecraft.server.v1_12_R1.ChatComponentScore.a(SourceFile:38) ~[patched_1.12.2.jar:git-Paper-1207]
        at net.minecraft.server.v1_12_R1.ChatComponentUtils.filterForDisplay(SourceFile:37) ~[patched_1.12.2.jar:git-Paper-1207]
        at net.minecraft.server.v1_12_R1.ChatComponentUtils.filterForDisplay(SourceFile:65) ~[patched_1.12.2.jar:git-Paper-1207]
        at net.minecraft.server.v1_12_R1.TileEntitySign.load(TileEntitySign.java:90) ~[patched_1.12.2.jar:git-Paper-1207]
        at net.minecraft.server.v1_12_R1.TileEntity.create(TileEntity.java:90) [patched_1.12.2.jar:git-Paper-1207]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:49) [patched_1.12.2.jar:git-Paper-1207]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) [patched_1.12.2.jar:git-Paper-1207]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:16) [patched_1.12.2.jar:git-Paper-1207]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:270) [patched_1.12.2.jar:git-Paper-1207]
        at org.bukkit.craftbukkit.v1_12_R1.CraftChunk.getTileEntities(CraftChunk.java:111) [patched_1.12.2.jar:git-Paper-1207]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:121) [patched_1.12.2.jar:git-Paper-1207]
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:1) [patched_1.12.2.jar:git-Paper-1207]
        at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:108) [patched_1.12.2.jar:git-Paper-1207]
        at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) [patched_1.12.2.jar:git-Paper-1207]
        at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:73) [patched_1.12.2.jar:git-Paper-1207]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:828) [patched_1.12.2.jar:git-Paper-1207]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
 [patched_1.12.2.jar:git-Paper-1207]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

in console, but no crash!
