### ISSUE TITLE
jline MouseTracking ?

### ISSUE THREAD

**Issue by khlfkk** [PaperMC/Paper#894]
It is random then the screen session is fail to reattach .

# Crash, Stacktrace

### Link/paste of stack trace

[13:41:45 WARN]: Exception in thread "Server console handler" java.lang.NoClassDefFoundError: org/jline/terminal/Terminal$MouseTracking
[13:41:45 WARN]:        at org.jline.reader.impl.LineReaderImpl.cleanup(LineReaderImpl.java:2248)
[13:41:45 WARN]:        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:589)
[13:41:45 WARN]:        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:390)
[13:41:45 WARN]:        at com.destroystokyo.paper.console.TerminalHandler.handleCommands(TerminalHandler.java:36)
[13:41:45 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer$2.run(DedicatedServer.java:77)
[13:41:45 WARN]: Caused by: java.lang.ClassNotFoundException: org.jline.terminal.Terminal$MouseTracking
[13:41:45 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[13:41:45 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:41:45 WARN]:        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
[13:41:45 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:41:45 WARN]:        ... 5 more

**Comment by stephan-gh** [comment]
I've seen this error before, but only after I replaced the Paper JAR while the server was still running. Does that happen every time you start the server?

**Comment by khlfkk** [comment]
Hello Minecrell, thanks for reply.
nope, when your server is running for couple of hours then when you stop the server it will show that.

**Comment by electronicboy** [comment]
How are you running the server? shared host, vps/dedi? are you running the latest version?

bearing in mind that starting any servers in a way which the cached jar could be updated, e.g. replacing the paperclip jar and running it to create a new updated jar in the cache folder, could create such an issue as the JVM would no longer be able to read the contents of the jar (and would thus for a class not found while tryna look for that class)

I really do not see how this could happen beyond plugins doing not-so-nice things with the classpath, or replacing the jar on the disk while the server is running

**Comment by khlfkk** [comment]
Thanks, i think this build can solve this issue
https://github.com/PaperMC/Paper/commit/1fd3be5bfab7674519d00961d708f0a562ecdbe3

**Comment by electronicboy** [comment]
completely unrelated
