### ISSUE TITLE
TerminalHandler: com.sun.jna.LastErrorException: [5] Input/output error

### ISSUE THREAD

**Issue by crysis992** [PaperMC/Paper#911]
Hello, 

This morning my server stopped responding after a world save with following error, no idea what it means or what caused it:

```[10:36:46] [Server thread/INFO]: Saving...
[10:36:46] [Server thread/INFO]: Saved the world
[10:36:47] [Server console handler/WARN]: Exception in thread "Server console handler" com.sun.jna.LastErrorException: [5] Input/output error
[10:36:47] [Server console handler/WARN]: 	at com.sun.jna.Native.invokeVoid(Native Method)
[10:36:47] [Server console handler/WARN]: 	at com.sun.jna.Function.invoke(Function.java:408)
[10:36:47] [Server console handler/WARN]: 	at com.sun.jna.Function.invoke(Function.java:354)
[10:36:47] [Server console handler/WARN]: 	at com.sun.jna.Library$Handler.invoke(Library.java:244)
[10:36:47] [Server console handler/WARN]: 	at com.sun.proxy.$Proxy18.tcgetattr(Unknown Source)
[10:36:47] [Server console handler/WARN]: 	at org.jline.terminal.impl.jna.linux.LinuxNativePty.setAttr(LinuxNativePty.java:84)
[10:36:47] [Server console handler/WARN]: 	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52)
[10:36:47] [Server console handler/WARN]: 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:592)
[10:36:47] [Server console handler/WARN]: 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:390)
[10:36:47] [Server console handler/WARN]: 	at com.destroystokyo.paper.console.TerminalHandler.handleCommands(TerminalHandler.java:36)
[10:36:47] [Server console handler/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer$2.run(DedicatedServer.java:77)
[10:36:47] [SIGCONT handler/WARN]: Exception in thread "SIGCONT handler" com.sun.jna.LastErrorException: [5] Input/output error
[10:36:47] [SIGCONT handler/WARN]: 	at com.sun.jna.Native.invokeVoid(Native Method)
[10:36:47] [SIGCONT handler/WARN]: 	at com.sun.jna.Function.invoke(Function.java:408)```

Nothing more, that was the last entry of the logfile, no crash-report.

**Comment by stephan-gh** [comment]
Were you actually unable to join/play on the server or was only the console/log file broken?

**Comment by meyden92** [comment]
I was unable to join the server and console was not responding, had to kill the process and restart.

**Comment by stephan-gh** [comment]
Can you reproduce this in a reliable way or did it happen only once?

**Comment by meyden92** [comment]
Just happened once, and I have no idea what it caused or how to reproduce it.

**Comment by stephan-gh** [comment]
Well, let's keep this open for now to see if someone else runs into this error at some point. It's hard to tell what's causing it, and I'm not sure if we can actually do much against it.

The only thing we can fix here is that the server should freeze entirely when this happens, but it's hard to fix without having a way to reproduce this.

**Comment by electronicboy** [comment]
what software are you running your server in, e.g. screen? did it crash during a re/detatch? how are the saves scheduled, e.g. vanilla save, or a cron job?

**Comment by electronicboy** [comment]
Closing due to lack of information and inactivity.
