### ISSUE TITLE
Skip unload requests for chunks within keepSpawnLoaded

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#92]
no reason to even try to unload them.

ChunkProviderServer.queueUnload can get called when no players are in the world, ignoring keepSpawnLoaded rules, SPAMMING it for the spawn chunks.

**Comment by JugadorNinja** [comment]
this is what you mean:
`[10:00:14 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_60]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_60]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-531]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_9_R1.StructureGenerator.a(StructureGenerator.java:203) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.WorldGenStronghold.c(SourceFile:96) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.WorldGenStronghold.getNearestGeneratedFeature(SourceFile:58) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.ChunkProviderGenerate.findNearestMapFeature(ChunkProviderGenerate.java:422) ~[patched_1.9.jar:git-Paper-531]
        at org.bukkit.craftbukkit.v1_9_R1.generator.NormalChunkGenerator.findNearestMapFeature(NormalChunkGenerator.java:56) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.ChunkProviderServer.a(ChunkProviderServer.java:359) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.ItemEnderEye.a(SourceFile:82) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.ItemStack.a(ItemStack.java:238) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:385) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:960) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.9.jar:git-Paper-531]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.jar:git-Paper-531]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_60]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.jar:git-Paper-531]
        ... 5 more
`
