### ISSUE TITLE
Nether World Problem

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#93]
**When a player go to the nether world, server console show this:**

```
[17:37:19] [Paper - Lighting Thread/ERROR]: stopTiming called async for world_nether - syncChunkLoad - Data
[17:37:19] [Paper - Lighting Thread/WARN]: java.lang.Throwable
[17:37:19] [Paper - Lighting Thread/WARN]:  at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:52)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.loadChunk(ChunkProviderServer.java:221)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:167)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:146)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getOrCreateChunkFast(ChunkProviderServer.java:83)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAt(World.java:341)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAtWorldCoords(World.java:337)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getType(World.java:760)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.a(World.java:2276)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.c(World.java:2419)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World$6.run(World.java:2502)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.FutureTask.run(Unknown Source)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.lang.Thread.run(Unknown Source)
[17:37:19] [Paper - Lighting Thread/ERROR]: stopTiming called async for world_nether - chunkLoad - Post
[17:37:19] [Paper - Lighting Thread/WARN]: java.lang.Throwable
[17:37:19] [Paper - Lighting Thread/WARN]:  at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.Chunk.loadNearby(Chunk.java:981)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:212)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:146)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getOrCreateChunkFast(ChunkProviderServer.java:83)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAt(World.java:341)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAtWorldCoords(World.java:337)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getType(World.java:760)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.a(World.java:2276)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.c(World.java:2419)
[17:37:19] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World$6.run(World.java:2502)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.FutureTask.run(Unknown Source)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:37:19] [Paper - Lighting Thread/WARN]:  at java.lang.Thread.run(Unknown Source)
[17:37:20] [Paper - Lighting Thread/ERROR]: stopTiming called async for world_nether - syncChunkLoad - Data
[17:37:20] [Paper - Lighting Thread/WARN]: java.lang.Throwable
[17:37:20] [Paper - Lighting Thread/WARN]:  at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:52)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.loadChunk(ChunkProviderServer.java:221)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:167)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:146)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getOrCreateChunkFast(ChunkProviderServer.java:83)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAt(World.java:341)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAtWorldCoords(World.java:337)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getType(World.java:760)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.a(World.java:2276)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.c(World.java:2419)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World$6.run(World.java:2502)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.FutureTask.run(Unknown Source)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.lang.Thread.run(Unknown Source)
[17:37:20] [Paper - Lighting Thread/ERROR]: stopTiming called async for world_nether - syncChunkLoad - Data
[17:37:20] [Paper - Lighting Thread/WARN]: java.lang.Throwable
[17:37:20] [Paper - Lighting Thread/WARN]:  at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:52)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.loadChunk(ChunkProviderServer.java:221)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:167)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:146)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.ChunkProviderServer.getOrCreateChunkFast(ChunkProviderServer.java:83)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAt(World.java:341)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getChunkAtWorldCoords(World.java:337)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.getType(World.java:760)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.a(World.java:2276)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World.c(World.java:2419)
[17:37:20] [Paper - Lighting Thread/WARN]:  at net.minecraft.server.v1_9_R1.World$6.run(World.java:2502)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.FutureTask.run(Unknown Source)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:37:20] [Paper - Lighting Thread/WARN]:  at java.lang.Thread.run(Unknown Source)
```

What should I do? I think this is a bug.
Thanks!

**Comment by zachbr** [comment]
You need to update
