### ISSUE TITLE
FATAL Error - entity.CraftPlayer cannot be cast to net.minecraft.server.v1_12_R1.EntityPlayer

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#942]
Error:
```
27.11 11:05:39 [Server] FATAL Error executing task
27.11 11:05:39 [Server] INFO java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer cannot be cast to net.minecraft.server.v1_12_R1.EntityPlayer
27.11 11:05:39 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
27.11 11:05:39 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
27.11 11:05:39 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:47) [patched_1.12.2.jar:git-Paper-1265]
27.11 11:05:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1265]
27.11 11:05:39 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1265]
27.11 11:05:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1265]
27.11 11:05:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1265]
27.11 11:05:39 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
27.11 11:05:39 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer cannot be cast to net.minecraft.server.v1_12_R1.EntityPlayer
27.11 11:05:39 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.tabComplete(CraftServer.java:1644) ~[patched_1.12.2.jar:git-Paper-1265]
27.11 11:05:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.tabCompleteCommand(MinecraftServer.java:1223) ~[patched_1.12.2.jar:git-Paper-1265]
27.11 11:05:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.lambda$a$2(PlayerConnection.java:2319) ~[patched_1.12.2.jar:git-Paper-1265]
27.11 11:05:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
27.11 11:05:39 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
27.11 11:05:39 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1265]
27.11 11:05:39 [Server] INFO ... 5 more
```

### Description of issue:
I am not sure of the specific action that ties into this just yet. It seems to spam 3-6 times in waves (not constant).

### Plugin list:
- AAC, ProtocolLib, Shopkeepers, + about 50 others that have never caused issues and don't seem relevant.
- I have not added/updated any plugins in the period before the error started beside this plugin (https://www.spigotmc.org/resources/christmas-christmas-2017.15007/). Players(on my server) are not yet able to interact with any of the plugin features, so it seems irrelevant. 

### Paper build number:
1265 (just updated yesterday and the error has not been seen until just after update)

**Comment by bloggy** [comment]
I have the same issue I think:
https://hastebin.com/corikexuta.vbs

**Comment by electronicboy** [comment]
Should be fixed in https://ci.destroystokyo.com/job/PaperSpigot/1266/
