### ISSUE TITLE
NullPointerException at world load during start-up.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#95]
Upgraded to Paper 518 from build 502, now started to get this error at start-up when the world loads. Any possible fix? 

```
[07:55:05] [Server thread/INFO]: Preparing level "world"
[07:55:05] [Server thread/WARN]: java.lang.NullPointerException
[07:55:05] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.Village.a(Village.java:394)
[07:55:05] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PersistentVillage.a(SourceFile:215)
[07:55:05] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PersistentCollection.get(PersistentCollection.java:51)
[07:55:05] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.WorldServer.b(WorldServer.java:72)
[07:55:05] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:262)
[07:55:05] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273)
[07:55:05] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:564)
[07:55:05] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[07:55:05] [Server thread/INFO]: Preparing start region for level 0 (Seed: -1449982769329756960)
[07:55:06] [Server thread/INFO]: Preparing spawn area: 66%
[07:55:06] [Server thread/INFO]: Preparing start region for level 1 (Seed: -1449982769329756960)
[07:55:07] [Server thread/INFO]: Preparing start region for level 2 (Seed: -1449982769329756960)
```

**Comment by aikar** [comment]
Vanilla bug, your world must of got a village near spawn that triggered it. about to push fix.
