### ISSUE TITLE
Infrequent server crash when navigating world (NoSuchElementException)

### ISSUE THREAD

**Issue by Puremin0rez** [PaperMC/Paper#954]
# Crash, Stacktrace

### Link/paste of stack trace
https://pastebin.com/raw/9TupWD8M

### Plugin list:
WorldEdit, Vault, LuckPerms. Nothing else.

### Actions to reproduce (if known):
I honestly have no idea how to reproduce it besides me just flying around. It certainly occurs when loading / unloading chunks, I've never had it while sitting idle. Other then that, zero idea of what triggers it. I've had this crash twice in the past 4 weeks.

### Paper build number:
Paper version git-Paper-1271 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

# Suggestion
Paper should really have more Tacos <3

**Comment by aikar** [comment]
I've also seen this every once in 2 blue moons. I have no idea whats going on with it, as async access is only thing I can see but I don't know what could be doing that.

**Comment by electronicboy** [comment]
#923 I think this is the same issue but in the TreeSet; I think what's happening here is that any addition/removal operations between the sets can become inconsistent for the exact same reason as they did for the HashSet

**Comment by TNTUP** [comment]
Got a server crash related to NoSuchElementException here https://pastebin.com/LhW5Ufnf

I'll try updating Paper this night, I'm on 1975 (14 versions behind) and let you know if it occurs again

**Comment by GWServer** [comment]
[17:13:42 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 57, Size: 46
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:47) [spigot.jar:git-Spigot-bb614f8-360629e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-bb614f8-360629e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-bb614f8-360629e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-bb614f8-360629e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-bb614f8-360629e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IndexOutOfBoundsException: Index: 57, Size: 46
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_151]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.Container.getSlot(Container.java:110) ~[spigot.jar:git-Spigot-bb614f8-360629e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1771) ~[spigot.jar:git-Spigot-bb614f8-360629e]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Spigot-bb614f8-360629e]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-bb614f8-360629e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot.jar:git-Spigot-bb614f8-360629e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[spigot.jar:git-Spigot-bb614f8-360629e]
        ... 5 more

**Comment by Black-Hole** [comment]
@sergservis This has nothing to do with your issue: One of your players is sending a packet with an invalid slot id. This won't crash your server.

**Comment by Malachiel87** [comment]
Same here https://hastebin.com/eqofopahuz.md (creative server with plotsquared and WE)

**Comment by electronicboy** [comment]
@xion87 That's a completely different issue and is generally down to plugins modifying the world unsafely (i.e. not handling removing TEs from the chunks TE list when removing their relevant blocks from the world)

**Comment by SecretlyJealous** [comment]
Crash: https://pastebin.com/zcp2ts4D
Log: https://pastebin.com/XDZBqftv

**Comment by SecretlyJealous** [comment]
Crash: https://pastebin.com/Pep7f9Fh
Second Crash today: https://pastebin.com/GFPBbibv

Going to revert from build Paper-1416 to build Paper-1414 because I've never had the crashing this frequent.

**Comment by cakoyo** [comment]
I sew the same error on my Paper fork today, but paste to here for reference https://pastebin.com/VQFqA9AU

**Comment by Puremin0rez** [comment]
The only thing I've figured out is that it's significantly more likely to occur when the worlds view distance is set to default (10).

I lowered the problematic worlds view distance from 10 to 7 and I haven't had it in a solid 2-3 months now - versus the once a week I was getting this crash previously. I guess it makes sense, since less chunks are being unloaded and loaded at the same time.

Unfortunately I have zero reproduction methods. It's quite random.

**Comment by electronicboy** [comment]
I have a patch for this, but ultimately need somebody to test it on a server for any issues, not really had the ability to spin it up on a loaded server yet

**Comment by hafarooki** [comment]
@electronicboy me me me!

**Comment by Proximyst** [comment]
If this issue still persists after 2+ yrs of being inactive, please open a new issue.
