### ISSUE TITLE
server crash exception ticking world

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#955]
got this while using build 1275

```
[07:29:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:908) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1275]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IndexOutOfBoundsException: writerIndex(31019) + minWritableBytes(8) exceeds maxCapacity(31022): UnpooledHeapByteBuf(ridx: 0, widx: 31019, cap: 31022/31022)
    at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:276) ~[patched_1.12.2.jar:git-Paper-1275]
    at io.netty.buffer.AbstractByteBuf.writeLong(AbstractByteBuf.java:1014) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketDataSerializer.writeLong(PacketDataSerializer.java:840) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketDataSerializer.a(PacketDataSerializer.java:112) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.DataPaletteBlock.b(DataPaletteBlock.java:139) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.DataPaletteBlock.writeBlocks(DataPaletteBlock.java:125) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.a(PacketPlayOutMapChunk.java:146) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.writeChunk(PacketPlayOutMapChunk.java:135) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:46) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PlayerChunk.b(PlayerChunk.java:143) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:208) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:325) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:897) ~[patched_1.12.2.jar:git-Paper-1275]
    ... 4 more
[07:29:00] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.IndexOutOfBoundsException: writerIndex(31019) + minWritableBytes(8) exceeds maxCapacity(31022): UnpooledHeapByteBuf(ridx: 0, widx: 31019, cap: 31022/31022)
    at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:276) ~[patched_1.12.2.jar:git-Paper-1275]
    at io.netty.buffer.AbstractByteBuf.writeLong(AbstractByteBuf.java:1014) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketDataSerializer.writeLong(PacketDataSerializer.java:840) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketDataSerializer.a(PacketDataSerializer.java:112) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.DataPaletteBlock.b(DataPaletteBlock.java:139) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.DataPaletteBlock.writeBlocks(DataPaletteBlock.java:125) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.a(PacketPlayOutMapChunk.java:146) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.writeChunk(PacketPlayOutMapChunk.java:135) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:46) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PlayerChunk.b(PlayerChunk.java:143) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:208) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:325) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:897) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[patched_1.12.2.jar:git-Paper-1275]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1275]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by electronicboy** [comment]
Discussed on IRC, more than likely down to a chunk having a bit too much inside of it in terms of data.
