### ISSUE TITLE
NegativeArraySizeException crash

### ISSUE THREAD

**Issue by enlyow** [PaperMC/Paper#959]
### Description of issue:
Server crash with error: 

`Encountered an unexpected exception
java.lang.NegativeArraySizeException: null
	at org.bukkit.craftbukkit.v1_12_R1.CraftChunk.getTileEntities(CraftChunk.java:103) ~[spigot.jar:git-Paper-1268]
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:121) ~[spigot.jar:git-Paper-1268]
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:104) ~[spigot.jar:git-Paper-1268]
	at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:108) ~[spigot.jar:git-Paper-1268]
	at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) ~[spigot.jar:git-Paper-1268]
	at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:73) ~[spigot.jar:git-Paper-1268]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:828) ~[spigot.jar:git-Paper-1268]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-Paper-1268]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

### Paper build number:
This server is running Paper version git-Paper-1268 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugin list:
BlockSyntax, Cases, ChatEx, Citizens, CitizensCMD, ClearLag, CommandScheduler, DbPools, DynPad, Essentials, EssentialsSpawn, FastAsyncWorldEdit, HolographicDisplays, ItemFixer, JSGui, MessageFilter, NametagEdit, NoCheatPlus, PermissionsEx, ProtocolLib, ProtocolSupport, QExtraNames, Tasker, Vault, WCooldown, WorldEdit, WorldGuard

**Comment by enlyow** [comment]
Crash screenshot: http://prntscr.com/hrqfys/direct

**Comment by electronicboy** [comment]
Crashes in this area generally always end up being caused by plugins modifying the state of the server in an unsafe manner, I really have no idea what would cause the size of the tile entities map to be negative other than plugins modifying this async and breaking the data on the chunk.

**Comment by enlyow** [comment]
Could this be FastAsyncWorldEdit?

**Comment by electronicboy** [comment]
if it's placing/removing tile entities async then yes, it has the potential to be a causing factor.

**Comment by enlyow** [comment]
At least I have suspicions only on plugins: FastAsyncWorldEdit and Clearlagg. Do I need to wipe the map after that?

**Comment by aikar** [comment]
This is plugin caused, as there is absolutely no way for this to happen otherwise. Try contacting plugin authors once you figure it out, but im assuming this was a once in a blue moon crash
