### ISSUE TITLE
Multiple startup failures on 1287

### ISSUE THREAD

**Issue by 0XE4** [PaperMC/Paper#962]
# Incompatibility (Bug)

### What behaviour is expected:
Server starting with no errors.

### What behaviour is observed:
Multiple errors for plugins.

### Steps/models to reproduce:
Start the server with 1287 instead of 1286.

### Paper build number:
    This server is running Paper version git-Paper-1287 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

# Crash, Stacktrace

### Link/paste of stack trace

```
[15:21:01 ERROR]: Could not load 'plugins/LoginMSG-1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [patched_1.12.2.jar:git-Paper-1287]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1287]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1287]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at java.net.URLClassLoader.definePackage(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1287]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1287]
        ... 6 more
[15:21:01 ERROR]: Could not load 'plugins/RandomSpawn.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [patched_1.12.2.jar:git-Paper-1287]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1287]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1287]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at java.net.URLClassLoader.definePackage(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1287]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1287]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1287]
        ... 6 more

```

Related to yesterday's commit for Bukkit: PluginClassLoader changes ?

**Comment by electronicboy** [comment]
https://ci.destroystokyo.com/job/PaperSpigot/1288 Looks like bukkit noticed their problem and apparently fixed it

**Comment by zachbr** [comment]
Fixed upstream with https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/20971610daa5cbe1685ac9ba0fa93525e7158048

**Comment by 0XE4** [comment]
Thank you both
