### ISSUE TITLE
ClassCastException.  TileEntityShulkerBox can not be casted to TileEntityCommand

### ISSUE THREAD

**Issue by Leymooo** [PaperMC/Paper#970]
https://pastebin.com/njBJPhg3

Maybe a FAWE make somethink wrong with TE, but i think it can be fixed in Paper.

**Comment by Black-Hole** [comment]
No, FAWE have to fix this. Messing with tile entities concurrently will cause a lot of problems, like https://github.com/PaperMC/Paper/issues/968

**Comment by Leymooo** [comment]
Maybe there is missing TE fix in WorldServer?
```[11:48:11] [Server thread/ERROR]: Block at 5,081,57,-1,598 is ENDER_CHEST but has net.minecraft.server.v1_12_R1.TileEntityShulkerBox@81a2a9a. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[11:48:11] [Server thread/ERROR]: Block at 5,082,57,-1,598 is ENDER_CHEST but has net.minecraft.server.v1_12_R1.TileEntityShulkerBox@7932c9bc. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[11:48:11] [Server thread/ERROR]: Block at 5,083,57,-1,598 is ENDER_CHEST but has net.minecraft.server.v1_12_R1.TileEntityShulkerBox@3f234979. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[11:48:11] [Server thread/ERROR]: Block at 5,080,57,-1,594 is ENDER_CHEST but has net.minecraft.server.v1_12_R1.TileEntityShulkerBox@570edf93. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[11:48:11] [Server thread/ERROR]: Block at 5,084,57,-1,598 is ENDER_CHEST but has net.minecraft.server.v1_12_R1.TileEntityShulkerBox@389e93e7. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[11:48:11] [Server thread/ERROR]: Block at 5,081,57,-1,594 is ENDER_CHEST but has net.minecraft.server.v1_12_R1.TileEntityShulkerBox@7965b7a2. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[11:48:11] [Server thread/ERROR]: Block at 5,085,57,-1,598 is ENDER_CHEST but has net.minecraft.server.v1_12_R1.TileEntityShulkerBox@5c285176. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[11:48:11] [Server thread/ERROR]: Block at 5,082,57,-1,594 is ENDER_CHEST but has net.minecraft.server.v1_12_R1.TileEntityShulkerBox@7d7bef27. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[11:48:11] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: Cannot cast net.minecraft.server.v1_12_R1.TileEntityShulkerBox to net.minecraft.server.v1_12_R1.TileEntityCommand```

**Comment by electronicboy** [comment]
This won't be fixed in paper, the fact that this exception is occurring means that there is an inconsistency between the block in the world and the tile entity in its place or the fact that it's being replaced after this check has occurred.

the API ensures that such state violations cannot occur, we cannot fix plugins doing horrible things to the state of the server when they avoid the API and modify the chunks themselves directly. It's not viable for paper to fix this, especially in cases where this can be caused easily by race conditions, where the server already does the relevant checks.

plugins should NOT be doing this kind of work async, and they should NOT be leaving the state of the server in such a state.

**Comment by electronicboy** [comment]
The relevant fix for that issue is already in the server, that's more than likely a race condition caused by some plugin changing the block between the check and the creation of the state.

**Comment by Leymooo** [comment]
Okey. Thanks for reply!

**Comment by Leymooo** [comment]
I have a one more question, why it continue crashes server after restart?
```
[14:15:53] [Async Chat Thread - #0/INFO]: Ⓖ [HABALHblE] (Креатив) mr_syslik: продаю дом недорого!
[14:15:53] [Server thread/INFO]: frediDimon issued server command: /menu
[14:15:54] [Server thread/INFO]: _I_L_U_X_A_ issued server command: /rg i
[14:15:54] [Async Chat Thread - #0/INFO]: Ⓖ [§LПолиция] ⊰Владелец⊱ dedywka: +
[14:15:55] [Server thread/INFO]: frediDimon lost connection: Disconnected
[14:15:56] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: Cannot cast net.minecraft.server.v1_12_R1.TileEntityShulkerBox to net.minecraft.server.v1_12_R1.TileEntityCommand
	at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_151]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:23) ~[patched_1.12.2.jar:git-Paper-1300]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftCommandBlock.<init>(CraftCommandBlock.java:14) ~[patched_1.12.2.jar:git-Paper-1300]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState0(CraftBlock.java:313) ~[patched_1.12.2.jar:git-Paper-1300]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:272) ~[patched_1.12.2.jar:git-Paper-1300]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:266) ~[patched_1.12.2.jar:git-Paper-1300]
	at org.bukkit.craftbukkit.v1_12_R1.CraftChunk.getTileEntities(CraftChunk.java:111) ~[patched_1.12.2.jar:git-Paper-1300]
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:121) ~[patched_1.12.2.jar:git-Paper-1300]
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:104) ~[patched_1.12.2.jar:git-Paper-1300]
	at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:108) ~[patched_1.12.2.jar:git-Paper-1300]
	at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:104) ~[patched_1.12.2.jar:git-Paper-1300]
	at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:73) ~[patched_1.12.2.jar:git-Paper-1300]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:828) ~[patched_1.12.2.jar:git-Paper-1300]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1300]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[14:15:56] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/Surv/./crash-reports/crash-2018-01-12_14.15.56-server.txt
[14:15:56] [Server thread/INFO]: Stopping server
```
I have a about ~35 crashes in some hours.

**Comment by MiniDigger** [comment]
because most likely your world got saved with an invalid state.

**Comment by Leymooo** [comment]
But why fixTileEntity in WorldServer does not try to fix this TE?

**Comment by electronicboy** [comment]
Because the server ensures that such a violation cannot occur by not allowing it to occur in the first place, thus it's not needed to check such a thing when a chunk is loaded.

The server doesn't expect that something is going to throw the server into such a state, the fixTileEntity method is basically only used by CraftBukkit (and was added by craftbukkit), if nothing touches the block in a way that ends up calling that, it won't ever consider the potential of fixing the TE.

Having a look, it would technically be possible to call that method everytime a TE is loaded, but that is not a fix for an issue, that's a workaround for your server being placed into such a horrible state in the first place, nor am I fond of increasing the load of chunk loading to workaround the fact that people are installing such horrible plugins on their servers in the first place.

**Comment by Leymooo** [comment]
Our players have access to WE in theris WG regions. Using only WE is not good, because WE blocks main thread. FAWE is good for this, but causes this issues. I will hope that developer will fix this issues.
