### ISSUE TITLE
PaperCrash

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#973]
[crash-2018-01-15_16.20.04-server.txt](https://github.com/PaperMC/Paper/files/1633033/crash-2018-01-15_16.20.04-server.txt)

We're getting this crash a lot now, latest PaperSpigot. Just lags out then this happens. No errors in console.

plugins:  https://i.gyazo.com/3e885c52bc6da953aa3ec30cd7584fdc.png

Only just start to happen today after we updated to latest version.

**Comment by aikar** [comment]
```Time: 1/15/18 4:20 PM
Description: Exception ticking world

java.lang.NullPointerException: Type may not be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
        at com.destroystokyo.paper.event.entity.PreCreatureSpawnEvent.<init>(PreCreatureSpawnEvent.java:27)
        at net.minecraft.server.v1_12_R1.SpawnerCreature.a(SpawnerCreature.java:200)
        at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:295)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:897)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
        at java.lang.Thread.run(Thread.java:748)

```

Relates to the recent event. Some how your getting a monster spawn that does not appear to be registered in the type map (not registered).

Does that pet plugin make pets spawn naturally in the world?

**Comment by Cobwebster** [comment]
The pet block plugin https://www.spigotmc.org/resources/petblocks-mysql-bungeecord-customizeable-gui-1-8-1-9-1-10-1-11-1-12.12056/ doesn't use mod-spawners no.

Its a creative server so we have disabled mob-spawning. We disable spawning via worldguard, i believe grief prevention also has something.

**Comment by aikar** [comment]
i didnt even see that one, i meant the mini pets. i was wondering if they are inserting custom mobs into NMS to spawn.

**Comment by Cobwebster** [comment]
yeah probably for sure. we've downgraded to the paperclip version we were before for now.

**Comment by Cobwebster** [comment]
Is there anything that can be done paper side to prevent this from crashing us out? Or do we need to just assume its that plugin and msg the dev?

**Comment by aikar** [comment]
Yes, we will fix it to not crash and print a warning when thus occurs as soon as we can
