### ISSUE TITLE
Fill Profile Property Events patch breaks Citizens from setting npc skin data.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#997]
Citizens dev 1498
http://ci.citizensnpcs.co/job/Citizens2/
Paper dev 1310

@zachbr @aikar This commit / patch https://github.com/PaperMC/Paper/commit/5b72a03bcf0f5f3d31cd6fe393b883dbbcd5e1fa seems to break skin lookup for various plugins. Instead of allowing plugins to populate profile properties from local sources, it seems to require it and doesn't throw out the necessary calls / lookups to the Mojang API like before. In my case, setting a Citizens npc skin via ```/npc skin <name>```, the npc skin does not update or display whatsoever. 

Downgrading to Paper dev 1309 (without the commit), npc skins properly get set and updated.

**Comment by aikar** [comment]
This is something the plugin is going to need to resolve. It is caused by the plugin manually implementing the fill profile properties activity itself, instead of letting the games code handle it.

https://github.com/CitizensDev/Citizens2/blob/master/v1_12_R1/src/main/java/net/citizensnpcs/nms/v1_12_R1/util/NMSImpl.java#L286

I have no idea why they are doing that, but they should just let mojangs code handle it.

Though from what I see, i'm not even sure they are reaching our event fire, as they are calling into their own fill method.

If the author(s) of Citizens can suggest ways to improve, i'm open to it.

Though one thing I can see I can improve is instead of looking for empty textures, look for .isComplete() in case someone inserts a non textures property, in case that is whats causing what you see.

**Comment by mibby** [comment]
@fullwall / @mcmonkey4eva ^

@aikar So it is not possible to keep compatibility with older plugins and plugins that may not be in active development which call a fillProfileProperties manually? I believe there are some head database plugins that possibly invoke a skin lookup the same way as well. Assuming it is done to keep compatibility of the plugin functions all the way down to spigot 1.8 and if spigot doesn't have any method to call for skins directly.

**Comment by aikar** [comment]
@mibby its not all plugins, its just Citizens that's doing this, thats their own code.

Anything that calls mojangs .fillProfileProperties would route through this event just fine.

I've studied this code and Citizens and can not find anything wrong on Papers side. There must be some odd detail on the citizens side causing this, but im perplexed that this commit itself seems to relate for you considering the Citizens code isn't even reaching the code I changed / the event.

Unless you're somehow not using the 1_12 NMS wrapper I linked above and its using different logic than what I just looked at.

I can't see why things wouldnt work anyways with the current Citizens code, as it looks up the profile, 

https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/profile/ProfileFetcher.java
Which will go intro WrappedGameProfileRepository for the other event, but its call to NMS.fillProfile doesn't call WrappedMinecraftSessionService, it just reimplements the logic.

Result is used here
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/skin/Skin.java

Which should be a profile with textures.

Can you verify this again mibby? maybe you just got rate limited...

**Comment by aikar** [comment]
I found the issue with debug enabled:

```
[22:10:04 INFO]: Profile lookup for player 'Foo' failed: com.destroystokyo.paper.profile.WrappedMinecraftSessionService cannot be cast to com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService false
[22:10:04 INFO]: java.lang.ClassCastException: com.destroystokyo.paper.profile.WrappedMinecraftSessionService cannot be cast to com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.fillProfileProperties(NMSImpl.java:292)
        at net.citizensnpcs.util.NMS.fillProfileProperties(NMS.java:60)
        at net.citizensnpcs.npc.profile.ProfileFetcher$1.onProfileLookupSucceeded(ProfileFetcher.java:81)
        at com.destroystokyo.paper.profile.WrappedGameProfileRepository$PreProfileLookupCallback.onProfileLookupSucceeded(WrappedGameProfileRepository.java:62)
        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:63)
        at com.destroystokyo.paper.profile.WrappedGameProfileRepository.findProfilesByNames(WrappedGameProfileRepository.java:47)
        at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48)
        at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by aikar** [comment]
@fullwall / @mcmonkey4eva Can you please use the interface instead of force expecting Yggdrasril

Also can you please relay the .fillProfileProperties method to the MinecraftSessionService instead of re-implementing that logic, which breaks our event.

**Comment by aikar** [comment]
Opened issue on Citizens Issue Tracker, closing as this is plugin caused.

**Comment by mibby** [comment]
@aikar 
> closing as this is plugin caused.

So is there nothing I can do in the meantime but keep my Paper version downgraded until / if Citizens gets updated to use the proper interface? That could be a while since Citizens doesn't seem to be in any form of active development and only breaking with Paper. :(

**Comment by aikar** [comment]
@mibby I can't recall if you are a developer or not, but fixing Citizens is pretty trivial. I don't have the time to do it myself though.

But looks like Citizens is receiving some development in the last month.

**Comment by mibby** [comment]
@aikar I do light development but wouldn't really know where to begin with reworking how Citizens fetches skins.

Citizens only received 1 commit in the last month. Prior to that, 2 commits 4 months ago. There are some breaking issues with npcs not spawning and skins disappearing client-side I reported more than a half a year ago, so as far as I'm aware, development is currently on hiatus.

**Comment by mcmonkey4eva** [comment]
Our lead developer on Citizens (fullwall) who's best able to handle weird internal issues is very busy with offline things. He checks in from time to time to fix what is reasonably fixable and give input on unclear issues. There's not much development going on not only for that reason but also because the majority of issues with Citizens are in one of two categories:
Minor and/or external issues that are a matter of helping the user or a conflicting plugin's developer resolve, and
important but very intricate issues like the skin system imperfections caused by the MC 1.7.6 skin backend rewrite. These are issues that would take an incredible amount of focused effort to have a hope of finding good stable ways to improve things... which will generally be a fairly minor improvement compared to the scale of effort needed to achieve it cleanly.

I'll notify him of this issue as a priority and hopefully he'll be able to address it when he's on next.

**Comment by aikar** [comment]
@mcmonkey4eva this can be fixed by changing the Yggdrasil cast to simply be theMinecraftSessionService interface instead.

that is the line causing the break.

The other issue I mentioned only impacts people who are going to use the new paper events, they will simply not see the texture fill events for citizen npc's

**Comment by mcmonkey4eva** [comment]
Would this attempt from earlier today suffice? https://github.com/CitizensDev/Citizens2/commit/c767b6fdc3c9f20f95d1f170983e4f81bd16de0e
If not, could you reply over at https://github.com/CitizensDev/Citizens2/issues/1392

**Comment by mibby** [comment]
@mcmonkey4eva That commit does seem to resolve the issue for me. Skins can be set again with the latest Paper. But I do seem to get hit with a rate limit on restarts during initialization with only a handful of npcs. 

```
[00:06:13] [Craft Scheduler Thread - 19/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@14557c0c[id=5a209a28-fe31-4ab9-bd2b-795767e2a115,name=player,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [patched_1.12.2.jar:git-Paper-1320]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [patched_1.12.2.jar:git-Paper-1320]
	at com.destroystokyo.paper.profile.WrappedMinecraftSessionService.fillProfileProperties(WrappedMinecraftSessionService.java:67) [patched_1.12.2.jar:git-Paper-1320]
	at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.fillProfileProperties(NMSImpl.java:292) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.util.NMS.fillProfileProperties(NMS.java:60) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.npc.profile.ProfileFetcher$1.onProfileLookupSucceeded(ProfileFetcher.java:81) [citizens-2.0.22-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.profile.WrappedGameProfileRepository$PreProfileLookupCallback.onProfileLookupSucceeded(WrappedGameProfileRepository.java:62) [patched_1.12.2.jar:git-Paper-1320]
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:63) [patched_1.12.2.jar:git-Paper-1320]
	at com.destroystokyo.paper.profile.WrappedGameProfileRepository.findProfilesByNames(WrappedGameProfileRepository.java:47) [patched_1.12.2.jar:git-Paper-1320]
	at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121) [citizens-2.0.22-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1320]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1320]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[00:06:13] [Craft Scheduler Thread - 19/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@196faa3f[id=0f3b8c34-b3da-4cb3-9a00-25ea6b0c3f2e,name=player,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [patched_1.12.2.jar:git-Paper-1320]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [patched_1.12.2.jar:git-Paper-1320]
	at com.destroystokyo.paper.profile.WrappedMinecraftSessionService.fillProfileProperties(WrappedMinecraftSessionService.java:67) [patched_1.12.2.jar:git-Paper-1320]
	at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.fillProfileProperties(NMSImpl.java:292) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.util.NMS.fillProfileProperties(NMS.java:60) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.npc.profile.ProfileFetcher$1.onProfileLookupSucceeded(ProfileFetcher.java:81) [citizens-2.0.22-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.profile.WrappedGameProfileRepository$PreProfileLookupCallback.onProfileLookupSucceeded(WrappedGameProfileRepository.java:62) [patched_1.12.2.jar:git-Paper-1320]
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:63) [patched_1.12.2.jar:git-Paper-1320]
	at com.destroystokyo.paper.profile.WrappedGameProfileRepository.findProfilesByNames(WrappedGameProfileRepository.java:47) [patched_1.12.2.jar:git-Paper-1320]
	at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121) [citizens-2.0.22-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1320]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1320]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by aikar** [comment]
@mibby  @mcmonkey4eva this is due to how the 'fix' was applied, which wasn't really ideal.

Ideally, the change shouldnt have checked instanceof.

It should of just been dropped to the interface, then let the authentication service be casted (And ideally, the auth service should move to interface too, but less needed here)

keeping with the existing logic would prob be fine for people to be missing our new events, theyd only be missing it purely for npc's, which you likely will want to control through citizens logic anyways.
